### PR TITLE
First time retention 

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- reimplemented after consolidation
*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by EDsCODE** [comment]
discovered small bug #2327 will address separately

**Review by timgl — COMMENTED** [review]
I'm not sure I fully understand the difference between recurring:
image

And first time:
image

Feels like that 25% for first time shouldn't be there? I could be wrong

UX wise, I'd be awesome to have an explanation of the difference between first time and recurring in the interface.

I also think it'd look nicer to use radio buttons rather than a dropdown.

**Review by paolodamico — CHANGES_REQUESTED** [review]
A few comments UX-wise:

- I think it might be confusing to have the first-time/recurring selector as retention type because retention type will probably be the selection between N-day and unbounded/rolling (#2220 for context). I would put this option next to the cohortizing event.
- Maybe change names to "Retention/target" event and "Cohortizing" event?
- I think having separate cohortizing and target events for recurring retention makes sense too (e.g. if I want to know from the users that opened a dashboard each week, what was the retention on creating actions).
- In general I would change the "Users" column to "Cohort Size".
    - Would be pretty cool if this column had an info icon with a tooltip that provides a bit more context based on the type of cohortizing event (e.g. for first time retention you would want to emphasize that these are users that did the cohortizing event for the first time ever).

Regarding functionality (might be easier to jump on a call to work through this together, lmk),
- Daily retention seems to work as expected (both cases) 🥳 
- I found this case in which when doing weekly retention (either case), opening the list of users shows that they're not retained but they should at least be retained on Period 0 (and based on the `$pageview` action they should indeed be retained for longer).
    image
- See this case of weekly first time retention (3 screenshots below), think I found a few issues.
    1. Same user (`fake@posthog.com`) is on cohort Oct 25 & Nov 1, leaving aside that this is supposed to be a "once in a lifetime" event, in first time retention no single user should be in two cohorts in this retention mode.
    1. Users don't show any retention on the individual users view.
    1. The retention event is `$pageview`, the user `fake@posthog.com` whose first event was on week of Oct 25 should show as retained for Week 1 of that cohort.

**Comment by EDsCODE** [comment]
> I'm not sure I fully understand the difference between recurring:
> image
> 
> And first time:
> image
> 
> Feels like that 25% for first time shouldn't be there? I could be wrong
> 
> UX wise, I'd be awesome to have an explanation of the difference between first time and recurring in the interface.
> 
> I also think it'd look nicer to use radio buttons rather than a dropdown.

@timgl That should be correct until we decide to use rolling retention. First time retention is the same as recurring retention except that later events won't be considered in a row unless they're new unique people based on the first event. So, in first time retention, the 25% you're seeing is that 1 person of the 4 (new people) came back. But you won't see them on nov 11 like you do with recurring because they're not new anymore. 

Definitely working to add supplemental information

**Comment by EDsCODE** [comment]
> A few comments UX-wise:
> 
> * I think it might be confusing to have the first-time/recurring selector as retention type because retention type will probably be the selection between N-day and unbounded/rolling (#2220 for context). I would put this option next to the cohortizing event.
> * Maybe change names to "Retention/target" event and "Cohortizing" event?
> * I think having separate cohortizing and target events for recurring retention makes sense too (e.g. if I want to know from the users that opened a dashboard each week, what was the retention on creating actions).
> * In general I would change the "Users" column to "Cohort Size".
>   
>   * Would be pretty cool if this column had an info icon with a tooltip that provides a bit more context based on the type of cohortizing event (e.g. for first time retention you would want to emphasize that these are users that did the cohortizing event for the first time ever).
> 
> Regarding functionality (might be easier to jump on a call to work through this together, lmk),
> 
> * Daily retention seems to work as expected (both cases) 🥳
> * I found this case in which when doing weekly retention (either case), opening the list of users shows that they're not retained but they should at least be retained on Period 0 (and based on the `$pageview` action they should indeed be retained for longer).
>   image
> * See this case of weekly first time retention (3 screenshots below), think I found a few issues.
>   
>   1. Same user (`fake@posthog.com`) is on cohort Oct 25 & Nov 1, leaving aside that this is supposed to be a "once in a lifetime" event, in first time retention no single user should be in two cohorts in this retention mode.
>   2. Users don't show any retention on the individual users view.
>   3. The retention event is `$pageview`, the user `fake@posthog.com` whose first event was on week of Oct 25 should show as retained for Week 1 of that cohort.
>   
>     
>     
>     

Thanks for the QA. let me look through these problems and if something is a big blocker we can call

**Comment by EDsCODE** [comment]
@paolodamico 
- fixed the person issue it was with caching 
- made the changes to the naming as you suggested
- added tooltips with descriptions. feel free to suggest changes to the copy i think it could be even clearer
- i'm leaving rolling retention option out of it for now. We can do it as a followup to add in the recurring/rolling retention options

lmk what you think!

**Review by paolodamico — APPROVED** [review]
Everything seems to be working now! _Disclaimer: I only reviewed with test data on a local instance and with Postgres, we'll have to continue testing with production data and CH._

I'll make a few suggestion improvements to the UX.

**Comment by paolodamico** [comment]
@EDsCODE please review #2346 with UX improvements before merging this branch. It would require enabling recurring retention with different cohortizing & retaining events, but I do think it provides a cleaner experience. Keep me posted!

**Pull request merged**
