### PR TITLE
chore: update msw to 0.47.3

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

MSW is not at version 0.47.3 but version 0.47.3 is available

## Changes

updates to version 0.47.3

## How did you test this code?

running the tests

### CODE REVIEW

**Comment by mariusandra** [comment]
so a no-op? :D 

image

**Comment by mariusandra** [comment]
ignore me... I guess I forgot how to read with the sun shining in my eye... thought I saw `from X to X`

**Comment by pauldambra** [comment]
> ignore me... I guess I forgot how to read with the sun shining in my eye... thought I saw from X to X

I've not had much sleep. For a second I believed you 🤣

**Comment by mariusandra** [comment]
homer bush

**Pull request merged**
