### PR TITLE
fix(data-warehouse): Use distinct_id field if present

### LINKED ISSUE #26631: "Distinct ID field" prefilled with "id" field
## Bug description

I have a `distinct_id` field in my data warehouse table but this field is not used in order to prefill "Distinct ID field".

image

"Distinct ID field" is prefilled with "id" field. However, "id" doesn't corrspond to a user unique identifier, it corresponds to a row unique identifier, and so I really don't want "id" to be used for "Distinct ID field".

So each time I need to change "Distinct ID field" to use the field "distinct_id" of my table. This is **very cumbersome and error prone**. I have maybe 20 different insights where I need to change each time the "Distinct ID field".

### PR DESCRIPTION
**Pull request by lcswillems**
## Problem

I have a `distinct_id` field in my data warehouse table but this field is not used in order to prefill "Distinct ID field".

image

"Distinct ID field" is prefilled with "id" field. However, "id" doesn't corrspond to a user unique identifier, it corresponds to a row unique identifier, and so I really don't want "id" to be used for "Distinct ID field".

So each time I need to change "Distinct ID field" to use the field "distinct_id" of my table. This is **very cumbersome and error prone**. I have maybe 20 different insights where I need to change each time the "Distinct ID field".

Closes https://github.com/PostHog/posthog/issues/26631

## Changes

Use "distinct_id" field as a default for "Distinct ID field". And if it doesn't exist, falls back to "id". 

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

I didn't test.

### CODE REVIEW

**Comment by lcswillems** [comment]
@Twixes I've tried to be way more precise in the issue and description of the PR. Is there anything more I should do?

Also, do you have an idea how fast this PR could be reviewed? This is very cumbersome and error-prone, and the PR should be very straightfoward.

**Review by Gilbert09 — APPROVED** [review]

**Comment by Gilbert09** [comment]
> @Twixes I've tried to be way more precise in the issue and description of the PR. Is there anything more I should do?
> 
> Also, do you have an idea how fast this PR could be reviewed? This is very cumbersome and error-prone, and the PR should be very straightforward.

Thanks for adding this in! I've approved the CI checks, once they all pass I'll get this merged in

**Comment by lcswillems** [comment]
@Gilbert09 Thanks for the review! I've fixed the formatting. However, there is a Cypress test failing but I've no clue how to reproduce it locally and the CI only runs when you trigger it. How could I help fixing the last failing job?

**Comment by lcswillems** [comment]
@Gilbert09 It seems that all the checks have passed! :partying_face:

**Comment by lcswillems** [comment]
@Gilbert09 Thank you very much for the fast review and the merge! Do you have an idea when this fix should go in production?

**Comment by Gilbert09** [comment]
> @Gilbert09 Thank you very much for the fast review and the merge! Do you have an idea when this fix should go in production?

@lcswillems It went live about 10 mins ago 🥳

**Comment by lcswillems** [comment]
@Gilbert09 Indeed! :heart: Thank you so much for the responsiveness!! 

image

**Comment by lcswillems** [comment]
@Gilbert09 My 2nd biggest issue I encountered using PostHog (and I've used a ton of functionalities already, the product is insane!!) is this one:

https://github.com/PostHog/posthog/issues/5196

In my case, I capture `transaction_sent` event, `transaction_succeeded` event and `transaction_failed` event. And I want to display in a piechart those 3 metrics:

- `count(transaction_succeeded) / count(transaction_sent)`
- `count(transaction_failed) / count(transaction_sent)`
- `( count(transaction_sent) - count(transaction_succeeded) - count(transaction_failed) ) / count(transaction_sent)`

But it is completely impossible at the moment. The best alternative I've found so far is using a funnel `transaction_sent > transaction_succeeded` but it is a workaround, not what I would really want.

Is there something special I could do in order to help getting it prioritized? I've seen a lot of people complaining about it and it would be a big improvement for PostHog to my opinion.

**Comment by Gilbert09** [comment]
> @Gilbert09 My 2nd biggest issue I encountered using PostHog (and I've used a ton of functionalities already, the product is insane!!) is this one:
> 
> #5196
> 
> In my case, I capture `transaction_sent` event, `transaction_succeeded` event and `transaction_failed` event. And I want to display in a piechart those 3 metrics:
> 
> * `count(transaction_succeeded) / count(transaction_sent)`
> * `count(transaction_failed) / count(transaction_sent)`
> * `( count(transaction_sent) - count(transaction_succeeded) - count(transaction_failed) ) / count(transaction_sent)`
> 
> But it is completely impossible at the moment. The best alternative I've found so far is using a funnel `transaction_sent > transaction_succeeded` but it is a workaround, not what I would really want.
> 
> Is there something special I could do in order to help getting it prioritized? I've seen a lot of people complaining about it and it would be a big improvement for PostHog to my opinion.

@lcswillems I'd recommend creating a feature request issue in https://github.com/posthog/posthog for this - then someone will prioritise getting it built

**Pull request merged**
