### PR TITLE
Use insight short ID in `insightLogic` key also on the insight page (again)

### PR DESCRIPTION
**Pull request by Twixes**
#8613 had to be reverted because of the logic in fact _not working_ on the insight page (PostHog/posthog#8631 – [Slack thread](https://posthog.slack.com/archives/C01G8S5T08Z/p1645012416744849)). 🤔 Will resolve this here and get the fix merged again.

### CODE REVIEW

**Comment by mariusandra** [comment]
Something's still broken :/

**Comment by Twixes** [comment]
This crap passes locally, I don't know what it wants.

**Comment by mariusandra** [comment]
If `/new` is the problem ([like you said on Slack](https://posthog.slack.com/archives/C01G8S5T08Z/p1645115575764899?thread_ts=1645112953.646969&cid=C01G8S5T08Z)), we could simplify this a lot by moving the "new insight" code with its redirect directly into the `InsightRouter` scene. It'll be less pretty (skeleton screen while redirecting), but it'll at least be more reliable. WDYT?

**Comment by Twixes** [comment]
That by itself wouldn't fix the bug, but it would definitely unlock the keying change that would then unlock resolving this particular bug and similar ones around the insight view/edit page.

**Pull request closed without merging**
