### PR TITLE
revert(recordings): use cooperative-sticky rebalance strategy

### PR DESCRIPTION
**Pull request by hazzadous**
For some reason some partitions aren't being consumed. So I'll simply revert this for now. We should, errrm, make it configurable next time, promise.

Reverts PostHog/posthog#15197

### CODE REVIEW

**Review by xvello — APPROVED** [review]

**Comment by pauldambra** [comment]
I'm about 70% sure that even only setting `rebalance_cb: true` means we need to implement assignment behaviour in the callback we provide.

(I think we even have to seek the appropriate offset on the partition ourselves - but haven't figured out a good way to test/debug this)

**Comment by hazzadous** [comment]
> I'm about 70% sure that even only setting rebalance_cb: true means we need to implement assignment behaviour in the callback we provide.

Having a look [here](https://github.com/acosom/node-rdkafka-acosom/blob/c1435e9cac4759a99d21f4f2f3c61b394a4626ff/lib/kafka-consumer.js#L94), it _looks_ like it will use either eager or cooperative in the case that `rebalance_cb` is a boolean, and only if it's a function will it be expecting you to perform the rebalance yourself, does that sound right?

**Comment by hazzadous** [comment]
And then [here](https://github.com/acosom/node-rdkafka-acosom/blob/c1435e9cac4759a99d21f4f2f3c61b394a4626ff/lib/kafka-consumer.js#L47) in the node based rebalance code it handles the emit of the `rebalance` event. And if you don't specify anything you'll not have any events emitted and librdkafka will handle the rebalance internally(?)

**Comment by pauldambra** [comment]
Ah, and in the vanilla one it handles the boolean case https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L54

OK, 70% was an over-estimate 🤣

**Pull request merged**
