### PR TITLE
fix(person-overrides): add constraints to catch race conditions

### PR DESCRIPTION
**Pull request by hazzadous**
## Problem

The main issue here is the CHECK CONSTRAINT we were expecting to save us from chains appearing in the mappings for person overrides isn't applied at commit and check constraints are not deferrable. Even if they were I believe that it would not be able to peek at other db changes so does not fix all race conditions.

Rather we should simply add a foreign key constraint to the persons table uuid column. Ideally we'd want a unique index on (team_id, uuid) but we don't have that. So we should add that, then add a foreign key to that, then when we delete persons from that table that will render rows still referencing this in the overrides as integrity errors.

If we go with soft deletes on persons table, then we'll want to change the reference to be to (team_id, uuid, is_deleted) thereby allowing soft deletes on this table as well as invalidating the foreign key references.

NOTE: I did some refactoring of the tests to not use BaseTest as this introduces implicit data (e.g. team.token) that makes if awkward to reason about, and use when we enable transactional tests cases

NOTE: refactored the tests to also be able to specify transactional tests cases so we could more easily test the race condition.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by tomasfarias** [comment]
The new constraint seems semantically different from the check constraint as the check constraint was preventing the usage of `old_person_id` as `override_person_id` while allowing repeated `override_person_id`s.

However, the new constraint would allow existing `old_person_id` (as these exist in the `Person` model) to be used as `override_person_id` or viceversa. The original constraint included a [fiddle](https://dbfiddle.uk/kvtLY-DG) to account for each possible case, I've adapted it to a [new fiddle](https://dbfiddle.uk/yEnifpvo) which shows that test cases now pass when they used to fail.


This is not necessarily an issue, just wondering what is motivating the change in semantics.

**Comment by hazzadous** [comment]
> The new constraint seems semantically different from the check constraint as the check constraint was preventing the usage of `old_person_id` as `override_person_id` while allowing repeated `override_person_id`s.
> 
> However, the new constraint would allow existing `old_person_id` (as these exist in the `Person` model) to be used as `override_person_id` or viceversa. The original constraint included a [fiddle](https://dbfiddle.uk/kvtLY-DG) to account for each possible case, I've adapted it to a [new fiddle](https://dbfiddle.uk/yEnifpvo) which shows that test cases now pass when they used to fail.
> 
> This is not necessarily an issue, just wondering what is motivating the change in semantics.

The new constraint relies on the assumptions:

 1. Something being used as an `old_person_id` implies that it was deleted from the person table, meaning that it will not be possible that it is in the `override_person_id` column.
 2. Something in the `override_person_id` column implies that it is in the person table, which we assume means that it is not in the `old_person_id` column.

That's obviously dependent on the application implementing the assumptions correctly.

I couldn't find a way that would provide the constraint that would handle the test case that I've included, which is roughly how the plugin server will be handling the merge. The test cases in the fiddle would need to include a `DELETE` on the person table to get the desired behaviour.

Not ideal. If you can find a way to get the desired constraints on the personoverrides table on it's own that would be great. It would likely need to use a unique index or excludes in some way rather than a check constraint as these don't apply at commit time afaict.

**Comment by hazzadous** [comment]
@tomasfarias I've also added a corresponding test in the plugin-server [here](https://github.com/PostHog/posthog/pull/13999/files#diff-63822abd7207c0388621ec3773d6c1867c4f16b99bf056994dd72e59fbc627b0R2344) fwiw.

I'm on pipeline team support this sprint so keen to get this handed over! Let me know if you want to hangout to do the handover.

**Comment by tomasfarias** [comment]
I've rebased this PR on `origin/master` to get the changes to CI plugin server in.

**Comment by tiina303** [comment]
Thought about deletions ... it's fine for us to leave them in the overrides table with broken keys (as in person was deleted entry is still in the overrides table), but we should add a test to the follow-up PR to make sure that doesn't break adding a future override:
1. merge X -> Y
2. delete Y
3. merge Y (distinct_id) -> Z and make sure it does the right thing (we can probably just update X -> Z here too 🤷‍♀️ )

**Comment by tiina303** [comment]
When we have soft deletes I wonder if this would work: https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey.limit_choices_to - old_person being limited_to is_deleted: true and override_person being limited to is_deleted: false
though I suspect this doesn't have guarantees on concurrent transactions

**Comment by tomasfarias** [comment]
Rebased on master to push our rework migration to number 0302 as number 0301 was taken.

**Review by tiina303 — APPROVED** [review]

**Pull request merged**
