### PR TITLE
Hide irrelevant numbers for the initial funnel step and clean styling up

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This hides the dropoff count for the first step of the funnel along with both percentages, since they just don't make sense there logically. Also a small styling cleanup, particularly around arrow icons and paddings.

| | Before | After |
| --- | --- | --- |
| L to R | Screen Shot 2021-08-18 at 19 07 18 | Screen Shot 2021-08-18 at 19 01 56 |
| T to B | Screen Shot 2021-08-18 at 19 07 07 | Screen Shot 2021-08-18 at 20 33 28 |

### CODE REVIEW

**Review by clarkus — APPROVED** [review]
These changes look good to me. I am trying to remember the reason we decided to leave the non-applicable metrics in step one. @paolodamico or @samwinslow do you remember if there was a reason we didn't hide those?

**Review by paolodamico — APPROVED** [review]
Changes good lgtm, except I would consider keeping the 100% indicator on the first step for consistency, even if it's obvious, I think it makes it's better to have it.

I think we originally had those values for consistency, but I think these changes are for the better (with the asterisk from above).

**Comment by samwinslow** [comment]
+1 to @paolodamico's recommendation to keep the percentage but drop the dropoff.

**Comment by Twixes** [comment]
Alrighty, keeping the percentage for all steps!

**Pull request merged**
