### PR TITLE
Plugin server info on system status page

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Adds a few plugin server-related pieces of data onto the system status page to help debug issues as they arise:
image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by macobo** [comment]
Aside: Should we include the same info in the instance status report? :)

**Comment by mariusandra** [comment]
Hmm, not sure:
- There's no similar data in the instance status report about redis/celery/etc being up or down. I guess we assume they should always be up.
- Sending data about who has access to install/configure plugins seems not relevant for the report (and could potentially increase an attack surface / leak some kind of PII).
- The "event ingestion via" bit might be relevant, though this PR is just to help debug things and we will move on to fully ingesting things in the plugin server soon enough

**Comment by macobo** [comment]
Up to you, just a thought - I can see "has plugin server set up"/"ingesting via" being a bit of information that'll be useful for debugging all of our esoteric deployment methods.

**Comment by mariusandra** [comment]
Yup. I just want this merged so I could test some helm charts 😅

**Review by macobo — APPROVED** [review]
Of course. I only brought it up here because it seemed to make more sense than to do it in #plugins :)

**Pull request merged**
