### PR TITLE
fix: Uncaught exception handling for plugins

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Possibly fixes https://github.com/PostHog/product-internal/issues/442

## Changes

* Adds catch for uncaughtException

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by hazzadous — CHANGES_REQUESTED** [review]
Looks good

Can we add a test where we try to load a plugin with an unhandled exception that would trigger the handler? Looking back at a similar issue [here](https://github.com/PostHog/posthog/pull/12448) I didn't manage to add a test their which makes me think it would be tricky. I roughly remember it being annoying because it would will the test runner or something, or maybe it was difficult to mock.

So no problem if not able to write a test. Non-blocking.

**Review by hazzadous — APPROVED** [review]
Ooops I said non-blocking then blocked the merge. To restate, would be nice to have a test, might be difficult though so feel free to merge.

**Comment by benjackwhite** [comment]
> Ooops I said non-blocking then blocked the merge. To restate, would be nice to have a test, might be difficult though so feel free to merge.

Given how hard it was to create the local plugin to trigger the issue, I'm not even sure how one would do that. I also don't have any spare time for this - it was already a distraction from my long todo list 😅 Happy to leave it open for someone to add the test or merge, what do you think @hazzadous ?

**Review by mariusandra — APPROVED** [review]

**Comment by hazzadous** [comment]
@benjackwhite I'll add some tests here https://github.com/PostHog/posthog/blob/master/plugin-server/functional_tests/plugins.test.ts#L58:L58

**Pull request merged**
