### PR TITLE
Allow renaming group types

### LINKED ISSUE #7763: Allow renaming group types
## Is your feature request related to a problem?

We use the group type name you've set up in tracking to be the thing you see in UI throughout insights, feature flags and group pages.

This can cause issues as:
- The code name might be somewhat ugly (e.g. `client_account`)
- We can't pluralize it in a way that always looks natural (e.g. `client_account(s)`)

## Describe the solution you'd like

Allow giving custom singular and plural names in the UI.

Not sure where to place this:

I'd add a cog icon next to each of the group name in people & groups page here:

image

Opening it opens a modal showing:
1. The name in code (uneditable)
2. Singular name (with a default to the name in code)
3. Plural name (with a default to `code_name(s)`
4. Link to the documentation

You can then change group settings that way.

Permissions-wise, the settings option would only be shown to administrators of the organization.

## Describe alternatives you've considered

Allowing deleting and re-adding group types - will cause issues since deletion is an expensive operation!

## Additional context

cc @clarkus for alternate design ideas

Was discussing this with @joesaunderson in slack

### PR DESCRIPTION
**Pull request by macobo**
## Changes

This PR adds a new section into settings for group analytics (if enabled) where users can configure what's shown in various dropdowns through the app.

This can be used if the name-in-code does not look well in the app itself/is confusing.

image

Fixes https://github.com/PostHog/posthog/issues/7763

## How did you test this code?

Changed the name and clicked throughout the app

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
Code looks alright to me!

No thoughts design-wise.

**Comment by paolodamico** [comment]
We should probably update the group docs to reflect this too

**Comment by macobo** [comment]
Already done https://posthog.com/docs/user-guides/group-analytics#renaming-group-types

**Comment by paolodamico** [comment]
you're the best @macobo!

**Pull request merged**
