### PR TITLE
Rework `SessionsPlayerButton` and clean up Sessions UI

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This is a prerequisite for #5664 that reworks `SessionsPlayerButton` into something that will also be useful in the persons modal. Based on a design by @clarkus (https://github.com/PostHog/posthog/issues/5664#issuecomment-903948068), though a bit more lightweight than there at the moment – can always adjust any styles.
Also cleaned up nearby Sessions UI.

| Before | After |
| --- | --- |
| Zrzut ekranu 2021-08-25 o 20 20 29 | Zrzut ekranu 2021-08-25 o 20 24 15 |

### CODE REVIEW

**Review by clarkus — APPROVED** [review]
This change looks good to me. I missed this in the earlier design, but I wonder if the color is enough to communicate previously watched recordings. We could include a tooltip on hover that clarifies the meaning of each icon state. 
Screen Shot 2021-08-25 at 11 48 16 AM

**Comment by alexkim205** [comment]
Nice! lgtm overall but left some feedback inline and below.

Are these two durations supposed to be the same? It's confusing that 1min is rounded up from 18s in this case.

Screen Shot 2021-08-25 at 2 21 32 PM

**Comment by macobo** [comment]
Q: In an ideal world most sessions would not have a dropdown. Do we show one even for those (as indicated by the screenshot?) If so - why? IMO This makes the "majority" case of navigation much slower - you expect most sessions (especially in modals) to have one recording only. 

Also this kills a feature - being able to distinguish whether a user has seen a recording or not. This is something that's quite vital for session recordings - you don't want to watch one twice.

As-is this change would make my usage of session recordings more painful.

Note also https://github.com/PostHog/posthog/issues/4884 - this quirk is something I think is temporary and we'll hopefully do away with soon.

cc @clarkus

**Comment by Twixes** [comment]
@alexkim205 Thanks for the review. As for durations, yes, they should definitely be different, as a PostHog session is detached from a session recording, that is a single session can have multiple session recordings, a single one, or none. So it's calculated separately based on PostHog events.

@macobo I see what you mean. I added a play icon to the button too, which is blue if there's an unwatched recording under it, and gray if all have already been watched. This should improve scannability.

Initially I wanted to make it play without a dropdown in case of a single recording, but I ran into a weird UX mismatch, where you'd be able to see the details of recordings when there were multiple of them (thanks to the dropdown), but you'd be clicking blindly in case of a single recording – no place to show the timestamp.
Alternatively I tried showing the dropdown on hover instead of on click, but that was super tricky with the way the popper component uses a ref + would potentially be annoying when moving the cursor over the column.
Hence I went for the dropdown-on-click-always approach.
Happy to hear what you think about this and iterate though (best in a later PR though). @clarkus @macobo

Updated button:
Zrzut ekranu 2021-08-26 o 17 21 02

**Comment by clarkus** [comment]
@macobo I think we can maintain the watched / unwatched treatment given my previous comment. It's essentially how it works now with different color coding and additional tooltips to translate what each icon color means. Is there more to it, or would that be sufficient to communicate watched / unwatched? 

I do think we should trigger dropdowns with clicks as much as possible. That's pretty consistent across all our dropdowns.

**Comment by Twixes** [comment]
Also added a 500+ ms hover tooltip to the play icon for individual recordings :)
Zrzut ekranu 2021-08-26 o 17 23 14

**Comment by macobo** [comment]
@clarkus 

> @macobo I think we can maintain the watched / unwatched treatment given my previous comment.

Problem being you need to open a dropdown to see it in the first place. Given that these lists are supposed to get large, we have made a process that used to be purely visual into a clicking fest.

@Twixes 

> @macobo I see what you mean. I added a play icon to the button too, which is blue if there's an unwatched recording under it, and gray if all have already been watched. This should improve scannability.

I think so too. Didn't check out the code but looks much better.

> Initially I wanted to make it play without a dropdown in case of a single recording, but I ran into a weird UX mismatch, where you'd be able to see the details of recordings when there were multiple of them (thanks to the dropdown), but you'd be clicking blindly in case of a single recording – no place to show the timestamp.

Very good point IMO re the design. 

All-in-all it brings up the question of what problem we're solving and why? 

For Sessions page specifically, after https://github.com/PostHog/posthog/issues/4884 has been resolved we will have 1-1 matching. For people modal, I'd expect similar - one session recording per person 98% of the time (since it's based on user navigating around, how often do you use two browsers at once?)

What are we gaining by simplifying the 2% case?

**Comment by clarkus** [comment]
> Problem being you need to open a dropdown to see it in the first place. Given that these lists are supposed to get large, we have made a process that used to be purely visual into a clicking fest.

True, but we've also added extra information to communicate the freshness of recordings and their duration. It's another click but you can have more info to indicate which session might be worth watching. We are going to hit some uppperbound for scale here at some point. We could adjust to showing recordings inline with an overflow option that links off to a full list of recordings for the user, but I'm not sure we'd be able to include the other information in that case. 

> What are we gaining by simplifying the 2% case?

I think we're making it better until #4884 is completed. Once we have more confidence in a 1:1 match, we can adjust here. Given how things are working now, this feels like a better experience until we're in a more ideal state.

**Review by paolodamico — COMMENTED** [review]
Sorry for the delay here. Quick posthumous review (UX/product, **not code**) based on PostHog Cloud to improve in a subsequent PR,

1. There's a weird flicker with scrollbars which makes interacting with the page really difficult.
image

2. Probably related to the above, the tooltip in the Recordings column header is no longer showing.
3. We should just allow direct clicking on the button if there's only one recording. No point in showing the dropdown. This way it can also be clear at a glance to users when a session has multiple recordings.

**Comment by clarkus** [comment]
Oh I thought it was set to only show a drop down in the case of multiple recordings. Otherwise it's a button.

**Comment by Twixes** [comment]
Couldn't reproduce the flickering, but there is a problem with sizing the last column in `ResizableTable`. Kind of outside the scope of this PR, but may be good to take a look at it later.
I see the point with the single recording case, put out a proposal how to handle it: #5757

**Pull request merged**
