### PR TITLE
chore: Add Surveys to support modal

### PR DESCRIPTION
**Pull request by joethreepwood**
## Problem

I _think_ this will add a 'Surveys' option to the Support Modal? I've directed it to Feature Success, I think.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by joethreepwood** [comment]
@pauldambra This failure mentions that Prettier thing you told me about earlier. Is it worth me setting that up?

**Comment by pauldambra** [comment]
Yep, it should be running in a git commit hook, and it's helpful if your text editor runs it too

**Comment by neilkakkar** [comment]
@Twixes  How does this get routed to our team? 🤔

**Comment by Twixes** [comment]
This rule: https://posthoghelp.zendesk.com/agent/admin/triggers/14505334778523 @neilkakkar

**Review by Twixes — APPROVED** [review]

**Pull request merged**
