### PR TITLE
feat(sampling): support sampling in experiments

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Problem

#12908 

More specifically, one of the clients in our Alpha testers group has requested this feature, given how slow the experiment metric loads for them.

## Changes

Adds a sampling filter to experiment goal setting view

## How did you test this code?

Manually locally

### CODE REVIEW

**Comment by neilkakkar** [comment]
Quick flyby, haven't tested it out yet, but does this filter get saved on the experiment, and thus re-used when querying for results?

i.e this filter: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/experiments/funnel_experiment_result.py#L73 - gets the sampling factor so that results use sampling too, and then hopefully the sampling correction happens at a level where the output of `funnel.run()` (L88, same file) gets adjusted results to calculate results on?

**Comment by yakkomajuri** [comment]
Ah so I knew there was something missing! So the filter does get saved on the experiment, but locally I didn't have enough data on the experiment results so assumed it used the same mechanism as the preview for the metric (i.e. purely frontend). Deep down I knew this to not be true I guess, but "worked with what I had" so I changed my assumption.

Will update the backend to also use this

**Comment by yakkomajuri** [comment]
Deleted my comment from earlier - yes it does save the filter on the model!

**Comment by yakkomajuri** [comment]
I'll YOLO this in - it's a purely frontend change and completely gated behind a feature flag. Will make sure it works on prod and push changes if needed

**Comment by yakkomajuri** [comment]
hmm yeah there are still some bugs around this

**Pull request merged**
