### PR TITLE
docs(capture): add spec for capture endpoints

### PR DESCRIPTION
**Pull request by hazzadous**
This adds an OpenAPI specification for the capture endpoints. This is
useful for documenting the API, and further can be used e.g. in tests to
validate that both clients and the API are behaving as expected.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by timgl** [comment]
Instead of doing this manually, we could annotate the endpoint with drf-spectacular so it gets generated automatically, and we can automatically pull it into our docs: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-2-extend-schema

**Comment by hazzadous** [comment]
> Instead of doing this manually, we could annotate the endpoint with drf-spectacular so it gets generated automatically, and we can automatically pull it into our docs: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-2-extend-schema

Yes we can where we are using DRF. This endpoint doesn't have a DRF spec however, and with the potential to move away from Django as the handler for the capture endpoints e.g. for performance reasons we may want to look into separating out from the implementation tech.

This also gives us the ability to add a little more context around the API and how it should be used, I posit that making the docs first class will make for a richer developer experience. e.g. adding documentation for any caveats that might be tricky to add as part of the autogenerated specs. Maybe we can do this also with the DRF autogenerated version though.

We can check for correctness of the docs via hooking into the tests for the API, as well as on the client tests to give us some level of confidence that docs, client and server implementation are inline, as well as reusing definitions for e.g. the Kafka message validations/testing.

I don't feel too strongly about this but suggest a little manual work over autogeneration can produce a better experience.

**Comment by timgl** [comment]
> Yes we can where we are using DRF. This endpoint doesn't have a DRF spec however, and with the potential to move away from Django as the handler for the capture endpoints e.g. for performance reasons we may want to look into separating out from the implementation tech.

Yep that makes sense!

> This also gives us the ability to add a little more context around the API and how it should be used, I posit that making the docs first class will make for a richer developer experience. e.g. adding documentation for any caveats that might be tricky to add as part of the autogenerated specs. Maybe we can do this also with the DRF autogenerated version though.

I documented a lot of this [here](https://posthog.com/docs/api#contributing-to-api-docs), you can add a lot of detail if you want. Again given that we're moving from python I'm happy with what you've proposed here though.

**Comment by ndimares** [comment]
@timgl if you guys do end up building an OpenAPI spec. I'd love to help y'all with generating SDKs from the spec. I [built some (Go, Python, TS, and Java)](https://github.com/speakeasy-sdks/posthog-sdks) based on the OpenAPI spec above. I'm a big fan of your product, we use you at Speakeasy. Let me know if the SDKs are of interest : )

https://github.com/speakeasy-sdks/posthog-sdks

**Comment by hazzadous** [comment]
> @timgl if you guys do end up building an OpenAPI spec. I'd love to help y'all with generating SDKs from the spec. I [built some (Go, Python, TS, and Java)](https://github.com/speakeasy-sdks/posthog-sdks) based on the OpenAPI spec above. I'm a big fan of your product, we use you at Speakeasy. Let me know if the SDKs are of interest : )
> 
> https://github.com/speakeasy-sdks/posthog-sdks

Amazing yes definitely! I've stalled a little here but keep your eyes peeled for updates on this PR.

**Comment by ndimares** [comment]
> 

Awesome! Eyes are peeled!

**Comment by timgl** [comment]
I don't think autogenerated SDKs for our capture endpoints makes sense as we already have client libraries for most languages, and they require fairly specific bits of code to handle things like feature flags.

The thing we could autogenerate libraries for is all the other endpoints, using the spec we also use to generate our docs: https://app.posthog.com/api/schema/. This isn't a priority yet but we are going to invest more in the docs etc for the API.

**Comment by ndimares** [comment]
> The thing we could autogenerate libraries for is all the other endpoints, using the spec we also use to generate our docs: https://app.posthog.com/api/schema/. This isn't a priority yet but we are going to invest more in the docs etc for the API.

That makes sense. I don't think the referenced link works (or maybe it's a private resource?) If you can share the spec, I can do the generation and you can take a look.

**Comment by ndimares** [comment]
After @hazzadous kindly pointed out that I needed to login to download the spec I was able to generate some SDKs for y'all (fyi @timgl ):

- [PostHog Go SDK](https://github.com/speakeasy-sdks/posthog-go-sdk)
- [PostHog Python SDK](https://github.com/speakeasy-sdks/posthog-python-sdk)
- [PostHog Typescript SDK](https://github.com/speakeasy-sdks/posthog-ts-sdk)

I only made a couple of tweaks to the spec for the generation:

- Added the servers object to the spec
- Added nullable as a value on enums marked with the nullable property.

We could definitely improve these SDKs with support for CSV types, which we don't support natively at the moment, and are instead handling as bytes.  

Looking forward to hearing any feedback, and if these could be at all useful to the PostHog community!

**Pull request closed without merging**
