### PR TITLE
feat: Display expiration date for credits on Billing page

### PR DESCRIPTION
**Pull request by patricio-posthog**
## Problem

We want to show until when their credits are valid on the billing page, so users know their expiration date.

## Changes

A change in the billing component, adding the expiration date next to the available credits.

Screenshot 2024-09-25 at 9 18 22 PM

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

It doesn't have impact in self-hosted.

## How did you test this code?

Manually tested and updating storybooks.

### CODE REVIEW

**Review by zlwaterfield — COMMENTED** [review]
Code looks good but I think we should iterate on the copy a bit more. 

Maybe something like `You have $500 credits remaining which are valid until October 23, 2025`. Then we could add a tool tip that sys they will apply to your bills and you won't be charged unless they run out. 

@raquelmsmith probably has opinions here.

**Comment by raquelmsmith** [comment]
I actually think we should make a few changes here. The bill total should be the total amount, not the amount after credits. And then we should use the same style as the bill to display the remaining credits and expiration, just smaller and muted color. 

I will play with this.

**Comment by patricio-posthog** [comment]
@raquelmsmith Sure, that makes sense. Let me know when I should retake this one.

**Comment by raquelmsmith** [comment]
I made some updates here (I've not liked how many sentences we use on this page for a while - figured I may as well clean it up a bit).


With credits:
Arc 2024-09-30 15 59 01

Expiration in tooltip:
Arc 2024-09-30 15 59 09

With discount (shouldn't ever be applied with credits, but UI handles it anyway):
Arc 2024-09-30 15 59 41

**Review by zlwaterfield — APPROVED** [review]
Looks awesome!

**Pull request merged**
