### PR TITLE
6331 pie chart persons bug

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- addresses #6331. Clicking on pie chart was showing same persons across all breakdown values
- remove ad hoc handling of timestamp arguments
- fix faulty tests and add a test for trend persons
*If this affects the frontend, include screenshots.*  

## How did you test this code?

*Please describe.*
backend test
will QA frontend

### CODE REVIEW

**Review by hazzadous — COMMENTED** [review]
Looks ok although can't say I follow it all. Just some comments around tests, but I understand it's consistent with the other tests there.

**Review by hazzadous — APPROVED** [review]
I find it so much more clear with the tests now. Nothing blocking from me.

I did find it surprising that the value_1 breakdown was 3. I guess it's the latest prop value that is taken?

It's so much easier to understand with the explicit people check. tbh that kind of makes the len checks unnecessary

**Comment by EDsCODE** [comment]
> I did find it surprising that the value_1 breakdown was 3. I guess it's the latest prop value that is taken?

Not the latest. It counts in the total if an event with that property is performed at all. So all three people performed the event with value_1 and only 1 of those 3 people performed with value_2

**Comment by hazzadous** [comment]
> > I did find it surprising that the value_1 breakdown was 3. I guess it's the latest prop value that is taken?
> 
> Not the latest. It counts in the total if an event with that property is performed at all. So all three people performed the event with value_1 and only 1 of those 3 people performed with value_2

Ah I thought there were 4 people with value_1 events, must have read it wrong.

**Comment by hazzadous** [comment]
Right I see, the person4 is out of time

**Pull request merged**
