### PR TITLE
fix: Modified TaxonomicPropertyFilter to resize based on parent

### LINKED ISSUE #9900: Bug: Inconsistent abbreviation of property names in global filters
## Bug description

Building on @andyvan-ph's feedback in Slack that [global filters are now harder to use](https://posthog.slack.com/archives/C011L071P8U/p1653298412107269), I went to have a look this issue myself. And found a bug!

That is, we seem to be inconsistent in turning overflowing property names to ellipsis `...` and in using the PostHog logo (which I think is meant to be used just on autocapture events, normally). 

Here's an example...

Screenshot 2022-05-23 at 10 57 29

Here, from top to bottom, I'm trying to track some properties which I chose based on them having long names. 

```
$active_feature_flags_1
Initial referring domain
Feature: filter_by_session_props_link
onboarding 1 test users ingested
Library Version
event_count_new_in_period
$enables_feature_flags_4267-event-property-taxonomy
```
In the screenshot above, some of those with the _shortest_ names get reduced to ellipsis (e.g. `Initial referring domain`, `Library Version`) while the longest (`$enables_feature_flags_4267-event-property-taxonomy`) do not. 

Others which I don't believe are autocaptured events, such as `Feature: filter_by_session_props_link`, are also accompanied by the PostHog logo. I always thought we only used this logo on autocaptured events?

Regardless, this is at full size on a 4K screen. It actually looks better if you shrink the window size dramatically. Then, it looks like this and the size of the filter modal increases because it now stacks on top of other elements, not side by side. 

Screenshot 2022-05-23 at 10 55 43

## How to reproduce

1. Filters
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

### PR DESCRIPTION
**Pull request by benjackwhite**
Rather than the window.

Closes https://github.com/PostHog/posthog/issues/9900

## Problem

See https://github.com/PostHog/posthog/issues/9900

## Changes

Fixes both the "ellipsis problem" where sometimes only "..." would show instead of just at the end of the text.
Also fixes the component to resize based on parent rather than the window

**Also** adds a nice little hook for this in the future:

```js
const { ref: wrapperRef, size } = useResizeBreakpoints({
        0: 'tiny',
        350: 'small',
        512: 'medium',
        1280: 'large',
})
// size will change only once one of the thresholds is passed 🥳 
```

In the EditorPanels:

Screenshot 2022-05-23 at 15 36 00

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Mostly in the Storybook but validated elsewhere in the code that it looks good

### CODE REVIEW

**Review by mariusandra — CHANGES_REQUESTED** [review]
Overall looks like an improvement. 

Found just one common case where the fake select box isn't showing well:

image
image

**Comment by benjackwhite** [comment]
> Overall looks like an improvement.
> 
> Found just one common case where the fake select box isn't showing well:
> 


@mariusandra Not exactly sure what you are referring to? The "Time" button positioning of the down chevron or what? Not sure that this change actually affected it tbh.

**Comment by benjackwhite** [comment]
@mariusandra Small tweak pushed that fixes the positioning I think you are referencing. If there is something else I didn't understand could you give a little more detail?

**Review by mariusandra — APPROVED** [review]
That's exactly what I meant, thanks! 👍

**Pull request merged**
