### PR TITLE
Support POSTHOG_REDIS_* vars in bin/plugin-server

### LINKED ISSUE #36: plugin expects redis on localhost
I upgraded the chart from 1.4.4 -> 1.4.7 which also includes a posthog upgrade from 1.20 -> 1.21. Now the plugins deployment tries to reach Redis on 127.0.0.1:
```
[MAIN] 🔴 Redis error encountered! Trying to reconnect...
 Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

On our dev cluster I am using redis as part of the chart (the default: redis.enabled true) which leads to the following env on the plugins pod:
```$ k exec posthog-plugins-866846fbb5-pmbsz -- env | grep REDIS
POSTHOG_REDIS_PORT=6379
POSTHOG_REDIS_HOST=posthog-posthog-redis-master
POSTHOG_REDIS_PASSWORD=**
```

I looked into the plugins repository which is using `REDIS_URL` as env var and tried setting that directly which fixed it for me.
https://github.com/PostHog/plugin-server/blob/bb8dfba4d83d068cbc497f11fcb85f0cc1ebff2d/src/config.ts#L29

```yaml
spec:
  releaseName: posthog
  chart:
    repository: "https://posthog.github.io/charts"
    name: posthog
    version: "1.4.7"
  values:
    plugins:
      resources:
      ...
      env:
        - name: REDIS_URL
          value: redis://:**@posthog-posthog-redis-master:6379/
```

Only looked very briefly and couldn't see where the REDIS env config mapping broke  ... maybe in the chart, more likely in the plugins server.

### LINKED ISSUE #3425: Plugin-server starts without correctly generated Redis environment variables (since 1.21.0)
## Bug description

Testing an upgrade from 1.20 to 1.21 with the Plugin Server via Helm / Kubernetes
The plugin-server becomes healthy from Kubernetes point of view but when you look at the UI or the logs it is clear that it is not. It tries to connect to REDIS like so `Error: connect ECONNREFUSED 127.0.0.1:6379` which indicates the REDIS_URL env has not been correctly generated.

Jumping into the diff it seems there used to be a line in the plugin-server executable that generated a `CONFIG` env var including the `REDIS_URL` (made from `POSTHOG_REDIS_HOST` etc.). Since 1.21.0 this seems to be removed.
https://github.com/PostHog/posthog/blob/1.20.0/bin/plugin-server#L7

I assume this may also apply to other env variables but the logged issue is specifically with Redis

## How to reproduce

1. Deploy the helm chart with Plugin Server enabled
2. Observe logs of the plugin-server

## Environment

- [ ] self-hosted PostHog 1.21.0
- [ ] Kubernetes 1.19
- [ ] Helm 3
- [ ] Chart version - 1.4.7

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

We recently changed the approach to providing configuration to plugin server in `bin/plugin-server` in order to make it independent from the Django server, but `POSTHOG_REDIS_*` variables, used in charts, did not get the special handling needed. This adds proper handling.
Resolves PostHog/charts#36, resolves #3425.

### CODE REVIEW

**Comment by behrtam** [comment]
Tried the updated helm chart 1.4.8 with the patch-1.21.0 image which leads to a new error:
```
yarn run v1.22.10
$ posthog-plugin-server
[MAIN] ⚡ posthog-plugin-server v0.8.3
[MAIN] ℹ️ 2 workers, 10 tasks per worker
[MAIN] 🔴 Redis error encountered! Trying to reconnect...
 ReplyError: NOAUTH Authentication required.
    at parseError (/code/plugins/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/code/plugins/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
[MAIN] 💥 Launchpad failure! ReplyError: NOAUTH Authentication required.
    at parseError (/code/plugins/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/code/plugins/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
```

Looking at the the readme of https://github.com/luin/ioredis
```
new Redis("redis://:authpassword@127.0.0.1:6380/4");
```
is the `REDIS_URL` maybe missing the colon(:) in front of the password?
```
-REDIS_PASSWORD_COMPONENT="$POSTHOG_REDIS_PASSWORD@"
+REDIS_PASSWORD_COMPONENT=":$POSTHOG_REDIS_PASSWORD@"
```

**Comment by mariusandra** [comment]
Hey, we kind of did this: https://github.com/PostHog/posthog/pull/3439/files

The fix landed in the same `patch-1.21.0` image and was reported to have worked. Could a simple update of the image solve this?

**Comment by behrtam** [comment]
I'm running the `patch-1.21.0` image but that does not contain the colon fix (https://github.com/PostHog/posthog/pull/3439/commits/088f60160f8b8256257f8cea1ebacea555319498).

```
❯ helm ls
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
posthog	posthog  	14      	2021-02-22 22:11:02.302256489 +0000 UTC	deployed	posthog-1.4.8	1.21.0

❯ k exec posthog-plugins-7f4dd6dcc6-htnj4 -it -- cat /code/bin/plugin-server | grep REDIS_PASSWORD_COMPONENT
  [[ -n $POSTHOG_REDIS_PASSWORD ]] && REDIS_PASSWORD_COMPONENT="$POSTHOG_REDIS_PASSWORD@"
  export REDIS_URL="redis://${REDIS_PASSWORD_COMPONENT}${POSTHOG_REDIS_HOST:-"localhost"}:${POSTHOG_REDIS_PORT:-"6379"}/"
  
❯ kubectl get pod posthog-plugins-7f4dd6dcc6-htnj4 -o jsonpath="{..image}"
docker.io/posthog/posthog:patch-1.21.0 docker.io/posthog/posthog:patch-1.21.0%
```

**Comment by behrtam** [comment]
Wasn't expecting an updated image unter the same label. Repulled the patch label ... go the updated image and it works now. Thanks!

**Pull request merged**
