### PR TITLE
chore: upgraded Ruff linter

### PR DESCRIPTION
**Pull request by Gilbert09**
## Problem
- VSCode Ruff extension required `ruff` to have a higher minimum version than we were currently using

## Changes
- Upgraded the dev dependency of `ruff` to the latest version. Can't see any drastic breaking changes in their [changelog](https://github.com/astral-sh/ruff/releases) to suggest we can't do this 🤷

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
Thanks, it's great to keep our dependencies up to date! Seems there are a couple of lint issues after the upgrade though.

**Comment by neilkakkar** [comment]
Could you also please run ruff on the entire codebase so if there are any styling updates they happen in this PR, rather than in unrelated PRs afterwards? 😅

**Comment by Gilbert09** [comment]
@thmsobrmlr @neilkakkar Fixes applied and whole codebase formatted 😅 only 50k lines changed, no biggie

**Comment by neilkakkar** [comment]
that's how you get your stats up ;)

**Comment by Gilbert09** [comment]
We have passing checks now if anyone fancies giving me a green tick 👀

**Review by neilkakkar — APPROVED** [review]
oooff that's a lot of linting, github is struggling! I wonder how the machine actually doing the linting struggled 😋 

P.s: Make sure you announce in #dev afterwards for people to run `pip install -r requirements-dev.txt` so they get latest ruff, because otherwise their code will be re-linting back to the old stuff and be annoying 😅

**Pull request merged**
