### PR TITLE
feat: log person uuid in activity log

### PR DESCRIPTION
**Pull request by tiina303**
## Problem

Sometimes there's problems with persons state between CH and Postgres. The uuid is recorded both in CH and postgres, so it's a much more helpful name compared to postgres id.
E.g. would have been helpful https://posthog.slack.com/archives/C0460J93NBU/p1666785896597509

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

Before and after - 1 vs the uuid as name
```
select * from posthog_activitylog order by created_at desc  limit 2;
                  id                  | team_id |           organization_id            | activity | item_id | scope  |                                                detail                                                |          created_at           | user_id | is_system
--------------------------------------+---------+--------------------------------------+----------+---------+--------+------------------------------------------------------------------------------------------------------+-------------------------------+---------+-----------
 0184195f-2f03-0000-b85d-bc58052481b9 |       1 | 018409f1-de71-0000-e359-ab5978740b95 | deleted  | 1       | Person | {"name": "1", "changes": null, "trigger": null, "short_id": null}                                    | 2022-10-27 12:16:19.203629+00 |       1 |
 0184195c-9744-0000-1cc4-8a9354a6b1e2 |       1 | 018409f1-de71-0000-e359-ab5978740b95 | deleted  | 2       | Person | {"name": "01840a1f-34cd-0000-ac5d-58a85398b4d8", "changes": null, "trigger": null, "short_id": null} | 2022-10-27 12:13:29.284049+00 |       1 |
(2 rows)
```

### CODE REVIEW

**Review by yakkomajuri — APPROVED** [review]
LGTM _provided_ you've checked that in the frontend we don't use that person ID to lookup an actual person name and that this would break that. 

I haven't checked myself, just guessing that this might be a possibility

**Review by mariusandra — APPROVED** [review]
The code looks good, but I didn't test deeply. Assuming you did a few tests in the interface to create/delete/merge/split persons and the log looked fine (did you? "how did you test this code" above is blank), it's good for me.

@pauldambra as the de-facto owner of the activity log (here's that moneky's paw again) might have something to add

**Review by pauldambra — APPROVED** [review]
LGTM

Only affect on the front end is that if someone deletes a person via the API we print out that ID 

```
<strong>{logItem.user.first_name}</strong> deleted the person: {logItem.detail.name}
```

So we're going from "deleted the person: 1" to "deleted the person: UUID"  

They're equally unhelpful IMO so a signal that the person activity log could be better rather than a reason to block here 🤔

**Comment by pauldambra** [comment]
> here's that moneky's paw again

🤣

**Pull request merged**
