### PR TITLE
chore: etag responses

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

Pulled from https://github.com/PostHog/posthog/pull/20632

## Changes

Adds etag responses to recording data

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Verify in production as per https://github.com/PostHog/posthog/pull/21276/files#diff-36f2d0bf4c522b153acbf49e500cbe4277a212da01f9b37e3aa7e454abb76cd5R513

### CODE REVIEW

**Comment by daibhin** [comment]
Was waiting on https://github.com/PostHog/posthog/pull/20632. Should now be good to go through this week

**Comment by pauldambra** [comment]
I _think_ superceded by #21952 🤞

**Comment by daibhin** [comment]
@pauldambra is this superseded if this focused on the plugin-server / realtime fetching? From what I understood about the other PR it was only streamed S3 / blob snapshots

**Comment by pauldambra** [comment]
we never shipped the realtime consumer, the cost of the shared EFS storage was too high... but it was this prompt from Ben that made us realise we were missing this feature

**Comment by pauldambra** [comment]
(the only reason I haven't removed the v3 consumer is wondering about testing writing to postgres instead of EFS/redis but that's unlikely in the short term)

**Pull request closed without merging**
