### PR TITLE
fix: add command to delete persons with no distinct id's

### PR DESCRIPTION
**Pull request by oliverb123**

### CODE REVIEW

**Comment by bretthoerner** [comment]
Iterating over them does seem super slow, you can toss raw SQL into Django like so:

```
from django.db import connection

def delete_persons_without_distinct_ids_raw_sql(team_id):
    with connection.cursor() as cursor:
        cursor.execute("""
            WITH persons_to_delete AS (
                SELECT p.id
                FROM posthog_person p
                LEFT JOIN posthog_persondistinctid pd ON p.id = pd.person_id AND p.team_id = pd.team_id
                WHERE p.team_id = %s AND pd.id IS NULL
            )
            DELETE FROM posthog_person
            WHERE id IN (SELECT id FROM persons_to_delete)
            RETURNING id;
        """, [team_id])
        
        deleted_ids = cursor.fetchall()
        deleted_count = len(deleted_ids)

    print(f"Deleted {deleted_count} Person objects with no PersonDistinctIds for team {team_id}.")
    return deleted_count
```

You could still have a dry run that just does `SELECT COUNT(*) FROM persons_to_delete`

I tried a "dry run" and got 717680 for that one team so it seems correct?

**Comment by oliverb123** [comment]
@bretthoerner I went for iterating to avoid taking a lock on the persons table, but if you reckon that's not a concern I'll go for this

**Comment by bretthoerner** [comment]
> @bretthoerner I went for iterating to avoid taking a lock on the persons table, but if you reckon that's not a concern I'll go for this

The select ran fast enough for me, and this seems like something we'll run very rarely. 🤷‍♂️

**Comment by oliverb123** [comment]
Sounds good, will go with that so

**Review by mariusandra — APPROVED** [review]
Looks good to me

**Pull request merged**
