### PR TITLE
Insight last modification shown

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This adds fields `last_modified_at` and `last_modified_by` to the `Insight` model, which are meant to represent material changes to the insight. Currently, a material change exclusively means that one of these fields has changed: `name`, `description` and `filters`. The remaining fields (`tags`, `favorited`, `color`, etc.) are not taken into account.

This info is shown in `InsightCard` as [per design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6212%3A32693). It's not shown anywhere on the insight's page however – thoughts on exposing it there too @clarkus?

Last modified

## How did you test this code?

Added a Pytest.

### CODE REVIEW

**Comment by clarkus** [comment]
> This info is shown in InsightCard as per design. It's not shown anywhere on the insight's page however – thoughts on exposing it there too @clarkus?

Sounds like a good idea to add it to the detail page. It could be in the header adjacent to the description and tags just like it is in the card.

**Comment by Twixes** [comment]
Alright, added like so:
Zrzut ekranu 2022-01-25 o 21 22 36
It's also feature-flagged there as initially the data on last modification will be very lacking.

**Review by clarkus — APPROVED** [review]

**Review by pauldambra — APPROVED** [review]
LGTM

**Comment by pauldambra** [comment]
The one failing python test looks related to this change...

**Pull request merged**
