### PR TITLE
chore: move frontend install, build, and clean into single docker line

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

Our docker image is too big (1.2gb), and some CI flows are failing as a result. This PR decreases it to ~1gb.

## Changes

Moves the frontend build steps: install, build, and clean into a single step. As a result, Docker isn't creating a layer with the `/node_modules` folder, and the overall size is smaller.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Deployed the image on playground and made sure it worked.

### CODE REVIEW

**Comment by pauldambra** [comment]
Yes 🙌 I was just about to message in Slack about this. Awesome sauce! 💖

**Comment by pauldambra** [comment]
Because it isn't a multi-stage build, I think this removes `node_modules` from the subsequent layers (so it doesn't contribute to further layer size problems) but it's still in the image contributing to the size

(I am a docker n00b though)

**Comment by mariusandra** [comment]
We can't really remove node_modules from the plugin server, as it's a node app that needs its dependencies. The "build" step here just compiles TS to JS, and does NOT bundle any dependencies.

We could try to move towards `pnpm` or `yarn3` with their `PnP` support that uses a totally different system of loading and storing modules: https://blog.logrocket.com/javascript-package-managers-compared/ (see the benchmarks below).

We can't do that for the frontend (yet?), but perhaps we can for the plugin server. If so, I vote for `pnpm` out of the two.

**Comment by rcmarron** [comment]
> We can't really remove node_modules from the plugin server, as it's a node app that needs its dependencies. The "build" step here just compiles TS to JS, and does NOT bundle any dependencies.

Yeah, the title of this PR had become incorrect. The ultimate goal here was to reduce the image size, and we ended up going a different route.

**Review by fuziontech — APPROVED** [review]
lgtm, nice calls

**Pull request merged**
