### PR TITLE
fix(insights): worldlier world map (bump trends limit)

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

HogQL Trends world map shows up to 100 countries. That's because without an explicit LIMIT clause, we limit queries to 100 rows.

## Changes

Adds an explicit 10k limit into the trends insight.

This might not be the best way to go. Perhaps a separate "insight" limit context is in order? However that might make the results look different when you click "Edit SQL" on an insight.

## How did you test this code?

Checked locally via "debug clickhouse queries", saw the numbers go up from the default "100" limit on a world map insight.

### CODE REVIEW

**Review by webjunkie — COMMENTED** [review]
So this will return 10k results everywhere now with breakdowns? Is this a good idea?

**Review by Twixes — CHANGES_REQUESTED** [review]
Makes sense, since the outermost SELECT should not have a limit, as the limit of breakdown values is applied in the inner query. What's missing is a test!

**Comment by mariusandra** [comment]
Precisely, the actual limit is already applied deeper. This default top-level limit just overrides it. 

We did have updated snapshsot tests 🙈, but added something more explicit as well. In fact, we did have a world map test, but that tested only up to 30. The error began at 100 😆.

**Review by Twixes — APPROVED** [review]
👌

**Pull request merged**
