### PR TITLE
fix: Webhooks groups properties

### PR DESCRIPTION
**Pull request by tiina303**
## Problem

When we stopped writing groups on events (which was the right thing to do as it's not used in analytics queries and used up resources unnecessarily), then it broke webhooks using group properties.

This is innefficient as the comment says, but we don't want to spend too much time improving a legacy system that's going away soon.

Also made sure we don't accidentally break this functionality by adding a functional test for it.

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by tiina303** [comment]
@mariusandra this came from Product Analytics side, see https://github.com/PostHog/posthog/pull/22764 

> Group properties on events never went anywhere, having only been partially implemented (certainly not at all in HogQL), and I don't think we want to prioritize that idea now.
(I'm a tiny bit worried that group properties behaving differently from person ones might be confusing for users, but this just doesn't seem important.)

**Comment by mariusandra** [comment]
I don't see how these two things are at odds. The conclusion is different. You concluded "let's kill it". I would've concluded "let's finish it (next month?) cause it'll be a nightmare to re-enable and backfill, so no action now".

**Comment by tiina303** [comment]
Unfortunately it would have required data fixing / backfill anyway, which I called this out in https://github.com/PostHog/posthog/pull/22962

> There was at some point a problem with data written to group properties, so they aren't fully in a good state anyway.

**Comment by mariusandra** [comment]
Don't forget, we're serving the customer here. The customer is using "frontend apps" like Product Analytics or Feature Flags to do what they need to do. Whatever would be great for users of Product Analytics (and the other products) should take priority over what inconveniences a team that _effectively_ serves other teams, like Pipeline.

PoE clearly was done to help end users with performance. GoE was discussed, but put on the back burner as the next step. Having it would obviously help with any query that uses group properties (enough users to matter, I've seen reports). We have also always said Groups should be a "first class citizen", whatever that means, so removing features from Groups seems like a steps backwards.

In any case, please own up and fix the regression from webhooks (and CDP?), and/or communicate with the users why groups are not a first class citizen anymore if you choose that.

**Comment by tiina303** [comment]
> fix the regression from webhooks

I'm confused, this is exactly what this PR does

**Comment by mariusandra** [comment]
Yes, thank you. If you need help with reviewing, let me know.

**Comment by bretthoerner** [comment]
I don't know much about these code paths, and since this is undoing a breaking change and people are talking about backfills it makes me nervous to breeze through this.

I didn't review https://github.com/PostHog/posthog/pull/22962 but is this just a revert of that change, or something more complicated?

**Review by bretthoerner — APPROVED** [review]

**Pull request merged**
