### PR TITLE
chore(frontend): yeet sass vars

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

We have a very bespoke `vars` system for SCSS, which requires custom config on each module bundler. 

Turns out:

```scss
@import '~/vars';
```

isn't valid scss, as scss doesn't support import aliases.

If I want to, say, rollup/parcel a bunch of JS into `@posthog/apps-common`, I have to spend a considerable amount of time fighting this custom config.

The solution is to either go `@import '../../../../../../../../../../../../../../vars.scss';` everywhere, or remove SCSS vars altogether, replacing them with modern CSS vars.

## Changes

This PR is a WIP to move us off of SCSS vars and into 2017.

- Get rid of `vars.scss` completely.
   - Move breakpoints (can't use css vars in media queries) to `breakpoints.scss`
   - Move the rest to `globals.scss`, and inline the values in the css var definitions
- Some variables I couldn't move from scss to css because of sass color methods, like `darken($primary, 20%)`. All of those I moved under a new `--depr-` namespace, such as `--depr-darken-primary-20`. We should probably replace them with official colors, or lighten/darken with CSS otherwise.
- Removes complicated scss path configuration for esbuild that depends on multiple packages like `sass-extended-importer`.

## How did you test this code?

Clicked around a lot locally, didn't notice any suspicious things.

### CODE REVIEW

**Comment by mariusandra** [comment]
Plenty of changes and most of the relevant $sass is gone.

Something's up with the sidebar:

image

but got to run now... will update later.

**Review by Twixes — CHANGES_REQUESTED** [review]
Great refactor! Only found two minor issues.

**Review by Twixes — APPROVED** [review]
Resolved.

**Comment by mariusandra** [comment]
Beautiful! Thank you! Multumesc! Kiitos!

**Pull request merged**
