### PR TITLE
Feature flag toolbar link

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Changes `apiURL` to be without a `/` in the end, so we could just concat `urls.actions(id)` to it.
- Adds a link to feature flags

Not sure about the highlight hover animation. It's there to indicate that just the text is clickable. Should we change this @clarkus 

## How did you test this code?

- Clicking on the flag title opens the flag in a new tab
- Clicked on the "all actions" link in the toolbar/actions
- Verified I could save an action in the toolbar and the links in the popup worked
- The heatmap works
- Flags are still fetched (`toolbarFetch` works)

### CODE REVIEW

**Comment by clarkus** [comment]
Clickable or actionable text usually gets more of a standard hyperlink treatment - in this case the underline on hover reinforces that it's actionable text, but our primary action color (blue) would reinforce that the text can be clicked on distinct from the switch. The issue here is that this text is also functioning as a label for the switch - some users might expect clicking on that would toggle the value of the switch component. I think the blue text helps reinforce this, but I could see it causing some confusion potentially. Thoughts?

**Comment by mariusandra** [comment]
It was automatically blue when I added the link, and that looked a bit... well, too blue. So I made it black...

image

**Comment by clarkus** [comment]
The other option would be a secondary action reserved for opening the target in a new tab. We could add on an icon with a tooltip "view flag in new tab" - this would separate those label actions from the view action. Thoughts?

Screen Shot 2021-10-11 at 3 26 49 PM
.

**Comment by mariusandra** [comment]
That's indeed the obvious other choice, but sensible UX guidelines suggest leaving plenty of "touch space" around clickable elements, and that would reduce space for the labels even more.

Unless we make the "window" wider... 🤔 🤔 🤔

**Comment by clarkus** [comment]
Generally a 40–48px target area is the desirable size. Most icons have a 24px viewbox plus another 8–16px of padding. I think we are probably breaking this rule in other places in the product, so maybe we should set up some kind of clean up task for that. 

In the current version, the text isn't acting as a label functionally - maybe just combine the label with the extra affordance from the icon and make it entirely dedicated to viewing in a new tab? We can also make that list wider and include multiple actions.

Screen Shot 2021-10-11 at 3 40 42 PM

**Comment by mariusandra** [comment]
Made it 50px wider and added a link to the end of the row:



The link's at the end of the row, and not at the end of the flag key to make "..."-ing long names easy:

image

**Comment by mariusandra** [comment]
This is a purely frontend change that's causing the docker build test to flake. Basically `yarn build` segfaults:

image

My only theory is that importing `urls` from `scenes/sceneLogic.ts` causes way too much stuff to also get imported onto the toolbar scene, which throws webpack into a segfault hole. I'll make a separate PR to pull out `urls` from `sceneLogic` to fix this import loop.

**Comment by mariusandra** [comment]
Merging with master after the urls refactor https://github.com/PostHog/posthog/pull/6381 seems to have fixed it. Would love a review and to get this in. :)

**Review by rcmarron — APPROVED** [review]
LGTM

**Comment by mariusandra** [comment]
Please also merge when things look good enough.

**Pull request merged**
