### PR TITLE
feat(hogql): Put retention actor appearances in columns

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

The result of the retention actors query is hard to understand.

## Changes

- put booleans of the returns as columns
- we can let the SQL query do that
- anyone can now filter from frontend or export this way conveniently

image

## How did you test this code?

- click in frontend

### CODE REVIEW

**Comment by webjunkie** [comment]
@mariusandra how can I make these HogQL dialogs understand the columns?

image

**Comment by mariusandra** [comment]
> @mariusandra how can I make these HogQL dialogs understand the columns?

Oh, hmm. Those dialogs are currently hardcoded to assume we're selecting from an "events" or "persons" table. There's a `hogQLTable` var we pass into the `taxonomicFilterLogic` via the `<TaxonomicFilter />` tag.

This then [gets passed](https://github.com/PostHog/posthog/blob/69becac2009bb4d17fcb2a5bd90d2a2b9219873a/frontend/src/lib/components/HogQLEditor/hogQLEditorLogic.ts#L34-L38) to the `HogQLMetadata` query. We then [put this table](https://github.com/PostHog/posthog/blob/5513be7731414cb1a4ffa5a7789610005a8538ae/posthog/hogql/hogql.py#L36-L43) in a random `ast.SelectQuery` together with the parsed column, and hope for the best.

The solution is likely to replace the `hogQLTable` field with a `hogQLBase`, which would then be a query node, either `{kind:'HogQLQuery', query: 'select * from events'}`, or a `InsightActorsQuery`.

**Comment by webjunkie** [comment]
I realized that `interval` is the term for the rows already in the general retention result... and then you select one interval to get the appearances/returns... so it the columns there should probably be named something else 🤔 
I will address that.

**Review by mariusandra — APPROVED** [review]
LGTM 👍. I'll have a think about the column editing. Not blocking for here though.

**Pull request merged**
