### PR TITLE
feat: remove superceded listing mechanisms

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

Now that we've moved over to session replay table for all listing we can remove the old listing mechanism

## Changes

* removes the old mechanisms

## How did you test this code?

* checking the UI still works
* running `./bin/tests -vv --lf posthog/queries/session_recordings/test`

### CODE REVIEW

**Comment by pauldambra** [comment]
let's chop this down a little

https://github.com/PostHog/posthog/pull/16617
https://github.com/PostHog/posthog/pull/16618

**Review by benjackwhite — APPROVED** [review]
Looks good! Didn't run it myself but nothing stood out as wrong 😅

**Comment by pauldambra** [comment]
🙃 we need to handle persisting and loading to LTS for playlists before we can remove the existing listing mechanism

**Comment by pauldambra** [comment]
still needs https://github.com/PostHog/posthog/pull/16864

**Review by benjackwhite — APPROVED** [review]
This makes me very happy. Assuming tests pass - lets go

**Pull request merged**
