### PR TITLE
Reduce Heroku worker thread count

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Extracted from https://github.com/PostHog/posthog/pull/1946
- Reduce the number of Heroku workers to follow the [WEB_CONCURRENCY](https://github.com/heroku/heroku-buildpack-python/blob/main/vendor/WEB_CONCURRENCY.sh) setting set by resource type

This reduces the number of concurrent threads used in a worker on a "hobby" dyno from 8 to 2, greatly reducing the memory/swap usage:
image

It also reduces the number of redis connections needed from ~19 when idle to ~15. 

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by timgl** [comment]
I'm not sure why, but when this was deployed the worker wasn't turned on and I had to manually turn it on so no events where coming in. I don't know if that was a direct result of this PR or not,but haven't seen this on other PRs.

**Comment by mariusandra** [comment]
Indeed the worker didn't come up in my test. https://github.com/PostHog/posthog/pull/2097

image

Testing if that's also the case with a fresh branch from master: https://github.com/PostHog/posthog/pull/2099

**Comment by mariusandra** [comment]
The same happened with a fresh app deployed from master!

- https://github.com/PostHog/posthog/pull/2099
- https://dashboard.heroku.com/apps/posthog-heroku-worker-t-kxgoto

image

Not sure why though :/

**Comment by mariusandra** [comment]
Every branch now deploys without workers started. I don't know why, but will debug. This PR should be safe to merge though.

Screenshot_20201029-134452

**Comment by mariusandra** [comment]
@timgl the worker is deployed when just deploying a new heroku app (followed the docs to get here)

image

I'll investigate and try to fix this in a new PR and/or make a new issue. Any reason this one should not be merged?

Good news is that redis is quite stable now on an empty instance:

image

**Pull request merged**
