### PR TITLE
Proposal: Hide people count

### PR DESCRIPTION
**Pull request by macobo**
See https://github.com/PostHog/posthog/issues/5559 for context

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by Twixes** [comment]
I've already done that in #5537 too, along with a bit more of a UI rework to clean this modal up.

**Comment by macobo** [comment]
Ah. I'm sure I wasn't the only reviewer who didn't notice you baked that in there :sweat_smile: 

I think a separate PR here makes sense - keeps things cleaner, makes it more obvious it was removed on purpose etc.

**Comment by Twixes** [comment]
I agree this is better regarding clarity, so happy to make the decision on this point here and adjust the other PR accordingly (maybe actually dropping the Refresh button idea, since these small caching inconsistencies won't be as glaring without this separate people count anymore).

**Review by paolodamico — APPROVED** [review]
makes sense, thanks @macobo !

**Pull request merged**
