### PR TITLE
Remove migration check

### PR DESCRIPTION
**Pull request by tiina303**
## Changes

https://posthog.slack.com/archives/C01MM7VT7MG/p1639581997132200

### CODE REVIEW

**Review by yakkomajuri — CHANGES_REQUESTED** [review]
Let's not do this. Let's keep the check but not make it a healthcheck. Should be a frontend change to `systemStatusLogic` or something

**Comment by tiina303** [comment]
do I need to change https://github.com/PostHog/posthog/blob/3f85aa4c47725eb85da61d0cfca737006104029a/frontend/src/scenes/instance/SystemStatus/OverviewTab.tsx#L17 too?

**Comment by yakkomajuri** [comment]
@tiina303 shouldn't need to. That's just going to add a link if the key exists, but if you remove the key, should be ok.

**Comment by paolodamico** [comment]
Are we merging this for the release?

**Comment by Twixes** [comment]
We definitely should do _something_ with the check to avoid needless alarm in nav @paolodamico Not sure if Platform ended up deciding whether to keep the check in System Status (`metrics.append(`) though.

**Pull request merged**
