### PR TITLE
feat: show editor panel for query-based insights

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

You can now switch insights to "query" mode but the UI flow to edit them is different to other insights

Was a stacked branch... work really begins at commit e3b979c

## Changes

* adds an edit button
* shows a query editor when in edit mode

NB

* does not hide other edit buttons, so right now there are three
* does not auto-update while editing, unlike other types of insights

## How did you test this code?

* a few developer tests
* 👀

### CODE REVIEW

**Comment by mariusandra** [comment]
Very nice!

Thinking out loud some product questions that are not for this PR: we now have two things we can call "queries": 1) Raw data exploration JSON nodes and 2) HogQL SQL (just the `HogQLQuery` data exploration node). 

For different people, both are queries. How do we design an interface that lets people edit the one they want 🤔.

Perhaps we need two tabs, one called "HogQL" or "SQL" and the other called "Raw" or "Code" or "JSON" or "...?"

**Comment by pauldambra** [comment]
part of #13927

**Comment by pauldambra** [comment]
> How do we design an interface that lets people edit the one they want 🤔.

Yep, my assumption is that we'll add more tabs or an affordance inside the tab to let people choose and edit. But it feels like such flux at the moment that I've left it as text only for power users

**Review by thmsobrmlr — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
