### PR TITLE
feat(exports): unify export bundles

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Shared dashboards and the exporter share a lot of duplicated code. Let's unify and build a central exporting and embedding system.

## Changes

- Removes `shared_dashboards.html` and their separate entrypoint, consolidates under `exporter.html`
- Moves some files around
- Does not change the look of things, does not add new export types

## Visual differences

The following exports and shares are now supported:

- Exported insights PNG:

export-pageview-pageview-pageview-pageview-user-conversion-rate-by-null (5)

- Exported dashboards PNG:

export-00000 (3)

- Shared dashboard URL:
image

- Shared dashboard URL with ?embedded (should go in an iframe)
image

- Shared dashboard URL with ?whitelabel (EE only - should also go in an iframe)
image

## How did you test this code?

Exported all of them manually. 

## Questions and next steps

- @clarkus Dashboards have 3 export "types" --> image, embed, full page... plus "whitelabel". For each of them the page looks just slightly different, but in my mind not enough to actually justify three separate headers and footers. Should we standardise on one look? Which one?
- Should we add toggles when exporting, so the user can select how their dashboard will look like?
- TODO: unify the dashboard sharing and exporting backends as well. It might make sense to move everything over to the exported asset table.
- Retention PNG exports don't work.

### CODE REVIEW

**Comment by clarkus** [comment]
> @clarkus Dashboards have 3 export "types" --> image, embed, full page... plus "whitelabel". For each of them the page looks just slightly different, but in my mind not enough to actually justify three separate headers and footers. Should we standardise on one look? Which one?

I'm not sure we need multiple export types either. Does the type mostly control how our branding and attribution is placed? 

I'd be interested to hear @marcushyett-ph's opinion on a white-labeling option. Unless there's a good reason to do so, it feels like we'd want folks to know this was being provided by PostHog and how to learn more about our product.

**Comment by marcushyett-ph** [comment]
@clarkus we discussed this a bit in the standup today

The while labeling option was introduced as it was a blocking issue for some of our healthcare clients where they needed to share aggregate data with their customers (about their customer's end-users), they love the PostHog dashboards (so didn't want to reimplement the graphs using our APIs) - but their customers were concerned at seeing a 3rd party's logo on their dashboard embedded within their product (thinking their sensitive data might have been shared or processed externally without their permission). Hacky / unreliable workarounds with cropping the embedded iframe were considered as alternatives.

I personally believe its worth maintaining support for whitelabel given the privacy concerns of many of our client's end users.  But I don't think we should actively promote it to customers especially those who don't have specific this need, given shared dashboards and insights are a good opportunity to promote our brand for many of our customers. 

I agree we could absolutely combine these similar views together, @mariusandra do we have any context on where and how "embed" is used today?

**Review by benjackwhite — APPROVED** [review]
lgtm 👍

**Comment by mariusandra** [comment]
Thanks! Gonna merge, as it's just the code that changed. I'd would love to get guidance on which modes we need to support, and how they should look like. I'm off Mon-Wed if that helps with planning work around this.

@marcushyett-ph I don't know the context, but this is how they got added: https://github.com/posthog/posthog/pull/7469

**Pull request merged**
