### PR TITLE
Only include events in session recording query when needed

### PR DESCRIPTION
**Pull request by rcmarron**
## Changes

This PR speeds up the session recording query by only joining with events table only when needed. 

Before, we were always joining with the events table to get the `start_url` and `end_url` (which were not yet displayed to users). This slows down the query when there are no event filters. If we want to show the URLs to users in the future, we should probably include them in the `session_recording_events` table.

More details justifying this change here: https://github.com/PostHog/posthog/issues/7247

## How did you test this code?

This code should not change anything outside of performance, so I made sure all existing tests still pass and did a smoke check on the feature. I also ran the resulting query in metabase and ensured it sped up the query there (once we solve the `has_full_snapshot` issue, the query should be blazing)

### CODE REVIEW

**Comment by rcmarron** [comment]
Note: This PR branches off of: https://github.com/PostHog/posthog/pull/7218

**Comment by macobo** [comment]
I'm gonna block this PR on a proper benchmarking suite + measurements verifying the fix. 

Will start work on those on monday + improve https://posthog.com/handbook/engineering/query-performance-optimization.

Also, no tests broke even though this is a behavioral change?

**Comment by rcmarron** [comment]
Somewhat surprisingly, this didn't really speed things up much (only ~5% improvement in the no-filter case). 

Looks like there's another bottle neck in the query that's an order of magnitude worse than the join, so we need to figure out what that is. I'll revisit this PR after making other improvements to the query. 

Next approach is materializing the `has_full_snapshot` column here: https://github.com/PostHog/posthog/pull/7281

**Comment by rcmarron** [comment]
Alright, now that the `has_full_snapshot` PR is in, this one is showing better results. 

The latest benchmark on master is old, so the ridiculous improvement above isn't correct. In reality, this PR has improved the query by ~ 4x from `4761.5±5.6e+02 ` to `1258.0±2.9e+02`. Still worth merging

**Review by macobo — APPROVED** [review]
You can refresh the stats on master manually as needed: https://github.com/PostHog/posthog.com/pull/2533

Mind doing that + pushing the branch again before merging this so the stats reported would be correct?

**Review by alexkim205 — APPROVED** [review]

**Pull request merged**
