### PR TITLE
Closes #4987 sets page title to dashboard name whenever a dashboard is visited

### LINKED ISSUE #4987: Include dashboard name in page title
## Is your feature request related to a problem?

It takes too long for me to open the dashboard I'm checking out daily. I need to open posthog dashboards -> find the right one -> click. I'd like to get there fastest.

## Describe the solution you'd like

Include dashboard name in page title. This way my URL bar and page history will suggest it when looking for the dashboard.

## Describe alternatives you've considered

Using bookmarks.

### PR DESCRIPTION
**Pull request by manish001in**
Fixes #4987 

Issue 4987 is among starter issues to tackle.
I believe this should take care of setting page title as the name of the dashboard.

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Screenshot from 2021-09-07 04-07-03

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by paolodamico — APPROVED** [review]
🥳 thanks for the contribution here @manish001in! This will certainly be super helpful! Made some minor tweaks to match the title styling in the rest of the app but looks good to go!

**Comment by paolodamico** [comment]
@posthog-bot please add @manish001in for code

**Comment by manish001in** [comment]
You are welcome @paolodamico . Looking forward to add more. 
If you could clear one thing, why did you add a check for App Analytics in dashboard-item in tests? Is that not different from dashboard title?

**Comment by paolodamico** [comment]
That's great! Absolutely, so the test dashboard we were using is actually called "App Analytics" (see previous lines in the same test case). I'm actually not sure why we had the other option in there, I think it was just some leftover bug.

**Pull request merged**
