### PR TITLE
chore(ci): Fix hook-migrator CI, better name rust checks

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

Add some required test checks on all PRs for rust (so better naming here).

Fix an issue with hook-migrator CI

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by neilkakkar** [comment]
hmm, I should update the rust CI checks to run when rust CI changes as well  👀

**Comment by neilkakkar** [comment]
Annoying that codeql is the slowest check now, will configure this to not run on rust files in a follow up

**Comment by neilkakkar** [comment]
will accept post-humous reviews, will get this in first to unblock required checks

**Review by jurajmajerik — COMMENTED** [review]
✅

**Pull request merged**
