### PR TITLE
fix(trends): fixes for trends query when comparing it against prod data

### PR DESCRIPTION
**Pull request by Gilbert09**
## Problem
- Using formulas should round the results to 2 decimal places
- Using a bold number display with a previous period was erroring due to missing labels
- Using property filters with materialized columns would return zero data when the column value was an empty string due to how we wrap the columns with a `nullIf(x, '')` and then use that in an `IN` compare operator, which would always return `false` regardless of whether it was a `in()` or `notIn()`

## Changes
- Fixed the above and confirmed the fixes with unit tests

## How did you test this code?
- Unit testsss

### CODE REVIEW

**Review by thmsobrmlr — APPROVED** [review]
This all looks sensible to me. And great to have tests 🙌

**Review by mariusandra — COMMENTED** [review]
It seems like the "in" change is effectively reverting @webjunkie 's changes here: https://github.com/PostHog/posthog/pull/18742/files

The original idea here was to speed things up, as every individual `properties.foobar` makes each query significantly slower. ClickHouse won't "inline" and optimize `JSONExtractRaw` if called multiple times, but keeps doing the hard work of finding the requested 10 bytes out of 1000+ multiple times. 

Is there something else we could do? E.g. wrap the exprs with `ifNull(col, 'EMPTY')` in case we detect a materialized field, or something like that?

**Comment by Gilbert09** [comment]
> It seems like the "in" change is effectively reverting @webjunkie 's changes here: https://github.com/PostHog/posthog/pull/18742/files
> 
> The original idea here was to speed things up, as every individual `properties.foobar` makes each query significantly slower. ClickHouse won't "inline" and optimize `JSONExtractRaw` if called multiple times, but keeps doing the hard work of finding the requested 10 bytes out of 1000+ multiple times.
> 
> Is there something else we could do? E.g. wrap the exprs with `ifNull(col, 'EMPTY')` in case we detect a materialized field, or something like that?

Hmm, yeah, okay, lemme investigate some more.

**Review by mariusandra — APPROVED** [review]
I ran into this when verifying Lifecycle insights. Good news: the verification went mostly well (3 insights were off by one). Bad news: enabling the test account filter returns 0 results in the lifecycle query.

That's because if we compare many hosts at the same with a `not equals`, the following gets added to the query:

```sql
ifNull(
    notIn(
        nullIf(nullIf(events.`mat_$host`, ''), 'null'),
        tuple('127.0.0.1:3000', '127.0.0.1:5000', 'localhost:5000', 'localhost:8000', 'localhost:8001', 'localhost')
    ), 
    0 -- this is the culprit
)
```

We could merge in this PR to revert to the previous code, and immediately solve the problem with the filter. However that won't fix it if users type `properties.$host in ('1', '2')` manually, and $host is null. There are changes we can do to make this work (code [similar to this](https://github.com/PostHog/posthog/blob/2586d27e2996a6c7d7a2403f283a46698be5c663/posthog/hogql/printer.py#L602-L616), but for `in` and `not in`). However, we can merge this in and revisit this as part of performance optimisations later.

**Pull request merged**
