### PR TITLE
chore: more space for descriptions

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We let people enter a 400 character description for a template but then clamp the display to 2 lines.

## Changes

* if there's no image, show a much smaller color block
* let the description fill the space
* let the description scroll

Screenshot 2023-03-01 at 21 58 13

## How did you test this code?

👀

### CODE REVIEW

**Comment by lharries** [comment]
I like the idea of showing the full description but don't think the current proposal looks great. How about instead when you hover over a card with a larger description then it expands to be like this? (I'm happy to take a crack at this if you'd prefer not to do the implementation)

**Comment by pauldambra** [comment]
Most of our visitors are not on phones so we don't need to worry about mobile too much, but if we rely on hover then the mobile interaction gets unclear. What's not great?

We could have blank dashboard on its own row, and then the template cards be double width? 

Alternatively we could leave it as is and see what length descriptions people actually add. 

But I think the the more templates there are, the more the descriptions (or some form of preview) become important

**Comment by lharries** [comment]
> Most of our visitors are not on phones so we don't need to worry about mobile too much, but if we rely on hover then the mobile interaction gets unclear. What's not great?

It's more of a taste thing but it just looks a bit broken to me

I'd probably vote to keep as is and later on work on a proper preview system? Or do the expand on hover.

**Comment by lharries** [comment]
(taking a crack at this now)

**Comment by lharries** [comment]
@pauldambra what do you think? I've added this as a commit to this PR if you could check it

https://user-images.githubusercontent.com/22766134/222437480-db901138-8a37-4b00-9729-f1a4a2a640aa.mp4

**Comment by lharries** [comment]
Need to fix a bit so don't merge just yet

**Comment by lharries** [comment]
I need to fix the object-fit: "cover" bug then should be ready

**Comment by lharries** [comment]
Screenshot Dashboards • PostHog (Google Chrome) 2023-03-02 at 13 51

Will update the transitions to use tailwind then should be done

**Comment by pauldambra** [comment]
Hmmm, yeah, this works better for image + long description 👍 

I think longer term it'd be good to handle this without hover, but that's not gonna be the killer feature for templates 🤣

**Comment by lharries** [comment]
@pauldambra this is now ready to go from my side if you're happy with the code want to merge it?

**Pull request merged**
