### PR TITLE
feat: make the new ticket button more visible for paying users

### PR DESCRIPTION
**Pull request by MarconLP**
## Problem

Priority user             |  Free user | Paid user
:-------------------------:|:-------------------------:|:-------------------------:
2024-04-10 at 01 05 12@2x  |  2024-04-09 at 20 58 48@2x | 2024-04-10 at 01 05 12@2x

### CODE REVIEW

**Review by slshults — COMMENTED** [review]
I like it! The only change I'd suggest (based on the screenshots) would be to change the phrase at the bottom of the `paid user` modal from "`email an engineer`" to `open a ticket` (or vice versa) for consistency with the phrase in the `Priority user` screenshot.

**Comment by corywatilo** [comment]
> or vice versa

Let's do this! We want our customers to feel valued (like they can speak directly to an engineer) and not like a number (ticket), so would love if we can use that phrase in both places. This reflects our brand values/tone too.

For _Priority user_, we can have the headline be "Contact us" with the CTA being "Email an engineer"

**Comment by raquelmsmith** [comment]
Nice! While you're here you could also link up the "submit a bug" button to open the support modal for free users. That's been requested a few times.

**Comment by MarconLP** [comment]
Changed the wording to "Email an engineer" and changed it to show the same view to normal and high-priority customers.

**Review by simfish85 — APPROVED** [review]

**Pull request merged**
