### PR TITLE
added redirection to posthogs website

### LINKED ISSUE #3798: Link logo to homepage in authentication views
## Is your feature request related to a problem?

On signup, login or reset password screens, I'd like to be able to click the logo to visit the homepage.

image

## Describe the solution you'd like

Link it to homepage

### PR DESCRIPTION
**Pull request by samcaspus**
## Changes

Closes #3798

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Review by paolodamico — APPROVED** [review]
Thanks for the PR @samcaspus! @posthog-bot add @samcaspus for code

**Comment by paolodamico** [comment]
@posthog-bot add @samcaspus for code

**Comment by paolodamico** [comment]
@posthog-bot please add @samcaspus for code

**Comment by yakkomajuri** [comment]
@posthog-bot please add @samcaspus for code

**Pull request merged**
