### PR TITLE
Replace taxonomic filter tabs with pills

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- WIP, [goal](https://github.com/PostHog/posthog/issues/5962#issuecomment-984163128), currently here:

- Stopping for today, happy to hand off if anyone wants to continue.

## How did you test this code?

- Clicking around in the browser.

### CODE REVIEW

**Comment by mariusandra** [comment]
Improved the design a bit, and ready for a review.. Still missing compared to the original design: the magnifier icon (and then the infinitely scrolling combined list, but that's for another PR). However with the keyboard icon at the other end, and the placeholder nearly filling the entire row, I'm not sure if this magnifier should be added now.

**Review by clarkus — CHANGES_REQUESTED** [review]
I do think the magnifier icon makes that keyword filter more obvious and that it'd be a good addition. Looks great otherwise!

**Comment by mariusandra** [comment]
All right, we're here now:

**Review by clarkus — APPROVED** [review]

**Review by Twixes — APPROVED** [review]
LGTM

**Pull request merged**
