### PR TITLE
instrumentation: track which filters change

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- Adding properties that denote which filters changes
- this will allow us to measure all user interactions with specific filters for each insight

## How did you test this code?

*Please describe.*
manual QA

### CODE REVIEW

**Review by samwinslow — APPROVED** [review]
LGTM!

**Review by paolodamico — APPROVED** [review]
lgtm! Genuine question, would this work better as an array of changed stuff? We can then do contains, but also graph the entire thing to do more exploratory stuff, but not sure if it'll be more complicated to use.

small feedback, would be helpful to have in the description the motivation/goal of this PR (what do you hope to measure / obtain from this?)

**Review by mariusandra — CHANGES_REQUESTED** [review]
Didn't LGTM, so fixed it 😅.

More precisely, the rerouting of `setAllFilters` via `_setAllFilters` was not necessary, as you can access the previous state of the store in a listener [via a magic 4th function argument and some selectors](https://github.com/PostHog/posthog/pull/6342/commits/75cd6c29ab2bbcac3aab3d840b42ea334d1460a8)... 😄.

I also merged with master.

The only thing missing here is tests for the new functionality.

If you want to send this to posthog as an array or an object is also not my call. I think @paolodamico does have a point with converting it to an object.

**Comment by EDsCODE** [comment]
> The only thing missing here is tests for the new functionality.

@mariusandra What kind of tests should I write for this now? A util test for the helper function or did you mean something different

**Comment by EDsCODE** [comment]
I added info so that the properties stored will be similar to this. So you can always see what the previous value was
```
{
...
changed_path_type: [old path value here],
}
```

**Comment by mariusandra** [comment]
@EDsCODE I meant logic tests. Add to `insightLogic.test.ts` a case that checks when `setFilters` is called, that it dispatches `reportInsightViewed` with the right list of changed filters.

**Comment by EDsCODE** [comment]
Any variants to the payload are considered in the util test

**Review by paolodamico — APPROVED** [review]
lgtm!

**Comment by mariusandra** [comment]
@EDsCODE I'm going to need to ask for changes. The test checks just one basic case, but not that you can run it multiple times and that it'll then only give the changes between the runs. This seems like the essential feature added with this PR, so that's what we should check.

Obviously also checking the `objectsEqual` bit is essential. Perhaps in the future we will want to call loadResults every time a filter was set, even if it's the same. Now we lose all context as to why that line has there

**Pull request merged**
