### PR TITLE
Hotfix for funnel historical trends & histogram being always hidden

### PR DESCRIPTION
**Pull request by samwinslow**
## Changes

Recent changes and likely some mistakes while rebasing / resolving merge conflicts caused 2/3 funnel views (Historical and Time to Convert) to never be shown.

This PR:
- adds a correct selector for the render condition of Steps and Time to Convert, which resolves the issue.
- uses Funnel component instead of FunnelBarGraph which has an additional render condition to delineate Steps vs Time to Convert.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by liyiy** [comment]
Historical trends works now but time conversion is still the steps bar graph :(

**Comment by samwinslow** [comment]
> Historical trends works now but time conversion is still the steps bar graph :(

Fix incoming, just a minute :)

**Comment by liyiy** [comment]
btw we also have a `<Funnel>` component in `Funnel.tsx` that I don't know where it's being used?

**Review by liyiy — APPROVED** [review]

**Review by liyiy — COMMENTED** [review]
⭐

**Pull request merged**
