### PR TITLE
feat(onboarding-1.0): Third party support during ingestion wizard

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

- plugin configuration not able to be centered because i'm re-using the `PluginDrawer` component 

Screen Shot 2022-05-05 at 9 29 19 PM
Screen Shot 2022-05-05 at 9 29 29 PM
Screen Shot 2022-05-05 at 9 30 04 PM
Screen Shot 2022-05-05 at 9 30 14 PM

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by marcushyett-ph** [comment]
Looking awesome, couple of bits of feedback from the screenshots:

* We should probably put a beta label on the Redshift import to highlight it's a bit experimental before people click through
* It would be awesome if we could bring in more of the setup instructions into the modal for segment (e.g.
image
And what would be even more awesome, would be if we could give them their actual PostHog API key here (so they don't need step 2), I'm not sure how they'd actually get their PostHog API key without skipping this step with the current design?
* For these apps it's probably worth highlighting somewhere that they don't support session recording, and you need to also integrate PostHog.js to do that (maybe on the instructions screen for each app)?

Again this looks awesome - so excited to see the impact of this!

**Comment by liyiy** [comment]
> It would be awesome if we could bring in more of the setup instructions into the modal for segment (e.g.

I think there's no DRY way to do this right now, I can definitely copy pasta that text into the modal again if we think it adds value but ideally we could just embed those instructions or something so there's one source of truth. 😁

**Comment by marcushyett-ph** [comment]
I agree it makes sense to have a single source of truth - I don't have a good idea of a way to do that other than we import the markdown directly from posthog.com (but that feels a bit messy).

What do you think in terms of embedding their project API key somwehere? I'm not sure how else else they'd be able to find it (at this stage of setup)

**Comment by liyiy** [comment]
> I agree it makes sense to have a single source of truth - I don't have a good idea of a way to do that other than we import the markdown directly from posthog.com (but that feels a bit messy).
> 
> What do you think in terms of embedding their project API key somwehere? I'm not sure how else else they'd be able to find it (at this stage of setup)

yea! i'll incorporate all the other points 😺

**Comment by liyiy** [comment]
@marcushyett-ph 
Screen Shot 2022-05-06 at 10 04 42 AM
Screen Shot 2022-05-06 at 10 12 34 AM

**Comment by marcushyett-ph** [comment]
Perfect!!

**Pull request merged**
