### PR TITLE
fix(autocapture): ensure `$elements` passed to `onEvent`

### PR DESCRIPTION
**Pull request by hazzadous**
Before calling `onEvent` the plugin does, amoung other things, a delete
on `event.properties` of the `$elements` associated with `$autocapture`.
This means that for instance the S3 plugin doesn't include this data in
it's dump.

We could also include other data like `elements_chain` that we also
store in `ClickHouse` but I've gone for just including `elements` for
now as `elements_chain` is derived from `elements` anyhow.

Note that this also requires merging https://github.com/PostHog/plugin-scaffold/pull/46 
first as we need to add to the `ProcessedPluginEvent` type. Typechecks before this 
happens will be failing.

My making this change was triggered by [an issue a user was having in Slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1658213386222879).

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by yakkomajuri — APPROVED** [review]
thanks for doing this - happy with it provided tests pass

**Comment by hazzadous** [comment]
Failing due to scaffold 1.2.0 changes not already integrated, will have to dig into what’s up tomorrow

**Comment by hazzadous** [comment]
Ok there's more wrong here, I've used the wrong `Element` in the scaffold.

Seems there will be a dependency cycle, and that we either need to move `Element` into the scaffold, or move the scaffold into the plugins-server. I'd prefer the second as I'm not a fan of having to do these parallel PRs 🤔  What do you think @yakkomajuri ?

**Comment by yakkomajuri** [comment]
Ah yes on the scaffold you're using some `Element` that wasn't imported anywhere: https://github.com/PostHog/plugin-scaffold/blob/dfe46f9cb9841e6cef760f62cbad8141d59668ec/src/types.ts#L102

I think indeed there's an annoying dependency here. The easiest is to add Element over in the scaffold actually, because unfortunately the scaffold is not just used by us, it's something that plugin devs use (hence it's a separate package)

**Comment by hazzadous** [comment]
> The easiest is to add Element over in the scaffold actually, because unfortunately the scaffold is not just used by us, it's something that plugin devs use (hence it's a separate package)

Yup I'll do that for now, although having the scaffold code owned by the plugins-server doesn't prohibit i.e. the plugins-server publishing the same scaffold package for use by plugin devs.

**Pull request merged**
