### PR TITLE
Separate Plugins dyno for Heroku

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Add optional `celeryworker` and `pluginworker` dynos that can be individually enabled as needed (default quantity = 0). The default worker dyno (quantity = 1) still launches both worker processes inside itself. 
image

- Had to refactor some CLI scripts to get the Procfile to make sense:
  - Run `docker-worker-beat` from within `docker-worker-celery` if called with `docker-worker-celery --with-beat`. 
  - I needed a single script to call in the Procfile, and I didn't want to add the 21st script in this folder. This way introduces no breaking changes.
  - Removes `bin/docker-worker-plugins` and just calls `bin/plugin-server` directly

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by macobo** [comment]
Can you have all 3 (worker, celeryworker, pluginsworker) working at the same time?

**Comment by mariusandra** [comment]
Yep, just add as many of whatever type you want. 

`worker` will work for most users as it runs both processes in one dyno, though it might get CPU-bound, since it starts 2x the recommended amount of concurrent workers. If `WEB_CONCURRENCY=2` is set, `worker` starts 2x plugins and 2x celery. If this env is not set (not on heroku), both plugins and celery start `nr of cpu cores` workers. The

I imagine you'll get away with one decent `worker` dyno for a while, yet when the load increases you'll want to scale each process type separately. Especially if we move ingestion to the `pluginworker` and still need `celeryworker` to run random python tasks.

**Review by macobo — APPROVED** [review]
Awesome! I think this is fine though we likely want to update heroku docs to reflect this.

Q: Why not put @Twixes as reviewer given you're pairing up?

**Comment by mariusandra** [comment]
Thanks! For things that concern infrastructure and subjective things like naming things I usually prefer to cast a wider net to get more and deeper opinions :).

**Pull request merged**
