### PR TITLE
Limit distinct_id to be 200 char max

### PR DESCRIPTION
**Pull request by tiina303**
## Changes

For https://github.com/PostHog/posthog/issues/8380

Proposing we do option (1) - trimming distinctID (as early as possible).

Note that there are other places where we restrict distinct_id to be max 200 (session recordings & user).

## How did you test this code?

CI added test

### CODE REVIEW

**Comment by macobo** [comment]
Should we also extend client libraries to warn when using distinct_ids longer than that? Can be a follow-up task, though we should issue it.

**Comment by guidoiaquinti** [comment]
> Should we also extend client libraries to warn when using distinct_ids longer than that? Can be a follow-up task, though we should issue it.

+1. I think the fix was going to be in the client library and without doing any sort of truncation post-HTTP200

**Comment by yakkomajuri** [comment]
> +1. I think the fix was going to be in the client library and without doing any sort of truncation post-HTTP200

This isn't a thing. I'm 100% on enforcing this at the lib-level _as well_ but the endpoint is open for people to send requests directly. If we enforce this client-side, the server also needs to account for it. With appropriate docs.

**Comment by guidoiaquinti** [comment]
> This isn't a thing. I'm 100% on enforcing this at the lib-level as well but the endpoint is open for people to send requests directly. If we enforce this client-side, the server also needs to account for it. With appropriate docs.

Client validation + server validation + docs = ✅

**Comment by tiina303** [comment]
Agreed, will create a separate follow-up task for client libraries (which is a bit lower priority) + will update docs

**Review by guidoiaquinti — APPROVED** [review]
I still believe this should not be the fix as we are not sure about the ramifications of silently truncating `distinct_id` without making it obvious to our users via an error message.

Anyway, if you think that is a non-issue I'm 👍 to merge

**Comment by tiina303** [comment]
> I still believe this should not be the fix as we are not sure about the ramifications of silently truncating distinct_id 

The effect for the users is as follows:
1. Most of the times we get longer distinct_ids from `alias`/`identify` calls (in JS we start with the anonymized id which is shorter than 200) or just bad setup/attempt of an attack.
2. For cases where `distinct_id` >400 was used: before there was the event only in CH, person either wouldn't be created or merged. Now we might merge people, who shouldn't be merged if their `distinct_id` differed after the 200th char.
3. For cases where 200 < `distinct_id` < 400 was used: same thing we might be merging people that shouldn't be merged. Note however that before we might not have stored session recordings or linked them properly or whatever the impact of the second location with distinct_id 200 limit was.

There are 24 teams on cloud who have some events where distinct_id > 200, 3 of which have >400.

**Review by yakkomajuri — CHANGES_REQUESTED** [review]
let's add 2 things:

1. A statsd metric showing how many times we truncated an ID
2. A sentry event showing the truncated ID - this we should remove after a while, but just so we see if we've truncated something legit

**Comment by tiina303** [comment]
> A statsd metric showing how many times we truncated an ID

good idea

> A sentry event showing the truncated ID - this we should remove after a while, but just so we see if we've truncated something legit

disagree - we can just look it up from CH what would be truncated and I did do that. If we want we can do the changes to libraries first & then change here.

**Comment by yakkomajuri** [comment]
@tiina303 maybe add the metric here and we get this in?

**Comment by guidoiaquinti** [comment]
As discussed on Slack, we still need this (cc @tiina303)

**Comment by guidoiaquinti** [comment]
Re-re-re-opening this again. Any chance we can push this to the finish line @tiina303? Otherwise, are we ok to close it?

**Comment by guidoiaquinti** [comment]
@tiina303 I'm closing this as stale as I didn't see much traction in the last 3 months and 29 days.

**Pull request closed without merging**
