### PR TITLE
Custom series name in bar value chart

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Fixes a bug in which the custom series name wasn't used in the bar value chart y-axis. Reported by a [user](https://app.papercups.io/conversations/all/6ac66ac1-dda2-4f3a-a7be-63589bc3fd75).

**Default**
Screen Shot 2022-01-06 at 10 39 52 AM

**With breakdown**
Screen Shot 2022-01-06 at 10 40 56 AM

## How did you test this code?
Creating bar value charts with and without breakdowns.

### CODE REVIEW

**Comment by alexkim205** [comment]
Would love to get https://github.com/PostHog/posthog/pull/7872 in first because I've refactored the code so that labels get constructed inside of LineGraph component itself (via chartjs's provided api).  I prefer this to preformatting them and passing them in, as it can lead to duplicate labels/breakdown/compare values (which we've seen happen in the InsightTable, InsightLegends, anywhere we use InsightLabel).

**Comment by paolodamico** [comment]
That's fine @alexkim205, but then can you adjust this PR based on those changes?

**Comment by alexkim205** [comment]
> That's fine @alexkim205, but then can you adjust this PR based on those changes?

no probs ill refactor this once that PR's merged

**Comment by alexkim205** [comment]
This issue was fixed with the refactor in #7872. Closing this one now.

Screen Shot 2022-01-10 at 8 06 20 AM

**Pull request closed without merging**
