### PR TITLE
#724: Export Events to CSV

### PR DESCRIPTION
**Pull request by michlsemn**
## Changes

- Added a CSV renderer to the Event Serializer on the backend.
- Added a button to export the CSV on the frontend.

## Issues

- Due to some React logic that I couldn't follow, whenever a filter is removed from the frontend, it's not removed from the `properties` list, so the filter remains in the export even if it's not in the Events table.
- As of yet, I couldn't find a way to hardcode or set a limit to the number of rows exported in the CSV.

image

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by Twixes** [comment]
Hi! Please ping when this is ready for review!

**Comment by michlsemn** [comment]
Hi @Twixes -- all the code quality checks and tests pass, except for the Cypress tests, apparently because this is a fork:

```
Warning: It looks like you are trying to record this run from a forked PR.

The 'Record Key' is missing. Your CI provider is likely not passing private environment variables to builds from forks.

These results will not be recorded.

This error will not alter the exit code.
```

Do you know how to fix this or can we go ahead and review?

**Comment by Twixes** [comment]
This is really nice! I have a concern about pagination though. 🤔 This seems to only return the first page.

Cypress complains that this is a fork, but that's irrelevant. The errors are because we messed up some test timings elsewhere, not related to this at all so we can disregard them.

**Comment by michlsemn** [comment]
@Twixes Can you try now? I added a check to see if the request is a CSV request. If so, I don't limit the queryset to 100 results. If this ends up working, we can set a hard limit to the number of rows we export as CSV in the alternate branch of that check.

**Comment by timgl** [comment]
We will definitely need a limit of some sort here. Would be good to see how long 100k events take to export for example

**Comment by michlsemn** [comment]
I added a hard limit of 100K to the queryset in the latest commit.

**Comment by Twixes** [comment]
We could maybe allow export of _all_ events with a slightly different solution. Since there could possibly be a large amount of data, we could resort to making the "Export" button start an export background task that'd save the results in an S3 bucket (with a lifecycle police of deleting files after, say, 1 week) and email the user with the link.

**Comment by timgl** [comment]
I agree with the idea however not everyone has smtp set up and not everyone has s3 buckets either. I think the current way makes sense for now, but let's test it.

**Comment by Twixes** [comment]
Ah, yeah, not feasible for self-hosting users. Could do the same internally then and display an exports list in the frontend. That'd be quite a bit of work though, so let's stick to this for now.

**Comment by michlsemn** [comment]
If someone needs access to all events' raw data, isn't it better to simply provide that person access to whatever view/table that contains the events' data? I don't think analyzing potentially tens of millions of rows in a CSV is feasible.

**Comment by Twixes** [comment]
We can't offer direct access to the database on PostHog Cloud, so in fact CSV may be the most efficient way of exporting data there. Analyzing millions of rows from a CSV should actually be quite feasible – only after importing them into another database or a data analysis tool. It could be smart to divide data into, say, ~1 GB chunks, but that shouldn't be a significant problem at the moment.

**Comment by michlsemn** [comment]
Hi @Twixes -- did you get a chance to check the latest changes? Thanks!

**Comment by Twixes** [comment]
I'd delegate authority to @timgl here. If a hard 100k events limit is alright, then we can merge this (preferably with information in a tooltip about the limit).

**Comment by Twixes** [comment]
Actually should be alright for now, if need be, we can always improve it later. :)

**Comment by yakkomajuri** [comment]
Hey @michlsemn! Thanks for the PR! Message me on Slack (Yakko Majuri) or shoot me an email at yakko[(at)]posthog[(.)]com for some merch!

**Pull request merged**
