### PR TITLE
fix: allow user invites to have capitalized email domains

### PR DESCRIPTION
**Pull request by xrdt**
## Problem

See this zendesk ticket: https://posthoghelp.zendesk.com/agent/tickets/11016 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/13668)

Further context on the fix is in the comment. 

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by raquelmsmith — COMMENTED** [review]
I think this is the wrong place to do it, feels like it should be frontend validation / mutation and then also validation on creating the organizationInvite. I think the current `validate` method where you've put this is just for using the invite

**Comment by xrdt** [comment]
The best place to do frontend validation would probably be in the invite modal itself. The emails that are being submitted are valid because users are getting the invite links. These valid emails (e.g. test@Gmail.com) are also being hard coded into the sign up form itself, so making this change on the invite submission made the most sense because there was nothing up to this point to suggest that the form was incorrect or that any of the previous steps were wrong.

**Comment by raquelmsmith** [comment]
Yeah so what I think we should do is fix it before it gets here. When someone submits the form to invite people, lowercase the domains. When the invite is created, again lowercase the domains (because people can invite via the API). That way the invitee sees the correct lowercased email in the form and eliminates questions along the lines of "will my email always have that weird capital letter in it?"

**Comment by xrdt** [comment]
[Invite api](https://posthog.slack.com/archives/C02E3BKC78F/p1712254960879039) appears broken but it works through 
the UI: 

Uploading Screen Recording 2024-04-04 at 11.28.06 AM.mp4…

**Review by raquelmsmith — APPROVED** [review]

**Pull request merged**
