### PR TITLE
feat: Editor panels refactor

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

The Editor Panels (feature flagged still under consideration) are hurting us technically because of duplicated code. This PR aims to fix that by removing the old Tab pages and replacing them with EditorFilters that can either be displayed in the new sidebar way or the old vertical way.

**NOTE**: I don't think this is the "perfect" UI - my goal is to have it "good enough" to merge so that we can solve this technical debt issue as well as get some of the wins from the tweaks done in the EditorPanels work.

## Changes

* Refactored the structure under `/insights/` to be clearer which components are which. 
* Changed over some button styles to be more inline with the standard style

## "Breaking" Changes (i.e. things that were too hard to keep the same)
- [ ] User Paths has the new UI (personally I think it is better anyways
- [ ] Many of the buttons have been changed to LemonButtons - plus side is they all look the same now
- [ ] Filters doesn't have the Advanced Options dropdown. The options are simply shown
- [ ] The lines separating different sections are gone

|Before|After|
|----|----|
|Screenshot 2022-06-27 at 15 12 37|Screenshot 2022-06-27 at 15 12 32|
|Screenshot 2022-06-27 at 15 16 28|Screenshot 2022-06-27 at 15 16 21|
|Screenshot 2022-06-27 at 15 16 42|Screenshot 2022-06-27 at 15 16 38|
|Screenshot 2022-06-27 at 15 17 00|Screenshot 2022-06-27 at 15 16 54|
|Screenshot 2022-06-27 at 15 18 44|Screenshot 2022-06-27 at 15 18 24|
|Screenshot 2022-06-27 at 15 17 41|Screenshot 2022-06-27 at 15 17 38|

## How did you test this code?

Mostly visual swapping between the old and the new to get an idea of how different it really is

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
Seems like the major value here is simplifying iterations in the future via code cleanup. The resulting UI looks like it'll work for now 👍

**Comment by mariusandra** [comment]
@benjackwhite is this draft or ready for review?

**Comment by benjackwhite** [comment]
> @benjackwhite is this draft or ready for review?

It's ready I would argue. Still not 100% sure on the folder re-structuring but that might be better left to a "Nail Insights" sprint...

**Review by mariusandra — CHANGES_REQUESTED** [review]
Looks great! Just some things:
- we seem to have a pattern where all folders inside `frontend/src` are lowercase, except when they represent a component. In that spirit, I'd also rename `scenes/insights/Filters/` and `scenes/insights/Views` to `filters` and `views` accordingly.
- should we also bite the bullet and remove `EF` from the name of all the classes? It's kind of redundant now that EF-s are the only way to F an insight while E-ing.

**Review by mariusandra — APPROVED** [review]
YEET!

**Pull request merged**
