### PR TITLE
Changed tone on action creation buttons

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

I agreed with @paolodamico on his first point from #1529. 

### Before
before

### After
after

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Review by paolodamico — APPROVED** [review]
This is great @yakkomajuri! I just updated the class name to `btn-action` to follow the naming convention of the rest of the project

**Comment by yakkomajuri** [comment]
Yeah that's fine, the reason I didn't go with 'btn' first is because I thought that could be confused with Bootstrap buttons, since this is just for an overriding attribute, rather than an actual full button styling.

**Comment by paolodamico** [comment]
> Yeah that's fine, the reason I didn't go with 'btn' first is because I thought that could be confused with Bootstrap buttons, since this is just for an overriding attribute, rather than an actual full button styling.

That makes sense, maybe then something like `btn-override-actionable` or something around that could be more informative? It's such a minor point we might just carry on like this

**Comment by yakkomajuri** [comment]
Yeah it's a small thing, just proceed however you prefer - far from a big deal

**Pull request merged**
