### PR TITLE
Launch toolbar

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

I think we need an easily accessible button to open the toolbar. There will be cases when it won't load automatically. You might just be logged out... or  a present or future browser/cookie/etc issue manifests itself. The natural thing I would do would be to go to my posthog app to make sure I'm logged in. Having a button that just opens my site again will be of great help. Especially if it fixes the problem.

This PR adds a colorful "Launch Toolbar" button on top of the sidebar:

image

This still has some issues, like the "add url" box looks bad if you don't have any URLs. I'm open to suggestions on what would be in there.

image

I must add cypress tests as well.

However... OK for the idea in general?

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (**MISSING**)

### CODE REVIEW

**Comment by timgl** [comment]
Makes sense! I think our sidebar is getting crowded (esp with a lot of dashboards) but agree an easy way to launch toolbar is good.

I also see you're only showing this to users who've opted into beta. I actually think we should show this to everyone, and if they click this we can show a modal with a little explainer and opt them into the beta.

**Comment by mariusandra** [comment]
Yeah, that definitely makes sense to show this to everyone! If nothing else, the next release should feature the toolbar more prominently (even if there are no other changes in it) so we could gather even more feedback. Not that many people have been using it so far.

**Comment by mariusandra** [comment]
Hi! This is ready to be reviewed. Please update the texts and add whatever you'd like to change.

**Comment by Twixes** [comment]
Cleaned up the UI a bit.

Before | After
-------|------
Before 1 | After 1
Before 2 | After 2
Before 3 | After 3

**Pull request merged**
