### PR TITLE
Updated demo data generation

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Submitting this without the CH implementation in the spirit of keeping PRs smaller.

### What this does

- Improves revenue data generation
- Adds app data generation
- Makes generation possible via both /demo and management commands 

This also implements @timgl's feedback about the "HogFlix concept", with `watched_movie` events, and subscription plans mirroring Netflix's basic, standard, and premium.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Was limited on time - CH might still have a few rough edges

**Comment by macobo** [comment]
Let me know if I can help with this somehow.

**Comment by yakkomajuri** [comment]
I mean I haven't had time to look back at this, but it should all work. I just wondered if there were some minor improvements to be done on the ch side but it should all be working

**Comment by macobo** [comment]
:) The changes were rolled into the above PRs.

**Pull request closed without merging**
