### PR TITLE
fix(experiments): secondary results with average count fix

### PR DESCRIPTION
**Pull request by liyiy**
## Problem

Secondary metrics that used an "average" (count per user, count per property value) math option on it were returning the total count instead of average number 

`Property value [average]` aggregations seem to just use regular "avg" math operators
## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by neilkakkar** [comment]
missing tests!

**Comment by liyiy** [comment]
> missing tests!

is there a test for the original `count_per_user` function? 👀 I was looking for them to add this one to, if not I can add both in a bit lol

**Comment by neilkakkar** [comment]
definitely exist ;) -> all right here: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/test/test_clickhouse_experiments.py#L2256

**Comment by liyiy** [comment]
> definitely exist ;) -> all right here: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/test/test_clickhouse_experiments.py#L2256

should've never doubted 🤣

**Comment by neilkakkar** [comment]
oh wait sorry, if this is only applicable to secondary metrics, then this is the place: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/test/test_clickhouse_experiment_secondary_results.py#L387

**Pull request merged**
