### PR TITLE
fix: allow choose another dashboard template after pressing back

### LINKED ISSUE #20784: Cannot choose another dashboard template after clicking `back`
## Bug description

https://www.loom.com/share/0de89dfd80794df3842a7087824fbd94?sid=9c4508fb-9a85-4960-95a8-a37ed9c6ab36

## How to reproduce

1. Try to create a new dashboard from the `AARRR` dashboard template
2. Click `back`
3. Try to select another template

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/11437

### PR DESCRIPTION
**Pull request by nikitaevg**
## Problem

Fix https://github.com/PostHog/posthog/issues/20784.

This was caused by the following:
1. `isLoading` is [set to true](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/DashboardTemplateChooser.tsx#L63) on selecting a template.
2. It's not set to false on pressing "back", so `onClick` [returns early](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/DashboardTemplateChooser.tsx#L61), I confirmed it via debugger.

## Changes

Listener for the "Back" button is described [here](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/NewDashboardModal.tsx#L64), so I set `isLoading` to false on `clearActiveDashboardTemplate`.

## Does this work well for both Cloud and self-hosted?

N/A

## How did you test this code?

Here's [before](https://github.com/PostHog/posthog/assets/6707908/55d43fb5-7d9d-4c90-9fa8-56a519c3c3e1), [after](https://github.com/PostHog/posthog/assets/6707908/20be62d5-12f0-4efe-862d-63cdd611653a).

Could you please guide me if I could add tests for this anywhere? I don't think it makes sense to test it in [newDashboardLogic.test.tsx](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/newDashboardLogic.test.tsx), as this functionality is spread across [newDashboardLogic.ts](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/newDashboardLogic.ts) and [DashboardTemplateChooser.tsx](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/DashboardTemplateChooser.tsx), and I couldn't find tests that cover both of them. I also haven't found tests corresponding to this module in the commit history.

### CODE REVIEW

**Comment by nikitaevg** [comment]
Hi @pauldambra !

I want to start contributing to PostHog, so I'm picking simple tasks to get acquainted with the project. Could you please review this PR as the latest contributor to this file, or assign somebody else? Thank you!

**Comment by pauldambra** [comment]
> Could you please guide me if I could add tests for this anywhere?

You could add tests in [newDashboardLogic.test.tsx](https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/frontend/src/scenes/dashboard/newDashboardLogic.test.tsx), but it isn't currently testing the kea logic in there so adding a test only for `isLoading` being false after calling `clearActiveDashboardTemplate` feels unnecessary

You _could_ add a Cypress test to validate this works. That's the best place for tests that validate the interaction between components and logics 

We only have a very basic test on top of templates here https://github.com/PostHog/posthog/blob/92e17ce307a577c4233d4ab252eebc6c2207a5ee/cypress/e2e/dashboard.cy.ts#L90

So - since you want to learn how to contribute to posthog - you'd need to add a Cypress intercept so that the template modal had a template with a variable, then test that clicking that new template moves to the variable form in the modal, and finally that click back and selecting a template again works

I've manually tested this PR so I'd be happy to accept it without a test, but if you want to learn how to contribute on more complex fixes I'm also happy spending time reviewing changes to Cypress tests :)

**Comment by nikitaevg** [comment]
Thanks for the guidance @pauldambra 

PTAL again, I added a test. What's the best way to request a review once again? Just mentioning a reviewer? I couldn't find it in the tutorials.

**Comment by nikitaevg** [comment]
FYI, I see there's a [failure](https://github.com/PostHog/posthog/actions/runs/8508236359/job/23306950231?pr=21248) in a not related e2e test, which seems to be a flake, because it happens with other PRs. I'll fix it in https://github.com/PostHog/posthog/pull/21259.

**Comment by nikitaevg** [comment]
Hi @Twixes! Kind reminder here, could you please review this?

**Review by Twixes — APPROVED** [review]
This works, thank you for the contribution! Apologies for the delay on this, I 100% dropped the ball on reviewing in a timely manner. Will do better next time!

**Comment by nikitaevg** [comment]
Thanks for the review @Twixes and no problem! 

The merge looks stuck though, is there something I should do? The failing tests are probably flakes, as I don't touch the backend part here.

**Pull request merged**
