### PR TITLE
Clarify unique users vs. total count

### LINKED ISSUE #6275: Confusion over metric definitions erodes trust
## Is your feature request related to a problem?

We receive a significant number of issues that 

**Example 1: Moving from trends to funnels**

By default we show a total count of metrics in trends, e.g. total number of page views in a day.

image

However if you switch to using funnels we also switch the aggregation to unique users (this is standard behavior for a funnel product). This shows a wildly different number, e.g. 100,000 page views a day, might only come from 10,000 users - and clicking between them makes it look like you've just lost 90,000 events and our data is unreliable.

In a user's own words:
"In the trends section...we have (a large number) of events...However, when trying to create a funnel with the exact same parameters...the specific event only shows (a small number) occurrences. I have debugged this for hours...and I cannot find anything that would create this behavior"

**Example 2: Persons modal vs trends**
Similar to example 1, if I look at a trends graph I may see the total number of events at any point in time (depending on how I configure it). However as soon as I click on a data point I get a modal with a list of the people who completed this event. This is going to be much smaller than the number of events which occurred (and can make it feel like data is missing).

## Describe the solution you'd like

I'd love a consistent solution that makes it abundantly clear how any metric is being processed or aggregated to avoid confusion when using a different aggregation of the same metric.

### Hacky quick fixes I have in mind

1. Where we use unique users by default - we also show the Total Count

In the persons modal
image

When I open a funnel (N.B. this is super-ugly there should be a way to do this much better)
image

2. We visually signify the type of aggregation in use in a way its unmissable

image

image

image

(again very ugly version - there must be a nicer way of doing this for funnels)
image

## Describe alternatives you've considered

@clarkus has already briefly shared a few options to consider over DM - would love to explore these futher

## Additional details

Would appreciate any feedback on the quick fixes proposed and more robust solutions

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Closes #6275. Initial stab at fixing this issue. Implements a bunch of different changes.

**Person modal.** (the total count is only shown when "Total count" is selected as math operator).

**Funnels new view**

**Funnels step table**

**Funnels tooltip**

**Funnels legacy**

**Funnels vertical**

## How did you test this code?

Manually tested a bunch of different cases:
- Feature flag on/off: `5730-funnel-horizontal-ui`
- Feature flag on/off: `5733-funnel-vertical-breakdown`
- Vertical/horizontal funnel configuration
- Postgres & Clickhouse versions.

### CODE REVIEW

**Comment by paolodamico** [comment]
Feels natural to tag @marcushyett-ph & @clarkus for a UX review & @mariusandra for a code review, but feel free to mix and match :wink:

**Comment by marcushyett-ph** [comment]
Wow this is super fast and - makes a huge difference (especially on the persons modal)

**Review by mariusandra — APPROVED** [review]
LGTM!

**Review by clarkus — APPROVED** [review]
LGTM - the addition of a unit for the l-t-r funnel layout might run into some scale issues when breakdowns are applied, but I think that's something we can watch for and spot-fix if it becomes an issue.

**Pull request merged**
