### PR TITLE
chore: don't add cypress because it does change image size

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We don't include Cypress in the package.json because of concerns over the final image size. This makes the e2e test runner more complicated and slower than it needs to be

## Changes

In #10371 we added image size output to the docker image test job. The image size in that job was 4.47GB

This PR adds Cypress as a dev dependency. With it the image size was 4.97GB. 500MB more!

## How did you test this code?

opening the PR

### CODE REVIEW

**Comment by macobo** [comment]
Note that 5GB is huge and there's an existing backlog task to clean this up - this affects _everything_ from first installs to local dev on charts and that 500MB is not free.

Instead going this route, does this need to be a dependency not a `devDependency`? Perhaps we can improve our CI pipeline.

**Comment by pauldambra** [comment]
Well that answers that question @benjackwhite @Twixes 

500MB more with Cypress as a dev dependency

**Comment by pauldambra** [comment]
@macobo yep, we were just testing to see what impact this would have. I agree it's not worth the simplification in the test runner to stand the extra size

**Comment by benjackwhite** [comment]
I think this is awesome work though because now we can try out multi-stage docker builds and still have cypress dev dependencies which simplifies local dev massively

**Comment by pauldambra** [comment]
Yep, I think I'll close this but we have a way of measuring it now!

(@macobo I see the confusion from the title change. The first time I ran the build I thought it had no impact. I must have looked at a previous output. Re-ran to confirm and saw the consistent 500MB)

**Pull request closed without merging**
