### PR TITLE
Fix papercups

### PR DESCRIPTION
**Pull request by timgl**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by Twixes** [comment]
A ha, I was literally about to message you about this. 😄 I [accidentally made the fix directly in master](https://github.com/PostHog/posthog/commit/2c242abdcb7feba2ce5b9c4bb84297ab9762ace9) and didn't notice the mishap in that commit. Might be safer to make master protected. 🤔

**Comment by Twixes** [comment]
Ah, I see it's protected now! But also I can't merge in pull requests, which, as opposed to direct commits, should be allowed.

**Comment by timgl** [comment]
Yeah merging directly to master obviously isn't great. The annoying thing is you can't protect master without requiring approvals

**Comment by timgl** [comment]
@Twixes Actually I've managed to do this, just needed to 'require' a couple of status checks.

**Pull request merged**
