### PR TITLE
Add padding to WhoAmI

### PR DESCRIPTION
**Pull request by florymette**
Hi, this is my very first pull request! 
I tried following the guides, please let me know if anything should be done differently:)

## Changes
This adds a little bit of padding to the WhoAmI component.

This fixes issue #6293

image

## How did you test this code?
I tested this on mac on different screensizes

### CODE REVIEW

**Review by paolodamico — CHANGES_REQUESTED** [review]
Thanks for the contribution @florymette! Think it'd be better to update the `.whoami` CSS class instead of setting the style directly to avoid mixing here. Also worth running `prettier` in your code to make sure everything is spaced out nicely.

**Comment by Twixes** [comment]
I would actually advise against changing `.whoami` (which is needlessly specific for a layout improvement) and instead go for higher-level `.navigation-top`. Let's add just a bit of sideways padding there with `padding: 0 8px;` BUT only on bigger viewports (the padding wouldn't look great on mobile, and mobile devices don't have scrollbars anyway) – basically also just `padding: 0;` inside the `media (max-width: 991px)` query.

**Comment by florymette** [comment]
Thank you for the feedback! I moved the styling to the stylesheet like @paolodamico suggested. Not sure if you would rather like that or prefer @Twixes suggestion. At any rate, the pullrequest has been updated :)

**Comment by paolodamico** [comment]
Thanks @florymette! I think @Twixes suggestion makes a lot of sense, would you like to make those changes? Happy to help get this over the line too. Let us know how you want to move forward.

**Pull request closed without merging**
