### PR TITLE
[patch] Fix api jest test

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- https://github.com/PostHog/posthog/pull/7287 introduced jest tests for our api class
- The api class returns an empty response if the URL is useless. The jest tests have dummy urls and the empty return isn't handled properly

*If this affects the frontend, include screenshots.*  

## How did you test this code?

*Please describe.*
Locally broken tests works now

### CODE REVIEW

**Comment by EDsCODE** [comment]
❓

**Review by hazzadous — CHANGES_REQUESTED** [review]
Can we, rather than change the runtime code, update the tests to return a mock response object. What do you think @pauldambra ?

**Comment by pauldambra** [comment]
Hmmm 🤔 , it's a good point that it tends to be better to bend the tests than prod code... I guess the question is whether the case ever comes up in reality or if its an artefact of test setup?

**Comment by pauldambra** [comment]
Ah, so this addresses this output when running the tests: `UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read properties of undefined (reading 'ok')".`

**Comment by pauldambra** [comment]
added an alternative rather than type code into a comment :) @hazzadous @EDsCODE

**Review by hazzadous — APPROVED** [review]
assuming the tests pass lgtm

**Pull request merged**
