### PR TITLE
Default set debug=1 to bin/start

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Buddy ran into this while running ./bin/start. No reason not to set this.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Is there a possibility someone uses `./bin/start` in prod?

**Comment by Twixes** [comment]
I don't think `bin/start` has production usage anywhere (certainly not proposed by us), but it's also not clear that it's for dev usage, so I'd either keep it as is OR add `DEBUG` _and_ rename it to `bin/start-dev` to make sure there's no confusion.

**Comment by timgl** [comment]
I suggest merging this. If you run this you'll get an error message saying you're running in DEV mode so feels safe.

**Comment by timgl** [comment]
I think this is fine to merge. You get some pretty big error messages if you use this with DEBUG=1.

**Pull request merged**
