### PR TITLE
Add Pie chart, improve trends graph layout and other small fixes

### PR DESCRIPTION
**Pull request by timgl**
@jamesefhawkins Would love QA

- Added Pie chart
- Changed the way we calculate the height of the charts (so check there's no overflow issues)
- Changed layout a bit to make more consistent with rest of site
- Added loading indicators to Dashboard

### CODE REVIEW

**Comment by jamesefhawkins** [comment]
@timgl could you add my posthog.com email to Heroku please so I can set up an environment? For some reason it isn't deployed.

**Comment by timgl** [comment]
done

**Comment by jamesefhawkins** [comment]
# Invalid (bug?)

Screenshot 2020-02-25 at 16 22 40

If there is any kind of breakdown, I cannot switch to the pie chart - I can select it, but then I end up at the table again. I would expect to see the breakdown as the pie chart.

It does however work if you do not apply a breakdown.

I'd suggest not making the pie chart selection available for now if there is a breakdown applied. Then we can add an issue for displaying pie charts of the breakdown in the future.

**Comment by timgl** [comment]
This is fixed, so merging.

**Pull request merged**
