### PR TITLE
Upgrade rrweb

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Upgrade rrweb to a set commit to fix a few issues.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by neilkakkar** [comment]
I think the main crux is in `posthog-js` where the recordings happen? I'll put up a PR there and test that out on  [this](https://github.com/rrweb-io/rrweb/issues/528#issuecomment-813809703) sample project.

**Comment by neilkakkar** [comment]
.. I see, my bad, looks like the extension loads the script `/static/recorder.js` which is on the main PostHog repo....

**Comment by neilkakkar** [comment]
Just finished testing, can confirm this specific rrweb commit resolves the issue.

**Comment by timgl** [comment]
Closing in favour of #4442

**Pull request closed without merging**
