### PR TITLE
chore: bucket recordings chunks lengths into a prom histogram

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We chunk recordings so that they fit into kafka but have no visibility of (or at least we're not looking at) how many recordings are chunked and how many chunks they have...

## Changes

puts that into a prometheus histogram

## How did you test this code?

🙈

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
Given that this gets called on every capture call for recordings I would love a sanity check from @PostHog/team-pipeline

**Review by benjackwhite — APPROVED** [review]
Given that this gets called on every capture call for recordings I would love a sanity check from @PostHog/team-pipeline

**Comment by pauldambra** [comment]
My understanding is that this is called on every capture but nothing happens. And then Prometheus scrapes the metric periodically

So the local call is 🤞cheap

With A gauge only the last value when the scrape happens ends up in Prometheus

Whereas with histogram all the values in the bucket arrive (which depending on scrape frequency) could be large numbers but will only be ten ISH large numbers

**Comment by hazzadous** [comment]
Yeah it's just a local thing, until prom scrapes so you shouldn't need to worry about adding to tight loops so much.

**Comment by pauldambra** [comment]
We only need this for a few days to get the data also

**Pull request merged**
