### PR TITLE
Force frontend to build on ./bin/start-frontend

### PR DESCRIPTION
**Pull request by fuziontech**
## Changes

Many users have been having isues with PostHog not building the frontend and ending up with a blank page forever.

This PR tries to fix that. It's a bit of a WIP currently.

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by timgl** [comment]
I'm not sure but these issues _might_ be because it takes a long time to build. This might make that worse

**Comment by fuziontech** [comment]
Agreed. Doing some tests on a new docker-compose setup to do some testing (why this is WIP)

**Comment by fuziontech** [comment]
My next step was to setup a landing page when it's in `debug` that basically says 'frontend is being baked fresh just for you. This should only take a few minutes'

**Comment by mariusandra** [comment]
https://www.snowpack.dev/ - we could try this

**Comment by fuziontech** [comment]
>Develop faster, with a dev server that starts up in 50ms or less.

That sounds nice

**Comment by fuziontech** [comment]
Didn't work 😢 Going to work on either landing page or this snowpack builder

**Comment by mariusandra** [comment]
I think https://github.com/PostHog/posthog/pull/1921 could have solved the root cause here?

**Pull request closed without merging**
