### PR TITLE
fix(plugin-server): call required methods on rebalanace to actually a…

### PR DESCRIPTION
**Pull request by bretthoerner**
…ffect assignments

## Problem

We are using a librdkafka `rebalance_cb` that is a no-op. This callback isn't just something called after librdkafka does all of it's magic, it _replaces_ the rebalance code, meaning our consumer is obligated to actually do the right thing with the assignments it is passed.

In my understanding, this could easily have caused the duplicates that were previously observed in prod. A few thoughts:

1. I still don't understand how a consumer would ever obtain partitions with this code broken. I feel like there must be a separate code path for a new consumer that doesn't go through the `rebalance` path? I'm trying to track this down still.
2. If I understand what a no-op rebalance callback does (well, doesn't do), once a consumer was running with some partitions, it would never add or remove new ones based on `rebalance`s.
3. 1 and 2 above combined = dupes?

Regardless, something seems wrong here and warrants more investigation.

## Changes

Call `consumer.assign()` and `consumer.unassign()` as expected.

librdkafka rebalance_cb docs: https://docs.confluent.io/platform/current/clients/librdkafka/html/rdkafka_8h.html#a10db731dc1a295bd9884e4f8cb199311

Note that there are a lot of confusing and slightly conflicting implementations of this found within librdkafka wrappers. I have chosen to base the code on the C++ librdkafka example. I still need to handle the incremental cases if we plan to use the cooperative strategies.

* C++ librdkafka example: https://github.com/confluentinc/librdkafka/blob/49f05db36e5bff78e856e33da951a5f998f9d55b/examples/rdkafka_complex_consumer_example.c#L191-L241
* node-rdkafka fallback when `rebalance_cb = true` (weird???): https://github.com/Blizzard/node-rdkafka/blob/d521e0f1f3695911dee13ba632859b071b553ab9/lib/kafka-consumer.js#L62-L73
* node-rdkafka docs example: https://github.com/Blizzard/node-rdkafka#rebalancing

An alternative is to _not_ set a `rebalance_cb` at all, so that we stick to default librdkafka logic. That could be handy in the short term (it should fix things without changing our current behavior aside from logging). But I think we _do_ want to a rebalance callback so that we can either throw away or complete in-progress work properly (medium to long term, anyway).

## How did you test this code?

CI

### CODE REVIEW

**Comment by bretthoerner** [comment]
Huh, it looks like recordings has their own callback assigned last, which is why things may work for them.

It's worth noting that they're getting lucky. Only one `rebalance_cb` is supported.

1. The first is set here (this is the no-op replacement that would break event ingestion): https://github.com/PostHog/posthog/blob/c9b1b4f5cd97385d0613043b414bd5ca6d31e170/plugin-server/src/kafka/consumer.ts#L82
2. Recordings then sets another here: https://github.com/PostHog/posthog/blob/43865778da19cf1d09911ae229981dbfdde6396c/plugin-server/src/main/ingestion-queues/kafka-metrics.ts#L90-L99
3. And it is finally replaced by the working: https://github.com/PostHog/posthog/blob/6bf7342217cbac351c4e8c3e6991e481a4a4ec4c/plugin-server/src/main/ingestion-queues/session-recording/session-recordings-consumer-v2.ts#L411-L473

**Comment by benjackwhite** [comment]
@pauldambra this could affect Mr Blobby especially if some assignments are not as we expected. Would be good to validate the actual impact of this and whether the recordings ingester is affected given they all use this code.

**Comment by xvello** [comment]
Thanks for digging into this @bretthoerner!

The code you are pointing to are [event listeners](https://nodejs.org/api/events.html), that one can register any number of.
These events are emitted by node-rdkafka's [default cooperativeRebalanceCallback callback](https://github.com/acosom/node-rdkafka-acosom/blob/c1435e9cac4759a99d21f4f2f3c61b394a4626ff/lib/kafka-consumer.js#L43-L62), because AFAIK we don't override that callback. It's worth auditing that callback code for a bug or race condition though.

My mental model (that could be wrong, worth triple-checking) is that:
  - rdkafka gets rebalance instructions from the broker
  - it calls node-rdkafka's `cooperativeRebalanceCallback`
  - that callback emits a `rebalance` event
  - all registered listeners are called `synchronously`. If one of them were to throw, I'm not certain that the rest of `cooperativeRebalanceCallback` would be executed though
  - after all event listeners return, `cooperativeRebalanceCallback` calls `incrementalAssign` / `incrementalUnassign` for us

BTW, this means that when our event listener is called, the consumer's assignment state is not yet updated. We cannot just pull it to build a Set of the partitions, like I suggested.

We should also abort the ongoing batch, but don't be too eager to start the next one, otherwise the consumer queue might have not been flushed yet. Let's put a pin on that as a future optimization, but not the main focus.

**Comment by xvello** [comment]
Based on that investigation, I think the next step is auditing the C++ code [added in the acosom fork](https://github.com/Blizzard/node-rdkafka/commit/d521e0f1f3695911dee13ba632859b071b553ab9) so a possible bug, leading to partitions not being properly unassigned. The PR adds a couple of tests already, but an edge case might not be covered.

There's new commits since this one, so let's check the actual revision we're executing.

**Review by xvello — CHANGES_REQUESTED** [review]
Marking as don't-merge, see earlier comments confirming that this part is already handled by the node-rdkafka wrapper. We now need to audit that is does the right thing.

@benjackwhite @pauldambra for context, we're auditing the code and adding more instrumentation before our fourth attempt at moving over plugins-ingestion to rdkafka.

During our last attempt, we noticed a significant increase in events going to CH, becoming steadily higher than events captured. One possible explanation for this would be a bug in partial unassignments, were a rebalance would lead to two consumers processing the same partition.

We don't see that issue happening on recordings v1 [[input volume === output volume]](http://grafana-prod-us/d/vm-kafka-overview/kafka-cluster-overview?orgId=1&var-job=kubernetes-pods&var-release=analytics-kafka-exporter&var-instance=All&var-topic=session_recording_events&var-topic=clickhouse_session_recording_events&var-topic_detailed=__amazon_msk_canary&viewPanel=4&from=now-7d&to=now), I'd lov your input on whether a blobby metric could confirm it's not happening there either.

**Comment by bretthoerner** [comment]
> The code you are pointing to are [event listeners](https://nodejs.org/api/events.html), that one can register any number of.

Ahhh, thanks. I definitely lost the thread between `rebalance_cb` and the `on('rebalance')` events. That makes a lot more sense. :)

**Comment by bretthoerner** [comment]
In that case, I'm going back to adding metrics. As another data point I did put up a PR with the latest Blizzard node-kafka, and tests fail, to my surprise: https://github.com/PostHog/posthog/pull/17378

The diff in both direction (what's only in Blizzard and what's only in acosom) didn't really have anything that stood immediately out to me, but I'll have to dig in deeper now.

**Pull request closed without merging**
