### PR TITLE
feat(flags): Add rate limit to decide endpoint

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

We need a way to discard excessive requests from a single team - which can potentially bring the system down by hogging all postgres resources.

This _should_ help us shed extra load without borking. I think a rate limit like this might work better not at django level, but gunicorn or nginx level, but haven't experimented with that, unsure of trade-offs.

Some things I've chosen not to do in this PR, which I might revisit after validation:

1. The current rate limit algorithm is not very efficient, and is very prone to race conditions. I will revisit this if it turns out to be a problem. In effect, this means a small (maybe big?) no. of requests over the rate limit will make it through. I want to test this sheds load effectively first, before trying to optimise the algo.
2. There's no real exceptions for orgs we want to allow through the limit.

Will test on dev to answer the following questions - could use @PostHog/team-infra help in validating these:

1. Does gunicorn request queue fill up?
4. Does this stop the healthcheck from occuring, thus making pods unavailable?

The main goal is to ensure pods don't become unavailable, so the request queue must continue processing quickly, which I expect it can if it's not being delayed by database i/o, which it shouldn't be if the rate limits work well, because we'll discard before any database queries.

For testing, since the env vars don't yet exist in prod, it should be safe to push this code without borking anything.

## Changes

Introduces two env vars: `DECIDE_RATE_LIMIT` to change rate limits, and `DECIDE_RATE_LIMIT_ENABLED` which decides whether rate limits should apply or not.

Rate limiting happens as part of decide short circuit middleware, so it occurs before any request processing.

We rate limit by the team token, and when no token is found, by request IP instead.

depends on: https://github.com/PostHog/posthog-js/pull/621

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Lots of unit tests.

### CODE REVIEW

**Review by ellie — APPROVED** [review]
Seems reasonable! Though we may wish to allow bursts/etc in the future? Unclear how the rest framework limiter functions, but token bucket is usually good: https://en.wikipedia.org/wiki/Token_bucket

**Comment by ellie** [comment]
also

> Does gunicorn request queue fill up?

Yes, but if we are servicing requests very quickly (eg with a limit) then this becomes less of an issue

> Does this stop the healthcheck from occuring, thus making pods unavailable?

Also yes, arguably rightly so - the pods are not healthy. We need to figure out a way around this, if not async processing. So much iowait in our app :(

**Comment by neilkakkar** [comment]
It's a somewhat-terrible fixed window algo, so definitely not great. Yep, token bucket / gcra would be ideal! Just didn't want to get bogged down yet with implementing a rate limiter.

Yeah, so for the validation, what I'll do next is: set these env vars on dev, send a thousand requests on dev, and then I'd like us to check metrics to confirm the rate limit is effective in quickly shedding load & allowing health check to pass -> when I do the stress test, I'd like your help in confirming our assumptions. I'm assuming we'll check here: http://grafana-dev/d/kubernetes-deployment/kubernetes-deployment?orgId=1&var-namespace=posthog&var-deployment=posthog-decide ?

**Comment by hazzadous** [comment]
@neilkakkar fwiw we're using token bucket in https://github.com/PostHog/posthog/blob/e2da984ff53dbfb0924d741c5c23cf0494d46004/posthog/api/capture.py#L41 already, in case that was relevant or useful.

**Comment by neilkakkar** [comment]
amazing, now I know what to switch to, instead of build, thanks!

**Comment by hazzadous** [comment]
It's within process however so not global.

**Comment by neilkakkar** [comment]
yeah, just saw that. This is an interesting problem - this token bucket loses in precision, but gains in speed and effective shedding, which might be a very worthy trade-off to make for decide, since we don't have strict requirements here, and only worry about pods not going down. Can suck a bit for end users though, depending on how they're routed to pods.

Will think over this.

**Comment by neilkakkar** [comment]
I think I can create a new storage here to work on redis, get the best of both worlds.

**Pull request merged**
