### PR TITLE
feat(debug): add insight metadata to queries

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Changes

TODO: 
- [x] ~Clarify with @webjunkie if it is a good idea to use these ids for queries that might have been created ad-hoc e.g. when just changing the date range?~ Rather not attribute them

Screenshot 2024-07-18 at 23 27 05

- [x] clarify if insight_id and dashboard_id can be used for queries when editing the insight -> also not
- [ ] clarify how to mark new / ad-hoc insights

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by webjunkie** [comment]
Insight and dashboard id are used to guide the cash warming, meaning the worst that happens is pushing the cache target date out. So it's not entirely correct to use it. On the other hand edits and date adjustments mostly happen right after the insight was used anyway, so maybe the effect is minimal?

**Comment by thmsobrmlr** [comment]
@webjunkie Am I assuming right that this can be closed now that you added this info in the hackthon project?

**Comment by webjunkie** [comment]
Ah sorry, wanted to reply yesterday. I added the info to the query logging. But I still want to associate the insight ID with queries coming from the query endpoint, which is currently not happening. So refreshes via the query endpoint are not attributed. I can look int it!

**Comment by thmsobrmlr** [comment]
> Ah sorry, wanted to reply yesterday. I added the info to the query logging. But I still want to associate the insight ID with queries coming from the query endpoint, which is currently not happening. So refreshes via the query endpoint are not attributed. I can look int it!

Got it, thanks! Would be great if you can look into it.

**Comment by webjunkie** [comment]
Okay I added a check, but got a bit confused in the process... the only time we need to attribute it to an insight is if they go to the insight and it doesn't refresh by itself (via async on the load) and they click refresh. Is that it? Otherwise all cases are date changes, filter changes, whatnot, we can hardly discern these.

**Comment by thmsobrmlr** [comment]
> Okay I added a check, but got a bit confused in the process... the only time we need to attribute it to an insight is if they go to the insight and it doesn't refresh by itself (via async on the load) and they click refresh. Is that it? Otherwise all cases are date changes, filter changes, whatnot, we can hardly discern these.

Hmm I think the best way is to compare the query to the query saved on the actual insight (in the same way the save button logic works). Probably easier after https://github.com/PostHog/posthog/pull/24076. Insights can change after being saved, duplicated and maybe more.

**Pull request closed without merging**
