### PR TITLE
Add docker hub build & push task to github actions

### PR DESCRIPTION
**Pull request by fuziontech**
Dockerhub is slow to build these. Let's have github actions do the building to see if it speeds things up

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
Should be in `docker-image.yml` IMO so that we don't end up with too many files in `.github/workflows/` – but the idea is great!

**Comment by mariusandra** [comment]
This would be great to fix, as builds wait up to 10 hours in the docker hub queue before completing:

image

Hard to tell customers who use an image to wait 10 hours and then try again :D.

**Review by Twixes — APPROVED** [review]
I revert my review – obviously this can't be in `docker-image.yml`, since that runs on pull request pushes, while this must work on master pushes. So this is fine.

**Comment by Twixes** [comment]
How do we request these builds now though? As in, if we merge this, is there another Docker push-inducing mechanism enabled that will overwrite this workflow's builds (in the above 10h or so)?

**Comment by mariusandra** [comment]
There's a list of builds [here in docker hub](https://hub.docker.com/repository/docker/posthog/posthog/builds). Right now we're caught up with the queue, so nothing will be counted double. Otherwise you can enter that page and kill all pending tasks

**Pull request merged**
