### PR TITLE
Virtualize action filter

### LINKED ISSUE #4135: Virtualize actionfilter
## Is your feature request related to a problem?

*Please describe.*
- several antd components are pre packed with virtualization support however our actionfilter uses lists which aren't supported right now
- this will cause slow loading when teams with many events/actions try to add a filter

## Describe the solution you'd like
- virtualize the lists inside this filter

## Describe alternatives you've considered
- leave it as is

## Additional context
- related to #4110 on fixing high load event properties/event names
- i've made progress on virtualizing the list but opening this ticket to formally track it and reference in the PRs
- the actionfilter is tricky mainly because we're stacking 3 lists on one another so it's taking a bit to get the UX smooth

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- closes #4135 
- uses react-virtualized to virtualize our action list
- action list previously used 3 separate lists but it's now all controlled within a single list so that the virtualization can function smoothly
- still undergoing some QA
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by EDsCODE** [comment]
@paolodamico could you test this with your high load of event names?

**Comment by timgl** [comment]
@EDsCODE this is the snippet i use to add a bunch of props to my local instance (run it in /demo)
```
const dic={};[...Array(5000).keys()].map((d) => dic[d] = 1);posthog.capture('test', dic)
```

**Comment by EDsCODE** [comment]
I specifically need to test high load of event_names and I think there was something about event definitions not being updated realtime at the moment

**Comment by EDsCODE** [comment]
Virtualization is working as expected 👍. With 20,000 event names, master right now will lag when you click on action filter. This PR has no lag when you click.

Last thing to add is search functionality and it will be ready

**Comment by paolodamico** [comment]
Sorry for the delay here @EDsCODE, been in calls all morning, glad you were able to test, ping me if you need any further help from me

**Review by paolodamico — APPROVED** [review]
lgtm! pretty solid improvement, tested with 30k events & 30k properties and rendering seems to work perfectly. 

Only issue I could find (maybe not worth spending too much time on this right now) is that search is quite laggy (see recording, I typed the whole word almost instantly). I think the problem here is we're searching on every key stroke. Even if search takes a little while, a better UX would be to debounce searching (or basically not tying updates to the search controlled input to search being completed), and showing a small loading indicator on the right side of the input.

image

**Comment by samwinslow** [comment]
+1 to what @paolodamico said. I was going to ask about debouncing search but then got sidetracked trying to add lots of events to my local instance in order to verify the problem. Fuse might have a debounce feature built-in.

**Review by samwinslow — APPROVED** [review]

**Comment by EDsCODE** [comment]
Above all makes sense. Will merge and follow up with debouncing as necessary

**Pull request merged**
