### PR TITLE
Introduce Dayjs

### LINKED ISSUE #2676: Replace Moment.js with a more modern datetime library
## Problem and solution

[Moment.js has reached its end of life.](https://momentjs.com/docs/) We should thus replace it with a more modern library, that is still actively maintained. I believe [Luxon](https://github.com/moment/luxon) would be a great solution – it's under the Moment organization umbrella as well, but is a much newer project, with lots of activity and solid code. Importantly, it has a model very similar to that of Python's `datetime` module, which should make our frontend and backend play even better together.

### PR DESCRIPTION
**Pull request by timgl**
## Changes

- Closes #2676.
- EDIT: This PR doesn't fully remove Moment just yet. See discussion below. 

[moment.js is one of our bigger libraries](https://bundlephobia.com/scan-results?packages=@papercups-io/chat-widget@1.1.5,@posthog/plugin-scaffold@0.2.12,@posthog/simmerjs@0.7.2-posthog.2,@sentry/browser@6.0.4,antd@4.11.2,chart.js@2.9.3,core-js@3.6.5,d3@5.15.0,d3-sankey@0.12.3,expr-eval@2.0.2,fast-deep-equal@3.1.3,funnel-graph-js@1.4.1,fuse.js@6.4.1,kea@2.3.2,kea-localstorage@1.0.2,kea-router@0.5.1,kea-window-values@0.0.1,moment@2.24.0,posthog-js@1.8.7,posthog-js-lite@0.0.3,posthog-react-rrweb-player@1.0.13,query-selector-shadow-dom@0.8.0,react@16.13.1,react-dom@16.12.0,react-draggable@4.2.0,react-grid-layout@1.1.1,react-markdown@5.0.2,react-monaco-editor@0.40.0,react-redux@7.2.0,react-shadow@18.4.2,react-sortable-hoc@1.11.0,react-syntax-highlighter@13.5.1,react-toastify@5.5.0,redux@4.0.5,reselect@4.0.0,rrweb@0.9.14,sass@1.26.2,zxcvbn@4.4.2&sortMode=size). This PR attempts to remove it, though somehow it still gets loaded through ant.d's datepicker?

image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by Twixes** [comment]
Closes #2676 I suppose.
BTW, in the plugin server we use [Luxon](https://github.com/moment/luxon), which was created by Moment people and has an API pretty similar to Python `datetime`.

**Comment by mariusandra** [comment]
For the record, Moment is [670kb of unminified JS](https://app.bundletracker.io/b/oZjTcXo9CMDGKl83GyIWxI2NjoJS3NYMTfVZ6gee) and most of it is taken up by including [all the translations in the world](https://app.bundletracker.io/b/oZjTcXo9CMDGKl83GyIWxI2NjoJS3NYMTfVZ6gee?root=%3Croot%3E%2Fmain%2F.%2Fnode_modules%2Fmoment&hue=25)

image

**Comment by paolodamico** [comment]
Alright solved merge conflicts, did some adjustments to the imports, and we should be good to merge. Indeed `moment` is not yet fully removed, at the dependency level, both AntD and `chart.js` depend on it. It will probably be a matter of excluding from the bundle, will leave this for a separate PR.

**Review by EDsCODE — APPROVED** [review]
lgtm

**Pull request merged**
