### PR TITLE
refactor(frontend): Remove Ant component 

### PR DESCRIPTION
**Pull request by rogemus**
## Changes

- Replace Switch with LeonSwitch
- Replace Skeleton with LemonSkeleton

Relates to https://github.com/PostHog/posthog/issues/13624

### CODE REVIEW

**Comment by rogemus** [comment]
Question to posthog team - do you prefer to import like that: 
``` import { X } from 'lib/lemon-ui/X ``` or ```import { X } from '@posthog/lemon-ui'```
I've seen both in code. 

Also, your imports are a bit messy. Would be OK if I sort them in the files I'm changing?

**Comment by Twixes** [comment]
Hey @kacper-rogowski-wttech! Is this ready for review?

**Comment by rogemus** [comment]
@Twixes hi, @kacper-rogowski-wttech is my corporate username. 

Sadly after some changes on master, I have conflicts in 20+ files, I will resolve them and mark PR as ready for review :D

**Comment by Twixes** [comment]
Most of the conflicts are probably from #18663 (hopefuly), so should be easy to resolve.

**Comment by rogemus** [comment]
Due to conflicts and a lot of changes on master I've closed this pr and open new one, which is much smaller and easier to review. 

New PR
https://github.com/PostHog/posthog/pull/19216 

FYI @Twixes

**Pull request closed without merging**
