### PR TITLE
refactor(experiments): replace legacy insight container with query

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

Experiments is using the legacy component `<LegacyInsightContainer />`, preventing a further cleanup of insights related code.

## Changes

This PR replaces the `<LegacyInsightContainer />` with a `<Query />` component

## How did you test this code?

Trying various combinations of saved and unsaved experiments / metrics

### CODE REVIEW

**Comment by neilkakkar** [comment]
What sorcery is this, this looks pretty good! xD

Few bugs:

1. The legend button seems to break the view
2. The results page doesn't really make sense: 
image

It's still showing the preview insight, when it should show the result of the experiment, which comes from the experiment results API endpoint, and should be a breakdown between control/test

**Comment by neilkakkar** [comment]
It's this bit: https://github.com/PostHog/posthog/blob/thomas/replace-metric-selector-insight-container/frontend/src/scenes/experiments/Experiment.tsx#L1027 where results determine the final filter

**Comment by thmsobrmlr** [comment]
> It's this bit: https://github.com/PostHog/posthog/blob/thomas/replace-metric-selector-insight-container/frontend/src/scenes/experiments/Experiment.tsx#L1027 where results determine the final filter

Thanks, will look into it.

You're right about the insight legend. Seems to be the case in the current live version as well though.

**Comment by thmsobrmlr** [comment]
@neilkakkar This should be working now.

**Review by neilkakkar — APPROVED** [review]
Seems to be working pretty well, thanks!

**Pull request merged**
