### PR TITLE
Fix Mix - z-index & multiple cohorts in breakdown

### LINKED ISSUE #5247: Multiple cohorts in taxonomic breakdown filter
## Is your feature request related to a problem?

The old filter supported multiple cohorts in a breakdown:

image

The new taxonomic filter does not. I don't think we can release this flag before this support is added. I'm not sure how many people use this feature, but it's definitely in the "more than 0 people have built something that depends on it and we can't remove it ever" zone.

## Describe the solution you'd like

Multiple select/tags in the taxonomic filter. It's not that hard to add TBH.

## Describe alternatives you've considered

"+ add another cohort" button.

## Additional context

[Don't click here](https://www.youtube.com/watch?v=gfkts0u-m6w).

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Two fixes ended up in one PR

- Fix new filter z-index in drawers (solves bug with filter not opening in new cohort drawer). 
- Taxonomic breakdown filter supports multiple cohorts. Closes https://github.com/PostHog/posthog/issues/5247

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by clarkus** [comment]
Are the changes feature flagged? I am not seeing the new picker in the deployment.

**Comment by mariusandra** [comment]
Yup, the same `4267-taxonomic-property-filter`. I added it to the deployment. Then it crashed and hasn't come up yet. Until it recovers, this screencast (and oh boy can I make more of them) is the best way to experience this breakdown.

"Not worse, and does the same stuff so the release isn't blocked" is the high bar I'm hoping to achieve here. :)

**Review by clarkus — APPROVED** [review]
Based on the attached screen captures, the crashed deployment, and my own local instance not working for some reason, I'll go on record to say this isn't any worse, does the same stuff as before, so the release shouldn't be blocked.

**Comment by clarkus** [comment]
One improvement I see that could be made, but that shouldn't block release: the breakdown values stack vertically. Depending on the character length or width of the selected values, we could use a left-to-right sentence-like flow of options. They're enclosed already, so if we move that remove action `x` into the container, it would make that left-to-right layout more feasible. That would reduce the height of the query builder and make it less likely to displace the visualization below.

**Review by paolodamico — COMMENTED** [review]
Posthumous lgtm and great stuff with the new UX

**Pull request merged**
