### PR TITLE
fix: Removing some self-hosted upgrade paths and references

### PR DESCRIPTION
**Pull request by joethreepwood**
## Problem

Speaking with @simfish85, it was suggested there are still some upgrade paths in the hobby deployment that lead users to believe they can upgrade a self-hosted version or purchase a license. I decided to remove them and, since the FOSS repo is a read-only mirror of this repo, this is where I have to start. 

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
Updates test assertions accordingly, looks good

**Comment by raquelmsmith** [comment]
It's actually be on my to-do list to load up the hobby deployment and click around and see what happens when I run into paywalls, and then fix that for reals. Instead of just saying "We don't offer this any longer" we should have a good CTA to the cloud product. This here is a good start so let's merge, just putting a note here that there is more work to do :)

**Comment by joethreepwood** [comment]
Sounds good. Happy to help with that if I can! This is definitely just a quick stopgap from someone who's not as technical 🤣

**Comment by joethreepwood** [comment]
Rerunning the tests. Not sure why they're failing.

**Comment by Twixes** [comment]
Re-running wouldn't help, the error messages were about leftover assertions with old messages :)

**Pull request merged**
