### PR TITLE
Fix Master EE code

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Fixes some broken things on master
- Tries to fix EE tests

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by mariusandra** [comment]
This unfortunately doesn't fix the EE tests since all clickhouse inserts now happen asynchronously:

image

Any thoughts on how to overcome this?
These EE tests should be enabled in github as well, like they are now in the clickhouse-actions branch.

**Comment by mariusandra** [comment]
@EDsCODE thanks for getting the CI tests to work!

I just fixed a bunch of mypy errors, though several still remain. Fixing the `person` test and code seems to be a much bigger undertaking than I thought before. 

Unfortunately I'm running out of time today...

@fuziontech or @EDsCODE can you pick this up? I think having a stable `master` branch should be one of the highest priorities.

**Comment by EDsCODE** [comment]
@mariusandra I added process_event in line with the process_event_ee call and changed create_person to use Person.objects.create. This should pretty closely mirror the pipeline as more an integration test than a unit test. There's a few more bugs I was trying to trace (I actually realized the persondistinctid still needs a bit more refactoring to use the replacingmergre tree properly because right now it’s generating ids rather than using the ids from postgres model) which I can finish in the morning. 

The other major error in the tests is that persondistinctids are out of sync/created multiple times compared to postgres model.

**Comment by EDsCODE** [comment]
Tests run now! I believe multitenancy failures should be unrelated as it has to do with the work @Twixes is doing

**Pull request merged**
