### PR TITLE
fix: Debounce the resize observer to help with window resizing

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

We currently fire a lot of re-rendering on resizing which can make things feel really sluggish. Most of the time we don't need this to be "real time" so we can have a slight delay

## Changes

* Implements a debounce in the observer by default

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by daibhin — APPROVED** [review]

**Comment by Twixes** [comment]
This feel better than I thought it would!

**Comment by benjackwhite** [comment]
> This feel better than I thought it would!

Yeah, the slight delay in some things correctly rendering is made up for immediately by things actually reacting to the viewport changes 😅

**Comment by Twixes** [comment]
Looks like funnel bars don't want to stop resizing in Storybook after this @benjackwhite 🤔

**Comment by benjackwhite** [comment]
Yeah its why this is going stale because I can't figure it out...

**Pull request closed without merging**
