### PR TITLE
fix: events are not showing up in any dropdown or searches

### LINKED ISSUE #26531: bug: events are not showing up in any dropdown or searches
### Bug Description

We have a self-hosted posthog instance (PostHog Git SHA - 5adf41e8b8).
In activity pages, we can see the incoming events and event types as well.

But while creating insights in dashboard, the dropdown to select event is blank.
It's happenning on the activity page's `Select an event` dropdown as well. 

## How to reproduce

1. Go to dashboard
2. Try to create an insight
3. In the event selection dropdown it's showing up no events

   Screenshot 2024-11-29 at 10 49 35 AM

## Additional context
1. In our posthog instance, there are already various events, checked in data warehouse and in activity page (/project/1/activity/explore)

   Screenshot 2024-11-29 at 10 51 30 AM

3. We have checked the API call as well, it returning blank results
    **Request** - 
    ```
    https://<posthog_instance>/api/projects/1/event_definitions?event_type=event&search=&limit=100&offset=0
    ```

   **Response** -
    ```json
   {
     "count": 0,
     "next": null,
     "previous": null,
     "results": []
   }
   ```

### Debug info

- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: 5adf41e8b8
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

### PR DESCRIPTION
**Pull request by tanmoysrt**
## Problem

Fixes https://github.com/PostHog/posthog/issues/26531
Events list is blank everywhere in self-hosted posthog instance.
Please check the issue, for more details

## Changes

- Added `property-defs-rs` service in `docker-compose.hobby.yml`

## Does this work well for both Cloud and self-hosted?

This is working well for docker-compose based self-hosted hobby instance.

## How did you test this code?

I have re-deployed my services to validate whether the issue gets fixed. Also, other users also have tried the same solution and worked for them as well.
Ref - Comments of https://github.com/PostHog/posthog/issues/26531

### CODE REVIEW

**Review by MichaelKutsch-ph — APPROVED** [review]
Thx for catching this and the contribution! 🚀

**Comment by MichaelKutsch-ph** [comment]
not sure about the breaking CI step here. @oliverb123, mind having a look?

**Comment by gumaerc** [comment]
Hey @oliverb123, we are experiencing the issue referenced in this PR on the paid version of Posthog. I had my boss try and submit a ticket through the website, but it threw back and error and didn't let him submit it. Can we re-open this issue and get it addressed? It seems to also be affecting the Posthog-hosted services. I just deployed some changes to our app to add some custom events. In my hobby project, these events show up in the Funnel step dropdowns right away. In our paid organization projects, they show up under "Activity" but not in the dropdowns when adding a step top a Funnel. The original issue is here: https://github.com/PostHog/posthog/issues/26531. It seems to pertain to the self hosted version of Posthog, but it seems the scope of this is beyond that because we are experiencing it on a paid account.

**Comment by gumaerc** [comment]
Update... I can see some of the custom events now in the Funnel step dropdown. It took several hours for them to show up though, so maybe there's still something to look into there.

**Pull request closed without merging**
