### PR TITLE
Better size feature flags table

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Improved width percentages AND removed the big blue `<PropertyFiltersDisplay/>` things. IMO they don't provide much value (most production feature flags have too many conditions for this to be readable), and they very easily take up a ton of real estate. To replace this I made the textual description a bit smarter.

### Before
localhost_8000_feature_flags (2)

### After
localhost_8000_feature_flags

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
I like the idea of the rollout conditions column, but I wonder how it'll scale. There is a feature flags design in progress right now where some of these things are changing to support group analytics. I wonder if this should be folded into that work. Thoughts, @macobo?

**Comment by macobo** [comment]
> I wonder if this should be folded into that work.

Don't think so - list page doesn't touch groups work right now

**Comment by Twixes** [comment]
What do you mean by scaling Chris?

**Comment by clarkus** [comment]
> What do you mean by scaling Chris?

I mean that rollout is summarized based on the number of groups. So to summarize rollout we'll need to list each group, it's rollout %, and possibly the filters set for each. It gets into a scenario similar to the one previously.

**Comment by Twixes** [comment]
I see, yeah. So, for now this removes listing so that we can avoid thinking about scaling issues. 😅

**Review by mariusandra — CHANGES_REQUESTED** [review]
I'd still like the rollout column to have some data, as it tells me if the feature IS actually rolled out without having to check everything. 

The "rolled out" column might say "1. Beta users", "2. email = marius@posthog.com"... or it might say "1. Cloud users", "2. marius@posthog.com". That makes a difference in what's the case. Hiding both behind "2 things here, lol 🙈, also look at all the whitespace :eyes:" is not good.

I'd just replace the blue bullets with a numbered list, possibly limiting that at 5 with a "show all" link somewhere.

**Comment by Twixes** [comment]
I see @mariusandra So I reworked this to keep the blue pills, but instead making them use the available space significantly better:

### `master`
Zrzut ekranu 2021-11-25 o 18 11 23

### `feature-flags-sizing`
Zrzut ekranu 2021-11-25 o 18 11 35

**Comment by Twixes** [comment]
Also affects the pills in insights:

| Before | After |
| --- | --- |
Zrzut ekranu 2021-11-25 o 18 42 51 | Zrzut ekranu 2021-11-25 o 18 42 34 |

CC @clarkus

**Comment by mariusandra** [comment]
Might it make sense to use gray pills instead? These look too much like primary action buttons.

**Review by mariusandra — APPROVED** [review]
I'd try with gray pills, but already an improvement #reduceWIP

**Comment by clarkus** [comment]
> Also affects the pills in insights:
> 
> Before	After
> Zrzut ekranu 2021-11-25 o 18 42 51	Zrzut ekranu 2021-11-25 o 18 42 34
> CC @clarkus

There should be an updated version of this component somewhere already. @pauldambra was working on this for breakdowns - the improvement would be the lower priority color (gray) as well as encapsulating the close icon within the bounds of the pill. I was using lower priority links to add items to the list, but it seems there are some recent updates using buttons. I don't have a strong preference there, but would like to know if there was a reason for diverging. 

Example pills from the recent settings rework:
Screen Shot 2021-11-29 at 7 58 41 AM
https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4325%3A30344

**Comment by pauldambra** [comment]
Yep @clarkus I think we're overdue a tags component. I got bogged down with how to do pop ups and keep the component ignorant. I'll make time to revisit

**Pull request merged**
