### PR TITLE
feat(persons): Prefer email-like distinct IDs for display names

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

When a person has no name properties (e.g. `email` or `name`), we display the first distinct IDs in the list as a display name. This is a bit too dumb if email is used as distinct IDs too, and the email just isn't the first in the list. In that case we show a random ID when a readable one could be used instead. [This was reported by a user.](https://posthog.slack.com/archives/C04J1TJ11UZ/p1685239289967799)

## Changes

We'll now be a bit smarter than that, and before we take the first random ID, we'll look for one that looks like an email – defined very simply by containing an `@` and a `.`.

## How did you test this code?

Added a unit test case.

### CODE REVIEW

**Review by benjackwhite — COMMENTED** [review]
This is a great step forward. I wonder, if we couldn't also prefer any ID that doesn't look like one of our autogenerated ones? We could still give email a higher priority but I have had cases before of this where people asked "why don't you show my DB ID (i.e. `user-1234` instead of the anonymous ID?"

This wouldn't make a difference in the case where their ID matches the format of ours, but it would make the solution more general at least.

**Review by benjackwhite — APPROVED** [review]
Wonder how this would perform a person with 100s of distinctIds but other than that looks very good to me 👍

**Comment by Twixes** [comment]
It's all lightweight matching so should be very quick.

**Comment by neilkakkar** [comment]
This is noice! One thing worth noting is that not all API responses for persons return all distinct ids (sometimes limited to 10, sometimes 1000, sometimes all), so it's _still_ possible that the person's representing id is not the email, even when such a distinct id exists. In this case I guess what would happen is you're in a cohort, click on random person uuid, which then opens the person page with the correct email header vs the uuid they clicked on.

No action to take, just fyi.

**Pull request merged**
