### PR TITLE
Fix crashing status instance page

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Status instance page was whitescreening due to React weirdness. This should fix it.

### CODE REVIEW

**Review by paolodamico — APPROVED** [review]
great catch @alexkim205!

**Comment by rcmarron** [comment]
@alexkim205 or @paolodamico 

Do you have more context on this change. I think it makes it so the internal metrics dashboard is never shown. Is that intended? Doing some dashboard refactoring here (for the project homepage) right now, and just trying to understand if we still need the internal metrics dashboard.

**Comment by alexkim205** [comment]
Hm, I don't have any context about whether we should be showing or hiding things on the status instance page. The fix was just a direct translation of the code that was already there, but I think @paolodamico might be the best person here.

**Comment by paolodamico** [comment]
It should still be shown and indeed there's a typo here, fixing.

**Pull request merged**
