### PR TITLE
chore(gunicorn): increase thread count for workers

### PR DESCRIPTION
**Pull request by hazzadous**
We currently run with 2 worker processes each with 4 threads. It seems
occasionally we see spikes in the number of pending requests within a
worker in the 20-25 region. I suspect this is due to 4 slow requests
blocking the thread pool.

I'd suggest that the majority of work is going to be IO bound, thus it's
hopefully going to not peg the CPU. If it does then it should end up
triggering the HPA and hopefully resolve itself :fingerscrossed:

There is however gzip running on events, which could be intensive
(suggest we offload this to a downstream at some point). If lots of
large requests come in this could be an issue. Some profiling here
wouldn't go amiss.

Note these are the same settings between web and event ingestion
workload. At some point we may want to split.

I've added a Dashboard for gunicorn worker stats
[here](https://github.com/PostHog/charts-clickhouse/pull/559) which we
can monitor to see the effects.

Aside: if would be wise to be able to specify these settings from the
chart itself such that we do not have to consider chart/posthog version
combos, and allow tweaking according to the deployment.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by ellie — APPROVED** [review]
Worth a try!

I wonder if something like Django Channels + async would be possible without too much work 🤔

**Review by guidoiaquinti — APPROVED** [review]
LGTM, I would probably try to bump 4 to 8 first and then see the increase

**Comment by hazzadous** [comment]
> I wonder if something like Django Channels + async would be possible without too much work

Yeah that would be interesting. My first instinct though is to try to remove as much processing as possible from the events endpoints. The things it's doing I think are:

 1. gzip decompression of the event data (off loading this to e.g. nginx would be great! Alternatively, moving routing/auth information to HTTP headers could remove the need to parse with gzip and instead do this within background processing)
 2. a pg request for auth (doing some caching here would hopefully reduce request times, as well as greatly increase resilience to pg performance/availability.)
 3. pushing to Kafka. The actual push is performed in a background thread iirc. So I think shouldn't have too much affect on request times.

At that point I think we'd have a reasonably lean ingestion endpoint.

**Comment by mariusandra** [comment]
Is this something where switching the gunicorn worker class from `gthread` to `gevent` yields massive wins?

**Comment by hazzadous** [comment]
> Is this something where switching the gunicorn worker class from gthread to gevent yields massive wins?

Possibly if we patched the pg connection to be gevent compatible.

However, the [Kafka producer](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html#kafka.KafkaProducer) we use handles batching IO in a separate thread, so there would not be much to gain there (probably playing with the producer settings would yield some gains though although I'm not sure).

Introducing gevent I don't think is worth the added complexity. I think the quickest win is to cache the pg requests which gives use a bit of resilience as well, aside from performance. gzip is the unknown for me. If we switched to gevent, but can't switch out of gzip and other CPU bound operations then we could end up killing concurrency rather than helping.

**Pull request merged**
