### PR TITLE
chore: make multivariates & persistence non-beta

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

image

No more BETAAAA! All libraries that need to, now support multivariates & persistence

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

YOLO, a picture is worth a thousand tests....?

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
🪀

**Comment by neilkakkar** [comment]
What sorcery is this?

In gmail, that yoyo is red

image


while it's green here 😮

**Comment by pauldambra** [comment]
https://www.researchgate.net/publication/338455022_Emoji_Face_Renderings_Exploring_the_Role_Emoji_Platform_Differences_have_on_Emotional_Interpretation

Emoji are a dangerous game

**Comment by pauldambra** [comment]
cherry-picked into 1.39.0

**Pull request merged**
