### PR TITLE
Async migrations rollback failures to update current index

### PR DESCRIPTION
**Pull request by tiina303**
## Changes

When rollback fails we might want to try again (E.g. if it was connection error to CH/Postgres), for those cases we need to know where we left off. This also makes any operations we do in the UI safer as they all operate from the index.
Note that I didn't update completion percentage not sure exactly how that should work yet (automatic behind the scenes?).

## How did you test this code?

Added unittest

### CODE REVIEW

**Review by yakkomajuri — COMMENTED** [review]
Unsure what this PR is supposed to accomplish? If we end up in `Errored` or `RolledBack` states we never update `current_operation_index` anyway so that's already set to the op we were processing when things went wrong.

**Comment by tiina303** [comment]
The summary wasn't clear?

Assume we have 3 operations & we completed the migration, we trigger a rollback and the 2nd (index=1) fails with some error.

My understanding of what currently happens: we end up with current_index = 3 (same as completed) & state = error
After this change: current_index = 1 (where we are in reality, if one would want to roll back or forward we should do it from this point) & state = error

My understanding is that when we're running normally we don't have this problem as we update the index after every succeeding op, however we don't do that in the rollback code.

**Comment by yakkomajuri** [comment]
@tiina303 Hmm I'd rather that index tell me where I errored out. Could be worth adding another column? 

This model will hold like 3 digit rows max so we can really add a ton of columns if we like

**Comment by tiina303** [comment]
> Hmm I'd rather that index tell me where I errored out. Could be worth adding another column?
This model will hold like 3 digit rows max so we can really add a ton of columns if we like

That's orthogonal to this PR and we could note that this information is available in the error log from some of my previous changes already, e.g. 
```
Exception was thrown while running operation 3 : Failed to execute ClickHouse op: sql= INSERT INTO default.temp_events_0002_events_sample_by SELECT * FROM events WHERE toYYYYMM(timestamp) >= 202201 AND , query_id=017e9391-01a6-0000-89d2-d75f5cbb429d, exception=Code: 62. DB::Exception: Syntax error: failed at position 216 (end of query) (line
```
and rollback one
```
At operation 4 rollback failed with error:Failed to execute ClickHouse op: sql= RENAME TABLE default.events to default.events_failed, default.events_backup_0002_events_sample_by to default.events ON CLUSTER posthog , query_id=017e9863-f4cb-0001-8c40-06e9e79fc51a, exception=Code: 57. DB::Except
```

On that note those could be more readable it's hard to find the place where sql ends and exception begins (UI formatting problem as I did see line breaks in the console output). Related thoughts on increasing the error varchar column to say 800 (or event more, I initially just used 400 based on last_error one)?

**Comment by yakkomajuri** [comment]
I think we might just need to address the "orthogonal" stuff here then.

I see your point with rolling back a completed migration. But what about a migration that errors halfway and then we rollback? I'd like to know where it errored. So let's maybe add another index here

**Comment by tiina303** [comment]
> I see your point with rolling back a completed migration. But what about a migration that errors halfway and then we rollback? I'd like to know where it errored. So let's maybe add another index here

What about a migration that we tried to run multiple times and errored at different locations. What would that other index be then?

**Comment by yakkomajuri** [comment]
I think indexes should always just be the last one - we can reset it too on occasions.

One thing we can do is append the error message with "errored at index _n_", so the errors will contain a log of things and we don't need to rely on indexes for debugging. Worth noting that current operation index is helpful for debugging but it was built so the runner can actually keep track things.

**Comment by tiina303** [comment]
> One thing we can do is append the error message with "errored at index n", so the errors will contain a log of things and we don't need to rely on indexes for debugging.

they already do, see my earlier message.

**Review by yakkomajuri — APPROVED** [review]
lgtm as per our talk

**Pull request merged**
