### PR TITLE
Show session events in seekbar

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Screen Shot 2021-10-30 at 3 07 33 PM

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by rcmarron** [comment]
This is ready for review. I think it could use some logic tests, but it's getting late, and I want to get us trying it out on our production data ASAP (and it's behind a feature flag).

Also, to get it working, we needed to fix a bug with the `next` url on the `/events` endpoint, so that fix is bundled in here too.



image

cc @mariusandra

**Comment by mariusandra** [comment]
Looks really cool! 

It might get a bit too dense with huge sessions though, so some grouping (at least not more than 1 per pixel :D) will be needed.

**Comment by rcmarron** [comment]
> Looks really cool!
> 
> It might get a bit too dense with huge sessions though, so some grouping (at least not more than 1 per pixel :D) will be needed.

Definitely agree! I really like the idea of grouping. I also think we should think about how grouping (or something else) will interact with events in the side bar. 

cc @clarkus let's chat about this on our call on Monday too.

**Comment by clarkus** [comment]
Definitely up for chatting about this, but the scrubber bar annotations were never intended to show every event. I just don't think it's going to scale very well. The event list is the core solution for itemizing and describing all events in detail. The scrub bar annotations are mostly intended for communicating important events - we've never fully established how we would indicate which events are important so there really isn't any mechanism for reducing the set right now.

**Review by rcmarron — APPROVED** [review]
LGTM

**Pull request merged**
