### PR TITLE
feat: no button muted alt

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

see #11214 

button muted-alt status does not pass contrast checking for accessibility

## Changes

* removes muted-alt status and uses primary-alt in the two places it was used
* this lets us enforce critical accessibility issues testing on the home page (and report on serious issues which are mostly uses of `text-muted-alt`)

| before | after|
|-|-|
| input-with-muted-alt-side-icon | input-with-primary-alt-side-icon|
| before-muted-alt |  after-muted-alt |

and removes the option for buttons all together

remove-button-muted-alt

## How did you test this code?

running the site and looking at it

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
Works for me!

**Review by clarkus — COMMENTED** [review]
I think the primary-alt would be a better choice than the primary blue for those instances. It just gives those components much higher priority and doesn't feel aligned hierarchy-wise with other components. I could see primary blue applying to active states to indicate focus, but generally icon decor / affordance could be communicated with lower priority (primary-alt or secondary-text).

**Comment by pauldambra** [comment]
> I think the primary-alt would be a better choice than the primary blue for those instances. It just gives those components much higher priority and doesn't feel aligned hierarchy-wise with other components. I could see primary blue applying to active states to indicate focus, but generally icon decor / affordance could be communicated with lower priority (primary-alt or secondary-text).

Yep, so this PR removes `muted-alt` as an option for buttons entirely and applies `primary-alt` in the two places that it was used. 

Or am I missing something? :)

**Comment by clarkus** [comment]
@pauldambra I was referring to the primary blue icons in the "after" samples. I checked storybook and it looks like those aren't blue anymore, so I think we're aligned now.

**Review by benjackwhite — APPROVED** [review]
I like it!

**Pull request merged**
