### PR TITLE
fix: snapshot size fangling headroom reduction

### PR DESCRIPTION
**Pull request by pauldambra**
in capture we try to split up recording data so that it fits into the kafka message size limit

we allow ourselves 0.95 of the SESSION_RECORDING_KAFKA_MAX_REQUEST_SIZE_BYTES setting

that is currently 10,485,760

so we allow 10,485,760*0.95 = 9,961,472

the first two rejected messages we sampled were 9.8 and 9.4MB as reported in S3 console, 10.3 and 9.9MB as reported on disk locally

one also could definitely have been split further

let's reduce the headroom to 0.9 or 9,437,184 and see if the splitting kicks in more effectively

### CODE REVIEW

**Review by daibhin — APPROVED** [review]

**Comment by daibhin** [comment]
Any idea what might be causing the difference locally versus on S3?

**Comment by pauldambra** [comment]
> Any idea what might be causing the difference locally versus on S3?

i bet s3 estimate the size to save the cost of reading the files 🙈

**Comment by daibhin** [comment]
@pauldambra haha the irony

**Comment by pauldambra** [comment]
test cleanup is failing.. not the tests 🤷 

========= 1234 passed, 3 skipped, 5052 deselected in 427.34s (0:07:07) =========
/home/runner/work/_temp/8db92b98-16a7-49e8-b626-85aabe9f8f13.sh: line 6:  7974 Segmentation fault      (core dumped) pytest posthog ee/ -m "not async_migrations" --ignore=posthog/temporal --ignore=hogvm/python/test --splits 10 --group 1 --durations=100 --durations-min=1.0 --store-durations $PYTEST_ARGS
Error: Process completed with exit code 139.

**Comment by marandaneto** [comment]
> Any idea what might be causing the difference locally versus on S3?

Maybe https://github.com/PostHog/posthog/issues/18473

**Comment by pauldambra** [comment]
@marandaneto no, this is the S3 reported size and the mac finder reported size :) our snapshot bytes estimate is just to give us a rough guide since we only care about if something is likely to need splitting up and that could be a boolean `is greater than config max` tbh 🙈

**Pull request merged**
