### PR TITLE
Add display to filter todict

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
Cumulative graph wasn't working. Fixed by adding it to the dict method for filters because it's used to determine cache key

*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
Annoyingly this is going to break caching of existing dashboard items. I know, I know. There's 2 solutions to this
1. "touch" all filters [like this](https://github.com/PostHog/posthog/blob/master/posthog/migrations/0071_cache_dashboard_items.py#L24) in a migration. We'll run into the same issue soon
2. Have a hash function that only takes into account properties that are actually set. That way we can easily add new properties without screwing up existing dashboard items

I'm happy to pick 2 up which was on my list anyway. I just recommend holding off merging this until then

**Comment by EDsCODE** [comment]
Do you mean break existing cache as in it will cause a reset/reload or something will actually fail?

**Comment by timgl** [comment]
It's [this line](https://github.com/PostHog/posthog/blob/master/posthog/tasks/update_cache.py#L65) I'm worried about. I originally thought this might break something important, but looking back I think the only things this will break are
1. the 'last refreshed' information on dashboard items
2. all currently cached dashboard items will need to be refreshed. If we merge this that could mean a ~15 min period shared dashboards don't work

**Comment by EDsCODE** [comment]
ohh got it—solution 2 above makes sense

**Comment by EDsCODE** [comment]
closed in favor of #1328

**Pull request closed without merging**
