### PR TITLE
PostHog Toolbar

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Still a work in progress!

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
Hi, this Epic PR is now ready to be reviewed and in *could* be merged to master.
It's non-destructive and the default behaviour is to show and use the old toolbar (aka "editor") in exactly the same way as before.

To enable the new toolbar, open [settings.py](https://github.com/PostHog/posthog/pull/896/files#diff-b962ddb5c8f7db056247c0585963093cR306) and switch this:

```python
# Change this to "toolbar" to work on the new toolbar, keep at "editor" and nothing will have changed
# from 1.7.0 (except it now supports HMR!)
TOOLBAR_VERSION = 'editor'
# TOOLBAR_VERSION = 'toolbar'
```

There's plenty still to do, yet we could start chunking it into smaller PRs from now on.
I'll reply in the epic ticket with more details about this PR and the next steps.

**Comment by mariusandra** [comment]
There's something wrong with a test:

image

I had a quick look but it wasn't immediately obvious what was broken.

**Comment by EDsCODE** [comment]
I noticed this yesterday too. What’s happening is that some change causes the event props not to be loaded “fast enough” or at all on the e2e instance when it’s created. For a quick patch i changed prop-filter-event to prop-filter-person but that change hasnt been merged yet so you could try that fix here!

**Comment by mariusandra** [comment]
Yeah, that's a bandage that I'll use if needed, thanks. Though I'd rather see this solved with a clean fix. I interacted with the page in cypress after the test failed and couldn't get the event names to appear. So it seems like a legit bug that should be reported or fixed. We even have a test case that fails :D.

**Comment by mariusandra** [comment]
Hi @timgl , this PR is ready for review. With the last changes I refactored and cleaned up some loose ends. After this is merged, everyone who has not set a  flag in `settings.py` will still get the old editor with the old code, as it was.

I still need to check why the test is failing though.

**Comment by mariusandra** [comment]
Another open issue: this PR is using the `posthog-js` from `@mariusandra/posthog-js`.

I should clean that up and release `1.1.0` officially. However the latest package is `1.0.7-beta.0`, which I can't find in github (I see `1.0.6` there). @timgl do you remember what went into the `posthog-js` beta that was published 2 months ago? Those changes will be lost if I push out 1.1.0.

**Comment by timgl** [comment]
Great, I'll review. For posthog-js, all the changes should be on master, even if they're not correctly tagged in package.json.  So you should be able to just push a new version without anything being lost?

**Review by timgl — APPROVED** [review]
Sorry I think I just caused a merge conflict. Other than that I think this is fine to merge given it doesn't change anything right now

**Comment by mariusandra** [comment]
Thanks! Conflict fixed. I'll fix the test and hook it to a new posthog-js version once you review [the PR](https://github.com/PostHog/posthog-js/pull/40) there.

**Comment by mariusandra** [comment]
Seems like the rebase already fixed the test. New PostHog version added, small bug fixed and merged.

**Pull request merged**
