### PR TITLE
Revert "Remove action.calculate_events()"

### PR DESCRIPTION
**Pull request by macobo**
Reverts PostHog/posthog#8624

This seems to have broken E2E tests somehow - maybe to do with a missing `.save()` call now?

Reverting quickly to unblock others.

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]

**Comment by macobo** [comment]
Hmm, didn't fix all the fails. Investigating...

**Comment by neilkakkar** [comment]
(new trend fail looks like a flake?)

**Comment by macobo** [comment]
Not a flake but a real problem - seems like hovering/clicking the dropdown causes the page to scroll which in turn causes things to fail in weird ways.

**Comment by macobo** [comment]
https://github.com/PostHog/posthog/pull/8632 does it better.

**Pull request closed without merging**
