### PR TITLE
Fix/booleans from env

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes
- follow up #672 merge conflicts
-

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
CI test failures, looks good otherwise

**Comment by timgl** [comment]
Merge conflicts. We've also had a report (#1055) of someone doing `DEBUG: 0`, probably because in examples I used `DEBUG: 1`. Worth seeing what happens if you pass either of those values.

**Comment by EDsCODE** [comment]
Fixed conflicts. Debug=0 is read properly as an int (bool) now!

**Comment by mariusandra** [comment]
I think something broke with this. I can no longer deploy to production/app:

image

**Pull request merged**
