### PR TITLE
Storybooks via Chromatic

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Chromatic is hosted storybooks plus visual testing. 
- Evaluating to see if it makes sense.
- Here's [our latest storybook](https://61260360a8e859003a7c138b-lkcxcprmcx.chromatic.com/?path=/story/posthog-scenes-events--all-events) hosted by them.
- This PR should enable chromatic builds and storybook "preview apps" for all branches and PRs.
- Suggested by @alexkim205 [here](https://github.com/PostHog/posthog/pull/5714#pullrequestreview-737456089)
- I've used Chromatic in the past, but it got quite expensive for us, as it was taking hundreds of screenshots per commit, quickly exceeding our $$$ budget. Chromatic does have a "free for open source" program, which I applied to. We can also turn off the tests and just benefit from the preview apps.
- Log in to chromatic with your github account and you should see the builds.
- Click "Details" below to see the storybook

image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
This works

**Comment by mariusandra** [comment]
Going to have to HODL for a bit, as some stories will be [breaking builds](https://www.chromatic.com/test?appId=61260360a8e859003a7c138b&id=6126cc3c7d2067003ab0b697) for some time to come:

image

For example the day here changes daily:



Might be worth just turning off the visual reviews honestly, as I fear they will bring a lot of noise at this stage.

**Comment by alexkim205** [comment]
> For example the day here changes daily:

Code changes lgtm, but I also wonder if visual reviews are worth the hassle atm especially with these non-deterministic edge cases. I wonder if we should also involve other stakeholders like PM's into this review process. Maybe @paolodamico or @marcushyett-ph will be able to gain more insight/direction from these visual reviews?

**Review by alexkim205 — APPROVED** [review]
Approving code changes

**Comment by mariusandra** [comment]
OK, I've disabled the visual tests. Let's merge and see if just having hosted storybook builds is something that helps us.

**Comment by marcushyett-ph** [comment]
I think the visual reviews are primarily valuable for testing for regressions. As with any test - if it's noisy or flaky it will quickly be ignored.

**Comment by mariusandra** [comment]
We should enable them eventually, because catching visual regressions feels like a low hanging fruit we can pick to improve quality. However right now is not the right time.

It's hard to drive organisational change, and pushing three strong changes at once (currently storybook, visual reviews, logic tests), will lead to zero adopted changes. Already two items (storybook and logic tests) is too much change at once, but here we are.

**Pull request merged**
