### PR TITLE
fix(dashboards): Ensure editing controls are always visible on TextCards

### LINKED ISSUE #26285: Code blocks in Text Dashboard blocks break editing the block
## Bug description

*Please describe.*
If text appears as a code block in the text element on a dashboard the lemon code block copy is on top of the 3 dot menu so that element can no longer be edited or deleted.
Example dashboard: https://us.posthog.com/project/35787/dashboard/265770

image

## How to reproduce

1. Add text block with code block formatting
2. Try and edit text block after creation
3. See copy button blocks menu

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by barronbud**
## Problem

Fix #26285 to ensure TextCards can be edited via menu.

## Changes
* Align items in the card container to flex-end
* Remove absolute positioning on action button div; switch to using margin for position

BEFORE
before-dashboard-textcard

AFTER
after-dashboard-textcard

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?
* Manual testing by adding new text card in dashboard
* Update snapshots to ensure storybook is aligned

### CODE REVIEW

**Comment by barronbud** [comment]
Waiting for some 👀 from the relevant team.

**Review by anirudhpillai — APPROVED** [review]
Thanks for fixing this!

**Review by thmsobrmlr — CHANGES_REQUESTED** [review]
Hi @barronbud. Thanks for the fix also from my end! 

I'm a bit late to the party but I think there might be a better option here. Context is that a primary use case for the text cards is separating the dashboard into sections with headlines. Those shouldn't be much bigger than the headline. Additionally changing the size of existing cards would alter the layout of existing dashboards for our customers. 

Here's a card before and after the fix:
Screenshot 2024-12-10 at 12 15 35
Screenshot 2024-12-10 at 12 13 11

My thoughts:
- Probably the best fix is to insert the button into the flow of the generated markdown. This seems quite complicated and I don't know if this would even be possible with the markdown library we're using.
- Therefore I think the next best thing we could do is make the text block a bit smaller than the full width, so that the edit icon isn't overlapped. Something like this:
  Screenshot 2024-12-10 at 12 48 40

Let me know what you think. I'm open for other ideas/thoughts. Also happy to put up a fix, but don't want to take away from your contribution - let me know if you want to take a look again with this added context.

**Comment by barronbud** [comment]
@thmsobrmlr Great idea!  And thanks for the additional context.

I undid prior changes and just shrunk the width on the body of the card to be about 83%.  I tried 91%, but it created a UI quirk when the content causes a scrollable overflow - the edit actions were visible, but could overlap the scrollbar.  

If you'd like to jump in, feel free!  Guessing there are some unique steps for the E2E testing that are harder for an external contributor.  I was just exploring the code during the interview process.  😁

**Comment by thmsobrmlr** [comment]
Thanks for the follow up @barronbud ! The issue with the new approach is that it moves the scroll bar inside as well, and that doesn't look so pretty:

Screenshot 2024-12-11 at 12 52 16

Gave it a whirl here: https://github.com/PostHog/posthog/pull/26828.

**Comment by barronbud** [comment]
@thmsobrmlr Looks great!  Gonna close this since the issue is already resolved.

**Pull request closed without merging**
