### PR TITLE
Fix all buttons loading on plugin updates

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Tiny thing that bothered me a bit.

All buttons would load when updating one plugin. Now only the plugin that's updating will load.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by mariusandra** [comment]
What happens if one plugin is updating and you click "update" on a few of the other ones as well?

**Comment by yakkomajuri** [comment]
Suddenly the process is sped up!! It's magical... 😅 

https://user-images.githubusercontent.com/38760734/115282371-af3ab480-a139-11eb-9a1a-a7d1de2317e5.mov


Will look into a better approach

**Comment by yakkomajuri** [comment]
Works individually now - made it a separate component for smoother loading (there was some lagging in the UI before):


https://user-images.githubusercontent.com/38760734/115287376-ba90de80-a13f-11eb-8988-e8c154365d81.mov

**Review by Twixes — APPROVED** [review]
I enjoy

**Pull request merged**
