### PR TITLE
Add null param to funnel breakdown

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- stops breakdown params from being sent when unneeded
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by EDsCODE** [comment]
@samwinslow Can you add the FF that you're working with so this works on your PR

**Review by liyiy — APPROVED** [review]

**Comment by samwinslow** [comment]
Quick noob question here @EDsCODE — will `null` serialize to `None` in Python? Will the effect be the same as if it were as `undefined` or not included in the query params at all?

**Comment by EDsCODE** [comment]
@samwinslow it'll be parsed into 'None'

**Review by samwinslow — APPROVED** [review]
Thx for adding the feature flag. Looks good to me!

**Pull request merged**
