### PR TITLE
A portion of the events store diff with the scaffold for supporting DynamoDB

### PR DESCRIPTION
**Pull request by fuziontech**
Doing this in an effort to cut down diff size and to enable others to use Dynamo with some boilerplate handled already

### CODE REVIEW

**Review by macobo — APPROVED** [review]
:bow:

**Comment by timgl** [comment]
Are we doing this just in case we ever want to use dynamoDB? not a huge fan of having code in the main codebase that isn't actively used

**Comment by macobo** [comment]
The context here was a discussion between me and James that we might store session recording data on DynamoDB instead. Opted not to do that for now, but he did this PR for some setup/scaffolding I could use.

**Comment by timgl** [comment]
Very stale and not priority right now. Let's open again when necessary.

**Pull request closed without merging**
