### PR TITLE
chore(deps): Upgrade TypeScript from 4.8 to 4.9 in the frontend

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This upgrades TypeScript from ~~4.6~~ 4.8 to 4.9 (current latest) in the frontend. The highlights:

- ~~[4.7's instantiation expressions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions), e.g. `const makeWrenchBox = makeBox<Wrench>` – basically bringing non-generic instances of generic functions (I ran into this being impossible a few times in the past, so kudos)~~
- [4.9's `satisfies` operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator), e.g. `const palette = { red: [255, 0, 0], green: "#00ff00", bleu: [0, 0, 255] } satisfies Record<Colors, string | RGB>` – this is awesome, since it allows combining type enforcement with `const` ergonomics

It was the latter that actually prompted me to do this.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
If only tests would pass 👍

**Comment by Twixes** [comment]
Solved, there's just one issue with Kea in `definitionEditLogic.test.ts`:
`Can not access "actionCreators" on logic "scenes.data-management.events.eventDefinitionsTableLogic.scene" because it is not mounted!`
This is despite the logic being mounted a few lines above, so I've no idea what's going on.

**Comment by Twixes** [comment]
Also, noticed we were already on 4.8, because the version was pinned loosely, only on the major component. TypeScript doesn't follow semver though, so that wasn't ideal (they always go up to `x.9` and then roll over to `(x+1).0`, treating every `*.x.*` release as major-ish).

**Comment by mariusandra** [comment]
There was a [bug](https://github.com/keajs/kea/commit/6f05ff642035bcff238799056f83b42f7c9a101d) in Kea 3.1.4 with mounting logics that had a default key, but weren't given any props when mounting.

I released 3.1.5, but for 10min now it's not showing up in the npm repo :/.

image

but 

image

and it won't let me republish. So I guess we'll wait 🤔

**Comment by Twixes** [comment]
Awesome, thanks for the fix @mariusandra!

**Pull request merged**
