### PR TITLE
Compute exposure independently for trend experiments

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

Changing the way we calculate exposure for trend experiments, by querying a dau `$pageview` trend as a measure of exposure, which is a lot more accurate than, say, equal exposures for each variant as they've been running for the same time.

cc: @paolodamico - is this assumption okay to make? That everyone would be getting `$pageview` events?

Further, now calculating significance for trends in the backend, and respecting exposure values. This is still very much an experimental calculation, need to play around and see how it goes. I suspect we wouldn't need the FF_threshold (since exposure is handled by $pageview, but we'll see)

## How did you test this code?

Unit tests!

### CODE REVIEW

**Comment by neilkakkar** [comment]
Currently, paths running experiment has probabilities like:

```
control: 0.00008899999999995023
direct: 0.297796
no-advanced: 0.702115
```

(and we don't know relative exposure)

I'd expect this PR to normalise the above results.

**Comment by paolodamico** [comment]
@neilkakkar can we sync super quickly tomorrow on this? I don't think it's a super safe assumption that everyone has pageview events. I can prepare numbers on this but a) not everyone has a web app / website and b) not everyone uses autocapture.

**Comment by neilkakkar** [comment]
Let's chat!

Very valid points, and I guess we can do better! (Also note that, in case we don't find the event, we fallback to assuming equal exposure. But, I want to find a solution that works for majority of people!)

[Feature Flag Called seems promising](https://app.posthog.com/insights/kHQZu0Em/edit?insight=TRENDS&interval=day&display=ActionsLineGraphCumulative&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24feature_flag_called%22%2C%22name%22%3A%22%24feature_flag_called%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&filter_test_accounts=false&new_entity=%5B%5D&breakdown=%24feature_flag_response&breakdown_type=event&properties=%5B%7B%22key%22%3A%22%24feature_flag%22%2C%22value%22%3A%5B%22paths-advanced-2101%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D)

since if we want to run multivariate experiments, we need to use posthog-js today, and some code needs to check for the FF. This above insight explains why control is doing soo poorly in paths experiment, when it shouldn't be^^

**Comment by paolodamico** [comment]
As chatted on Slack today, Feature Flag called seems like a good approach for now. There are some watch outs related to how users actually use FFs in their code.

**Pull request merged**
