### PR TITLE
fix: update filter rows correctly when deleting filters from a group

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

When deleting one of multiple filters the UI appeared to delete only the last item (when deleting the first)

~~Under the hood we were removing the filter by index _and_ keying the filter row by index

When re-rendering the filter rows because the UI already had a row with key 0 it would not rerender and appear not to change. Even though the data would be changed correctly.~~

When the props to the PropertyValue component changed we only update them if they were an id we could look up. Sometimes they are a string 

## Changes

~~keys the filter row by the stringified value of itself~~

update the input whenever the value changes

## How did you test this code?

running it locally and seeing that the behaviour is now correct

### CODE REVIEW

**Comment by benjackwhite** [comment]
This feels like there is a deeper issue with the FilterRow component itself if it is not rerendering due to the `React.memo` wrapper. I guess keying it more specifically works but might be the least-good hacky approach....

**Comment by pauldambra** [comment]
@benjackwhite the bug is present even if I remove the `React.memo` although good call to check

**Comment by pauldambra** [comment]
@benjackwhite ah, but the component is broken in a tonne of other places it is used with this change :'(

**Comment by pauldambra** [comment]
Took a different tack and this fixes the delete case without breaking the pop up version (I think)

@mariusandra do you remember a reason why we were sometimes ignoring the value passed into `PropertyValue.tsx`

**Review by benjackwhite — APPROVED** [review]

**Pull request merged**
