### PR TITLE
dev(cypress): install cypress deps in codespaces, add to package.json

### PR DESCRIPTION
**Pull request by hazzadous**
As a developer with experience with cypress, my ideal would be to just
be able to `yarn install` and then `yarn cypress run ...` without
having to setup anything else.

As a developer without experience with cypress but with cypress tests
failing in CI, I would like to be able to easily debug locally. I'd
look at the cypress docs and the CI workflow and try out the commands
there. This change handles having the deb packages installed at least.

As a team, I want to make sure that running and updating these tests is
part of everyones development workflow, so want to reduce friction as
much as possible.

As a dev deploying this to production as a docker image, I want the
deploy to be fast, so the image should be small and only contain what is
required to run in production.

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by mariusandra** [comment]
I was thinking earlier we might use [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) or something similar for this?

Our current structure:

```
package.json  # simple project
plugin-server/package.json  # simple project
```

What we should probably have:

```
package.json  # workspace root (has just scripts, no deps)
frontend/package.json  # project in the workspace (new for frontend, move all stuff here)
frontend/cypress/package.json # contains cypress deps only
plugin-server/package.json  # project in the workspace (same as before)
```

Then locally `yarn install` would install the deps of all workspace projects. However when building the container, we'd specify exactly which projects to install.

**Comment by hazzadous** [comment]
> I was thinking earlier we might use [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) or something similar for this?

Yeah I hadn't even got that far but yes separating out project root from frontend etc makes a lot of sense, and would make, e.g. writing the dockerfile, handling github actions paths easier.

I haven't played with workspaces tbh, but I guess the changes you've suggested can happen independently as well.

Maybe I'll hold off on the package changes until we do this, and just keep the apt deps so I can continue with other things

**Comment by mariusandra** [comment]
Up to you to see what are the next steps... Anything that avoids bundling Chrome in the posthog docker container is good.

**Comment by hazzadous** [comment]
> Up to you to see what are the next steps... Anything that avoids bundling Chrome in the posthog docker container is good.

The simplest thing there is just multistage build, which I think we should do anyway. I'll put in something separately for this then we don't have to worry so much about frontend deps getting in there.

**Comment by hazzadous** [comment]
Closing whilst addressing feedback and perhaps separate PRs

**Pull request closed without merging**
