### PR TITLE
New funnel uncalculated state

### LINKED ISSUE #5322: UX issues with funnel uncalculated state
We have a new "uncalculated"/outdated state to show when a funnel state has changed in Postgres. Some UX issues I found with this implementation:

1. Banner doesn't have great positioning and has confusing copy when on the funnel empty state.

2. On a regular state, banner also feels strange. The warning state makes it feel like something is wrong, but this is part of a regular workflow. You can also interact with the elements of the graph (see tooltip). 

Something like what Metabase does could maybe work better? Tagging @clarkus for input too.

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Closes #5322.

### After

https://user-images.githubusercontent.com/13460330/129119669-8172d61f-4ba4-48c9-8678-510efa2b9eb7.mov

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by clarkus — DISMISSED** [review]
I think the copy here could be a bit more generic. It's not that the filters have changed, but the query steps. Generally, we could say "Your query has changed" or if we can be more specific to context, "your query steps have changed".

**Comment by clarkus** [comment]
I am also torn on the interaction here. Blocking out the visualization as soon as the query changes might be really disruptive. What if the user was still using the vis a reference for how they wanted to adjust their filters? Having that view immediately taken away might be frustrating. Can we prompt for this refresh action in a less intrusive way? We could even represent state in the primary "calculate" action there. Thoughts?

**Comment by alexkim205** [comment]
Hm that's a good point, I found myself actually doing that too a few times. I wonder what the best way is to indicate a state change inside of a button. Perhaps changing the color or making it blink? Maybe changing the text to 'Recalculate' and adding the refresh icon before it would be enough. What do you think?

**Comment by paolodamico** [comment]
My feedback was going to be that the visuals feel a bit off. Think it's easy to lose the button to the background, but actually @clarkus may have a point, perhaps something with similar styling (though either less alpha or adding a blur overlay or something) but that only takes the top of the graph?

**Review by paolodamico — COMMENTED** [review]
My feedback was going to be that the visuals feel a bit off. Think it's easy to lose the button to the background, but actually @clarkus may have a point, perhaps something with similar styling (though either less alpha or adding a blur overlay or something) but that only takes the top of the graph?

**Comment by alexkim205** [comment]
I think a hybrid of those suggestions might work best. Indicate a state change and call to action in the calculate button + adding a minimal blur to indicate staleness but not obscure beyond interpretation

**Comment by clarkus** [comment]
I feel like anything we do to obscure the chart is going to be potentially frustrating. The job to be done is to inform that the query doesn't match the visualization. I don't think we need to change the chart to achieve that. What if we adjusted button state to make this more obvious? This also has the benefit of being adjacent to the component where you are going to resolve this problem in the future. Placing it here helps a user know where to go to resolve it. 

Screen Shot 2021-08-11 at 4 34 36 PM

In this case, once the user calculate the query, drop the button state to secondary. If the query changes, change the state back to primary. If N seconds pass without a re-calculate, show a tooltip to draw the user's attention to the place to recover. 

https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1008%3A135212

**Comment by alexkim205** [comment]
That looks awesome, thank you! I like that the tooltip won't be so in-ya-face on every recalculate bc of the N second delay. Gonna think about how to implement this one

**Comment by alexkim205** [comment]
Updated the video in the description w/ the new implementation. Currently the timeout is set to 3s, but lmk if you want me to change this.

**Review by paolodamico — APPROVED** [review]
looks pretty good to me!

**Comment by clarkus** [comment]
Nice job, @alexkim205 🥇

**Pull request merged**
