### PR TITLE
test plugin server person-state test

### PR DESCRIPTION
**Pull request by yakkomajuri**
Seems we have a flaky/broken test but unsure how this happened if all PRs in master passed tests?

### CODE REVIEW

**Comment by neilkakkar** [comment]
See this sir: https://github.com/PostHog/posthog/pull/10455#issuecomment-1164532269

**Comment by neilkakkar** [comment]
If you can get to it today, that will be golden. I've made it non-flaky, but still broken lol

**Comment by yakkomajuri** [comment]
ah thanks for the context - what made this suddenly stop passing though? failing consistently on all my PRs but somehow Karl's PRs that went in earlier today were green?

**Comment by neilkakkar** [comment]
Yes, unsure about why so earlier. They suddenly started consistently failing for me on CI, and on local after I made the 'create new UUID every time' change.

**Pull request closed without merging**
