### PR TITLE
WIP: quick first steps of adding a snapshot_data table

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

see #2142 

We want to be able to ship session recordings to S3. _After_ having stored them in CH. If we do that on the current table schema we can't delete the data from CH.

## Changes

Adds a new snapshot data table *without using it*

Intention would be 
 * to add the table without using it
 * in a follow-up start joining to the empty table when reading snapshot data
 * then start writing snapshot data to this table instead of to the existing metadata table
     * by  adding a new kafka topic the plugin server pushes snapshot data into

## How did you test this code?

* running it to see a table is created
* it's all just copying existing stuff so far, needs kafka setup so can test that table can receive data

### CODE REVIEW

**Comment by pauldambra** [comment]
Ah... we query snapshots using

```
        SELECT session_id, window_id, distinct_id, timestamp, snapshot_data
        FROM session_recording_events
        WHERE
            team_id = %(team_id)s
            AND session_id = %(session_id)s
        ORDER BY timestamp
```

so need the team_id in this table too!

**Comment by pauldambra** [comment]
We query snapshots using 

```
        SELECT session_id, window_id, distinct_id, timestamp, snapshot_data
        FROM session_recording_events
        WHERE
            team_id = %(team_id)s
            AND session_id = %(session_id)s
        ORDER BY timestamp
```

and page in memory...

Would be great to be able to page in CH but...

If we split the snapshots and metadata then that's the only query we need to care about for S3 performance.

So, as is, we'd read all session snapshots from S3 multiple times for each recording. If we can make this "page-able" (definitely a word) then we'd read each bit of snapshot data once

**Comment by mariusandra** [comment]
> Intention would be 
> * to add the table without using it
> * in a follow-up start joining to the empty table when reading snapshot data
> * then start writing snapshot data to this table instead of to the existing metadata table
>     * by  adding a new kafka topic the plugin server pushes snapshot data into

I think we need to write to the table first in order to read from it? 🤔 :3d_think:

Might it make sense to write to both places in parallel when testing things.

**Comment by macobo** [comment]
isn't this just the current session_recording_events table? Note that extra columns in clickhouse are "free" as long as they aren't queried.

**Pull request closed without merging**
