### PR TITLE
Update paths dashboard items

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

- updated the colors
- apply a minimum width on the paths canvas in order to display at least 2 steps fully 

Screen Shot 2021-10-15 at 1 37 57 AM
Screen Shot 2021-10-15 at 1 38 13 AM
Screen Shot 2021-10-15 at 1 38 21 AM

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by liyiy** [comment]
@clarkus Did we want to expand the minimum height of the paths dashboard item? (I assume it would also be # of nodes dependent) It looks like the case from the figma mocks but I wasn't sure because the dimensions of that has a height of over 800px which seemed like a lot.

I can also shrink the height of the canvas (thus shrinking the height of each link) to try to fit more vertical view, but this would probably also have to be # of nodes dependent since we don't want to squish them if there's too many 

example here:
- without minimum canvas height
Screen Shot 2021-10-15 at 1 47 08 AM

- with minimum canvas height
Screen Shot 2021-10-15 at 1 46 47 AM

**Comment by clarkus** [comment]
My concern with limiting the height is that it's going to congest that chart more making it harder to understand. Does constraining the height produce really messy results when there are a lot of starting paths? I will pull this branch and give it a try, too.

**Comment by clarkus** [comment]
I tried this out - it's pretty straightforward to size the dashboard item to a reasonable size for the path visualization. These visualizations can be pretty unique, so it makes sense that you'd have to dial it in a bit. I think the changes look good.

**Comment by liyiy** [comment]
@clarkus What would be an ideal minimum height for the paths dashboard item? I assume this would also be dependent on how many start nodes exist

**Comment by clarkus** [comment]
@liyiy did some experimenting - I think the current default. of around 330px is too short. Let's bump it up to 480px as a default and see how that works for users. I feel like for it to be the best case a user is probably going to have to manually adjust their dashboard layout to best represent the path item. Paths are so variable that it's hard to say where the best default is.

**Pull request merged**
