### PR TITLE
fix: puts a pay gate on the description field

### LINKED ISSUE #13707: Bug when trying to create a dahsboard by filling all inputs (optional and mandatory)
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

When I try to create a dashboard, if I fill the description PostHog doesn't create the dashboard, but if I don't fill it PostHog creates the dashboard.
When I create the dashboard without the description and I try to add it afterwards, postHog tells me that to add it I have to be in premium plan.

https://user-images.githubusercontent.com/33268490/212322865-119ba439-79b2-47ab-88ce-aafe99fb4b23.mov

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. New dashboard
2. Fill in all inputs: Name, Description and template.
3. Create

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

Closes #13707 

## Changes

Adds a pay gate to the modal

### permissioning but not collaboration

Screenshot 2023-01-13 at 13 00 31

### neither permissioning nor collaboration

Screenshot 2023-01-13 at 13 00 10

### collaboration but not permissioning

Screenshot 2023-01-13 at 12 55 40

### both collaboration and permissioning 

Screenshot 2023-01-13 at 12 54 35

## How did you test this code?

running locally

### CODE REVIEW

**Review by macobo — APPROVED** [review]

**Comment by Twixes** [comment]
Two pay gates in one modal seems a bit overkill though, maybe we just shouldn't show the description field during dashboard creation if it's gated?

**Comment by pauldambra** [comment]
> Two pay gates in one modal seems a bit overkill though, maybe we just shouldn't show the description field during dashboard creation if it's gated?

Hmmm 🤔 makes it harder for the user to discover but you can get that feedback from a created dashboard...

**Comment by Twixes** [comment]
Yeah, exactly, I think it's enough if we show that descriptions exist by just having that on the actual dashboard.

**Comment by pauldambra** [comment]
updated to hide the field instead

|without collaboration|with collaboration|
|--|--|
|Screenshot 2023-01-13 at 18 25 00|Screenshot 2023-01-13 at 18 24 43|

**Pull request merged**
