### PR TITLE
feat: duplicate filter

### LINKED ISSUE #11140: Option to duplicate a filter within a AND/OR group
## Is your feature request related to a problem?

When creating a bunch of slight variations in a grouped `OR` filter on an insight, it's a tedious process.

(My use case: I want to get actions that match any of several URL strings.)

## Describe the solution you'd like

**Power user feature request:** I'd love a "duplicate" option next to each filter in the group, next to the trash can icon (not pictured here, but similar to how you can do it on the group level here)

In my case, this would save the following: click add filter, type `url`, click `Current URL`, and change `equals` to `contains`, and just let me replace the text string in the duplicated filter.

image

### PR DESCRIPTION
**Pull request by kevoconnell**
note: this is #11268, I was trying to squash my commits and ended up deleting my changes on that branch, my bad 😅
## Problem
- closes #11140 

- addresses rows that are not in a popup, still need to figure out where popup rows are in the product 😞 

## Changes
Screen Shot 2022-08-11 at 1 12 17 PM
Screen Shot 2022-08-11 at 1 15 20 PM

## How did you test this code?

- create a filter in insights
- click the copy icon, a duplicate filter should be made
- delete the first icon and make another filter, should duplicate
- add more than one filter, than duplicate the second and first filters

### CODE REVIEW

**Comment by hazzadous** [comment]
You got a noop merge in does that count towards you GitHub contribution #hackunlocked

**Comment by kevoconnell** [comment]
> You got a noop merge in does that count towards you GitHub contribution #hackunlocked

it better @hazzadous  🤣

**Comment by alexkim205** [comment]
Awesome changes @MrKevinOConnell! 

Made a few changes (below) but other wise looks good to me:


- [ ] Removed onCopy from PathCleanFilters since we don't expose copy anywhere in the interface. Note, setting only available for licensed users.

Screen Shot 2022-08-12 at 1 10 18 PM

- [ ] Account for more edge cases on duplicate
- [ ] Duplicate in place rather than appending to end

**Review by alexkim205 — APPROVED** [review]

**Review by clarkus — CHANGES_REQUESTED** [review]
Looks like a good change - I do think it'd be easier to associate the duplicate and remove actions with the filter if the icons were top-aligned with the first input in the filter declaration. It's the same alignment as the and/or affordance for the logical operator, just applied to the right position with the inline actions. 

Screen Shot 2022-08-15 at 4 02 24 PM

Does this change only affect the filters that apply to all steps? We also support inline filters for each graph series in the query builder. Would this change introduce inline actions to duplicate filters in that area or is it just for the "global" filters that apply to all graph series / steps?

**Pull request closed without merging**
