### PR TITLE
feat: node widgets

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

PostHog nodes in Notebooks need a means of configuring them

## Changes

**Note:** The generic 'Notebook Settings' was removed from the final version of this PR because there was nothing I wanted to put in there for now. It can easily be added back by reverting [this commit](https://github.com/PostHog/posthog/pull/16910/commits/5b7acb18c69b318aa41556dbb19675272f2d6978).
notebook-settings

Screenshot 2023-08-07 at 11 44 03

In line with the PostHog 3000 world we've gone with widget components in the left hand sidebar.
- Pass attributes & update function through the `notebookNodeLogic` for each node type
- Add settings to recording node that allows the inspector to be hidden
- Styling tweaks to support a sticky sidebar

## How did you test this code?

Manually

### CODE REVIEW

**Comment by daibhin** [comment]
Current WIP preview
widgets

**Review by benjackwhite — CHANGES_REQUESTED** [review]
A few things noticed on the first pass:
1. The empty state feels really weird... The empty space when you enter edit mode feels off. Maybe we need a sensible placeholder like when you have an empty Recording playlist?
2. If you have the view in the "compact mode" then again its way off... I think in that mode, the content should still try and center with the controls to the left and only move to the right if there isn't enough space.
3. Small screen size doesn't work at all... Given that we are trying to focus on strong UX, I would push for a small resolution solution of some kind

**Comment by benjackwhite** [comment]
also would be great if we could have some indicator when you are in the controls as to which Node you are editing. Maybe even something like auto scrolling it into view when you click inside the settings?

**Comment by daibhin** [comment]
@benjackwhite totally agree on the empty state. Starting a new document looks particularly odd:
Screenshot 2023-08-07 at 12 38 34

Two obvious options could be to do what is shown in some of the gifs above
1) Always have a "Notebook Settings" widget that lives above the active node settings widget. It could house some document wide settings, possibly even collapsed / wide mode or sharing settings.
notebook-settings

2) Show / Hide the sidebar as an active node is selected. The jumping made that a little less interesting an option in my opinion
widgets

**Comment by daibhin** [comment]
On the second point @benjackwhite. Just wanted to confirm that you mean that the content should center itself on the page and the controls live right next to it on the left hand side (until it has no space) so there is asymmetric padding to both edges, unlike now where the content is slightly off center because the two combined are centered?
IMG_6555
Basically moving to the second one, where the first is what is currently implemented

**Comment by benjackwhite** [comment]
> On the second point @benjackwhite. Just wanted to confirm that you mean that the content should center itself on the page and the controls live right next to it on the left hand side (until it has no space) so there is asymmetric padding to both edges, unlike now where the content is slightly off center because the two combined are centered? IMG_6555 Basically moving to the second one, where the first is what is currently implemented

100% - thats such a great visual to demonstrate what I was thinking 🙌

**Comment by daibhin** [comment]
@benjackwhite think I've fixed up everything you mentioned above. Also moved the widgets into a Lemon component. Not entirely sure what your intended use is for the new settings UI but happy to work on the API if it doesn't suit your needs (I'd imagine the hard coded width will be limiting)

**Review by benjackwhite — CHANGES_REQUESTED** [review]
Some comments more important than others. After reviewing, I think it's worth another go to make sure the whole UI works in Popover mode as well and clean up some of the hacks _or_ get it in behind a FF and then we look at it together with some real use cases and fix up the issues then.

**Comment by benjackwhite** [comment]
@daibhin  Slightly opinionated but I jumped in and moved things around a fair bit, mostly to get it in a somewhat working state so we can merge and improve as we go. I think I see what you were moving towards with the actions but I think we should keep it simple for now and revisit when we are building out some controls (maybe playlists controls?) to get a better sense of how this would best work and feel.

**Review by benjackwhite — APPROVED** [review]

**Pull request merged**
