### PR TITLE
Add site popover on profile picture to fresh top bar

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

~~Adds this ([per Figma](https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?node-id=484%3A2678)):~~ See comment below for final version.
site

I called the component "SitePopover" as it just encompasses quite a wide array of things (account, orgs, billing/license, instance status), but there may be a better name for it.

### CODE REVIEW

**Comment by Twixes** [comment]
Here's the new popover complete, with some _really_ long names just to make sure the layout stays fine (sans "New organization", which is added too, just isn't normally enabled on self-hosted):
Zrzut ekranu 2021-10-28 o 18 50 41

Try it out in local dev and click around a lot @clarkus

**Review by clarkus — CHANGES_REQUESTED** [review]
This looks great! One small change I can see is the placement of utility links in the popover. Those should be opposite of and at the same vertical offset as the primary value shown. So in the screenshot below, I'd expect "manage account" to have the same vertical offset as "Chris". Likewise, in your examples with longer character counts, I'd expect the lettermark to placed at the same vertical offset as "Elizabeth the second...".

Screen Shot 2021-10-28 at 10 50 28 AM

One functional change - when I click on an element other than the popover, or an element contained in the popover, the popover should dismiss. 

That's all I could find UX-wise. Nice job!

**Review by mariusandra — CHANGES_REQUESTED** [review]
1. All clickable things should have `cursor: pointer`


2. Release notes don't open.

3. While I love the fruitiness, I'm not sure if "Lemonade" is a good name for a folder in the codebase, as you need to investigate to figure out what it is. Is your plan to develop a new component library here, and this is a project name, or just being fresh? I'm just afraid of what we'll end up if we go far from conventional names like "funnels", "navigation", etc and enter the "banana", "lemonade", "aardvark" era. We can refactor/rename later, so no blocker from my side now... but would like to get some thoughts on this.

4. Also, what makes a button a lemon?

**Comment by Twixes** [comment]
@mariusandra Fixed. So, good question why all these things are citrus.
I mean, they could be just named "ButtonV2" or "NewButton", but then I thought that already doesn't look clean _and_ is very generic. So going with the lemon theme I'm naming Chris-style (as opposed to AntD-style) UI lemon-something so that we can then easily refactor it – all `grep` results with `lemon` _must_ be part of this new nav project. Last time around when we reworked the sidebar it was a bit confusing with things in very similarly named directories… so now it's extremely obvious. And definitely no plans to introduce bananas or any other fruits LOL

@clarkus Accidentally removed `onClickOutside` before pushing, that's why it didn't close. 😅 
Hm, I'm not sure if I got what the alignment should be exactly: in the one-line case, and in the multi-line case. Which one of the below should be used in the latter?

| `center` (current) | `baseline` | `flex-end` |
| --- | --- | --- |
| Zrzut ekranu 2021-10-29 o 10 43 56 | Zrzut ekranu 2021-10-29 o 10 43 50 | Zrzut ekranu 2021-10-29 o 10 43 40 |

**Review by mariusandra — APPROVED** [review]
LGTM and let's get this in.

I think just the first blue thing here should be top aligned, and the rest center aligned

All top:
image

All center:
image

Feel free to update if you want, and/or merge and tweak later.

**Review by mariusandra — CHANGES_REQUESTED** [review]
Actually, one bug. If your e-mail is `grzegorz.brzeczyszczykiewicz@interia.pl`, you end up with this:
image

The blue "manage account" button could just share the first line with the name perhaps? `float:right` if nothing else.

**Comment by Twixes** [comment]
Good catch with the email (very valid Polish one LOL), fixed (with no `float`):
Zrzut ekranu 2021-10-29 o 13 43 55
I'll get this in and work with Chris to smooth out the alignments in a separate PR.

**Comment by mariusandra** [comment]
[Awesome!](https://www.youtube.com/watch?v=AfKZclMWS1U) :D 

(could you also [review this next?](https://github.com/PostHog/posthog/pull/6719) really want to get to enabling this flag for cloud soon)

**Pull request merged**
