### PR TITLE
Percentages to Time Conversion + Better Y-Axis Labels + Misc. Fixes

### LINKED ISSUE #5302: Clean up histogram y-axis labels
## Bug description

Clean up y-labels so that gridlines are aligned and long numbers are abbreviated e.g. 5,000 -> 5K

Screen Shot 2021-07-22 at 4 28 05 PM

## Expected behavior

Expect y labels to be aligned, not cut off, and abbreviated.

## How to reproduce

1. The new time conversion funnel viz

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### LINKED ISSUE #5327: Histogram should show percentages
Our current histogram shows absolute numbers in the y-axis, yet the most important thing you probably want to look at is percentages to get a useful sense of distribution.

Keeping the absolute numbers might still be helpful, but secondary to percentages.

### LINKED ISSUE #5339: Conversion time distribution squished vertically
## Bug description

image

Conversion time distribution graph is very short vertically.

## Expected behavior
It should be easy to read, maybe 500px high or something.

## How to reproduce

1. Using safari image
2. Go to any funnel and hit time to convert

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Fixes a bunch of time conversion quality bugs, refactors it a bunch, and adds a few features. See below for a detailed breakdown.

- [X] Abbreviate y labels to use SI units (k, M, etc.). Fixes #5302.
- [X] Hide step 1-2 if only two steps
- [X] Standardize axis colors with existing LineGraph colors
- [X] Shift y labels to align
- [X] Fix squished height bug in Safari. Fixes #5339
- [X] Add absolute percentages above/below bar. Closes #5327.
- [X] Add kea logic tests for `histogramLogic`
- [X] Scrolling for many bins, adds min width to each bar so labels don't get squished

**Before**

Screen Shot 2021-07-27 at 5 24 21 PM

**After**

Screen Shot 2021-07-27 at 5 23 29 PM

Screen Shot 2021-07-27 at 5 24 59 PM

Screen Shot 2021-07-28 at 12 11 43 PM

Safari:

Screen Shot 2021-07-27 at 5 25 31 PM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [X]  Kea logic tests
- [X] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by clarkus — APPROVED** [review]
Looks good to me. I like how this aligns to the funnels layout. The only other thing I can think of testing is if the upper-bound for the number of bars changes based on percentages being shown. Those characters widths add up, so at some point they'll exceed the width of the bars. We'll want to limit that based on the available space in the chart.

**Comment by marcushyett-ph** [comment]
Fixes look good to me from a user experience perspective!

**Comment by alexkim205** [comment]
Thanks for that edge case @clarkus. I've added a min width to each bar and added some scrolling behavior similar to what we have for funnel steps.


https://user-images.githubusercontent.com/13460330/127381629-7757b9bd-5491-46d7-869b-bb700a369950.mov

Fewer bars and responsiveness demo:


https://user-images.githubusercontent.com/13460330/127382329-4b3304be-d28b-4145-b809-49bf104d649d.mov

**Comment by clarkus** [comment]
Those changes look good to me.

**Comment by alexkim205** [comment]
failing backend tests are unrelated, but have been nondeterministically failing

**Comment by EDsCODE** [comment]
merge master once #5364 is in

**Pull request merged**
