### PR TITLE
feat(cohorts): add cohort filter grammars

### PR DESCRIPTION
**Pull request by alexkim205**
## Problem

Adds filter grammars as part of cohort filtering project.

Design doc: https://docs.google.com/document/d/1fxgTkPLPzNGIlODCqOof3yc-5qqxPTDY3kgtQe_koa4/edit

## Changes

This PR is only responsible for implementing a foundational grammar for cohort filtering on the frontend. For this review, please ignore TODO's and styling. 

P.S: Also note that the AND/OR structure isn't refactored yet so what you see here isn't completely 1:1 with the mockups (the behavioral filter will be brought up into a separate section headline).

PPS: The diff ballooned because I ended up refactoring a lot of the existing selector components from https://github.com/PostHog/posthog/pull/9492. Static objects in `constants.tsx` also make up new ~700 lines as well.

https://user-images.githubusercontent.com/13460330/165378766-b5e3f314-f9ac-4871-bfe6-19a844c8fa24.mov

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8983%3A41658

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Storybook

### CODE REVIEW

**Review by clarkus — DISMISSED** [review]
Looks super good. I noticed there are still some `TODO` items in storybook, so maybe there is still more to review?. I saw a couple of things we could align.

When using the property criteria, the picker still references "events".
Screen Shot 2022-04-26 at 12 41 58 PM

The event / property picker here feels less actionable than all the other inputs. Since it's really just a more-capable selection control, can we give it the same button-like treatment you've set for the other components? TL;DR can we make the text on the event picker blue, too? Or make them all using the standard black... I can see benefits to both options, but the core concern is that they all look the same here. 

Screen Shot 2022-04-26 at 12 43 02 PM

**Comment by alexkim205** [comment]
Thanks @clarkus, addressed!

Screen Shot 2022-04-27 at 12 59 13 PM

**Comment by alexkim205** [comment]
Thanks @clarkus, addressed both concerns in this revision. This PR is now ready for a review!

I left one TODO for the property value selector, which depends on the row data logic implementation. I'll leave that for another PR.

**Review by clarkus — APPROVED** [review]

**Comment by alexkim205** [comment]
Merging this in to unblock frontend logic work. Pretty safe since it doesn't touch any components in prod.

**Pull request merged**
