### PR TITLE
Move rrweb player into repo

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

V0.0.1 of the new recordings player. There's still lots of things left to implement but this PR is just meant to get a rough first iteration out so that future PR's can start building on top of it incrementally. 

Everything new introduced here is hidden behind a FF `new-sessions-player` and code is separated out cleanly so that today's session player could be replaced by deleting a file and a few lines of code.

- [x] Moves `posthog/react-rrweb-player` into PostHog repo
- [x] Fixes bug where we set total time on loading first chunk and then revise once entire recording is loaded.
- [x] General UX redesign - separation of controller and frame
- [x] Move speeds into dropdown
- [x] New `sessionRecordingPlayLogic` that moves everything from local state to kea (holding off on writing tests for now to move quickly - ok for now because this is an improvement on today's code, which has no tests and more complicated logic).
- [x] Renamed `sessionRecording` to `session-recording` to keep code naming consistent. (probably why diff is deceivingly large)

### Immediate TODO

- [ ] Implement slider that just works better
- [ ] Events side list

Screen Shot 2021-10-18 at 11 14 21 AM

## How did you test this code?

- As noted above, holding off on writing logic tests. OK tradeoff for: 

image

### CODE REVIEW

**Comment by alexkim205** [comment]
Not sure why unrelated frontend tests are failing.

**Review by mariusandra — DISMISSED** [review]
Looks great in general and good to release with the flag, though somethings seems to be broken when the flag is off:



Also, I think kea-typegen made some comments in `frontend/src/lib/utils/eventUsageLogic.ts` go missing :/.

**Review by clarkus — APPROVED** [review]

**Review by rcmarron — DISMISSED** [review]
This looks good to me - excited to have the player in the main repo! Looks like there's one issue with the 'recording analyzed' event always firing (even if the modal is closed). Otherwise everything else worked for me.

Also, of note, I couldn't repro @mariusandra's issue. I'm wondering if it was related to the local FF issue, but that doesn't totally make sense because that was causing FFs to evaluate to `undefined`

**Comment by alexkim205** [comment]
Thanks both for the quick reviews :). I can't seem to reproduce the issue you're running into as well @mariusandra but the merge from master might have fixed that.

https://user-images.githubusercontent.com/13460330/137961749-0dccd19e-0e46-45a4-b815-b55c280dd6b0.mov

**Review by rcmarron — APPROVED** [review]
LGTM assuming @mariusandra 's issue is no longer happening.

**Pull request merged**
