### PR TITLE
Closes #337 - add stickiness of action to /trends

### LINKED ISSUE #337: Best / Heavy Users
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
I have DAUs but I don't know who are my heaviest/best users. If I want to optimize for those best users I need to know who they are and what they do. I also won't be able to see this in the aggregate

**Describe the solution you'd like**
I should be able to chart the number of days users perform an event within a week/month. I should be able to do this by cohort and the total user base and as a cumulative % of users and non cumulatively % - I should be able to measure this by a specified time period 

**Describe alternatives you've considered**
This could be done in a fiddly way with cohorts, by deciding the event and then clicking into each user to look through their event history

**Additional context**
Requested by: https://app.hubspot.com/contacts/6958578/contact/39151

### PR DESCRIPTION
**Pull request by timgl**
image

image

### CODE REVIEW

**Comment by timgl** [comment]
@jamesefhawkins If you fancy some QA this weekend? The environment is hooked up to the production database

**Comment by jamesefhawkins** [comment]
# UX feedback

I find the term "stickiness" not self explanatory, so I don't actually know if the displayed data is correct.

Is our definition the number of days that a user performs an action on in the given the timeframe?

I'd add that I *love* the idea of improving our ability to make clear how engaged users actually are with certain actions, excited to get this right!

**Comment by timgl** [comment]
Yep you're correct on the definition. It's a metric some other products use too. I could add some text, possibly under the button itself if you select stickiness.

something like "Stickiness shows you how many days users performed an action within the timeframe. If a user did an action on Monday and came back and did it twice on Friday, it would be listed as "2 days" in the chart.".

**Comment by jamesefhawkins** [comment]
That explanation makes sense. This is a very useful way to look at retention.

One small tweak, at first I didn't find it intuitive that I had to click this button to choose between stickiness and volume:

Screenshot 2020-03-17 at 15 51 13

Could we make that more obvious by using a dropdown the same style as the breakdown by select in the item above:

Screenshot 2020-03-17 at 15 51 54

**Pull request merged**
