### PR TITLE
Clickhouse Deduplicated Elements

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Use ReplacingMergeTree for elements
- Remove element_groups
- Use elements_hash as a virtual "pk"
- Refactor events query to match
- Use Redis to avoid inserting duplicate elements

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by mariusandra** [comment]
I added Redis caching in front of the `create_element` calls to take a bit of load off clickhouse. However even if duplicate elements are inserted into clickhouse, they will be conveniently ignored and/or discarded thanks to ReplacingMergeTree.

I think this is ready for an initial review. 

This PR will merge the `clickhouse-elements` branch to the `clickhouse-actions-paths` branch, which still has a few things to be fixed before that can be merged to `clickhouse-actions`.

**Review by EDsCODE — COMMENTED** [review]
Good catch with the element dup. That would've been a mess of repeats.
There are two areas where group_id need to be replaced/updated

1. `ee/clickhouse/sql/actions`  ELEMENT_ACTION_FILTER uses this within the query
2. `ee/clickhouse/models/element.py` serializer can be updated to reflect new table

**Comment by mariusandra** [comment]
Thanks, I'll check this. 
I found another bug - the cache key should contain the team id.

**Comment by EDsCODE** [comment]
ready to close?

**Comment by mariusandra** [comment]
Yeah, can be closed. I think that the fixes that were here and not in master got merged in with the paths.

**Pull request closed without merging**
