### PR TITLE
Event definitions & property definitions ordering

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

This PR grabs the filtering and ordering capabilities initially introduced in #4110 to return events & properties based on relevancy and allow special ordering and filtering.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by paolodamico** [comment]
Broken tests fixed, ready for a quick look

**Comment by paolodamico** [comment]
@timgl would you mind taking a look to avoid further merge conflicts with #4480?

**Comment by macobo** [comment]
No business context but lgtm - might be worthwhile benchmarking for netdata. :)

**Comment by liyiy** [comment]
I am sorry about the merge conflicts 😢 This might also be broken for enterprise version definitions since I couldn't figure out how to pass the order variable correctly into the raw SQL query (like turning the value `"name"` into `name` since `ORDER BY "name"` doesn't work, needs to be `ORDER BY name`)

**Comment by paolodamico** [comment]
It's fine, I think I'll close this. We're caching results in the frontend anyways, so probably worth doing ordering there.

**Pull request closed without merging**
