### PR TITLE
Smart Paths resize

### LINKED ISSUE #7175: Recalculate visualizations when nav sidebar is toggled
Lemonade UI brought us a navigation toggle. But the paths visualization width isn't isn't recalculated. This either leads to empty space (when collapsing the nav) or cutting off part of the viz (when expanding).

Note: The size _is_ correctly recalculated when resizing the browser, so seems like it just needs to also be run when toggling the menu now.

image

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Resolves #7175.

Only for `NewPaths` (feature flag `new-paths-ui`), but this is the only one that matters as it's rolled out to everyone now.
~~This needs to go in after https://github.com/PostHog/posthog/pull/7103 so that `useResizeObserver` can be used.~~

## How did you test this code?

Resized my window and toggled the sidebar.

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey, look at me trying to scope creep this PR:

**Comment by Twixes** [comment]
Damn Marius, cool it down with the scope or we'll hit a thousand lines in this PR soon enough!

**Comment by mariusandra** [comment]
🥶

**Comment by hazzadous** [comment]
looking now

**Review by hazzadous — APPROVED** [review]
Looks functional ✅

**Pull request merged**
