### PR TITLE
Maintain default feature flags behavior on cloud

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Following #5282 this maintains the default behavior on cloud for feature flags.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
I think this makes sense on many levels. Yet I'm slightly worried what might happen if cloud & master go out of sync regarding what flags anyone sees. In general it's fine, but I'd ping @macobo and @timgl 's opinion on this as well.

Using `0` or `[Ff]alse` to clear the flags makes sense as well, as otherwise there's no way to disable them except by setting them to gibberish (which includes `0` or `false` :D).

**Comment by paolodamico** [comment]
Alright merging this in now, if there's something wrong we can fix later in a separate PR.

**Comment by mariusandra** [comment]
Found an issue here. [The flag](https://app.posthog.com/feature_flags/839) `4267-taxonomic-property-filter` was released to just "posthog team except if email=marius@posthog". Thus for 2 weeks users on cloud got the old property selector and had to wait for the filters to load. I now added "or all users".

image

This is the kind of [cloud and master going out of sync](https://github.com/PostHog/posthog/pull/5296#pullrequestreview-713145474) issue someone should have warned us against! :D

**Comment by paolodamico** [comment]
I think it's fine that master and cloud are out of sync because we're usually testing different things and have different release cycles (e.g. running experiments on Cloud), but we could definitely improve our process to make sure what needs to be released is properly released. We could have a quick check every Monday to see everything is as expected.

**Pull request merged**
