### PR TITLE
Make funnel steps sortable

### LINKED ISSUE #936: Support funnel step reordering
**Is your feature request related to a problem? Please describe.**
I need to add a new step at the start of my funnel but I can't just insert a new one or move one to the start. I have to delete all existing actions+filters and start again.

**Describe the solution you'd like**
To click + drag actions to reorder them in the list.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Closes #936
- Closes #1245
- Thank you @glmaljkovich for all your work in PR #1245. I ended up using the `react-sortable-hoc` component that you referenced after all. `react-grid-layout` is unfortunately not suitable for fixed-height lists.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by glmaljkovich** [comment]
Cool!

**Review by EDsCODE — COMMENTED** [review]
Love this! Did a quick QA and found a bug. When you're using event based steps, reordering them will cause a crash/white screen. I think the onSortEnd handler is missing something?

The exact error is that actionfilterrow can't filter on undefined. I checked state and on line 195 in ActionFilterRow, filter is just { order: 0} when the bug happens and there's no other attributes which is causing the lookup to error out

**Comment by mariusandra** [comment]
I think I know what's up and will submit a fix as soon as I can. Thanks for the QA!

**Comment by mariusandra** [comment]
Ready for another look!

**Comment by paolodamico** [comment]
I'll take a look in a few hours once I can get to my computer 👨‍💻

**Review by EDsCODE — APPROVED** [review]
looks goood

**Review by paolodamico — APPROVED** [review]
lgtm! added a few suggestions in a separate PR #2888 mostly on UI, which I recommended merging in this PR before merging to `master` if they look good. @mariusandra for these type of suggestions do you prefer I use separate PR or just push to your same branch?

**Comment by mariusandra** [comment]
@paolodamico feel free to do the toe stepping ;)

**Comment by yakkomajuri** [comment]
Hey @glmaljkovich you did help make this a reality though so would love to send over some merch to you for your help!

Email me at yakko[at]posthog[.]com from your GH email so we can sort it out.

**Pull request merged**
