### PR TITLE
feat(hogql): Add ported ee tests for paths query

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

Follow up from #19959 

These tests cause some side effect that makes two seemingly unrelated tests fail 😭 

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by webjunkie** [comment]
@mariusandra do you fancy some investigative work figuring out these unrelated test fails here?
I moved them out of the original PR and they just get stale 🤭

**Comment by mariusandra** [comment]
This is really weird. Very hard to just guess what's happening. I'd investigate it with a binary search: comment out half the tests, wait 30 minutes, see if that makes it pass, and try again 😅

**Comment by thmsobrmlr** [comment]
> Hey wait, now they are green 👀
> 
> @thmsobrmlr we could get these in and then work on the skipped funnel ones in yet another PR?

Sounds fair to me.

**Review by thmsobrmlr — APPROVED** [review]

**Comment by thmsobrmlr** [comment]
nit-pick: maybe we could come up with a better file name for the tests or just add them to the other test file

**Pull request merged**
