### PR TITLE
Cache some /api endpoints on the client when navigating around

### PR DESCRIPTION
**Pull request by macobo**
Context: https://github.com/PostHog/posthog/issues/4567

This PR refactors the following endpoints not to be loaded every time we load insights:
- `api/annotation`
- `api/action`
- `api/projects/@current/event_definitions`
- `api/projects/@current/property_definitions`
- `api/person/properties`

Instead the data is stored on the client for 5 minutes or until they reload the page.

Some of these endpoints can return megabytes of data so this speeds things up significantly

## Future work

- Cache things in localStorage (but also invalidate when switching accounts?)
- Port /api/cohort endpoint to this - it has some crufty reload logic built in though
- Make caching logic smarter / provide users ways to force data to reload

## Commits

- Cache event definitions between navigating
- Cache property definitions while navigating around
- Cache person properties while navigating
- Cache actions
- Remove dead code from annotations logic
- Drop more dead annotations code
- Fix cohortsModel typing
- cache annotations inbetween navigation
- Update default filter if event definition is ever reloaded

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by macobo** [comment]
Needed to modify FE tests a bit to combat flakiness.

@mariusandra sending this your way - delegate if-as needed, my main goal is to get the ball rolling re performance fixes for key customers and app. :)

**Comment by paolodamico** [comment]
As discussed on Slack I believe @mariusandra is reviewing this on Monday (particularly analyzing the general approach), so I'll skip reviewing. If either you or @macobo think is still valuable I take a look please tag me for a review again and happy to take a look.

**Comment by Twixes** [comment]
What's the state of this #4627 having been merged?

**Comment by mariusandra** [comment]
There are still a few other fixes in this PR that I'll integrate before closing it.

**Pull request closed without merging**
