### PR TITLE
Run typescript with strict in CI, allow no new errors

### PR DESCRIPTION
**Pull request by macobo**
- Verify no new typescript code breaks "strict" compilation

As new code gets added and new type errors introduced, CI should now yell at you for failing typechecks.

Old errors are ignored using a file called `.ts-strict-blacklist` which contains file names + line numbers to ignore for errors. Ideally we'd remove files from that list as these errors get resolved or clean the file up every now-and-then.

Gotchas:
- Typegen files got ignored wholesale due to various bugs surrounding them
~~- This is much slower than it needs to be - we need to run kea-typegen 7 times to get the 'correct' type definitions out. This is something we'll hopefully fix soon.~~
- If adding code above the line giving the error, CI will start yelling at you. If the type error is not correctible, feel free to just set the whole file as ignored or similar.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by mariusandra** [comment]
What constitutes as "new code" here? If I edit some old file full of TS errors and change one line to fix a bug, will that line be considered as new code or the entire file I touch?

**Comment by macobo** [comment]
@mariusandra Took me a 'few' tries to get this green (due to various typegen issues). I've since updated the description.

**Review by Twixes — COMMENTED** [review]
This is cool but also… weird? I don't know. I say we can merge this just to see what happens, but would not rule out reverting if it turns out to be too weird.

**Comment by macobo** [comment]
@Twixes The basic concept is the same as this: https://sirupsen.com/shitlists/. 

In a large system getting rid of "bad-behaving" code is hard, so you do this by first enforcing no new errors can be added and then fixing things one-by-one later. This avoids large PRs, merge conflicts or working in areas of code where refactoring for sake of refactoring could introduce bugs or waste time.

**Review by mariusandra — APPROVED** [review]
Good to try!

**Pull request merged**
