### PR TITLE
Change global filters to filters

### PR DESCRIPTION
**Pull request by timgl**
## Changes

We've had some feedback that "Global Filters" is confusing, so I suggest changing it back to just Filters. Wdyt @paolodamico 

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by paolodamico — COMMENTED** [review]
I'm not sure about this, feedback comes from a single user, and I've seen the opposite in some usability tests, where the "Global" keyword helps clarify these filters vs. the series/step level filters. Maybe a different term? 

Think we should also add the info circle with a helpful tooltip explaining these filters?

Tagging @clarkus for thoughts too

**Comment by clarkus** [comment]
I agree with both of you to an extent. I feel like `global` is the wrong term, but agree that we need to clarify the difference between these filters. I've been calling these "step / series filters" and "insight filters" in my head. While global filters are global to the insight, you could argue that global communicates a broader scope than is really accurate. I'd recommend leaning on a secondary description to clarify scope. 

> Insight filters reduce or limit the data set for an insight, and take effect before step filters. 

> Step filters reduce or limit the data set for a given step or series in an insight, and take effect after insight filters. 

That's some rough text, but that would be enough to know how the scoping impacts the data set. Secondary to the clear labeling, we can rely on hierarchy and proximity to communicate the scope of a filter. Here's a screenshot from some recent work on our insight composition workflow. Step filters are clearly labeled, but they're also adjacent to the thing they affect, which reinforces their scope. 

Frame 8589

Thoughts?

**Comment by paolodamico** [comment]
I think something like that makes a ton of sense, it's straightforward and clear. Should we then close this for now, while we finalize and implement those new designs?

**Comment by clarkus** [comment]
@paolodamico I think closing makes sense. The most recent take on this flow is at https://github.com/PostHog/posthog/issues/5141.

**Comment by timgl** [comment]
@clarkus do we have a clear path to this getting implemented? If it's some way out it might still makes sense to merge this (or something similar) in the mean time.

**Comment by clarkus** [comment]
> @clarkus do we have a clear path to this getting implemented? If it's some way out it might still makes sense to merge this (or something similar) in the mean time.

@timgl I am still working out how this can scale across all our insights. The work at https://github.com/PostHog/posthog/issues/5141 was more targeted at seeing a visualization as soon as possible in the workflow. It's really a time-to-value exploration more than "make filters more obvious" solution. 

Short term I think adding in the descriptions would be the biggest improvement That could be our inline help icon with tooltip or it could be simple text under the header. I think the critical thing is knowing the order in which filters apply. Once we have descriptions, I think it'd be fine to drop the "global" qualifier from the label.

**Pull request merged**
