### PR TITLE
feat: Derive URL from the recording content instead of pageviews

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem
Related to https://github.com/PostHog/posthog/issues/16792
If you aren't tracking pageviews then the URL bar at the top is always empty.

## Changes

* Derive URLs from the rrweb events rather than the pageviews

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

👀

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
👍

**Comment by pauldambra** [comment]
Might be nice to have a loading state in that bar

Screenshot 2023-07-27 at 14 31 16

**Comment by benjackwhite** [comment]
Ooh yeah we could keep it around if we are buffering 👍

**Comment by benjackwhite** [comment]
Actually that's not so easy due to the different states that there can be... Will do it later if we do it.

**Comment by benjackwhite** [comment]
@pauldambra one better - realised we can ditch a bunch of waiting state as we always have a URL at least from the metadata response 💪

**Pull request merged**
