### PR TITLE
chore(plugin-server): migrate AWS SDK for JavaScript v2 APIs to v3

### PR DESCRIPTION
**Pull request by trivikr**
## Problem

From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.

## Changes

Migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).

```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 packages/feedback/*.js
```

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by trivikr** [comment]
Can someone review at this PR?

**Comment by trivikr** [comment]
cc recent active contributors @Twixes @mariusandra @pauldambra

**Comment by xvello** [comment]
Hello @trivikr and thanks for reaching out.

This code is unused so we will remove it instead. We also import the v2 SDK to inject in https://github.com/PostHog/snowflake-export-plugin and https://github.com/PostHog/s3-export-plugin/, but these plugins will be dropped later this year, as they are superseeded by a new export system. Until we fully sunset these two plugins, the v2 `'aws-sdk'` import will still show up on this repo, but can be safely ignored.

**Comment by trivikr** [comment]
Closing as maintainers responded that JS SDK v2 will be retained, and the code which uses them will be deprecated.

**Pull request closed without merging**
