### PR TITLE
fix: feature flags list view user filter

### PR DESCRIPTION
**Pull request by liyiy**
## Problem

feature flags "created by" filter was bugging out because of state

https://user-images.githubusercontent.com/25164963/189773147-8ac54795-ed54-44fa-9916-9afb51b7967a.mov

## Changes

https://user-images.githubusercontent.com/25164963/189773159-c73795e9-27e4-4b69-9f95-7599488c5533.mov

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by EDsCODE — COMMENTED** [review]
I think this is fine as a fix but the filtering should happen on the backend. Also before we merge a temp fix, is there a ticket/work tracking pagination as that's where we'll see issues here. Currently [several teams approaching a good number of flags ](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgdGVhbV9pZCwgY291bnQoKikgY291bnQgRlJPTSBwb3N0aG9nX2ZlYXR1cmVmbGFnIGdyb3VwIGJ5IHRlYW1faWQgT1JERVIgQlkgY291bnQgREVTQyIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)

**Comment by neilkakkar** [comment]
I think the opposite? Anything below a few thousand flags is going to be much faster filtered on the frontend, since no round trip latency, and filtering would be sub 100ms, and the memory usage for a thousand flags is pretty small (1MB -ish).

And we don't have to worry about the number of flags blowing up, because they're limited by human input, rather than machine input (unlike events/persons/properties).

Thoughts?

**Comment by neilkakkar** [comment]
Pagination makes sense! But I'd also say that should happen on the frontend, as then sorting isn't disturbed, you have all the data with you.

**Review by neilkakkar — APPROVED** [review]

**Comment by liyiy** [comment]
> I think this is fine as a fix but the filtering should happen on the backend. Also before we merge a temp fix, is there a ticket/work tracking pagination as that's where we'll see issues here. Currently [several teams approaching a good number of flags ](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgdGVhbV9pZCwgY291bnQoKikgY291bnQgRlJPTSBwb3N0aG9nX2ZlYXR1cmVmbGFnIGdyb3VwIGJ5IHRlYW1faWQgT1JERVIgQlkgY291bnQgREVTQyIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)

I wrote it in the backend originally and now I'm removing it in favor for the frontend because even we don't have enough feature flags yet to require backend filtering for it 😮 I still stand by my statement that it's prob better to just do it in the backend so we don't have to remember to refactor it eventually (so I agree with you) but in this case the "created by" issue would've required maintaining another state of `all feature flags` so it's cleaner to just combine it all into one `searched/filtered flags` state but also it would take a while for companies to intentionally fill out 1000+ feature flags which means we might not really need it in the backend ever?

**Comment by liyiy** [comment]
> Pagination makes sense! But I'd also say that should happen on the frontend, as then sorting isn't disturbed, you have all the data with you.

We already have pagination on the lemontable for this 🤗 max size of 100 per page

**Comment by EDsCODE** [comment]
Got it! Let's roll with this as it's ok for now and I added [this](https://github.com/PostHog/posthog/issues/11808) to track the eventual need

**Pull request merged**
