### PR TITLE
Move models to separate files

### PR DESCRIPTION
**Pull request by timgl**
## Changes

- move all models into their own separate files for readability, avoidance of merge conflicts, avoidance of 5k line files etc
- removed a few references to FunnelStep but haven't removed the model itself yet

## Checklist
- [x] All querysets/queries filter by Team
- [x] Code reviewed
- [ ] QA'd

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
What, no separate apps? 🤣
Seems good for me. The only question/change I would perhaps do is to also move files like `ActionStep`, `FunnelStep` into their own files (`models/funnel_step.py`). I'm used to this style from Rails, but it might not be a convention nor needed here.
In any case, approved even without that.

**Comment by timgl** [comment]
@mariusandra Haha

Moved `ActionStep` into a separate file, and removed FunnelStep completely (with subsequent migration).

**Comment by timgl** [comment]
@Tannergoods Big change so worth qa'ing. Annoyingly it's as broad as "anything could have broken" -- though I don't think it will have been!

**Comment by Tannergoods** [comment]
QA where I went

- [x] Setup - url, invite team, password change, slack integration
- [x] Dashboard -  add, remove
- [x] Trends - actions & events, multi properties, breakdown, shown as, events + actions, time intervals, sessions
- [x] Actions , Events - create new, delete, toolbar
- [x] Users, event stream, create, delete cohortas
- [X] Funnels,. create new, filters, delete
- [X] Paths

This all looks great!

**Pull request merged**
