### PR TITLE
fix: Prevent Popover overflowing window

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

The Popover can go out of bounds, especially in situations where the overall window position is fixed. 

## Changes

Apparently in FloatingUI ( the successor ) this [problem is fixed](https://floating-ui.com/docs/size) but nonetheless found a solution for our lib that takes care of ensuring the dimensions of the popover are never outside of the window, matching a traditional select box

|before|after|
|-----|-----|
|||

## How did you test this code?

* Added a storybook entry "LongSelect"
* Tested it in the modal example shown and a few other places

### CODE REVIEW

**Comment by benjackwhite** [comment]
@Twixes this still isn't perfect as it should ideally recognise that the upper area is larger than the bottom and use that instead but I couldn't figure out a quick way to handle that.

**Review by mariusandra — COMMENTED** [review]
Hmm. This means that sometimes, when the dropdown is at the bottom of the modal, the dropdown might behave like this:


Which isn't to say this isn't an improvement. Just... 🤔 

I'd be happy to take on the side-quest of upgrading our popups to floating UI, having built the original `<Popup />` component in the first place. Popper v2 was the latest and greatest then. Funny how fast the world moves.

The idea was always to build an abstraction, letting us swap out the engine whenever needed. Two other places in the codebase use popper directly.

**Comment by benjackwhite** [comment]
Personally I think that's not a big deal that it matches the window height but I get the point. It's a blocker for the Subscription work I would say so either we merge this as an improvement or we take the extra time to swap to the other lib

**Review by Twixes — COMMENTED** [review]
This seems correct. On the other hand the project that this is copied from says:

> # Don't use this
> Switch to Floating UI which supports this out of the box with no issues

So the migration idea seems well-founded. 😅

**Review by mariusandra — COMMENTED** [review]
The migration's proving to be suspiciously [tricky](https://github.com/PostHog/posthog/pull/10295). I think we need to upgrade to React 18 first 😅 

If we can get that `console.log` out, let's get this in for now.

**Pull request merged**
