### PR TITLE
fix: no insight data logic loading in session replay filters

### PR DESCRIPTION
**Pull request by pauldambra**
follow up to https://github.com/PostHog/posthog/pull/20709

That added a connection from `entityFilterLogic` to `insightDataLogic` assuming that there is always an insight data logic for every entity filter

But there is filtering in session replay and no insight linked to the entityFilterLogic. So this is causing errors in the console

I don't want to get trapped in the web of insight logic interactions so I won't try and break the dependency. 

If we set the doNotLoad prop when the `typeKey` is "session-recordings" then the connected insight data logic at least doesn't make any API calls

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
Hmm.. I think this issue is persent for every ActionFilter outside of insights. Does this block something with session replay currently? Otherwise I'd argue for a broader fix.

Thanks for looking into it in any case!

**Comment by pauldambra** [comment]
>  Does this block something with session replay

I'm guessing it's not free and we already thrash the browser 🙈 

>  I'd argue for a broader fix.

Totally, I just don't want that to be me doing it 🤣

**Review by webjunkie — APPROVED** [review]
Uh, I already felt that with connecting these logics is not ideal 😅 

I can take a look, probably next week.
We can do this quick fix here for the moment I guess.

**Comment by pauldambra** [comment]
> Uh, I already felt that with connecting these logics is not ideal 😅

Yep, for insight / dashboard logic interactions I used to use the insightsModel logic as a message bus. So here entityFilterLogic would call `insightsModel.seriesRenamed` (or similar) with the insight id, series, new name and all insight data logics listen and ignore or act appropriately (whether that is still or was ever the best solution is another thing 🤣) 

Thanks!

**Pull request merged**
