### PR TITLE
feat(jobs): use main DB as backup for jobs DB

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Problem

https://github.com/PostHog/posthog/issues/11784

## Changes

If a separate DB is specified for jobs, allow using the main DB as a backup.

### CODE REVIEW

**Review by hazzadous — COMMENTED** [review]
I'm not a big fan of this tbh but maybe I'm missing something.

Rather than trying to improve the availability of a Postgres instance, I would rather focus on being resilient to downtime on the Postgres instance. This should be something we can achieve given that we're talking about background processing.

Adding a separate db for a queue sounds like a complication we shouldn't introduce. It also looks like every anonymous user event gets inserted into the Graphile DB? Is there a danger that this load could affect the rest of the app if we end up switch to the main DB?

If we want to improve the availability of Postgres then perhaps there are other options to look at first?

I don't really know how the scheduling works though, so would love to learn more before committing to this.

**Comment by yakkomajuri** [comment]
Let's take a step back here - I think things are a bit unclear.

We want to ensure jobs are persisted somewhere so that we don't lose them. We may process them with a delay, but we want to process them.

On Cloud here's how that works. 

We take a job and try to add it to an Aurora instance that we run only for the purpose of jobs. Currently, if Aurora is down, we retry adding the job to Aurora from memory with exponential backoff.

If a) Aurora is down for long b) The plugin server crashes/restarts we lose the job from memory and thus do not have it anywhere.

The job queue manager was built with this in mind way back in the day. The idea is to have many stores (persistent or not) where the job would be added in case another store was unavailable.

Thus, what I'm proposing here is:

1. Always try to add to Aurora first
2. If we absolutely can't, try to add it to the main DB
3. Retry the process up to _n_ times

Maybe this was clear to you, but just clarifying either way.

Nevertheless, the point is that if we want to guarantee that we won't lose the job, we must have a fallback persistent (or persistent-ish) store to add the job to if one store is unavailable. So if not the main DB, what else? See #11784 for alternatives.

As for load, we currently enqueue ~1000 jobs per minute. For comparison, we insert ~1200 persons per minute, and that accounts for just 0.46% of runtime on our Heroku Postgres instance. We'd expect both of these to grow at similar rates too. 

We read jobs a lot less too - see how in this proposed solution we'd poll every 20s, so `3 * n_pods` SELECT queries per minute.

**Comment by hazzadous** [comment]
> Nevertheless, the point is that if we want to guarantee that we won't lose the job, we must have a fallback persistent (or persistent-ish) store to add the job to if one store is unavailable. So if not the main DB, what else? See https://github.com/PostHog/posthog/issues/11784 for alternatives.

I would suggest that taking advantage that the event is already persisted to Kafka is what we should be relying on. There are certain errors for which we should probably use stop on error for. There are some that may benefit from in memory retries, which may reduce the chance of issues, but we can always fall back on the fact that we have the event in Kafka and haven't committed an offset for.

 * For the failure case of PG being down, simply failing the batch may be an option and restarting the consumer.
 * For a failure where we manage to communicate with PG but there is an unrecoverable error, e.g. an Integrity error that would fail on retry, pushing to the DLQ may be relevant
 * For any other unexpected failures perhaps pushing to a retry topic is relevant. They may work the next retry, and pushing to the retry topic avoids blocking consumption from the main topic.

We can rely on Kafka persistence to give us the guarantees we want. Introducing some layered combination of persistence I would suggest isn't the way to go. We end up having to reason about more dependencies, adding these to health checks, we end up with more places that things can go wrong, we need to maintain schemas in both of these DBs, we need to test that these backup persistence layers are functional, we end up with multiple services we need to check in case of monitoring and debugging.

I don't think the alternative above is particularly difficult or complicated, but just involves deciding what to do on each class of error. We rely on Kafka persistence, and the guarantees it gives to know that jobs are persisted in the Aurora instance.

> As for load, we currently enqueue ~1000 jobs per minute. For comparison, we insert ~1200 persons per minute, and that accounts for just 0.46% of runtime on our Heroku Postgres instance. We'd expect both of these to grow at similar rates too.

We'd also be increasing the number of connections we have to Postgres I guess? Or perhaps we can just reuse the connections we already have. At any rate, it's creating a hole new class of issues that I think we can easily avoid, whilst creating a system that's more reliable and easy to manage.

Anyway, happy to go with this PR, but also happy to pitch in and help with the alternative.

**Comment by yakkomajuri** [comment]
You're thinking only of events here. That's a separate problem and one I agree with you 100% on. See #11790. 

Jobs are not in Kafka. They're nowhere. Some jobs (buffer jobs) may be enqueued as a result of an event, but many jobs are just triggered arbitrarily by plugins. They live nowhere.

**Pull request closed without merging**
