### PR TITLE
feat(Experiments): UX feedback from private beta of no-code experiments.

### PR DESCRIPTION
**Pull request by Phanatic**
## Problem

This PR addresses feedback from a private beta customer of no-code experiments. 

1. Can't tell if all transforms apply on Element selection in a variant.
2. Allow editing variants before an experiment is launched.
3. Cannot select SPAN & H2 elements

## Changes

1Show checkbox next to icon if a   transform is  enabled on the HTML element
image

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

👀

### CODE REVIEW

**Comment by jurajmajerik** [comment]
IMO two icons next to each other is not a great pattern because it is becoming cluttered. I'd probably remove the main icon and display a checkbox (in a circle) whenever the transform type has been applied.

image

**Comment by jurajmajerik** [comment]
image

Please make the variant name input field span the same width as the collapsible below. They are both form elements, having the same position in the hierarchy, so should be aligned.

**Comment by jurajmajerik** [comment]
image

Would be nice if changing the variant name input immediately changed the variant name of the collapsible.

**Review by jurajmajerik — APPROVED** [review]
Looking good, some design nits :)

**Comment by Phanatic** [comment]
https://github.com/PostHog/posthog/pull/25694#issuecomment-2425869433
Sounds good, I'll remove the icon for the type of transform and instead add in a checkmark

**Comment by Phanatic** [comment]
https://github.com/PostHog/posthog/pull/25694#issuecomment-2425878354
I tried doing this the first time I built this header, but sadly, because we order the headers by name, we end up having to rearrange the variants on each keystroke. Gif is here
change_as_i_type

**Comment by Phanatic** [comment]
https://github.com/PostHog/posthog/pull/25694#issuecomment-2425874837
this is fixed now

**Pull request merged**
