### PR TITLE
Add `urls` to programmatically create routes

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- WIP, publishing to get some early feedback (share if you have any)
- Adds functions like `urls.dashboads(123) === "/dashboard/123"` that should now be used instead of hardcoded URLs. 
- It's a lot of things to manually write now in `sceneLogic` when adding a new url... 🤷 . We can simplify later...?

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by macobo** [comment]
Q: What's the problem being solved? If applied for API, it seems to add an extra step to be able to figure out the data flow, increasing overhead. However this seems to be frontend-only.

**Comment by mariusandra** [comment]
So a bit of context. This is part of the "improve frontend stability" goal. 

While there's admittedly little value in `urls.dashboards() == '/dashboard'` (other than type safety and not forgetting the `s` at the end of it), what this PR begins would greatly help with issues like https://github.com/PostHog/posthog/issues/4681 -- where you want to link to more complicated objects throughout the interface. `filteredInsight(filter) == '/indsights?insight=TRENDS&interval === day....'`

Having one consolidated place where to look for urls, instead of them scattered all around with custom builders, would make for a stronger and stabler interface.

We haven't had many urls change (other than `/plugins` --> `/project/plugins` that caused some bugs), but this would also assure if something changes, every place that links to it is immediately updated.

**Comment by mariusandra** [comment]
The inspiration for this change came when I realised that I can't CMD+click "funnels", "retention", etc here, and that it would be a lot of wasted effort without a global solution that makes linking easy:

image

**Comment by macobo** [comment]
I'm excited for this!

**Comment by Twixes** [comment]
This looks like a good idea. Could you make it ready for review?

**Comment by mariusandra** [comment]
I'd love to get this out the door, but managed to run out of time before going on holiday.... and got dazed with the merge conflicts now. Plus many more links should get converted.

If anyone else could take it over, that would be really great! @Twixes or @macobo or @liyiy or @alexkim205 or @paolodamico perhaps? :)

**Comment by paolodamico** [comment]
I can pick this up if no one else wants/can

**Comment by paolodamico** [comment]
FYI @mariusandra for when you get back, your PR originally got rid of `openScene` and all related logic, but couldn't find where this was going so I reverted for now.

**Comment by paolodamico** [comment]
Alright merged master, fixed conflicts & tests, and migrated URLs across the app to use the new methods. There's probably URLs missing (particularly in HTML components but we can leave those for a subsequent iteration). Would appreciate a quick review as this affects a ton of components.

**Review by liyiy — APPROVED** [review]
This seems good to me, gave it a quick click around and everything is working fine

**Comment by paolodamico** [comment]
Thanks for the review @liyiy !

**Pull request merged**
