### PR TITLE
Groups: Handle groups in /my_flags endpoint and toolbar

### LINKED ISSUE #7360: Toolbar does not respect groups for which flags are enabled
## Bug description

When I open the toolbar, I won't see flags enabled that are group-based

## Expected behavior

These flags work

## How to reproduce

1. Create a flag which matches groups
2. Be part of match group
3. Open toolbar
4. See flag is reported as not enabled

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Problem comes from how groups support is implemented. In posthog-js users call `.group()` at the start of their pageview to set their relevant groups and these get forwarded to `/decide` endpoint.

In the toolbar we don't have access to `posthog-js` and cannot call `posthog.getGroups()` to forward the same data to `/my-flags` endpoint.

I'd love to avoid a solution that tries to 'remember' groups on the server-side for the user as this conflicts with the whole groups data model.

@mariusandra curious if you have ideas on how to remedy this? Is there any way we can communicate state from posthog-js which we know will be active on their page?

### PR DESCRIPTION
**Pull request by macobo**
This fixes https://github.com/PostHog/posthog/issues/7360

The two-way data communication here is a bit iffy but /shrug

## How did you test this code?

Unit tests
Also create a feature flag with groups, checked toolbar state.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Seems to work, but rather iffy indeed. I guess there was a reason to go for this approach, and not query "groups the user belongs to" inside `/my_flags`?

**Comment by macobo** [comment]
It's because users don't belong in groups schema-wise.

**Comment by mariusandra** [comment]
Are you saying there's no way to look up the groups a user belongs to? That sounds... odd.

I haven't looked at the schema, but every place where we let the user decide what data is theirs ("I'm in groups 2, 5 and 8, give me the flags") sounds sketchy.

**Comment by macobo** [comment]
Yes. In group analytics users don't belong in groups because this leads to double-counting events (how would you count how many paying organizations do you have?). Instead _events_ belong to groups, representing that the user was active in a particular group at a particular time.

Check out the original RFC [here](https://github.com/PostHog/meta/pull/30) or the upcoming groups documentation.

**Pull request merged**
