### PR TITLE
chore(clickhouse): use posthog database when checking version

### PR DESCRIPTION
**Pull request by hazzadous**
## Problem

By default the clickhouse client we use uses `default` as the database.
This will cause problems in situations where there is no `default`
database. For the ClickHouse version check we use this `default_client` which 
doesn't specify the database (the other clients in this file do) hence 
we get:

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/code/posthog/apps.py", line 43, in ready
    in_range, version = service_version_requirement.is_service_in_accepted_version()
  File "/code/posthog/version_requirement.py", line 28, in is_service_in_accepted_version
    service_version = self.get_service_version()
  File "/code/posthog/version_requirement.py", line 36, in get_service_version
    return get_clickhouse_version()
  File "/code/posthog/version_requirement.py", line 58, in get_clickhouse_version
    rows = client.execute("SELECT version()")
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 267, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 453, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 117, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 133, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 150, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 81.
DB::Exception: Database default doesn't exist. Stack trace:
```

This version check happens prior to the initial clickhouse database creation migration `0001_initial.py` so it 
would also fail if we used the `CLICKHOUSE_DATABASE`

## Changes

Updated default client to explicitly specify the "system" database.

## How did you test this code?

Existing tests didn't fail.

### CODE REVIEW

**Review by yakkomajuri — COMMENTED** [review]
how long has it been since the default db has become `posthog`? I remember that when writing this connecting to posthog would say the db didn't exist, and note that this runs before migrations.

I've just created a fresh database locally and `default` exists - so I saw that's what we have in docker/clickhouse/config.xml.

Provided we ensure the default database is consistent across deployments, I'd be happy to change this. But note that there's a problem where `CLICKHOUSE_DATABASE` is an env var but the default db is hardcoded. Thus let's use a const here for a db we know exists.

**Comment by hazzadous** [comment]
> how long has it been since the default db has become posthog?

On Cloud I'm not sure but I imagine posthog has been default from the beginning.

>  I remember that when writing this connecting to posthog would say the db didn't exist, and note that this runs before migrations.
>
> I've just created a fresh database locally and default exists

I try to clarify the behaviour here, and if possible make sure local dev env is representative with minimal dependencies 🤞

**Comment by yakkomajuri** [comment]
My point is then - can we update docker/clickhouse/config.xml and set this to a string literal `posthog`? That db should always exist, even if someone sets `CLICKHOUSE_DATABASE` to `foobar` which we then create via migrations

**Comment by hazzadous** [comment]
@yakkomajuri I opted for specifying the `system` database instead. We already make the assumption that this database exists and we have access to it.

**Review by yakkomajuri — APPROVED** [review]
Perfect, was actually thinking the same at this point!

**Pull request merged**
