### PR TITLE
Increase Element model varchar limits again

### PR DESCRIPTION
**Pull request by Twixes**
Reverts PostHog/posthog#3923. Would still be good to get this in, but we need to identify why this seemingly simple migration failed to run in production.

### CODE REVIEW

**Comment by mariusandra** [comment]
Locking of sorts that's impossible to predict? Certain tables with massive usage will just have to remain append only from now on :).

**Comment by Twixes** [comment]
That's the thing, table usage should be irrelevant here as in Postgres this should only be a table check update, and not even one causing a table scan since Postgres knows that all existing rows are fine if the varchar limit is only increased.

**Comment by Twixes** [comment]
I suspect it's typical ORM crap: running crazy big queries for something where only a tiny bit of data is needed, or in this only a tiny table metadata migration.

**Comment by mariusandra** [comment]
Yup, but we have learned by now that theory and practice don't align here :(.

**Review by mariusandra — APPROVED** [review]

**Comment by Twixes** [comment]
Identified the issue: clearly Postgres is not smart enough to apply the same no-scanning-needed `ALTER` logic to `varchar[]` (note brackets – Postgres array) columns, causing locking. And here the offending column was `attr_class`. We didn't see its length being a problem though, so let's just keep it as is and migrate for the rest.

**Pull request merged**
