### PR TITLE
feat(dashboards): Show badge on refresh button when auto refresh on

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Working with dashboard reloads recently, I've been leaving auto-refresh on and a couple times forgot about it, making for some surprise ghost refreshes.  

## Changes

I propose a tiny badge to indicate when auto-refresh is on:
Screenshot 2024-06-13 at 12 35 48

### CODE REVIEW

**Review by thmsobrmlr — APPROVED** [review]
Makes sense

**Comment by webjunkie** [comment]
Just had the same idea yesterday https://github.com/PostHog/posthog/pull/22911 😆

**Review by webjunkie — APPROVED** [review]
Can we make it more subtle?

**Comment by Twixes** [comment]
Oh hahaha, I didn't notice your PR – great minds think alike.
Good point with subtlety, made it muted:
Screenshot 2024-06-13 at 13 12 03

**Pull request merged**
