### PR TITLE
fix(sso): add org creation confirmation screen

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

User's accidentally create new organizations when attempting to login via SSO. This happens if the user:
* SSOs with a personal email when they mean to use a work email (common for GitHub SSO)
* SSOs on posthog cloud, when they intend to log into self hosted
* Hasn't been invited to an organization (and the org doesn't have JIT enabled), and they attempt to SSO in

This has happened to ~1200 users, and is super confusing because the user ends up in the ingestion flow when they expect to be intend to be in a project. Notably, this happens very often for our largest self-hosted customers.

[Recording showing it happen yesterday](https://app.posthog.com/person/oRXN86XciuKnzD099faPatpuHXlSRbbtyTegIZbhd8P?filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222022-05-12%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list#activeTab=sessionRecordings&sessionRecordingId=180ddcfdb2f33-0fa432767b307d-c555420-1fa400-180ddcfdb3028)

## Changes

Adds a "confirm creating new organization" screen. This appears if a user SSOs in, and a new organization would normally be created. 

[Figma here](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10540%3A42380)

image

(GitHub won't let me upload the video of it working, so the pic has to do for now)

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Updated the backend tests. I should probably add tests to the logic, but it's getting late here. Will plan to add those tomorrow.

### CODE REVIEW

**Review by liyiy — APPROVED** [review]
LGTM, would merge if @mariusandra doesn't have any feedback for this

**Comment by liyiy** [comment]
well obviously once tests are passing, of course 😄

**Review by mariusandra — APPROVED** [review]
Looks good. I didn't run to check, but will this warning show up for the first organization/user on an instance as well, or that's taken care of through a different flow?

**Review by clarkus — COMMENTED** [review]
The copy changed - should that be reconciled with what we have in [figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10540%3A42380)? Should there be a cancel action here to go back to the previous step?

**Comment by clarkus** [comment]
Made some quick iterations to deprioritize the message and give a meaningful, succinct prompt that is expanded via a "read more" action. Clicking read more will expand to show the full content of the message. There is no "collapse" action. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10704%3A48809

Screen Shot 2022-05-24 at 9 39 17 AM

Screen Shot 2022-05-24 at 9 39 28 AM

**Comment by rcmarron** [comment]
Great, just updated to the new designs here. Made one slight tweak on the copy.

image
image

**Comment by rcmarron** [comment]
> will this warning show up for the first organization/user on an instance as well, or that's taken care of through a different flow?

@mariusandra, yeah, those user will hit this page now. We just updated the warning, so it's a bit less jarring.

Also, for reference, they used to hit the page below, and now will hit the one above instead: 
image

**Comment by rcmarron** [comment]
Planning to merge this after code freeze tomorrow

**Pull request merged**
