### PR TITLE
Honour JS_URL in production, heals #4009

### LINKED ISSUE #4009: JS_URL env variable is not honoured in production
## Bug description

Setting `JS_URL` is not honoured in production. Webpack has a hard coded `/static/`

## Expected behavior

Ability to override the publicPath of Webpack

## How to reproduce

1. Set `JS_URL` to a URL of choice and `NODE_ENV` to `production`
2. Build Webpack assets

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.24.0

## Additional context

Looks like it's only used in non-production environments.

https://github.com/PostHog/posthog/blob/f7dfc7f7e24a2f83b7e1fe8dfa168a71522c1e01/webpack.config.js#L73-L78

### PR DESCRIPTION
**Pull request by lharress**
## Changes

Respect `JS_URL` environment variable when building Webpack assets for production.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by timgl** [comment]
Hey, thanks for raising this PR.

What's the reason for this change? Do you run your JS somewhere different from the PostHog backend?

**Comment by lharress** [comment]
We'd like our static assets served through a CDN without putting something like Cloudflare in front of our entire stack (we're unable to take this approach due to contractual obligations/reasons).

I see this more as a bug;
> JS_URL | URL used by Webpack for loading external resources like images and files.
https://posthog.com/docs/configuring-posthog/environment-variables

This is not the case in production, it's only honoured in development environments.

**Review by Twixes — APPROVED** [review]
This makes sense to me, I'll just ping @macobo to make sure that this won't affect any existing deployments (which I'd presume don't have a custom `JS_URL` env var value).

**Review by macobo — APPROVED** [review]
This seems perfect, thank you! Should affect no issues, but checking out the test failures before merging.

**Comment by lharress** [comment]
Thanks!

**Pull request merged**
