### PR TITLE
feat: pre-fill existing tags for insights, actions, event definitions, and property definitions

### LINKED ISSUE #10678: Pre-populate existing tags
It'd be nice if previously-used tags populated in here, so I don't have to type them from scratch or worry about mistyping using a slight variation.

image

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

closes #10678

There are several pages where you can add tags to an item. But we only suggest existing tags on one of them.

## Changes

Suggest tags on insight, action, event definitions, and property definition pages

Adds an API to event definitions and property definitions to allow this. There's no pagination but there are (at least for now) very few tags on these types.

### property definitions

property_definitions

### event definitions

event_definition

### insights

insights-tags

### actions

actions-tags

## How did you test this code?

added developer tests and checked in the UI locally

### CODE REVIEW

**Review by mariusandra — CHANGES_REQUESTED** [review]
Hmm.. I think tags should be global. That means, if you add a tag "marketing" for an insight, the same tag should be available when you tag actions. There's a lot of code duplication here to prevent that from being a thing. 

Also, to avoid refactoring this later, I think we should use the taxonomic filter to select tags, giving us autocompletion and pagination virtually for free.

**Comment by pauldambra** [comment]
>  I think tags should be global.

fair

> we should use the taxonomic filter

Oh, I hate changing the taxonomic filter 🤣 . I think I'll split this into two steps ✂️

**Comment by pauldambra** [comment]
Tags are now project "global"

tags

**Review by mariusandra — APPROVED** [review]
I could nit on a thing here or there, but I won't 😅. Looks good to me! 👍

**Pull request merged**
