### PR TITLE
fix: disable add to dashboard button

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

If you have no edit rights on a dashboard you can't add it to (or remove it from) dashboards

We present the button as if you can add to dashboard, let you choose a dashboard, and then give you an error message

permissions-before

## Changes

Disables the button if you don't have edit permission

## How did you test this code?

running it locally and checking it still works

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
What bout "Add to a new dashboard"?

**Comment by pauldambra** [comment]
> What bout "Add to a new dashboard"?

Do you mean they should be allowed to?

Currently if you try... we create the dashboard (cos you have permission to do that) and then fail to add the dashboard to it



This change doesn't let you get to that button

**Comment by Twixes** [comment]
Ah, right, I misunderstood the change a bit. So, it in fact makes it impossible to see directly on _which_ dashboards the insight is if you can't edit it. This is safe, but might be a bad experience if you just want to go from the insight to a dashboard (which normally is very easy). My suggestion is to just disable the buttons _in_ the modal so that view access is not hampered.

**Review by Twixes — APPROVED** [review]
👌 Nice improvement

**Pull request merged**
