### PR TITLE
Add cloud job queue envs

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Enables the S3 job queue as a backup to postgres for PostHog cloud
- Still needs some manual testing before being ready for merge

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by Twixes** [comment]
How far from merging this are we now?

**Comment by mariusandra** [comment]
I'm still hesitant to publish this before https://github.com/PostHog/plugin-server/pull/446 works well, but I haven't had a chance to look at it. If nobody else has this problem, then I don't know :).

Also the credentials in AWS that this PR links to need to be refreshed, as I shared them randomly in Slack a few times, and I'm not sure what test data they still contain.

**Comment by neilkakkar** [comment]
As far as I understand things: we don't have things setup yet to resort to a backup queue, yet? Merging this as is would mean everything goes to both queues, instead of s3 being a backup?

I think this missing bit should come before we merge this PR (and figure out if it's just Marius's queue that's borked). For the latter bit, I was hoping @Twixes could try running the S3 queue? (https://posthog.slack.com/archives/C01F6QWTVB5/p1622632083123700?thread_ts=1622536636.109200&cid=C01F6QWTVB5)

**Comment by Twixes** [comment]
I'm gonna wait for Marius until closing.

**Comment by mariusandra** [comment]
@yakkomajuri @tiina303  do you think this is something that works reliably enough and could be enabled? The point is to have a backup backend for queues in case graphile goes down for whatever reason.

**Comment by yakkomajuri** [comment]
I'd like to give this (and all job queues epic stuff) a better look once I'm back. Happy for @tiina303 to make a decision in the meanwhile.

**Pull request closed without merging**
