### PR TITLE
Show clickhouse disk and system.stats on /instance/status

### PR DESCRIPTION
**Pull request by macobo**
Part of https://github.com/PostHog/vpc/issues/45

image

image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by macobo** [comment]
If you have thoughts on what other metrics to expose, shoot here or under the linked issue!

**Review by fuziontech — APPROVED** [review]
Perfect! 👨‍🍳 👍

**Comment by fuziontech** [comment]
Doesn't really matter, and might actually be something that we _want_ to do because we are `open source` - but is this something that we want to be exposing on app?

**Comment by macobo** [comment]
> but is this something that we want to be exposing on app?

Not 100% sure but the metrics seem fairly innocent. For self-hosted instances these may include information we'd want for debugging and asking them for shell access to DB is quite a lot.

On app.posthog.com this page is only exposed for super-admins (us)

**Pull request merged**
