### PR TITLE
938 wire in the FE for multi property breakdown funnels

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

This firms up that the contract between FE and BE will be sending breakdown (a single property breakdown) OR sending breakdowns (a multi property breakdown)

A client has to send a multi property request in order to receive one. So this change has no effect when the feature flag is off in the FE

It also makes the `TaxonomicBreakdownFilter` aware of the multi property breakdown flag so that when the flag is on someone can choose multiple breakdowns

### TODO 

- [x] better display of multi property breakdown in labels
- [x] don't display the name twice in single property breakdown & old vertical funnels combo

me-fe-3

## How did you test this code?

unit tests and exploratory testing by using funnels

### CODE REVIEW

**Comment by pauldambra** [comment]
Bias for ~~action~~ asking for review

I think this is ready... I can't decide if I should delete the gigantic data tests on funnelLogic. They were really useful in understanding the system. And would be a guide if we choose to spend time simplifying the funnel data structure. But they're mahoosive

**Comment by pauldambra** [comment]
@clarkus it was hard to see the different breakdown properties so I put them in small pills and limited max width (as very long URLs made the table stretch too far). 

Does that work?

**Review by mariusandra — CHANGES_REQUESTED** [review]
1. It's kind of weird that one of the two is a rounded button, the other a square one:
image

2. Correlation analysis gives errors


3. I think it used to be the case that the breakdown value was persisted from one tab to the next (just like the events are). It's not so on app right now, but should we persist them somehow?


4. All those `funnelLogic.test` tests are nice, but I think they're way too verbose. First, if ever edit any of the inconsequential filters anywhere in the code, we'll start getting errors here. To help with the verbosity, I'd either move the data to a new file, to some `mockedResponse` variables that can be reused, and/or use `partial`, and only check that the pieces of data we really care about are correct, no matter what other fields there are.

**Comment by pauldambra** [comment]
@mariusandra point 1 was introduced by funnel simple mode...

https://github.com/PostHog/posthog/pull/7252/files#diff-2d89e00c6f1089fc4dd9a9ad3a3982b29858eba738590bf68a491d3b3643d614R25

but isn't there in master currently https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/PropertyFilters/PropertyFilters.tsx#L38

I don't have enough context to know which button style to fix... @paolodamico  ??

button

**Comment by pauldambra** [comment]
1. tempted to fix outside of this issue. 
2. correlation API fixed - removed the DataClass that needed manually serializing everywhere
3. fixed - although when going from a multi-property funnel to single property trends you have to lose some data
4. deleted the tests and raised an issue so I don't forget that the improvement is there to be made

mp-fe-5

**Review by mariusandra — APPROVED** [review]
Looked through the code, played with the interface, LGTM.

**Comment by clarkus** [comment]
> @clarkus it was hard to see the different breakdown properties so I put them in small pills and limited max width (as very long URLs made the table stretch too far).
> 
> Does that work?

Sure but I think we should truncate in ways consistent with other insights. The most relevant example is probably in the path insight. It's pretty basic truncation from what I remember. @paolodamico previously mentioned the need for a truncation utility that considers the formatting of the thing being truncated - if we know we're truncating a URL we can try to format and summarize in ways that still represent the meaningful portion of the URL. Anyway, I am a 👍 , but I do see the eventual need for some smarter truncation in these components.

**Comment by paolodamico** [comment]
Definitely! For instance if you have a single domain host, we could easily remove that. Removing the query string could be quite relevant too in other scenarios.

**Pull request merged**
