### PR TITLE
Activate turbo mode

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Removes the turbo mode feature flag

## How did you test this code?

- Ran `yarn test` locally, and clicked around in the app. 
- Running CI now to see if E2E tests pass

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
Looks good except for one leftover TODO comment I found in `actions.js`, it says "is this only because of turbo mode?" 👁️

**Comment by mariusandra** [comment]
Nice catch! Regarding the comment itself:

```ts
// cy.reload() //TODO is this only because of turbo mode?
```

That reloaded a page, which worked with turbo mode, but didn't when you opened the URL. 

Theoretically, we might always have two different paths you get to the same data in the app, one by loading from scratch, the other by taking what's already in the app. There are bound to be differences in implementation. So we should either: 

a) over engineer this and test by reloading every time the URL changes, plus taking a snapshot of the DOM before and after the reload, and some other magic
b) test by never reloading, but just clicking around and hoping for the best
c) both, because who knows if the behaviour is different even if renders the same with "a" over multiple pages

I vote "b for now"

Some test is failing though.

**Comment by mariusandra** [comment]
Merged with master and fixed tests. Ready for a re-review @Twixes

**Review by Twixes — APPROVED** [review]

**Comment by EDsCODE** [comment]
~~I think this introduced some flakiness in the jest tests~~ ~~or the test itself when introduced [here](7287) was just flaky~~ Nope, it is the test that changed in here

**Pull request merged**
