### PR TITLE
Paths dashboard item fix

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

I think it's unreasonable to try to squish a giant paths viz inside of the tiny dashboard item box, so let's enable scrolling inside of it?

https://user-images.githubusercontent.com/25164963/136963787-86a863ce-90bb-4e5f-85c3-84a3013fc749.mov

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by EDsCODE** [comment]
We could force a minimum size for paths viz? it's unreasonable to do anyhting paths related inside such a small window

**Comment by liyiy** [comment]
> We could force a minimum size for paths viz? it's unreasonable to do anyhting paths related inside such a small window

What do you mean by force a minimum size?

**Comment by EDsCODE** [comment]
Have a minimum height and width for a dashboard item when it's a paths viz

**Comment by macobo** [comment]
Anything I can do to help this?

**Pull request closed without merging**
