### PR TITLE
Fix double tab opening when clicking with META

### LINKED ISSUE #1889: Simplify AWS CloudFormation deployment instructions
## Is your feature request related to a problem?

The current [AWS cloudformation documentation](https://posthog.com/docs/deployment/deploy-aws#cloudformation-install-recommended) is quite wordy, making setting things up intimidating and take far too long.

## Describe the solution you'd like

The best-in-class solution and documentation for setting up ECS clusters with CloudFormation is https://github.com/buildkite/elastic-ci-stack-for-aws.

It has:
- Clickable deploy button
- AWS CLI instructions for install + upgrading based on a local config file
- Repo with a issue tracker and relevant config -> easy for users to make improvements

~~Ideally we'd also create a repo, link to documentation from there and automatically deploy relevant config changes to S3 on merge.~~ This already exists at https://github.com/PostHog/deployment.

## Describe alternatives you've considered

Keep current solution.

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Fixes #1889 

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by macobo** [comment]
TIL. Thanks!

I'm noticing that Link and LinkButton components onClick handlers drifting a bit - Is that a problem, perhaps we can unify them somehow?

**Review by macobo — APPROVED** [review]
LGTM, didn't test since didn't reproduce for me.

**Comment by mariusandra** [comment]
Good point. Merged the two!

**Review by macobo — APPROVED** [review]

**Comment by paolodamico** [comment]
Works for me in Chrome. In Firefox the new tab is now only opened once but the active tab switches to the new tab, this is definitely a huge improvement, but we should keep in mind to fix this later, as when you do cmd + click you expect to keep the focus on the current tab.

**Pull request merged**
