### PR TITLE
feat: update placement and verbiage for sign in and register links on auth forms

### LINKED ISSUE #9520: Updated placement of register and sign in links for authentication
## Is your feature request related to a problem?

We updated the authentication screens a bit ago, but the placement of registration and authentication links shipped with some inconsistencies. Sometimes links are shown in the form header, sometimes as tertiary actions adjacent to primary buttons. This is possibly intentional, but the SAML/SSO workflow for authentication lacks a link back to registration entirely. 

## Describe the solution you'd like

Consistent placement and verbiage for these links. These links will move into a consistent position adjacent to the primary actions for the form. To achieve this, the password recovery action and password strength indicator will move into a consistent position opposite the password input label. 

I updated the [authentication and registration flows in figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/?node-id=3558%3A32653) to illustrate this change.

Login
Register (default)

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem
Closes https://github.com/PostHog/posthog/issues/9520

The auth forms (sign in, login) both link back to the other so that someone can easily go from one to another. However, the location and verbiage of these links was inconsistent between the two forms.

## Changes

- On the register (/signup) form, the link to log in was moved to below the "Create Account" button.

| Before  | After |
| ------------- | ------------- |
| image  | image  |

- On the login form, the "forgot password" link was moved to above the password field, next to the label
- On the login form, the "Create an account" link had some descriptive text appended to the front to be consistent with the verbiage on the register form

| Before  | After |
| ------------- | ------------- |
| image  | image  |

The changes were based on the [designs](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/?node-id=3558%3A32653) provided in https://github.com/PostHog/posthog/issues/9520 

## Concerns

1. For the "Forgot Password" link placement I followed the existing convention found in the register form where the extra stuff (ie. password strength indicator) is included in the `<label>` element. However, I do have slight misgivings about this pattern since it's likely not the best for accessibility to have all that in the `label`. I considered modifying the `Field` component to handle this properly, but decided to go with convention for now and make those changes if requested. 

## How did you test this code?

- I clicked the links to make sure they go where they are expected to go. 
- I tested on different screen widths to make sure it all shows up and looks decent.
- I ran `yarn test` and got some errors:

```
Summary of all failing tests
 FAIL  lib/components/ActivityLog/activityLogLogic.plugin.test.tsx (14.679 s)
  ● the activity log logic › humanizing plugins › can handle exports finishing

    expect(element).toHaveTextContent()

    Expected element to have text content:
      Finished exporting historical events between 2021-10-29 and 2021-11-04 (inclusive).
    Received:
      Finished exporting historical events between 2021-10-28 and 2021-11-03 (inclusive).

      157 |             const actual = logic.values.humanizedActivity
      158 | 
    > 159 |             expect(render(<>{actual[0].description}</>).container).toHaveTextContent(
          |                                                                    ^
      160 |                 'Finished exporting historical events between 2021-10-29 and 2021-11-04 (inclusive).'
      161 |             )
      162 |         })

      at _callee9$ (lib/components/ActivityLog/activityLogLogic.plugin.test.tsx:159:68)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (../../node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● the activity log logic › humanizing plugins › can handle exports failing

    expect(element).toHaveTextContent()

    Expected element to have text content:
      Fatal error exporting historical events between 2021-10-29 and 2021-11-04 (inclusive). Check logs for more details.
    Received:
      Fatal error exporting historical events between 2021-10-28 and 2021-11-03 (inclusive). Check logs for more details.

      175 |             const actual = logic.values.humanizedActivity
      176 | 
    > 177 |             expect(render(<>{actual[0].description}</>).container).toHaveTextContent(
          |                                                                    ^
      178 |                 'Fatal error exporting historical events between 2021-10-29 and 2021-11-04 (inclusive). Check logs for more details.'
      179 |             )
      180 |         })

      at _callee10$ (lib/components/ActivityLog/activityLogLogic.plugin.test.tsx:177:68)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (../../node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)


Test Suites: 1 failed, 85 passed, 86 total
Tests:       2 failed, 3 skipped, 844 passed, 849 total
Snapshots:   14 passed, 14 total
Time:        267.03 s
Ran all test suites.
```

These don't seem to be related to my changes here. Additionally, when running the tests on master I get the same errors, so I don't think they need to be considered for this PR.

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
Thanks for the contribution and the detailed PR!

Looks great! The failing tests are definitely not related and likely some flakiness. I'll trigger the CI and if it all passes we should get this in.

Agree with the nesting in the label - not perfect but definitely fine for now. Probably a nice extension to the `Field` would be to either allow a way to fully override the label rendering or an extra value for rendering to the side but that probably needs a bit more thinking...

**Comment by benjackwhite** [comment]
Looks like this [breaks a cypress test](https://github.com/PostHog/posthog/actions/runs/3239519797/jobs/5312772289) due to the forgot password link being hidden at first when the email isn't entered.

Brings up an interesting point... Maybe we want to keep the "Forgot Password?" link when the password input isn't visible. Or maybe this whole idea is a bit user un-friendly - do we want to require you to type your email already before you can click reset password...?

@raquelmsmith if you can figure out a fix for cypress (probably filling the email input first before trying to click the link then I think we can move forward as is 👍 If you have any issues let me know and I can take a look at fixing it

**Comment by raquelmsmith** [comment]
Hm... it is possibly one extra step for users if they have to enter their email first. I poked around a bit - Amazon shows the Forgot PW link before entering email, Docker waits until after entering email, and Salesforce also waits until after entering email. Most others show both fields initially. But it seems that showing the Forgot PW button after entering email initially is a common pattern. I'd be inclined to keep it that way unless the button is used SUPER commonly, or there are some number of support requests from people saying they can't find it (which I imagine will be unlikely).

I'll get the cypress test updated at some point today 👍

**Comment by raquelmsmith** [comment]
@benjackwhite I updated the failing test and ran it locally to see that it passed. Should be good now but lmk if there is anything else that needs attention 👍 

image

**Comment by raquelmsmith** [comment]
@benjackwhite looks like it turned off auto-merge after I pushed code since I'm not in the org. Can you re-trigger workflows?

**Comment by raquelmsmith** [comment]
Superseded by #12995

**Pull request closed without merging**
