### PR TITLE
feat(surveys): Show only custom events in Event Select dropdown.

### PR DESCRIPTION
**Pull request by Phanatic**
## Problem

The existing Event Select implementation shows all events, both client-sent and autocaptured by the Posthog platform, when selecting an event to activate a Survey popup. Instead, we would like to only show custom events sent by the client in this list and show the user a tooltip about how the events are observed and surveys are activated. 

image

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

1. Manually in local development.

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
Nice, this works for now! :)

**Comment by marandaneto** [comment]
> we would like to only show custom events sent by the client in this list

@neilkakkar or @Phanatic do you actually remember the reason to filter out auto-capture events in this list?

I would appreciate it if you have any context since we have customers trying to target auto capture events, but it's gated by this filter.
What I can think of is 'the list is huge and I don't find my own events', but that we could solve differently as well.

**Comment by neilkakkar** [comment]
Heya @marandaneto - I think the PR is for filtering out actions, which is what I assume customers want to target too. We could just add the `$autocapture` event here, but the main problem is action matching doesn't yet work for survey event triggers, because we need to move this entire logic to the frontend, and I'm not sure if we got that far.

This was an intermediate state where when we don't have action matching, don't show these actions to users because they wouldn't work anyway 🤷‍♂️. The matching here is a bit more complicated than the regular filters we have, specifically the selector matching.

**Comment by marandaneto** [comment]
> Heya @marandaneto - I think the PR is for filtering out actions, which is what I assume customers want to target too. We could just add the `$autocapture` event here, but the main problem is action matching doesn't yet work for survey event triggers, because we need to move this entire logic to the frontend, and I'm not sure if we got that far.
> 
> This was an intermediate state where when we don't have action matching, don't show these actions to users because they wouldn't work anyway 🤷‍♂️. The matching here is a bit more complicated than the regular filters we have, specifically the selector matching.

makes a lot of sense, then we could just find a way to filter out actions but still show all events (autocapture, exception, custom events, etc).

> I think the PR is for filtering out actions, which is what I assume customers want to target too

most likely a few would like that, but in this specific case, it is more about a few other events, eg, "App updated", "Exception", and a few others that would be useful for targeting surveys.

Thanks

**Comment by neilkakkar** [comment]
Nice yeah 👍

**Pull request merged**
