### PR TITLE
feat(settings): staff users

### PR DESCRIPTION
**Pull request by paolodamico**
## Problem
As we introduced more settings that can be managed through the PostHog UI by staff users, we're presented with the problem of managing staff users.

## Changes
- Allows viewing, adding & removing staff users (_follows UI conventions on share dashboard modal & invite teammates_).
    
    
- Properly handles removing yourself as a staff user.
    

## How did you test this code?
- Add & remove other staff users.
- Remove yourself and see the staff users and instance settings page disappear.

### CODE REVIEW

**Comment by paolodamico** [comment]
@liyiy tagging you here for a review as you're taking over the settings feature.

**Comment by liyiy** [comment]
This is looking super solid and will be a nice value add  👍 Code wise it LGTM, just want to clarify some UX details 

Some questions I have:

How is a staff user different from the other membership types? Are admins = staff users? Can regular members also be staff users? What is the distinction between roles here? (if this has been discussed in a PR plz feel free to direct me to it, it's just not very clear as a user here why admins and staffs are split up)

It also looks like we're managing team statuses in two different parts of the settings now? Should we be consolidating this into one location? 

Screen Shot 2022-03-11 at 10 48 31 AM

**Review by clarkus — CHANGES_REQUESTED** [review]
Echoing @liyiy's questions. It's not sure how the roles are various levels overlap. A single user could be a staff user of an instance, an owner of an organization and an admin or other role of a project. It does seems like we need some centralized place that at least puts all this into context. The problem I'd want us to avoid if possible is managing user roles at 3 distinct locations. Is there any documentation or a problem statement for this work?

Recommend checking out the [building blocks ](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/?node-id=0%3A1)area of figma. It has a whole series of table patterns with common icons and such. Might also be worth getting a review from @Twixes as he refactored the tables a good bit lately. 

Specific items to address:
- The inline destructive action icon is typically a trashcan. This is subtle, but it would make this consistent with other recently updated tables. 
- The dialogue component should use a primary action. Even if it's destructive, we should promote one action over the other to give the user a starting point. This component is blocking the screen till a decision is made, so anything we can do to give a prominent yes / no  type feeling to those actions is good. This dialogue is using four palette colors and none them really match our other buttons styles. We should try for more consistency there. 
- We have a pretty full featured user management flow in project settings. Any reason you didn't reuse that here? The placement of adding controls overlaps with where we usually place controls for finding stuff. It might be a better experience and compete less with the rest of the page if there was some consistency between those flows. 

Screen Shot 2022-03-11 at 8 18 20 AM

Does removing a staff user at this level affect their ability to participate in the org or projects? Does removing a member from an org also remove them from a staff user role? How do these interact? We would likely want to clarify the warning messaging to ensure users know exactly how far-reaching the change is.

**Comment by paolodamico** [comment]
Clarifying scope here first (and will update copy in the app too). Staff users are instance-based (see https://posthog.com/docs/self-host/configure/instance-settings#staff-users), which is completely independent of any org/project permissions (you can be or not be a staff user regardless of any permission level on org/project). It's only applicable for self-hosted and we would expect only a handful of users to be staff users in each instance.
@clarkus the reason this is not on the project or org page is because this is instance-level settings, that's why I added it on the instance settings page.

- I'll update the remove icon to the trash one (FYI the org invites page still uses that cross icon)
- For the dialog.
   - I do think it's worth having a different color for the destructive action to emphasize the impact of the change, thoughts?
   - I'll remove the warning icon and color (we use it in invites too).
 - Re the add modal. I did that originally but it felt more cumbersome (https://github.com/PostHog/posthog/pull/8987/commits/9d529be25a03993d19e036a8bf568f9849ea3005), because the flow is different. You don't need to set another attribute, so felt more intuitive to have it just in there.

**Comment by paolodamico** [comment]
We seem to have so many remove/delete icon uses, which one should we use? If it's the trash icon can you provide the svg or Figma link? We only seem to have an Ant version in the codebase today.

Screen Shot 2022-03-11 at 10 44 04
Screen Shot 2022-03-11 at 10 43 56
Screen Shot 2022-03-11 at 10 42 49
Screen Shot 2022-03-11 at 10 42 28

**Comment by liyiy** [comment]
I removed myself as a staff user and I was the only person on the team, how does a user recover from that?

**Comment by paolodamico** [comment]
Updated copy to clarify scope of staff users and updated dialog based on @clarkus's feedback (though I still think it should show the red color to convey the destructive nature of the operation), only thing outstanding is confirm the remove button. Thanks @liyiy & @clarkus for the quick review.

**Comment by clarkus** [comment]
The settings page UI hasn't been updated recently. There is a set of work at https://github.com/PostHog/posthog/issues/4268 that was intended to update all this but it wasn't scheduled. The trash can icons used for destructive actions are mostly in other table views - the ones I linked to in figma - and query builders. 

Here's the delete SVG - it should already be in the iconset. 

delete_black_24dp (2)

> For the dialog.
> I do think it's worth having a different color for the destructive action to emphasize the impact of the change, thoughts?
> I'll remove the warning icon and color (we use it in invites too).

Primary actions are generally higher contrast. We don't have a ton of instance of a primary destructive action, but the pattern is much like our primary blue actions but with the destructive color palette. A quick illustration:

Screen Shot 2022-03-11 at 9 08 08 AM

Notably this pattern requires that you use some destructive verb and then name the thing being destroyed. It's much more clear to say "remove user" than "remove" - it communicates directly the scope of the action and really gives a user confidence in that action. 

> Re the add modal. I did that originally but it felt more cumbersome (https://github.com/PostHog/posthog/commit/9d529be25a03993d19e036a8bf568f9849ea3005), because the flow is different. You don't need to set another attribute, so felt more intuitive to have it just in there.

Just calling out that we're doing the same thing via two different patterns in multiple locations. It works, but I think it's going to be confusing long term and need some updates to ensure it aligns with other similar views. Not a blocker for now, but I do think it could align to the other workflows. Your call.

**Comment by paolodamico** [comment]
@liyiy you'd have to connect to the Django shell and re-add you. This is expected, as this is for advanced users. We can reconsider now allowing users to remove themselves to avoid this in the future.

**Comment by clarkus** [comment]
If there is only one staff users, should we disallow removals? This would align with the way it works for projects and orgs.

**Comment by paolodamico** [comment]
Great @clarkus, all the context I was missing, thanks, will push the final update and we can get this in.

**Comment by paolodamico** [comment]
Re @clarkus,

> If there is only one staff users, should we disallow removals? This would align with the way it works for projects and orgs.

That makes a lot of sense, will do that too.

**Review by liyiy — APPROVED** [review]
Cool, it LGTM then 😄 This is a good first iteration of the feature! 

I will defer to @clarkus for the more granular UI UX behaviors

**Comment by paolodamico** [comment]
Alright addressed all final feedback @clarkus,

**Pull request merged**
