### PR TITLE
feat(experiments): Support avg count per user trend metrics

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

Avg count per user experiments don't work well today:

1. The results are broken, because it assumes the counts are the averages.
2. On the UI, we show a cumulative graph, which makes no sense for avg count per user metrics.
3. same for secondary metrics.

This PR fixes main trend metrics, secondary metrics to come in a follow up.

Now, we:

1. Use daily active users on the given goal to calculate exposure.
2. Use total count on the given goal to determine significance with arrival rates
3. Show the avg count per user in the graph.

This can be a bit more surprising for some users, who, say, expected a t-test of means instead. Will document this 🤷 .

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Storybook + unit tests

### CODE REVIEW

**Comment by liyiy** [comment]
Nice! Another great addition UX wise for later could be to add the secondary metrics graphs themselves onto the page (though I forget if there was a reason we chose not to do that other than didn't have bandwidth) 

And the secondary metrics graphs can be hidden and opened in a modal for example so they don't take up too much screen

**Comment by neilkakkar** [comment]
Reminder for Monday: this is still in draft, can't go in yet because of the problematic snapshot - the trend is missing AGAIN.

**Comment by neilkakkar** [comment]
That should do it - the right css classes weren't loading earlier, causing that wonky snapshot

**Comment by neilkakkar** [comment]
Will investigate the snapshot later - have confirmed it's working fine in storybook now + in local dev

**Pull request merged**
