### PR TITLE
fix(performance): Make preflight logic as cheap as possible

### PR DESCRIPTION
**Pull request by macobo**
Every single web request we put preflight data in the html body for the sake of new deployments preflight page. 

This generates substantial amount of queries against postgres and clickhouse _even if the instance is already set up_. 

## Changes

Limit the amount of queries made on cloud.

We _could_ refactor how preflight works completely and only load this data when needed, but a lot of these toggles requiring database queries are used elsewhere from settings to feature flags to input fields on the frontend.

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
This does change the meaning of "preflight" for cloud since we've been using it as a sort of health check... but I think shifting to "we guarantee these services are available on cloud" is fine ☘️

**Comment by macobo** [comment]
> we've been using it as a sort of health check...

I'm not aware that we have been - can you clarify? AFAIK we use instance status everywhere else - preflight is literally only really used 'first deploy' and for ad-hoc vars through the app.

**Comment by pauldambra** [comment]
> and for ad-hoc vars through the app.

Yep, I think that's what I mean.

E.g. We show file upload if object storage is true in preflight. 

So, we're using the preflight response to probe for availability of services _after_ first deploy. 

I think this change is good because the `isCloud` short circuit in preflight makes it more of a "use this on first deploy" over "use this to check if things are available" when on cloud they should always be available.

Arguably, we should have an explicit "is service X available" logic to separate the "preflight" usage and the "check if services are available generally" usage. But I don't think we need this _now_

**Comment by macobo** [comment]
> Arguably, we should have an explicit "is service X available" logic to separate the "preflight" usage

Yeah - the PR itself calls out that the fact everything relies on preflightlogic is stupid and the 'full' fix would be to refactor all of that.

**Pull request merged**
