### PR TITLE
feat(insights): reoganize chart filter options

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

I was having a hard time understanding the different chart options, especially how the "Time" and "Value" Chart are different.

## Changes

- Re-organizing the chart filter options into "Time Series" and "Value" categories and using the chart type as name.
- Replacing the existing Antd-Icons with Material icons and adding a custom icon for cumulative.
- Removing leftover code from trends beta.

Group_1

## Discussion

> ## Changes
> 
> - I'm proposing to re-organize the chart filter options into "Time" and "Value" as primary category and then simply using the type as name (see screenshot).
> - I've changed the icon for the "Bold Number" chart into something I found more fitting. It  would be great to have a horizontal bar chart icon for the "Value" Chart as well.
> 
> *Before*
> before
> 
> *After*
> after1
> after2
> after3
> 
> ## Request for comments
> 
> - Please let me know if I'm misunderstanding/missing something about the charts that doesn't make this categorization work.
> - Also let me know what you think of this? Are the categories more/less clear for you? Option 1/2/3?
> - Probably would be great to get some real user feedback as well, if we want to continue with this.

### CODE REVIEW

**Comment by Twixes** [comment]
This was bugging me too! I think option 1: time vs. value is the most relevant (and material in terms of insights results, i.e. the resulting numbers should be the same across all time modes, and the same across all value modes).

**Comment by pauldambra** [comment]
Yep, I like Option 1... although "bar" in both sections is a bit confusing. Do they need different names or icons?

**Comment by mariusandra** [comment]
A rule I have is: if I find it confusing, somebody else somewhere does so as well. 

In this case we've probably just gotten used to it. Option 1 is the cleanest and gets my vote.

Some considerations:

1. For the icon, what about just a small bold centered "123"?
2. Longer term, I think "cumulative" should just be a checkbox (together with "[percentages](https://github.com/PostHog/product-internal/issues/68)") on the line and bar chart views, and be removed from this list. That icon should be repurposed for area charts :).
3. What about using "Time series" as the label (vs just "Time")?

**Review by mariusandra — APPROVED** [review]
LGTM

**Pull request merged**
