### PR TITLE
Add names to celery nodes (#7054 pt. 2)

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

While working on #7054 I stumbled upon the fact that we don't name our celery nodes. We've always shipped with one node, but with the chart people can now scale up to 20 very easily.

Not only is it best practice to name them, I also need this in order to keep track of nodes crashing when running special migrations.

@mariusandra tagged because you worked on these scripts last apparently.

## How did you test this code?

Ran the scripts locally

### CODE REVIEW

**Review by guidoiaquinti — APPROVED** [review]
LGTM but we are implicitly adding a dependency on the `openssl` binary being present (is this always true?)

If we know we run in `bash` we could simply use `$RANDOM`, otherwise we can be more creative

**Comment by yakkomajuri** [comment]
that's a good point. I used `openssl` because I remember us using it elsewhere, although I can't find it now.

Should be reasonably ubiquitous but worth considering options here

**Comment by yakkomajuri** [comment]
How's this now? @guidoiaquinti 

We're running Celery so Python must exist

**Comment by yakkomajuri** [comment]
Scratch that, read the docs and they have a way to name nodes based on the host. Given multiple of these should always run in separate hosts, no need for all the random id generation

**Pull request merged**
