### PR TITLE
feat: adding capture events for toggling access control button

### PR DESCRIPTION
**Pull request by surbhi-posthog**
## Problem

We want to capture logs when the user toggles on/off access control feature under teams.

Remaining features include:

- [ ]  SSO enforcement which is turned on after verifying a domain.
- [X]  Project permissions - so if someone toggles project private/public
- [X]  Ingestion taxonomy - if someone marks events as verified
- [ ]  White label branding - surveys and sharing dashboards

## Changes

Changes only add logs in the backend, no frontend changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud: Yes

## How did you test this code?

Locally verified that the activity monitor showed the events and add tests
image

### CODE REVIEW

**Comment by surbhi-posthog** [comment]
Adding a separate function to test toggle action

**Comment by surbhi-posthog** [comment]
The tests I wrote for this event keeps failing due to mismatch event name. I can keep working on this, but Id like to merge the capture at least so we can start collecting logs on this action

**Review by zlwaterfield — CHANGES_REQUESTED** [review]
Can you remove the cache that's being added in these new files?

**Comment by zlwaterfield** [comment]
> The tests I wrote for this event keeps failing due to mismatch event name

Hmm, not sure what you mean. We should be able to test this fairly easily. Do you want to add the test back and I can help you debug it?

**Comment by surbhi-posthog** [comment]
I've added the tests back and verified that they pass locally. Previously the tests were failing, so I want to wait for these to complete before moving forward.

**Comment by surbhi-posthog** [comment]
creating a new branch since this got ugly: https://github.com/PostHog/posthog/pull/27031

**Pull request closed without merging**
