### PR TITLE
metrics - add Prometheus endpoint

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Changes
This PR adds the `django-prometheus` library and adds a new route to our app to expose them at `/_metrics`. As you can see below, the default lib config already includes few nice metrics regarding Python GC and the Django framework. 
 
In future PRs we'll start adding custom metrics.  

## How did you test this code?
```
➜  posthog git:(prometheus_client) ✗ curl -s http://127.0.0.1:8000/_metrics | head -n 50
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 41203.0
python_gc_objects_collected_total{generation="1"} 6569.0
python_gc_objects_collected_total{generation="2"} 1030.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 370.0
python_gc_collections_total{generation="1"} 33.0
python_gc_collections_total{generation="2"} 3.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="9",version="3.8.9"} 1.0
# HELP django_model_inserts_total Number of insert operations by model.
# TYPE django_model_inserts_total counter
# HELP django_model_updates_total Number of update operations by model.
# TYPE django_model_updates_total counter
# HELP django_model_deletes_total Number of delete operations by model.
# TYPE django_model_deletes_total counter
# HELP django_migrations_unapplied_total Count of unapplied migrations by database connection
# TYPE django_migrations_unapplied_total gauge
django_migrations_unapplied_total{connection="default"} 0.0
# HELP django_migrations_applied_total Count of applied migrations by database connection
# TYPE django_migrations_applied_total gauge
django_migrations_applied_total{connection="default"} 233.0
# HELP posthog_capture_endpoint_to_kafka_success_total Total count of captured events successfully sent to Kafka
# TYPE posthog_capture_endpoint_to_kafka_success_total counter
# HELP posthog_capture_endpoint_to_kafka_failures_total Total count of captured events unsuccessfully sent to Kafka
# TYPE posthog_capture_endpoint_to_kafka_failures_total counter
# HELP django_http_requests_before_middlewares_total Total count of requests before middlewares run.
# TYPE django_http_requests_before_middlewares_total counter
django_http_requests_before_middlewares_total 7.0
# HELP django_http_requests_before_middlewares_created Total count of requests before middlewares run.
# TYPE django_http_requests_before_middlewares_created gauge
django_http_requests_before_middlewares_created 1.6354256230487292e+09
# HELP django_http_responses_before_middlewares_total Total count of responses before middlewares run.
# TYPE django_http_responses_before_middlewares_total counter
django_http_responses_before_middlewares_total 6.0
# HELP django_http_responses_before_middlewares_created Total count of responses before middlewares run.
# TYPE django_http_responses_before_middlewares_created gauge
django_http_responses_before_middlewares_created 1.6354256230487418e+09
# HELP django_http_requests_latency_including_middlewares_seconds Histogram of requests processing time (including middleware processing time).
# TYPE django_http_requests_latency_including_middlewares_seconds histogram
django_http_requests_latency_including_middlewares_seconds_bucket{le="0.005"} 1.0
django_http_requests_latency_including_middlewares_seconds_bucket{le="0.01"} 5.0
```

### CODE REVIEW

**Comment by guidoiaquinti** [comment]
Heroku deploy is failing with:

```
         File "/tmp/build_64326edd/posthog/settings.py", line 446, in <module>
           raise ImproperlyConfigured(
       django.core.exceptions.ImproperlyConfigured: The environment vars "DATABASE_URL" or "POSTHOG_DB_NAME" are absolutely required to run this software
 !     Error while running '$ python manage.py collectstatic --noinput'.
```
Not sure how is this related but I'm taking a look

**Comment by hazzadous** [comment]
> Heroku deploy is failing with:
> 
> ```
>          File "/tmp/build_64326edd/posthog/settings.py", line 446, in <module>
>            raise ImproperlyConfigured(
>        django.core.exceptions.ImproperlyConfigured: The environment vars "DATABASE_URL" or "POSTHOG_DB_NAME" are absolutely required to run this software
>  !     Error while running '$ python manage.py collectstatic --noinput'.
> ```
> 
> Not sure how is this related but I'm taking a look

Is that the per PR heroku review app? I don't think anyone is using these fyi, there was some [discussion on slack](https://posthog.slack.com/archives/C0113360FFV/p1635333946060800)

**Comment by guidoiaquinti** [comment]
> > Heroku deploy is failing with:
> > ```
> >          File "/tmp/build_64326edd/posthog/settings.py", line 446, in <module>
> >            raise ImproperlyConfigured(
> >        django.core.exceptions.ImproperlyConfigured: The environment vars "DATABASE_URL" or "POSTHOG_DB_NAME" are absolutely required to run this software
> >  !     Error while running '$ python manage.py collectstatic --noinput'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure how is this related but I'm taking a look
> 
> Is that the per PR heroku review app? I don't think anyone is using these fyi, there was some [discussion on slack](https://posthog.slack.com/archives/C0113360FFV/p1635333946060800)

Actually I think it also breaks the container build, something is wrong and I can't repro locally

**Review by hazzadous — COMMENTED** [review]
I think this looks alright. One potential issue is do we need to restrict access to this endpoint at all? Not sure what the answer to that is.

Are we using prometheus for anything at the moment? What do you have planned?

I can't see why it would cause the build to fail, perhaps worth converting to draft for now?  (selfish, I just want it off of my to be reviewed list)

**Comment by guidoiaquinti** [comment]
> I think this looks alright. One potential issue is do we need to restrict access to this endpoint at all? Not sure what the answer to that is.

That's a good call, I think it's up to us but we should probably do that.  

> Are we using prometheus for anything at the moment? What do you have planned?

Not at the moment. My plan is to improve our overall _metric story_ to be able to give to our user (and ourself as well) more answers about product. Quoting an instrumentation best practice: 

_The short answer is to instrument everything. Every library, subsystem and service should have at least a few metrics to give you a rough idea of how it is performing. Instrumentation should be an integral part of your code. Instantiate the metric classes in the same file you use them. This makes going from alert to console to code easy when you are chasing an error._

> I can't see why it would cause the build to fail, perhaps worth converting to draft for now? (selfish, I just want it off of my to be reviewed list)

I've moved it back to draft 🙏 . Apologise for setting this as _ready for review_ but I didn't hit the issue locally.

**Comment by hazzadous** [comment]
> I've moved it back to draft 🙏 . Apologise for setting this as _ready for review_ but I didn't hit the issue locally.

Actually yeah ignore me, I can just submit a review any time this happens, no need for you to do anything here.

**Comment by guidoiaquinti** [comment]
Let's close this as the bot is driving me crazy. I'll re-evaluate this in the future.

**Pull request closed without merging**
