### PR TITLE
Update app favicon

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Updates the app's favicon to match new @lottiecoxon's design. In addition, it adds support for additional browsers and OSs (particularly mobile). Icons generated with aid of https://realfavicongenerator.net/

**Light mode**

**Dark mode**

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by corywatilo** [comment]
With how much detail is in the logo, it unfortunately doesn't really scale down to a 16x16 icon that well.

One thing we could do is "clip" the back portion of the hedgehog so we can zoom in a little more on the front half.

Preview of some options below, but be sure to view **[this Figma prototype](https://www.figma.com/proto/MRmFaOSXV1zYTGnOODGyCc/Social-Media?node-id=227%3A8650&viewport=546%2C474%2C1&scaling=min-zoom&page-id=227%3A8462)** to view it at real size.

(My personal preferences would be `C` and `F`.)

Also note that we can do a light and dark icon using the `prefers-color-scheme` tag. **[more info](https://catalin.red/svg-favicon-light-dark-theme/)**

image

**Comment by corywatilo** [comment]
Running with `A` for now. All exported icons in [this Dropbox folder](https://www.dropbox.com/sh/7hwq8vhnnv0t8p1/AACkvSn5xV6t-dPUMnpVuPA0a?dl=0).

**Comment by paolodamico** [comment]
Thanks for the review and the alternate options @corywatilo! Very cool! Alright, so I've updated the favicon, and it's ready for one final look before merging.





For context, as mentioned on Slack, we cannot use different versions for dark and light mode because that's only supported with svg icons and our gradient gets messed up on svgs.

**Comment by corywatilo** [comment]
Close enough for jazz!

**Comment by Twixes** [comment]
Post mortem, but IMO it's kind of awkward now… The hedgehog is cut off, very small, and it's pretty odd that the spikes are flat yellow when nothing else is (especially since there's also a ring that's a pink-orange gradient). I don't want to be a nuisance if everyone else likes A most, but how about swapping for C? Best PostHog representation IMO

**Comment by corywatilo** [comment]
I don't disagree the level of detail in a 16x16 frame is quite high. It would be worth figuring out a better representation of PostHog that fits into a very tiny space. (It doesn't have to be the exact logo we use at larger sizes.)

**Comment by Twixes** [comment]
I think the monochrome version of the logo lends itself very well to this purpose.

**Comment by paolodamico** [comment]
Personally I really like having the coloured outline. It brings attention to the PostHog tab and you identify it quickly, but open to a different approach

**Comment by corywatilo** [comment]
I added some alternate favicons. I left `C` in here for comparison, since it's the most simple fallback option. 

A benefit to these is we don't have to worry about doing a light/dark version, which is tricky.

image

**Comment by mariusandra** [comment]
C and H are the best options IMO. I don't think dark mode is *that* tricky to get right, so personally I'd just go with C.

However, one more point/request. In a few past projects I've configured the favicon to be different depending if you're looking at the production site or your local dev environment. This substantially prevents second guessing and mistaking the live tab for a local test tab and messing up data. So I also vote "I" for the dev mode tabs simply because it's most colorful.

(Yes, we do have the [tricolore](https://github.com/PostHog/posthog/pull/2269) at the bottom of a dev session, which helps a lot, but the icon would help even more.)

**Comment by paolodamico** [comment]
So personally what I like about the current version is that it's very easy to locate PostHog tabs among your browser open tabs, it just stands out. However, I see your point about the hedgehog not being very distinguishable, in which case I would go with H or G (even though the hedgehog is still hard to identify at a glance). Though I'm a bit conflicted as just the hedgehog with just the gradient feels a bit off-brand....

Above being said, I would go with H, but happy to go in any direction.

**Comment by corywatilo** [comment]
@Twixes Should you so desire to implement...

(1x and 2x here)
favicon@2x
favicon

**Pull request merged**
