### PR TITLE
chore: remove no-migrations from ./bin/tests

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

see https://posthog.slack.com/archives/C0374DA782U/p1676031826665739

## Changes

removes -no-migrations since it only slows down the first run of the tests

## How did you test this code?

it is self testing

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
approved under duress 😂

**Comment by pauldambra** [comment]
Why under duress @neilkakkar? Should we do something else? 

I was thinking `./bin/tests` should be the swiss-army knife approach that always works

**Review by hazzadous — APPROVED** [review]

**Comment by neilkakkar** [comment]
(don't expect us to spend time on this) - agree this should always work, my qualm is can we adjust migration 300 such that this doesn't become a hard requirement to run tests, as it's an annoying wait every time you want to run tests. Specially, when say, you have 3 tests in 3 different files and you want to run them one by one, so it's one run per test, total one minute.

**Comment by hazzadous** [comment]
> as it's an annoying wait every time you want to run tests.

Is this still an issue on subsequent runs?

**Comment by hazzadous** [comment]
And does [this](https://github.com/PostHog/posthog/pull/13530) change help with speed at all?

**Comment by neilkakkar** [comment]
.... As it turns out, it was my test that was hanging, not this. All duress is gone now 😂 

homer

**Pull request merged**
