### PR TITLE
feat(feature-flag): Feature flag usage dashboard

### PR DESCRIPTION
**Pull request by EDsCODE**
## Problem

- usage tab is minimal right now

## Changes
- auto create a dashboard and associate it with the feature flag to be shown in usage tab

Screen Shot 2023-02-23 at 10 13 35 AM

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by lharries** [comment]
This is great. For the positioning of the dashboard, I wonder if it should be on the Overview page after the other section too? Would increase visibility

I'm pretty far along with [Dashboard templates](https://github.com/PostHog/posthog/pull/14322) - will be merged in next week with the ability for our team to easily create templates to be used globally. Afterwards we'll do a separate PR for others making their own templates

I'd suggest for the charts at some point we move to dashboard templates (although feel free to merge this in and move to templates after). That way we can give a few best-practice options. But they can also then create their own templates for their use case

**Comment by EDsCODE** [comment]
I sort of want to start splitting out the diagnostics and analysis part of flags. I think the overview page is about to get really cluttered if we keep pushing everything there. The usage tab right now has the event log too. Are you suggesting the charts and event log should all live on the overview tab?

**Comment by lharries** [comment]
I'd probably do something like:

Overview page = Short summary of current status of the flag rollout and whos seeing it. Below that the dashboard. In a similar way to on the home page it has the three blocks and then the dashboard below
Usage (maybe a better name e.g. Events) = Events log

I wouldn't put the events log table on the home page.

But you are closer to this so will be able to iterate on the UI better than me :)

**Comment by EDsCODE** [comment]
Ah, another note to add that might clarify the differences in thinking: I think there will be several sorts of dashboards/insights that are relevant for a feature flag so it won't just be a single dashboard that holds everything relevant to a flag. 

So a few iterations later there should be a usage tab (like what's shown right now) and then an analysis tab too. They can both be powered mostly by the dashboard templates but focused on different information. Usage is purely just feature flag usage. Analysis is how feature flag is impacting important metrics or points of interest or recordings. That's primarily why I'm not trying to put everything on overview as it will get bloated very quickly. I think once these pages are [validated](https://posthog.slack.com/archives/C034XD440RK/p1677178033217149) to be useful, we can reorient the overview page to highlight the most important parts of "usage" "rollout conditions" "analytics"

**Pull request closed without merging**
