### PR TITLE
fix: handle the case of invalid json gracefully

### LINKED ISSUE #1576: Invalid JSON causes internal server error
## Bug description
I am trying to use the RESTful API to be able to built on the `posthog-js-lite`-package by adding the `decide`-endpoint only when I tried to call this endpoint in Paw I kept getting 500 Internal Server Error. After a few hours of staring at what could be the problem I noticed I was sending invalid JSON as Base64 string.

Encoded: `eyJ0b2tlbiI6IFRva2VuSGVyZSwgImRpc3RpbmN0X2lkIjogMTc0NTYyNWM2MDUxOTgtMGIwZWZkY2Y2ZjJjOGEtMWU0ZDMyMWEtMWVhMDAwLTE3NDU2MjVjNjA2ZGNkfQ==`
Decoded: `{"token": TokenHere, "distinct_id": 1745625c605198-0b0efdcf6f2c8a-1e4d321a-1ea000-1745625c606dcd}`

Note that I forgot to properly quote the string values of the properties `token` and `distinct_id` 

## Expected behavior
The API shouldn't fail with status code 500 but instead returning something like 400 or 422 to indicate something is wrong with my request instead of throwing confusing 500.

## How to reproduce

1. Run the `curl` command:
```
curl -X "POST" "https://app.posthog.com/decide/" \
     -H 'Origin: https://localhost:5000' \
     -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44' \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     --data-urlencode "data=eyJ0b2tlbiI6IGFwaV9rZXksICJkaXN0aW5jdF9pZCI6IDE3NDU2MjVjNjA1MTk4LTBiMGVmZGNmNmYyYzhhLTFlNGQzMjFhLTFlYTAwMC0xNzQ1NjI1YzYwNmRjZH0="
```
2.  Notice 500 is returned

## Environment

- PostHog cloud or self-managed?: cloud
- PostHog version/commit: latest cloud version

### PR DESCRIPTION
**Pull request by weyert**
This changes the behaviour how invalid json is handled in the `/decide`-endpoint instead of failing hard by throwing a 500 internal server error it instead will throw a 400 Bad Request error instead to make the Developer Experience better

fixes #1576

## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by weyert** [comment]
Originally I want to use a custom exception handler and return 400 when JSONError exception is thrown but I am seem to unable to get my exception handler to get called. The main reason for this approach to change the behaviour for all API routes.

**Comment by yakkomajuri** [comment]
Thanks for this @weyert! I'll be giving it a look when I get the chance early next week! I'll look into the tests and make sure the changes fit nicely with #1553

**Comment by yakkomajuri** [comment]
Ok so this right now works but is not the way I want to handle it because it adds redundancy through calling `_load_data` twice. The approach @weyert is following here is drawn from our /capture endpoint, but I've now realized that the implementation /capture uses doesn't actually work to detect all malformed JSON. I'm working on it.

**Comment by yakkomajuri** [comment]
Ha, I've been hopping around timezones so my GitHub posts are happening "in the future". 

"Yakko self-requested a review in 1h"

**Comment by yakkomajuri** [comment]
Ok so @weyert had mentioned that we should see if there are any other endpoints that could benefit from this approach. I think /capture potentially could. However, I'll merge this as it is somewhat "blocking" me on #1553 and then see with another PR the other endpoints this could be applied to.

Thanks for this @weyert! I definitely agree we should be throwing as few 500s as possible.

**Review by yakkomajuri — APPROVED** [review]

**Comment by weyert** [comment]
Thank you @yakkomajuri for looking and accepting my pull request  :D

**Pull request merged**
