### PR TITLE
fix: data warehousetable N+1 take 3

### PR DESCRIPTION
**Pull request by pauldambra**
we're still getting N+1 warnings about datawarehouse table

let's make it the default to select_related all the things

### CODE REVIEW

**Comment by pauldambra** [comment]
this really won't go away 🤣 
opened this to see if the tests all pass

**Comment by EDsCODE** [comment]
Link to the error? Was it the same exactly call spot or a different one now

**Comment by pauldambra** [comment]
https://posthog.sentry.io/issues/5183540615/events/latest/?project=1899813&referrer=latest-event

**Comment by pauldambra** [comment]
Screenshot 2024-07-12 at 19 04 16

i think this is on the reverse relation from external schema to table

felt silly to keep chasing it around the code base so do it on the object manager instead

**Review by EDsCODE — APPROVED** [review]

**Pull request merged**
