### PR TITLE
chore: add ttl to performance events table

### PR DESCRIPTION
**Pull request by alexkim205**
## Problem

We're slowly rolling out the new session recordings network feature to beta users, and don't want the new `performance_events` to explode.

## Changes

- [x] Adding TTL of 3 weeks to performance events table
- [x] Add editable instance setting called `RECORDINGS_PERFORMANCE_EVENTS_TTL_WEEKS` with default 3

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

- [x] Add update instance setting test
- [x] Locally run migration

```sql
SHOW CREATE TABLE sharded_performance_events
FORMAT Vertical
```

Screenshot 2023-01-25 at 11 25 09 AM

### CODE REVIEW

**Comment by neilkakkar** [comment]
Curious: Does this feature work without having session recordings?

**Comment by alexkim205** [comment]
> Curious: Does this feature work without having session recordings?

Hm, this PR isn't really a feature but rather a safety measure. Network requests won't work if you don't have session recordings turned on, but I believe the table will still be created and we'd want to put a TTL in any case.

**Comment by benjackwhite** [comment]
> Curious: Does this feature work without having session recordings?

It does but as part of the Web Performance thing that is totally Alpha and only enabled for team PostHog atm. Even in that case we would limit the TTL on this table and be using an Aggregating table to keep the long term aggregate metrics.

**Comment by neilkakkar** [comment]
@alexkim205 my bad, the 'this' was very ambiguous, I meant the 'network performance' feature, not just this PR.

Reason I asked was to check if it makes sense for recordings and performance data to diverge (when, say, ttl of one is larger than the other); but since it's standalone, having a separate ttl seems to make sense 👍

**Comment by pauldambra** [comment]
I stole this query from the internet https://metabase.posthog.net/question/603-performance-events-data-sizes

we've got 13 million rows but they compress by 88% so they're only 1GB on disk. Most of the columns for most of the rows should be empty so this makes sense...

Is it worth throwing away data yet?

**Comment by benjackwhite** [comment]
> Is it worth throwing away data yet?

Part of the thinking here is that we are considering defaulting network recording to ON when Recordings are enabled (which will soon be all new projects) so we predict a pretty hefty increase in data. My understanding was that changing a TTL later is perhaps not so simple and as such we were opting for adding one now, at least while this data is only useful for Recordings.

Am I wrong about the TTL think I wonder? Can we just add one later and then all old data will be dropped @fuziontech ?

**Comment by pauldambra** [comment]
In comparison events compressed_size is 5.07 TiB. Events is even more highly compressed than this table

We've got about 20 days of data for one team which is 1GB on disk. Let's be kind and call that 1GB per team per month. Assume that all teams send the same amount of data as us (definitely not true). And we've got a minimum of terabytes of data a month _compressed_

Apologies for popping out of a trash can like Oscar the Grouch and nay-saying. We definitely need a TTL. 

Just makes the work to aggregate more urgent ⏩

**Comment by pauldambra** [comment]
Also makes me wonder if we can fund work on S3 backed archival for ClckHouse (since I'm assuming we don't want to _do_ the work)

**Comment by alexkim205** [comment]
Shoutout to @benjackwhite for helping me with the migration issue. It turned out to be CH migration 37 that was silently failing on creating the sharded_performance_events table because the ttl_period SQL parameter had a reference to `created_at` which the performance events table does not have.

**Review by benjackwhite — APPROVED** [review]

**Comment by mariusandra** [comment]
Somehow ever since this PR a lot of new PRs and commits in master fail with
```
FAILED ee/api/test/test_performance_events.py::TestLicensedPerformanceEvents::test_performance_lists_events_by_session_id
```

**Pull request merged**
