### PR TITLE
Add CH Person Sessions By Day

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

**Quick and dirty** solution to CH person sessions by day. More like setting context for you @macobo here instead of an issue. 

Also `get_person_by_distinct_id` didn't work for me so I had to use `get_persons_by_distinct_ids` because I wasn't about to debug the query right now. 

There's most definitely better ways to do this, but yeah this was a quick fix from someone who hasn't been involved with CH.

## Before 

Screenshot 2020-10-28 at 18 46 30

## After 

Screenshot 2020-10-28 at 18 45 58

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by EDsCODE** [comment]
i'm guessing you didn't do anything to affect `test_alias_twice` test? This is super weird because I haven't seen this test flake in the entire team we've been running ee tests so far

**Comment by yakkomajuri** [comment]
Nope - In fact the linter test failed with everything else passing, then I fixed the formatting and now this failed :D @EDsCODE

**Review by macobo — APPROVED** [review]
It's def hacky, but I think this is fine for now.

**Comment by yakkomajuri** [comment]
Separate test is now failing. Should I just merge @EDsCODE ?

**Comment by EDsCODE** [comment]
yeah i'll make a note of it

**Pull request merged**
