### PR TITLE
chore: add optional pyroscope profiling client

### PR DESCRIPTION
**Pull request by xvello**
## Problem

[pyroscope.io](https://pyroscope.io/)'s continous python profiling seems to be pretty good, especially in a multi-threaded environment like ours. I am using it locally to identify optimizations to the capture endpoint, and it would be great to take a few profiles in a k8s environment.

Like Sentry, the integration is disabled in test mode and if PYROSCOPE_TOKEN is not set. We'll set it via chart values when relevant. It is set to hopefully collect the most relevant info for our gunicorn setup: `gil_only=False` is set to collect all the CPU usage, including the kafka producer threads, not just the one thread holding the GIL.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Tested locally by setting the right envvar and getting profiles in pyroscope.cloud

### CODE REVIEW

**Review by tiina303 — APPROVED** [review]
lgtm

**Comment by xvello** [comment]
The python build is failing on this branch, because pyroscope does not ship a wheel for alpine, and the build from source seems broken. Tracking https://github.com/pyroscope-io/pyroscope/issues/1796 for resolution of this issue.

**Comment by xvello** [comment]
https://github.com/PostHog/posthog/pull/13314 (moving base image alpine->debian) should unblock us here, by enabling use of the precompiled wheel 🤞

**Comment by xvello** [comment]
Closing for now

**Pull request closed without merging**
