### PR TITLE
fix: issue-16716 (Added cache for all filter operators)

### PR DESCRIPTION
**Pull request by Arun-chaitanya**
## Problem
#16716 

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by Arun-chaitanya** [comment]
@thmsobrmlr @neilkakkar  I have trying to add filtersOperatorsCache in propertyFilterLogic but every time I change an operator the state of the filtersOperatorsCache resets, even though I am trying to manage to not let that happen via setFilter in filtersOperatorsCache reducer. Can you help me why it is happening? My hunch here is that a totally new logic is being created whenever the operator is changing. Please let me know your thoughts on this.

**Comment by Arun-chaitanya** [comment]
Got the issue in my code. Will try to complete it as soon as possible.

**Comment by Arun-chaitanya** [comment]
@thmsobrmlr @neilkakkar I have done the changes. Please review.

**Review by thmsobrmlr — CHANGES_REQUESTED** [review]
Thanks for yet another contribution, @Arun-chaitanya! Unfortunately this doesn't seem to work as expected for me:



As you can see only the first option gets restored when changing back to "doesn't equal", instead of restoring all previous options.

**Comment by arunfancraze** [comment]
@thmsobrmlr Got it. Actually I checked in new insights and edit insights page. It was working there. Let me check for this page also.

**Comment by arunfancraze** [comment]
@thmsobrmlr can you guide me on how to reach that webpage for which you have posted the video recording?

**Comment by Arun-chaitanya** [comment]
@thmsobrmlr can you recheck once? I tried to follow the same steps and was able to see the changes I made. Here is the video recording for reference.

https://github.com/PostHog/posthog/assets/44457256/0374ee9f-f2d3-4cd6-9561-12ca6441979e

**Comment by Arun-chaitanya** [comment]
@thmsobrmlr can you please take a look at my screen recording and recheck on your side? I followed the same steps as you did in the screen recording and it is working fine for me. I may have been missing some edge cases according to me, can you suggest if anything is coming to your mind.

**Comment by Arun-chaitanya** [comment]
@Twixes can you also look into it if you have some time. Thanks

**Comment by thmsobrmlr** [comment]
Hmm.. I can see that the same thing seems to work in your case, but still doesn't in my case. Just to check, have you pushed everything you have locally?



My repro is as following:
1. Navigate to dashboard "Website" from the demo data
2. Add a filter "Target (href)" "doesn't equal" "[test1] and [test2]"
3. Close the popover
4. Change the filter from "doesn't equal" to "doesn't contain" - only "test1" is visible now
5. Change the filter back to "doesn't equal" - unfortunately only "[test1]" is visible now

**Comment by Arun-chaitanya** [comment]
Can you give it a final try. @thmsobrmlr . If still not working, please check https://github.com/PostHog/posthog/pull/17143 once. This time 100% sure that I have no local changes left and also I followed the exact same steps mentioned by you and was able to see the desired results.

**Comment by thmsobrmlr** [comment]
@Arun-chaitanya Unfortunately it's still the same. Can't imagine anything else then some code not being pushed though. 

I've noticed something else as well: The cache does not consider for which property you change the operator. So when I 
1. set a value for "Current URL equals x,y" 
2. change "equals" to "contains"
3. change "Current URL" to "Target (href)"
4. change "contains" to "equal"

I get the cached value from step 1.

**Comment by thmsobrmlr** [comment]
https://github.com/PostHog/posthog/pull/17143 seems to work better. I'll check properly after a meeting.

**Pull request closed without merging**
