### PR TITLE
Make dashboard redesign final

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Removing flag `dashboard-redesign` and code that is made redundant by this.

### CODE REVIEW

**Comment by mariusandra** [comment]
Is this flag somewhat related or dependent on `line-graph-v2`? There are still issues with annotations when that's enabled, and the annotations are weird in a different way when that flag's disabled...

**Comment by Twixes** [comment]
It should be independent from `line-graph-v2`.
I see some issues with placement of annotations too – fixing this! Will be a separate PR as it's orthogonal to purging the old code.
As for `line-graph-v2`, I would love for that situation to be cleaned up too, but I don't have a ton of context on the why and what. That's on the flag owner – @alexkim205 I reckon.

**Review by mariusandra — APPROVED** [review]
Code looks good to me 👍... and 🎉 for getting this done! Great job!

The only one thing I'd consider a "ux bug" is that this "by an unknown user" part doesn't add value if looking at e.g. newly created empty dashboards, or other historic data. Happy to leave it for another PT, but can we skip all after "by..." if it's null?

image

**Comment by Twixes** [comment]
Agreed, now hiding the "by unknown user" part (when the user is, well, unknown). Also made use of `last_modified_at` in the list of saved insights instead of the faulty `updated_at`.

**Pull request merged**
