### PR TITLE
feat(experiments): allow multiple preview images

### PR DESCRIPTION
**Pull request by Aashw1n**
## Problem
Related to feature: #25914
While this feature hasn't been voted on, wanted to give this a shot.  Please let me know if there's a certain way you'd like to see this done, or if I can add anything to make this better/mergeable.

There are a couple ways to enable this. What I did here was change the ` "variant_screenshot_media_ids"` type from `Record<string, string>` to `Record<string, Record<string, string>>`.

The `variantKey` would now hold a `mediaTypeKey` (desktop and mobile in this case). 
The ` "variant_screenshot_media_ids"` would look something like this after images are uploaded.

Uploads and other ops such as delete are updated to accommodate.

`  "variant_screenshot_media_ids": {
    "test": {
      "mobile": "019303cf-d43d-0000-ad80-fa0413947644",
      "desktop": "019303cb-ec8a-0000-afc8-7fdc326d02b3"
    },
    "control": {
      "mobile": "019303cf-bc51-0000-844c-ab7e3a73a134",
      "desktop": "019303cf-c627-0000-58d2-8c204b9cae5e"
    },
    "test_group_2": {
      "mobile": "019303d0-0a26-0000-832d-914b0e295998",
      "desktop": "019303cf-df82-0000-ee79-1935a0ab8d8b"
    }
  }`

## Changes

This is one possible change that enables this feature. UI is still pretty jank, but it looks like this.
Other possible change, and a potential issue with this one discussed in the following comment. 

https://github.com/user-attachments/assets/96ea0a49-e44c-4847-8aa6-f33832321900

## Does this work well for both Cloud and self-hosted?

Works well on local dev. 

## How did you test this code?

Tests mentioned in developing locally handbook, as well as manual tests and sanity checks.

### CODE REVIEW

**Comment by Aashw1n** [comment]
Another way to do this would be to just change the  `"variant_screenshot_media_ids"` type from `Record<string, string>` to `Record<string, string[]>` or `Record<string, Array<string>>`. And store the list of imageId's for each variantKey.  Probably add logic to limit the number of images that can be uploaded for each variant. 

The solution I just added would leave older keys in the Record. 
This would not happen with the list, and would be updated. In either case, without some mitigation, user would have to reupload the images, and it would leave the older images suspended in storage.

**Comment by Aashw1n** [comment]
Hi @jurajmajerik 

Thanks for your feedback! I've made the changes as you pointed out. UI is similar to what to mentioned, and up to 5 images can be uploaded before the upload option disappears, and reappears when an image is deleted. 5 images seemed like just enough before the UI explodes. 

As I refined this, I chose to standardize the full with of the column, so as more images are added, width for the upload icon and the images are adjusted accordingly. 

All operations are changed accordingly. 

The `"variant_screenshot_media_ids"` would look like this with all possible images populated.

`"variant_screenshot_media_ids": {
    "test": [
      "01931fdc-4021-0000-c33b-cfa883f400cb",
      "01931fe6-68f6-0000-5d0c-d518510a7005",
      "01931fe6-73eb-0000-94c9-f8e1c991f039",
      "01931fe6-84f6-0000-6f27-0de54b8106b8",
      "01931fe6-8f72-0000-887e-ecc13ceca193"
    ],
    "control": [
      "01931fdc-0665-0000-13c2-fb66ffbbcd37",
      "01931fdc-196e-0000-738b-b38fe319910f",
      "01931fe6-223e-0000-c270-726cc77a651d",
      "01931fe6-2cee-0000-fced-e5d01d49cc4b",
      "01931fe6-4dd6-0000-bd14-80a3a3f02dcf"
    ],
  }`


Video and images below would demonstrate the changes.


https://github.com/user-attachments/assets/f4566c67-efb6-48e6-8c15-196eae61aef1



Please let me know if there's anything I can do to improve this, or if there's something specific you'd prefer.

**Comment by Aashw1n** [comment]
Hi @Twixes @jurajmajerik 

Requesting a review on this

**Comment by jurajmajerik** [comment]
Hey @Aashw1n, apologies for the delayed review.

The new design looks great! However I've realized that your implementation is breaking backwards compatibility 😬 This is because the code assumes that `mediaIds` is always an array and directly calls `.map()` on it. To test this, checkout to master, add a single image, then check out back to your branch and try viewing the existing experiment with images.

What we need here is some logic to check whether `mediaIds` is an array or a string and normalize it to an array.

---

The second issue I've noticed is in the unUpload handler. To replicate:
- add a console log to the `onUpload` handler
```
        onUpload: (_, __, id) => {
            console.log('onUpload', id)
```
- upload a single image from the UI
- see that the image is uploaded twice:
```
onUpload 01932ef7-9658-0000-1323-947ab85d0ac2
onUpload 01932ef7-965a-0000-4653-44489c33274c
```

This bug is likely not introduced by your implementation, but it would be great if we could fix it now, otherwise our object store gets cluttered with duplicate images. Can you please look into this one as well? 🙏

**Comment by Aashw1n** [comment]
Hi @jurajmajerik 
Thanks for the review! I'll adjust for backwards compatibility, I'd noticed it as I was working on this as well, but it completely slipped my mind 😅

And nice catch, I'd be happy to get that little upload bug out of the way as well!

**Comment by Aashw1n** [comment]
Hi @jurajmajerik 

Now, in case of a photo already being populated, it'll be initialized as an array in the component, and db will be updated with an array on upload/delete. 

Here's an upload on master 

Screenshot 2024-11-15 at 4 10 30 AM


And here's how it looks when I run my branch:

Screenshot 2024-11-15 at 4 16 08 AM




Here's how the upload log looks after the fix. 


https://github.com/user-attachments/assets/794964a6-6517-4824-a55b-b60c13adaa74



As always, if there's anything else needed on this, please let me know and I'd be happy to make changes accordingly.

**Comment by jurajmajerik** [comment]
Looks amazing, thanks @Aashw1n!

I'll resolve conflicts and merge this. Please send me your email to juraj at companyname, I'll send you little something :)

**Review by jurajmajerik — APPROVED** [review]

**Pull request merged**
