### PR TITLE
Tooltips improvements III

### LINKED ISSUE #4156: Update design of tooltips
EDIT: This issue now encompasses only the UI/implementation for tooltips only. The main chart components are encompassed in #4758.

At @paolodamico's request, I put some thought into making graphs more visually appealing. After some [research](https://docs.google.com/document/d/1pHshHgMQYs14xLd24s5L4z6ouEv1fjnL3qAt4RjMXl8/edit?usp=sharing), I landed on this:

image

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Builds up on #4651 and closes #4156. Implements the improvements based on the latest feedback that wasn't addressed in that PR. Changes look pretty small, but actually took a while to get it right 😔. 

### Changes in this PR
- Tooltip is now positioned a bit to the right of the x-axis points so you can see what you're clicking on. If the tooltip wouldn't fit the window, it's positioned a bit to the left of the point (Point 2).
- Cross hair line now snaps to x-axis points (Point 5).
- Point 6 was actually addressed with #4761. In any case, with the changes we're planning on how we show dashboards this should actually be a moot point.
- Point 1 is now fixed, positioning of bar value chart tooltips is now intuitive.
- **Bonus ⚡**. Fixes the color display on bar value charts when there were more series than colors.

**Before**

**After**

### What's next
- Point 3. This PR still doesn't show this issue, though this isn't an issue with this new tooltips view in particular, it already existing. I'm already working on a refactor to allow selecting overlapping data points in the personal modal.
- Point 4. I'm tabling this for now. The way tooltips are mounted on Charts.js is by absolutely positioning the element on the screen, we therefore need to apply `cursor-events: none` for the tooltip to still be shown when hovering over it. As we're moving to D3 and this might change, not much sense in optimizing right now.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by mariusandra** [comment]
Nice! I made a few updates:

1. I added a small CSS animation for the tooltip position.
2. I patched `chart.js` itself, added the crosshair plugin directly into the source, and (most importantly) added a new `nearestX` mode, which only matches the nearest point on the current X coordinate:



Still kind of TODO, but could be pushed further:

A. The crosshair should animate smoothly as well?
B. It's a bit of a winky-wonky dance here:


We could still do something with those points, but all the rest LGTM!

**Review by mariusandra — APPROVED** [review]

**Review by corywatilo — APPROVED** [review]
Looks good! My only thoughts in the tooltips themselves (which can be addressed later):

1. Numerical count looks a tad large
2. I wonder how it would feel if we kept the numbers lined up on the far right, vs having them at the end of the label now. Might be a little clearer. Possibly a subtle dividing line between rows so it's not hard to scan across.

**Comment by paolodamico** [comment]
Thank you both for the review and @mariusandra for the extra improvements. Will keep this for a next improvement round as I want to see what happens with D3 and get some user feedback too. Also @mariusandra I think we need to create the repository for the custom chart.js package? Hopefully it'll be short-lived?

**Comment by paolodamico** [comment]
@mariusandra there seems to be an issue with the Docker build related to the introduction of the new custom package, do you have some context?

> Module not found: Error: Can't resolve '@posthog/chart.js' in '/code/frontend/src/scenes/insights/LineGraph'

**Comment by mariusandra** [comment]
- This is the custom chartjs repo: https://github.com/PostHog/Chart.js/tree/2.9 -- everything is in the `2.9` branch.
- Very weird re: docker. Could it also be caching? 🤔 
image
- I made another PR to try running the tests without a cache: https://github.com/PostHog/posthog/pull/4782

**Comment by paolodamico** [comment]
Seems like it wasn't a caching issue, build works locally too. Any ideas?

UPDATE: I checked the built package and it looks like there isn't a `Chart.js` file in the `dist/` folder, but there's a `chart.js` file, could it be something related to case-sensitivity in the file system?

**Comment by mariusandra** [comment]
I just discovered the same. I didn't see your comment update as I was reading the thread in gmail... 🙈 

image

That's indeed the problem. The fileystem on a macOS is case-insensitive, but on Linux it's case-sensitive.

ChartJS v3 (`master` branch) [has changed](https://github.com/chartjs/Chart.js/blob/master/rollup.config.js#L37) all the files to be lowercase. I had built this before realising we're on v2 and it's not worth the upgrade. I switched to the `2.9` branch and rebuilt. macOS saw that "chart.js" was already there when writing out "Chart.js"... and saved the new data in it... and boom.

I released a new version. 🤞

**Comment by mariusandra** [comment]
Cypress keeps repeatedly failing on `trends.js` with "Apply specific filter on custom action"

image

... but works well locally:

image

What's worse, it seems like it's running a completely different test in Github.

In github:

Trends -- Apply specific filter on custom action (failed) (attempt 2)

Locally:

image

I don't understand where it even gets that "Continent Code" from... :/

... so merging and assuming it's something to do with gamma rays in the MS Azure datacenter... 🤞

**Comment by paolodamico** [comment]
Thanks for driving this to the finish line @mariusandra! Excited about this, starting progressive release.

**Pull request merged**
