### PR TITLE
feat(hogvm): hogvm bytecode action matching in the plugin server

### PR DESCRIPTION
**Pull request by mariusandra**
Reverts the revert PostHog/posthog#17036

### CODE REVIEW

**Comment by mariusandra** [comment]
Still planned: adding an env that configures which teams this is enabled for.

**Comment by tiina303** [comment]
> Still planned: adding an env that configures which teams this is enabled for.

If you'd like to gradually roll it out you could also do team_id < ENV ; but I guess the alternative is to look up who uses webhooks and list the team_ids

**Comment by Twixes** [comment]
What were the metrics, what needs to be changed?

**Comment by tiina303** [comment]
btw I added some metrics in https://github.com/PostHog/posthog/pull/17056

**Comment by mariusandra** [comment]
Having just seen this PR: https://github.com/PostHog/posthog/pull/17073
... I was reminded that the one problem we have here is the needless deserialization and serialization of `elements_chain: str` to/from `elementsList: Element[]`. 

I think the original logic was that this deserialized version is friendlier for plugin authors to handle. However this seems excessive now. 

HogVM would be really happy to work with just the `elements_chain` string field for its matching, as we're doing the same regexp match ClickHouse would do. However that's not available in the webhooks consumer, as only `elementsList` is sent over as part of `IngestionEvent`.

**Review by Twixes — APPROVED** [review]
Obviously ship it YOLO

**Pull request closed without merging**
