### PR TITLE
Antd layout

### PR DESCRIPTION
**Pull request by EDsCODE**
Had this branch for a while. Got it ready for PR. Works on layout/header components for #531  and will give us more space for #532 

- Sidebar tweaked a little further so it has dropdown menus now
- Sidebar is static on scroll
- When screen is minimized past a threshold, the sidebar will close and a trigger will appear to close/open drawer
- Using antd layout components now will standardize header and sider giving us more space to work with in content

Screen Shot 2020-04-16 at 10 32 50 PM

### CODE REVIEW

**Comment by SanketDG** [comment]
Did a rough QA, this adds a large line-height to all modal content.

image

**Comment by EDsCODE** [comment]
@SanketDG Thanks for the catch! I swapped out the header component with a div and previous styling to preserve the content formatting

**Review by timgl — APPROVED** [review]
LGTM, only small comment would be if you click the `^` on Events, it does actually take you to events immediately even if you actually wanted to go to actions for example.

**Comment by EDsCODE** [comment]
> LGTM, only small comment would be if you click the `^` on Events, it does actually take you to events immediately even if you actually wanted to go to actions for example.

Do you think it should be split up? I deliberately made the click default to events to mimic the original sidebar's functionality (so it doesn't take 2 clicks to get to events). Open to changing the button to not default you to events. Alternatively, we can merge this and make that call if it feels clunky later on

**Comment by timgl** [comment]
Fine to leave as is for now

**Pull request merged**
