### PR TITLE
chore(storybook): Optimize Storybook start time

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Storybook is a great tool, but it takes quite a while to start… warm startup (i.e. one using cache) takes 45 seconds in fact. The longer loading takes, the more I fall out of The Flow™️.

## Changes

This upgrades Storybook to take advantage of Webpack 5 with filesystem caching (instead of Webpack 4) + Storybook 7's on-demand story feature. This takes warm startup time down from 45 to 25 seconds.

I also tried out switching to Storybook's Vite builder – which would have the advantage of getting us close to removing `webpack.config.js` – but it wasn't much faster than the current setup (~40 s) and it didn't like our way of importing static files like `.mp3` or `.lottie`.

## How did you test this code?

Ran Storybook.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
That's turbo!

Why the move from `babel.config.js` to `.babelrc` though? The Storybook docs even [mention](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7) a separate `.babelrc.json` file. I thought the last new correct thing was `babel.config.js`?

**Comment by mariusandra** [comment]
Tests don't seem happy though.

**Comment by Twixes** [comment]
Storybook doesn't like the JS version of Babel config. I went for `.babelrc` without `.json` just for consistency with the plugin server's style – both seem to work the same.

**Comment by Twixes** [comment]
It seems that both Webpack 5 and Vite builders suffer from insane memory usage, causing issues in GitHub Actions. I was very hopeful Storybook could be optimized like production builds were, but it turns out that isn't possible. Maybe Storybook 7 will be better.

**Pull request closed without merging**
