### PR TITLE
fix: switch updating form

### PR DESCRIPTION
**Pull request by Justicea83**
## Problem
https://github.com/PostHog/posthog/issues/18236

## Changes
1. Change the switch `type` to button

## How did you test this code?
In the browser

https://github.com/PostHog/posthog/assets/26106822/ee18fb70-a25f-4e26-b333-ebc3dd36ec56

1. Create an existing survey
2. Edit the existing survey
3. Add user targeting for it, choose a property that has a date type on it
4. Toggle the include time, ensure it doesn't submit the button

### CODE REVIEW

**Comment by Justicea83** [comment]
@Twixes can you review this? Sorry for mentioning your name.
Do we have steps I have to follow for calling on reviewers?

**Comment by Justicea83** [comment]
Not sure what cancelled it, will be glad if you can trigger the re-run for me

Screenshot 2023-11-08 at 00 00 09

**Comment by liyiy** [comment]
This looks good to me! @Twixes do you want to take an extra look before I merge this in?

**Comment by Justicea83** [comment]
Bumping @Twixes

**Comment by Justicea83** [comment]
@liyiy I think you can merge right?

**Comment by Justicea83** [comment]
Thanks @liyiy

**Comment by Justicea83** [comment]
Wanted to ask a question @liyiy , not sure where to ask it.
If some features are hidden behind feature flags and you want to enable them in dev, where should i put the constants.
Example is  `surveys-multiple-questions`.

I already tried creating a `.env` file inside the `posthog/` but it doesn't seem to be picked up.

Can you assist? I know you worked on the surveys feature 😄

**Comment by liyiy** [comment]
@Justicea83 All you would have to do is create that feature flag and enable them in your dev instance! For a faster copy over of all feature flags for development purposes, I would recommend taking a look at https://posthog.com/handbook/engineering/developing-locally#extra-working-with-feature-flags

**Comment by liyiy** [comment]
@Justicea83 You should've also received a gift card to our merch store for your contribution, let me know if you haven't received anything 🤗

**Comment by Justicea83** [comment]
Thanks for the gift, I received it. I also connected on LinkedIn.

**Pull request merged**
