### PR TITLE
Paths pay gate

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Implements a pay gate for all the Paths new functionality (following #6413 & https://github.com/PostHog/company-internal/issues/417). All paid features are hidden for now, and we show a simple and dismissable prompt to upgrade. If you dismiss the prompt, we will not show it again (unless you clear local storage or use app in incognito). **🎨 Storybook component included.**

**Paid features:**
- Connection between funnels <> paths
- Paths with an end point
- Excluding items
- Wildcard groups
- Advanced visualization options (weights)

## How did you test this code?

- Launched the app with and without `advanced_paths` in available features. Made sure that paid features showed up when applicable, and didn't show up when not applicable.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
LGTM. Some misc thoughts:

1. Are we releasing the new paths? If so... can we delete this border around the different events? It looks so ugly :)

image

2. Then also I can't get any results if I select `$pageview`. Something feels weird with the filters, but it could be just me... not sure. Outside the scope here I guess.

3. Can we get this menu back, even if clicking them opens a upsell box. I think this is a great place to upsell:

image

**Comment by neilkakkar** [comment]
> Then also I can't get any results if I select $pageview. Something feels weird with the filters, but it could be just me... not sure. Outside the scope here I guess.

By design. You can only select URLs or custom events. There's no `$pageview` on Paths, just URLs or custom events.

**Comment by mariusandra** [comment]
@neilkakkar This feels really broken by design then:


I see pageviews, yet I can't see a path between them, even if I select pageview events or select a starting URL.

Is this really how it should be?

**Comment by neilkakkar** [comment]
Ah, I misunderstood, I thought you meant you put $pageview in the start point, not in the event type filter. This, definitely feels broken lol.

**Comment by paolodamico** [comment]
The broken experience seems to be unrelated to this PR, but definitely worth fixing @EDsCODE

**Review by neilkakkar — CHANGES_REQUESTED** [review]
Blocking merge, because somehow error appears to be related to this change. Master is good, PR is not good. Not set any organization level licenses.

How do I enable on local this setting?

**Comment by neilkakkar** [comment]
On what should be paid vs not: Old paths allowed for 3 steps only, and new Paths without the advanced option to show more edges means that >10 steps look very empty.

Thoughts on fixing not-paid Paths to 3? 

Example: 5 steps:

image

17 steps:

image


17 looks broken compared to 5, (how did the number go down?!) because they fundamentally need more edges to represent the same information.

**Comment by EDsCODE** [comment]
@mariusandra  What happens when you click on include events? Empty state shows up if user sessions don't have multiple different events in a 30 minutes window. Although, in this case i'd assume there are multiple pagesviews with different URLs

**Comment by paolodamico** [comment]
Thanks for the review! Update here,
- Border thing, code improvements addressed (@mariusandra) & limited to 5 steps if you don't have the paid feature (@neilkakkar)
image

- Tested multiple times, with different projects, different settings and Pageviews seem to render properly. Can you try again? Could it have been a DB issue or something?
    image
    image

I'll hold off merging until we confirm it works, we can cherrypick it to the release.

**Review by mariusandra — APPROVED** [review]
Looks good to me. I'm seeing some paths locally now, so that problem is gone as well.

**Pull request merged**
