### PR TITLE
Better seekbar for session recordings

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Implements a working seekbar for session recordings play view. Builds on top of https://github.com/PostHog/posthog/pull/6505.

There're a lot of edge cases to watch out for and there are definitely some minor bugs/performance issues. However, the main functionality is there and I think it's worth getting this one out under a beta flag so that we can iterate on these minor bugs better.

Some edge cases to watch out for:

- scrubbing while playing
- scrubbing while paused
- click to seek
- drag to seek
- drag and hold over specific time seek
- seek forward/backwards on different speeds
- current time being greater than last buffered time
- moving in and out of different states (play, pause, skip, scrub, buffer)
- dragging scrubber (mousedown, mouseup, etc.)
- resize window -> resizes seekbar
- and a lot more 🥲 

https://user-images.githubusercontent.com/13460330/138372839-29dd37fb-72bb-47c1-adcf-b99b4d1da836.mov

## How did you test this code?

- I'm holding off on writing tests for session recording player so I can iterate quicker.

### CODE REVIEW

**Review by clarkus — APPROVED** [review]

**Review by rcmarron — DISMISSED** [review]
This is great! So good to see the seek bar coming alive!

A couple of thoughts on performance (maybe we address these in a later PR - up to you). Right now, it feels kind of laggy as you drag and click around. I think there are a couple of pointed changes that we can do to help this:
* It seems like we don't move the thumb until the player frame actually updates to the time, and I think it's because the setCurrentTime action is updating the thumb position as well as the user action. And so they're fighting for the position. Maybe we track a `is_seeking` and the user interaction takes precedence if that's happening?
* I think as the user slides the bar, we are updating the player. What if we only update the player time when the user releases (e.g. `onSeekEnd`). Probably want to play with it, but that might speed things up a bunch?

A couple of bugs:
* Resizing the windows seems to break things
image
* I'm not sure if the speed toggle is supposed to work yet, but it seems to always show 1x on reload, but the player goes at 16x (I might be setting that in the old player, and then it's persisted to this player?)
* It seems to pause right before the playback actually finishes:
image

**Comment by alexkim205** [comment]
Thanks for the review! Tried out a few of the performance suggestions but it seems like it might require more digging.

> It seems like we don't move the thumb until the player frame actually updates to the time, and I think it's because the setCurrentTime action is updating the thumb position as well as the user action. And so they're fighting for the position. Maybe we track a is_seeking and the user interaction takes precedence if that's happening?

* Adding a `is_seeking` tracker should solve with the render race problem, but the lag still persists. I found another rendering bug where the entire `<PlayerController/>` component was rerendering on ever seek change, but fixing that hasn't helped either. I'm wondering if it's something to do with how we're using `left: Xpx` to paint this state change. 

> I think as the user slides the bar, we are updating the player. What if we only update the player time when the user releases (e.g. onSeekEnd). Probably want to play with it, but that might speed things up a bunch?

* I think this is a good optimization to make!

Bugs:

* Fixed resize bug
* I can't seem to reproduce this one. I'm changing the speed to 16x and then reloading, but seeing the player playing at 1x speed. I can only think of this happening when the inactivity skipping happens at the very beginning of the recording. Made a conservative fix that might address this issue.
* Fixed

Additions

* Slider now working on touch devices

**Review by rcmarron — DISMISSED** [review]
This is awesome! So much faster on seeking! A couple of little bugs I noticed in testing:
* The play/pause button switches to pause when you're seeking. I get that it's technically paused, but it feels a bit odd.
* I wish clicking to seek was as fast as seeking by moving the thumb. When I play with Youtube, it seems like the thumb meets my mouse click onMouseDown, and then I can start seeking from that point. I wonder if we moved to something along those line it might feel snappier and the same `is_seeking` check could apply to the "click to seek" UX.
* On mobile, something weird happens when I scrub where it resets. You can see it in the video. It seems to repro pretty consistently.

https://user-images.githubusercontent.com/4813045/138741021-2fe5bb9a-4f5c-4ea7-81de-5e13fd8a027c.mov

**Comment by alexkim205** [comment]
> The play/pause button switches to pause when you're seeking. I get that it's technically paused, but it feels a bit odd.

Changed!

> I wish clicking to seek was as fast as seeking by moving the thumb. When I play with Youtube, it seems like the thumb meets my mouse click onMouseDown, and then I can start seeking from that point. I wonder if we moved to something along those line it might feel snappier and the same is_seeking check could apply to the "click to seek" UX.

Nice catch! I got rid of the `onClick` entirely and replaced it with `mouseDown/touchStart` handlers. Realized that having two separate handlers here was causing `handleSeek` to double fire since clicking is a subset of mousedown. This now makes seeking on click work as quickly as dragging the seekbar.

> On mobile, something weird happens when I scrub where it resets. You can see it in the video. It seems to repro pretty consistently.

This seems to be caused by some Web API weirdness. X coordinates exist on a different parameter on `touchend` compared to `touchmove` events. This was causing `getxPos()` to return `NaN` which led to the thumb always jumping back to the 0 mark. Should be fixed now!

https://user-images.githubusercontent.com/13460330/138751353-f6c73227-4b53-4181-bcc2-2651e71d23af.mov

**Review by rcmarron — APPROVED** [review]
Nice! This is feeling very smooth!

**Review by mariusandra — COMMENTED** [review]
Overall looks good, and definitely the right call to get it out and iterate. Left some comments inline, feel free to address in the future if/when relevant.

Also, I suggest starting to lock in the functionality with tests, or you'll end up pushing them too far into the future. The suggestion here is a basic one: figure out what you can do to derive as much data with selectors as you can, and eliminate as many actions as you can. This will make it so you have less code to test 😆.

**Comment by alexkim205** [comment]
Hey @mariusandra thanks for the review :) 

I've addressed the resolved conversations in this PR - #6641

---

I'm working on the logic tests in a separate PR—Stay tuned!

**Pull request merged**
