### PR TITLE
feat: Added kea-router beforeUnload support

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

As part of https://github.com/PostHog/posthog/pull/10197 I upgraded `kea-router` to have built in support for handling unload intercepting e.g. stopping the user from leaving if they have changes. The current method only supports Insights and is pretty hacky and buggy

## Changes

* This PR upgrades kea-router and implements the new `beforeUnload` event for Insight

## How did you test this code?

Tested the various case of going to into edit mode, making a change and then:
  * ✅ Going back and getting prevented natively
  * ✅ Going forward ( to a different url) and getting prevented natively
  * ✅ Clicking a different url and getting prevented via the router
  * ✅ Saving the Insight and no longer being prevented from moving

### CODE REVIEW

**Comment by mariusandra** [comment]
Still some tests failing :/

**Comment by benjackwhite** [comment]
@mariusandra should be fixed now and with some better code

**Review by mariusandra — APPROVED** [review]
Looks good! Still reviewing the other PR, will leave it up to you to merge them in.

**Review by Twixes — COMMENTED** [review]
I reran that test but forgot to post the review. 😅 Looks great to me! Cleaner than the previous approach.

**Pull request merged**
