### PR TITLE
feat(correlation): ability to exclude property correlations for events

### PR DESCRIPTION
**Pull request by hazzadous**
This simply stores a list of event property names. Specifically it
doesn't store a separate list for each event, but rather a list of
properties irrespective of event name.

### CODE REVIEW

**Comment by neilkakkar** [comment]
Hey @hazzadous , just pushed an update that hopefully makes things clearer for both this PR, and the previous one (property exclusions).

I realised that the only thing we're using `setEventPropertyNames` is to set an array. But, this can be achieved just as well using the reducer state. Have a look here: https://github.com/PostHog/posthog/pull/6665/commits/c0c81159239450d2a1c6a2a7612240a8e615d80b

Now, when you click Exclude, the action is called with the right event name, which triggers the row vanishing.

**Comment by hazzadous** [comment]
@neilkakkar great yup looks good to me

**Review by neilkakkar — APPROVED** [review]

**Comment by hazzadous** [comment]
@neilkakkar need to resolve conflicts the target branch has with master now, then will get this one in as well

**Comment by hazzadous** [comment]
Have changed to master target, and merged in master. fingers crossed that should be enough @neilkakkar

**Pull request merged**
