### PR TITLE
Move `Dashboards` to `LemonTable`

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

The Dashboards page was looking really meh. Moved it to the new table component from https://github.com/PostHog/posthog/pull/7103 as part of https://github.com/PostHog/posthog/issues/6710:

| Before | After |
| --- | --- |
| Zrzut ekranu 2021-11-19 o 17 46 08 | Zrzut ekranu 2021-11-19 o 17 47 13 |

## How did you test this code?

Just using the table.

### CODE REVIEW

**Comment by mariusandra** [comment]
The lemons are coming!

I find two things weird though:
1. The "Created" text is right-aligned. I understand right-aligning numbers to be able to read the thousands, millions, etc in line, but here with free-form text it doesn't make much sense.
2.  Too much space in the first "pin" column.
image

**Review by clarkus — CHANGES_REQUESTED** [review]
- This looks good, but I think sorting is the wrong mechanism for showing pinned items. What if instead we put a prominent filter in place for limiting the set to just pinned / unpinned items? My core issue is that there isn't a column label and the sort indicator is kind of orphaned - there's just nothing there that identifies that info. Instead I think we could combine the pinned status with the primary dimension, dashboard name, to communicate pinned status. This has the added benefit of not over-prioritizing that pinned column. 
- I think we could do more to size the columns to their content. They just feel oversized for the range of data they are representing. This would have the added benefit of freeing up more space for describing columns that benefit from additional characters - dashboard name, users, etc.
- The table row also feels over-padded on the right. Any reason we have extra padding there?

**Review by mariusandra — APPROVED** [review]

**Comment by Twixes** [comment]
Marius was really happy to see the new iteration, so it got merged – here's what it looks like @clarkus:
Zrzut ekranu 2021-11-22 o 12 14 20
Feel free to point anything out, happy to adjust.

**Comment by clarkus** [comment]
Looks better to me - the column sizing still feels overly specific but that's not a blocker.

**Pull request merged**
