### PR TITLE
chore(data-management): better ux signaling to bring actions into events

### PR DESCRIPTION
**Pull request by alexkim205**
## Problem

To make the simplification of actions less jarring for users already using actions, I'm bringing back the actions tab and adding some signals indicating/explaining the change.

## Changes

With FF

Screen Shot 2022-06-24 at 1 01 41 PM

Without FF

Screen Shot 2022-06-24 at 1 04 13 PM

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Toggle FF

### CODE REVIEW

**Review by clarkus — CHANGES_REQUESTED** [review]
The "will deprecate" pill on the actions tab definitely adds affordance and gets a user to look there, but I am wondering if we should show the deprecation banner prominently above the tabs. The change affects both the actions and events lists, so you could argue that it makes sense to place it at a higher level in the hierarchy. 

I think the message content could be improved a bit to be a bit clearer and more approachable. How about something like:

"Actions are now called events and can be found in the events tab. Events are now called raw events and can still be found in the events tab. You can create a new event (formerly known as an Action) by clicking the "New event" button."

Given this is a bit of a deprecation, I think we could get ahead of this a bit and send the notice to users via an email or other alert. It might just be easier to mange this if they're being informed of the change via a direct and clear message before having to navigate the data management page. 

@joethreepwood do you have any thoughts on how we could communicate this to users outside the product so they're not caught off guard when looking for actions?

**Comment by joethreepwood** [comment]
> @joethreepwood do you have any thoughts on how we could communicate this to users outside the product so they're not caught off guard when looking for actions?

We could do a blog explaining what has changed, why and the impact. Ideally we release this a few days before the switch. We should absolutely do this. Tagging @andyvan-ph, who I'll defer to on social decisions.

The main way though, would be email. We have permission for emails such as this in our policies, so the question is whether to send to ALL users, or AFFECTED users. 

So the questions are: Is this change momentous enough we should email every users, and how many users would be affected?

I'd love input from you both on the first question, but my feeling is that unless there is action required or the affected users are a majority then it isn't worth telling everyone. On the second question, it's just a case of whether there is action required or any functionality which may be disrupted?

I've created [a cohort](https://app.posthog.com/cohorts/10378) to help us size the number of affected users and to use for email targeting. I'm looking at any users who have created an action in the last 120 days _and_ who have ingested and logged in in the last 90 days (i.e. are active users). That pool is 420 people, so this _feels_ like a small number of users.

**Comment by clarkus** [comment]
I think only alerting affected users is a good call. Secondary to that we can rely on the banner components and messaging in product to clarify what changed. The only other thing I think we should promote is a way to get in touch with us if the affected user has questions / concerns about the change. That should go into the banner message for sure.

**Comment by joethreepwood** [comment]
OK, I can create an email for the affected users. To help me write this and because I'm late to this, can your give me (either here, or via Slack) a quick overview of what's changing, why and what the impact could be for users @alexkim205 ?

**Comment by alexkim205** [comment]
Thanks @joethreepwood! 

A quick overview of the change:

### What changes?

- Actions will be renamed to events, and events to raw events
- "Events" (previously actions) are moved into the events table in Data Management > Events

### Why?
- With the introduction of Data Management's event and property definitions, it is difficult to decide when to create an action vs. a simple event definition. Customers also reported that they struggle to differentiate or group similar events, causing inconsistency in reporting and inaccurate analyses.

### Impact
Nothing functionally changes
- Flow for creating a new "Event" (previously action) does not change. This can be done from the Data Management > Events page
- "events" and "actions" filters have been renamed to "raw events" and "events" filters. These two concepts are kept separate in taxonomic filters.
- API endpoint does not change either for actions (still deciding if its worth it to change the endpoint name here)

Here's the more detailed RFC that captures the reasoning behind this (https://github.com/PostHog/product-internal/pull/300).

Please lmk if you need any more details here.

**Comment by joethreepwood** [comment]
I'll send a test email to relevant people on this thread, but I have the audience and campaign set up as follows.

The only thing I need to know @alexkim205 is a date for when this launch will take place. I assume we'll update docs at that point too? I'll defer to @andyvan-ph but given the small impact, I'm not sure a blog post is fully warranted. 

Screenshot 2022-07-08 at 12 20 42

**Comment by joethreepwood** [comment]
The email is now scheduled to send 22 July, 12 noon GMT

**Comment by alexkim205** [comment]
Closing because work here is outdated. Chris's copy feedback is still going to be applied in this PR (https://github.com/PostHog/posthog/pull/11018)

**Pull request closed without merging**
