### PR TITLE
Global annotations

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes
- depends on #1120 
- implement ability to add global annotations

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Looks good to me!

Feel free to merge when needed (re: cutting the next release?)

**Comment by mariusandra** [comment]
One thought... and it probably doesn't make sense to address it in this PR, but feel free. I can create a new issue as well.

When there are many annotations, it feels quite cumbersome to have to manually click on them, especially if they are closely together:



It would be cool if the boxes would just open when you hover over them... and then perhaps you can click them to "fix" them to the screen if you want to add/delete notes.

**Comment by EDsCODE** [comment]
https://github.com/PostHog/posthog/issues/1220

**Comment by EDsCODE** [comment]
I will wait until we figure out when the next feature deployment is! if it's tomorrow, I'll merge this after we cut release so we get to test it, otherwise I'll merge it so it goes in with annotations next week

**Pull request merged**
