### PR TITLE
Show underlying property value type

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Had a user call where it was hard to say whether PostHog was receiving data from Segment in string or in number type. This makes the type apparent in PostHog UI.

Properties

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Doesn't "feel nice" though, having those annotations for everything. Maybe an info button or tooltip would be better? I see the benefit of this, but I think it would be a little annoying and not too beneficial for the majority of users

**Comment by Twixes** [comment]
I actually thought of just a small question mark next to the value that would show a property type tooltip on hover, but opted for something simpler for a start. If you think the tooltip would work better, can implement that!

**Comment by mariusandra** [comment]
Are there only string and number types? Or something else like date?
I'd skip writing anything for strings as they are 99% of the types and do something for the other ones. For example a monospace font for numbers or a simple and unobtrusive antd icon in front of the field (with a tooltip)

**Comment by Twixes** [comment]
Yeah, if it's a date, it's still a string, since we're limited by JSON's capabilities. So basically it can be string, number, boolean, or null.

**Comment by mariusandra** [comment]
Then for me something like makes sense:
- string: no change
- number: monospace font
- boolean: shown as a true/false tag (text with a background)
- null: just "null" in a gray font

**Comment by mariusandra** [comment]
Parsing dates and showing them in a friendly way with `<CalendarOutlined />` before it could also make the product feel nicer. `<NumberOutlined />` could maybe go in front of the numbers?

**Comment by Twixes** [comment]
Made it look like this:

Icons

**Comment by Twixes** [comment]
Made it look like this:

Icons

**Comment by yakkomajuri** [comment]
I like the icon + tooltip approach! Thinking if maybe the icons could be a few shades lighter than the text?

**Comment by Twixes** [comment]
Should be nice now.

**Pull request merged**
