### PR TITLE
fix: Update packaging dependency and pin prance

### PR DESCRIPTION
**Pull request by tomasfarias**
## Problem

`requirements.txt` and `requirements-dev.txt` contain incompatible versions of `packaging`:

[The former](https://github.com/PostHog/posthog/blob/master/requirements.txt#L227) in line 227 requires:
```
packaging==23.1
    # via webdriver-manager
```

Whereas [the latter](https://github.com/PostHog/posthog/blob/master/requirements-dev.txt#L143) in line 143:
```
packaging==21.3
    # via
    #   -r requirements-dev.in
    #   datamodel-code-generator
    #   prance
    #   pytest
```

I've narrowed down the issue to a mistake in the `prance` library that incorrectly published a new version `0.23.x` under the `0.22.x` version number, thus it doesn't appear as the latest in [PyPI](https://pypi.org/project/prance/#history). See https://github.com/RonnyPfannschmidt/prance/issues/148.

## Changes

The solution is to update `packaging` and pin `prance` to the actual last version `0.22.x`.

### CODE REVIEW

**Comment by pauldambra** [comment]
I had to pin prance in requirements.in as well to remove all errors when running pip install locally....

**Comment by tomasfarias** [comment]
`pip install`-ing both requirements seems to resolve for me:
```
pip install -r requirements.txt -r requirements-dev.txt
...
Successfully installed django-3.2.18 fakeredis-2.11.0 mypy-0.981 mypy-extensions-0.4.3 packaging-23.1 prance-0.22.2.22.0 redis-4.5.4 sqlparse-0.4.4 webdriver-manager-3.8.5
```

But we can wait for CI, if it's needed in `requirements.in` I can add it too.

**Comment by tomasfarias** [comment]
I think it may be needed as `Async migration tests` only install `requirements.txt` and are failing as `prance` is not there:

```
posthog/api/test/test_capture.py:25: in <module>
    from prance import ResolvingParser
E   ModuleNotFoundError: No module named 'prance'
```

EDIT: Or `Async migration tests` should install `requirements-dev.txt`...

**Review by pauldambra — APPROVED** [review]
me: approving my own changes on someone else's PR

lockscreen

**Pull request merged**
