### PR TITLE
Remove feature flag for hotkeys buttons for insights page and add hot…

### PR DESCRIPTION
**Pull request by DimitrisMazarakis**
Add function for Hotkey buttons for Insights page #3740

## Changes

Removed featured flag for hotkeys buttons in insights page after testing locally that they work successfully and added the hotkey button for the history button.

Screenshot from 2021-05-20 23-28-40

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by paolodamico** [comment]
Thanks for the PR @DimitrisMazarakis! I just pushed some minor changes to the PR,
1. I'm removing the hotkey button from history as we have plans to remove that view (see #3408)
2. I'm also removing other feature flagged code required to release hotkeys for everyone.

**Comment by paolodamico** [comment]
I also want to share some stats for the record on why it makes sense to release this feature. In the last 4 weeks,
1. Feature was used on average by 8% of active users (about the same as some of the less used insight features). ([reference](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A5043%2C%22name%22%3A%22App%20Pageview%20-%20Logged%20in%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%7B%22id%22%3A%22hotkey%20navigation%22%2C%22name%22%3A%22hotkey%20navigation%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&filter_test_accounts=true&new_entity=%5B%5D&date_from=-30d&interval=week&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22hotkeys-3740%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&formula=A%2FB))
2. On average, there was a 68% increase in weekly discovered learnings per user. While this is not a perfect number as a) the sample size of the experiment group was small and b) this feature was running in parallel with other experiments, we can at least now that directionally this feature lead positive results. Reference: [experiment group](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A5043%2C%22name%22%3A%22App%20Pageview%20-%20Logged%20in%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&formula=A%2FB&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22hotkeys-3740%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&date_from=-30d&interval=week) & [control group](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A5043%2C%22name%22%3A%22App%20Pageview%20-%20Logged%20in%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&formula=A%2FB&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22hotkeys-3740%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D&date_from=-30d&interval=week).

**Review by paolodamico — APPROVED** [review]

**Comment by paolodamico** [comment]
Cypress tests pass locally, @macobo / @timgl do you know if these are supposed to run fine for forks?

**Comment by timgl** [comment]
@paolodamico You could push the branch as your own and create the PR to have the test run properly. they look like semi legit test failures so maybe good to test.

**Comment by Twixes** [comment]
The Cypress tests should run properly on fork PRs too though, at least I don't think there's any secret sauce here (internal test data or anything like that) besides parallelization. It's discouraging for contributors to see tests failing and their issues closed due to the something just in the maintainers' CI setup, so we should make sure this is accurate.

**Comment by paolodamico** [comment]
EDIT: I'm merging this PR given that CI tests actually pass (see #4488), seems like a CI issue with forks.

**Comment by yakkomajuri** [comment]
hey @DimitrisMazarakis ! seems the bot didn't pick up your email address automatically. Care to message me at yakko at posthog . com for a gift card code for merch?

**Comment by DimitrisMazarakis** [comment]
Hello @yakkomajuri ! My email is dimitrismazarakis77@gmail.com .

**Pull request merged**
