### PR TITLE
Install `python3-saml` everywhere

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Changes
As discussed [here](https://github.com/PostHog/posthog/pull/6575#discussion_r733457836) let’s install `python3-saml` and all its related dependencies by default. This is to simplify our overall setup, as the benefits this bifurcation brings are not worth the complexity we need to maintain.

I've manually added `python3-saml==1.12.0` to `requirements.in` and then I ran:

```
pip-compile requirements.in
pip-compile requirements-dev.in
```

Here's also the related change to our docs: TODO

## How did you test this code?

**DEV**

1. The image is built correctly:
    ```
    ➜  posthog git:(python3_saml_everywhere) ✗ docker build -f dev.Dockerfile .
    [+] Building 720.4s (14/14) FINISHED
    ```

1. Image size and build time are like before

1. `docker-compose -f docker-compose.dev.yml up` still works:
    ```
    posthog-backend-1   | Django version 3.2.5, using settings 'posthog.settings'
    posthog-backend-1   | Starting development server at http://0.0.0.0:8000/
    posthog-backend-1   | Quit the server with CONTROL-C.
    ```
    ```
    posthog-worker-1    | [MAIN] 11:15:35 🚀 All systems go
    posthog-worker-1    | [core] INFO: Worker connected and looking for jobs... (task names: 'pluginJob')
    ```

**PROD**
1. The image is built correctly:
    ```
    ➜  posthog git:(python3_saml_everywhere) ✗ docker build -f production.Dockerfile .
    [TODO]
    ```

1. Image size and build time are like before

1. `docker-compose -f docker-compose.dev.yml up` still works:
    ```
    [TODO]
    ```

### CODE REVIEW

**Comment by paolodamico** [comment]
FYI the biggest blocker we have these deps was running on Heroku, you can see a few PRs where I tried different things to install the deps. Perhaps the option is running Dockerized on Heroku.

**Comment by guidoiaquinti** [comment]
> FYI the biggest blocker we have these deps was running on Heroku, you can see a few PRs where I tried different things to install the deps. Perhaps the option is running Dockerized on Heroku.

Yup, unfortunately I'm still not there but that's on my TODO list. Do you know where we configure Heroku? `app.json`?

**Comment by paolodamico** [comment]
Yes! And there's a community (but on the Heroku repo) build pack to install apt deps.

**Comment by guidoiaquinti** [comment]
Actually, I think https://github.com/PostHog/posthog/issues/6605 is a pre-requirement of this PR (as well as moving Heroku to use containers).

**Comment by hazzadous** [comment]
> Actually, I think #6605 is a pre-requirement of this PR (as well as moving Heroku to use containers).

We can in the least just remove the conditional in the Dockerfile? Or is there some reason we'd not want to do that? i.e. just because we can't deploy to heroku doesn't seem like a reason to make it conditional in the Dockerfile? Or anywhere else?

**Comment by paolodamico** [comment]
From my perspective we can definitely remove the conditional on the Dockerfile as it won't affect Heroku. Important to keep in mind the `SAML_DISABLED` env var is still used in the app to know whether to load those modules or not.

**Comment by paolodamico** [comment]
@guidoiaquinti just checking we want to let this die

**Comment by guidoiaquinti** [comment]
> @guidoiaquinti just checking we want to let this die

We shouldn't but this is unfortunately not a priority for me and/or my team atm :/

**Pull request closed without merging**
