### PR TITLE
Events scene design proposal in storybook

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Trying out an experiment --> what if we integrate mockups (or even figma previews?) directly into storybook..
- The aim is to provide a clear example between what is designed and what is implemented (minus the broken design)
- Copies a png file from [this comment](https://github.com/PostHog/posthog/issues/5546#issuecomment-904155079) into the storybook
- View the result [here](https://61260360a8e859003a7c138b-klzjmjcfco.chromatic.com/?path=/story/posthog-scenes-events--all-events). 

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by paolodamico — COMMENTED** [review]
I'm a bit torn about this. On the one hand, it can help introduce this concept of "finalized" designs so we have them ready for implementation. On the other, designs change all the time so I'm concerned this will become outdated faster than we push them.

Thoughts @clarkus ?

**Comment by clarkus** [comment]
Sorry I haven't made time to respond yet. I think this could be fine, but I honestly don't have a good enough handle on the core problem yet. I don't think I can evaluate possible solutions because I'm still trying to frame the problem sufficiently. Here are my quick thoughts so far:

- Sharing design work for feedback / communication usually comes in 1 or 2 forms
  - Iterative work shared early and often within the feature team - this is more focused on specific problems and not necessarily focused on the broader solution
  - Milestone sharing to a broader audience - sometimes this happens when engineers demo implemented solutions, but it can also happen via other means. 

We're currently using figma comments / slack to drive a lot of the iterative work right now. That's been working better so far, but it's still early. This solution could help address milestone sharing, but it might not be approachable to less-technical team members.

**Comment by paolodamico** [comment]
I'm more concerned that we won't have this "hand-off" moment alive for too long. Consider now, we have paths designs still in the works, when they are done implementation most likely be soon ready too, and designs will quickly get outdated as we push tweaks/improvements right away.

**Comment by mariusandra** [comment]
This all makes sense. I agree that the synchronisation aspect will quickly get out of hand. Let's close this for now. Would be cool if we could somehow link to Figma from relevant storybook stories though.

**Pull request closed without merging**
