### PR TITLE
Closes #410 - precalculcate events that match action

### LINKED ISSUE #410: Precalculate which events belong to which actions
At the moment, whenever we do a query involving actions in the frontend, the database has to do a lot of heavy lifting to calculate which events match the action. This has resulted in us hitting Heroku time-outs (30s) and it's clearly not scalable.

@mariusandra Suggested creating a new table (or just a m2m field) on the action that stores each event that matches it. This will massively speed up every query.

There are a couple of moving parts to this.

- [ ] **Migration**: For each existing Action, we'd need find out which events match and store those.
- [ ] **Capture**: Whenever we capture an event, we need to figure out what actions (if any) match that event, and store the event against that action. We might have to put [this bit of code](https://github.com/PostHog/posthog/commit/cc1de5839394136849b58ffeac998fd205a3ca6c#diff-3b36a34a38797d4ea54c7f9d17d69ac8L330) back to be able to do that.
- [ ] **Creating/updating actions**: whenever someone creates or updates an action, we need to flush the events associated with that, and re-run the query to find all the events that now match this new action and store those.

### PR DESCRIPTION
**Pull request by timgl**
@mariusandra Would love your thoughts on this (also see #410 for more details)

It makes a lot of things a lot quicker as expected, like the /actions overview, /trends, the dashboard etc.

I would love your very direct feedback. Important to get this right, I'd rather do it again than do it wrong now.

**Edit**: Another problem with this is that databases meant for large storage (like Clickhouse) don't support relations. This might be a bridge to cross at that point as it does massively speed things up for Postgres right now.

### CODE REVIEW

**Comment by mariusandra** [comment]
Hi @timgl , I had a look at the PR. 

My main concern is about updating the events (creating the many-to-many relationships) in synchronous mode (on submit)... vs doing it asynchronously (background job).

I see code like this and wonder if it is scalable:

```python
def on_action_step_change(sender: Any, instance: ActionStep, **kwargs: Any):
    events = Event.objects.query_db_by_action(instance.action)
    instance.action.events.set(events)
```

I don't know enough about django's ORM to know what SQL queries this will produce, but it's possible that this results in python calling a SQL `INSERT` query N times, where `N == events.len()`. Possibly even 2xN, if it has to disconnect the previously connected actions one by one before creating new ones. I don't know if it will preserve old ones and just add new ones... or recreate everything. In any case, if you have a database with millions of events, adding one bad step such as "url contains 'http'" will potentially result in a lot of work... and the "add step" button timing out after 30 sec.

The user will just be editing a few characters in a string on the interface, never knowing how many gigabytes of SQL will be sent back and forth between the DB and the app server.

Do you have somewhere a *HUGE* test database with (hundreds of) millions of events, on which you can try running an experiment to add/remove some action steps and to see if it times out or not? It might be worth creating such a test setup and trying this. However if you enable debug output of sql queries, and run this on even a small DB, if you see hundreds of `INSERT` statements in the logs, you will have a problem very quickly.

Assuming the problem exists (and django doesn't do some postgres magic that solves all of this with 1 query), I see a few options for overcoming this:

a) When editing an action step, update the events asynchronously in a python/django background worker, probably in batches of thousands of events... and show some "reindexing" label to the user while the work is being done, possibly even with a progress bar. You should keep track of how far the work has progressed, so that if the user adds another action step before the first job has finished doing its work, it will either cancel the first job or somehow assure that the two jobs will not interfere with each other. Plus you'll need a way to pause/resume those jobs, as your users might want to upgrade posthog while they are running... or any number of fun scenarios.

b) Move the many-to-many updates into postgres. I don't have enough experience to say how to do this for certain, but it should be possible to create a trigger that for every insert/update in an action step, creates or updates the many-to-many relationships automatically inside postgres. It will be a lot faster than piping all your data into django and back, but it might still be slow as you will be possibly updating or inserting millions of entries into the database. I'm also not sure how would you pass the list of events to postgres. You'll probably need to write a lot of SQL to duplicate the django code that matches events to actions.

c) Some combination of the two, where you create a postgres function that updates only a part of the events (e.g. created_at between X and Y) and then call this function multiple times from a django background task.

d) Find some other technology that does this automagically. I'm not sure what though.

All of the options are a lot of work... and sorry that I don't have any better ideas right now :). The first thing is still to test how much work will django and postgres have to do when editing/adding an action step. It could be that with tens of millions of events, things still run smoothly, even if you add a new action that matches `"/"` in the URL. Or it could not be, but before testing this, we won't know for sure.

**Comment by timgl** [comment]
The semi-good news was Django was a little bit cleverer than doing a single query for each event, but it was still loading the ID's in memory. After a lot of digging, I came up with the following, fairly simple solution. Luckily I did implement the Action matching logic in a way that meant it's just a SQL query, so I was able to do b).

```sql
INSERT INTO "posthog_action_events" ("action_id", "event_id") SELECT 100,
       "posthog_event"."id"
  FROM "posthog_event"
 WHERE ("posthog_event"."team_id" = 2 AND (("posthog_event"."event" = '$pageview')))
 ORDER BY "posthog_event"."id" DESC;
```

It's actually fairly fast with about 30k rows (about 4s). It does fall down with a million rows, as it takes about 100 seconds.

I think we should push forward with QA'ing, merging the solution as I have it now as it really speeds up the entire interface for a large number of people (including our own account for example) and won't break deployments with millions of rows any more. I'll write up a ticket for implementing workers so this can be the first thing we offload to those.

Does that make sense to you @mariusandra ?

**Comment by mariusandra** [comment]
Hi @timgl , that makes sense and looks like a cool fix. It might be worth wrapping the DELETE & INSERT queries inside a transaction though... unless django does it automatically, as otherwise you might end up with a weird and inconsistent state if the user cancels the save request half way through. 

Another small (or big?) win might be to optimise the delete/insert queries to 1) delete what is not in the new batch of events and 2) insert only what should be added... but the current approach for sure makes sense just considering the 80-20 rule.

**Review by mariusandra — APPROVED** [review]

**Comment by timgl** [comment]
@mariusandra Yep, I've now added this inside of a transaction. The optimisation I tried but it was much slower, as that select query can get super slow, and it's faster to reinsert everything than to run that query twice. There might be a way of doing a window(?) but I don't want this code to become too specific to Postgres, for when we do migrate to another type of database.

@Tannergoods Would you mind giving this a really thorough QA? This has the potential to break everything related to actions.

https://posthog-410-precalculat-vpotea.herokuapp.com/

It uses a fork of the production database so you can play around with it as much as you like

**Comment by Tannergoods** [comment]
I believe I have been very thorough. (have listed everything I touched as a reminder but also in case I've missed something) 

Dashboards (deleted / created new) 
Trends - built several filtered and broke down, volume, stickiness, Total, DAU
Actions - filtered, created new (both page views and front end elements), Live Actions, deleted, edited
Users, Cohorts - created new (adding new group looked to timeout but this might not be related, screenshot below)
Funnels created, edited and deleted
Paths (I know this doesn't match up but wanted to check!) 

Posthog

**Comment by timgl** [comment]
@Tannergoods Great work, thanks for diligence.

**Pull request merged**
