### PR TITLE
fix: insight tooltip scrolling

### LINKED ISSUE #19555: Insight overlay is not scrollable
## Bug description

The overlay will cut of the 3rd item.
2024-01-02 at 14 06 49@2x

## How to reproduce

1. Create an insight with multiple chart series
2. Hover over the chart
3. Try to view the 3rd item inside of the overlay

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/8738

### PR DESCRIPTION
**Pull request by anirudhpillai**
## Problem
Fixes #19555 

## Changes
This was tricky because we don't enable `pointer-events` on the tooltip so on moving the mouse once can quickly move to the tooltip from on point on x axis to other.

I added an mouseEnter/Leave handler to change the `pointer-events` but still there is a gap that we put between the tooltip and the vertical line on the x axis (so that the points are visible) and as soon as the mouse moves away from this vertical line, the tooltip itself disappears. 

So I reduced the gap between the tooltip and the axis with points so it's 'easier' to access the tooltip and scroll on it. It's still not ideal but it actually lets you scroll for now. 

https://github.com/user-attachments/assets/a3e0dfdf-f0a5-4fef-aa3b-15e911d5d615

## Does this work well for both Cloud and self-hosted?
N/A

## How did you test this code?
Tested locally

### CODE REVIEW

**Comment by anirudhpillai** [comment]
Will reimplement with mouse tracking (moving towards tooltip) or by letting user hold shift to scroll tooltip

**Comment by abhi12299** [comment]
@anirudhpillai continuing from your work, I tried to implement the following:
- When user holds `shift` key, I prevent the tooltip from disappearing
- Allowing pointer events in the tooltip component so that the scroll can work

However, this change has the following side effects:
- Now that pointer events are allowed in the tooltip, when the user enters the tooltip, the `onClick` handler of the chart no longer works. This is because earlier, the tooltip had `pointer-events: none` property, which meant clicking anywhere in the tooltip registers as a click on the chart.
- Since the tooltip responds to pointer events and is being rendered on top of the chart, the chart assumes any interaction (or mouse entering) with the tooltip as a `mouseout` event. This means that even if we pass the chart's `onClick` handler down to the tooltip, it will not work, because the `onChartClick` function needs a reference to the `chartEvent` with which it can identify the lines/points for which data should be opened in the modal. Refer to this code: https://github.com/PostHog/posthog/blob/038e10c010b028766f77e1d11394aac23ce658c3/frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx#L71-L96
- If we keep holding `shift` and just move the cursor out of the chart, the tooltip stays there because the moment the chart triggered a `mouseout` event to set the opacity of the tooltip to `0`, we were holding down the `shift` key.

All 3 issues are described in this video:

https://github.com/user-attachments/assets/af172f0b-93af-40d1-a47c-1d062dce593e

There are 2 ways forward now:
1. Make the tooltip not scrollable/interactive and try to truncate the text within the tooltip bounds
2. If we want to keep the tooltip interactive, we have to work around the fact that the chart will trigger a `mouseout` event. So we need to keep a reference of the points/line that the user opened the tooltip for, and open the modal with that data. We still need to figure out what behaviour we want for the last side effect described above (moving the cursor out of the canvas while holding `shift`.

Hoping to discuss this more and getting to a resolution :)

**Comment by anirudhpillai** [comment]
@abhi12299 thanks for looking into this and agreed on all the 3 issues those were want we ran into.
@skoob13 had another idea using some library logic from Radix to make the tooltip stick when the mouse moves towards it, but make it disappear in other scenarios (kinda based off of what you suggested in 2. but without the shift key)

**Comment by abhi12299** [comment]
@anirudhpillai so that means if I implement the behaviour of persisting the tooltip while the shift key is being held (with click handlers working), this can be extended to using mouse movements instead.

Should I continue to implement the shift functionality then?

**Comment by anirudhpillai** [comment]
I think we shouldn't need the shift key then. When the tooltip appears and you're moving mouse towards the tooltip, it sticks around, otherwise if you move mouse away from tooltip, it disappears. I'll let Georgiy confirm though, he might have envisioned it differently :)

**Comment by abhi12299** [comment]
okay

**Comment by anirudhpillai** [comment]
also @abhi12299 wanted to send you a gift code for our merch store, can you let me know which email to send it to?
Can also email anirudh at posthog.com if you don't want to share it here :)

**Pull request closed without merging**
