### PR TITLE
Add an empty state for funnels and property filter arrow fix

### LINKED ISSUE #5340: Helpful error state when funnel query fails
## Bug description

When I create a funnel breakdown query that doesn't work for some reason, I see the empty state rather than an error explaining what happened and what I can do to fix it:

image

## Expected behavior

I would expect to see an error that says "You cannot break down by this property" or event "An unexpected error occurred", this empty state is really confusing.

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&actions=%5B%5D&interval=day&new_entity=%5B%5D&funnel_viz_type=steps&display=FunnelViz&breakdown=action_name&breakdown_type=event

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### LINKED ISSUE #5421: Extra arrow in property filters
## Bug description

Potentiall introduced in https://github.com/PostHog/posthog/pull/5384

Screen Shot 2021-08-02 at 5 25 54 PM

## Expected behavior

No extra arrow

## How to reproduce

1. View any filter
2.
3.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Two fixes in one

- [X] Fixes #5421
- [X] Fixes #5340 
    - [Test link to localhost funnel](http://localhost:8000/insights?insight=FUNNELS&filter_test_accounts=false&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24browser%22%2C%22value%22%3A%5B%22Chrome%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&actions=%5B%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22display%22%2C%22value%22%3A%5B%22asdfadsfads%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D&breakdown=%24screen_width&breakdown_type=event)

Screen Shot 2021-08-02 at 6 24 08 PM
Screen Shot 2021-08-02 at 6 24 01 PM
Screen Shot 2021-08-02 at 6 24 33 PM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by alexkim205** [comment]
Going to auto-merge this one bc the fix for https://github.com/PostHog/posthog/issues/5421 is fairly urgent.

**Comment by marcushyett-ph** [comment]
Thanks for this @alexkim205 its great. I appreciate this is already merged - but it'd be awesome if we could wrap this warning text in an <Alert> since it doesn't stand out very clearly right now.

Let me know if I should file a separate issue for this?

**Comment by alexkim205** [comment]
Hey @marcushyett-ph , sorry about the rushed merge, would've normally waited but the bug in our filters was pretty obvious—but thank you for the review. Could you clarify what you mean by wrapping in warning text? Would you like this to look like our "Add one more step" empty state with an icon and bigger text?

**Comment by marcushyett-ph** [comment]
No worries- fixing the bug was definitely more important...

The warning currently looks like this - but its not actually clear that it's a warning:

image

If it looked like this it would be clearer to a user that it's trying to warn them about something:

image

**Pull request merged**
