### PR TITLE
Toolbar Actions Flow

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Loads the actions/edit or actions/new part of the toolbar when clicking the "inspect element" links

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by mariusandra** [comment]
A not-related cypress test failed, so I clicked "re-run all jobs". Now all of them failed.

**Comment by mariusandra** [comment]
A not-related cypress test failed, so I clicked "re-run all jobs". Now all of them failed.

**Comment by EDsCODE** [comment]
Can you push another blank commit to trigger tests? When you try to rerun cypress action after a day it breaks

**Review by EDsCODE — COMMENTED** [review]
One UX confusion I found was that if the action isn't tied to the page that you're navigating to and you try to update it, it doesn't show up in the resulting saved actions which was confusing. I think clicking inspect action on the edit action page should take you directly to the action if we know where it is rather than allow you to choose a page.

It works great if I manually define the url that the action exists at and navigate there when editing

**Comment by mariusandra** [comment]
Good catch @EDsCODE ! I updated the toolbar to now just show all the actions in the list. Previously it only listed actions that were somehow related to the current page.

If an action is related to the current page should still be shown in the interface somehow, just not as the only filter that affects the list. For example I could split the actions into two lists... or add some icons. I think that should be outside of this PR.

**Review by EDsCODE — APPROVED** [review]

**Pull request merged**
