### PR TITLE
fix: refactor demo page to use timeout instead of interval

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem

When generating demo data we had used `setInterval` to poll the API every second to see if demo data was ready. For some unknown reason this interval caused issues with storybook on production only, which caused visual regression tests to all fail.

## Changes

Refactors the demo generating logic to use a timeout instead of an interval. This pattern is used elsewhere in the app so I'm hoping it's okay here 🤞 

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?\

Manually

### CODE REVIEW

**Review by thmsobrmlr — APPROVED** [review]
Awesome, that fixes it! The one failing test is unrelated and I'll look into it tomorrow. Thanks for the quick handling :)

**Comment by raquelmsmith** [comment]
Hooray!

**Comment by neilkakkar** [comment]
Generally, interval is terrible and you never want to use it.

I can't find the really-good-docs about it, but here's one crux: https://developer.mozilla.org/en-US/docs/Web/API/setInterval#ensure_that_execution_duration_is_shorter_than_interval_frequency

**Comment by raquelmsmith** [comment]
Good to know, thanks!

**Pull request merged**
