### PR TITLE
ci: Split Temporal backend suite into three

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

The Temporal suite is taking around 25 minutes to complete ([example](https://github.com/PostHog/posthog/actions/runs/11573832601/job/32219910639), not an unusual one). A 25 minute wait kills productivity.

## Changes

Splitting the suite into three groups.

### CODE REVIEW

**Review by Gilbert09 — APPROVED** [review]

**Comment by Twixes** [comment]
Looks like this didn't have as much of an effect, because the run time is _heavily_ skewed towards a few tests. Group 3 still takes 20 minutes. These tests are the biggest offenders, each taking over 60 seconds:
```
120.84s call    posthog/temporal/tests/batch_exports/test_snowflake_batch_export_workflow.py::test_snowflake_export_workflow_raises_error_on_copy_fail
105.78s call    posthog/temporal/tests/batch_exports/test_snowflake_batch_export_workflow.py::test_snowflake_export_workflow_raises_error_on_put_fail
61.24s call     posthog/temporal/tests/batch_exports/test_s3_batch_export_workflow.py::test_s3_export_workflow_with_request_timeouts[model0]
60.63s call     posthog/temporal/tests/batch_exports/test_s3_batch_export_workflow.py::test_s3_export_workflow_with_request_timeouts[None]
60.50s call     posthog/temporal/tests/batch_exports/test_s3_batch_export_workflow.py::test_s3_export_workflow_with_request_timeouts[model1]
60.07s call     posthog/temporal/tests/batch_exports/test_s3_batch_export_workflow.py::test_s3_multi_part_upload_raises_retryable_exception
```

**Comment by neilkakkar** [comment]
@Twixes I didn't care too much about the `.test_durations` file for temporal earlier because there was only one group, but now if you update that, this splitting should be more clever

**Comment by neilkakkar** [comment]
this is a good way to do it (vs running locally which can be annoying) -> https://github.com/PostHog/posthog/blob/master/.github/workflows/ci-backend-update-test-timing.yml#L43 

although iirc last time temporal failed for some reason, which is why I split them out in the first place. I think if you just try running temporal tests, might work here.

**Comment by Twixes** [comment]
@neilkakkar, yup, already updated .test_durations in [`09e878b` (#25880)](https://github.com/PostHog/posthog/pull/25880/commits/09e878bcbbde8367e6041f33100ec1d95b49a029), only `posthog/temporal/**/*` ones. So each Temporal group takes ~11 minutes now, rather than one taking ~25.

**Comment by neilkakkar** [comment]
ah missed that commit, perfect 👍

**Pull request merged**
