### PR TITLE
Plugins secret config fields

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

**Related issue:** #3082 

Submitting this as a WIP because there are a lot of ways one could approach this and I wanted to get feedback on the approach taken here. Happy to change directions hence submitting this early. 

Essentially, I wanted to add this with minimal impact to how things are currently handled, hence, this works as follows:

### Frontend
1. Adds a lock icon with a tooltip next to the name of secret fields to indicate and explain to users that these values are write-only
2. Let's a user update these fields as usual if they do not have a value yet
3. If a given field does have a value already, show it as `****************` for strings and `Secret Attachment` for attachments
4. Show a warning to the user the first time they try to update a secret value that is already set (but not visible to them)

### Backend
1. Never send secret values to the client
2. Substitute attachments with some default file specs and strings with `****************`
3. On an update call, attachments were already handled correctly, so that they wouldn't be overridden if there was no change. Updates to strings check that the value sent isn't a masked value (i.e. `****************`) before updating

### Screen Recording

https://user-images.githubusercontent.com/38760734/107965252-38026c00-6fa2-11eb-9328-45d3e738e3c4.mp4

### Screenshot 

Screenshot 2021-02-15 at 15 19 04

### Next

After validating the approach, still have to add some tests and smoothen out the edges.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Would love some feedback on the approach here @mariusandra

**Comment by mariusandra** [comment]
The approach is in the right direction! I want to dig a bit deeper if the `displayWarning` function is in the right place and if it's a good idea to use the `clonedNativeEvent` system. It feels overly complex somehow :).

The thing I'd change though is to show the `*****` as a placeholder in the input... and remove these special strings like `"Secret Attachment"` and code like `if (form.getFieldsValue()[key || ''] !== '****************') {`. Just from it being `secret: true` the interface should derive all the stuff, not by checking the value of the field.

I'll dig deeper when I get the change. Must go AFK now for a few hours...

**Comment by yakkomajuri** [comment]
So the reason for the placeholders is an easy (the easiest?) way to determine a few things:

- The config is secret 
- The config already has a value
- The user certainly wants to change the value

From the frontend only I cannot derive if the config already has a value, so the backend needs to send me some indication. The reason knowing if it has a value or not is important is because if I'm setting this up for the first time, I shouldn't feel afraid to play with the config, but if I'm modifying it, I may be overwriting someone else's work.

So now on the update side, when the form is submitted, I need to know if I should update this secret value or not. Given that the user doesn't know this value, if I have a placeholder, I just check that the value isn't a placeholder. However, if I don't, I need to tell the backend that this value was changed by the user, so we need to store that in the logic and handle it in the backend.

An example - let's say there's no placeholder and secret fields just get a value of `''`. When the backend receives `''` for that field, it doesn't know if the user just didn't mess with the secret config or actually wants it empty. 

So yeah, I also don't like the placeholders lying around and am definitely happy to change this up (hence I put this PR out early and raw), but I felt it was a simpler way of leveraging the existing logic without keeping track of secret fields having been messed with and then sending that to the backend alongside the new config.

**Comment by yakkomajuri** [comment]
side note that we ofc decisions shouldn't necessarily be made based on what's easiest/lowest impact on existing code. That was just my rationale here given the changing nature of our plugins feature

**Comment by Twixes** [comment]
IMO we should only do this with encryption of secrets. Users will be putting A LOT of trust into this system by giving us all the sensitive data, like crucial API keys. It's on the level of passwords. Should not be plain text.
Though I'm not sure how to store encryption keys, especially on infrastructurally limited self-hosted.

**Comment by yakkomajuri** [comment]
We could ask for their password when modifying a secret field and use that to encrypt the secret values?

**Comment by yakkomajuri** [comment]
I guess if we can handle this for Cloud, self-hosted is less of a problem given the data is not going to a third-party?

Definitely would be important to have a good solution here across the board, but just wondering about priorities.

**Comment by yakkomajuri** [comment]
Could we leverage Django's `SECRET_KEY` here maybe?

**Comment by mariusandra** [comment]
I'm not sure if encrypting these values makes sense. From who are we hiding them and how secure can we make this? The plugin server needs to be able to read the unencrypted values, and thus we will need to somehow store the encryption key together with the encrypted data, effectively rendering the encryption meaningless.

**Comment by yakkomajuri** [comment]
I was thinking the same - the plugin server will always have the plain text values anyway. But I guess we could leverage env vars if we wanted to do this? We then aren't storing a key with the data.

Just brainstorming really as I write really 🦆 

Secondary point is that indeed it's good to warn users of stuff + try to have plugins request as limited API keys as possible e.g. 'this only needs read-access to this type of record'

**Comment by Twixes** [comment]
We can't ask for password in the plugin server though… and on each event.
Basically something like Hashicorp Vault would be reasonably straightforward and secure, although that's something we can't run with `./bin/start` and it'd be a lot of complexity to only support it in EE.
We precisely should store the encryption key as far away from encrypted data as possible. Main intention is: if someone dumps our DB, users' secrets should be useless for them.
`SECRET_KEY` sounds like a solution actually. Both Django and plugin server can have access to it, and it's outside of the DB. Very unsophisticated solution, for better or worse.

**Comment by mariusandra** [comment]
I'd move the discussion on encrypting data at rest to a different issue. This PR already improves the situation immensely (your teammates can't see your github personal api key) and we should finish the last remaining things (api tests? something else) and get it in.

**Comment by yakkomajuri** [comment]
Will add API tests - agree that we can deal with the encryption side on a separate issue/PR. 

A symmetric encryption mechanism leveraging `SECRET_KEY` could be a quick way to improve security here.

**Comment by yakkomajuri** [comment]
This is ready for another (final?) pass @mariusandra

**Review by mariusandra — APPROVED** [review]
LGTM!

**Pull request merged**
