### PR TITLE
Change funnels API from GET to POST

### LINKED ISSUE #4554: Can't create really long funnels due to GET limitation
## Bug description

We've had a user create a funnel with Korean characters and 17 steps, which causes this issue:
image

## Expected behavior

We should send requests to api/insight/funnel using POST instead of GET.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Problem

Fixes #4554.

See discussion on PR #4561.

User created a long funnel (17 steps) which resulted in a request to `api/insight/funnel` that had a path longer than `4094` bytes. Gunicorn sets the default `limit_request_line` to `4094` to protect against DDOS attacks [[docs]](https://docs.gunicorn.org/en/stable/settings.html#limit-request-line), a bad request from the gunicorn layer was being propagated to the user. 

## Changes

- Change `api/insight/funnel` from GET to POST endpoint
- Refactor out util function to check for refresh flag

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [X] Django backend tests
- [ ] Jest frontend tests
- [X] Cypress end-to-end tests
- [X] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

## Testing

- All e2e tests pass
- Basic: Pulled down main repo and locally tested funnel functionality.
- EE: Pulled down [`posthog/posthog-cloud`](https://github.com/PostHog/posthog-cloud) and tested ee functionality.

### CODE REVIEW

**Comment by timgl** [comment]
@alexkim205 looks like legit test failures for e2e?

**Comment by alexkim205** [comment]
> @alexkim205 looks like legit test failures for e2e?

Ah good spot, it seemed to be running properly locally but will take another look at this.

**Comment by alexkim205** [comment]
fixing formatting and tests. Tests seem to be transient

**Comment by alexkim205** [comment]
Cypress tests that are failing are due to a known caching issue with our e2e tests. There's a previous run that passed before the last formatting change, so I'm going to merge this as I've tested that our changes work on cloud and local.

**Review by mariusandra — COMMENTED** [review]
✅ looks good

**Pull request merged**
