### PR TITLE
test(storybook): add more insight card examples

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

I need to manually check all the insight cards work when refactoring those.

## Changes

This PR adds an example for every visualization component possible in the `<InsightCard />`. 

Follow up: Ideally we'd unify the `VIEW_MAP` in `<InsightContainer />` with the `displayMap` in `<InsightCard  />` at some point.

## How did you test this code?

CI run / Storybook

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
HogQL has "Error loading data", which doesn't seem correct

**Comment by thmsobrmlr** [comment]
> HogQL has "Error loading data", which doesn't seem correct

Ah, I forget to write about that. The issue here is that InsightCard doesn't use cached results for the "SavedInsightGrid" placement, as only exported or shared insights do so: https://github.com/PostHog/posthog/blob/27630a7d799df1c7fedd12507bef695f2325b74b/frontend/src/lib/components/Cards/InsightCard/InsightCard.tsx#L561-L562
https://github.com/PostHog/posthog/blob/27630a7d799df1c7fedd12507bef695f2325b74b/frontend/src/lib/components/Cards/InsightCard/InsightCard.tsx#L607-L610

Since I don't understand why that is, I decided against changing it in this PR. The live versions work, as they simply make a call against the API (and the Storybook versions can't).

@pauldambra Do you have any hints on why the new query-based insights have these two checks in place instead of a singular `const isCached = !!insight.result`?

**Comment by pauldambra** [comment]
I don't remember... it might have been to give things names as I was figuring them out, or might be an artefact of the steps taken to figure it out 🙈

**Comment by thmsobrmlr** [comment]
Thanks for the quick help! Going to use the cached insight for all dashboard placements then.

**Review by Twixes — APPROVED** [review]
Looks good! Well, the insights that are in table form look a bit wonky, but in any case good to track this

**Pull request merged**
