### PR TITLE
Configurable table columns

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

see #1534 

* tidies up table config 
* puts it neatly behind a feature flag
* prepares for improvement of structure
* improves mobile display

## How did you test this code?

running locally by overriding the feature flag `posthog.feature_flags.override(['4141-event-columns'])` and with new unit tests

table-column-config

### CODE REVIEW

**Comment by clarkus** [comment]
I put together some quick ideas for how we might improve this feature at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4193%3A26630. It's mostly focused on scale and addressing a few other edge cases we might encounter. Happy to put in more iterations on this if you see any changes you'd like to make.

**Review by mariusandra — CHANGES_REQUESTED** [review]
Looks like a solid improvement, and could already be merged in since it's flagged. However I found some things to pick on... 😄  Comments inline. 

The only true "blocker" to get this in master behind a flag is the gap that's visible instead of the configuration button when the flag is off. Feel free to push the rest to another PR if it makes sense.

**Comment by pauldambra** [comment]
I _think_ I've addressed the comments and made some headway on the design...

**Review by mariusandra — COMMENTED** [review]
Almost there! 🎉 

- The only blocker: If I have default columns and nothing in the URL, things keep disappearing. This happens every time we make a request to reload events in the table below, but only if the "saved" setting is the default one:

- Long columns wrap badly in the "visible columns" section -> the checkbox goes on its own line
- Same for the "hidden columns" list, but I get the limits of the virtualized list. Perhaps still it would look better with a "..." in the end, and a tooltip showing the full title? Fine to keep and move on as well.
- Can you add a ['DEPRECATED' comment](https://posthog.com/handbook/engineering/schema-changes#avoid-deleting-django-model-fields) to `events_column_config` in `models/user.py`?

**Comment by pauldambra** [comment]
Ah, the long text display is an existing defect in PropertyKey I think (it was accidentally not working that way in the visible columns column because having `flex-grow: 0` on that was hiding it)

Screenshot 2021-10-12 at 21 03 28

Screenshot 2021-10-12 at 20 57 14

Definitely needs fixing but should be separate to this.  logged at #6396

**Review by mariusandra — CHANGES_REQUESTED** [review]
Found a sin in the react world, so sorry, going to have to ask for changes 😅🙏

**Comment by mariusandra** [comment]
Every time I read through this PR I have to fight the urge to scope creep it even further and replace those setStates... 🙃

**Review by mariusandra — CHANGES_REQUESTED** [review]
The mangling of different approaches (logics, react state, props not updating after already having mounted, etc) causes a lot of tiny quality issues, that I fear we will be squashing endlessly:



We can put this behind a flag and not release it, or I would really strongly suggest just going with the sunk cost fallacy and fixing this issue at its core. This means 1) strongly coupling "TableConfig" with "EventsTable", 2) moving the files themselves into scenes/events, 3) removing all props from the `TableConfig` component, 4) passing all data between logics directly, and not via the inefficient logic -> react -> useEffect -> logic loop, 5) rejoicing in how everything flows smoothly.

**Comment by pauldambra** [comment]
I think some of the quality issues are due to this branch being an old age pensioner now :) Have rebased against master to confirm.

**Comment by pauldambra** [comment]
I've not moved it into EventsTable... the dependency only points "down" now so there's nothing IMO stopping other tables using this

I _think_ it's better now :)

**Review by mariusandra — APPROVED** [review]
Well, LGTM! 👍

**Pull request merged**
