### PR TITLE
Historical export support for elements_hash

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

So I've been helping 2 customers migrate recently.

Customer 1 has all their elements in the elements column of the events table.

Customer 2 has events up to time _t_ in the elements column, and the rest in `posthog_element` and `posthog_elementgroup`. 

Customer 1 is covered. This PR adds support for users like Customer 2.

## How did you test this code?

Added test.

### CODE REVIEW

**Review by tiina303 — APPROVED** [review]
👍

**Comment by yakkomajuri** [comment]
@Twixes just wondering if you can skim this for any holes given you've worked with elements

**Comment by yakkomajuri** [comment]
friendly ping @Twixes

**Review by Twixes — APPROVED** [review]
This looks alright

**Pull request merged**
