### PR TITLE
Fix unselecting fields in action

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Previously if you un-selected a value and saved the action it would still be there. Fix that. Also add delete button in the edit itself.

image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Review by paolodamico — COMMENTED** [review]
A few UX comments,

- I think it's more intuitive to have the delete button at the top of the page, in line with the editing action title.
- Related to the above, it's a bit confusing when you click undo after deleting and you end up in the action list page but with the un-deleted action not shown.
- When unselecting a box, I think it would be best UX-wise to remove the content from the input to make it clear when you're unselecting that you're removing that condition (you would then need to store what was on the input so if the user re-selects the box again **before saving**, you can put it back).
    - Related to the above, I gave it a bit more thought and I'm thinking we can do this in a more intuitive way. Maybe we can drop the checkboxes altogether and instead add a clear button on the input (like you usually have on iOS)? Thoughts?

**Comment by paolodamico** [comment]
FYI, accidentally pushed a commit that should've gone on a different branch, rebased and forced push to clear it.

**Comment by timgl** [comment]
Agree re selection and done.

I also moved the delete button but less sure about that one. I copied the way we did it for feature flags originally which i think might work better
image

**Review by paolodamico — APPROVED** [review]
This is great, a bunch of logic gets simplified. Did a few minor styling tweaks and fix for actions to be reloaded after undoing delete.

Re delete button, I think is a fair point. While I think we need to give this a bit more thought, for now I kept both buttons and we can track which one users find more intuitive.

**Pull request merged**
