### PR TITLE
Remove yarn build cache in gitactions

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes
-
-

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
I thougth James G already did this? Looks good otherwise

**Comment by fuziontech** [comment]
I removed the cache for grabbing dependencies. This is for building the frontend dist artifacts. Is there a bug on building now too?

**Comment by EDsCODE** [comment]
Hmm I may have been misreading the errors on my PR. Let me double check what's happening

**Comment by EDsCODE** [comment]
There's an error on #1051 that was consistently happening in git actions but not locally so I thought it was a general error with building. Going to close

**Pull request closed without merging**
