### PR TITLE
By default disable async migrations auto rollback

### PR DESCRIPTION
**Pull request by tiina303**
## Changes

While we're manually working with users it's better if there are less side-effects happening automatically, we can always trigger the rollback from the UI (PRs coming) or even run the commands directly, but if we messed up somewhere with the migration the auto rollback action could make things worse.

Related: https://github.com/PostHog/product-internal/pull/243/files#diff-21c8bc166d8a8d6cc467f35fc487a0ab722e95deb594d5cc6b1342052c35d58fR64

## How did you test this code?

CI on Github

### CODE REVIEW

**Review by yakkomajuri — COMMENTED** [review]
not sure how I feel about this.

a lot of the pain we felt last week was very cloud-specific. self-hosted users should have as much of a hands-off experience as possible. I'd advocate for keeping the cloud default as disabled but auto rolling back on self hosted

**Comment by tiina303** [comment]
I'd personally feel much more comfortable manually testing with users if we didn't automatically rollback. Which is different from future state, where we likely do want auto rollbacks to be on, when ww have fully released it.

**Comment by yakkomajuri** [comment]
My worry is that with anything that takes more than 30sec, users might have moved onto other things and will not be aware of when this fails immediately (side idea: send an email). And the state of the DB without the rollback could be problematic. Rolling back feels like the safer option actually. 

Happy to get this in as a temp thing but I seriously think trying to rollback is safer.

**Comment by tiina303** [comment]
Sure now that we have the configs in the UI, when we work with people directly we can ask them to disable rollback first & it will be easy to do & they will also get exposure to the management UI.

**Pull request closed without merging**
