### PR TITLE
Saved insights filter & url sync

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Sync the filter with the URL for saved insights. 
- Refactor `utils.test.js` to `utils.test.ts`

## How did you test this code?

- Added tests for the new functionality

### CODE REVIEW

**Comment by mariusandra** [comment]
Added some improvements. Todo still:
- won't load insights on initial load
- tests

**Comment by mariusandra** [comment]
Seems to work well now... and has tests for the new stuff! Ready for a look.

**Review by Twixes — CHANGES_REQUESTED** [review]
This looks good to me, with one UX-y exception: could we put the tab in the pathname (e.g. `/saved_insights/favorites`) instead of hiding it in the middle of the query string (`&tab=favorites`)? That'd nicely connect the URL to the in-app navigation in a simple way

**Comment by mariusandra** [comment]
Hm, I could, but didn't we agree the URLs should be:

- `/insights` <-- saved insights
- `/insights/123` <-- a specific saved insight

In that pattern, adding `/insights/all`, `/insights/yours`, `/insights/favourites` will lead to annoying extra complexity in `scenes/sceneLogic.ts`, `scenes/urls.ts`, `insightLogic.ts` and `savedInsightsLogic.ts`. And what if we switch to `/insights/UUID`?

Love the UX simplification, but it's tricky to share paths like this between scenes. Can we merge as is?

**Comment by Twixes** [comment]
Hmm, I see what you mean with moving away from `saved_insights`. In this case I think we're good here for now.

**Pull request merged**
