### PR TITLE
Plugins via NPM

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Add support for:
- zip and tgz archives
- github and npm packages (give the npm url when installing a plugin)

Makes way for compiled plugins, as npm packages can contain built/compiled code that you wouldn't put into github (e.g. the `dist` folder)

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by mariusandra** [comment]
Happy to have someone review this now!

**Comment by mariusandra** [comment]
Damn it, something is breaking tests in production that didn't break locally. Will try to fix.

**Review by timgl — APPROVED** [review]
Tested and works fine. Obviously there's no indication on the frontend that you can add an npm url which confused me, but i assume you're thinking about the UX in another PR?

**Comment by mariusandra** [comment]
Yeah, I'd indeed like to redo this part in another PR.

These two boxes are also way too similar. I've twice had to do a double take to know which one to paste my URL to:

image

Adding a third NPM box (or just a line in the first box) brings even more challenges and I think we should rethink this "add plugin" part completely. Possibly as a two step form.

Thinking further, another interesting option we could add is "upload a zip". I imagine this can be useful for a 3rd party paid plugin ecosystem, similar to downloading wordpress themes from a marketplace. Who knows what other sources will we need to integrate with for EE customers?

Made an issue: #2251

**Comment by mariusandra** [comment]
Also, fun story. The tests were having an issue because:
- downloading a `.tgz` from npm and pulling out a file works fine locally and in the tests
- downloading a `.zip` from github and pulling out a file works fine locally and in the tests
- downloading a `.tgz` from github and pulling out a file works fine locally **but not in github actions**. It says the file is corrupt. In all versions of Python.

Luckily we only download `.zip`s from github and I had to add `.tgz`s for npm, so it all worked out 🤷 

This seems like a too deep rabbit hole to go into, so I'm glad to have dodged it for now.

**Pull request merged**
