### PR TITLE
Code snippets with proper syntax highlighting

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This replaces the abysmal mix of snippets with hard-coded or missing syntax highlighting with a proper general solution using [Prism](https://github.com/PrismJS/prism).

### Here's how this looks with the incredibly cool SynthWave '84 theme.

synthwave84-setup
synthwave84-autocapture
synthwave84-ios

### If that's a bit _too_ cool, can be switched to instead use the highly legible Accessibility Dark theme:

a11y-dark-setup
a11y-dark-autocapture
a11y-dark-ios

### CODE REVIEW

**Comment by timgl** [comment]
Hm, not massively in favour of this because of its massive bundle size: https://bundlephobia.com/result?p=react-syntax-highlighter@12.2.1

**Comment by Twixes** [comment]
Right, that'd be for the absolute whole bundle, but for this reason I opted for the lighter Prism instead of highlight.js + [an async build](https://github.com/react-syntax-highlighter/react-syntax-highlighter#async-build), so only the parts of Prism that are actually used should be included, resulting in a massively smaller bundle than what BundlePhobia shows.

**Comment by yakkomajuri** [comment]
Bundle size aside, option 1 ("cool") is too much for the eyes. I prefer the "milder" option 2, although some of its colors even could use a tone down in my view.

**Comment by Twixes** [comment]
Here are some alternative themes: https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/prism-async-light.html

**Comment by yakkomajuri** [comment]
I like vsc-dark-plus not because I think it's the "coolest" but because the color scheme is likely familiar to most people

**Comment by paolodamico** [comment]
I agree too on the more neutral version, and it's great that we're doing full syntax highlighting!

I would also consider doing something with a light theme like on the [new setup design](https://www.figma.com/file/gtW3o3VKYvf04ws8cZM3Nr/PostHog-Onboarding?node-id=3%3A320) (maybe with `prism` theme). For dark ones, I like `vsc-dark-plus` & `okaidia` as they seem fairly universal.

**Comment by Twixes** [comment]
Here's VSC Dark Plus:

vsc-dark-plus-ios

**Comment by yakkomajuri** [comment]
Hmm yeah, not "cool" but familiar. Also, unrelated to this, but the color scheme on the Objective-C import statement really bothers me... The same statement in C at least is highlighted differently by VSCode

**Comment by Twixes** [comment]
Yeah, every syntax highlighter does its own thing, so they're going to look different even with identical schemes.

**Comment by yakkomajuri** [comment]
Yeah I know, the bright blue "#" just bothers me hahaha but anyway, do we have any note on what the "practical/actual bundle size" will be? So we can choose to move to merging or close

**Comment by Twixes** [comment]
This is an extra 200kB when comparing app.posthog.com and posthog-react-syntax-hi-ge11oz.herokuapp.com.

**Comment by Twixes** [comment]
Hm, on second look, it seems to actually be way more, but also this is a development deployment, so can't say for sure. Will have to measure locally.

**Comment by Twixes** [comment]
I just realized [we're actually using Prism, and more precisely its `solarizedlight` theme, in the docs](https://github.com/PostHog/posthog.com/blob/f06ff2341d209218f3aab9a471cfa328110fcaa5/gatsby-browser.js#L13). It's kind of ugly in my opinion though. 😄  With this we could unify the style across the docs and the app, and maybe pick an elegant color scheme at that.

**Comment by Twixes** [comment]
Here's the current theme, selected with @yakkomajuri.

okaidia-snippet

I've confirmed with a production instance that this is only 70 kB more transfer (927 kB on this branch vs. 857 kB on master) on the Setup page, and 54 kB on pages without code snippets, so I think it's safe to merge!

**Pull request merged**
