### PR TITLE
Remove redis warning

### PR DESCRIPTION
**Pull request by timgl**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by mariusandra** [comment]
How come? People who have gotten this warning have had issues with their setup if I recall correctly... and we don't really know for how many people this has helped ensure their setup is legit, or do we?

**Comment by timgl** [comment]
I have seen a ton of instances where PostHog was working normally but people would consistently get this error, and has caused a ton of confusion. I spent some time a while ago trying to debug this but couldn't find a root cause. At this point, we can assume anyone installing PostHog will have a worker setup correctly. We can return this error message in the 'status'/debug page in #1812.

**Comment by mariusandra** [comment]
I get the point, as since if you don't have redis, events are not ingested and it's quite obvious something is broken. 

As a first change though I would have changed the `heartbeat > 90` to something like `heartbeat > 900` to see if that fixes the problem. If there's no ping in 15min, it's probably worth showing a warning sign with a link to the upcoming stats/debug page.

**Comment by yakkomajuri** [comment]
Yeah, it's a common and very annoying problem #1523. Increasing the time for the heartbeat check could be something.

**Comment by mariusandra** [comment]
Fine to remove it from my side.

Would be good to have an alert somewhere prominent once #1812 goes live and an issue is detected. Be it redis being down or "your database is getting too large for this instance".

**Pull request merged**
