### PR TITLE
chore: Optimize my_flags performance

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

The call to `my_flags` is pretty slow as it loads ~240 things for me.

## Changes

- keep less stuff in memory
- turn into a list once and use that
- use serializer once for the whole batch
- use generator expression to not keep another list

## How did you test this code?

- just tests
- check in browser network.. was a little faster
- not sure how to really test performance

### CODE REVIEW

**Comment by neilkakkar** [comment]
Hey @webjunkie 👋 , didn't realise this was getting slow.

I think only the toolbar uses `my_flags`, and it doesn't really need everything we're sending here, so you can optimise this much further by using the `MinimalFeatureFlagSerializer`:

(1) You wouldn't need to prefetch anything then
```
feature_flags: QuerySet[FeatureFlag] = FeatureFlag.objects.filter(
            team_id=self.team_id, deleted=False
        )
```

(2) You can serialize like so:

```
"flags": [
                  MinimalFeatureFlagSerializer(feature_flag, context=self.get_serializer_context()).data
                  for feature_flag in parsed_flags
              ],
```

**Comment by neilkakkar** [comment]
oh, also, you can check performance graphs in sentry: https://posthog.sentry.io/performance/posthog:b43f4fd4bddc40ab9256c7c951c53066/?project=1899813&query=&referrer=performance-transaction-summary&showTransactions=outlier&statsPeriod=14d&transaction=%2Fapi%2Fprojects%2F%7Bparent_lookup_team_id%7D%2Ffeature_flags%2Fmy_flags%2F&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29

So it seems like serializing is indeed the slowish bit, specially where it's getting tags for all flags 😮‍💨 , definitely unnecessary.

**Review by neilkakkar — APPROVED** [review]
excellent!

I'm hoping you've tried it with the toolbar locally, and all works well? :) (lmk if I should double check 🙈 )

**Comment by webjunkie** [comment]
The toolbar works for me... but maybe do a quick sanity check, not that I missed some case.

**Comment by neilkakkar** [comment]
yep all looks well 👍

**Pull request merged**
