### PR TITLE
feat(navigation): Add "Command palette" button

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

We have the command palette, much improved now with PostHog 3000, but still hard to find.

## Changes

~~This adds a direct "Command palette" button to the navbar.~~ Current version in a comment below.

Inspired by GitHub ([internal Slack thread](https://posthog.slack.com/archives/C064U4XCPHQ/p1706545528503299)):

Screenshot 2024-01-29 at 20 15 16

### CODE REVIEW

**Comment by corywatilo** [comment]
I don't love - feels a little cluttered. I wonder if we try a tooltip that explains Cmd + K for search, Cmd + Shift + K for command palette?

**Comment by Twixes** [comment]
Didn't love it either. Here's the simpler take on informing about commands:

Screenshot 2024-02-23 at 18 40 41

**Comment by Twixes** [comment]
I'm tempted to do "For all other inquiries, press [Cmd Shift H]" and then make that shortcut toggle hedgehog mode 😄 but will keep that for when we integrate a keyboard shortcuts system into the command palette

**Review by corywatilo — APPROVED** [review]

**Review by thmsobrmlr — APPROVED** [review]
👍

**Pull request merged**
