### PR TITLE
style(trends): World map polishes

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Resolving a few items from [project Oyster](https://github.com/orgs/PostHog/projects/44/views/1) (see Done section).

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Polish world map?
Screenshot 2022-04-11 at 09 17 11

**Comment by Twixes** [comment]
…

**Comment by Twixes** [comment]
🏓 @mariusandra I need this to un-feature-flag the feature.

**Review by mariusandra — APPROVED** [review]

**Comment by mariusandra** [comment]
Looks good, only the persons modals don't open...

**Comment by Twixes** [comment]
Works on machine. 🤔 The persons modal isn't supposed to open when clicking on countries that have no data (there's also no "Click to view countries" or `cursor: pointer` for them), is that maybe what you're seeing?

**Comment by mariusandra** [comment]
It's broken for me on the homepage map:

**Comment by Twixes** [comment]
Ah, so it does open, but with wrong results. This is quite bad and it _is_ an item in [project Oyster](https://github.com/orgs/PostHog/projects/44/views/1), but the problem is, this _seems_ to occur with ALL breakdowns – not just world map.

**Pull request merged**
