### PR TITLE
fix: floating uninstall button

### PR DESCRIPTION
**Pull request by Justicea83**
## Problem

https://github.com/PostHog/posthog/issues/18029

## Changes
1. Remove default relative position for Lemon buttons

## How did you test this code?
In the browser

Screenshot 2023-10-17 at 14 46 49

1. Navigate to `Browse Apps` > `Apps Management`
1. Shrink the screen to mobile size
1. Click on the humburger icon to reveal the sidebar
1. Ensure the Uninstall button isn't floating around.

### CODE REVIEW

**Comment by Justicea83** [comment]
Screenshot 2023-10-17 at 15 21 54

Not sure how this is related to the current changes, looking into the tests and not finding anything

**Comment by Justicea83** [comment]
@raquelmsmith can you help with the merging of this PR, if you like the changes?

**Comment by Justicea83** [comment]
@neilkakkar not sure if you can help me assign a reviewer.

I also want to ask, it there a process for asking for review in this repo. 
Check the `contributing` doc, didn't find such info

**Comment by raquelmsmith** [comment]
this should get thorough front-end review before it is merged as we have lots of buttons all over the place.

**Comment by Justicea83** [comment]
Alright sure, maybe we need a secondary testing organization like [Applause](https://www.applause.com/), to speed this up.

**Comment by Justicea83** [comment]
Meanwhile I will take a look at something else.

Thanks @raquelmsmith

**Comment by raquelmsmith** [comment]
> maybe we need a secondary testing organization like [Applause](https://www.applause.com/), to speed this up.

we have lots of visual regression tests so I'm not that concerned, just want to take a manual poke around to be extra sure :) will do that on monday!

**Review by Twixes — CHANGES_REQUESTED** [review]
Thank you for looking into this!

This is not the fix though. We need `position: relative` on `.LemonButton` e.g. for position of actions in `LemonButtonWithSideAction`. This also doesn't seem to actually fix the issue.

The real fix is removing the `.Plugins__Popconfirm` class, which has a problematic `z-index` that we no longer need.

**Comment by Twixes** [comment]
Hmm, I believe something went wrong when rebasing/merging, because there are many commits considered part of the diff, which already are in `master`

**Comment by Justicea83** [comment]
This PR is messed up, I'll close it out and open another one

**Pull request closed without merging**
