### PR TITLE
feat(onboarding): after inviting team, prompt to use bookmarklet

### LINKED ISSUE #12712: Onboarding V2: After inviting a technical user to help, prompt them to explore the product
**As a** non-technical user,
**I'd like to** be able to explore the product before the engineering team implements it,
**so that** I can figure out if it's the right solution for us.

### Details

We now ask if someone is technical at the beginning of onboarding. If they are not technical, they still should be able to explore PostHog to see if it's the right fit for them before they invite their team, or before their team has time to install it.

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem

Fixes #12712. 

We now ask if someone is technical at the beginning of onboarding. If they are not technical, they still should be able to explore PostHog to see if it's the right fit for them before they invite their team, or before their team has time to install it.

## Changes

After someone invites a team member, they are taken to an onboarding screen confirming that they have indeed invited someone, and giving them options for how to explore PostHog while they wait. 

For now, I've given them the option to use the bookmarklet or continue without ingesting any events. In coming days we will replace the bookmarklet with the option to import a demo project with demo data, but this at least gives people a couple options for now until we have that ready.

Nov-09-2022 14-21-30

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

There aren't any tests for the onboarding yet. We should add them. For now I just tested this manually by pressing all the buttons.

### CODE REVIEW

**Comment by raquelmsmith** [comment]
@kappa90 I'm not sure how to test this since my local setup doesn't have emailing enabled. Any suggestions?

**Comment by raquelmsmith** [comment]
Also I'm not sure what the CI failure means:

image

**Review by kappa90 — APPROVED** [review]
LGTM, the only problem is: this is going to affect the running experiment. Should we re-run it?

**Comment by kappa90** [comment]
> @kappa90 I'm not sure how to test this since my local setup doesn't have emailing enabled. Any suggestions?

We currently don't send any email, we just create invite links that you can share manually. For future improvement, we will want to send the emails ourselves.

**Comment by kappa90** [comment]
> Also I'm not sure what the CI failure means:
> 
> image

I think that's because you're trying to merge from a fork. Just open a branch on `posthog` directly.

**Comment by raquelmsmith** [comment]
Since I cant change the target branch I had to open a new PR https://github.com/PostHog/posthog/pull/12731

**Pull request closed without merging**
