### PR TITLE
fix(data-management): Make sure the page is called "Event Properties"

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

A user was confused because they needed to change the typing of a _person_ property, and our UI made them think the "Properties" page only applies to _event_ properties – when in reality there's no distinction in Data Management. (See ZEN-246)

## Changes

Made sure it says just "Properties" everywhere. Let me know if there are any other places where it says "Event Properties".

### CODE REVIEW

**Comment by alexkim205** [comment]
We actually explicitly call this "Event properties" because we don't support person properties (yet) in data management. 

Now that you mention it, Properties should be changed to Event properties in the tabs to make that clearer

Screen Shot 2022-07-26 at 11 51 23 AM

**Comment by Twixes** [comment]
Ah, I see, so it's the other way around. But then interestingly, the _event_ property definition IS in fact used by the taxonomic filter – i.e. if event property `createdAt` is typed as "DateTime", then filtering by person property `createdAt` will have the option to use datetime operators "before" and "after" (which only work for DateTime properties).

**Comment by Twixes** [comment]
So just to determine what to do with this PR, what's the plan for Data Management?

1. Will Event Properties be a separate page from Person Properties (in which case the quirk I mentioned in the comment above will be removed);
2. Or will they officially be renamed to Properties and existing Event Properties will be fully unified with Person Properties (in which case the quirk will be expected behavior)?

@alexkim205

**Comment by alexkim205** [comment]
> So just to determine what to do with this PR, what's the plan for Data Management?
> 
> 1. Will Event Properties be a separate page from Person Properties (in which case the quirk I mentioned in the comment above will be removed);
> 2. Or will they officially be renamed to Properties and existing Event Properties will be fully unified with Person Properties (in which case the quirk will be expected behavior)?
> 
> @alexkim205

I believe the best way would be 1 so that we don't introduce any weird quirks. I've pushed a change to address this for now

**Review by alexkim205 — APPROVED** [review]

**Pull request merged**
