### PR TITLE
feat(hogql): warnings and notices

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Searching for cohorts by string can lead to errors.

## Changes

Adds either a warning, notice or hint for this. Help choose which is the best. I left it as a hint for now.

- Warning
Screenshot 2023-06-19 at 15 07 56

- Info
Screenshot 2023-06-19 at 15 08 49

- Hint
Screenshot 2023-06-19 at 15 09 40

## How did you test this code?

Visually just for now.

### CODE REVIEW

**Comment by Twixes** [comment]
This feels like adding a feature that's deprecated right out of the gate, which is a bit funny. 😅 Though one way in which this would be _really_ useful is having a quick fix that'd swap out the string for the cohort ID + having hover tooltips for cohort IDs showing the name.

**Comment by mariusandra** [comment]
Why is it deprecated? I don't understand why is it better to search for cohorts by ID? Searching by name makes queries easier to read, at the expense of some in-team discipline. It might be a tradeoff you choose to make at times.

I'm thinking of further extending this, and adding a `info` tab and using that to 1) show the name of the cohort when it's an `id`, 2) show the type of each detected property, 3) etc

**Comment by Twixes** [comment]
No, I agree it's better to search by name, which is why I think this makes sense. By "deprecated" I mean that tongue-in-cheek, because the editor now says that cohorts by name are a "problem", which is maybe too strong of a word (but not sure if there's a weaker level in Monaco). The "quick fix" feature of Monaco/VS Code is really nice though, and in this way we could leverage the API so that you can immediately get the name swapped out for an ID – if that's what you want of course. (So effectively you could search by name, but save with an ID when done)

**Comment by mariusandra** [comment]
Other than errors, these three screenshots show the options available.

Definitely in favour of adding the quick fixes here to convert to numbers and back.

**Comment by thmsobrmlr** [comment]
My vote is for option 3 as a hint. And +1 to @Twixes suggestion to populate the "quick fixes" feature, though I don't know how complicated that is.

Some frontend checks are failing though.

**Comment by mariusandra** [comment]
Will this do the trick then?



Happy to accept suggestions for better error/warning messages.

**Comment by Twixes** [comment]
Makes sense, but things are red

**Review by thmsobrmlr — APPROVED** [review]
Just restarted a cypress test that flaked. Can go in once this passes.

**Comment by mariusandra** [comment]
Seems like a legit flake, as it failed 3x in a row and has something to do with HogQL 🤔

**Pull request merged**
