### PR TITLE
Saved insight fixes 3

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Fix saving insight name/description/tags.
- Refactor the inline editor component, but I don't know what to do with the "max width". It was set to 400px for both the edit and view modes, which was too little for long titles. Setting to 100% is not nice either. Dynamically based on content length?
image
image
image

- Remove the "add to dashboard" popup menu in the saved insights list. Will add it back once you can add an insight to multiple dashboards.
image

- Decided to defer the work to add an insight to multiple dashboards [due to complexities](https://github.com/PostHog/posthog/issues/6712). Deferred until next week.
- Changed the button when the chart is on a dashboard to look like this:
image
image

- Changed the "add to dashboard" modal to now be an edit modal which lets you change the dashboard if you edit an item. Again a temporary stop-gap to remove the previous bad interface for something that's at least correct, if not most user friendly.
image
image

- Add a "discard changes" button that reverts to the last saved state, not an empty state.

- Add better times to the tables
image

- Re-enabled the insight date range picker for "view" mode
- Boost for turbo mode when going from saved insights to insight, if the insight is already loadede.

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by mariusandra** [comment]
All right, another bunch of updates. After this PR goes in, what else still remains [from the insight joy-sparking list](https://github.com/PostHog/posthog/issues/6513#issuecomment-951870899), before we can release this flag to beta users on cloud? Currently it's just for the team, but we should start rolling it out and testing ASAP.

I'll already scope these outside of this saved insights flag release:
- Saving to multiple dashboards
- Making sure all graphs have the same empty/loading states
- Change the URL from `/saved_insights` to `/insights` (will do so if we fully release the feature)
- Insight table with adjustable columns

**Review by Twixes — CHANGES_REQUESTED** [review]
Found a few rough UI edges, not sure how many strictly from this PR, but I think we should fix all for rollout:

1. The star is wrapped awkwardly on mobile/tablet screens.
    Zrzut ekranu 2021-10-29 o 15 00 27

1. The profile picture is wrapped weirdly.
    Zrzut ekranu 2021-10-29 o 15 00 14

1. This arrow should always be on the left.
    Zrzut ekranu 2021-10-29 o 15 01 15

1. I'm not sure exactly what to do about this, but I found it awkward that the Title and Description fields _completely_ change form when starting to edit them – Description suddenly gets larger, while Title smaller. Honestly I think maybe a simpler flow would be making them always directly editable, since another slightly choppy experience is having to click "Done" and then still "Save" to actually remember the change.
    | Read | Edit |
    | --- | --- |
    |  Zrzut ekranu 2021-10-29 o 15 04 30 | Zrzut ekranu 2021-10-29 o 15 04 47 |

1. When in tag-adding mode (which BTW can't be exited), the input field suggests reusing the same tag that was put in last. However, actually doing that results in an error: 
    Zrzut ekranu 2021-10-29 o 15 03 49
    Zrzut ekranu 2021-10-29 o 15 03 53

1. The Discard tooltip is redundant + obscures confirmation.
    Zrzut ekranu 2021-10-29 o 15 08 39

1. On the topic of general Saved Insights polishes left, it doesn't make sense to show Your Insights with a Created by option. We should either drop the Your Insights tab, or remove Created by on it.
    Zrzut ekranu 2021-10-29 o 15 01 38

**Review by clarkus — APPROVED** [review]
I haven't been able to get my local instance running for a few days, so this review is based on the assets provided in the initial description. Things look good to me overall. 

> Refactor the inline editor component

I think setting to a default minimum width of 320–480px or so is fine. The fields can scale up as needed to contain content. The name and description fields shouldn't wrap below the page-level actions, though. 

> Changed the button when the chart is on a dashboard to look like this:

This might out-compete the other actions here, but what if we named the dashboard that is using the insight? "Used on dashboard Billing Metrics" for example.

**Comment by mariusandra** [comment]
@Twixes 
1. done
2. done
3. done
4. I'm not happy about those elements. They should be properly inline (no change to fonts, etc), possibly with [react-contenteditable](https://github.com/lovasoa/react-contenteditable). We might also need a better way to do this, as the logic of "editing it saves it in view mode, but editing it doesn't save it in edit mode until you explicitly click save" is also slightly unexpected. I'd do it outside this PR though
5. done. The error is still rather awkward when you add an existing tag, but at least it's not the default option
6. removed
7. removed the option, kept the tab

@clarkus 
1. This inline editing component is funny. it now looks more or less acceptable with a 640px max width and no min-width. I can only have the height expand dynamically, not the width. A true solution is to convert it to a seamless "content editable" experience, but let's do that after this PR.
2. The button might get too long if the name of the toolbar is on it. I just added a tooltip with it for now
image

Good to merge? What other things from [this list](https://github.com/PostHog/posthog/issues/6513#issuecomment-951870899) should we fix before this is good enough to start rolling out on cloud? CC @paolodamico

**Review by Twixes — APPROVED** [review]
My only tiny suggestion would be to rename this to "Discard changes" (it may not be completely clear that nothing beyond current changes will be discarded), but overall things LGTM!
Zrzut ekranu 2021-11-3 o 11 05 33

**Pull request merged**
