### PR TITLE
feat: add button to experiments to view recordings for a variant

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem

After I launch an experiment, the first thing I do is go watch recordings of people who were exposed to it - usually I'm more interested in the test variant, but sometimes I want to watch the default behavior too.

There is currently no way to get from experiment -> relevant recordings. 

## Changes

Adds a button to the results table to view recordings:

Arc 2024-11-07 05 56 06

This button shows up even if people don't use recordings. If they click it, they will just see a thing that says they don't have recordings enabled. This is intentional as it's good for our cross-sell AND because this is such a good flow for the user, to be able to see what people are doing with the experiment variants. 

Code review from:
- @pauldambra for replay filter creation (this seems so manual to do this - is there a better way?)
- @PostHog/team-experiments for placement in the experiments UI

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Ya

## How did you test this code?

It works locally.

### CODE REVIEW

**Comment by raquelmsmith** [comment]
> The buttons seem a bit prominent, though. What if the entry point was above the table next to "Explore results"?

I considered that but I think it's most common that people want to watch recordings for a specific variant (usually `test` but then later prob control as well) so having a single button doesn't work.

**Comment by danielbachhuber** [comment]
> I considered that but I think it's most common that people want to watch recordings for a specific variant (usually `test` but then later prob control as well) so having a single button doesn't work.

I was thinking the button could open some secondary element that allowed you to choose which variant you wanted to see (or potentially "all" or potentially some other set of recordings). Not a strong opinion, though.

**Comment by pauldambra** [comment]
@corywatilo has been pitching "preset" or "saved" filters in replay. I guess experiments, flags, "sessions triggered by your URL trigger config" could all be presets we offer too, so that, as well as having buttons like this in context, folk that visit replay directly can be prompted to use the system like this

**Review by pauldambra — APPROVED** [review]
LGTM

The filters are pretty big but we can tidy that up if/when we see folk using this. I think we'll be doing work on filtering in coming weeks so happy to sweep that all together

**Review by jurajmajerik — APPROVED** [review]
Looking good! A bit too prominent to my taste too, but we'll soon rebuild the results UI when we support multiple main metrics, so will think about how to refine this then. Great feature!

**Pull request merged**
