### PR TITLE
fix: update clickhouse-driver

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem

_**Note:** This is definitely outside of my wheelhouse 😄 but my local env wouldn't run and everyone else was done for the day, so I got this far in trying to figure it out before I decided to call it the end of the week. I figured I'd post what I found here so that someone else can pick it up next week, or tell me what a better fix is._

In attempting to upgrade to python@3.10 I ran into issues installing dependencies. Specifically:

```bash
Collecting clickhouse-driver==0.2.1
  Using cached clickhouse-driver-0.2.1.tar.gz (211 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /Users/raquelmsmith-ph/Sites/posthog/env/lib/python3.10/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      error in clickhouse-driver setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.4.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

_At this point I tried to just use python3.9 again and that didn't work any more either, not sure why._

I looked at the `clickhouse-driver` changelog and saw that this was fixed in v0.2.4: https://github.com/mymarilyn/clickhouse-driver/blob/master/CHANGELOG.md#024---2022-06-13

After updating the dependency I was able to install everything fine. Running the app surfaced an error with `client.substiture_params()` that I could make a guess with how to fix. But tests had lots of errors, most (all?) dealing with:

``` bash
        if isinstance(breakdown, str) or isinstance(breakdown, int):
            expression, _ = get_property_string_expr(
                table,
                str(breakdown),
>               escape_param(breakdown),
                column,
                allow_denormalized_props,
                materialised_table_column=materialised_table_column,
            )
E           TypeError: escape_param() missing 1 required positional argument: 'context'

posthog/models/property/util.py:581: TypeError
``` 

v0.2.3 required a `context` argument for the `escape_param()` function and it's not super obvious to me how to go about including this. 

I'm not sure if there is a better/simpler fix that doesn't involve updating this library. 

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by Twixes** [comment]
Hmm, 0.2.1 works on my machine. From your logs, it looks like `pip` is using the `setup.py` installation process. Do you have the `wheel` package installed? Try `pip install wheel`, because when looking at my logs, in place of `Preparing metadata (setup.py) ... error` I had `Building wheel for clickhouse-driver (setup.py) ... done` – this means `pip` used a pre-built distribution of the package (the wheel) instead of downloading the source and building locally with `setup.py`, which is preferred when possible.

**Comment by xvello** [comment]
@Twixes I have the same install error on my machine while rebuilding the venv with python@3.10 from homebrew:

```
± python --version
Python 3.10.10
± pip --version
pip 23.0 from /Users/xavier/git/posthog/venv/lib/python3.10/site-packages/pip (python 3.10)
```

The error persists after `pip install wheel`: 

```
± python3.10 -m venv venv
± source venv/bin/activate
± pip install wheel
Collecting wheel
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Installing collected packages: wheel
Successfully installed wheel-0.38.4
[...]
± pip install --prefer-binary -r requirements.txt
[...]
Collecting clickhouse-driver==0.2.1
  Using cached clickhouse-driver-0.2.1.tar.gz (211 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /Users/xavier/git/posthog/venv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      error in clickhouse-driver setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.4.*'
      [end of output]
```

**Comment by pauldambra** [comment]
That works for me too (even with --prefer-binary which I don't use and stood out as a difference)

Did you run the equivalent for your machine of `CFLAGS="-I /opt/homebrew/opt/openssl/include $(python3.10-config --includes)" LDFLAGS="-L /opt/homebrew/opt/openssl/lib" GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 pip install -r requirements.txt` 

@Twixes do you use `pyenv`? I do and am wondering if that's the difference

**Comment by Twixes** [comment]
Yeah, I haven't tried this without pyenv, so while I don't see _how_ that'd make a difference, I can't exclude it.

**Comment by xvello** [comment]
I just setup pyenv, it it indeed does work with python3.10 from pyenv: clickhouse-driver is installed from a wheel, while the published wheels don't match the python3.10 from brew.

We are still masking an issue by using the wheel though: our version of clickhouse-driver is not installable on 3.10 and needs updating, like our pinned version of aiohttp does not install on 3.11 and will need updating.

**Comment by thedeveloperr** [comment]
Faced same issue on fresh install on macOS with apple silicon with python3.10 from brew using pip.

The fix in draft PR works for me, I also came to github top update driver version in requirements.txt and opening a PR for it but found this draft.

**Comment by thedeveloperr** [comment]
> I just setup pyenv, it it indeed does work with python3.10 from pyenv

+1 works for me too.

**Comment by raquelmsmith** [comment]
Same, works for me with pyenv. Question then becomes - do we update the docs to use pyenv, or update the dependency so it works regardless?

**Review by Twixes — APPROVED** [review]
Looks good!

**Review by xvello — APPROVED** [review]
Tests pass fine with brew's python3.10, thanks a lot 🙇

**Pull request merged**
