### PR TITLE
feat(apps): rename `web.ts` to `site.ts`

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Part of https://github.com/PostHog/meta/issues/63

The filename `web.ts` for "web inject apps" isn't very memorable. It could easily be confused with `frontend.tsx`, which is the filename for sidebar apps. 

## Changes

Renames `web.ts` to `site.ts`, which is short for "PostHog Site Apps", and refers to apps that run on your site (through posthog-js).

The naming is still not final and up for 👍  /  👎

## How did you test this code?

Hoping CI goes green. Locally an app with `site.ts` instead of `web.ts` ran as expected.

### CODE REVIEW

**Comment by pauldambra** [comment]
So, we want someone to look at the names of the files and be able to understand what they're for?

`web` and `site` IMHO don't help because they leave you asking the question: "which site?"

Alongside "frontend": "your front end, my front end"?

A lot of other tools call them "tags" which would at least be familiar for people used to other similar tools.

Likely a problem we can't solve only with file names 🙉

Although `posthog-app-frontend.tsx` and `your-site.tsx` would probably be the shortest clearest step. But some text on the editor page between the tab header and the editor panel is probably the thing

Screenshot 2022-10-11 at 08 11 18

**Comment by mariusandra** [comment]
I agree none of this is perfect 😅, however now's the last reasonable moment to make any changes to this filename. 

### `web.ts`

The current `web.ts` was chosen randomly during the hackathon, and I now think `site.ts` is just a bit more clear than `web.ts`, with regards to describing where the code in the file runs. `web` can mean absolutely anything (`internet.ts` anyone?), while `site` scopes it down just a bit more in the right direction. You wouldn't call the posthog app a "site", would you?

My theory is that if we introduce the "[my sites](https://github.com/PostHog/posthog/issues/12181)" feature, the concept of a `site` will be *abundantly clear* within PostHog.

### `frontend.tsx`

This is more confusing, and I'd love to tackle it separately outside the scope of this PR. I did [consider `sidebar.tsx`](https://github.com/PostHog/meta/issues/63#issuecomment-1273368129) for a while, though I fear that might still be limiting (what if you want your app not in the sidebar, but under project settings? we might enable this one day).

**Comment by mariusandra** [comment]
Also,
- +1 for "some text on the editor page between the tab header and the editor panel is probably the thing".
- I think `posthog-app-frontend.tsx` and `your-site.tsx` are perhaps too explicit 🤔. "Omit needless words" and all that fluffy stuff.

**Comment by pauldambra** [comment]
> "Omit needless words" and all that fluffy stuff.

Yep... tension between "each idea once" and "fewest number of parts" is always hard to resolve :)

**Review by pauldambra — APPROVED** [review]
> My theory is that if we introduce the "https://github.com/PostHog/posthog/issues/12181" feature, the concept of a site will be abundantly clear within PostHog.

🚢

**Pull request merged**
