### PR TITLE
feat(data-management): person property definitions

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

We would like to [compare person properties numerically](https://github.com/PostHog/posthog/issues/11922), but we can't. All person properties are casted to strings.

## Changes

This adds a system to track person properties, similar to what we have for event properties.

It's still draft - no tests yet. Curious to hear if this is in line with the plans for the plugin server, and if this is the right place where one would place such a hook.

This would also be one of the last steps to moving away from loading all person property definitions into memory when the app loads.

## How did you test this code?

Locally the code ran and started creating properties on *each new user*.

image

### CODE REVIEW

**Comment by mariusandra** [comment]
Hmm... [looking at these lines](https://github.com/PostHog/posthog/blob/ee841edd1d48de6fe1f2b702ad02628edb6b7002/posthog/tasks/calculate_event_property_usage.py#L124-L137)... it seems like every time we calculate stats for "property query usage", we also create event property definitions for any person properties and group properties that we encounter. 

This makes me wonder if instead of a new model, I could reuse the `propertydefinition` model, and add flags "is_event_property", "is_person_property", "is_group_property" to each row 🤔

**Comment by timgl** [comment]
@mariusandra Just had a customer [ask about this again](https://posthog.slack.com/archives/C01HF5WHH4L/p1670868442802579) for dates. Any progress?

**Comment by mariusandra** [comment]
This has literally been the first open tab in by browser today, and we talked about it in the standup on Monday. I got a green light from the team to carry on with the approach in this PR, as it's super relevant for data exploration as well.

Coming this week is the best I can say now.

In data exploration, we would need to wrap every numeric person property with `toInt` unless this is in, such as `toInt(person.properties.anyInteger)`. Right now we also need to do this for event properties, but for them we already have the data/number/string data available, and can just plug that in.

**Comment by timgl** [comment]
Would this PR help with dates too?

**Comment by mariusandra** [comment]
This PR is a prerequisite for getting person property date filtering working.

I'd like to continue work on this, but get stuck in the "paralysis by analysis" stage. Which option should we go for?

`<Context>`

Currently all event and person properties get extracted to a string, when we query for them in ClickHouse. When we want to use these properties in filters (e.g. `properties.age > 18`), we are comparing a string, and hence must cast it to an `integer`, `datetime`, `float` or any of the other ClickHouse properties that would allow us to compare values.

The easiest way to do this is to know the type of the property beforehand, so that we could cast values automatically at query time, by e.g. using `JSONExtractInt` instead of `JSONExtractRaw` (or casting it some other way).

The good news is that we already track the type of each event property per team, but we don't do this for person and group properties.

If we add this tracking, then we can implement date (and number?) comparisons for person and group fields, and remove the explicit `toInt()` calls you currently need in HogQL.

`</Context>`

The PR until now tried to copy the structure of the event property type tracking for person properties, but there are a multiple ways we could do this:

1. This PR creates a new model `PersonPropertyDefinition(id, name, is_numerical, query_usage_30_days, property_type)` next to the existing `PropertyDefinition` (same structure), and writes data to it during ingestion. The problem: this won't support group property types, this adds another table, and this duplicates some code in the plugin server.

2. Edit the existing `PropertyDefinition` model, and add `property_kind = NULL | 'person' | 'group_1' | 'group_2' | ...` field, where `NULL` means event. Adjust plugin server to update the counts accordingly, and fix `calculate_event_property_usage` to not. Problems: migration to change indexes might be long running? Unintuitive to get that `NULL == 'event'`.

3. Create a new table to track everything but event properties.

4. Drop these tables and create ([magic](https://www.google.com/search?q=Clarke%27s+Third+Law)) clickhouse views that count the usage and type of properties, and use these to power all property filters. Drawbacks: queries on those views for each property filter usage might get too frequent (we'll need to fetch types every time we run a hogql query that accesses properties for example). We'll still need to provide users with a way to override property types as well.

5. When building a query, fetch the latest values for any property, and decide on the type then and there. Let the user override it during query time. Then use this information in the property filter `{type:'person',op: 'lessThan', typeOfValue: 'int', value: 18}`. Cons: more burden on the users, and more complicated HogQL like `toInt(person.properties.age) < 18`. 

What should we go for? Each of these is a few hours of work, so I'd be happy to get a rain check before starting. Option 2 seems like the sanest choice so far? Anything I'm missing?

**Comment by timgl** [comment]
Yeah 2. definitely makes the most sense to me. We can abstract the null = 'event' bit using a property on the django model to make it easier to work with, but it's definitely less duplication than the other options.

**Comment by mariusandra** [comment]
We had [a chat](https://posthog.slack.com/archives/C0368RPHLQH/p1671018722185839) about this internally (and in the standup today), and concluded that instead of a "quick fix" that we'll have to maintain again and again, @macobo will work on a proper analysis and fix for this next sprint (likely already in this long Christmas sprint).

**Pull request closed without merging**
