### PR TITLE
Correlation discovery experiment

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

I want to run an experiment to promote discovery of correlations. Right now I want to test my hypothesis that people don't know about correlations (they don't know there's an option to scroll down).

The experiment is successful if discoveries of correlations (and subsequent usage) goes up.

I'm using a toast to tell people there's more data below: (cc: @clarkus @paolodamico for thoughts on this). The idea isn't to come up with the best way to attract attention to correlations, but a way that just works, to confirm whether my hypothesis is correct or not. At that point, if need be, we can consider putting in some extra resources to solve this problem of discovery.
 
image

## How did you test this code?

use the toolbar to check what happens when test or control is selected. Confirm toast occurs only for `test` variant.

### CODE REVIEW

**Comment by clarkus** [comment]
Do our toasts have the capacity for a single inline action? If we could somehow include an action that scrolls to the top offset of the correlation tables, that'd give the user a click event to see correlation instead of a scroll... it's a minor change but one is much more powerful and immediate. 

Screen Shot 2022-01-07 at 9 51 54 AM

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4794%3A27646

**Comment by neilkakkar** [comment]
I was being too lazy. Great idea, will sort this out 👀 . Also, very pretty 😻

**Comment by paolodamico** [comment]
Love @clarkus's proposal! My feedback was going to be that the toast will probably not move the needle as it looks like just the typical request success (and we hardly ever read the content)

**Comment by neilkakkar** [comment]
Latest iteration: 
image


Getting the action inline was annoying, as I then have to somehow increase the width of the default toastcontainer, which would increase size of all toasts. Leaving it like this, unless big objections?

**Review by liyiy — APPROVED** [review]
let's ship this and iterate as needed 😸

**Comment by paolodamico** [comment]
If the experiment proves successful (which it looks like it might), though let's keep an eye out to make sure we don't drop funnel discoveries, let's implement @clarkus's before releasing to everyone

**Pull request merged**
