### PR TITLE
Configure mypy

### PR DESCRIPTION
**Pull request by hakib**
This PR adds some helpful mypy rules and makes the appropriate adjustments. 

- This PR does not make any functional changes.
- This PR does is not adding any typing other than what was necessary for the new rules to pass. 
- Some of the rules revealed possible bugs.

Feel free to take what you need or none at all!

### CODE REVIEW

**Comment by timgl** [comment]
@hakib This is awesome, thanks! Annoyingly a few merge conflicts but once that's fixed I'm keen to merge this.

**Comment by hakib** [comment]
That's great! Let me know if there is anything  I can do to help merge this.

**Comment by timgl** [comment]
@hakib There are a few conflicts that would be good to resolve? You can run `git fetch` and then `git rebase master` to rebase your branch on top of current master.

**Comment by hakib** [comment]
Rebased ans resolved the conflicts. There are still some mypy errors left.

**Comment by timgl** [comment]
Superseded by #562 to fix some of the outstanding errors

**Pull request closed without merging**
