### PR TITLE
fix: Docker build not detecting JS issues

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Somehow a faulty build got in due to a merge that didn't have conflicts.

## Changes

* Adds typescript checking as a sanity check in the docker image build

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Review by zlwaterfield — APPROVED** [review]

**Comment by benjackwhite** [comment]
This is harder than hoped. Getting tsc to run in the docker image requires a fair number of changes, many of which aren't super clear to me...

**Comment by zlwaterfield** [comment]
@benjackwhite can we have a CI check that runs the tsc before the deploy is started?

**Comment by benjackwhite** [comment]
> @benjackwhite can we have a CI check that runs the tsc before the deploy is started?

We can but again it slows everything down...

**Comment by zlwaterfield** [comment]
True, but better that requiring the branch to be up to date. 

@benjackwhite what if we only did it for the staging env? Since we build and deploy staging first that would make sure it never gets to production.

**Comment by benjackwhite** [comment]
> True, but better that requiring the branch to be up to date.
> 
> @benjackwhite what if we only did it for the staging env? Since we build and deploy staging first that would make sure it never gets to production.

Think you're misunderstanding the flow - we [build once here](https://github.com/PostHog/posthog/blob/master/.github/workflows/container-images-cd.yml). When that is done, the deploy starts (dev, then prod envs).

So the change would be to add the CI step _before_ the deploy one to validate things (which would be v. slow...)

**Comment by zlwaterfield** [comment]
Ah ok, thanks for the clarification.

**Pull request closed without merging**
