### PR TITLE
Do not create Kafka or mv tables on backup hosts during migrations

### PR DESCRIPTION
**Pull request by macobo**
This brings migrations logic more in-line with what's running on cloud

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by fuziontech** [comment]
I'd like to move away from this. I'd like to make it so that schema wise the cluster is homogenous. The only thing that is different on the clusters should be configs.

**Comment by macobo** [comment]
How are backup hosts handled then though on cloud? They do not have the MV tables in practice and every migration we do tries to re-add them?

**Comment by fuziontech** [comment]
Yeah well have to make sure schemas are synched between cluster nodes

**Comment by fuziontech** [comment]
Closing this based on our talks earlier. Feel free to reopen if you disagree!

**Pull request closed without merging**
