### PR TITLE
feat(hogql): add list expr

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

SQL syntax is more expressive than HogQL AST nodes for complex structures. Unfortunately `parse_select` and `parse_expr` (1) don't support list placeholders, (2) don't support optional siblings and (3) don't support nullable placeholders.

Examples:
1. `parse_select('SELECT {columns} FROM events', placeholders={"columns": [ast.Constant(value=1), ast.Constant(value=2)]})` (doesn't support list-type columns)
2. `parse_expr("max(steps) over (PARTITION BY aggregation_target {placeholder}) as max_steps", placeholders={"placeholder": ast.Field(chain=['some_col'])})` (doesn't support the placeholder sibling)
3. `parse_select('SELECT event FROM events WHERE {where}', placeholders={"where": None})`(doesn't support nullable placeholder)

## Changes

This PR introduces a `ast.ListExpr` node that can only be added manually to the parse tree and gets expanded to a list. It would be great to add sibling support to the parser for this as well.

### Alternatives

1. Construct the AST manually (without using `parse_select` or `parse_expr`).
2. Use f-strings that are then parsed. This would mean that we'd need to handle things like column names as strings instead of `ast.Field`s as long as possible.
3. Parse the SQL and then modify the AST.
4. `QueryAlternator.append_select`

## How did you test this code?

*Going to add test cases after feedback.*

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
> The third case is usually solved with a `placeholders={"where": ast.Constant(value=True)}`.

Do we actually need the error message for `None` values? Using the commit I just pushed, things like the example would just work without a workaround.

> However, yes, placeholders aren't supported everywhere. So far when there has been a new place we need them, we've added them to the grammar directly, with corresponding parser nodes in both the Python and C versions.

Does the `ListExpr` thing make sense? Or would I rather adapt the `SelectQuery` parser to handle both single- and list type inputs?

**Comment by Gilbert09** [comment]
> parse_select('SELECT {columns} FROM events', placeholders={"columns": [ast.Constant(value=1), ast.Constant(value=2)]}) (doesn't support list-type columns)

Out of interest, does using `ast.Array(exprs=[...])` work here as a placeholder instead of a raw python array?

> Does the ListExpr thing make sense? Or would I rather adapt the SelectQuery parser to handle both single- and list type placeholders?

I reckon adapting select query to handle array placeholders (either via raw python arrays, or via the `ast.Array` node) would be preferable than adding a `ListExpr`

**Comment by thmsobrmlr** [comment]
> > parse_select('SELECT {columns} FROM events', placeholders={"columns": [ast.Constant(value=1), ast.Constant(value=2)]}) (doesn't support list-type columns)
> 
> Out of interest, does using `ast.Array(exprs=[...])` work here as a placeholder instead of a raw python array?

`ast.Array`s are actual SQL arrays as in `SELECT [1,2]`.

**Review by mariusandra — COMMENTED** [review]
This does make sense. 

Should we think about limiting where the printer can expand the lists? Passing lists as function arguments can lead to errors, or worse security implications. Worse case, some S3 connection string gets nudged too far? Not sure... 🤷

How many places would need to change to manually allow lists? You'd probably just need to make the printer's `visit_list` throw, and swap out things like

```python
        group_by = [self.visit(column) for column in node.group_by] if node.group_by else None
```

with something lenient like:


```python
        group_by = self.visitList(node.group_by)
```

🤔

**Pull request closed without merging**
