### PR TITLE
Kea TypeGen

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

This PR supersedes #1176 and:

- adds `kea-typegen`
- updates some eslint/typescript config
- runs kea-typegen and writes 40 initial `*Type.ts` files 
- updates `userLogic.ts` & `userLogicType.ts` to be fully typed (removes all `any`s)

Here's the Making Of screencast for this PR:
https://www.youtube.com/watch?v=jGy-p9UxcBA

It's basically the only documentation that currently exists regarding `kea-typegen`. I strongly recommend watching it to get a better overview of what's in this PR and especially if you're going to add types to posthog logic yourself.

## Checklist

- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
A LOT of `*Type.ts`

**Comment by EDsCODE** [comment]
**EDIT:** I figured it out. needed to restart webpack otherwise the kea version wasn't up to date

~~Hmm my userlogic from the kea object still doesn't have a type:~~

This is at the bottom of userlogic.ts
Screen Shot 2020-07-28 at 9 44 53 AM

when i type a dummy object with the interface it works
Screen Shot 2020-07-28 at 9 45 21 AM

**Review by EDsCODE — APPROVED** [review]

**Comment by mariusandra** [comment]
Hmm, @EDsCODE just confirming you ran `yarn install` and have kea `v2.2.0.beta.N` installed?

**Comment by EDsCODE** [comment]
I do now haha (I edited the comment above)

**Pull request merged**
