### PR TITLE
Make funnel persons api call return values structure consistent with others

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Standardize the format of the results from the funnel persons call so I don't have to index it two different ways on the frontend

side note: personally I think for all persons calls the results should just be { people: [], count: x } instead of [{ people: [], count: x }] but maybe we're passing in other objects into the array that I haven't encountered 😄 

Screen Shot 2021-07-01 at 8 59 54 AM

Screen Shot 2021-07-01 at 9 00 22 AM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

**Review by neilkakkar — CHANGES_REQUESTED** [review]
Think you want to do this in the `funnel` method! (and then fix the tests that will break because of the change)

Makes sense otherwise 👍 .

**Comment by liyiy** [comment]
> Think you want to do this in the `funnel` method! (and then fix the tests that will break because of the change)
> 
> Makes sense otherwise 👍 .

Would I want to keep this for funnel trends too? :o 

Also I don't think there are tests testing the api call return values since everything's passing

**Comment by neilkakkar** [comment]
Nope, no need for trends (yet. Edit: no problemo if you do add it) - nothing exists there. And with my PR, I'll add it in for trends 👍 . Tests pass right now because not in the `funnel` call xD It's these tests: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/test/test_clickhouse_funnel_person.py

**Comment by liyiy** [comment]
> Nope, no need for trends (yet. Edit: no problemo if you do add it) - nothing exists there. And with my PR, I'll add it in for trends 👍 . Tests pass right now because not in the `funnel` call xD It's these tests: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/test/test_clickhouse_funnel_person.py

hahaha that makes sense, thank you neil!! I would def add it but my intel laptop comes on Friday so I don't actually have clickhouse running yet Dx

**Comment by neilkakkar** [comment]
The list inside `results` is annoying, but yeah, I guess convention is better than `person/funnel` being right and alone.

lol, I just updated the tests to find you've done it already xD

**Review by neilkakkar — APPROVED** [review]
Waiting for tests to pass

**Pull request merged**
