### PR TITLE
feat(hogql): inline hogql editor with autocomplete

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

The HogQL filter editor doesn't spark joy.

## Changes

Take it to Monaco

- Event source:
image
- Persons source:
image

## How did you test this code?

In the browser. CI will make snapshots.

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
Ohh that'll be amazing! Seems like there is some kind of import issue & tests aren't running right now.

**Comment by mariusandra** [comment]
> Ohh that'll be amazing! Seems like there is some kind of import issue & tests aren't running right now.

Hmm, yeah, something's up. Will check after lunch...

**Comment by mariusandra** [comment]
I believe everything is fixed now. Still some dark mode storybook screenshots to update.

**Review by benjackwhite — APPROVED** [review]
Looks good to me (although a lot of code areas I haven't had much to do with)

**Comment by mariusandra** [comment]
image

I don't know why, but there's a 2nd set of identical django tests that just block and won't run. One full set has already finished: 

image

... so I'm going to force merge this in.

**Pull request merged**
