### PR TITLE
feat: allow query flag with data exploration insight flag

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We want to be able to release "dashboard queries" separately from "data exploration insights"

## Changes

This allows that

## How did you test this code?

👀 locally

### CODE REVIEW

**Comment by mariusandra** [comment]
Still needs some massage

**Comment by pauldambra** [comment]
saved-insights-list

creating-a-json-view

**Comment by mariusandra** [comment]
It mostly works well... but then I found that you can't save a SQL query as something else later:



This is odd too:



🙃

**Review by mariusandra — APPROVED** [review]
Works for me 👍

**Pull request merged**
