### PR TITLE
Add option to delete feature flags

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

This started bugging me so I just decided to fix it. I then saw it was put up for Hacktoberfest #1144 but I was looking at my duplicate #1554 

Added a Cypress test for good measure but not sure how much that's worth these days 

Looks like this:

### Edit Flag 

Screenshot 2020-09-29 at 16 36 15

### Confirm Deletion Modal

Screenshot 2020-09-29 at 16 36 22

### Deleted 

Screenshot 2020-09-29 at 16 36 28

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Review by paolodamico — COMMENTED** [review]
Just a minor thing but it might be worth using the general delete workflow we have elsewhere which is actually deleting without confirmation and then offering an undo action for a few seconds after? Just making this point in the basis of consistency.

**Comment by yakkomajuri** [comment]
Can definitely implement that - the original thought was just that feature flags can power a lot of stuff so you should be certain when deleting them. But makes sense to me!

**Comment by paolodamico** [comment]
Oh agree! Maybe then do both? Confirmation and undo for a few seconds? Well on the other hand worst case scenario you just recreate another one with the same key.

**Comment by yakkomajuri** [comment]
Yeah that's true - not too bad of an outcome. I'll get to this tomorrow

**Comment by yakkomajuri** [comment]
Thanks @paolodamico for the feedback! Added the undo toast, but kept the modal. Happy to remove the modal if you think that's best.

Also, happy to add the modal to other areas where deleting something could benefit from a little friction. User data for example asks for confirmation but does so via a browser alert/confirm.

Will leave that for a separate PR though in the spirit of keeping PRs concise.

**Comment by yakkomajuri** [comment]
This has been lingering here but should be ready to go. Let's get it in before the code freeze @paolodamico @mariusandra ?

**Comment by mariusandra** [comment]
This broke cypress btw

image

**Comment by yakkomajuri** [comment]
Will fix!

**Comment by yakkomajuri** [comment]
The commit after I said it was ready removed the modal and hence broke the test. Will put out a PR to fix.

**Comment by mariusandra** [comment]
It's really annoying that we can't rely on cypress tests anymore. I only saw this myself since on my own PR I decided to check if I broke anything (in the 3 tests that were failing) and noticed this. Remembering this PR was just merged I decided to check and comment here. Lucky find I guess. Next time we might not be so lucky.

**Comment by yakkomajuri** [comment]
Indeed, we're so used to them failing that we merge when they do fail and then risk breaking more things

**Pull request merged**
