### PR TITLE
feat(insights): support 'any event' filter

### LINKED ISSUE #4332: Introduce "Any event" preset
## Is your feature request related to a problem?

Users coming in from different analytics tools have the expectation of having an "Any event" option. We default to "Pageviews" to serve this use case, however it's clearly not the same, plus particularly not useful if you're not tracking a website or have autocapture off.

## Describe the solution you'd like

I'd like us to have the concept of "Any event" where it matches everything for all insights. We would default to this option.

## Additional context

We have to analyze the technical feasibility of this. Might require some complex query building. CC @EDsCODE @buwilliams for input.

### LINKED ISSUE #10125: Wild card event in event selectors
## Is your feature request related to a problem?

We’re coming from Mixpanel and this Any Event wild card is very handy in multiple situation :
Computing WAU/MAU and compare app vs web since Web and App event are not necessarily the same
Checking App Version release % 
Not having to maintain a long action list , especially when new app versions introduce new events.

## Describe the solution you'd like
We'd like to be able to use a wildcard event in the event selector that would select any event. 

Screenshot 2022-06-02 at 17 55 40

## Describe alternatives you've considered

We've considered building an action that would contain all events but that would require to add any new event to it, which is not really something that scales well.

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Sometimes users want to query for "Any event".
Resolves #4332, resolves #10125.

## Changes

Makes it possible. 

- Now a `null` event filter will match all events.

image

- Removes the `NEW_ENTITY` entity type, leaving only `ACTIONS` and `EVENTS`. That was a bit of a hack and is no longer needed as we now support `null` (any) events.

- Adds support for the taxonomic filter to display both local and remote lists at the same time

## How did you test this code?

- Tested all the different insights in the browser
- Added a test for each insight that supports "any event"

### CODE REVIEW

**Comment by mariusandra** [comment]
The "any event" filter now works quite well now for all insights with the data exploration flag both enabled and disabled



There are still some open questions / issues:
- "Any event" is currently an event with the id `""` or `null`. 
- Does this make sense? Should we stick to just one of the two? `null` then?
- This PR deprecates an entity type `new_entity`. I could alternatively use `any_event` as its own property.
- Not a single test was ~~broken~~ added
- Also, this breaks the session recordings list

**Comment by thmsobrmlr** [comment]
Some fly-by comments, before I manage to do a full review:
- To me it would feel more natural if the font color for "Any event" would be the same as the other events. Did you leave it lighter by intention?
- It would be great if "Any event" could also be selected from the dropdown. Didn't understand that I have to click on the small "x" immediately.
- Typings for the EventNode need to be updated to include null

**Comment by mariusandra** [comment]
Ready for another look.

- I kept the "x", and also added "any event" as the first event in the list.
- The font for "any event" is now normal
- Updated the typing

To get this to work, I had to change even more files:

- The taxonomic filter can now show both local and remote data sources at the same time in the same list.
- `TaxonomicFilterValue` now can also be `null`
- Cypress failed, since with the removal of the "new entity" type, the "add graph series" button that adds a new row in trends and selects "any event" by default, won't automatically open the popup to let you select an event. I think it's fine. However we could default to adding `$pageview` and leave it at that.

**Comment by mariusandra** [comment]
There's one bug I know of: pressing "X" when you had selected an action causes a `null` action to be used instead of a `null` event. This breaks things.

**Review by thmsobrmlr — APPROVED** [review]
Nice! Seems like we should have supported the any event option a long time ago.

As a follow up I think having the event show up as "verified event" with the green icon or even as a special event with it's own icon would take this from A to A+. Might also be worth asking a native speaker regarding "Any event" and "All events".

**Comment by mariusandra** [comment]
The name "All events" seems more intuitive when using the interface, so renamed it:



I still found a bug with the event explorer and some other places:



will fix.

**Pull request merged**
