### PR TITLE
Timezone handling UX

### LINKED ISSUE #2778: Improve UX timezone support
## Is your feature request related to a problem?

When using PostHog, if you're particularly sensitive to specific time of day stuff, there's no clear indication of which timezone is being used. Further, there's some suspicion that we might be mixing timezones in different parts of the app.

## Describe the solution you'd like

Ideally we would allow each user to set their preferred timezone (maybe on the org, project or user level; open to discussion), and then for each time in the app we would do something like Stripe does (see screenshot below). The UTC conversion is relevant for our more technical users who may be using it to compare stuff with other data sources.

## Describe alternatives you've considered

Just allowing the selection of a timezone for each user and showing datetimes only in that timezone.

## Additional context

- Related to #2676.
- Came from a [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.jc9thlt4k0t7)

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- This PR closes #2778.
- Introduces a `timezone` attribute on projects (`Team`s) that allows configuring a specific timezone for each project. Defaults to UTC.
- Any static timestamp is now shown through the `TZLabel` component, which shows a conversion to all relevant timezones.
    
- We now show an indicator in insights and dashboards that all calculations are done in UTC.
    
    

- Tangential. Refactors `renameCurrentTeam` to use the already existing `patchCurrentTeam` method and show relevant toast message.

## Checklist

- [X] All querysets/queries filter by Organization, by Team, and by User
- [X] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by paolodamico** [comment]
Ready for review. As a follow-up improvement, we should use the same project timezone to compute all queries (instead of defaulting to UTC).

**Comment by paolodamico** [comment]
Thanks for the improvements! Are we good to merge here?

**Review by Twixes — APPROVED** [review]
Looks great for me. Just made the UI a bit nicer in a few places.

helper
settings

**Comment by paolodamico** [comment]
Thanks @Twixes, looks good! Merging

**Pull request merged**
