### PR TITLE
feat: 7 day free trial on cloud

### PR DESCRIPTION
**Pull request by timgl**
## Problem

We want to give people a 7 day free trial of all features on cloud

## Changes

In combination with https://github.com/PostHog/posthog-cloud/pull/204. Doesn't matter which order this gets merged in.

TODO:
- Show more clearly in the interface that a free trial is happening
  - banner (if "no events ingested" isn't showing)
  - In the dropdown menu top right
- Improve the 'trial expired' alert (better styling, dismissible etc)

image
image

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by kappa90** [comment]
I think the second screenshot shows uncommitted code, or I'm missing something?

I can't find anywhere in this branch nor in the other PR, the banner with this copy:

`Your free trial has expired. To continue using all features, add your card details.`

**Comment by kappa90** [comment]
@clarkus can we loop on this to define the UI for a top banner and how to display that a trial is ongoing/expired in the top right menu?

I'd love to redo the billing page to match the pricing one on the website, as we discussed, but I think that's out of scope now.

**Comment by timgl** [comment]
> I think the second screenshot shows uncommitted code, or I'm missing something?

Oops! Committed now

**Comment by joethreepwood** [comment]
> image

It feels like this would be more impactful if we were communicating to users specifically what they'll be losing when they drop from a free trial. Clustering all of this into a product prompt may be tricky. Maybe we link out to a landing page which summarizes what's lost and why users should upgrade, offer persuasive content such as case studies and/or get some feedback from them. 

Happy to spin something like this up if useful?

Also, we're currently missing a space after the comma.

**Comment by clarkus** [comment]
Those stacked banners displace most of the interface that users will actively trying to use during the trial. I'd advocate for the [site-wide banner component](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5251%3A32136) introduced during the last IA update. In this example it's showing an update announcement but it could easily be used for the trial messaging. The reasoning is that it has less of an impact in terms of displacing other content. 

Screen Shot 2022-07-19 at 7 53 11 AM

I'll need a bit more information on how the trial actually works before I can do much more here. We don't really charge for specific features - we mostly bill based on usage. The presence of payment information is what typically gates access to the "paid" stuff. Is the goal to show the time remaining in the trial? Do we need to have it in both the banner and the menu? If the banner doesn't dismiss until the trial ends, we could encapsulate this into a single component and simplify the work. If we want dismissible banners, then injecting it into the menu adjacent to the billing item might make sense. 

Have you thought about which roles are exposed to this prompt? Should it be any project / org member, or just those with admin rights?

**Comment by timgl** [comment]
> I'll need a bit more information on how the trial actually works before I can do much more here. We don't really charge for specific features - we mostly bill based on usage. The presence of payment information is what typically gates access to the "paid" stuff. 

The idea is that even if you haven't put billing information in we'll give you access to these features for free for 7 days so you get used to them and it's more painful when you then lose them.

> Is the goal to show the time remaining in the trial? Do we need to have it in both the banner and the menu? If the banner doesn't dismiss until the trial ends, we could encapsulate this into a single component and simplify the work. If we want dismissible banners, then injecting it into the menu adjacent to the billing item might make sense.

I don't have a strong opinion here

> Have you thought about which roles are exposed to this prompt? Should it be any project / org member, or just those with admin rights?

Everyone, as we're not sure who actually holds the credit card.

**Comment by clarkus** [comment]
Should we include any language about charging based on usage? Users might be more willing to enter payment details if they understand how billing works. Just saying that entering payment details doesn't automatically mean the account will be charged.

**Comment by timgl** [comment]
> Should we include any language about charging based on usage? Users might be more willing to enter payment details if they understand how billing works. Just saying that entering payment details doesn't automatically mean the account will be charged.

Yep definitely. I tried this a little bit but would love more suggestions

**Comment by clarkus** [comment]
https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=11992:55263#230861971

Screen Shot 2022-07-19 at 8 36 56 AM

@joethreepwood let me know if you have any improvements for this copy. I just went for the basic stuff.

**Comment by clarkus** [comment]
> Yep definitely. I tried this a little bit but would love more suggestions

I feel like describing this in detail on the billing page might be best. It's a bit more long-form content and it really depends on your plan / hosting. There are some adjacent designs in that project that are in progress but try to communicate some of this information. It just feels hard to fit into a banner component. 

billing   usage

**Comment by joethreepwood** [comment]
@clarkus I'll update some copy ideas on the Figma. 

An alternative idea I've been considering is: What if, instead of limiting access after 7 days, users can only claim the free 1m monthly events if they enter payment info in the first seven days? 

Just feels a bit more carrot than stick.

**Comment by joethreepwood** [comment]
> @clarkus I'll update some copy ideas on the Figma.
> 
> An alternative idea I've been considering is: What if, instead of limiting access after 7 days, users can only claim the free 1m monthly events if they enter payment info in the first seven days?
> 
> Just feels a bit more carrot than stick.

Discussed this idea in more detail with Marcus and it's _probably_ a less good idea.

Marcus did raise the idea, which I like, of updating the modal based on the users' activities however. We could consider subtly directing them to premium features, then using the banner to make it clear that they'll lose access unless they enter a card.

**Comment by clarkus** [comment]
Makes sense. I do think we could pull in more of the content from https://github.com/PostHog/posthog.com/issues/3797. Specifically that the first 1M events are free each month for select plans. The key thing is for users to know that entering payment details doesn't automatically equate to a recurring bill. It's really a low risk thing depending on their usage. Plus if we introduce usage caps in the billing feature, there's a lot of options available to the user to control their spend on this.

**Comment by joethreepwood** [comment]
What would you think about a message such as the below and which then sent users to a separate page where we accept the billing information and fully explain 1) what the premium features are and 2) that they may not actually get a bill anyway because 3) 1m events free each month? 

**Day 1 message:**
Welcome to PostHog! We've given you access to all premium features for [X] days. Find out more!

**Day X message:**
Your trial of premium features ends in [X] day(s). Find out how to unlock them forever.

**Expiry message:** 
You're on a limited plan. Find out how to get premium features back and get 1m events free each month.

The issue otherwise is that trying to say: 
- You've got all features for X days
- But this isn't a trial and you can continue to use PostHog afterwards
- You need to enter payment info
- This doesn't mean you'll be billed
- And you get 1M events free each month

Is a lot to cram in one sentence, and also doesn't address the point that users may not know which features are premium anyway.

**Comment by kappa90** [comment]
I refactored the billing alerts following your suggestions, feedbacks are welcome!

Notes:
- The trial CTA sends to `/organization/billing`, which currently doesn't give much information about the plans. I want to improve the billing page following @clarkus designs.
- I think we need to add information about the trial and the different plans during the onboarding, so one can choose to start the trial or subscribe directly.
- There is a design problem when both a billing alert and an announcement are triggered (see last screenshots)
- I trimmed @joethreepwood 's copy suggestions a bit to make them fit in the bar, but please tell me if anything looks wrong.

Trial started:
Screenshot 2022-07-26 at 10 22 53

Trial ongoing:
Screenshot 2022-07-26 at 10 23 09

Trial ending:
Screenshot 2022-07-26 at 10 23 19

Trial has ended:
Screenshot 2022-07-26 at 10 24 09

Billing information is missing:
Screenshot 2022-07-26 at 10 26 42

Usage limit warning:
Screenshot 2022-07-26 at 10 27 06

Usage limit exceeded alert:
Screenshot 2022-07-26 at 10 29 16

Potential design problem:
Screenshot 2022-07-26 at 10 30 55

**Comment by clarkus** [comment]
> There is a design problem when both a billing alert and an announcement are triggered (see last screenshots)

We should only show one global banner at a time. Ideally the trial would take priority over other alerts. Feature updates might be best communicate via another component in the future (in-app messaging and notifications for example).

**Comment by kappa90** [comment]
I'm extracting the alerts redesign in a different PR, as we're not going to release the trial for now.

**Comment by timgl** [comment]
Won't merge this now

**Pull request closed without merging**
