### PR TITLE
ci(docker): Fix Docker image test job on forks

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

PR check "Test Docker image build" is failing on PRs from forks. See https://github.com/PostHog/posthog/pull/10975#issuecomment-1195511287.

## Changes

Trying to fix it.

### CODE REVIEW

**Comment by Twixes** [comment]
I'm a bit stumped by this so asked a question in GitHub's forums: https://github.com/community/community/discussions/27348

**Comment by arunjagadishsd** [comment]
> I'm a bit stumped by this so asked a question in GitHub's forums: [community/community#27348](https://github.com/orgs/community/discussions/27348)

@Twixes can we make this ready for review even without this PR check passing ?
https://github.com/PostHog/posthog/runs/7543230598?check_suite_focus=true

**Comment by gitstart** [comment]
> I'm a bit stumped by this so asked a question in GitHub's forums: [community/community#27348](https://github.com/orgs/community/discussions/27348)

Hey @Twixes can this PR be made ready for review without this [PR check](https://github.com/PostHog/posthog/runs/7543230598?check_suite_focus=true) passing ?

**Comment by Twixes** [comment]
We should be good to go now, thanks to using GitHub Actions artifacts instead of GitHub Container Registry! Thanks @hazzadous for doing the heavy lifting in https://github.com/PostHog/posthog/pull/11262

**Pull request merged**
