### PR TITLE
feat(sampling): move fastmax toggle and sync with insight filters

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Problem

#12908 

## Changes

Toggling fast mode now syncs with the insight filters i.e. it will highlight the 10%

Also moved it to the insight pages only rather than the top bar as that's really the only scene where it's relevant. If we later do experiments support/saved insights and all we can reconsider.

Screenshot 2023-03-06 at 16 50 37

## How did you test this code?

Manually

### CODE REVIEW

**Review by lharries — APPROVED** [review]
Agreed on the new UX (haven't dived into the code or run it locally)

**Comment by yakkomajuri** [comment]
very confused as to how I broke the entire frontend suite with this change? any thoughts @pauldambra ?

**Comment by pauldambra** [comment]
@yakkomajuri looks like you need to run `pnpm schema:build` and commit the results

Oh, wait?! You didn't change schema.ts

**Comment by yakkomajuri** [comment]
🤷

**Pull request merged**
