### PR TITLE
Use separated session recording endpoints

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Change frontend to use new endpoints created here - https://github.com/PostHog/posthog/pull/6563

Also fixes a few bugs
- [x] continues playing at the end of the recording.
- [x] jumping to buffering part of code shows recording still playing. 
- [x] use kea-window-values plugin
- [x] don't use isTouchDevice() check. Listen to all mouse/touch events on all devices for better compatibility.  

## How did you test this code?

* Add new logic tests for meta data endpoint
* Add edge case tests for fetching both meta and snapshots

### CODE REVIEW

**Comment by alexkim205** [comment]
@rcmarron Ready for review!

**Review by rcmarron — DISMISSED** [review]
This is great! Starting to see it come alive!

Outside of the comments - a couple of small bugs:
* If you throttle the network and let the player reach the last buffered point, it pauses, but the screen doesn't change to a "buffering" state. And then when more of the recording loads in, it remains paused.
* I can't consistently repro this, but sometime when the recording loads, the buffering sign doesn't go away, so it's always buffering. The video below shows it happening (although probably not too useful for figuring out what's happening...)

https://user-images.githubusercontent.com/4813045/138988447-bb8b0bcf-02dc-45c0-b324-468f69fa2f4b.mov

**Comment by alexkim205** [comment]
Thanks for the review :)

1. Fixed that first bug.
2. That 2nd buffering bug is super weird. It looks like it loaded the recording but the last buffered time didn't update. I can't seem to reproduce this either, but have you noticed it happening on shorter recordings with inactivity skipping?

**Review by rcmarron — CHANGES_REQUESTED** [review]
Looks like there may still be an issue with that pesky analytics event... otherwise looks good!

**Review by rcmarron — APPROVED** [review]
LGTM

**Pull request merged**
