### PR TITLE
chore: add bulk mode to plugin config update management command for inlining

### PR DESCRIPTION
**Pull request by oliverb123**
The user agent is used by hundreds of configs, so I added a bulk mode to the update command.

### CODE REVIEW

**Review by benjackwhite — DISMISSED** [review]
Nit but I would make a different var "old_plugin_id" and that way it is really clear. Weird that you would specify config_ids but actually its "configs that use this old_plugin_id"

**Comment by oliverb123** [comment]
@benjackwhite You mean add a new argument to the command or just a new variable in the code?

**Comment by oliverb123** [comment]
@benjackwhite made the command args a bit more general to indicate how things behave differently based on mode, is that alright?

**Review by benjackwhite — APPROVED** [review]
Still prefer my suggestion but this is small enough that I'm certainly not gonna block 😅

**Pull request merged**
