### PR TITLE
Revert "dev(react): add react hook eslint rules, as warnings"

### PR DESCRIPTION
**Pull request by mariusandra**
Reverts PostHog/posthog#6571 and closes https://github.com/PostHog/posthog/pull/6698

### CODE REVIEW

**Comment by mariusandra** [comment]
Let's at least revert these. We can leave the [other PR](https://github.com/PostHog/posthog/pull/6576/files) with `eslint-disable` comments merged as is, or decide to revert as well, I'm fine either way. However this will already just remove the github warnings.

**Comment by hazzadous** [comment]
@mariusandra thanks, I did try doing this before as mentioned in the previous PR comments: https://github.com/PostHog/posthog/pull/6698

e.g. eslint was failing because it doesn't recognise the disables. I have the other PR linked in that PR, but it had a lot of changes so I wanted to get something less risky in.

What do you suggest we do?

**Comment by hazzadous** [comment]
Perhaps just a find and replace would have been better than the revert of the comment additions, that seems pretty easy

**Review by hazzadous — APPROVED** [review]
Just need to find and replace the disable comments to get the eslint check passing?

**Comment by mariusandra** [comment]
Indeed, that did the trick and was quite painless. Thanks for the quick ✅

**Comment by hazzadous** [comment]
🙏 :sorry:

**Pull request merged**
