### PR TITLE
Add checks for non-null migrations

### PR DESCRIPTION
**Pull request by timgl**
## Changes

based on https://github.com/PostHog/post-mortem/pull/9, add a check that fails if you add a non-null migration

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by yakkomajuri — APPROVED** [review]
lgtm

thanks for adding

**Comment by Twixes** [comment]
This seems like _too_ strict of a regulation IMO. Adding a non-None-default field to `Organization` is not going to be a problem. Adding one on `Person` or `Event` will be.

**Comment by yakkomajuri** [comment]
Well I'm happy to postpone this decision for when this test fails and someone has a legitimate reason for having a non-null column - should be easy to change then @Twixes

**Comment by timgl** [comment]
> This seems like too strict of a regulation IMO. Adding a non-None-default field to Organization is not going to be a problem. Adding one on Person or Event will be.

I don't think it's worth the risk. For example Actions seems like a table it would be safe to do on, but they are called on ingestion so would actually drag ingestion down.

I think it's easy enough to work around this that we should try this. If we come across a case where we _really_ need a non-null column we can have that discussion.

**Pull request merged**
