### PR TITLE
Introduce NGINX in front of our web workers

### PR DESCRIPTION
**Pull request by fuziontech**
This will reduce some of the burden of serving static assets and decouple the app processes from the request being received. It will also let us split out the `/capture` endpoint if we need to, bypassing gunicorn and django entirely.

The main thing is it shortens the path from client -> gunicorn to nginx on localhost -> gunicorn. For large payloads and a slow connection this can tie up a gunicorn process for a long time reducing the number of requests gunicorn can handle. NGINX can handle a lot more of these simultaneously than gunicorn.

Some other improvements is caching of files before serving. NGINX will cache images, css, and js payloads in memory speeding up delivery.

>the Heroku router engages the dyno during the entire body transfer –from the client to dyno. For applications servers with blocking I/O, the latency per request will be degraded by the content transfer. By using NGINX in front of the application server, we can eliminate a great deal of transfer time from the application server. In addition to making request body transfers more efficient, all other I/O should be improved since the application server need only communicate with a UNIX socket on localhost. Basically, for webservers that are not designed for efficient, non-blocking I/O, we will benefit from having NGINX to handle all I/O operations.

### CODE REVIEW

**Comment by timgl** [comment]
Just for future reference, why are we making this move?

**Comment by fuziontech** [comment]
This will reduce some of the burden of serving static assets and decouple the app processes from the request being received. It will also let us split out the `/capture` endpoint if we need to, bypassing gunicorn and django entirely.

The main thing is it shortens the path from client -> gunicorn to nginx on localhost -> gunicorn. For large payloads and a slow connection this can tie up a gunicorn process for a long time reducing the number of requests gunicorn can handle. NGINX can handle a lot more of these simultaneously than gunicorn.

Some other improvements is caching of files before serving. NGINX will cache images, css, and js payloads in memory speeding up delivery.

>the Heroku router engages the dyno during the entire body transfer –from the client to dyno. For applications servers with blocking I/O, the latency per request will be degraded by the content transfer. By using NGINX in front of the application server, we can eliminate a great deal of transfer time from the application server. In addition to making request body transfers more efficient, all other I/O should be improved since the application server need only communicate with a UNIX socket on localhost. Basically, for webservers that are not designed for efficient, non-blocking I/O, we will benefit from having NGINX to handle all I/O operations.

**Comment by Twixes** [comment]
So same as #2209, this is a Heroku optimization and has been in draft state for a while. With Cloud being off Heroku, do we want to merge this for self-hosting users?

**Comment by mariusandra** [comment]
I'd say let's keep the setup simple and close this. IIRC this was a nice to have fix that won't make much difference in the end anyway.

**Pull request closed without merging**
