### PR TITLE
fix(dashboard): remove breakdown limit in `apply_dashboard_filters`

### LINKED ISSUE #24894: Dashboard not respecting breakdown limit counts
https://posthoghelp.zendesk.com/agent/tickets/17996

Dashboard is only showing (default) 25 items even though breakdown limit is set to 1000.

The query that is being generated from the dashboard doesn't have a breakdown limit set.

### PR DESCRIPTION
**Pull request by abhi12299**
Fixes #24894

Dashboard filters do not apply a breakdown limit with this change.

### CODE REVIEW

**Comment by abhi12299** [comment]
i will update this test once we finalise if this is what we want: https://github.com/PostHog/posthog/blob/798cedaaa1c82669bd1347b8f8d7271b141ce572/posthog/hogql_queries/insights/trends/test/test_trends_dashboard_filters.py#L265-L297

**Review by Twixes — COMMENTED** [review]
For context, we added the limit reset [in this PR](https://github.com/PostHog/posthog/pull/21707/files#diff-e0050d4789a418b4a9bfa841800c91ed68822c548ff402c938465c61a6593a54), because total value bar charts didn't use to handle many series on dashboards well (looked cramped) – but this seems to work well now, so this change looks good :)

**Comment by abhi12299** [comment]
@Twixes 
I'm not sure why this e2e test is failing - this change has nothing to do with insight navigation:
Screenshot 2024-09-30 at 3 10 08 PM

This test is also failing due to an unrelated issue:
Screenshot 2024-09-30 at 3 09 49 PM

**Review by Twixes — APPROVED** [review]
🚢

**Pull request merged**
