### PR TITLE
Show plugins in onboarding

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This is a frontend-only change to onboarding section 2 UI, showing plugins. Builds on #4106, which made some plugins preinstalled and preenabled (currently only GeoIP, thinking about 1-3 more in the future).

### Before
before

### After
after

## Checklist

- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by Twixes** [comment]
Wellll, after reading https://github.com/PostHog/experiments/issues/2 I realized onboarding has been completely shut down as an experiment some time ago (even though it's still in code) – therefore #3764 seems to be outdated, and this PR in its current form is irrelevant. Should plugins end up in the new Project Home then - for instance? @kpthatsme @paolodamico

**Comment by paolodamico** [comment]
So the onboarding experiment is shut down for now, but I do plan to re-scope it and bring back the setup page, so this is not wasted. We'll see how the project home evolves but I think that'll be more useful post-integration/post-setup. I can review this PR tomorrow or on Monday.

**Review by mariusandra — CHANGES_REQUESTED** [review]
I tried running this, but got this error:

image

Switching the listeners in personalizationLogic to lazily include organizationLogic (`() => ({})` instead of `{}`) fixed that.

Then, if I click this button

image

... twice! Then it consistently kills the tab

Screenshot 2021-05-06 at 12 01 12

UX wise, I think we should just have a few checkboxes and then the "finish setup" button. I'm not sure the button to open plugins (and in a new tab) adds much. Let's instead have just one plugin there for now and add more later.

Other than that, looks good. If that crash gets fixed, I'd be Ok to merge.

**Comment by mariusandra** [comment]
Let's close this for now then... and reopen/recycle/regurgitate when there's a new place to put these toggles.

**Pull request closed without merging**
