### PR TITLE
chore(early-access-feature): Add migration that updates model to not be protected

### PR DESCRIPTION
**Pull request by EDsCODE**
## Problem

- deleting team data doesn't work because early access features were protected

## Changes
- change the property from protected to cascade as we have with all our other team related models

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by liyiy — APPROVED** [review]

**Comment by neilkakkar** [comment]
hmm, this doesn't make sense to me - shouldn't we delete early access first when team is deleted (before flags), and it should resolve this problem?

Otherwise right now, iiuc, this borks regular flow where deleting a flag deletes early access, which is definitely not what we want when someone reuses a flag on early access

**Review by neilkakkar — CHANGES_REQUESTED** [review]
unless I'm mistaken about the above comment, in which case, feel free to ignore and carry on

**Comment by EDsCODE** [comment]
Didn't merge yet for that reason! Was thinking on the multiple flag case

**Comment by EDsCODE** [comment]
@neilkakkar good call out. this should work properly now

**Review by neilkakkar — APPROVED** [review]
perfect 👍

**Pull request merged**
