### PR TITLE
feat(flags): Integrates flag autocapture deeply into other components

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

1. minor CTA on usage tab:

image

2. Automatically generates enriched insights as soon as we detect data coming in.

3. When enriched analytics is present, view recordings points to a more specific filter.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by neilkakkar** [comment]
There are some problems with the usage dashboard db constraints & how deletion works, which I'll address separately.

**Comment by neilkakkar** [comment]
Had to work around how we detect if usage dashboard is enriched already or not, because the previous solution was making everything much slower / n+1 querying.

Not happy with the current solution either (we check in the UI itself, once the dashboard is loaded). I would've loved to make this a part of the logic somehow, but this doesn't seem to be working well, as it forms a chain, where I can only mount the dashboard logic after the feature flag is loaded (to get the right dashboardID), and then I have to wait for the dashboard here to be populated afterMount, and then finally get the value I need.

**Comment by annikaschmid** [comment]
@neilkakkar I would change the colour of the tooltip, either make it green with an (i) or they grey box we use to invite team members. Otherwise it looks too much like a warning / something is wrong
Screenshot 2023-08-15 at 15 31 52

**Comment by annikaschmid** [comment]
And I would make it dismissable, since this is optional

**Comment by neilkakkar** [comment]
makes sense, will do

**Pull request merged**
