### PR TITLE
Login UI revamp

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Improves new UI for login page according to #5860 (latest designs [on Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3558%3A32665)). Scenes can be found on [Storybook](https://storybook.posthog.net/).

**Mobile**

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by paolodamico** [comment]
Next step would be updating the signup page & all invite pages.

**Review by clarkus — COMMENTED** [review]
This is looking good to me. Are you still in progress on this work or are you ready for a full review? I noticed a couple things that were missing, so didn't want to jump into this if it was still ongoing.

**Comment by paolodamico** [comment]
Hey @clarkus! This is meant to be a full implementation of the login page, so tear it apart! FYI won't be able to address until Monday, but please do share feedback anyways

**Review by clarkus — CHANGES_REQUESTED** [review]
I only looked at the login pages here - we have some competing validation patterns, which is kind of jarring. I don't think it's a blocker to releasing this UI revamp as this is likely a preexisting issue. 

We use tooltips to guide completion when a specific format is required (emails). Note I was able to enter a malformed email address and bypass a validation message for the email field. That's probably something to fix before shipping, but the rest just feels like polish. 
Screen Shot 2021-09-23 at 12 10 38 PM
Screen Shot 2021-09-23 at 12 10 54 PM

**Comment by paolodamico** [comment]
Thanks @clarkus! That's actually the browser's HTML5 default validation, I've gotten rid of it. Also implemented the new nicer errors UI.

**Review by clarkus — APPROVED** [review]

**Review by mariusandra — APPROVED** [review]
Definitely an improvement, and all looks good to me to merge! Great to see the storybook stories as well! 👍 

My only comments, though not blockers:
- Any chance to also get the signup page in storybook?
- I guess updating the invite signup page is for another PR? 
Screenshot 2021-09-27 at 17 10 25
- The "forgot password no SMTP env" dialog is also in a different style:

**Comment by paolodamico** [comment]
Thanks @mariusandra & @clarkus for the reviews! Merging now as this is only the login. Will add (including storybook) the signup and invites in separate PRs.

**Comment by clarkus** [comment]
Are we tracking password resets as part of this effort, or should that be included in the onboarding work at https://github.com/PostHog/posthog/issues/6022?

**Comment by paolodamico** [comment]
I'll do that as part of the signup or invite PR. Are you thinking any special design considerations?

**Comment by clarkus** [comment]
@paolodamico nope I think it just needs to align with the other screens.

**Pull request merged**
