### PR TITLE
PyCharm run configurations

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Adds a bunch of environment-agnostic run configurations that'll make it easier for anyone to get started on PyCharm

image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by pauldambra** [comment]
looks good to me... they show on my machine (after restarting PyCharm)

I can't run them yet to confirm, but don't think I should make this merge wait on my machine setup

**Comment by pauldambra** [comment]
Ah, actually, the plugin server dev config has AWS secret key in it! @mariusandra

**Comment by pauldambra** [comment]
I'll get setup and see if that can be provided as an environment variable instead

**Comment by mariusandra** [comment]
Oh, dropped those keys, thanks for spotting. They were for testing anyway, so no real leak :).

**Comment by pauldambra** [comment]
If I start by running `.bin/start` then the script sets `DEBUG=1` and everything runs fine.

But if I run the postgres config from this set I get the error `The environment vars "DATABASE_URL" or "POSTHOG_DB_NAME" are absolutely required to run this software.` That goes away if I set `DEBUG=1`

Should those bits of env var config be captured elsewhere (e.g. the getting started guide) or should they come into this shared config?

(I'd guess we have the same DB URL and name, so they could be shared? But it is a guess :))

**Comment by mariusandra** [comment]
I hope I fixed this with the last cleanup:

Screenshot 2021-09-20 at 13 17 48

**Comment by alexkim205** [comment]
This is awesome thank you marius!

**Pull request merged**
