### PR TITLE
Rename `DashboardItem` model to `Insight` and deprecate `DashboardItem{Serializer,ViewSet}`

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Addressing a TODO item: "Rename model to something more accurate like `Insight`".
Keeps the Postgres table name unchanged just in case (verified no funky business in the migration with  `sqlmigrate`).

### CODE REVIEW

**Comment by timgl** [comment]
I love this proactive renaming, will avoid much confusion in the future!

**Review by paolodamico — APPROVED** [review]
lgtm! Though I'm waiting for the Heroku deployment to complete correctly and deploying to playground to be extra sure nothing is affected.

**Comment by mariusandra** [comment]
Why `SavedInsight` and not `Insight`?

**Comment by Twixes** [comment]
That's what I did first @mariusandra but then I found it potentially really confusing considering we've already got `/api/insight/` (or actually now `/api/projects/<id>/insights/`) and its "ephemeral insights", while these here are "saved insights". I was also planning to rework `/api/dashboard_item/` to `/api/projects/<id>/saved_insights/` (since the endpoint needs to be moved anyway). But I've got to say, it's not entirely clear to me what the difference between `InsightViewSet` and `DashboardItemViewSet` (vel `SavedInsightViewSet`) is, as they both have the same `queryset`.
Do let me know what you think is the best way forward with this. Simple enough to do `s/SavedInsight/Insight/g` (the other way around… much more risky).

**Comment by mariusandra** [comment]
I guess that makes sense, and `SavedInsight` is definitely an upgrade over `DashboardItem`. Yet `Insight` is even cleaner somehow. I wouldn't block it for that, yet I don't know if core analytics folks who touch insights daily have thoughts regarding this.

**Comment by neilkakkar** [comment]
This (specially the ViewSets using the same querysets) had been massively confusing.  This is a great refactor, thank you!

Calling the model `Insight` makes sense to me too. The model implies they're being saved.

Not sure how I feel about calling both API paths Insight though - that feels more confusing to me? (since even if they're both Insights, they're treated very differently in code - SavedInsights have all the extra machinations to do with saving / dashboards, while Insights are simply a dict of filters).

So, definitely not blocking, but it makes sense to me to differentiate naming based on the layer it's in: At the models layer, `Insight` makes sense. At the API layer, there's ephemeral & saved insights.

(How to distinguish them without being confusing on the API layer is an exercise left to the reader) 😂

**Comment by mariusandra** [comment]
Two things that might affect this PR:

1. A new consideration came up in my call with @clarkus yesterday. Currently you can only save one insight on one dashboard. You can not have a case, where you have one and the same insight stored on multiple dashboards. I would definitely see this useful: I define my "booking revenue" insight once, and then plot it on both the sales and accounting dashboards - one source of truth.

2. We don't need to keep anything as is. I would personally love to [get rid of this](https://github.com/PostHog/posthog/blob/40cbfddf2759037143d53adba17c8532ed9c2da8/frontend/src/scenes/insights/insightLogic.tsx#L130-L157) and do just one query to `/api/insight/query` or wherever.

**Comment by paolodamico** [comment]
+1 to the saving the same insight on 0, 1, or n dashboards. It's really confusing UX when you add it to another dashboard and it actually creates a copy. Mildly related, @clarkus I think we would also need to be a bit more explicit when you're updating saved insights to make sure you don't override anything you didn't intend.

**Comment by clarkus** [comment]
> A new consideration came up in my call with @clarkus yesterday. Currently you can only save one insight on one dashboard. You can not have a case, where you have one and the same insight stored on multiple dashboards. I would definitely see this useful: I define my "booking revenue" insight once, and then plot it on both the sales and accounting dashboards - one source of truth.

To me this is the core value prop of saved insights - being able to manage in one spot and reuse in multiple places. If we can ensure this is possible, I think we're good. 

> +1 to the saving the same insight on 0, 1, or n dashboards. It's really confusing UX when you add it to another dashboard and it actually creates a copy. Mildly related, @clarkus I think we would also need to be a bit more explicit when you're updating saved insights to make sure you don't override anything you didn't intend.

Yup it should all be gated by that edit flow except for the meta changes like names, descriptions, tags. Those can happen from either mode. 

How should a saved insight propagate out to the dashboards using it - is there any need to do this in a conditional way? Is it acceptable to edit that insight and just have it immediately propagate out? @mariusandra and I were talking yesterday about communicate how an insight is being used - "used on N dashboards" for example. Is there a case where a user might want to push the update to a subset of those boards using it? I'd argue for simple and powerful over flexible and more complex for now, but wanted to ask for your input.

**Comment by Twixes** [comment]
Thank you all for assembling in this flash mob here. LOL

Have you been of the opinion that this is a great refactor already? That was just the prelude. I've since realized that `DashboardItemSerializer` and `DashboardItemViewSet` are essentially mere subsets of, respectively, `InsightSerializer` and `InsightViewSet`, and that only of these sets can prevail in a reasonable codebase. So I unified things and got rid of the former (though will wait with full removal until we are nearer 1.30.0 to delay a breaking change to the API). Also, settled on `Insight` instead of `SavedInsight`.

I also +1 the idea of making the dashboard-insight relationship many-to-many, but that's definitely a topic for a different PR (though made easier by this one).

**Review by paolodamico — APPROVED** [review]
lgtm! but as it's such a big change worth waiting for @mariusandra taking a look. Also, because I ran migrations on posthog playground with the current version we should rollback the last migration before merging this or we'll end up with a broken playground.

**Review by mariusandra — APPROVED** [review]
Read through the code, looks good and makes sense.

**Comment by Twixes** [comment]
Rolled back the playground migration, so this should be good to go.

**Pull request merged**
