### PR TITLE
fix(session-analysis): dollar sign columns were erroring out formula queries

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

In trends if you create a formula that uses 'unique sessions' or 'unique groups', the query errors out because of a syntax error around the column having a dollar sign in it.

## Changes

Moves the query builder to not treat `$session_id` and `$group_X` as properties, but rather, as columns on the event table (because they're materialized columns either works here). Doing this allows us to wrap the columns in `"` without other repercussions.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Verified that creating a formula trend for `unique sessions/unique users` works.

### CODE REVIEW

**Review by liyiy — APPROVED** [review]
nice, confirmed it wasn't working and now it is

**Comment by liyiy** [comment]
actually I think unique groups is still failing for me

**Comment by rcmarron** [comment]
Hmmmmm, yeah, looks like a `$group_X` is still sneaking into the select. Gonna figure it out

**Comment by rcmarron** [comment]
oooof this took longer than I wanted it too, but I think this should be the right fix now.

**Comment by liyiy** [comment]
> oooof this took longer than I wanted it too, but I think this should be the right fix now.

neither of the options work now :( not sure if something is cached or I'm doing something wrong on my end?

**Comment by rcmarron** [comment]
> neither of the options work now :( not sure if something is cached or I'm doing something wrong on my end?

Gahhh, this is the peskiest issue. Just fixed + wrote tests. Good catch! I think the cache was getting me when I did the "a bit simpler" commit lol

**Comment by rcmarron** [comment]
Cherry picked: https://github.com/PostHog/posthog/commit/21183894c1d6f38bf72614e7a57d6c57742e6cec

**Pull request merged**
