### PR TITLE
feat(data-exploration): convert trends table for data exploration

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

As part of the ongoing effort to enable data exploration for insights, the trends table needs to be converted.

## Changes

This PR:
- Converts the InsightsTable to data exploration, thereby:
  - Splitting the table into 3 main components: `InsightsTable` (entry for current version) `InsightsTableDataExploration` (entry point for data exploration) and `InsightsTableComponent` ("dumb" component, that doesn't care about data exploration or not).
  - Splitting the table itself into multiple components, whereby each column now has it's own e.g. `AggregationColumn`, `ValueColumn`, `WorldMapColumn`
  - Adds a couple of helpers for the data exploration stuff
  - Adds a storybook story, just for the table - found it better to see all options in isolation 

Some things are still in non data exploration land:
- `indexedResults`, as it's based on things sent from backend
- `hiddenLegendKeys`, `setHiddenLegendKeys` aka `toggleVisibility`, as that turned out to be a bigger refactor in itself

## How did you test this code?

- Added table to storybook.
- Manual testing:
  - [x] table on dashboard
  - [x] table as main view
  - [x] check/uncheck series
  - [x] aggregating by total, average, median
  - [x] aggregating by total only for ...
  - [x] hourly interval display
  - [x] renaming in action filter
  - [x] renaming in table
  - [x] sorting by total column  
  - [x] sorting by value column
  - [x] sorting by series column
  - [x] world map column
  - [x] breakdown column
  - [x] special handling of math entities

### CODE REVIEW

**Review by pauldambra — COMMENTED** [review]
love that you're giving names to things 🙌 

Didn't seem to apply breakdowns while editing, and is showing the details table below the table which I think it shouldn't do

**Comment by thmsobrmlr** [comment]
Woah, good catches!

Regarding "details table below the table which" - yep that's happening, but probably a separate issue. What I think is happening is that when you click "save" insightsLogic is overwriting the query. I'll need to add a listener or condition for this. Will do so in a separate PR.

Fixed the other issue, where I didn't render the data exploration version for the main insights table.

**Review by pauldambra — APPROVED** [review]
Series name disappears when you add the breakdown but then re-appears if e.g. you add another series. But that happens with the flag off so no reason to block here 🤷

**Comment by pauldambra** [comment]
> What I think is happening is that when you click "save" insightsLogic is overwriting the query. I'll need to add a listener or condition for this. Will do so in a separate PR.

I think I've been fighting similar in https://github.com/PostHog/posthog/pull/14205 🙈

**Pull request merged**
