### PR TITLE
fix: important changes query perf

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

I claimed this query was cheap... We have good tools to investigate our performance!

https://sentry.io/organizations/posthog/performance/summary/?project=1899813&query=transaction.duration%3A%3C15m&statsPeriod=24h&transaction=%2Fapi%2Fprojects%2F%7Bparent_lookup_team_id%7D%2Factivity_log%2Fimportant_changes%2F&unselectedSeries=p100%28%29

p50 is 1.7 seconds, p99 almost 3 seconds. 🤯 

https://app.pganalyze.com/databases/-675880137/queries/5576993211/indexadvisor

Shows the query time is spent querying `scope` for `scope__in=["FeatureFlag", "Insight"]`

## Changes

~~* Adds a bTree index on scope~~

Adds filtering by team id to engage the existing index

`queryset.explain` started as
```
Limit  (cost=14.40..14.40 rows=1 width=594)
  ->  Sort  (cost=14.40..14.40 rows=1 width=594)
        Sort Key: created_at DESC
        ->  Seq Scan on posthog_activitylog  (cost=0.00..14.39 rows=1 width=594)
              Filter: (((user_id <> 4) OR (user_id IS NULL)) AND ((((scope)::text = 'FeatureFlag'::text) AND ((item_id)::text = ANY ('{5,6}'::text[]))) OR (((scope)::text = 'Insight'::text) AND ((item_id)::text = ANY ('{23,24,25,26,27,28,29,30,31,32,33}'::text[])))))
```

adding  a filter on team id alongside the filter for scope/item_id pair moved to using the index
```
Limit  (cost=8.20..8.20 rows=1 width=594)
  ->  Sort  (cost=8.20..8.20 rows=1 width=594)
        Sort Key: created_at DESC
        ->  Index Scan using posthog_act_team_id_13a0a8_idx on posthog_activitylog  (cost=0.14..8.19 rows=1 width=594)
              Index Cond: (team_id = 1)
              Filter: (((user_id <> 1) OR (user_id IS NULL)) AND ((((scope)::text = 'FeatureFlag'::text) AND ((item_id)::text = ANY ('{1,2}'::text[]))) OR (((scope)::text = 'Insight'::text) AND ((item_id)::text = ANY ('{1,2,3,4,5,6,7,8,9,10,11}'::text[])))))
```

this remained true with a single filter for team_id (and way easier to read)
```
Limit  (cost=8.20..8.20 rows=1 width=594)
  ->  Sort  (cost=8.20..8.20 rows=1 width=594)
        Sort Key: created_at DESC
        ->  Index Scan using posthog_act_team_id_13a0a8_idx on posthog_activitylog  (cost=0.14..8.19 rows=1 width=594)
              Index Cond: (team_id = 3)
              Filter: (((user_id <> 7) OR (user_id IS NULL)) AND ((((scope)::text = 'FeatureFlag'::text) AND ((item_id)::text = ANY ('{9,10}'::text[]))) OR (((scope)::text = 'Insight'::text) AND ((item_id)::text = ANY ('{45,46,47,48,49,50,51,52,53,54,55}'::text[])))))
```

Also removed the pre-emptive filter for scope since it was only duplicating the subsequent conditions

### fly-by

* poll half as frequently
* mark read sooner

## How did you test this code?

running the site locally and seeing it still work

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Looks good 👍. Merge conflict though.

As always, I'm concerned with migrations that affect large tables. We're adding an index with relatively few unique keys to a 7M row table. That shouldn't cause problems... 😅

**Comment by pauldambra** [comment]
@guidoiaquinti can I steal your Postgres brain?

This migration adds an index to `scope` on `posthog_activitylog` (Django does not add the index concurrently so holds a lock on the table)

as @mariusandra points out there are c7m rows. `scope` has 5 possible values. Way over 90% of the rows are set to 1 value (surprisingly)

You can rewrite the migration to convince Django to add the index concurrently but can't do that in a txn and it feels slightly off the beaten path.

My gut is to try the deploy and see if it fails. (which makes me think it would be nice to have statsd timing on migrations)

**Comment by guidoiaquinti** [comment]
> @guidoiaquinti can I steal your Postgres brain?
> 
> This migration adds an index to `scope` on `posthog_activitylog` (Django does not add the index concurrently so holds a lock on the table)
> 
> as @mariusandra points out there are c7m rows. `scope` has 5 possible values. Way over 90% of the rows are set to 1 value (surprisingly)
> 
> You can rewrite the migration to convince Django to add the index concurrently but can't do that in a txn and it feels slightly off the beaten path.
> 
> My gut is to try the deploy and see if it fails. (which makes me think it would be nice to have statsd timing on migrations)

👋 thank you for looping me in Paul! I’m not 100% convinced adding an index in a column with such low cardinality will help the query much. We can double check the distribution of the values, but in a perfectly balanced/even distribution, you’ll still end up scanning +1M keys using a simple lookup on `scope` (in this case is even worst as 90% of the values are set to a single value)

Looking at your query, I think a composed index `(item_id, SCOPE)` might have a better impact? 

Regarding the deployment/rollout: if the underlying `ALTER` uses the [`CONCURRENTLY` param](https://www.postgresql.org/docs/11/sql-createindex.html), the index will get created taking no locks that prevent concurrent inserts, updates, or deletes on the table. Regardless, as the table is doing only a few writes operation per min, I don’t think locking it will be a huge issue.

What do you think about this @hazzadous ?

**Comment by pauldambra** [comment]
I'd not looked at distribution since releasing the activity log.... It's pretty wild!

Screenshot 2022-10-07 at 10 36 39

**Comment by neilkakkar** [comment]
Had a quick look as well because these things are fun:

The problem to me seems to be that the important changes queryset doesn't filter by team ID at all, which implies it has to scan the entire table for scope?

And having the teamID filter will allow it to reuse the existing scope & itemID index: 
https://github.com/PostHog/posthog/blob/master/posthog/models/activity_logging/activity_log.py#L75

**Comment by guidoiaquinti** [comment]
> Had a quick look as well because these things are fun:
> 
> The problem to me seems to be that the important changes queryset doesn't filter by team ID at all, which implies it has to scan the entire table for scope?
> 
> And having the teamID filter will allow it to reuse the existing scope & itemID index: https://github.com/PostHog/posthog/blob/master/posthog/models/activity_logging/activity_log.py#L75

+1. Even better if we can modify the query to reduce the scope :) (not sure if there are any product/app implications to this)

**Comment by pauldambra** [comment]
> the important changes queryset doesn't filter by team ID at all 

@neilkakkar 🤯 

homer-hedge

**Comment by neilkakkar** [comment]
something going really wrong with those snapshots? 👀

**Comment by pauldambra** [comment]
@neilkakkar 🤔 if you run the tests more than once in the same session the activity log isn't being cleared so the snapshot has the max ids seen. Snapshotting is not adding much value here anyway

(although should fix test setup)

**Review by mariusandra — APPROVED** [review]
:shipit:

**Pull request merged**
