### PR TITLE
fix(experiments): re-arrange page layout

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

- bump experiment preview to the bottom (as shown in mocks)
- move person selection to the upper right to fill up the empty space and avoid a super long form

Screen Shot 2022-03-15 at 4 35 39 PM
Screen Shot 2022-03-15 at 4 12 54 PM

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by liyiy** [comment]
@clarkus Thoughts on pushing the person selection to the upper right instead? Moving experiment preview down now provides us too much empty space on the right hand side so this should help fill the void, is still connected to the insight chart, and reduces the vertical length of the form

**Review by clarkus — CHANGES_REQUESTED** [review]
I don't see the white space as a problem. A vertical list of options is easy to scan, maps to how this would layout in narrow viewports, etc.

**Comment by liyiy** [comment]
> I don't see the white space as a problem. A vertical list of options is easy to scan, maps to how this would layout in narrow viewports, etc.

Ok, I moved it back. I agree that a vertical list of options is easier to scan than a side by side layout, just wondering if there are other things we could do to utilize that space better... since secondary metrics is eventually going to take up A LOT of vertical space too. And super long forms might be overwhelming too.. But not the most critical of problems for now

**Comment by clarkus** [comment]
> Ok, I moved it back. I agree that a vertical list of options is easier to scan than a side by side layout, just wondering if there are other things we could do to utilize that space better... since secondary metrics is eventually going to take up A LOT of vertical space too. And super long forms might be overwhelming too.. But not the most critical of problems for now

Yeah I think this is something we need to watch for and instrument. It's hard to justify changes when we're moving quickly with a beta release. I think once we let users use it for a while and gather some feedback, we'll be able to identify improvements and justify making them.

**Comment by liyiy** [comment]
i moved it back btw and also added cancel save buttons to the header

Screen Shot 2022-03-15 at 8 21 29 PM

**Comment by neilkakkar** [comment]
This specific transition looks a bit jarring:

image

**Comment by liyiy** [comment]
What is jarring about it and how would you like it to look like instead? The mocks have it placed slightly between form options but code wise it's better to just align it with metrics selection or something instead of pushing it down to a random spot.

**Comment by neilkakkar** [comment]
Agree with the placement, jarring bit to me is how the line below filters ends in the middle. Don't know what's the best way to solve it though. Maybe a full line?

**Comment by neilkakkar** [comment]
Hey @clarkus , what do you think about that line?^

**Review by neilkakkar — APPROVED** [review]
Not sure about the half-line, but already an improvement, so approving, and we can circle back to the line when Chris replies :)

**Comment by clarkus** [comment]
There's a design for this at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498. It uses a line to separate page sections, but it's kind of a mid-step between goals we identified. There are longer term designs that show secondary metrics, has a fixed floating experiment preview that updates as you complete items, etc. I don't have enough information to really execute here and I'm pretty booked on other projects. I'm going to keep pointing y'all back to the design work that was done, because that's where I have more confidence on decisions. 

We might consider a quick chat to reassess what is needed here? I just can't reactively design something this complex while working on other projects, especially considering the amount of experiments design work that's available for reference.

**Comment by neilkakkar** [comment]
Huh, I could've sworn the mocks looked different.

Not looking for re-design of stuff here, just confirmation that what we're doing is looking the same as the mocks. The difference, and the reason why I'm tagging you in all these reviews is to confirm that this code is an accurate representation of the mocks or not.

Happy to chat as well :)

**Comment by clarkus** [comment]
> Not looking for re-design of stuff here, just confirmation that what we're doing is looking the same as the mocks. The difference, and the reason why I'm tagging you in all these reviews is to confirm that this code is an accurate representation of the mocks or not.

I know this has been a bit of a meandering project design-wise, so I can help point out references if that's valuable. Maybe a pairing session where we review as a group, take notes and put together some action items to address? Short of that, I just need y'all to cross check the designs more before requesting reviews. A lot of this stuff is documented there, so when asked to respond I am going to point y'all back to that resource unless we're encountering some new constraints. I only say that because that's what it takes to balance the other ongoing work and reviews. Again, happy to schedule time to do a review together. I know some of this stuff is hard to see. 👍

**Comment by liyiy** [comment]
full border now

Screen Shot 2022-03-17 at 6 52 23 PM

**Review by clarkus — APPROVED** [review]

**Comment by neilkakkar** [comment]
That's a great idea, Chris. I'm just realising that I'm missing a lot of details going through the mocks. For next time, would just pair and figure out exactly what all is wrong, and then fix that together. Makes things much easier.

>  I can help point out references if that's valuable

Would love this, just something to hone my 'design-sense'

**Pull request merged**
