### PR TITLE
ci(cypress): run cypress tests on master as well

### PR DESCRIPTION
**Pull request by hazzadous**
We do this for a couple of reasons:

 1. we want to validate master branch. We may have tested on branch, but
    that doesn't guarantee that we're tested something equivalent to
    master. e.g. the branch may no longer be a decendant of master
 2. we fix the caching issue. Caches are scoped to a. the branch, and b.
    the branch to which we are merging.

This eliminates 2:30 time off the initial E2E build, and some time off the `yarn build` (maybe a couple of minutes although that's anecdotal)  presumably due to `babel-loader` caching.

### CODE REVIEW

**Comment by Twixes** [comment]
I like the spirit of this! However, I'm not sure if running the check on `master` is the best way. Considering how flaky E2E tests tend to be (and they will always be more flaky than all other test suites, even if just a bit), running them after merge may introduce false positives. And any positives, true or false, will be stressful to sort out once in master.

I think it'd be better to catch problems in the PR itself – GitHub has this repo setting which requires the branch to be up-to-date before merging, so actually I propose we do that instead. We've been using it in https://github.com/PostHog/plugin-server for some time and it's been working pretty well. WDYT?

Screen Shot 2021-10-11 at 13 41 41

**Comment by paolodamico** [comment]
+1 to @Twixes comment, it's particularly disheartening to open the main page of the repo and see a big red cross next to the latest commit, makes you think something is broken. Let me know if the proposed approach makes sense and I'll enable that for this repo.

**Comment by hazzadous** [comment]
> I like the spirit of this! However, I'm not sure if running the check on `master` is the best way. Considering how flaky E2E tests tend to be (and they will always be more flaky than all other test suites, even if just a bit), running them after merge may introduce false positives. And any positives, true or false, will be stressful to sort out once in master.
> 
> I think it'd be better to catch problems in the PR itself – GitHub has this repo setting which requires the branch to be up-to-date before merging, so actually I propose we do that instead. We've been using it in https://github.com/PostHog/plugin-server for some time and it's been working pretty well. WDYT?
> 
> Screen Shot 2021-10-11 at 13 41 41

My understanding is that running this won't actually block anything, it's just a little more github actions time (at worst it's doubling the actions time, if we only ever run it once on PRs, but I suspect they're run much more than that).

Whilst I think the updated branch setting looks interesting, I imagine in the majority of cases everything is fine, so blocking devs from being able to merge without a rebase, and potentially getting into contention issues would not be a good experience. i.e. update branch, tests run, in the mean time someone has merged into master etc.

> +1 to @Twixes comment, it's particularly disheartening to open the main page of the repo and see a big red cross next to the latest commit, makes you think something is broken. Let me know if the proposed approach makes sense and I'll enable that for this repo.

If this is a concern we could make this silently fail? Although I would like to think that we have tested master given that this is the code we are releasing.

Alternatively if this a contentions issue I can drop this, although I would suggest that we should be running tests on master despite concerns that it would be red. We can just get rid of the flaky tests if they are a concern?

**Comment by hazzadous** [comment]
Also, for what it's worth this was just to try to get the workflow to run a bit faster, it's not a must have.

**Comment by Twixes** [comment]
I'm pretty sure if we do this silently, it's very unlikely that anyone would actually check for failures. I think there are three options:

1. Run E2E tests on `master` and deploy anyway (this PR currently):
	- pro: very easy to implement
	- pro: doesn't interfere with anything
	- con: doesn't interfere with anything, so wouldn't prevent issues in prod
	- con: in case of a failure, solving it would be stressful (the code being live), especially since inevitably we'd first try rerunning the suite to see if the red check isn't just a fluke
2. Run E2E tests on `master` and only deploy after they pass:
	- pro: safe for the state of prod
	- con: in case of a failure, fixing it would require creating a new PR, which is slower than updating an existing one
	- con: in case of a failure, unrelated PRs (that don't fix the failure) would be completely held up
	- con: it'd take 10-15 min longer for merges to actually go live
3. Require PRs to be up to date before merging:
	- pro: safe for the state of prod
	- pro: in case of a failure, the PR just gets updated ahead of merging
	- pro: would also apply to all other suites, which can detect problems that Cypress can't exactly
	- con: PRs would need to be brought up to speed, which, as you mentioned, is 10-15 min in which a conflict _could_ arise

None are perfect, but for me, 3 improves the situation best.

**Comment by hazzadous** [comment]
For option 1, presumably the cons are valid for the currently situation anyhow? But agree it's not the most visible of failures.

I'm ok with 3 although I wonder what that does for the experience. For our internal development that's probably fine, we've probably got a higher tolerance for pain, but for external contributors it's one more barrier. I would highlight that it doesn't address the caching issue that I was originally looking to solve however.

**Comment by hazzadous** [comment]
(perhaps the other option is to just run the workflow, but auto-pass the test on master, that might prevent some yak shaving)

**Comment by hazzadous** [comment]
I'll close this PR for now, to reduce the noise in the PR list.

**Pull request closed without merging**
