### PR TITLE
Fix edit actions losing focus on each keystroke

### LINKED ISSUE #5627: Edit Actions view loses cursor focus after every keystroke
## Bug description
Edit Actions view loses cursor focus after every keystroke
https://app.posthog.com/action/9391?properties=%7B%7D#backTo=Actions&backToURL=%2Fevents%2Factions
image

## Expected behavior
After a keystroke the focus persists in the textbox you are typing in.

## How to reproduce

1. go to https://app.posthog.com/action/9391?properties=%7B%7D#backTo=Actions&backToURL=%2Fevents%2Factions
2. Attempt to modify `Link target equals` field
3. Watch as the focus goes elsewhere after each key press

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Fixes #5627

Turns out React doesn't honor unique key re-rendering if components are nested and share states.

image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by samwinslow — APPROVED** [review]
Code LGTM! Reviewing from mobile, so I trust that this works from a UX perspective :)

**Review by fuziontech — APPROVED** [review]
lgtm!

**Comment by macobo** [comment]
Would this have been caught by an e2e test? Worth adding one?

**Comment by alexkim205** [comment]
good idea! I'll add an e2e test as well

---

It looks like we already have a cypress test for inputting text edit action fields but `cy.type` overrides any focusing/blurring nonsense that the user actually experiences. I'll edit this existing test to check if the input field is still focused after typing something.

**Pull request merged**
