### PR TITLE
feat: Simplify playlist selector

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

WIP
Adding to playlists is not quite as intuitive as we hoped. 
* Too many steps to add to a playlist
* Unclear UI and wording
* Removal from a playlist is not clear

## Changes

* Fix height of playlist lists, with sticky functionality

**Recent Recordings**

**Playlist**

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## TODOs

- [x] Fix height of playlists scrollers
- [x] Link add/remove of playlists to the actual playlist view
- [x] Don't show all added playlists on search
- [x] Ensure adding a new playlist in the popup works as intended
- [x] Add dismissable AlertMessage for pinned recordings explaining how they work
- [x] Make the two lists collapsable
- [x] Hide pinned recordings if filters are expanded
- [x] Display current playlist first in list of dropdown
- [x] Fix properties loading
- [x] Fix "save to playlist" button
- [x] Show count of "pinned dashboards"
- [x] Add back in loading state for lists
- [x] Remove the global playlists model logic as it introduces caching bugs
- [x] Fix Playlist search bar to top of popup
- [x] Fix beforeUnload of playlist when you have unsaved filter changes and click a recording
- [x] Don't report playlist update for background changes (derived name)
- [x] Add tracking for playlist interactions like e.g. expanding pinned list 
- [x] FIX: Make changes to filter, save - still marked as having changes

## Follow up Issues
- https://github.com/PostHog/posthog/issues/13345

### CODE REVIEW

**Comment by alexkim205** [comment]
Added collapsibility - 


https://user-images.githubusercontent.com/13460330/206764570-af806d64-ac77-433d-8c26-1bb197fe23ce.mov

**Comment by alexkim205** [comment]
- [x] Ensure adding a new playlist in the popup works as intended
- [x] Fix properties loading
	- Refactored properties fetching logic out of sessionRecordingListLogic into sessionRecordingListPropertiesLogic
- [x] Display current playlist first in list of dropdown
- [-] Remove the global playlists model logic as it introduces caching bugs
     - Partially, removed all references to saved model logic except in savedSessionRecordingPlaylistsLogic

**Comment by benjackwhite** [comment]
Weird jest tests still failing but I don't get why, they seem unrelated to our changes...

**Comment by alexkim205** [comment]
@benjackwhite I think this should be good to go! addressed the last of the todos and added a logic test. I'll leave a ✅ here and leave it for you to merge once you've looked it over

**Review by alexkim205 — APPROVED** [review]

**Pull request merged**
