### PR TITLE
fix: docs for Flutter Implementation

### PR DESCRIPTION
**Pull request by coder-Aayush**
## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
Nice fix

**Comment by coder-Aayush** [comment]
@posthog-bot

**Comment by coder-Aayush** [comment]
@benjackwhite pull request is not merged yet

**Comment by benjackwhite** [comment]
Sorry for the delay here 🙌

**Pull request merged**
