### PR TITLE
fix(events): auto load new events checkbox issue

### PR DESCRIPTION
**Pull request by abhi12299**
## Problem
- When the `Automatically load new events` checkbox is unchecked and the user cancels the ongoing query, the error message displayed is "The query was cancelled" - which is correct.
However, after this, when the checkbox is checked, the error is about `AbortSignal` and it does not trigger a refetch immediately.

- When you cancel the ongoing query when the  `Automatically load new events` checkbox is checked, you will see the `AbortSignal` error.

Here's the bug:

https://github.com/user-attachments/assets/6804e334-34a7-4d98-a5ff-cef2486c60b2

## Changes
- `loadNewData` prioritises new response if the existing response is null. https://github.com/PostHog/posthog/blob/dfbd23b4964811125e07dcede8a14e2a2b5d3598/frontend/src/queries/nodes/DataNode/dataNodeLogic.ts#L238-L264
Lines 258-262 here show that the object returned from the loader will only have `results` key if `values.response` is null

- `responseError` reducer also reacts to `loadNewData...` actions; this helps to get rid of the error state when new data is loaded.
- When you cancel the ongoing query when the  `Automatically load new events` checkbox is checked, you will not see any error state in the table - this is because the auto load functionality will trigger a refetch in 30s anyways, so it is not a good UX to show an error state only for it to be replaced with the table after 30s.

Here's the fix:

https://github.com/user-attachments/assets/9c5d62d2-9f3e-4440-8afe-31f89ec25a3c

### CODE REVIEW

**Comment by abhi12299** [comment]
Will fix the cypress tests after discussing and finalising on the desired behaviour.

**Review by Twixes — COMMENTED** [review]
Looks good to me @abhi12299! But not sure why CI's red, definitely worth getting to green

**Comment by abhi12299** [comment]
@Twixes working on it!

**Comment by abhi12299** [comment]
@Twixes only the visual regression tests fail. I don't think I have access to the assets uploaded by the tests to see what the difference is.

**Review by Twixes — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
