### PR TITLE
chore(apps): rename plugins to apps

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

- Part of https://github.com/PostHog/posthog/issues/9654

## Changes

- Renames "Plugin" and "Plugins" to "App" and "Apps" on all the ~plugin~ app pages.
- Does not rename `Plugin` to `App` everywhere in the code. The Scene is still called `Plugin`, etc. We can do this as the next step.

## Not done

- We refer to the "repository" now as the "App Library" in some places and as the repository in others. What should it be? 
- I didn't change any of the links. They all still lead to pages like posthog.com/plugins . Where should all the blue links visible in the screencast lead to?

## How did you test this code?

- Clicked around locally

### CODE REVIEW

**Comment by joethreepwood** [comment]
As per https://github.com/PostHog/posthog.com/pull/3253 the place to see all available apps will be `/apps` so we should probably be directing users there, or to specific pages in that folder.

Also on that PR I _think_ I've correctly redirected the `/plugins` and `/integrations` pages on .com to the new `/apps` page. However, I think extra work from @smallbrownbike or @corywatilo may be warranted there to make that new `/apps` page easier to use. There's no search or filters currently, for example. But I defer to them. 

I'd love to get a solution to https://github.com/PostHog/posthog/issues/9509 too, so that we can link from `/apps` to the Apps section of the product, but that may be a later job.

**Review by joethreepwood — APPROVED** [review]

**Comment by joethreepwood** [comment]
I think this looks good to me, based on my many years of coding experience. 

Just needs to sync with https://github.com/PostHog/posthog.com/pull/3253 

> Does not rename Plugin to App everywhere in the code. 

This is consistent with changes I made to the docs as part of the above PR. I've changed references to the plugin server to the app server, but haven't touched any code samples (and have referenced plugin/app server in cases where it seemed important to encompass ambiguity).

**Comment by joethreepwood** [comment]
@mariusandra We're good to launch this whenever you're ready. They're already called apps on the website now.

**Comment by mariusandra** [comment]
And it's done! 🎉

**Pull request merged**
