### PR TITLE
Signup UI Oct 2021

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Implements the new design for the signup page and some minor cleanup on the way. **Best way to check the new views out is through Storybook.**

## How did you test this code?
- Opened the signup page both simulating cloud (by manually setting the required values in the preflight payload) and self-hosted, and tested the signup form from start to finish.
- Tested adding an invalid email address and invalid password.
- Tested adding insecure but compliant password.
- Tested the form on mobile through developer console.
- There's also already existing E2E tests to test the signup flow (`signup.js`)

### CODE REVIEW

**Comment by timgl** [comment]
Minor point. "Through manual testing" isn't super prescriptive, something like "I created an invite link, opened that in an incognito browser and signed up" would be better

**Comment by paolodamico** [comment]
Oh thanks @timgl, missed a bit here of what to add. Updated the description!

**Review by mariusandra — COMMENTED** [review]
The code LGTM, though I found some UX things to nit about:

1. This resolution breaks the three taglines at the bottom of the page and makes the page have a scrollbar.
 
image

2. Not sure if the string "secure-o-meter" adds value or confuses people. I got slightly confused and think it'd be cleaner without.

image

3. I'm not sure if this animation adds anything:


4. More complicated validation for the e-mail happens only after page 2



5. The invite and expired invite URLs still show the old setup page:

image

image

**Comment by clarkus** [comment]
> Not sure if the string "secure-o-meter" adds value or confuses people. I got slightly confused and think it'd be cleaner without.

I'm not sure how valuable it is either. This existed before the recent design updates... the only change impacting this was the label change from "password strength" to "secure-o-meter". Could just change it back to the previous value, but I'm still skeptical about how much value this is adding. 

Also a note that we should include the password reset portion of these flows here, too. I am updating the designs for those today. 

Edit - the password reset screens are at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3861%3A26198

**Comment by paolodamico** [comment]
Thanks @mariusandra & @clarkus! Feedback addressed, ready for another look.
- Agreed on "Secure-o-meter" label, got rid of it. I do think the component adds value, particularly as our password requirements are quite lax (but quite open to removing it).
- Invite signups and password resets will be migrated in a separate PR.

**Review by clarkus — APPROVED** [review]

**Comment by mariusandra** [comment]
- One cypress test called "signup.js" is suspiciously failing. Might be related? 🤔 
- Let's disable all fields when submitting
image

Other than that LGTM.

**Comment by paolodamico** [comment]
Good catches @mariusandra, thanks! Should be addressed now, will merge once tests pass

**Pull request merged**
