### PR TITLE
style(experiments): Better styling for variant selection

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

Figma: https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498

Before:
image

After:

Not sure yet how to handle required text though. Have the default right now:

image

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Run locally, go to experiments, create new, see things look like figma mock

### CODE REVIEW

**Comment by clarkus** [comment]
@neilkakkar I posted updated error states at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498. There's a comment there with some more specifics. 

Screen Shot 2022-03-15 at 9 13 56 AM

**Comment by liyiy** [comment]
> @neilkakkar I posted updated error states at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498. There's a comment there with some more specifics.
> 
> Screen Shot 2022-03-15 at 9 13 56 AM

@neilkakkar That's antd's form item erroring so if we want those error states, might have to change back to form list with form item, otherwise if we want to stick with inputs not in a form we'll have to change the error state display

**Comment by neilkakkar** [comment]
Yes indeed. Quick question: Can we customise Form.Item's erroring to look like what it shows in the mocks? (it's similar but not the same 🤷 )

**Comment by clarkus** [comment]
The examples above look pretty flawed to me. It only shows on element focus and there is no affordance for indicating an error otherwise. I feel that we need something inline to draw the users attention to the erroneous portion of the form. Happy to discuss so we can get something shipped, but I don't see the tooltip pattern as being very effective for this. 

The validation pattern I referenced above is part of ant-d btw. https://ant.design/components/form/#components-form-demo-without-form-create

**Comment by neilkakkar** [comment]
Nah, all good, makes sense, will switch! (and would probs need @liyiy 's help for the styling 😅 )

**Comment by neilkakkar** [comment]
Hey @clarkus , @liyiy , here's the new iteration. Chris, does this work?



The big problems I could use your help with, Li:

1. The validation message is out of sorts, on top of whatever is below
2. Responsiveness to different screen sizes is complete jank

**Comment by neilkakkar** [comment]
Also, @liyiy , I tried the `Form.List`, but it was very terrible, majorly because it fights with kea on ownership of data: has its own add and remove functions, which can make things out of sync with whats stored in kea, and reconcilation only happens on save? idk. It might work, but I was struggling a bit too much and decided not to go that route.

**Comment by clarkus** [comment]
> Hey @clarkus , @liyiy , here's the new iteration. Chris, does this work?

The clear action should not use a destructive color - you're not losing work, just clearing a single field. If the remove were farther reaching in terms of how much was removed, a destructive icon would be appropriate. In this case it just needs to be the typical gray color. Example screenshot from another feature in the app.

Screen Shot 2022-03-16 at 8 07 32 AM

The validation message placement is pretty problematic, too. I can do a full review once y'all get that positioning and stuff.

**Comment by neilkakkar** [comment]
Thanks @liyiy , that was super helpful <3

Hey @clarkus , how-do-you-like-me-noww?

**Review by liyiy — APPROVED** [review]
🎉

**Comment by clarkus** [comment]
Where did that clearing action come from? It's not in the designs and I don't think it's adding value... or at least not enough value that it's worth displacing the error icon. The main job here is indicating an error, not clearing the input. 

Here's the corresponding design from [figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498)- we just need to match against this.

Screen Shot 2022-03-17 at 9 30 05 AM

**Comment by neilkakkar** [comment]
> Where did that clearing action come from?

You mean the red box on the right? You want the cross to be an exclamation point?

**Comment by clarkus** [comment]
> > Where did that clearing action come from?
> 
> You mean the red box on the right? You want the cross to be an exclamation point?

Yes. That's why I used that icon in the designs. Are y'all referencing figma and trying to follow that work? I feel like I've been pretty clear on this so I'm struggling to understand how the communication keeps failing here. 

Screen Shot 2022-03-17 at 9 55 46 AM

**Comment by liyiy** [comment]
final edit:

Screen Shot 2022-03-17 at 5 43 53 PM

**Review by clarkus — APPROVED** [review]

**Pull request merged**
