### PR TITLE
Add negative cohort filtering of events

### PR DESCRIPTION
**Pull request by thedeveloperr**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## Checklist

- [x] All querysets/queries filter by Organization, by Team, and by User
- [x] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by Twixes** [comment]
Hey! Converted to draft since the PR title said so. Mark it as ready for review once, well, it's ready. Please do add screenshots if you've got some frontend changes in here! :)

**Comment by thedeveloperr** [comment]
@Twixes Reading about ClickHouse and then I will make changes to EE version. Frontend is also WIP.

**Comment by Twixes** [comment]
Hey! How have you been @thedeveloperr? Made progress?

**Comment by thedeveloperr** [comment]
Oh sorry for late response. I got busy with some  job and family stuff. Forgot to update here. I still have some reading up to do on click house so i can make changes for EE version. If someone wants to complete it please feel free to do and let me know . Otherwise I will try again on weekend. 

Regards,
Mohit Gupta

**Comment by thedeveloperr** [comment]
@Twixes I couldn't find time to add this feature in EE clickhouse. I might not be able to complete this PR. Please feel free to use the existing commit if they are up to mark

**Comment by Twixes** [comment]
Hey! No problem. I think we'll tackle this in a different PR in this case.

**Pull request closed without merging**
