### PR TITLE
Upgrade simmer to version that works with colons ":" in class names.

### LINKED ISSUE #1368: Toolbar Heatmap crashes on sites built with Tailwind CSS
## Bug description

Sites built with Tailwind use a lot of classes like: `text-base leading-6 font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900 transition ease-in-out duration-150` 

The problem is with the ones that have a colon (`:`) inside them. Simmerjs crashes with the following:

```
Failed to execute 'querySelectorAll' on 'Document': 'A.text-base.leading-6.text-gray-400.hover:text-gray-500.hover:text-white' is not a valid selector
```

... bringing down the entire toolbar.

## Expected behavior

The toolbar shouldn't crash when your page contains a CSS class with a colon in it.

https://stackoverflow.com/questions/45110893/select-elements-by-attributes-with-colon

## How to reproduce

1. Make a page with a `<button />` that has a class `with:colon`.
2. Wait for a few events to be captured or click the button yourself
3. Open the toolbar, click "heatmap" and watch it burst up in flames (and then crash)

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- This PR closes #1368 
- I [fixed the bug](https://github.com/gmmorris/simmerjs/pull/19) in Simmer and sent a PR
- This PR upgrades to [my own version](https://github.com/mariusandra/simmerjs/tree/local-release) of the simmer npm package that already contains the fix (plus adds types), so we could use it immediately.

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Review by timgl — COMMENTED** [review]
When saving an element with colon as an action storing it as `nav:link` works, but `nav\:link` doesn't. Is there a way of un-escaping colons?

**Comment by mariusandra** [comment]
Hey! Indeed, actions aren't matched. I'll see what can be done... but quickly beforehand: things get complicated when you consider that we have two types of colons: `className == "nav:link"` or `selector == "nav:nth-element(4)"`. 

Thus the selector `a.text\:bold:nth-child(4)` is a correct on and un-escaping colons would break it.

I guess by that analysis the problem lies in the backend code that matches actions to elements. I'll have a look at it.

Alternatively I could save the selector as `[class="text:bold"]` if it contains a colon or other escapable character, but I don't think that would automatically solve anything either.

**Comment by mariusandra** [comment]
Added un-escaping of selectors in the backend. Ready for another look.

**Comment by mariusandra** [comment]
I wasn't happy with the unescaping as it would give incorrect results when you had e.g. three legit slashes (`"\\\\\\"` in escaped format) in your classname. That's fixed now.

**Pull request merged**
