### PR TITLE
Refreshing insights

### PR DESCRIPTION
**Pull request by timgl**
## Changes

See #3144 for the full changelog. The only thing this adds is a key on funnelLogic to solve #3268

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
hmm right so adding the key was indeed enough, we just had to explicitly pass empty props - I went on a whole chase with funnelVizLogic...

testing now

**Comment by yakkomajuri** [comment]
Solution makes sense to me. I added the key in originally and then it broke funnels but I see now that it's the empty props issue. 

But so things I've tested that work fine:
- Refreshing everything
- Multiple dashboard panels
- Funnels in general

Did find this though, not sure if a result of the PR:


https://user-images.githubusercontent.com/38760734/107622969-8fc26f80-6c50-11eb-89f6-c875d57f3876.mov

Top right says computed a minute ago so we found a cache result based on the old filters?

**Comment by timgl** [comment]
@yakkomajuri thanks for the QA. I think the weird behaviour came from us not removing that last refresh message when you changed filters. I've added that now.

**Comment by yakkomajuri** [comment]
Similar behavior still:

Screenshot 2021-02-11 at 10 23 28


See how the funnel has one step but I see the old two-funnel step.

Running on latest commit here `eb9fb6d`

**Comment by yakkomajuri** [comment]
Even weirder:

https://user-images.githubusercontent.com/38760734/107624967-871f6880-6c53-11eb-9879-d9031a62d12f.mov

Let me try master before you're off on a goose chase

**Comment by yakkomajuri** [comment]
Yeah doesn't seem to happen on master

**Comment by timgl** [comment]
@yakkomajuri Hm I'm unable to reproduce even with demo data + exact same steps. I've added some breakpoints which might help, could you try again with those?

**Comment by yakkomajuri** [comment]
I'll flush Redis in case there's some lingering issues from old cache and try out these breakpoints

**Comment by yakkomajuri** [comment]
Able to reproduce on the deployed env:

Screenshot 2021-02-11 at 12 55 10


It's definitely quite an odd one though, I'm not even sure I can instruct you on how to reproduce, because I'm just clicking around removing and adding steps. I have been trying to create funnels and subfunnels though, where I load a funnel with two steps, add a step, and then remove it. It also does seem to me that this happens when the steps are the same, although in different orders?

I mean, this time around the screenshot has Purchase -> HogFlix signed up -> HogFlix signed up -> Purchase, and it's giving me those 2 first steps essentially.

Sending the link obviously doesn't work.

**Comment by yakkomajuri** [comment]
Hmm okay so stuff seems to go south when I click refresh and then change the steps

**Comment by yakkomajuri** [comment]
@timgl Ok here's some reproducible steps (I think), caught on camera in the wild:


https://user-images.githubusercontent.com/38760734/107640073-a923e580-6c69-11eb-9a3a-b209c8250df7.mov

**Comment by timgl** [comment]
Note to self: make sure to fix refresh issue

**Comment by timgl** [comment]
@yakkomajuri Simplified logic again, should work now (sorry for back and forth!)

**Comment by yakkomajuri** [comment]
Bug seems fixed, one annoying UX thing now, where as a user I am expecting the spinner to pop up when I click calculate (given we've always had it), but now I just seem to be getting the funnel with no "loader". For long queries I end up thinking something is broken:


https://user-images.githubusercontent.com/38760734/107765022-06cb3700-6d29-11eb-8d9a-406524d9ac02.mov

**Comment by timgl** [comment]
@yakkomajuri Thanks! Fixed :)

**Pull request merged**
