### PR TITLE
Make events search more prominent

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

Very regularly we get questions about how to search for events on the events table.

The problem is that this functionality is so hidden it took me a lot of time to find it as well. This makes it more prominent.

The idea was to use the same component as the actions search, but the events search uses a `select`, so I've left that as is. 

Sent the export button to the other side to remove clutter on the left side of the screen.

PR also fixes random TS errors I ran into.

| Before | After |
| :-----: | :----: |
| Screenshot 2021-03-05 at 12 28 00 | Screenshot 2021-03-05 at 12 24 24

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Latest update is this instead of the `disabled` approach:


https://user-images.githubusercontent.com/38760734/110116316-3e208700-7daf-11eb-9ca5-e588229b8d9b.mov

**Comment by mariusandra** [comment]
I think this already improves the situation.

However I think the ideal place for this filter is a new "Event" tab inside this dropdown... 🤔 

image

The other issue (also outside the scope?) is that this "event" is not saved in the URL, so if you reload the page, it resets.

And the third issue can be seen on your screencast: when you search for an event the "The are 4 new events" thing from before the filtering stays in place... and causes noise when clicked on.

Do with this feedback what you will :D

**Comment by yakkomajuri** [comment]
Right so:

1. This I believe is relevant - it's an approach discussion. I do think event name makes sense as a separate search that I can immediately access, but happy to implement it via the dropdown too.

All the other issues I'm happy to take on - but they were all there before. The new events thing with the search has bothered me before so I might as well fix it.

**Comment by yakkomajuri** [comment]
Ah I see the point now - if I have event in the dropdown that immediately fixes the URL problem... I suspect this approach will not solve the fact that it is hidden though?

**Comment by mariusandra** [comment]
Indeed, it would solve all those issues at once. For discoverability, if I want to filter by something, clicking the "add filter" button seems obvious. I guess that's what's happening now as well -> people click it and don't find the "event name" option.

**Comment by fuIIstack12345** [comment]
Hello guys
I am very interested in this project and I really hope to work with your team.

**Comment by macobo** [comment]
Re adding it inside "Add filters", I agree in theory - however:
1. I think we need to rethink the adding filters UX completely anyways, given that e.g. sessions needed to roll out their own solution for extending it.
2. I think it's worth pushing this out before then.

**Comment by yakkomajuri** [comment]
Yeah I never really got the chance to revisit this.

Fixed the conflict though so feel free to merge @macobo

**Comment by yakkomajuri** [comment]
just a friendly ping @macobo

**Comment by macobo** [comment]
Baby steps!

**Comment by yakkomajuri** [comment]
:baby:

**Pull request merged**
