### PR TITLE
fix(insights): fix one crash to investigate another

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Trying to open the saved insight card list view for our team results in this:

image

## Changes

Prevents the broken code from firing. Not the cleanest fix, but it'll help me move on to the next issue.

More to come.

## How did you test this code?

Locally simulated the condition with a well-placed `false`

image

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
Do you have a link to the broken insight? The `insight` filter should default to `TRENDS` if it's not present, but the screenshot seems to show a funnels insight 🤔  Would be nice to better understand what is happening.

**Comment by mariusandra** [comment]
It's this one: https://app.posthog.com/insights/3SN68fmz (link also crashes)

image

The filters are really empty, yet the title would suggest this was once something.

**Comment by thmsobrmlr** [comment]
Turns out we've been cleaning query nodes to eagerly and thereby removing a required "series" property. A fix is coming here https://github.com/PostHog/posthog/pull/17879. This doesn't seem to be the same issue as in the screenshot however 🤔

**Review by thmsobrmlr — APPROVED** [review]
👍 

We could alternatively fall back to `TRENDS` for `insight` in `filtersToQueryNode`. Don't really know how insights without `insight` occur, so hard to say if we want to show and error or handle it in a graceful way.

**Comment by mariusandra** [comment]
Couldn't get a flaky test to pass, so merged the followup https://github.com/PostHog/posthog/pull/17875 directly to master instead.

**Pull request closed without merging**
