### PR TITLE
Temp fix for start point in user paths

### PR DESCRIPTION
**Pull request by yakkomajuri**
### EDIT: I messed up typing though, looking into it now

Ultimately all of these filters need refactoring.

However, this PR is a temp fix that:

- Makes `START POINT` input in paths open a selector on click
- Makes it display the correct value
- Flips some logic around from a negative conditional to a positive one (more readable)
- Fixes an issue with duplicate keys due to the key used by `Specify`

https://user-images.githubusercontent.com/38760734/121378323-7a690380-c919-11eb-89b1-3a24f5e7774d.mov

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by timgl** [comment]
legit test failure?

**Comment by samwinslow** [comment]
@timgl Yes, test failure is legit. Investigating.

**Comment by yakkomajuri** [comment]
I'll look into this post CH call

**Comment by samwinslow** [comment]
I think PropertyValue needs to be converted to TS.

**Comment by yakkomajuri** [comment]
Ok so had a call with @samwinslow to decide what to do about this for the release.

Conclusion: I'll wrap up this temp fix and have it ready to go. Sam will look into a minor refactor which would be a better solution. If the refactor would take too long, we'll just get this in.

Was fixing some `posthog-node` bug but looking into this now

**Comment by yakkomajuri** [comment]
This is an absolute mess, anything I change breaks something else. 

Types are all over the place, and there were hidden bugs here we didn't ever handle before (did anyone ever test paths with custom events?)

Will work on it for a bit longer but ultimately a refactor here is the only reasonable solution

**Comment by yakkomajuri** [comment]
It's so far from perfect but it should be a bit more usable than what's in master right now (not usable).

I do have to set a cap on my "stepping on toes"  though - spent too much time on this and have other things to do. 

cc @samwinslow

**Comment by samwinslow** [comment]
#4686 may supersede this; waiting for checks to run there.

**Comment by yakkomajuri** [comment]
Closing in favor of #4686

**Pull request closed without merging**
