### PR TITLE
Optimized update person props

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

~~WIP with some rough edges. I need to benchmark this but it looks like much better solution to what we currently have.~~

Cleaner, fewer subqueries, will remove complexity from the plugin server, etc

Benchmarks:

Screenshot 2021-10-19 at 14 30 55

Average person on Cloud has 13 props so on most cases the change in performance is minimal. Even on extreme cases the difference isn't too bad, and worth it for integrity.

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by yakkomajuri** [comment]
To do:

- [x] Handle the one broken test case
- [x] Handle https://github.com/PostHog/posthog/issues/6458
- [x] Handle increment
- [x] Update plugin server PR
- [x] Benchmark
- [x] Push minor updates to the function that were done locally

**Review by tiina303 — COMMENTED** [review]
some early feedback (as it's still in draft mode)

**Comment by yakkomajuri** [comment]
@tiina303 see my comment on #6458 and let me know what you think so we can make the final changes to this

**Comment by yakkomajuri** [comment]
We won't be able to use `PERFORM` (https://stackoverflow.com/questions/38577956/how-to-execute-perform-pg-notify) so it's a bit weird that `SELECT` does the update without return but 🤷  simplified it further, and popped the `FOR UPDATE` inside the function.

**Comment by yakkomajuri** [comment]
Addressed everything @tiina303

**Review by tiina303 — APPROVED** [review]

**Pull request merged**
