### PR TITLE
Add index for event URLs

### PR DESCRIPTION
**Pull request by mariusandra**
This potentially fixes issue #333... for now :)

### CODE REVIEW

**Comment by timgl** [comment]
Failing tests! Otherwise looks good, however is it worth combining this index with `team_id` and `event`? I don't know that much about indexes but what I understand is you might as well have multiple fields in one index, which will be faster if you do a lookup for all of them and equally fast if you do it for a single one

**Comment by mariusandra** [comment]
Yep, it seems that there is (was?) an issue.

If you want to run this migration without any downtime for posthog.com (and everyone else using it), we must call `CREATE INDEX CONCURRENTLY` instead of `CREATE INDEX`.

However with `CONCURRENTLY` the index then can't be created inside a transaction (`BEGIN` / `END` block).

This is not a problem if running only this migration (it worked for me)... but when running all migrations, django seems to want to force them inside a transaction, even when setting `atomic = False`.

I made a commit that removes `CONCURRENTLY`. It will run... but probably lock the DB for users who have a lot of events. I'm not sure what to do. Perhaps there's a way to make the tests respect the atomic migration? Or perhaps locking the events table for a brief moment is good enough?

I also added `team_id` to the index. Good catch! This required a new extension though, which I also added.

**Comment by timgl** [comment]
We should probably add `event` too, [I identified that as another thing we should index](https://github.com/PostHog/posthog/issues/325).

Running the current migration on a copy of our production database (couple million) only took 26s so I think I'm happy for that to be non-concurrently

**Comment by mariusandra** [comment]
Added event! We should probably also add a new index for just `team_id` and `event`, without the current_url. I can make a new PR for that.

**Comment by timgl** [comment]
Don't worry about that for now, let's merge this and carry on :)

**Pull request merged**
