### PR TITLE
Groups: feature flag support for aggregating by groups

### PR DESCRIPTION
**Pull request by macobo**
## Changes

This PR adds support for using groups with feature flags. Some constraints:
- You can only use person + cohort filters for normal flags
- You can only use group filters for group flags
- To check for group flags, you need to pass groups to the endpoint (and in client libraries)
- For flags that are released to 100% of of a certain group type, you would need to specify what group you're part of
- It respects user-based overrides

Handled in follow-up PRs:
- Updating my_flags endpoint
- Updating client libraries
- Validation & UI for seleting this aggregation

## How did you test this code?

Extensive unit tests

### CODE REVIEW

**Review by EDsCODE — COMMENTED** [review]
Overall, looks good. The naming is getting confusing (noted below)

**Comment by EDsCODE** [comment]
Mistake commits. Computer lagged and was showing wrong branch

**Comment by macobo** [comment]
ping @EDsCODE for the full review.

**Review by EDsCODE — APPROVED** [review]
apart from minor comments above, this lgtm

**Pull request merged**
