### PR TITLE
Enable support for Autocapture events in correlations - UI

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

Boom:

image  

Now Autocapture on elements get their own correlation row (see last row in above^). @paolodamico would like this xD.

I'm pretty sure we'd have to tweak things based on exclusions to figure out what works here and what doesn't, but want to get this in so I can actually play around with this^ (once Harry's PR for exclusions everywhere is in).

## How did you test this code?

See things look like the screenshot^

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]

**Comment by mariusandra** [comment]
This screenshot needs to be on the posthog homepage as the first thing you see:

image

**Comment by marcushyett-ph** [comment]
@neilkakkar  what was the success event for this example funnel?

@mariusandra funnels nailed?

**Comment by neilkakkar** [comment]
Since this was on local, there's just one person doing things (me), and I clicked around a lot to get autocapture to give me data, so don't take it at face value.

The funnel was: `filters set` -> `filters set`. 

But, once exclusions are in, this should start working well on Production (right now $feature-flags have overwhelmingly more success counts, which drown out all these events), and we can then start testing how well this does.

**Comment by marcushyett-ph** [comment]
Haha cool - thanks for the context - excited to have a play in Prod

**Comment by mariusandra** [comment]
@marcushyett-ph I think we nailed so hard we cracked the board.

**Pull request merged**
