### PR TITLE
refactor(sidebar): Revamp pinned dashboards empty state

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Things were kind of misaligned (and I'm not sure fully grammatical) in the Pinned dashboards list empty state.

before

## Changes

Revamped the empty state look:

after

### CODE REVIEW

**Review by clarkus — APPROVED** [review]
How about "There are no pinned dashboards. Once you pin a dashboard, it will display here." We might also consider using the stacked layout where the icon is on top and the description is below. Not a huge deal, but it'd align to our other empty states and might consolidated the pattern.

**Comment by Twixes** [comment]
I tried such a layout out, but the empty state is then very wordy and large, when normally this popover is quite compact, so I'm not sure how to make this that much nicer (perhaps I'm not using the right pattern). Though this seems to be an improvement already. WDYT?

**Comment by clarkus** [comment]
I [redrew the empty state](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10288%3A42328) at the same width with a smaller-form message. I am mostly concerned with the content of the empty state, not so much the layout. 

Screen Shot 2022-05-17 at 9 02 04 AM

**Comment by Twixes** [comment]
Thank you! I will merge this for now, but I'll use the more proper empty state in a separate PR.

**Pull request merged**
