### PR TITLE
Only allow using aggregate functions on numerical properties

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This is a change to implement https://github.com/PostHog/posthog/pull/1217#issuecomment-661864870. Only event properties that have at least one occurrence of type `number` will be allowed in aggregate function trends (sum, average etc.). If a user has no such properties, aggregate functions will be grayed out.

No numerical properties

### CODE REVIEW

**Comment by timgl** [comment]
Tested this and event did an explicit event with a number (`posthog.capture('test event', {a_number: 12})`) but the options were still greyed out

**Comment by Twixes** [comment]
Should be OK now. @timgl

**Comment by Twixes** [comment]
Actually I misinterpreted the issue. Turns out that there was a mishap in the code updating `event_properties_numerical` and it just… didn't do anything for the past month. I didn't monitor properly whether it's functioning as supposed to, so this just slipped up. That means the frontend part of this PR will need to wait some more for events to be ingested.
Alternatively I could just write a migration that'd just check every past event, which'd be way more reliable anyway, but pretty processing-intensive. Not sure how well that'd work on the production Postgres DB.

**Comment by Twixes** [comment]
This is now fixed in master, but from my tests it's uncompletely unfeasible to do event a `COUNT(*)` on our production Postgres DB, much less select every event and update each team based on that, so best to just let this PR wait for a while.

**Pull request merged**
