### PR TITLE
Show user hash in events table for identified users with only distinct ids

### LINKED ISSUE #5510: Show IDs for identified users on events table
## Is your feature request related to a problem?

I'm unable to discern between different identified users triggering events if they have no email or name set.

Screenshot 2021-08-09 at 11 09 31

The distinct ID might also be something that means something to me, so would be useful to see it.

## Describe the solution you'd like

Show me a Distinct ID for identified users on the events table.

## Describe alternatives you've considered

Keep as is.

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

closes #5510 

moves set up of a PersonHeader into a logic and changes display for identified user with only distinct ids from "no email or name set" to "Identified user ${userhash}"

## How did you test this code?

with unit tests and by running locally

### CODE REVIEW

**Comment by pauldambra** [comment]
hmmm, tests are failing because kea logic keys don't work the way I thought 🤔 

changed to draft until I can resolve that

**Comment by pauldambra** [comment]
OK, I think the checks will pass this time.

Adding @mariusandra as a reviewer since I've tried to be clever with Kea keys and could have accidentally been stupid instead :)

**Comment by yakkomajuri** [comment]
I know I opened the issue for this but will pass this review on to core exp. people if ok. Already a bit overwhelmed this week with stuff to do

**Review by mariusandra — COMMENTED** [review]
Some flyby thoughts

**Pull request merged**
