### PR TITLE
refactor(funnels): Overhauled funnel results table

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Currently in top-to-bottom funnel layout we show a table with detailed results below the funnel bars. Soon, this table will also be used in the left-to-right layout to improve its experience, so the table is in dire need of an overhaul. [Design by Chris in Figma.](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8161%3A46841)

## Changes

Implements the fresh design.
WIP, so I'll post screenshots in a comment later.

## How did you test this code?

TBD, but this is in Storybook.

### CODE REVIEW

**Comment by Twixes** [comment]
This replaces the old table in top-to-bottom funnel steps view. A follow-up PR will also make use of it in left-to-right view, but that will also need new step bars.

As an aside, I'm in favor of removing top-to-bottom view, as it's practically unused – [see insight](https://app.posthog.com/insights/8pCB1UIm).

### Before
Screen Shot 2022-04-11 at 20 53 46

### After
Screen Shot 2022-04-11 at 20 51 55

**Comment by clarkus** [comment]
I know this is still in draft, but I did notice that there is some additional horizontal padding on the linked cell contents for completed counts. It's a minor thing, but in super dense tables like this one, even a little mis-alignment can throw off your ability to scan the values. Looks super good other than that minor nit.

**Comment by clarkus** [comment]
> As an aside, I'm in favor of removing top-to-bottom view, as it's practically unused – [see insight](https://app.posthog.com/insights/8pCB1UIm).

Worth mentioning that this layout option is in a non-standard place compared to other insights. It could be that users just aren't discovering it for some reason. The l-t-r is also the default and shows a ton more information, so maybe it's a signal that this level of detail is more valuable. The simpler top-to-bottom layout scales to be more readable in some viewport sizes and could be a more approachable options for embedding and other forms of sharing. Before we remove it, I'd like to better understand why it isn't being used and maybe experiment with other placements for the layout control. I am not against removing it, but I think there could be some value there that we might just not be seeing because of some placement decisions.

**Review by mariusandra — CHANGES_REQUESTED** [review]
Agreed with @clarkus re padding. The dropped numbers are also not aligned with the column header:

image

However, without a breakdown, the table is rather empty:

image

**Comment by Twixes** [comment]
Oh sorry Chris, forgot to mark this ready for review. Good catch with padding there, fixed.
@marius :+1: Both should be fixed now.

As for the top-to-bottom layout, I agree it's not promoted convincingly. If it were clearly useful over left-to-right though, I'd expect even a bit more usage. At the same time, I'd argue it's more straightforward from both user and technical perspectives to offer one refined (perhaps responsive) view rather than maintaining two separate experiences (`funnelLogic` is IMO overcomplicated because of this).

**Review by mariusandra — APPROVED** [review]

**Pull request merged**
