### PR TITLE
Show only spinner when loading for funnels

### LINKED ISSUE #5445: Showing spinner and warning at the same time
## Bug description

We currently show a spinner and a warning simultaneously when triggering a funnels query:

image

## Expected behavior

We should only show a warning when the page is not in a loading state.

## How to reproduce

1. Go to funnels
2. Run any slow-ish funnels query
3. See the warning and the spinner at the same time

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Screen Shot 2021-08-04 at 11 39 11 AM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by marcushyett-ph** [comment]
Love this one line change... just waiting for it to deploy and I'll test it on the branch

**Comment by marcushyett-ph** [comment]
I see some quite weird spacing when I tested it: anything I've done wrong?

**
image
**

**Comment by liyiy** [comment]
Oh that's because I didn't check it on the postgres version 🤧, just fixed it

Screen Shot 2021-08-05 at 9 28 08 AM

**Comment by marcushyett-ph** [comment]
Perfect!

**Review by marcushyett-ph — APPROVED** [review]
Amazing thanks!

**Pull request merged**
