### PR TITLE
Add DEBUG overlay bar

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

@mariusandra mentioned this way of reminding on the frontend that DEBUG is enabled:

Apprentus staging bar

This is a similar implementation of the idea:

Desktop tricolor
Mobile tricolor

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey, looks very cool! 

In my last job, that "debug toolbar" worked well, but we quickly needed one feature: to be able to close/hide it sometimes. For example for screenshots, etc. Could you implement some "X" button as well?

Regarding the git revision - it's actually not *that* important. The screenshot I sent was from the staging server, where this is all the information I had. Under dev mode I was actually showing the active branch instead. I think we could also show the branch here.

**Comment by Twixes** [comment]
Take a look at this then:

Debug toolbar with changes

**Comment by mariusandra** [comment]
Looks great on the screenshot!

I tried it and this is what it looked like on mobile:

image

The 4th row with the "X" is a bit much I think. Could we perhaps even fit it in one line on mobile? Just skip the labels and keep the "DEBUG", "debug-bar", "commit ID" data?

**Comment by mariusandra** [comment]
I'm not sure why it shows "unknown" on the screenshot. I didn't reload the sever, so that might be it. After reloading it works and thereafter if I change the branch without reloading the server, it updates it automatically.

A few other nits could be to make the branch and commit links to github... :)

**Comment by Twixes** [comment]
It should fit in one line on mobile now.

**Comment by timgl** [comment]
I love how we could have gone with something that didn't look very nice but instead decided to make it look awesome, even if it is mostly internal.

It would be good to make the first panel red and add an explicit warning that running in DEBUG mode is not recommended in production

**Comment by mariusandra** [comment]
@timgl but then it won't look like a squished logo anymore :D

image
image

**Comment by timgl** [comment]
Ha yeah ok but the point is it's a warning/error? You could move that message to the middle maybe?

**Comment by yakkomajuri** [comment]
This design is dope

**Comment by Twixes** [comment]
I think this should be alarming enough?

DEBUG

**Pull request merged**
