### PR TITLE
chore: cleanup old feature flags and person on events instance setting

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

Cleans up old person on events instance setting.

Also, realised that we never released the funnel `BREAKDOWN_ATTRIBUTION` for self-hosted 😱  (cc: @joethreepwood , can we mention this in the array? Minor thing, docs here: https://posthog.com/manual/funnels#choosing-breakdown-property-behaviour )

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by pauldambra** [comment]
@neilkakkar :'(

`would reformat /home/runner/work/posthog/posthog/gunicorn.config.py`

Have seen this on another branch too 🤔

**Comment by neilkakkar** [comment]
I fixed it in another PR of fine so plis squeeze this one in 🇯🇴

**Review by pauldambra — APPROVED** [review]
clearly trying for a last minute release breaker :)

**Comment by pauldambra** [comment]
cherry-picked into 1.39.0

**Pull request merged**
