### PR TITLE
Add papercups to app

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Papercups is an OS alternative for intercom

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
This is pretty good! Definitely not Intercom level, but will do. What does this look like from our side?

**Comment by timgl** [comment]
There's a #papercups channel you can use to respond to messages coming in !

**Comment by Twixes** [comment]
That's handy 👍

**Comment by reichert621** [comment]
hey tim! thanks for giving us a shot 😛 just wanted to let you know you can also pass in some user info if you have it available to identify the person you're talking to! (see https://github.com/papercups-io/chat-widget#using-in-html)

let us know if you have any feedback!

**Pull request merged**
