### PR TITLE
chore(ingestion): re-introduce rdkafka consumer alongside kafkajs

### PR DESCRIPTION
**Pull request by xvello**
## Changes

- Copy `eachBatchParallelIngestion` into `eachBatchLegacyIngestion` to keep it around, duplicate some code instead of trying to refactor
- Cherry pick https://github.com/PostHog/posthog/pull/15695 again
- Add `KAFKA_CONSUMPTION_USE_RDKAFKA` option, make it read by ingestion and overflow consumers, to chose what consumer and processing loop to use
- Run functional tests with two values of `KAFKA_CONSUMPTION_USE_RDKAFKA` for the transition. Unit tests don't need it as they are duplicated in code.

The PR is designed so that removing the kafkajs code will be simple, without moving around the rdkafka code. It should be reviewed commit per commit to track the copied code before it is modified.

### CODE REVIEW

**Comment by hazzadous** [comment]
😬 😅

**Review by hazzadous — APPROVED** [review]
I _think_ it looks good 🤞

**Review by hazzadous — COMMENTED** [review]
I believe we also spoke about going with an eager partition strategy. I guess we can do as a followup?

**Comment by xvello** [comment]
Thanks Harry!

Since cooperative rebalancing is the biggest immediate win from the rdkafka migration, I changed my mind and preferred keeping it.
As we'll control the rollout per deployment with the envvar, I think that the `k delete rs` manual operation is not as much of a hassle as when we had 4 deployments over two regions. I'll need to document that in the ingestion runbook though!

**Comment by hazzadous** [comment]
> As we'll control the rollout per deployment with the envvar

👍 at least it isn't rollback and revert this time, and we don't have to keep blocking the pipeline!

**Comment by xvello** [comment]
Diffing `master` with this branch to double-check a smaller diff:

### Kafkajs code path

```diff
--- posthog/plugin-server/src/main/ingestion-queues/batch-processing/each-batch-ingestion.ts	2023-06-20 14:13:42
+++ target/plugin-server/src/main/ingestion-queues/batch-processing/each-batch-ingestion-kafkajs.ts	2023-06-20 14:13:56
@@ -1,38 +1,27 @@
 import * as Sentry from '@sentry/node'
 import { EachBatchPayload, KafkaMessage } from 'kafkajs'
-import { Counter, exponentialBuckets, Histogram } from 'prom-client'
 
 import { KAFKA_EVENTS_PLUGIN_INGESTION_DLQ, KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW } from '../../../config/kafka-topics'
 import { Hub, PipelineEvent, WorkerMethods } from '../../../types'
-import { formPipelineEvent } from '../../../utils/event'
+import { normalizeEvent } from '../../../utils/event'
 import { status } from '../../../utils/status'
 import { ConfiguredLimiter, LoggingLimiter, WarningLimiter } from '../../../utils/token-bucket'
 import { EventPipelineResult } from '../../../worker/ingestion/event-pipeline/runner'
 import { captureIngestionWarning } from '../../../worker/ingestion/utils'
 import { ingestionPartitionKeyOverflowed } from '../analytics-events-ingestion-consumer'
-import { IngestionConsumer } from '../kafka-queue'
+import { KafkaJSIngestionConsumer } from '../kafka-queue'
 import { latestOffsetTimestampGauge } from '../metrics'
+import { IngestionOverflowMode } from './each-batch-ingestion'
+import {
+    ingestionParallelism,
+    ingestionParallelismPotential,
+    kafkaBatchOffsetCommitted,
+    kafkaBatchStart,
+} from './metrics'
 
 // Must require as `tsc` strips unused `import` statements and just requiring this seems to init some globals
 require('@sentry/tracing')
 
-// The following two counters can be used to see how often we start,
-// but fail to commit offsets, which can cause duplicate events
-const kafkaBatchStart = new Counter({
-    name: 'ingestion_kafka_batch_start',
-    help: 'Number of times we have started working on a kafka batch',
-})
-const kafkaBatchOffsetCommitted = new Counter({
-    name: 'ingestion_kafka_batch_committed_offsets',
-    help: 'Number of times we have committed kafka offsets',
-})
-
-export enum IngestionOverflowMode {
-    Disabled,
-    Reroute,
-    Consume,
-}
-
 type IngestionSplitBatch = {
     toProcess: { message: KafkaMessage; pluginEvent: PipelineEvent }[][]
     toOverflow: KafkaMessage[]
@@ -45,20 +34,25 @@
     promises?: Array<Promise<void>>
 }
 
-export async function eachBatchParallelIngestion(
+/**
+ * Legacy consumer loop that uses the kafkajs consumer, kept as a fallback while we iterate on
+ * eachBatchParallelIngestion and rdkafka.
+ * TODO: delete as soon as rdkafka is tuned and ready for prime time.
+ */
+export async function eachBatchLegacyIngestion(
     { batch, resolveOffset, heartbeat, commitOffsetsIfNecessary, isRunning, isStale }: EachBatchPayload,
-    queue: IngestionConsumer,
+    queue: KafkaJSIngestionConsumer,
     overflowMode: IngestionOverflowMode
 ): Promise<void> {
-    async function eachMessage(event: PipelineEvent, queue: IngestionConsumer): Promise<IngestResult> {
+    async function eachMessage(event: PipelineEvent, queue: KafkaJSIngestionConsumer): Promise<IngestResult> {
         return ingestEvent(queue.pluginsServer, queue.workerMethods, event)
     }
 
     const batchStartTimer = new Date()
     const metricKey = 'ingestion'
-    const loggingKey = `each_batch_parallel_ingestion`
+    const loggingKey = `each_batch_legacy_ingestion`
 
-    const transaction = Sentry.startTransaction({ name: `eachBatchParallelIngestion` }, { topic: queue.topic })
+    const transaction = Sentry.startTransaction({ name: `eachBatchLegacyIngestion` }, { topic: queue.topic })
 
     try {
         /**
@@ -67,7 +61,7 @@
          * and a separate array for single messages, but let's look at profiles before optimizing.
          */
         const prepareSpan = transaction.startChild({ op: 'prepareBatch' })
-        const splitBatch = splitIngestionBatch(batch.messages, overflowMode)
+        const splitBatch = splitKafkaJSIngestionBatch(batch.messages, overflowMode)
         splitBatch.toProcess.sort((a, b) => a.length - b.length)
 
         queue.pluginsServer.statsd?.histogram('ingest_event_batching.input_length', batch.messages.length, {
@@ -79,6 +73,7 @@
         prepareSpan.finish()
 
         const processingPromises: Array<Promise<void>> = []
+
         async function processMicroBatches(
             batches: { message: KafkaMessage; pluginEvent: PipelineEvent }[][]
         ): Promise<void> {
@@ -232,7 +227,7 @@
     }
 }
 
-export async function ingestEvent(
+async function ingestEvent(
     server: Hub,
     workerMethods: WorkerMethods,
     event: PipelineEvent,
@@ -260,7 +255,7 @@
     return `${pluginEvent.team_id ?? pluginEvent.token}:${pluginEvent.distinct_id}`
 }
 
-async function emitToOverflow(queue: IngestionConsumer, kafkaMessages: KafkaMessage[]) {
+async function emitToOverflow(queue: KafkaJSIngestionConsumer, kafkaMessages: KafkaMessage[]) {
     await Promise.all(
         kafkaMessages.map((message) =>
             queue.pluginsServer.kafkaProducer.queueMessage(
@@ -274,7 +269,7 @@
     )
 }
 
-export function splitIngestionBatch(
+export function splitKafkaJSIngestionBatch(
     kafkaMessages: KafkaMessage[],
     overflowMode: IngestionOverflowMode
 ): IngestionSplitBatch {
@@ -344,16 +339,14 @@
     }
 }
 
-const ingestionParallelism = new Histogram({
-    name: 'ingestion_batch_parallelism',
-    help: 'Processing parallelism per ingestion consumer batch',
-    labelNames: ['overflow_mode'],
-    buckets: exponentialBuckets(1, 2, 7), // Up to 64
-})
-
-const ingestionParallelismPotential = new Histogram({
-    name: 'ingestion_batch_parallelism_potential',
-    help: 'Number of eligible parts per ingestion consumer batch',
-    labelNames: ['overflow_mode'],
-    buckets: exponentialBuckets(1, 2, 7), // Up to 64
-})
+function formPipelineEvent(message: KafkaMessage): PipelineEvent {
+    // TODO: inefficient to do this twice?
+    const { data: dataStr, ...rawEvent } = JSON.parse(message.value!.toString())
+    const combinedEvent = { ...JSON.parse(dataStr), ...rawEvent }
+    const event: PipelineEvent = normalizeEvent({
+        ...combinedEvent,
+        site_url: combinedEvent.site_url || null,
+        ip: combinedEvent.ip || null,
+    })
+    return event
+}
```

### RDKafka code path (new branch vs fea9e4d7 to before the revert)

```diff
--- posthog/plugin-server/src/main/ingestion-queues/batch-processing/each-batch-ingestion.ts	2023-06-20 14:17:08
+++ target/plugin-server/src/main/ingestion-queues/batch-processing/each-batch-ingestion.ts	2023-06-20 14:13:56
@@ -1,16 +1,22 @@
 import * as Sentry from '@sentry/node'
-import { Message } from 'node-rdkafka-acosom'
-import { exponentialBuckets, Histogram } from 'prom-client'
+import { Message, MessageHeader } from 'node-rdkafka-acosom'
 
-import { KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW } from '../../../config/kafka-topics'
+import { KAFKA_EVENTS_PLUGIN_INGESTION_DLQ, KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW } from '../../../config/kafka-topics'
 import { Hub, PipelineEvent, WorkerMethods } from '../../../types'
 import { formPipelineEvent } from '../../../utils/event'
 import { status } from '../../../utils/status'
 import { ConfiguredLimiter, LoggingLimiter, WarningLimiter } from '../../../utils/token-bucket'
+import { EventPipelineResult } from '../../../worker/ingestion/event-pipeline/runner'
 import { captureIngestionWarning } from '../../../worker/ingestion/utils'
 import { ingestionPartitionKeyOverflowed } from '../analytics-events-ingestion-consumer'
 import { IngestionConsumer } from '../kafka-queue'
 import { latestOffsetTimestampGauge } from '../metrics'
+import {
+    ingestionParallelism,
+    ingestionParallelismPotential,
+    kafkaBatchOffsetCommitted,
+    kafkaBatchStart,
+} from './metrics'
 
 // Must require as `tsc` strips unused `import` statements and just requiring this seems to init some globals
 require('@sentry/tracing')
@@ -22,17 +28,24 @@
 }
 
 type IngestionSplitBatch = {
-    toProcess: PipelineEvent[][]
+    toProcess: { message: Message; pluginEvent: PipelineEvent }[][]
     toOverflow: Message[]
 }
 
+// Subset of EventPipelineResult to make sure we don't access what's exported for the tests
+type IngestResult = {
+    // Promises that the batch handler should await on before committing offsets,
+    // contains the Kafka producer ACKs, to avoid blocking after every message.
+    promises?: Array<Promise<void>>
+}
+
 export async function eachBatchParallelIngestion(
     messages: Message[],
     queue: IngestionConsumer,
     overflowMode: IngestionOverflowMode
 ): Promise<void> {
-    async function eachMessage(event: PipelineEvent, queue: IngestionConsumer): Promise<void> {
-        await ingestEvent(queue.pluginsServer, queue.workerMethods, event)
+    async function eachMessage(event: PipelineEvent, queue: IngestionConsumer): Promise<IngestResult> {
+        return ingestEvent(queue.pluginsServer, queue.workerMethods, event)
     }
 
     const batchStartTimer = new Date()
@@ -47,6 +60,7 @@
          * We're sorting with biggest last and pop()ing. Ideally, we'd use a priority queue by length
          * and a separate array for single messages, but let's look at profiles before optimizing.
          */
+        const prepareSpan = transaction.startChild({ op: 'prepareBatch' })
         const splitBatch = splitIngestionBatch(messages, overflowMode)
         splitBatch.toProcess.sort((a, b) => a.length - b.length)
 
@@ -56,8 +70,12 @@
         queue.pluginsServer.statsd?.histogram('ingest_event_batching.batch_count', splitBatch.toProcess.length, {
             key: metricKey,
         })
+        prepareSpan.finish()
 
-        async function processMicroBatches(batches: PipelineEvent[][]): Promise<void> {
+        const processingPromises: Array<Promise<void>> = []
+        async function processMicroBatches(
+            batches: { message: Message; pluginEvent: PipelineEvent }[][]
+        ): Promise<void> {
             let currentBatch
             let processedBatches = 0
             while ((currentBatch = batches.pop()) !== undefined) {
@@ -66,9 +84,10 @@
                     data: { batchLength: currentBatch.length },
                 })
 
+                // Process overflow ingestion warnings
                 if (overflowMode == IngestionOverflowMode.Consume && currentBatch.length > 0) {
-                    const team = await queue.pluginsServer.teamManager.getTeamForEvent(currentBatch[0])
-                    const distinct_id = currentBatch[0].distinct_id
+                    const team = await queue.pluginsServer.teamManager.getTeamForEvent(currentBatch[0].pluginEvent)
+                    const distinct_id = currentBatch[0].pluginEvent.distinct_id
                     if (team && WarningLimiter.consume(`${team.id}:${distinct_id}`, 1)) {
                         captureIngestionWarning(queue.pluginsServer.db, team.id, 'ingestion_capacity_overflow', {
                             overflowDistinctId: distinct_id,
@@ -76,9 +95,52 @@
                     }
                 }
 
-                for (const message of currentBatch) {
-                    await eachMessage(message, queue)
+                // Process every message sequentially, stash promises to await on later
+                for (const { message, pluginEvent } of currentBatch) {
+                    try {
+                        const result = await eachMessage(pluginEvent, queue)
+                        if (result.promises) {
+                            processingPromises.push(...result.promises)
+                        }
+                    } catch (error) {
+                        status.error('🔥', `Error processing message`, {
+                            stack: error.stack,
+                            error: error,
+                        })
+
+                        // If there error is a non-retriable error, push
+                        // to the dlq and commit the offset. Else raise the
+                        // error.
+                        //
+                        // NOTE: there is behavior to push to a DLQ at the
+                        // moment within EventPipelineRunner. This doesn't work
+                        // so well with e.g. messages that when sent to the DLQ
+                        // is it's self too large. Here we explicitly do _not_
+                        // add any additional metadata to the message. We might
+                        // want to add some metadata to the message e.g. in the
+                        // header or reference e.g. the sentry event id.
+                        //
+                        // TODO: property abstract out this `isRetriable` error
+                        // logic. This is currently relying on the fact that
+                        // node-rdkafka adheres to the `isRetriable` interface.
+                        if (error?.isRetriable === false) {
+                            const sentryEventId = Sentry.captureException(error)
+                            const headers: MessageHeader[] = message.headers ?? []
+                            headers.push({ ['sentry-event-id']: sentryEventId })
+                            headers.push({ ['event-id']: pluginEvent.uuid })
+                            await queue.pluginsServer.kafkaProducer.produce({
+                                topic: KAFKA_EVENTS_PLUGIN_INGESTION_DLQ,
+                                value: message.value,
+                                key: message.key,
+                                headers: headers,
+                                waitForAck: true,
+                            })
+                        } else {
+                            throw error
+                        }
+                    }
                 }
+
                 processedBatches++
                 batchSpan.finish()
             }
@@ -105,12 +167,23 @@
                 overflow_mode: IngestionOverflowMode[overflowMode],
             })
             .observe(splitBatch.toProcess.length)
+        kafkaBatchStart.inc() // just before processing any events
         const tasks = [...Array(parallelism)].map(() => processMicroBatches(splitBatch.toProcess))
         if (splitBatch.toOverflow.length > 0) {
+            const overflowSpan = transaction.startChild({
+                op: 'emitToOverflow',
+                data: { eventCount: splitBatch.toOverflow.length },
+            })
             tasks.push(emitToOverflow(queue, splitBatch.toOverflow))
+            overflowSpan.finish()
         }
+
         await Promise.all(tasks)
 
+        const awaitSpan = transaction.startChild({ op: 'awaitACKs', data: { promiseCount: processingPromises.length } })
+        await Promise.all(processingPromises)
+        awaitSpan.finish()
+
         for (const message of messages) {
             if (message.timestamp) {
                 latestOffsetTimestampGauge
@@ -118,6 +191,7 @@
                     .set(message.timestamp)
             }
         }
+        kafkaBatchOffsetCommitted.inc() // successfully processed batch, consumer will commit offsets
 
         status.debug(
             '🧩',
@@ -131,12 +205,12 @@
     }
 }
 
-export async function ingestEvent(
+async function ingestEvent(
     server: Hub,
     workerMethods: WorkerMethods,
     event: PipelineEvent,
     checkAndPause?: () => void // pause incoming messages if we are slow in getting them out again
-): Promise<void> {
+): Promise<EventPipelineResult> {
     const eachEventStartTimer = new Date()
 
     checkAndPause?.()
@@ -144,11 +218,12 @@
     server.statsd?.increment('kafka_queue_ingest_event_hit', {
         pipeline: 'runEventPipeline',
     })
-    await workerMethods.runEventPipeline(event)
+    const result = await workerMethods.runEventPipeline(event)
 
     server.statsd?.timing('kafka_queue.each_event', eachEventStartTimer)
-
     countAndLogEvents()
+
+    return result
 }
 
 let messageCounter = 0
@@ -185,7 +260,19 @@
         toProcess: [],
         toOverflow: [],
     }
-    const batches: Map<string, PipelineEvent[]> = new Map()
+
+    if (overflowMode === IngestionOverflowMode.Consume) {
+        /**
+         * Grouping by distinct_id is inefficient here, because only a few ones are overflowing
+         * at a time. When messages are sent to overflow, we already give away the ordering guarantee,
+         * so we just return batches of one to increase concurrency.
+         * TODO: add a PipelineEvent[] field to IngestionSplitBatch for batches of 1
+         */
+        output.toProcess = kafkaMessages.map((m) => new Array({ message: m, pluginEvent: formPipelineEvent(m) }))
+        return output
+    }
+
+    const batches: Map<string, { message: Message; pluginEvent: PipelineEvent }[]> = new Map()
     for (const message of kafkaMessages) {
         if (overflowMode === IngestionOverflowMode.Reroute && message.key == null) {
             // Overflow detected by capture, reroute to overflow topic
@@ -206,9 +293,9 @@
         }
         const siblings = batches.get(eventKey)
         if (siblings) {
-            siblings.push(pluginEvent)
+            siblings.push({ message, pluginEvent })
         } else {
-            batches.set(eventKey, [pluginEvent])
+            batches.set(eventKey, [{ message, pluginEvent }])
         }
     }
     output.toProcess = Array.from(batches.values())
@@ -229,17 +316,3 @@
         messageLogDate = now
     }
 }
-
-const ingestionParallelism = new Histogram({
-    name: 'ingestion_batch_parallelism',
-    help: 'Processing parallelism per ingestion consumer batch',
-    labelNames: ['overflow_mode'],
-    buckets: exponentialBuckets(1, 2, 7), // Up to 64
-})
-
-const ingestionParallelismPotential = new Histogram({
-    name: 'ingestion_batch_parallelism_potential',
-    help: 'Number of eligible parts per ingestion consumer batch',
-    labelNames: ['overflow_mode'],
-    buckets: exponentialBuckets(1, 2, 7), // Up to 64
-})

```

### Producer

```diff
--- posthog/plugin-server/src/utils/db/kafka-producer-wrapper.ts	2023-06-20 14:17:08
+++ target/plugin-server/src/utils/db/kafka-producer-wrapper.ts	2023-06-20 14:13:56
@@ -3,7 +3,7 @@
 
 import { disconnectProducer, flushProducer, produce } from '../../kafka/producer'
 import { status } from '../../utils/status'
-import { DependencyUnavailableError } from './error'
+import { DependencyUnavailableError, MessageSizeTooLarge } from './error'
 
 /** This class is a wrapper around the rdkafka producer, and does very little.
  * It used to be a wrapper around KafkaJS, but we switched to rdkafka because of
@@ -37,7 +37,7 @@
         topic: string
         headers?: MessageHeader[]
         waitForAck?: boolean
-    }) {
+    }): Promise<void> {
         try {
             return await produce({
                 producer: this.producer,
@@ -46,6 +46,8 @@
                 value: value,
                 headers: headers,
                 waitForAck: waitForAck,
+            }).then((_) => {
+                return // Swallow the returned offsets, and return a void for easier typing
             })
         } catch (error) {
             status.error('⚠️', 'kafka_produce_error', { error: error, topic: topic })
@@ -54,6 +56,8 @@
                 // If we get a retriable error, bubble that up so that the
                 // caller can retry.
                 throw new DependencyUnavailableError(error.message, 'Kafka', error)
+            } else if ((error as LibrdKafkaError).code === 10) {
+                throw new MessageSizeTooLarge(error.message, error)
             }
 
             throw error
```

```diff
--- posthog/plugin-server/src/main/ingestion-queues/kafka-queue.ts	2023-06-20 14:17:08
+++ target/plugin-server/src/main/ingestion-queues/kafka-queue.ts	2023-06-20 14:13:56
@@ -43,7 +43,11 @@
         this.kafka = pluginsServer.kafka!
         this.topic = topic
         this.consumerGroupId = consumerGroupId
-        this.consumer = KafkaJSIngestionConsumer.buildConsumer(this.kafka, consumerGroupId)
+        this.consumer = KafkaJSIngestionConsumer.buildConsumer(
+            this.kafka,
+            consumerGroupId,
+            this.pluginsServer.KAFKA_CONSUMPTION_REBALANCE_TIMEOUT_MS
+        )
         this.wasConsumerRan = false
 
         // TODO: remove `this.workerMethods` and just rely on
@@ -97,6 +101,7 @@
             // KafkaJS batching: https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch
             await this.consumer.run({
                 eachBatchAutoResolve: false,
+
                 autoCommitInterval: 1000, // autocommit every 1000 ms…
                 autoCommitThreshold: 1000, // …or every 1000 messages, whichever is sooner
                 partitionsConsumedConcurrently: this.pluginsServer.KAFKA_PARTITIONS_CONSUMED_CONCURRENTLY,
@@ -172,11 +177,12 @@
         return emitConsumerGroupMetrics(this.consumer, this.consumerGroupMemberId, this.pluginsServer)
     }
 
-    private static buildConsumer(kafka: Kafka, groupId: string): Consumer {
+    private static buildConsumer(kafka: Kafka, groupId: string, rebalanceTimeout: number | null): Consumer {
         const consumer = kafka.consumer({
             // NOTE: This should never clash with the group ID specified for the kafka engine posthog/ee/clickhouse/sql/clickhouse.py
             groupId,
             readUncommitted: false,
+            rebalanceTimeout: rebalanceTimeout ?? undefined,
         })
         setupEventHandlers(consumer)
         return consumer
@@ -228,6 +234,8 @@
 
     async start(): Promise<BatchConsumer> {
         this.consumer = await startBatchConsumer({
+            batchingTimeoutMs: this.pluginsServer.KAFKA_CONSUMPTION_BATCHING_TIMEOUT_MS,
+            consumerErrorBackoffMs: this.pluginsServer.KAFKA_CONSUMPTION_ERROR_BACKOFF_MS,
             connectionConfig: createRdConnectionConfigFromEnvVars(this.pluginsServer as KafkaConfig),
             topic: this.topic,
             groupId: this.consumerGroupId,

```

**Pull request merged**
