### PR TITLE
add math.round to funnel steps

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

2min PR before call. PRs over issues. Hope I'm helping cut down the number of bugs from Core Experience's list.

### Funnels before:

Screenshot 2021-07-16 at 13 58 27

### Funnels now:

Screenshot 2021-07-16 at 13 55 10

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by Twixes** [comment]
I think we should be rounding to 2 decimal places (this may matter for large scale customers), and do this on the backend (in the ClickHouse query ideally).

**Comment by Twixes** [comment]
Hm, well, maybe not in the backend actually, as we're using `calcPercentage` in these places. So I reckon the rounding should live only inside `calcPercentage`.

**Comment by yakkomajuri** [comment]
didn't add to `calcPercentage` as I didn't check all the places using it and don't know how many decimal places they want. I just know old funnels use integers.

This is almost like an issue though so anyone feel free to hijack the PR.

**Comment by mariusandra** [comment]
I think it's perfectly fine to do the rounding in the frontend. In fact, we need to round numbers everywhere in the frontend, as who knows what data sources these beautiful 😍 graph components will eventually be connected to.

**Comment by mariusandra** [comment]
Though for this PR, first, thanks! 👍 , and second I'd indeed add more decimal points. 2 is probably a good bet, though I don't know what requirements our users will have. That might not be enough when you have very narrow numbers to compare.

**Comment by yakkomajuri** [comment]
originally I had 2 decimal points but then looked at old funnels and changed it. again, do with this as you wish :D more just pointing out the bug

**Pull request merged**
