### PR TITLE
Paths highlighting for path start and end

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Screen Shot 2021-10-06 at 6 49 30 PM

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by liyiy** [comment]
Also accounting for path starts/ends that come from funnels. Though from what I've been seeing, the paths only seem to include the start/ends when it's an in between funnel path? Plz correct me if wrong

Screen Shot 2021-10-07 at 1 50 19 AM

**Review by clarkus — CHANGES_REQUESTED** [review]
This is looking good to me so far. I did find one small confusing thing when applying end points to the visualization. Maybe it's my data but I never see that end point highlight unless I also have a start point defined. Is that a known thing, @liyiy?

**Comment by liyiy** [comment]
> This is looking good to me so far. I did find one small confusing thing when applying end points to the visualization. Maybe it's my data but I never see that end point highlight unless I also have a start point defined. Is that a known thing, @liyiy?

In general or for funnel paths? 

For non funnel paths I was able to get one highlighted here with just an end point selected

Screen Shot 2021-10-07 at 11 00 54 AM

**Review by clarkus — APPROVED** [review]
@liyiy It was for non-funnel paths. I have very limited data locally, so I am guessing that might be the problem. The changes look good to me otherwise.

**Comment by EDsCODE** [comment]
> Though from what I've been seeing, the paths only seem to include the start/ends when it's an in between funnel path? Plz correct me if wrong

Start and ends should show up independently

**Comment by liyiy** [comment]
@EDsCODE 

What do I highlight in this case? the start point nodes don't show up (I've tried with the other end too), can you point me to a working example?

https://user-images.githubusercontent.com/25164963/136415620-a318fab3-4d59-4e1b-ab80-6b4cda99f3ed.mov

**Comment by clarkus** [comment]
> What do I highlight in this case? the start point nodes don't show up (I've tried with the other end too), can you point me to a working example?

I'm not sure you can highlight anything in that case - insight loaded would match to multiple items, but for other contexts this is a 1:1 match. I think you'd have to match on some property value instead, right?

**Comment by EDsCODE** [comment]
Mmm, ok for now just highlight if the start point exists but otherwise dont worry about highlighting anything else. There's some data clean up we need to do to guarantee we always show the start/end points

**Pull request merged**
