### PR TITLE
Try to debug redis leak

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Adds a bunch of `ignore_result=True` statements to suspect tasks in the hopes of preventing this: 
image

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by macobo** [comment]
We could also use the global setting: https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-task_ignore_result

I _think_ this means using CELERY_IGNORE_RESULT=True in settings.py

**Comment by mariusandra** [comment]
@macobo that's worth considering and will probably be a wise choice to prevent similar leaks in the future.

Adding the `ignore_result=True`-s that I did, I got this to go to just grow ~10/h, instead of ~4000/h

image

It's still keeps a bunch of them around (list below), but much less.

```
Connecting to redis-shaped-04070 (REDIS_URL):
ec2-23-22-91-243.compute-1.amazonaws.com:19559> KEYS *
1) celery-task-meta-60cbdc64-5bad-4047-92f6-1f445810c94d
2) celery-task-meta-7ee3bb35-fa3d-4c25-a0c1-790e51b75512
3) redbeat:posthog.celery.clean_stale_partials()
4) _kombu.binding.celery
5) celery-task-meta-b94f4faf-7cf3-4884-bb74-919f5b43e8a6
6) celery-task-meta-78851905-8fd4-4e1c-bdde-22cdb2942f0f
7) celery-task-meta-c1f43d6e-5994-47f8-982e-223597e6c07e
8) redbeat:10 sec heartbeat
9) celery-task-meta-4580e22f-2a32-4abc-965b-70997d1b4082
10) celery-task-meta-e4dc7e9f-df86-449e-a0d6-9b5e09fb6821
11) celery-task-meta-14bd2dc4-5b76-48e4-8e0c-597c0944694f
12) redbeat:posthog.celery.status_report()
13) celery-task-meta-688b76a8-f391-48b9-8e6e-9e3610b642f7
14) redbeat:check dashboard items
15) celery-task-meta-0af0a531-2705-435c-a4fe-a69a71196657
16) redbeat::statics
17) redbeat::schedule
18) celery-task-meta-21263c8e-6dd7-4968-aeab-aa7ce8bffc60
19) _kombu.binding.celeryev
20) redbeat:debug
21) celery-task-meta-120d7821-7ab5-494d-a01a-fd20b715631c
22) redbeat:posthog.celery.send_weekly_email_report()
23) celery-task-meta-987789ff-8b4c-451b-8cd1-a7919a347878
24) POSTHOG_HEARTBEAT
25) celery-task-meta-6e60e50e-237a-4f94-ac69-52650052d1a3
26) redbeat:1 sec queue probe
27) _kombu.binding.celery.pidbox
28) redbeat::lock
29) redbeat:posthog.celery.update_event_partitions()
30) celery-task-meta-3b9baacc-e4d1-4d28-bc8c-72eeaf9482c8
```

**Comment by mariusandra** [comment]
I find the following rather humorous:



Scheduled tasks, without explicitly being set `ignore_result=True` in the task pollute redis. It's not a big deal since these keys will expire within 24h and redis tries to delete old expiring keys first if out of memory. 

Surprisingly, this video was taken while `CELERY_IGNORE_RESULT = True` was present in `settings.py`! There seems to be [some fuzz](https://github.com/celery/celery/issues/5398) over this option, so we might need to explicitly set this at every task.

**Comment by mariusandra** [comment]
Right, here's what I found:

1) `CELERY_IGNORE_RESULT = True` applies to all `.delay()` calls (which are a wrapper around `apply_async`).
2) Calling `apply_async` with `CELERY_IGNORE_RESULT=True` does nothing
3) Calling `apply_async`  with `ignore_result=True` as an argument (`process_event.apply_async(args=[...], ignore_result=True)`) has no effect
4) Calling `apply_async` or `delay` on a task like `@shared_task(ignore_result=True)` or `@app.task(ignore_result=True)` ignores the result
5) Scheduled tasks are also not ignored by default, even though that would seem logical. Was not expecting this.

I verified that nobody was ever doing anything with the return value of any task and added `ignore_result=True` to each task, plus the global `CELERY_IGNORE_RESULT=True` setting as well.

I thought about adding `ignore_result=True` to just `.apply_async` tasks, but decided against it. It would be weird and error prone to explicitly add this property to just a few tasks, while leaving the others without the property. In that scenario you could easily switch between the two calling styles and forget to add/remove the property on the task itself. If `ignore_result=True` is on all tasks, it'll remain on all tasks going forward.

**Review by macobo — APPROVED** [review]
Solid work!

**Pull request merged**
