### PR TITLE
chore: allow existing constraints

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We block adding constraints to existing tables because of the risk of locking. But that's what the Django ORM does, so sometimes we'll need to allow it.

See https://github.com/PostHog/posthog/actions/runs/5077280448/jobs/9120371555 for a failing example and https://github.com/PostHog/posthog/blob/57e7ed7cfaff5f6e1b93b253db9c6f6b9815ca75/posthog/migrations/0253_add_async_migration_parameters.py#L9 for where we have a safe workaround for another type of check

## Changes

Allow someone to comment on the Django ORM-generated SQL so that we allow that constraint. This is probably safer than needing hand-cranked migrations to work around the check.

(or this is putting the wrong answer on the internet to shake the correct answer loose)

## How did you test this code?

🙈

### CODE REVIEW

**Comment by pauldambra** [comment]
In this case of https://github.com/PostHog/posthog/pull/15505, we have "only" tens of thousands of rows to be affected. I'm not sure how we can quantify the risk of locking that table.

**Review by benjackwhite — APPROVED** [review]
From my side makes sense and is useful regarding my PR but I don't have the context for the whole locking stuff

**Comment by pauldambra** [comment]
@fuziontech since you forced through the referenced migration...

Any thoughts on letting folk add constraints with a comment like this?

**Comment by pauldambra** [comment]
@fuziontech since you forced through the referenced migration...

Any thoughts on letting folk add constraints with a comment like this?

**Comment by pauldambra** [comment]
another example of this blocking a change...

Django ORM adds a constraint when adding a FK to a table 🤷

**Pull request merged**
