### PR TITLE
fix(funnels): use step.index instead of step.order

### PR DESCRIPTION
**Pull request by hazzadous**
This change updates the base funnel.py to use step.index, as this will
always be an integer whereas step.order can be `None`. I'm not sure what
the difference is between them aside from this.

Note that I have also removed the `order` attribute from the request in
the test. I suspect we should just not have this as a parameter in the
rest api. It doesn't seem like it's ever anything other than the index
of the event in the array. Perhaps there is a use case for it :shrug:

Note also that we now fail the test I changed, as omitting the order in
the request also omits the order in the response. This may not be
desired, as clients (as my test does) may rely on this order attribute
being set.

Refers https://github.com/PostHog/posthog/issues/6941

### CODE REVIEW

**Comment by macobo** [comment]
> It doesn't seem like it's ever anything other than the index of the event in the array.

We have two parallel arrays here (events vs actions) which "order" is used to join in the correct order.

**Comment by hazzadous** [comment]
> We have two parallel arrays here (events vs actions) which "order" is used to join in the correct order.

Ah, right ok I'll check how that affects things

**Comment by neilkakkar** [comment]
`index` is decided using `order`, so for correct results, we'd want the frontend to keep sending `order`. On the backend, using `index` makes sense because it gives a default "order" to steps missing it from FE. (some cases where this is ok, like when dealing with unordered funnels, or only 1 entity)

**Comment by hazzadous** [comment]
> `index` is decided using `order`, so for correct results, we'd want the frontend to keep sending `order`. On the backend, using `index` makes sense because it gives a default "order" to steps missing it from FE. (some cases where this is ok, like when dealing with unordered funnels, or only 1 entity)

@neilkakkar thanks for the info. I was going to make the typing for order as required in the frontend and see where it's getting dropped. But do you think there's explicit handling for unordered funnels that is dropping the `order` property, and that is desired?

**Comment by neilkakkar** [comment]
Nope, I don't think so.

 And this route makes sense too! (as long as we then verify on the backend and don't crash when order doesn't exist, which I think was happening from time to time)

**Comment by hazzadous** [comment]
closing as not a priority atm

**Pull request closed without merging**
