### PR TITLE
Adjust `SessionRecordingsButton` behavior for a single recording

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Button behavior adjustment based on https://github.com/PostHog/posthog/pull/5745#pullrequestreview-739809140 feedback. Change: for a button with a single recording, a click opens the recording, while a hover shows it details. No change for no or multiple recordings.

### CODE REVIEW

**Comment by paolodamico** [comment]
Hey @Twixes! I'm doing a couple of style tweaks so please 🙏  hold off on merging

**Review by paolodamico — APPROVED** [review]
lgtm!

**Comment by paolodamico** [comment]
Did a couple of minor style changes.
1. Use online outlined icon.
2. Remove the dropdown arrow when there's only one recording to make it clear it's a button.

**Comment by Twixes** [comment]
I was thinking about removing the dropdown icon too, but it looks really awkward IMO with that void. Maybe it could be replaced with a different contextual icon, e.g. an arrow right to indicate that clicking will take you to the recording or something like that?

**Comment by paolodamico** [comment]
> I was thinking about removing the dropdown icon too, but it looks really awkward IMO with that void. Maybe it could be replaced with a different contextual icon, e.g. an arrow right to indicate that clicking will take you to the recording or something like that?

Yes! Love that

**Pull request merged**
