### PR TITLE
chore(recordings): use node-librdkafka for ingester production

### PR DESCRIPTION
**Pull request by hazzadous**
Previously we've been using the KafkaJS Producer with a wrapper around
it to handle batching. There are a number of issues with the batching
implementation e.g. not having a way to provide guarantees on delivery
and rather than fix that, we can simply use the librdkafka Producer
which is a lot more mature and battle-tested.

Ultimately we should probably move over to librdkafka for all the plugin server 
operations, but I'm starting with recordings first and just the producer which is a 
little less critical than the other workloads.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by mariusandra** [comment]
We switched away from librdkafka because it was flakey and caused the app to crash in unpredicatble ways :). @Twixes even had to submit [a C++ patch](https://github.com/Blizzard/node-rdkafka/pull/857) to them. 

Might be better now, and the early days of the plugin server were different (more async stuff flying around), but don't assume it's a silver bullet.

**Comment by hazzadous** [comment]
@mariusandra do you happen to have a link to examples of issues you'd seen? I've only migrated the functional tests to use the librdkafka producer so far, the _seems_ ok so far. But would love to fail fast here rather than move everything over.

Is it more than just the patch that @Twixes submitted?

**Comment by mariusandra** [comment]
I tried finding something the [old archive](https://github.com/PostHog/plugin-server/issues?q=is%3Aissue+kafka+is%3Aclosed), but couldn't. I also don't remember the specifics, but more of a general feeling of things being odd/sluggish/flakey/crashy whenever we used it. 

Sorry, I know I'm not very helpful :(

**Comment by hazzadous** [comment]
> I tried finding something the [old archive](https://github.com/PostHog/plugin-server/issues?q=is%3Aissue+kafka+is%3Aclosed), but couldn't. I also don't remember the specifics, but more of a general feeling of things being odd/sluggish/flakey/crashy whenever we used it.
> 
> Sorry, I know I'm not very helpful :(

No it's all useful data. I'll have a look through that repo to see how it was being used.

**Review by xvello — APPROVED** [review]

**Comment by hazzadous** [comment]
@xvello running the tests with master merged in 🤞

**Pull request merged**
