### PR TITLE
Draft: fix(settings): improve dropdown UX when there are no pre-defined options

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem

This fixes the first problem in https://github.com/PostHog/posthog/issues/11511 where a multiple select with no pre-set options still showed a dropdown of "options" where the only options were the ones the user had already added. 

## Changes

Ideally the `antd` `<Select>` component would allow you to set a `placement` for the dropdown as `none`, but alas it does not. That can be added as a feature request. But in the mean time, I figured we could simply hide it. I don't typically like doing this to the DOM (better to prevent the node from appearing in the first place) but it seems that the component doesn't support that. If you have other ideas let me know.

In order to hide the dropdown, I had to upgrade to `antd@4.23.1`, where a prop `popupClassName` was added to the `<Select>` that could be used to hide the dropdown (which is apparently also known as a popup). In upgrading to to `antd@^4.23.1` it downloaded `4.23.6` and I discovered a dependency bug introduced in the `4.23.5` release in the `rc-textarea` package dependency. I opened an issue for that [here](https://github.com/react-component/textarea/issues/24). So, I pinned the `antd` version to `4.23.4`..... Not ideal to pin a dep version but when that issue gets resolved I can un-pin it. 

So with all that out of the way I added a `hideDropdown` prop to the `LemonSelectMultipleDropdown` component to hide the dropdown when it is present, and added a corresponding story.

| Before  | After |
| ------------- | ------------- |
| image  | image  |

Finally, there was a story for `No Options`. This is technically a situation where you don't have any options originally, but you still want to show them in the dropdown after adding. I don't really see where this would be useful (since it was decided that it was bad UX, hence this issue) so I removed it.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

There aren't any tests for this, though I think I might add a cypress test, so I'm leaving this as a draft for now, will get to it likely tomorrow. I'm also concerned that updating the `antd` package will change how things look so this would probably benefit from some more in-depth QA.

Also feedback on the decisions above would be appreciated :) I'd also wait to merge this until the above-mentioned issue is resolved so I can un-pin the version number.

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
Hey! Thanks for the PR. Ideally we'd still show a dropdown saying just "Add {new-option}" for clarity, but this is definitely an improvement already. The only problem is it appears the version still needs to be pinned, as https://github.com/react-component/textarea/commit/0594cd0c30fc9bd4fe321e8f59c5dc5092312854 didn't go into `antd` yet.

**Comment by raquelmsmith** [comment]
I'll revisit this this week.

**Comment by raquelmsmith** [comment]
Bad bot! I'm avoiding this because I want to visually QA the entire site for the antd upgrade.... but it should be done regardless.

**Comment by raquelmsmith** [comment]
Closing in favor of https://github.com/PostHog/posthog/pull/13358 since this branch was on a fork

**Pull request closed without merging**
