### PR TITLE
Add Sigma Analysis to funnel table

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

Introduces the `sigma-analysis` feature flag, which tracks tool 1 of Quant Analysis: #5543 .

Highlights all funnel table items that are outliers. By definition & careful selection of sigma-windows, these shouldn't be more than 1-2 per table.

image

image

---

I was struggling to get the blue background on the fixed table columns as well - not sure what to do about it.

## How did you test this code?

Manually, go to funnels and see things look like the screenshot^

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]
Just a couple of stylistic comments, nothing much from me.

**Review by alexkim205 — CHANGES_REQUESTED** [review]
Thanks for wading through the hot mess that is `funnelLogic` right now. Left a few inline comments for you.

re:

> I was struggling to get the blue background on the fixed table columns as well - not sure what to do about it.

I'm not that sure what you mean here. Are you trying to make the column headers also have a blue background if theres a sigma cell here?

**Comment by neilkakkar** [comment]
@alexkim205 :

See the left most bit:
image

I want the fixed column row to have the blue stuff as well - but it seems like the fixed property somehow overrides the class? I experimented with making it not fixed, and that worked.

**Comment by neilkakkar** [comment]
@alexkim205  - I'll get this in now, but please let me know if I left anything outstanding :)

(and would appreciate pointers on the highlighting issue - if you figure it out 😅 )

**Pull request merged**
