### PR TITLE
Use Avro as serialization to Kafka for Events and other messages

### PR DESCRIPTION
**Pull request by fuziontech**
Avro is a schema enforced and fast serialization that would be a great fit for this. This is some work towards using it for our data pipeline.

### CODE REVIEW

**Comment by timgl** [comment]
Is still worth spending time on now? I think you mentioned JSON being fast enough for now?

**Comment by fuziontech** [comment]
It's a better serialization to have long term. It's faster, schema enforced, and would make long term storage much easier and cleaner. We can always migrate to it later with not much risk.

**Comment by Twixes** [comment]
@fuziontech Quite a bit of conflicts here… Are we going forward with this approach or can this be closed?

**Comment by fuziontech** [comment]
Go ahead and close it for now

**Pull request closed without merging**
