### PR TITLE
Add event (type) column to order by primary key for events table

### PR DESCRIPTION
**Pull request by fuziontech**
## Changes

https://posthog.slack.com/archives/C01MM7VT7MG/p1639692552163000

We'll have to do this migration manually on cloud for now

## How did you test this code?

tests!

### CODE REVIEW

**Comment by tiina303** [comment]
is_required needs to change too & maybe check against sample by if that changed too initially so we'll need to less likely update this in the future. 
Could we also add a test that fresh installs all 'is_required' functions return false.

**Comment by macobo** [comment]
Non-code Q (cc @yakkomajuri for this): this ~big~async migration is already deployed to clients, meaning that they would need to know how to roll back and roll forward to get any benefits. Should this be a separate async migration due to this?

**Comment by yakkomajuri** [comment]
Here's go my thoughts and a proposed solution.

Above all, I want to drill one point home:

> We'll have to do this migration manually on cloud for now

Let's **please please** not do this. We've just built a whole system to handle these things, let's dogfood it. Plus come to think about it async migrations might be the best thing that happened for context sharing in the Platform Team in a while. The transparency they bring over running stuff manually is tremendous. 

Now, as for what we should do next.

When we started work on this I [proposed that async migrations be non-sequential](https://github.com/PostHog/posthog/issues/7054#issue-1050824615). We did away with that but I propose we bring it back and do away with dependencies altogether.

**Why?**

1. Getting rid of dependencies opens the field for us to handle various possible states people might be in, which is the whole goal of data migrations
2. We can still have dependencies anyway. `is_required` is super powerful. We can just introduce dependencies there.

Thus, as for this migration, I would:

1. Get rid of dependency handling
2. Update the `is_required` check in `0001_events_sample_by` to return `false` if we're in the state `ORDER BY (team_id, event, toStartOfHour(timestamp), distinct_id, cityHash64(uuid))` **OR** `ORDER BY (team_id, toDate(timestamp), distinct_id, uuid)` (and also rename it to just `events_sample_by`
3. Ship another migration (with a great description) to get us to `ORDER BY (team_id, event, toStartOfHour(timestamp), distinct_id, cityHash64(uuid))` without a dependency (so it can run **before or after** `events_sample_by`)
4. Ship a patch release (optional?)

In fact, with this approach, if we wanted to, we could keep the range of `events_sample_by` as that's what's needed to upgrade CH, and the other migration can have a larger range, as it's just a performance optimization. Ideally if you haven't run any of them you'd run the second one only, but if you do end up running `events_sample_by` you'd be ok to upgrade ClickHouse. This is a side point though.

And then for the future, I'd also:

- Run the `is_required` check early so migrations can be tagged as completed without the user having to trigger them to find out if they're necessary

**Comment by tiina303** [comment]
Can't we just rename the migration & it will look like a new migration to everyone (the ones who ran it already & the ones who haven't yet)?

**Pull request closed without merging**
