### PR TITLE
Added web-pack live reload

### PR DESCRIPTION
**Pull request by sacgov**
## Changes

Design choices

the choice of the internet is [this](https://github.com/owais/django-webpack-loader). But it needs a lot of modification done. It is obtrusive. What i have added though not elegant is an easy way and doesn't change any existing codebase.

Static Assets are not loaded by webpack but are copied directly in the start command - so they are not managed by webpack. We should have a loader for them too. I did a workaround by proxying the static assets like pngs as well to django server.

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey! Thank you @sac0 ! It's perfectly fine for me not to use the django loader. However some small fixes I'd make:

* Can you remove the `dev` script and just put the code under `start`? We only use `start` for development and nothing else. After this change it would sit unused.

* I think it's good to proxy /static to django. However the `"**/*.png"` rule will make it that we now can't use pngs through webpack at all if I'm not mistaken? I checked and it seems that the only png we have is just the `public/posthog-logo.png`... that's only referenced in two places by React. I think that could definitely be moved into webpack... and I'd prefer it if webpack handled all the assets for the react part of the app as well. Perhaps it could go under `frontend/src/layout/_assets/posthog-logo.png`?

**Comment by sacgov** [comment]
Refactored to remove unnecessary scripts. Also webpack can handle the assets if it is in imported as
import logo from `frontend/src/layout/_assets/posthog-logo.png`; and ``
In our case we are settign the src programatically this.props.apiurl + path - this is resolved at runtime rather that at build. So i added the copy-webpack-plugin - which is the most widely used one for such cases.

**Comment by mariusandra** [comment]
Hi, this seems good. I tried running it (via yarn start) and it worked fine. I didn't try yet if building works (e.g. if the generated docker container would contain the new code properly).

However one question: now we will need to open the app on http://localhost:8001/ ? I see how it can be easy to forget the 8001 and run it on the old port and then wonder why nothing is working.

Is there any way to still load the index.html from port 8000, but have it load the scripts in development mode from port 8001? I used such an approach quite successfully before with both Rails and Django apps in the past. Do you think this could be easy to add?

**Comment by timgl** [comment]
@sac0 Hey! Just chasing a little bit ;) Any thoughts on this?

**Comment by sacgov** [comment]
Hi @timgl . A busy week at the workplace. I will get it done this weekend. I think there is no way without looking into a bit of django stuff, I need to change the js URL's to load from 8001 as well as have the reload js added in the html only in dev environment. Need to look more into posthog's code for it. Will do that. 

The current pull request works. Just that it needs to open new port(8001). I'll try incorporating @mariusandra 's comments.

**Comment by timgl** [comment]
No worries, really appreciate the work you've put in so far 🙌

**Comment by EDsCODE** [comment]
Thanks for the help in starting this ticket @sac0! We ended up merging this in with #878

**Pull request closed without merging**
