### PR TITLE
Fix line charts and make them monotone (closes #1218)

### LINKED ISSUE #1218: Chart tooltip out of bounds and invisible
### Bug description

The graph tooltip here is broken:

### How to reproduce

1. Get a chart like on the screencast above
2. Hover the topmost points
3. The tooltip goes even higher and doesn't show

### Expected behavior

It should flip around. I assume since it's a `<canvas>` we can't make it go outside the box. 

### Environment

- PostHog cloud or self-managed?
- PostHog version/commit

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Line chart improvements.

Before | After
-------|------
Before | After

### CODE REVIEW

**Comment by ungless** [comment]
Quick question: are we using bezier curves in the charts just because they look good? afaik they lack accuracy and that's why GA/mixpanel don't use them.

Might be wrong on this one.

**Comment by timgl** [comment]
@MaxTheMonster yep, no conscious choice it was just what Chart.js shipped with. Happy with any other suggestions you have!

**Comment by Twixes** [comment]
This PR changes that to https://en.wikipedia.org/wiki/Monotone_cubic_interpolation.

**Comment by ungless** [comment]
Chartjs has `lineTension` which we can just set to 0 to give straight lines.

@Twixes I suppose this works too in terms of retaining the curvy-ness without causing serious errors. Both work, but I guess having no tension at all eliminates any confusion from a UX point of view (does the data actually change between days as shown? they might ask)

**Comment by ungless** [comment]
image

**Comment by timgl** [comment]
I think the straight lines look good

**Comment by ungless** [comment]
[https://github.com/PostHog/posthog/pull/1238](https://github.com/PostHog/posthog/pull/1238)

@Twixes does this still fix the original issue?

**Comment by timgl** [comment]
Closed in favour of #1238

**Pull request closed without merging**
