### PR TITLE
Team management

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- Created `GET /api/team/user/` endpoint for listing users on the team.
- Created `DELETE /api/team/user/{id}/` endpoint for deleting other users.
- Added the menu item for team management on the frontend.
- Added the view to list all users from the team and invite new users.
- Added support for permanently deleting users on the frontend (with confirmation prompt) and post-success message.

## Checklist

- [ X ] All querysets/queries filter by Team (if applicable)
- [ X ] Backend tests (if applicable)
- [ N/A ] Cypress E2E tests (if applicable)

## Screenshots

**Listing users**

**Deleting user**

**Client-side pagination**

### CODE REVIEW

**Comment by timgl** [comment]
I think this looks good. We generally do frontend and backend in the same PR so that it's easier to QA both together

**Comment by paolodamico** [comment]
Got it, I'll work on the frontend. I wanted to get feedback on the backend structure first before starting on the frontend, in case we needed to fix something beforehand

**Comment by paolodamico** [comment]
Frontend ready, ready for review

**Comment by Twixes** [comment]
Overall looks good to me, just polished the front end a bit. I'm just a bit not sure if it's the best idea to completely delete a user's PostHog account on deletion from a team? There should be at least an email about that, so that the user doesn't find themselves surprised they can't log in anymore. Maybe a more robust, many-to-many Team–User relationship would be even better (in UX, not just in database), though obviously more work to implement.

**Comment by timgl** [comment]
Agree with @Twixes : users have an "is_active" flag which is equivalent to deleting a user, but without deleting all of their funnels etc. Just setting that flag to False should achieve what we want :)

**Comment by Twixes** [comment]
That'd be much better (and more secure). And I still think there should be an email for this.
Also, it'd be good for teams to have owners (an `owner` bool on the posthog_team_users bridge table), because currently you can invite someone and they can just delete you, even if you created the team. This could go wrong maliciously or accidentally.

**Comment by timgl** [comment]
@Twixes Some of the team management stuff we'll put in the paid version, as that's not something individual developers need.

RE the email, I could see it both ways but happy to leave that for now to get this out

**Comment by paolodamico** [comment]
Great! Thanks for the review, the feedback and the polishing!

- I agree with the M2M relationship as a future improvement (I would definitely consider this for the cloud edition too), and having some more granular controls on the enterprise version.
- I also understand the reasoning behind the soft-delete, happy to make that change on the API. The only thing I would like to propose is that we do redact the email address and name for privacy reasons. Enable a user to effectively have their PII removed from the system. Wdyt?

**Comment by Twixes** [comment]
Merged this using PR #1274 as there was a conflict to be resolved manually.

**Pull request closed without merging**
