### PR TITLE
feat: allow edition non global enabled plugins

### PR DESCRIPTION
**Pull request by tiina303**
## Problem

To be able to not allow new installs we'll marke plugins as is_global=false, but atm that means already enabled plugins won't be editable, this PR changes that.

## Changes

related https://posthog.slack.com/archives/C02E3BKC78F/p1687866846613699

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Used cloud mode locally [see thread](https://posthog.slack.com/archives/C04866B8W2J/p1687802215613379)
Admin org:
Screenshot 2023-06-27 at 16 21 15

Another org:
Screenshot 2023-06-27 at 16 19 58
 and was able to edit the non-global hello world app
Screenshot 2023-06-27 at 16 20 09

### CODE REVIEW

**Comment by tiina303** [comment]
Not sure about the storybook test nor the snapshot that now shows no apps

**Review by hazzadous — APPROVED** [review]
I gather that in this case, if for instance we disable a plugin config because of errors they will not be able to see the config any more?

**Review by Twixes — APPROVED** [review]
Added a couple tests as a way of verifying assumptions, everything seems in order.
@hazzadous That's right. UX-wise I suggest some an extra warning when disabling a plugin that doesn't belong to the current org and at the same time isn't global

**Comment by tiina303** [comment]
I'd say in those cases the answer is - your plugin usage was causing problems, which is one of the reasons why we made it non-global. We can tell them what they should be doing instead. TLDR: this is fine.

**Pull request merged**
