### PR TITLE
chore: rename docker-compose.dev.yml -> docker-compose.yml

### PR DESCRIPTION
**Pull request by hazzadous**
we currently don't have a default docker-compose config, is would seem
appropriate to make the dev the default.

Corresponding changes are required:

 1. [posthog.com](https://github.com/PostHog/posthog.com/pull/3493)
 2. [posthog-cloud](https://github.com/PostHog/posthog-cloud/pull/195)

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by EDsCODE — APPROVED** [review]

**Comment by Twixes** [comment]
Wanna merge @hazzadous?

**Comment by hazzadous** [comment]
@Twixes there were some merge conflicts that I need to get around to resolving. I'll reopen and make the changes when I get time.

**Comment by hazzadous** [comment]
@Twixes or if you wanted to make them feel free to push to this branch

**Comment by hazzadous** [comment]
@Twixes assuming CI passes 🤞

**Comment by hazzadous** [comment]
Cloud tests fail because they try to use master/docker-compose.yml , tempted to just merge this in given it should be fine after that.

**Pull request closed without merging**
