### PR TITLE
Refactor PropertyValue to TS

### LINKED ISSUE #4665: Adding a filter in Sessions page crashes
## Bug description

Adding a filter in the sessions page crashes.

## Expected behavior

We don't crash

## How to reproduce

1. On the sessions page try to add a filter (tried to select Browser)
Screen Shot 2021-06-09 at 15 55 27
Screen Shot 2021-06-09 at 15 56 01

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Looks similar to an earlier issue on the insights page https://github.com/PostHog/posthog/issues/4626

### PR DESCRIPTION
**Pull request by samwinslow**
## Changes

Goal: Make state management in PropertyValue more clear; make debugging easier via static typing. It should now be evident that PropertyValue handles string values and array values quite differently from each other.

Closes #4665.

UPDATE:

As I want to get this done in a timely manner and not spend any extra time building a controlled dropdown state, ~~for now I updated the copy on user paths to suggest the user has to start typing in order for results to show. (`Select` --> `Search`).~~ WIP

A better fix would be somewhat simple; all we need to do is trigger the dropdown to open after results are loaded (requiring controlled state). I just want to get this done for now, though.

Screen Shot 2021-06-10 at 9 11 50 AM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Testing this now - my first comment on this is the same as @timgl had on my first "fix", how do I know what to type on the paths input? I should be getting suggestions right away. Is that what you meant by autofocus? It's indeed annoying because `onClick` will also trigger on the options in the selector

**Comment by yakkomajuri** [comment]
Another issue is something I was also looking to fix (I think it may have always been broken) - is that changing `PATH TYPE` keeps the old input but renders the default path for the new type.

**Comment by yakkomajuri** [comment]
Also some issues with the suggestions when switching path types (multiple for the same, suggestions persist changing types)

Screenshot 2021-06-10 at 11 15 03
Screenshot 2021-06-10 at 11 15 23

**Review by yakkomajuri — CHANGES_REQUESTED** [review]
I'll review the code once the behavioral issues above are addressed. Like I said on our call, there's a lot of problems here beyond just types.

I got beat up by this component yesterday 😂

**Comment by yakkomajuri** [comment]
Another issue here (also related to legacy bad practices), is that the query for events expects an integer, so it's failing now as we're sending it a string. Previously, we would show autocomplete options as strings but then assign their id as the value, so the user would see a  random `294` instead of the event selected. It's ridiculous, I know 😂 

This is another issue I was facing

**Comment by samwinslow** [comment]
> Testing this now - my first comment on this is the same as @timgl had on my first "fix", how do I know what to type on the paths input? I should be getting suggestions right away. Is that what you meant by autofocus? It's indeed annoying because `onClick` will also trigger on the options in the selector

Argh, thought I submitted the updated description. Yes, that's what I meant by autocomplete -- will work on today.

**Comment by samwinslow** [comment]
Why do we separate Path Type and Start Point? Seems weird to make the user explicitly decide between autocaptured and custom events, for example, when those types are not differentiated elsewhere.

I know this might seem like a UX nitpick, but the weird state mismatches that occur when switching from one path type to another might be solved, for instance, by using SelectBox like we do elsewhere.

EDIT: See images and more context here: #4703.

**Comment by samwinslow** [comment]
Spinning off some of these issues: #4703, #4704 which are long-standing problems. If anyone has advice regarding getting the autofocus to work, it would be much appreciated. I feel like we need to keep this PR to a reasonable size.

**Comment by samwinslow** [comment]
@EDsCODE @paolodamico I see you both did some work on PropertyValue some time ago... if you have any time to take a look, could you see if I'm missing something regarding getting the dropdown to open as soon as results are loaded? Have been stuck on this for a while.

**Comment by mariusandra** [comment]
I gave it a go and ~90min later I think I have something that works.

I think the problem with the dropdown not opening was this:

```jsx
<AutoComplete>
   {input ? <Option ... /> : null}
   {options.map(o => <Option ... />)}
</AutoComplete>
```

The first element was `null` / `undefined` and hence the list looked empty and antd didn't auto-open it. Replacing this with an array of options (still passed as `children` since we need custom labels) solved the problem.

There was also a problem with the "custom element" view, where the text `<span> bla` was sent to the API, not the ID. That's also fixed.

Plus various type fixes and other small tweaks to make sure things work.

The only thing that's still broken is this: If you search for a custom element, we put the ID in the URL. If you then reload the page, you'll only see the ID in the dropdown, as we haven't downloaded the list of elements and can't really match this ID to any better string. Since the custom element paths page itself is quite useless, I propose to leave it at that for now and move on. :)

**Comment by mariusandra** [comment]
Also managed to find and fix a sql injection (cc @EDsCODE)

@samwinslow @paolodamico @yakkomajuri do you think this is safe to merge now? Obviously cypress is borked and we don't know if anything is broken or not 😅

**Comment by paolodamico** [comment]
I actually have little context on this, so I'll defer to @samwinslow, though do let me know if you want me to take a closer look.

**Comment by yakkomajuri** [comment]
@mariusandra there's still the problem of switching path types with the input persisting but the graph changing. 

So it says `hogflix.com` but it actually is `<span> Click me`

**Comment by mariusandra** [comment]
That should also be fixed now. Hopefully without breaking anything else :D

**Review by yakkomajuri — APPROVED** [review]
Behavior-wise :thisisfine: - will leave the code review of @mariusandra's changes to @samwinslow

**Comment by samwinslow** [comment]
Re-running all tests locally to see what failures, if any, should be addressed.

**Pull request merged**
