### PR TITLE
Release funnels simple mode

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Releases the new funnels simple mode.
- Results have been fairly positive. On average (4 week span; Dec 5 to Jan 3) users in the experiment group discovered 13.67 weekly funnels per active user vs. 10.03 on control group (~36% improvement). [[Data source](https://app.posthog.com/dashboard/21755)].
- With the release of this experiment we can now test the funnels cue experiment.

## How did you test this code?
- Launched the app and made sure the new simple mode was seen on funnels without a feature flag.

### CODE REVIEW

**Comment by kpthatsme** [comment]
Couple of quick checks –

- The data points for the experiment are quite low, if we're using the data to drive the product change we should wait for some more volume and let it run now the holidays are over.

- Looking at this [chart](https://app.posthog.com/insights/AjHBi9ID/edit?insight=TRENDS&events=%5B%5D&actions=%5B%7B%22id%22%3A%2210784%22%2C%22name%22%3A%22Discoveries%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22funnel-simple-mode%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22custom_name%22%3A%22Experiment%20-%20total%20discoveries%22%2C%22math%22%3A%22total%22%7D%2C%7B%22id%22%3A%2210784%22%2C%22math%22%3A%22total%22%2C%22name%22%3A%22Discoveries%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22funnel-simple-mode%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22custom_name%22%3A%22Control%20-%20total%20discoveries%22%7D%5D&date_to=2021-12-16&display=ActionsLineGraph&interval=week&date_from=2021-11-25&exclusions=%5B%5D&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22insight%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22FUNNELS%22%5D%2C%22operator%22%3A%22exact%22%7D%5D&funnel_to_step=1&funnel_viz_type=steps&funnel_from_step=0&filter_test_accounts=true) it actually looks like the control group has been performing better? Now this could be a symptom of exposure if it was running as a non 50-50 split but just wanna clarify

**Comment by alexkim205** [comment]
Looking good codewise.

**Review by alexkim205 — APPROVED** [review]

**Comment by paolodamico** [comment]
Re @kpthatsme, the problem is indeed that the control & experiment groups are not split 50/50, that's why I use instead the number of discoveries per active user ([source](https://app.posthog.com/dashboard/21755)). I think the number of users is valid, as we've run this for ~4 weeks (even without the 2 weeks of holidays), but open to challenge

**Comment by kpthatsme** [comment]
No that sounds reasonable to me then - thanks for confirming @paolodamico

**Pull request merged**
