### PR TITLE
Show users per day per action in trend graph

### LINKED ISSUE #300: WIP Break down a trend graph into the actual users
It'd be nice to click a data point on the trend graphs, to see all the users or actions that made up that data as a table.

### PR DESCRIPTION
**Pull request by mariusandra**
Fixes #300

### CODE REVIEW

**Comment by timgl** [comment]
Great work! Couple of points
- [x] Could we somehow do `cursor: pointer` over the chartjs node? Despite knowing I could click it it wasn't obvious.
- [x] Also if it's easy could we make the area to click bigger? It's quite a small target. Please ignore if it takes more than 10-15 mins.
- [x] This should work when the graph is displayed in stickiness mode too. Sorry about that, I didn't that that was as important but using it it was frustrating that side didn't work. If you think this will take a long time (> 1 hour), please let me know and I can write a ticket that we can pick up at some other time.

- [x] When loading the table, somehow the borders of the table extend to the end of the modal 
image

**Comment by mariusandra** [comment]
Hi, showing users in the stickiness mode works now. 

It took about an hour to get it showing the list. Then I spent another hour or so optimising this query and the default stickiness chart query.

With the existing stickiness query you will run into issues with large datasets, as the code was loading every unique person and day combination and summing the people manually in python (`people[event.person_id] += 1`). This calculation should be handed off to the database instead.

I managed to get the users list query working well (it just gets the users who have this many unique days), but got stuck with the stickiness chart query. 

I did improve it slightly: now it already returns the number of days for each user instead of returning each user as many times as he/she has days... but it should be possible to directly get the number of days and the number of users who have that many days. Unfortunately Django's QuerySets got the best of me this time.

**Comment by mariusandra** [comment]
Hey @timgl , that is now done as well!

The stickiness graph is now fully calculated inside postgresql... and only the compact end result is returned to django. I couldn't figure out how to do it fully with querysets (probably I need to create some custom managers to be able to select from a subquery?), so I used raw sql to get the final counts.

I have limited test data locally, but as far as I could tell, it works and gives the right results.

It's basically the second or third day I'm writing Django, so my apologies if what I did is not how things should be. If you have suggestions on how to improve, please let me know :).

**Comment by mariusandra** [comment]
Another small thing. When clicking on a row with 0 users, we show this message. A similar message is shown in other places in the interface as well. Meaning that events have been sent, but since none match the current query, we show "sorry, you haven't sent any event". It's the same also on the users page (e.g. if you select a badly configured cohort) and also in the paths page. Probably elsewhere that I'm not aware of as well.
 
image

So probably not anymore in the scope of this task, but there could be a nicer way to tell the users that the active filters yield no results :).

**Comment by timgl** [comment]
When I tried it the /people endpoint wasn't working for non-stickiness. I pushed a fix and wrote some tests.

For non-stickiness, can we use date_from and date_to? Just set them to the date that you've selected, that should work. I tried to do this but couldn't figure out how.

**Comment by mariusandra** [comment]
Hey! It was a sad and apparently untested last minute "fix" in the stickiness graph that caused the bug with the non-stickiness users. Sorry about that. The last commit fixed it.

I'll try to remember the test next time as well. Sorry about that.

**Comment by timgl** [comment]
Sorry that this has turned into a slightly endless PR!

 It looks like the URL doesn't get automatically updated when you change any of the filtering. This was a cool feature because it means you can really easily share a version of the graph with someone else by copying the url. Hw hard it would be to put this back?

**Comment by mariusandra** [comment]
Hey, that's weird. It works for me in localhost. I just tested. Can you provide some more details on how it's broken or where? Are there any errors in the browser console?

**Pull request merged**
