### PR TITLE
feat(data-manage): add filters to definition table views

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Adds event and event property filters to respective definitions table views.

I omitted property filters in both definitions filters since searching for event definitions by property and vice versa isn't implemented in the backend yet. I just wanted to get these pages up to speed with our old versions before launch week so that users can meaningfully find definitions here. 

https://user-images.githubusercontent.com/13460330/158469330-058633d6-6a15-47dd-bf20-df226f240868.mov

Screen Shot 2022-03-15 at 4 42 18 PM

Screen Shot 2022-03-15 at 4 42 41 PM

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6727%3A39698

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Manual QA

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
I wonder if a keyword search could be more useful in this context. These lists are distinct items, not a live history of event instances. If I were to select a single type, I'd only see one item in the underlying table. A keyword fuzzy search might help when a user doesn't know the exact value they're looking for. It'd be great if the search could search across item names, tags, etc. Actions already works this way which is why I'm a bit thrown by the single select filter. Thoughts?

**Comment by alexkim205** [comment]
That makes sense, the way I have it now it kind of feels like you're making the same query twice. Once in the taxonomic filter popup and once more in the table view. I'll switch these two free form input boxes instead

**Comment by alexkim205** [comment]
Updated to inputs. Using antd components here until we migrate everything to lemon land eventually.

https://user-images.githubusercontent.com/13460330/158473537-a1544701-b85d-454c-9664-d45372234c2a.mov

**Review by clarkus — APPROVED** [review]
🚀

**Comment by alexkim205** [comment]
Observing a minor filtering persistence with event properties table, but I'll root cause that in another ticket. Merging this now

**Pull request merged**
