### PR TITLE
Rework "On dashboard" button

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

It wasn't possible to go straight from an insight to the dashboard it's on. Now it will be.
WIP as the experience of "Add graph" and "Add to dashboard" needs to be solidly improved still.

### CODE REVIEW

**Comment by paolodamico** [comment]
Feel free to retag me when it's ready for review

**Review by mariusandra — APPROVED** [review]
This LGTM as it is now.

**Comment by Twixes** [comment]
Well… now this is ready for review. New experience:

Still not sure if the modal for adding to dashboard is good (maybe a project switcher-like Popup? @clarkus) though it's not _bad_.

**Comment by clarkus** [comment]
Those changes look good to me. I think we can probably hold off on touching up the dashboard modal until we have more clarity around https://github.com/PostHog/posthog/issues/6712.

**Review by mariusandra — APPROVED** [review]
LGTM, though a relevant cypress test is failing.

**Pull request merged**
