### PR TITLE
Fix breakdown people modal postgres

### PR DESCRIPTION
**Pull request by timgl**
## Changes

When we breakdown and then click a modal we include the properties, however in the API we were incorrectly filtering users on events properties.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by samwinslow — APPROVED** [review]
LGTM, Kunal and I have both noticed inconsistencies here and this was probably the cause

**Comment by samwinslow** [comment]
Looks like the failing test case could be because the `type` is not specified. If there is no `type` should it be assumed to be `person`, or should we just expect it to always be set?

**Comment by timgl** [comment]
I can't find any instances of properties being used in combination with this endpoint and all of our dropdowns add the type by default so I think this should be safe.

**Comment by paolodamico** [comment]
Merging with approval from @samwinslow to get into the release.

**Pull request merged**
