### PR TITLE
feat: [1/2] access control capture (without test)

### PR DESCRIPTION
**Pull request by surbhi-posthog**
## Problem

We want to capture logs when the user toggles on/off access control feature under teams.

Remaining features include:

- [ ]  SSO enforcement which is turned on after verifying a domain.
- [X]  Project permissions - so if someone toggles project private/public
- [X]  Ingestion taxonomy - if someone marks events as verified
- [ ]  White label branding - surveys and sharing dashboards

## Changes

Changes only add logs in the backend, no frontend changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud: Yes

## How did you test this code?

Locally verified that the activity monitor showed the events and add tests
image

### CODE REVIEW

**Comment by surbhi-posthog** [comment]
I see the failing test - I think I need mock the API calls for user permissions being changes first before checking if the capture is called. Will spend more time debugging this, but if anyone has suggestions please let me know!

**Comment by surbhi-posthog** [comment]
Since the tests were failing on origin and cannot be debugged locally, I'm separating the tests and capture log changes. I will add the tests in the following PR and follow up on it.

**Review by patricio-posthog — APPROVED** [review]
Let's add tests to this asap

**Review by zlwaterfield — APPROVED** [review]

**Review by zlwaterfield — CHANGES_REQUESTED** [review]
Sorry I didn't mean to approve. I thought about this more and we should get the test working on this PR. It should be possible. I'll try and debug it later in the week.

**Comment by surbhi-posthog** [comment]
im closing this PR and will follow up changes through this PR https://github.com/PostHog/posthog/actions/runs/12551899005/job/34997145853?pr=27142

**Pull request closed without merging**
