### PR TITLE
fix: person prop parsing && autocomplete on props

### PR DESCRIPTION
**Pull request by paolodamico**
## Problem

- There was a bug in which we were ignoring the proper parsing of properties when adding/editing from the UI (i.e. `boolean`, `null`, `number`)
- UX issue with autocomplete, browser suggestions for this are way off as these are very specific names.

## Changes
- Saved properties to the DB will now reflect the proper type and not default to string for everything.
- When editing/adding a property, the inputs will no longer autocomplete or autocapitalize.

## How did you test this code?
I'll be honest I didn't. Very straightforward changes imo.

@mariusandra back to PRs over issues 😉

### CODE REVIEW

**Comment by paolodamico** [comment]
fyi seems like some Ubuntu mirrors are down, just a matter of re-running the failing tests

**Review by mariusandra — APPROVED** [review]
LGTM :D.

Yeah, we've seen this problem with tests on other branches as well, so gonna ignore that and merge. Doesn't look like anything would break here.

Thanks and... welcome back? :D

Edit: seems like I need to fight CI a bit to get this in...

**Comment by paolodamico** [comment]
thx Marius! awaiting merge now, hope to be seen here more frequently

**Comment by mariusandra** [comment]
There's some mess happening with github actions (sounds familiar?). I'll close this PR and re-open one with the same changes... That's probably the easiest way forward right now 😅

**Comment by paolodamico** [comment]
😆 vaguely familiar, sg!

**Pull request closed without merging**
