### PR TITLE
test(frontend): Automatically test Storybook stories with snapshots

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

We have a setup for taking snapshots of Storybook stories in place, but the instrumentation of those actual tests is really cumbersome – the test for each story needs to be written manually. We just need that step to happen automatically to get lots of tests for (almost) free.

## Changes

This sets our project up for automated story snapshots using `@storybook/test-runner`.

~~Because the resulting `__snapshots__` directory is relatively large (9 MB at the moment) and subject to turnover, I enabled Git LFS for it (superseding https://github.com/PostHog/posthog/pull/13475).~~

~~WIP as some stories fail (I suppose because we've never had tests for whether they still work), and this needs to be added to CI too.~~

### CODE REVIEW

**Comment by Twixes** [comment]
Alright, after lots and LOTS of tuning, and hours of waiting for CI to do its thing (weirdly often differently even from the dockerized local setup), I believe this works.

For now snapshots are opt-in, as some scene stories have problems, which need to be tackled separately. However, already all of Lemon UI is covered by snapshots here, which a boon – and adding snapshots is just a single line of code now.

I dropped Git LFS, as apparently support for diffs with LFS is quite poor across the board (though it does exist), which seemed too annoying for now. Instead, to make snapshot size less of a concern, I added PNG optimization (with OptiPNG) to the pre-commit hook. That results in a lossless size reduction of around 25% (based on current snapshots – 1270 kB before optimization, 967 kB after).

Also, visual regression tests are now part of the "Frontend CI" workflow, as they got even more Storybook-focused – it just wasn't true that they were "_e2e_-vrt".

**Comment by thmsobrmlr** [comment]
> waiting for CI to do its thing (weirdly often differently even from the dockerized local setup)

I found that most often a stale storybook build or mock service worker was the issue. In cases like this I rebuild storybook with `pnpm storybook --no-manager-cache`, open Storybook in an incognito window and hard reload (open dev console, right click on refresh, "Empty cache and hard reload").

**Review by mariusandra — APPROVED** [review]
Looks great! Going to ✅ even if some comments below. Get it in 🚢 

Having trouble testing it locally though. Probably should upgrade one of those: 

image

Running the scripts without docker works, though obviously a lot of different pixels.

**Comment by Twixes** [comment]
Oh yeah, I'm on `docker compose` 2.13.0 via Docker Desktop, looks like 2.13.0 is when `--build` was added to `run`.

**Review by thmsobrmlr — APPROVED** [review]
LGTM

**Pull request merged**
