### PR TITLE
Highlight automatic changes to date range filters

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

I'm sure there was a reason for this at some point, but I've now watched user after user on demos get confused by the automatic range changes after selecting an interval. It's particularly weird when I'm looking at some data and want to just change the interval (e.g. daily to weekly), and suddenly I have no data? See below:

https://user-images.githubusercontent.com/38760734/111342622-89218080-8672-11eb-8781-9fd2a4c9804a.mov

cc'ing @paolodamico for an assessment of the expected UX here

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by timgl** [comment]
The reason for this was _not_ doing this was confusing too and would potentially kill us, ie selecting 'all time' and then 'minute.' Or someone would have 'last 7 days' and then select weekly, leaving them with a single data point. I am happy to revert or maybe just change _when_ we do this.

**Comment by yakkomajuri** [comment]
Hmm yeah that makes sense - I'll give some thought into how this could be better if at all. Given that the flip side of the coin is long-running queries I guess I'm against the change too.

**Comment by paolodamico** [comment]
Just thinking out loud here, but if we do need to keep that behavior, maybe we could do some highlighting (i.e. bring attention) to the filtering interval that changed (sort of like google docs does when content is added/removed?). Something like this https://stackoverflow.com/a/41391835, but obviously with the right styling.

**Comment by yakkomajuri** [comment]
@paolodamico yes that at least would make it more clear

**Pull request merged**
