### PR TITLE
chore: Remove cypress

### PR DESCRIPTION
**Pull request by timgl**
## Problem

Reverts #11200. It's not worth the increase in docker image size and build time locally to have cypress included.

## Changes

Remove cypress from package.json

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by pauldambra** [comment]
🤔 hmmm, we need to sort out what the `e2e-test-runner` file should do then. 

The cypress tests are a pain to run locally because they install and uninstall.

I guess we either put that fangling back in the script or say people need Cypress as a global dependency. Global dependencies are yucky so it'd be reverting that e2e-test-runner script too.

----

What was it slowing down locally? 

We need to find a faster solution. My worry is we're not adding UI tests because they're slow to write and run. So we're not getting the benefit of the time we are spending

**Comment by benjackwhite** [comment]
Also in favor of finding a better solution for this than the current e2e-test-runner. It's confusing and hard to work with which makes E2E tests painful. I thought we investigated this and found it didn't increase the docker image size since we did the whole optimised docker build work?

**Comment by pauldambra** [comment]
In [the PR that added it in we can see docker image size](https://github.com/PostHog/posthog/actions/runs/2824585820) is 471.12MB. 

[With Cypress excluded](https://github.com/PostHog/posthog/actions/runs/2867239445) its 471.33MB 

So barely changing the image size (although we do risk death by a thousand cuts of accepting many small increases)

I thought that the impact of having it present was when we run (a fresh) `yarn install` we have to wait for Cypress to be installed. But we don't have to wait for cypress to be installed and removed each time we run the test script

The impact of it not being present is the reverse (Captain Obvious reporting for duty). We don't wait on install but do when we run the e2e test script. 

So for local dev it felt like only a win. I'd rather fix impact on build time than lose the benefit of e2e test runner being faster.

**Comment by mariusandra** [comment]
What about `yarn workspaces`? (Or `pnpm workspaces` if we do not want to get to other goals this sprint.)

With workspaces we could use separate `package.json` files to create isolated, yet interlinked packages such as:

1. `@posthog/frontend`
2. `@posthog/plugin-server`
3. `@posthog/apps-common`
4. `@posthog/cypress-devtools`
5. `@posthog/esbuilding`

There's surely a clever trick we can use to only install what's needed when building the docker container, and get the others locally when relevant.

**Pull request closed without merging**
