### PR TITLE
feat: guidance for using projects in the new project modal

### PR DESCRIPTION
**Pull request by lharries**
## Problem

Often users are separating each product into a different environment, leading to a suboptimal experience where they can't track conversion across their marketing website and app + they don't have a unified view of the customer. I've updated the docs here https://github.com/PostHog/posthog.com/pull/4905

## Changes

This gives them the opinionated best practices as they make projects.

Screenshot Homepage • PostHog (Google Chrome) 2022-12-15 at 23 15@2x

## How did you test this code?

Ran it locally

### CODE REVIEW

**Comment by lharries** [comment]
Potentially we could change the name "Default Project" to "Production" too? cc @Twixes

**Comment by montrifork** [comment]
Is this only for entreprise users?

**Comment by lharries** [comment]
Hi @montrifork, multiple projects are available on everyplan apart from open source

Screenshot Organizations and projects - Using PostHog - PostHog (Google Chrome) 2022-12-16 at 15 03@2x

**Review by mariusandra — APPROVED** [review]
Work for me

**Comment by Twixes** [comment]
Guidance is good, though I'm seeing a couple of issues to be cleaned up here:
 - We should be using `ol` instead of plain 1. 2. 3.
 - Double `br`s don't look good, let's just use margin
 - Is it true that most companies will want those particular three projects? This seems very opinionated, and for instance _we_ don't really use PostHog this way. I'm afraid such a specific list may lead to users shoehorning by users, and it makes for a bit of a wall of text (for a modal).

**Comment by montrifork** [comment]
@lharries then is this pull request regarding the cloud? I thought this pull requests concerns only the open-source.

**Comment by lharries** [comment]
@montrifork yep for both cloud and open-source it adds guidance for how to use projects. The full docs changes are here: https://github.com/PostHog/posthog.com/commit/e0ce8359675ee72552453fb655715cb51e79b7f7

Are you concerned by anything or just curious? (It's just adding some extra words so not a major change)

**Comment by montrifork** [comment]
@lharries I'm discovering posthog at the moment and I'm trying to draw the line between the open source version and the others in term of features, I just found this pull request kind of confusing since what I understood so far is that multi projects is only supported in the cloud and the enterprise version and now I see a source code concerning the multi project getting merged to the open source version, I hope you understood my confusion.
Now I'm more curious about  how does the separation of features is done in Posthog if you can commit code concerning the cloud without compromising how the open source version will work.
FYI I just pulled the last changes from master and I'm getting an error(it was working with an earlier commit):
`[TYPEGEN] 💔 frontend/src/scenes/session-recordings/player/add-to-playlist/playerAddToPlaylistLogicType.ts:6:74 - error TS2307: Cannot find module '../../saved-playlists/savedSessionRecordingPlaylistModelLogic' or its corresponding type declarations.
[TYPEGEN] 
[TYPEGEN] 6 import type { PlaylistTypeWithIds, RecordingTypeWithIdAndPlaylist } from '../../saved-playlists/savedSessionRecordingPlaylistModelLogic'
[TYPEGEN]                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[TYPEGEN] 
[TYPEGEN] 💔 frontend/src/scenes/session-recordings/player/new-playlist/playerNewPlaylistLogicType.ts:7:38 - error TS2307: Cannot find module './playerNewPlaylistLogic' or its corresponding type declarations.
[TYPEGEN] 
[TYPEGEN] 7 import type { NewPlaylistForm } from './playerNewPlaylistLogic'
[TYPEGEN]                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
[TYPEGEN] 
[TYPEGEN] 💔 frontend/src/scenes/session-recordings/saved-playlists/savedSessionRecordingPlaylistModelLogicType.ts:6:99 - error TS2307: Cannot find module './savedSessionRecordingPlaylistModelLogic' or its corresponding type declarations.
[TYPEGEN] 
[TYPEGEN] 6 import type { PlaylistTypeWithIds, PlaylistTypeWithShortId, RecordingTypeWithIdAndPlaylist } from './savedSessionRecordingPlaylistModelLogic'
[TYPEGEN]                                                                 `

**Comment by thmsobrmlr** [comment]
@montrifork Regarding the error you get: try running `pnpm typegen:clean && pnpm typegen:write`. I'm assuming you have stale generated typings for our kea logics.

**Comment by lharries** [comment]
@montrifork got you. The best way to see what's OSS is to use the [product manual](https://posthog.com/manual/dashboards) as shown below. We used to have a direct table to compare all the features but that seems to have gone - I'll add a note to add that back.

Screenshot Dashboards - Using PostHog - PostHog (Google Chrome) 2022-12-19 at 19 24@2x

In general, if using it for anything professional/commercial I'd highly recommend cloud as there's far less overhead for maintenance and setup. But you're still welcome to deploy the OSS version via docker

**Pull request merged**
