### PR TITLE
fix(experiments): creation form UI bugs 

### PR DESCRIPTION
**Pull request by liyiy**
## Problem

1. remove asterisk
Screen Shot 2022-03-10 at 12 12 09 PM

2. Fix not lined up property filters
Screen Shot 2022-03-10 at 1 17 43 PM
Screen Shot 2022-03-10 at 1 19 04 PM

3. Fix variants error field display
Screen Shot 2022-03-10 at 12 12 03 PM
Screen Shot 2022-03-10 at 12 20 50 PM

4. Fix variants listing spacing
Screen Shot 2022-03-10 at 1 33 04 PM
Screen Shot 2022-03-10 at 1 33 13 PM

## Changes

👉 *Stay up-to-date with our [coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by neilkakkar** [comment]
This is <3 <3 <3! 

Also, I noticed a property filter bug that was causing experiments to 'whitescreen' :$ 

Empty objects in js are truthy -> https://github.com/PostHog/posthog/pull/8973/commits/b461ea4769196160b0b632e29d9ae1328d6b1c9b . Flagging since you might've more context, and remember more places on the frontend where we're currently doing the same for property groups 😅

**Comment by neilkakkar** [comment]
Annd d'oh, I made the change in the wrong place. Wasn't needed there.

Here's the issue though, not sure how we've handled this elsewhere so asking:

https://github.com/PostHog/posthog/blob/master/frontend/src/lib/utils.tsx#L1291 -> This line assumes it's a list, but this is not necessarily so. It can be an empty object as well, which doesn't have the filter function defined.

Do we need more explicit checking here?

**Comment by clarkus** [comment]
Unsure if my review is still needed or not. There is a design for this area of the form at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498. I wasn't tracking that there are naming conventions or syntax options to highlight - I don't think we should use our destructive color palette for that. Do you want me to incorporate that into the design or go with what you have already?

Screen Shot 2022-03-11 at 9 37 53 AM

**Comment by neilkakkar** [comment]
Hey @clarkus , happy to incorporate if you have a suggestion about syntax options to highlight :)

**Comment by liyiy** [comment]
We can go with what's on the mocks, this was just a quick fix for the really obvious UI bugs

**Pull request merged**
