### PR TITLE
Turbo mode

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- **Turbo mode!** Like in the good old 486DX days!
- Much better and cleaner version of #6614 and #6600
- This PR just the logics of previously visited scenes running in the background, instead of rendering the entire scene into the DOM and hiding it with `display:none` like the previous PRs did.

- Before:

- Activating Turbo Mode!

- After:

- Flyby bugfixes:
  - Pressing "back" and changing from "cohorts/7" to "cohorts/" now closes the drawer
  - "Jest Tests" pycharm run configuration
  - Split the "sceneLogic" file into "sceneLogic", "scenes" (this one links to all imports now) and "sceneTypes".
  - Split the "events" scene into 4 separately mountable scenes (events, actions, event stats, event property stats). Caching their respective logics is now handled by sceneLogic, instead of internally
  - The `/i/:insight_short_id` urls did a `push`, but should have done a `replace`
  - Remove the age-old code where each Scene was passed `user` as a prop, instead of taking it from `userLogic`, from the scenes that still were using this prop
  - Fixed a bunch of sort mutation bugs. Should switch kea's values to `ReadOnly<>` probably soon!
  - Split up the kea test init code into a function that takes no logics and can be put inside beforeEach()

## How did you test this code?

- A lot of manual testing
- Added tests to make sure loaded scenes stay in memory in sceneLogic
- Added test to make sure when opening a dashboard item with the right url, we take the data from the dashboard logic directly

### CODE REVIEW

**Comment by mariusandra** [comment]
Ready for a look @Twixes , no jest/TS errors locally, hoping for the same in the pending CI run.

**Review by Twixes — COMMENTED** [review]
This is nice overall, but I'm not completely sure if the restructuring of the Events page is good.
1. Switching to the main Events tab (this does not seem to apply to Actions and other tabs), including from the sidebar, now feels significantly _more_ sluggish.
2. The sidebar item only is highlighted when in the Events tab, despite other tabs (e.g. Actions) being on the same page from the user's perspective.
	Zrzut ekranu 2021-10-26 o 16 00 10

**Comment by mariusandra** [comment]
Changes done. The events page was always really slow to me thanks to that huge table. Check out some other pages with huge tables (e.g. feature flags) to see the same sluggishness... :(

**Review by Twixes — APPROVED** [review]
I may still be wrong but I don't think it's only as bad as before. Looks like handling the click event on the Events tab button is a worse slowdown than before, and this seems to be the main contributor to slugishness – loading is not as noticeable once the base of the scene is loaded, but if everything tries to render at once ASAP it's worse. Maybe after the restructuring things are now loaded earlier, causing this effect in a more abrupt way.

| `master` | `turbo-mode` |
| --- | --- |
| before | after |

But this definitely does all boil down to the table component (the flame graph points to it too), so I guess we can live with it for a bit. Once the table is optimized, this _should_ be gone.

**Comment by mariusandra** [comment]
I guess that's because the table is always empty for the non-turbo case, and renders fast... but now it can be a full 200 row table, causing a lot of sluggishness. I'll document this as a followup in https://github.com/PostHog/posthog/issues/6513 that we'll need to resolve before we can remove the flag.

**Pull request merged**
