### PR TITLE
fix(surveys): survey results displaying in edit mode

### LINKED ISSUE #25554: Bug: NPS survey type, Issue with Survey Explore Results.
## Bug description

When analysing a survey and clicking explore results, on a NPS survey type the embedded NPS insight becomes editable in the surveys screen and this cannot be undone without logging out

image

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. Have a NPS survey type with results
2. Click explore results on any other survey (or the NPS survey)
3. Navigate back to the NPS survey
4. The embedded insight is now in edit mode

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by Aashw1n**
## Problem

Fixes #25554

Embedded insight shows up in edit mode if a new insight is whipped up anywhere in the application (+ new insight in product analytics, open as insight in the web analytics section ,and the explore result button in survey results). Video below would demonstrate.

https://github.com/user-attachments/assets/c68b88e8-f375-4b36-8981-0c620e87570e

## Changes
The Query Component has a prop `readOnly` that fixes this when enabled, without affecting anything else. 
Please let me know if there's anything I'm missing, or if you'd prefer a specific fix. 

Video Below shows embedded insight after the fix: 

https://github.com/user-attachments/assets/d60202ac-ec17-4b50-8caf-7b6007e35ed1

## Does this work well for both Cloud and self-hosted?

Local Development

## How did you test this code?

Automated tests mentioned in the "Develop Locally Handbook", as well as manual before-after tests.

### CODE REVIEW

**Comment by Aashw1n** [comment]
Hi @Phanatic,
Requesting a review on this before it goes stale

**Comment by Phanatic** [comment]
Thanks for opening this PR @Aashw1n I have this on my list to look at first thing tomorrow morning.

**Comment by Aashw1n** [comment]
Hi @Phanatic!
Quick reminder for a review on this

**Review by Phanatic — APPROVED** [review]
Looks good! Please fix failing tests in CI and I can merge this PR in.

**Comment by Aashw1n** [comment]
Hi @Twixes @Phanatic 
Thanks for the approving review 😁.
The automerge wasn't kicked off after the approving review, so I just want to make sure this is merged and closed off.

**Pull request merged**
