### PR TITLE
Plugin ordering

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

It took me a while to place this in the UI in a sensible way, but the end result makes a lot of sense I think:

buttons
reordering

However only when writing the Kea logic for this did I realize that for instance the plugin config is not created when a plugin is installed and we can't actually base things on that… In fact I'm kind of confused how installing plugins works with configs. Why doesn't each plugin installation per project get its own config outright mandatorily? @mariusandra Otherwise I don't think `PluginConfig.order` makes sense?

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by Twixes** [comment]
Note: there should probably be a note under the pipeline in Reordering Plugins that these items are draggable.

**Review by mariusandra — COMMENTED** [review]
Hey! 

This ordering is definitely important, yet not yet important a tricky thing to get right, so I was planning to defer it as long as possible :).

When we do implement plugin ingestion in JS, it will need to be the last plugin anyway, so ordering technically doesn't matter for it.

Regarding this:

> However only when writing the Kea logic for this did I realize that for instance the plugin config is not created when a plugin is installed and we can't actually base things on that… In fact I'm kind of confused how installing plugins works with configs. Why doesn't each plugin installation per project get its own config outright mandatorily? @mariusandra Otherwise I don't think `PluginConfig.order` makes sense?

Yeah...

I kind of "deprecated" global plugins now (pending work to get them working with organisations, access rights, etc), but the tricky bit here is that plugins can be installed without being enabled... and plugins can be installed and enabled globally, with no per-team config. All of this will need to share the `order` logic somehow.

So, currently we have:
- Plugins (aka plugins installed into the instance)
- PluginConfig (aka plugins configured and then enabled either per project or globally)

Each PluginConfig results in an installation of the plugin and extra memory usage on `posthog-plugin-server`. This is probably fine for most cases, but not for the `posthog-maxmind-plugin` that loads a 70MB database and then stores it somehow in memory. Enabling that on app per team would not work. 

The idea was to "globally enable" (`team=None`) this plugin and have it run for all teams. If we do this on `app`, we will still need an option to "opt out" (or in?) to this globally enabled plugin per team. Perhaps by creating a fake `PluginConfig` that has a foreign key to the globally enabled PluginConfig, with a new `order`... so it would reuse the `vm` in the server?

Plus, all of that should be communicated in the interface clearly.

Like I said, this gets tricky quickly... :D. I'd just try to get the ingestion working first.

Quickly going through this PR, I found two issues:

The reordering seems to be "stuck" somehow:


I'm getting some TS errors:
image

**Comment by Twixes** [comment]
Oh, yep, it's definitely a draft because I got confused by how configs are supposed to work. Let's get back to this after ingestion then.

**Comment by mariusandra** [comment]
Some thoughts regarding this. I would redo the main interface of the plugins from cards to a one-dimensional list/stack. In that case the order is pretty clear and could be made explicit.

**Comment by Twixes** [comment]
Hmm, so I think we'll integrate something like this into the main installation area? @mariusandra 
Also, `react-sortable-hoc` would definitely work better for this than `react-grid-layout`.
Feel free to close if you believe we should ditch this PRs approach.

**Comment by mariusandra** [comment]
To keep things clean, let's close this and continue once https://github.com/PostHog/posthog/pull/2939 lands.

**Pull request closed without merging**
