### PR TITLE
feat(hogql): groups support - part 1

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

HogQL is missing support for groups.

## Changes

This is part 1 of such support. I decided to split it up into two PRs to get the easy wins out quickly, and not get stalled with support work.

- [x] Refactors the huge `database.py` into smaller files. The new changes are in `groups.py` and `cohort_people.py`
- [x] Adds fields `goe_{index}` to events to access "groups on events" properties. No support for "groups not on events" yet, see the TODO below.
- [x] Splits `raw_groups` and `groups` tables. The table without "raw_" contains some SQL magic to remove duplicate fields.
- [x] Do the same split for the "cohort_people" table because why not: it's been pending and was a small thing.

## Todo in part 2

- [ ] Create an automatic join on the events table to access "groups not on events"
- [ ] Use short formats like "event.organization.bla" or "person.account.foo"
- [ ] Double check conflicts and team-id overrides with these short formats
- [ ] Make it work in non-HogQL insights

## How did you test this code?

- I tested selecting from both the `groups` and `cohort_people` tables in the UI, with some changed rows in the database. Everything worked.
- Updated snapshots and queries in tests to show minimal changes.

### CODE REVIEW

**Comment by mariusandra** [comment]
Fixed the tests and this is ready for a review. Since the columns change for different tables with PoE on or off (`person_id` is added as a string field with PoE on), I had to lock a few `select * from events` tests down to just one variant. 

We're changing PoE to v2 soonish anyway, and the "[custom sql fields](https://github.com/PostHog/posthog/pull/15180)" PR will change the way fields are resolved as well, so I'm not too bothered by this right now.

**Review by Twixes — APPROVED** [review]
This seems straightforward

**Comment by Twixes** [comment]
Maybe one question is: should the raw versions be exposed to users?

**Comment by mariusandra** [comment]
> Maybe one question is: should the raw versions be exposed to users?

Good question. They can be sometimes useful to users, so hard to say. As tables they should just work when selecting (we need to select from somewhere), but we could hide them in the database scene. They could be useful for more advanced users to debug issues though 🤔.

Edit: they could also be useful for "breaking out" of our `argMax` jail, e.g. to get a speed boost somewhere.

**Pull request merged**
