### PR TITLE
perf(cohorts): reduce select batch size, and sleep 1 between

### PR DESCRIPTION
**Pull request by hazzadous**
Previously we were hammering the database, see
https://github.com/PostHog/product-internal/issues/256 for details. Now
we:

 1. reduce the batch by 5 times
 2. have a little sleep(1) between batches

We also add a little bit of logging for instance in failure cases.

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Review by guidoiaquinti — APPROVED** [review]
LGTM 🚢  (looping @EDsCODE for visibility)

**Comment by neilkakkar** [comment]
I think we were doing this because we wanted to maintain some semblance of the "cohorts are recalculated every 15 minutes guarantee". (Last I remember, @timgl was working on this?)

Think it makes sense to update these guarantees as well, to say something like, recalculated every hour.

**Comment by hazzadous** [comment]
> I think we were doing this because we wanted to maintain some semblance of the "cohorts are recalculated every 15 minutes guarantee". 

Ah! I don't think this will change the frequency of update but will change the response time. We schedule about 1 every minute so the frequency will be tied to the number of cohorts in the system. Does that pass a sanity check?

@neilkakkar where abouts are do we state the guarantee?

**Comment by neilkakkar** [comment]
Yes, that makes sense. Ah, wait, this is cohortpeople batches, not the cohort recalc batches. So, this may slowdown recalc only for cohorts with > 10,000 people?

image

**Comment by neilkakkar** [comment]
Yes, that makes sense. Ah, wait, this is cohortpeople batches, not the cohort recalc batches. So, this may slowdown recalc only for cohorts with > 10,000 people?

Hmm, makes sense, probably no need to change this guarantee at all for now.

**Comment by guidoiaquinti** [comment]
> I think we were doing this because we wanted to maintain some semblance of the "cohorts are recalculated every 15 minutes guarantee". (Last I remember, @timgl was working on this?)

To be super clear: there has never been a guarantee of cohorts being recalculated every 15 minutes. If we need this to happen we should revisit how cohort recalculation works.

**Comment by timgl** [comment]
> To be super clear: there has never been a guarantee of cohorts being recalculated every 15 minutes. If we need this to happen we should revisit how cohort recalculation works.

It used to be this way hence it says so in the tooltip. It doesn't need to be guarenteed though, we should just aim to reduce the number

**Comment by guidoiaquinti** [comment]
Running every 15 min doesn't guarantee they get re-calculated successfully every 15 minutes. Before the cohort fix we pushed last week, few cohort recalculations were constantly failing due to the size.

**Comment by timgl** [comment]
> Running every 15 min doesn't guarantee they get re-calculated successfully every 15 minutes. Before the cohort fix we pushed last week, few cohort recalculations were constantly failing due to the size.

I'm talking way way back here. But agree i'd be a good idea to change the tooltip to not say 15 minutes.

**Pull request merged**
