### PR TITLE
Gunzip request body json

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

This makes posthog accept gzip-encoded json. Required to get the iOS integration working.

## Checklist
- [x] All querysets/queries filter by Team
- [ ] Code reviewed
- [ ] QA'd

### CODE REVIEW

**Review by timgl — COMMENTED** [review]
could we add a test for this?

**Review by SanketDG — COMMENTED** [review]
I may be wrong here, but it seems like [Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) seems to be used and `Content-Encoding` on the response.

Also Django has a `middleware` for this https://docs.djangoproject.com/en/2.2/_modules/django/middleware/gzip/

**Comment by mariusandra** [comment]
@SanketDG what you're describing applies when a client asks for a page from the server and it replies. In that case the client specifies if the response could and should be compressed or not. 

What this fix addresses is a different case. Here the client submits a POST request with a compressed payload, without first asking if the server is able to accept it. The client in this case is the (not yet released) `posthog-ios` integration.

@timgl yes, definitely this should get a test case. I'll add one soon.

**Comment by SanketDG** [comment]
Apologies, looks like I had a completely reverse understanding.

**Comment by mariusandra** [comment]
@timgl The gzip test is now there. The iOS integration will only send gzipped payloads, so this is required to get it to work :).

**Review by timgl — APPROVED** [review]

**Pull request merged**
