### PR TITLE
Filter session recordings

### PR DESCRIPTION
**Pull request by rcmarron**
## Changes

TODO:
- Backend
    - [x] Clickhouse filter recordings by those containing an event
    - [x] Clickhouse filter recordings by timestamps
    - [x] Clickhouse filter recordings by session duration 
    - [x] PG filter recordings by those containing an event
    - [x] PG filter recordings by timestamps
    - [x] PG filter recordings by session duration
    - [x] Support pagination
    - [x] Add person object to serializer
    - [x] Tests
- Front end
    - [x] Add duration filter
    - [x] Add time filter
    - [x] Add pagination
    - [x] Add event filter
    - [x] Clean up list view (add person etc.)
    - [x] Style events filter
    - [x] Tests

## How did you test this code?

Wrote tests for both front + back end

### CODE REVIEW

**Comment by rcmarron** [comment]
@clarkus I took a look at the two filtering designs [here](https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1121%3A143574) and [here](https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=838%3A140334).

I think there's a bunch we can just grab from those. 1 piece that doesn't seem straight forward is filtering recordings by **events/actions** not just the event/action properties. I was imagining an experience where a user can ask "Show me all recording where a 'clicked buy button' event happened on the '/shopping' url". It looks like we do a similar thing in a couple of places:

**The funnel step control (and other insights)**:

image


**The existing session filter**:

image

I'm happy to just run with one of these approaches (the existing session filter seems more appropriate - because it's a filter), but I wasn't sure if the funnel step control is the direction we're trying to move everything toward.

Wanted to make sure we're on the same page for the general direction before I start building.

**Comment by clarkus** [comment]
> I think there's a bunch we can just grab from those. 1 piece that doesn't seem straight forward is filtering recordings by events/actions not just the event/action properties. I was imagining an experience where a user can ask "Show me all recording where a 'clicked buy button' event happened on the '/shopping' url". It looks like we do a similar thing in a couple of places:

@rcmarron let's go with the existing session filter for now. It does what we need and we know we might be refining this again in the future as we learn more.

**Comment by rcmarron** [comment]
> @rcmarron let's go with the existing session filter for now. It does what we need and we know we might be refining this again in the future as we learn more.

@clarkus just took a quick look here, and the existing sessions filter is pretty tightly coupled with the rest of the functionality of sessions that session recordings doesn't support yet (saved filters, person property filters etc.). I think it would be harder to use that one than to just run with the newer action filter.

Playing with the new action filter, it seems to "just work" out of the box. It'd be something like this (obviously with a bit more polish). Any issue with that direction?

image

**Comment by clarkus** [comment]
@rcmarron do we need to support multiple groups of rules with operators? I have some designs that will work for group-level operators (match any or match all), but I'd need some time to draw something that will work with multiple groups. 

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4021%3A29956

Screen Shot 2021-10-04 at 5 25 08 PM

**Comment by rcmarron** [comment]
Alright, this is ready 😅.

A couple of notes:
* There are 2 follow issues that we can prioritize appropriately:
    * https://github.com/PostHog/posthog/issues/6318
    * https://github.com/PostHog/posthog/issues/6319

Here are a few screen shots:

### No filters
image

### Duration filter
image

### Entity Filter
image

### Date Filter
image

**Review by paolodamico — COMMENTED** [review]
Looking good Rick! Some comments UX-wise,

- I love the new "Last X days" buttons but are fairly inconsistent with the rest of the app, wonder if we should introduce them, @clarkus for thoughts.
- When I click "Last X days" it seems strange that an end date is not filled, feels like a bug (though I know it makes sense).
- The way to add an event/action filter feels clunky. You need to click like 4 times to get into search mode, I would suggest just having the dropdown there directly, you click on it and it pops up right away (i.e. filters get added automatically).
    - Related, when you first open the taxonomy dropdown it's in a strange state where no tabs are selected.
- Maybe make the play button a bit bigger and primary color? Also I believe we mostly use the squared version to represent session recordings.
- Play buttons no longer seem to change when you've watched a recording.
- I'll let @clarkus chime in but I think the positioning of the filters is a bit unintuitive, they're distributed across the page and not aligned, but unsure exactly where these should be.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/2779

**Comment by clarkus** [comment]
> The way to add an event/action filter feels clunky. You need to click like 4 times to get into search mode, I would suggest just having the dropdown there directly, you click on it and it pops up right away (i.e. filters get added automatically).

> Related, when you first open the taxonomy dropdown it's in a strange state where no tabs are selected.

I think this could be resolved by autofocusing and some sane defaults. When I click add `event or action filter` we should focus the search input, display the default list of options. It looks like there aren't any defaults loading in. Really this feedback is that this should work a lot like it does when building an insight query (Automatically trigger next steps where it makes sense)

> I love the new "Last X days" buttons but are fairly inconsistent with the rest of the app, wonder if we should introduce them, @clarkus for thoughts.

I see what @rcmarron was going for here. I linked another issue that maps out some date picker improvements, but doesn't explicitly address preset date ranges. I think the easiest thing for a user would be to select a preset range first. If that preset range doesn't satisfy the needs, then use a custom picker to be more precise with input. 

Screen Shot 2021-10-08 at 8 38 40 AM

Regarding icons / play buttons, I think we can pull in some of those changes from recordings and add them here. I am going to work through a review for this as well. Looking like a great start @rcmarron

**Comment by clarkus** [comment]
Here's a breakdown of the steps it takes to add a filter item now (plus a video):

1. Click add event or action filter
2. Click select filter
3. Click a tab option
4. Click an event or action result in the list

The desired changes would be:

1. Click ad event or action filter
2. The select filter click automatically triggers to show the taxonomic picker with the first tab selected. This would give a one click action to get to the 4th step where a use could pick their item or search for the one they want.

https://user-images.githubusercontent.com/254612/136586393-5ffbf183-b7ec-44e0-b7ed-7a6a7ee81a4c.mov

**Review by clarkus — CHANGES_REQUESTED** [review]
We should disallow date selections that haven't happened yet or those that precede recordings being enabled. Does it make sense to have an unbounded value field for durations?

Screen Shot 2021-10-08 at 8 49 32 AM

When using a date range preset it's weird that today's date isn't set as the end of the range. Being unbounded just makes you question how it's working. Showing that option would reinforce how the range works. 

Screen Shot 2021-10-08 at 8 51 41 AM

This is a minor nit and I am aware this is a pre-existing decision, but the alternate styling for the `and` here could be dialed down a bit to match the `where` label. It just makes that `and` look actionable when it's not. It's also always an `and` scenario, so we could communicate this at a group level, too. 

Screen Shot 2021-10-08 at 8 53 57 AM

**Review by alexkim205 — CHANGES_REQUESTED** [review]

**Comment by rcmarron** [comment]
@paolodamico @clarkus 

Great feedback!

I just pushed up some UX fixes that I think address your comments.

### No filter selected

image

### New Date filter (the one we use elsewhere)

image

### Filter control is focused on clicking the button

image

**Review by clarkus — APPROVED** [review]
Just tried it out and it's a lot better. Thanks for the quick turnaround on changes.

**Review by paolodamico — COMMENTED** [review]
I think this is solid enough to merge and start testing the page deprecation. Definitely think we can significantly level up the UX here (as a future improvement). It particularly still feels like quite ad-hoc and not really in line with the rest of the app. CC @clarkus 

Probably worth @alexkim205 or @mariusandra taking a look at the code before merging

**Comment by clarkus** [comment]
> I think this is solid enough to merge and start testing the page deprecation. Definitely think we can significantly level up the UX here (as a future improvement). It particularly still feels like quite ad-hoc and not really in line with the rest of the app. CC @clarkus

Yeah I think this is true of most pages that revolve around query builders. I think there's a case for more standardization but we're going to have to make time to address it across features. I have a good start on the work, but would need more time to really figure it out.

**Comment by alexkim205** [comment]
Other than my one comment, lgtm!

**Review by alexkim205 — APPROVED** [review]

**Comment by mariusandra** [comment]
This is really awesome! Great work! 😄 

One thing for the wishlist: on cloud when filtering, the table still loads for a few seconds. Since there's no loading indicator, it feels a bit broken until it suddenly reloads.

**Comment by rcmarron** [comment]
Thanks! ~~PR coming in a few minutes with that and storing the filter in the URL~~ PR here: https://github.com/PostHog/posthog/pull/6370

**Pull request merged**
