### PR TITLE
refactor(insights): Unify relative date parsing

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Our relative date (e.g. "-7d", "-1mStart") parsing logic was duplicated between `posthog.utils.relative_date_parse` and `posthog.queries.query_date_range.QueryDateRange._parse_date`. This was confusing and those branches already had diverged a bit (some time ago the `posthog.utils` version was refactored to also return the parsed unit-value mapping).

## Changes

Refactored to unify this handling into `QueryDateRange`, as suggested by @EDsCODE [in Slack](https://posthog.slack.com/archives/C034XD440RK/p1673024382380479).

## How did you test this code?

Relying on existing tests.

### CODE REVIEW

**Comment by mariusandra** [comment]
While this PR was in progress, I [managed to add](https://github.com/PostHog/posthog/pull/13681) `relative_date_parse` from the _wrong_ location into `posthog/models/event/query_event_list.py`. 🤔

**Comment by Twixes** [comment]
Turns out it's a huge pain put this into `QueryDateRange`, since `relative_date_parse` is also used by filter mixins (`DateMixin`), and `QueryDateRange` is filter mixin-aware at runtime for typing reasons, which results in circular imports. Also, practically everywhere the `utils` version is used now, so by sticking to that we avoid having to update lots of imports. Hence I propose we just make the `utils` function canonical – the diff is really small this way.

**Review by mariusandra — APPROVED** [review]

**Comment by mariusandra** [comment]
The approach makes sense to me, though there's one failing backend test.

**Comment by Twixes** [comment]
Well, the devil is always in the failing tests. That one test uncovered a problem arising from discrepancies between those two duplicates of the date parsing function – in some places we've been rounding `date_from` down to the start of the day/hour, and in other places we haven't. I consolidated this, but now I need to see what other tests are gonna fail, and whether the existing behavior is the one we want to keep 100%.

**Review by EDsCODE — APPROVED** [review]
> Turns out it's a huge pain put this into QueryDateRange, since relative_date_parse is also used by filter mixins (DateMixin), and QueryDateRange is filter mixin-aware at runtime for typing reasons, which results in circular imports. 

Fair enough! I'm not opinionated on where these implementations live/how we dedup as long as we move closer towards a more consolidated understanding of how timestamps are handled. I originally wanted to move more logic into the query date range class but as you noted the util function is used in various places that would take a good bit of refactoring to make this make sense

**Pull request closed without merging**
