### PR TITLE
New login & signup (React)

### LINKED ISSUE #3339: Migrate login & account signup to new design/component
## Is your feature request related to a problem?

Following #3300, the regular signup screen and login page are out of sync with the new design and components. Further, the login page is still a Django static page.

## Describe the solution you'd like
We should now migrate the regular signup screen and the login page to the new components/design.

Additionally we should improve the overall UX of invites as suggested on point 4 of @Twixes review from #3300 to only show login or signup (respectively) when accepting a user invite.

## Describe alternatives you've considered
Keep everything as is.

## Additional context
The `LoginSignup.tsx` already introduces some preparations to support these new screens/flows.

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

This PR migrates the login page to React and the default signup page to the new design.
- Closes #3339.
- Fully refactors signup & login routes under a `auth` namespace for code clarity. Everything now fully running on Kea & TS.

In addition this PR:
- Introduces `/api/login` endpoint for REST-based login.
- Changes the way we do authentication in E2E tests (to doing them client-side vs. server-side automatic) so that we can properly E2E test signup flows.
- Introduces tests for critical signup flows.
- Removes all legacy signups & logins.
- Fully validates inputs on the client-side for better user experience.
- Updates the way we display social login buttons as per discussion on #3339
- Properly displays server-side error messages (e.g. when you're locked out by Axes).
    

### Signup page
Signup process is now split into 2 steps to improve conversion.
image

**Self-hosted version**

**Mobile version**

**Input validation**
Note that we show a different content on the left-hand side if you're running on cloud vs self-hosted.
image

### Login page

**Mobile version**

## Checklist

- [X] All querysets/queries filter by Organization, by Team, and by User
- [X] Django backend tests
- [X] Jest frontend tests
- [X] Cypress end-to-end tests

### CODE REVIEW

**Comment by paolodamico** [comment]
Tagging @corywatilo too for a final UI/UX review

**Comment by corywatilo** [comment]
Looks great! Just small nits (you choose what's above the line):

### Signup

**Both versions**

1. Can we add a bit more padding between logo row and page title?

**In _Self-hosted_**

1. Text change: "Interested in Cloud?" -> "Interested in a hosted solution?"
2. Remove line below _PostHog Cloud_ option - that should only show if there's an item below

### Login page

1. Headline: "Welcome back to PostHog" -> "Welcome back!" (Just because we have "PostHog" in the login form, so it feels superfluous.

**Comment by paolodamico** [comment]
All feedback addressed @corywatilo !

**Review by timgl — APPROVED** [review]
LGTM

**Pull request merged**
