### PR TITLE
fix: close button overlap on modal

### PR DESCRIPTION
**Pull request by Tomolo997**
## Changes

Fix screenshot:

Screenshot 2024-03-07 at 22 08 08

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by raquelmsmith** [comment]
Thanks for your contribution here @Tomolo997. Can you explain where you saw this modal? I'd like to fix that issue more pressingly 😄

**Comment by Tomolo997** [comment]
Hi this the pull request. https://github.com/PostHog/posthog/issues/20769

**Comment by Tomolo997** [comment]
@raquelmsmith is this something that should be updated or reviewed?

**Comment by raquelmsmith** [comment]
Yes, sorry I was leaving this as a reminder to look into the reason why this was appearing at all, as you should theoretically never see it. We can just get it in though. Looks like there's now a conflict - do you want to look into that?

**Comment by Tomolo997** [comment]
Yes i did manage to rebase it and then push it. So it can be checked again.

**Pull request closed without merging**
