### PR TITLE
Kea-typegen auto-import

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Upgrades `kea-typegen` to version `0.8.0-beta.1` which now automatically imports all referenced types inside logic type files. All local types (`type` next to `const logic`) will also automatically be added to the end of the `logicType<Types>` list.
- It's still beta, so some things are still not optimal. However,
- **Reduces number of TypeScript errors from ~300 to ~~133~~ 110**

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

**Comment by macobo** [comment]
You might need to regenerate the typescript errors file. See comment at top of .ts-strict-blacklist

**Comment by mariusandra** [comment]
Done! 

If we exclude `Type.ts` files, we have TS ~25 errors left. Including type files, we're at 110 TS errors.

**Review by macobo — APPROVED** [review]
:rubber: :stamp:

**Comment by mariusandra** [comment]
Awesome! Let's get this in then. I'll gradually fix the remaining errors in `*Type.ts` files in the coming days/weeks. 

Almost there...

**Pull request merged**
