### PR TITLE
feat(correlation): add property correlation to funnels UI

### PR DESCRIPTION
**Pull request by hazzadous**
## Changes

Added correlation table for properties. Not clean but enough to get something out.

## How did you test this code?

Ran locally, played around with funnels. (actually, @neilkakkar did as I couldn't get sensible sample data)

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
With the caveat that: we'll come back after a round of feedback to clean this up, and dedupe most of this, LGTM.

**Review by neilkakkar — CHANGES_REQUESTED** [review]
Actually, just one thing: We may use this to demo as well, so would be nice to have a default llist of properties pre-populated.

I'm thinking: $browser, $os. $geoip_country_code ?

**Review by neilkakkar — APPROVED** [review]
One dot remains, but otherwise LGTM :smile:

**Comment by neilkakkar** [comment]
Oh also, I guess now that https://github.com/PostHog/posthog/pull/6310 is in, we can update the pattern here as well (same as `FunnelCorrelationTable` for instantiating funnelLogic

**Comment by paolodamico** [comment]
Flaky tests failing due to parallelization, merging

**Pull request merged**
