### PR TITLE
style: "Normalize paths" UI suggestion

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

UI proposal on top of #12808:

### Before

Screenshot 2022-11-16 at 11 50 35

### After

Screenshot 2022-11-16 at 11 52 32

### CODE REVIEW

**Comment by Twixes** [comment]
There are a few details here:
- Rows in menus should be the same height (2.5rem in our case usually). If one is smaller, it looks squished.
- Extra info icons shouldn't be at the start of an interactive element (start being left in left-to-right languages). A user first needs to read the label, _then_ they might want to know more.
- Info icons next to labels have a size of 1.25rem (`text-xl`).
- I added `id` to the switch, so that the label toggles it too.
- I propose more concise "Normalize paths", since that's more general (it's slashes AND question marks AND hashes, so quite a mouthful when being precise). However, in the extra info it's probably beneficial to be _more_ specific what are the mechanics (e.g. if we strip hashes, it's safer to mention that, lest a Support Hero gets asked about this down the line). Feel free to change the wording or the name of the option, it's just that balance I really mean
  
Do with this PR as you will @pauldambra

**Comment by timgl** [comment]
flyby question. Should we just _always_ strip noise? With perhaps the exception of query params, is there ever a case where you wouldn't want to do this?
Worried about overloading our interface with options and settings if we can come up with something universal

**Comment by Twixes** [comment]
Good point. I think it's great to have an escape valve, but really I agree it makes sense for this toggle to be enabled by default.

**Review by pauldambra — APPROVED** [review]
🚀 😍 

Agree that default enabled makes sense for this... I wondered about not allowing it to be turned off but the toggle is pretty hidden and I wondered if someone who thought they were already normalising URLs would want to see where they weren't. 

I guess if nobody clicks the toggle and nobody complains we can remove it :)

**Comment by pauldambra** [comment]
There's a conflict here... I'll merge locally to avoid doing a dance in GitHub :D

**Pull request merged**
