### PR TITLE
dev(direnv): add direnv and nix config

### PR DESCRIPTION
**Pull request by hazzadous**
This is what I have been using locally, but perhaps others can benefit
also? It's not a complete solution, but it's a start.

I've added a `.env` file which is setup for `PRIMARY_DB=clickhouse`,
which I guess we want as the default given it should be the only one in
the future. It doesn't contain anything confidential so I do not see any
issue with committiing it, and these vars are required for running a
local dev env. The only other place I've seen these vars is in the
handbook, which isn't very convinient but maybe I've missed something.

It is required to have both https://nixos.wiki/ and https://direnv.net/
installed (and maybe dotenv).

Let me know if it's possible to get this in, otherwise I'll continue with these locally only.

### CODE REVIEW

**Comment by hazzadous** [comment]
@macobo how easy is it to get something like this in?

I can obviously just keep it to myself, but I'd love to integrate and share if possible. Open questions, what do people do to switch to primary_db=postgres (in the future this will not be an issue but that's not now). 

Comments / abuse welcome

**Comment by macobo** [comment]
I have no strong opinions around this - just slightly wary about introducing _more_ configuration tools and things you need to set up.

image

This smells like a proposal PR - if you agree, it would be worth it to:
1. Open a PR against the handbook on local dev setup on how to set everything up
2. Hook more people into this PR to get their opinions/see if they agree with this approach.

As-is this wouldn't be compatible with my setup (I have pyenv + fish-specific script which sets up env vars) but if we switch to something I'm game to switch as well.

**Comment by hazzadous** [comment]
> As-is this wouldn't be compatible with my setup (I have pyenv + fish-specific script which sets up env vars) but if we switch to something I'm game to switch as well.

Yeah I'm thinking most people are actually running the backend/frontend locally, something like https://posthog.com/handbook/engineering/ee-setup Option B.

My drive for this is that, whilst the instructions on ee-setup are available, it's not exactly the most straight forward of processes and everyone appears to have slightly different setups. I'd love to have one sanctioned setup that should be guaranteed to work, but of course you can do whatever you want if you choose.

I might just do a little poll on how people are setting up their local dev. Maybe there's a common option that would be worth catering for.

**Comment by hazzadous** [comment]
Too many PRs open...

**Pull request closed without merging**
