### PR TITLE
Revert #4206 - Test Environment toggle

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Removes the flag that adds this production/test switch and related code added in https://github.com/PostHog/posthog/pull/4206 (couldn't revert directly)

image

## How did you test this code?

- Went through the [original PR](https://github.com/PostHog/posthog/pull/4206) and removed the corresponding code in master.
- Checked that the app still works
- Will hope all the tests on cloud will run

### CODE REVIEW

**Comment by paolodamico** [comment]
Curious what prompted to do this right now? In a more general sense I think it's worth doing this at some point, it's a significantly better clearer mental model than what we have with test / internal users.

**Review by paolodamico — COMMENTED** [review]
Code-wise this looks good to me, but see comment above. If we do plan to revisit this at some point, would we want to keep this around for now?

**Comment by mariusandra** [comment]
The good reason: It's a bad practice to keep unused "just in case" code around, especially [messy looking](https://github.com/PostHog/posthog/pull/6250/files#diff-889eb1aa446eb59c3d1b19f52fec6a0ea0e7fc11ebe13167c4a9382288ad05f1L132-L165) unused JS utils. If a feature didn't make the cut, I'd rather remove it.

The real reason: Locally I enable all flags by defaults (`python manage.py sync_feature_flags`) and this just gets in the way and has to be manually removed all the time.

**Comment by paolodamico** [comment]
Alright sounds good, we can revisit when/if this becomes a priority again.

**Comment by mariusandra** [comment]
The existence of this flag made me lose a bit of time again.

Somehow it adds a `properties` field to every outgoing GET request, causing no event properties to be returned:

image

**Comment by paolodamico** [comment]
Finally tests pass 🙌, looks like we have some flaky backend test

**Pull request merged**
