### PR TITLE
AntD Refactor: Setup Page

### PR DESCRIPTION
**Pull request by SanketDG**
Yet to self-QA thoroughly.

I am looking for advice on the UI/UX, if it looks and fits right.

Screenshot:

image

### CODE REVIEW

**Comment by timgl** [comment]
This looks great! Thanks for doing this 🎉 

A few quick thoughts:
- [ ] Some of the spacing between buttons is inconsistent
- [ ] When there are no URLs at the top of the page the `+ Add Another Url` link wraps weirdly next to the line
- [ ] While we're at it, it might be worth adding an <hr /> between each of the sections just to make it clearer

**Comment by timgl** [comment]
@SanketDG Hey Sanket, did you catch my above PR? Happy to take over doing those items if you can't find the time :)

**Comment by SanketDG** [comment]
@timgl Apologies. I have updated with your comments, I was thinking I would need 2-3 more iterations to get through each page so this should be done over the weekend.

**Comment by SanketDG** [comment]
Screenshot:

image

The icon for the link `Add URL` seems to be misaligned for some reason, could be an Ant thing, will debug this.

**Comment by timgl** [comment]
@SanketDG This looks good apart for that 'add url' alignment issue when there are no URLs set. Let me know when and I can QA that :)

**Comment by SanketDG** [comment]
@timgl Somehow that popped back in, should be okay now :D

**Comment by timgl** [comment]
Looks good, thanks for this!

**Pull request merged**
