### PR TITLE
Show error message on ChunkLoadError

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Show an error message rather than sticking people in a reload loop of death.

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by mariusandra** [comment]
Normally reloading solves the issue, as chunks go missing only when a new version of the app is deployed and old files are no longer there. Thus I wouldn't blatantly show a error message to everyone, but would prefer to try reloading just once.

One option is to set the reloading timestamp in `window.localStorage`, and check if we've already reloaded in the last ~30sec. If so, only then show the error.

**Comment by timgl** [comment]
@mariusandra The annoying thing is this is kind of hard to test so I'd rather just do the simplest thing possible now to solve the reloading issue, we can then improve.

**Comment by timgl** [comment]
@mariusandra happy with this?

**Review by mariusandra — APPROVED** [review]
Hmm... no, not really happy.. :).

With this change, whoever is using posthog cloud will get an awkward "network error" message after they navigate from one route to another, whenever we push something to master. Now the page silently reloads instead and the page transition is just a second or two slower.

However, I won't stand in the way of trying new things. So feel free to merge! If this gets annoying we can revert.

**Comment by mariusandra** [comment]
I had `app.posthog.com` suddenly reload yesterday when going from one page to another. It was very subtle and had I not known how to look, I'd have missed this. So the reloading logic is working as intended... at least that time for me. Probably also many other times.

**Pull request closed without merging**
