### PR TITLE
fix: forgive missing methods

### PR DESCRIPTION
**Pull request by raquelmsmith**
## Problem

Sentry error: https://posthog.sentry.io/issues/3950061851/?project=1899813&query=is:unresolved+id:7068a2d6a79e4b1dbde4ae1888274606&statsPeriod=14d

And customer report: https://posthoghelp.zendesk.com/agent/tickets/1862 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/4882)

## Changes

Makes it forgiving of missing methods.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

I'm not fully certain how to test this locally...

### CODE REVIEW

**Comment by unchained-42** [comment]
Hello, 
Thanks for fixing this issue, but now i have this error due to your fix i guess : 
`Error: connect ECONNREFUSED 172.20.88.150:6543
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
    at TCPConnectWrap.callackTrampoline (node:internal/async_hooks:130:17)
    `

Screen Shot 2023-02-28 at 11 41 20

**Comment by unchained-42** [comment]
And i have alway this error in debug : 
`Plugin unloaded (instance ID 0186978e-ce8b-0000-e00e-68c79003cf23).`
Screen Shot 2023-02-28 at 11 42 42

**Comment by unchained-42** [comment]
@raquelmsmith

**Comment by raquelmsmith** [comment]
@kevin-btc which plugin are you seeing this for?

**Pull request merged**
