### PR TITLE
fix: hide  helpbutton popover when onClickOutside is triggered

### PR DESCRIPTION
**Pull request by thinklinux**
## Problem

There are 3 popover components in the topbar:
- notifications
- help
- user menu

Notifications and the user menu act the same when user clicks outside the popover or the esc key is pressed - we hide the popover. 

The help popover does not hide when clicked outside or the esc key is pressed.

## Changes

The behaviour of the HelpButton component should be the same as the other two. HelpButton uses LemonMenu which is build on top of the LemonDropdown -> Popover :) So we can expose the `onClickOutside` prop in the LemonMenu in order to have this kind of behaviour implemented in the HelpButton. Also the LemonMenu can benefit from it too.

## How did you test this code?

This is before the change:

https://github.com/PostHog/posthog/assets/326949/6554198d-fa59-429f-bd2e-a0d620a27a72

And this is after the change:

https://github.com/PostHog/posthog/assets/326949/2be96693-70c6-419b-81d4-5e32d6d7762c

### CODE REVIEW

**Comment by thinklinux** [comment]
@Twixes fixed my PR comment. Some of the stuff were lost because of markdown and I didn't see it before :)

**Review by Twixes — APPROVED** [review]
Hey @thinklinux! Thanks for this, looks good. You'll need to merge the PR with current PostHog/posthog master to get the checks to pass though – we had some issues with PR checks on external contributions, and that is now solved

**Comment by thinklinux** [comment]
Hey @Twixes thanks for the review! Happy I helped! Merged everything. Let's see :)

**Review by Twixes — APPROVED** [review]
Hmm, there's a build issue due to our service provider, but everything's working well!

**Pull request merged**
