### PR TITLE
chore(correlation): switch to exclude for property correlation

### PR DESCRIPTION
**Pull request by hazzadous**
This PR does quite a lot. It should have been broken into more.

 1. migrate all custom hooks to a new kea logic
 2. fix up storybooks for funnel correlation development
 3. change property selection to property exclusion, and add a little button to property correlation table rows so you don't have to search through the list of properties in the dropdown

[Storybook](https://61260360a8e859003a7c138b-yeqwevqzvj.chromatic.com/?path=/story/posthog-scenes-insights-funnel--with-correlation-and-skew)

### CODE REVIEW

**Comment by mariusandra** [comment]
Another thing that can be useful here is [`<BindLogic>`](https://keajs.org/docs/guide/react#bindlogic). I suggest using that in the component's main component, and then just use `useValues` and `useActions` instead of all these custom hooks in all nested components.

**Comment by hazzadous** [comment]
- [x] migrated popover logic to `propertySelectLogic`
 - [x] migrated property selection logic to `propertySelectLogic`
 - [x] migrating property search to `propertySelectLogic`
 - [x] use `kea-localstorage` for `excludedProperties`

**Review by mariusandra — COMMENTED** [review]
had another look through

**Comment by hazzadous** [comment]
@neilkakkar this is good to go 🤞 

It's probably worth getting in the backend exclusions though, then I'll rebase.

**Comment by hazzadous** [comment]
Just merging master to see if that fixes the e2e

**Comment by hazzadous** [comment]
Just checking the e2e failure

**Review by neilkakkar — APPROVED** [review]

**Review by mariusandra — CHANGES_REQUESTED** [review]
The logic looks pretty solid! Added one bit of info that might help below. 
Then finally the logic could use tests as well and this is good to go.

**Comment by hazzadous** [comment]
@mariusandra I've added [tests for the funnelLogic](https://github.com/PostHog/posthog/pull/6597/files#diff-355f2e4b3e935b8a44fef60fa2314e4e2e92e825f96cc99dc8f74c6252031fd6) and [tests for the propertySelectLogic](https://github.com/PostHog/posthog/pull/6597/files#diff-ffba37384fdb2c79decae4073568a29de1510e393ffa1b9b68f41ecf647c84fb), let me know what you think.

**Review by mariusandra — APPROVED** [review]
I'd still change the selector for `properties` to get the data via a `(_, props) => props.properties` selector, the rest is looking good! :+1:

**Comment by hazzadous** [comment]
> I'd still change the selector for `properties` to get the data via a `(_, props) => props.properties` selector, the rest is looking good! 👍

@mariusandra Yes I forgot to do this 🤦  and now I have conflicts! I'll resolve and get this in, then follow up with another to avoid any more conflicts.

**Comment by hazzadous** [comment]
e2e funnels.js failure, am debugging. Rerunning tests as well.

**Comment by hazzadous** [comment]
Tests pass on retry.

I tried to reproduce locally. It seems that you need to have PRIMARY_DB=postgres to run cypress locally. It ran successfully, although this test appears to be failing quite a bit recently. I'm going to leave it for now as have other priorities, but will try to get back to debugging at some point.

**Pull request merged**
