### PR TITLE
chore(refactor): pythonic schema

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

A couple of options for datamodel codegen would make our schema more "pythonic". 

## Changes

This PR:
- ~Snake cases field names~ -> This needs a frontend<->backend conversion function, thus should be addressed in a separate PR.
- Uppercases enum member
- Wraps long string literals
- ~Adds better validation for tuples i.e.~ -> Turns out we actually have results that don't adhere to the specified format. Should be addressed in a separate PR as well.
    ```diff
    -    bins: list[list[int]]
    +    bins: list[list[Any]] = Field(..., max_length=2, min_length=2)
    ```

Obviously backend needs to be adapted to follow the new schema, but I though I'd put this out already for a :+1: / 👎 : from you all.

## How did you test this code?

_Not yet_

### CODE REVIEW

**Review by webjunkie — COMMENTED** [review]
> Snake cases field names

Lots of changes, but would be nice 👏🏻

**Comment by webjunkie** [comment]
> This needs a frontend<->backend conversion function, thus should be addressed in a separate PR.

Does it? I whishfully thought it would work via Pydantic alias, meaning Pydantic converts it for us back and forth.

**Review by webjunkie — APPROVED** [review]
Lots of changes 😵‍💫 
Let's get it in before it conflicts with something.

**Comment by thmsobrmlr** [comment]
> > This needs a frontend<->backend conversion function, thus should be addressed in a separate PR.
> 
> Does it? I whishfully thought it would work via Pydantic alias, meaning Pydantic converts it for us back and forth.

Will have a look again, but _something_ definitely broke. Maybe it was the backend -> frontend route.

**Comment by webjunkie** [comment]
> Will have a look again, but _something_ definitely broke. Maybe it was the backend -> frontend route.

Looks like it requires setting `by_alias=True` when dumping everywhere.

**Pull request merged**
