### PR TITLE
chore: only report failing tests in plugin server tests

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

When I look at output from failing plugin server tests there is a colossal amount of logging. And signal to noise ratio is way off

## Changes

Turns off reporting for any passing tests and only reports logs for failing tests

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

running the tests and seeing less output

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]
Probably fine, is there a cli flag to see all output if needed?

**Comment by mariusandra** [comment]
I was thinking about adding this [jest-github-actions-reporter](https://github.com/cschleiden/jest-github-actions-reporter) reporter by (eventually) [upgrading to jest 28](https://jestjs.io/blog/2022/04/25/jest-28#github-actions-reporter). 

Would this log silencer also silence it? 🤔 

Edit: LGTM otherwise

**Comment by pauldambra** [comment]
> I was thinking about adding this [jest-github-actions-reporter](https://github.com/cschleiden/jest-github-actions-reporter) reporter by (eventually) [upgrading to jest 28](https://jestjs.io/blog/2022/04/25/jest-28#github-actions-reporter).

> Would this log silencer also silence it? 🤔

This doesn't silence failed tests and the reporter you link to only reports on failing tests. So *in theory* they wouldn't clash

That said it's easy to remove this if it gets in the way :)

**Comment by macobo** [comment]
How married are we to this? I'm locally disabling this as running tests got more painful now as I have no clue what is failing and why.

**Pull request merged**
