### PR TITLE
feat(hogql): always prepend table name in clickhouse sql

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

I saw one error where a materialised column was inaccessible outside a select subquery, since we didn't prepend the table name.

## Changes

Adds a common sense security measure: in printed ClickHouse SQL, we now prepend each accessed field with the name of the table it's on.

## How did you test this code?

Updated the tests. Hoping CI will catch anything else.

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
Looks good,

One thing I'm not sure about: How does this work with aliasing?

For example, if I do `JSONExtractRaw(events.properties, blah) as properties` and use properties in a line below, prepending `events` to the name will bork it.

**Comment by mariusandra** [comment]
Thanks for the review!

Depending on how you use `properties`.

The following is not valid ClickHouse SQL:

```sql
select coalesce('not properties', null) as properties, coalesce(properties, events.properties) as `what is this` from events
```

For some reason columns in a row can't refer to previous ones. You need to use [WITH](https://github.com/PostHog/posthog/pull/14495) for such magic.

If you alias a column as `properties` inside a subquery and access it from within a context where you can access it (it's basically in a join), then we'll either add or not add the alias of the subquery, depending on whether it has one or not.

**Comment by neilkakkar** [comment]
That doesn't sound 100% right. For example, this is valid:

```
SELECT JSONExtractRaw(events.properties, '$os') as properties, upper(properties) as props, lower(events.properties) from events LIMIT 1
```

and the `upper(properties)` is not referring to events.properties, but prepending events here will fail?

**Comment by neilkakkar** [comment]
(also curious why your example fails, not sure why 🤔 )

**Comment by neilkakkar** [comment]
I think it's a coalesce weirdness, if I reverse the ordering in the second coalesce, it passes. I'm guessing something to do with the restriction on arguments:

image

**Comment by mariusandra** [comment]
Odd stuff. This query however works fine in both hogql and clickhouse:

image

🤷

**Comment by neilkakkar** [comment]
Looks like we're good then 🤷  😅

**Pull request merged**
