### PR TITLE
Embeddable dashboards

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Allow users to embed customers in iframes by giving them a snippet and removing the dashboard name etc.

image

image

## How did you test this code?

Share dashboard, copy the iframe, put into another html file.

You can also add `?embed` behind any shared dashboard.

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
Love the idea, but I propose dropping "Dashboard made with \<PostHog logo\>" from the embedded mode. It's redundant considering the "Made with PostHog" footer and gets in the way of content (also the positioning of things), making me want to embed this into my website less.
Screen Shot 2021-12-02 at 12 18 55

**Comment by timgl** [comment]
Hm I do think it's a good opportunity to get our name out and because of the scrollbar most people won't actually see the end of the page.

@corywatilo any opinions on a way of doing this in a more subtle way?

**Comment by Twixes** [comment]
I pushed some general improvements to shared dashboards here, which overall make them look better (it was all kind of dirty… like descriptions rendered with HTML entity references) and also adjust the positioning of the logo in embedded mode. Here's a comparison:

### Before – regular
old

### After – regular
new-regular

### After – embedded

new-embedded

WDYT @timgl?

**Comment by timgl** [comment]
Looks amazing, thanks!

**Pull request merged**
