### PR TITLE
fix: exclusion steps cannot be selected

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

In [this community slack message](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1652252796270319) the user reports that when they try to add an exclusion filter to a funnel they get an error.

Confirmed this happens for all users

The error is because on adding the exclusion filter, and before being offered a pop-up to choose the event or action, the UI sends an empty exclusion filter to the API

Fixing the API to ignore those empty values shows that the exclusion filter UI does not allow you to make a selection. So exclusion filters cannot be added.

exclusion filters

## Changes

in order to get the feature functionally working again

* ignore empty exclusion filters in the API
* allows the default value for the exclusion filter to work 
* allows you to set an exclusion filter even if the from and to step range matches the length of the actions/events in the filter

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

running it locally

### CODE REVIEW

**Comment by neilkakkar** [comment]
perhaps makes sense to update the frontend to not send that API request? Since that's atleast one extra query making it to Clickhouse which is worthless.

And on the backend, filtering out empty entities, but not incomplete ones as the current solution does, as that hides better error messages / covers a larger error area than we want

**Comment by neilkakkar** [comment]
Also, fixes https://github.com/PostHog/posthog/issues/9537

**Review by benjackwhite — APPROVED** [review]
Generally looks good, although I'm not too familiar with the underlying exclusion logic.

**Comment by pauldambra** [comment]
> I'm not too familiar with the underlying exclusion logic.

@benjackwhite that makes two of us 🤣 

the joy of support week fixes is a kind of freedom

**Pull request merged**
