### PR TITLE
Pass in funnel_step_breakdown param for funnels breakdown persons modal

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

We have to pass in `funnel_step_breakdown` in order to get the breakdown persons back properly

https://user-images.githubusercontent.com/25164963/126684623-9c0a350c-6952-463c-a092-d74c587f3b5e.mov

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by mariusandra** [comment]
- Can we also show the breakdown title somewhere in the persons modal?
- Would it be easy to add the option to click on the dropped off part?

**Comment by mariusandra** [comment]
If this will turn into a final modal improvements PR, then two more things:

1. "Persons who completed step" shows even if I'm looking at a dropoff
2. The "Persons who completed step #3" turns into "step #0" if I load more people

**Comment by clarkus** [comment]
@liyiy @mariusandra should we remove the CSV export button from the modal for this release? @EDsCODE mentioned on slack that the backend only supports this for trends right now.

**Comment by liyiy** [comment]
> @liyiy @mariusandra should we remove the CSV export button from the modal for this release? @EDsCODE mentioned on slack that the backend only supports this for trends right now.

approved and merged here https://github.com/PostHog/posthog/pull/5297

**Comment by liyiy** [comment]
- [x] Can we also show the breakdown title somewhere in the persons modal?
- [x] Would it be easy to add the option to click on the dropped off part?
- [x] "Persons who completed step" shows even if I'm looking at a dropoff
- [x] The "Persons who completed step /Actions (Log / Graph) #3" turns into "step #0" if I load more people

All points tackled! 

only thing is that long breakdown names get kind of ugly in the title, should I just '...' it if it's too long? @clarkus  -> 

Screen Shot 2021-07-22 at 4 39 20 PM 

VS 

Screen Shot 2021-07-22 at 4 08 49 PM

**Review by mariusandra — APPROVED** [review]
Looks good to me. Check with @clarkus for how to best show this and feel free to merge after. I'd actually put the breakdown itself onto a second line with a slightly different style... and perhaps end that with "..."

**Comment by clarkus** [comment]
I think truncating to a single line for now will be fine. I'd like to use that as the solution for a while before we try to improve it. We could separate out the values, but then that could lead to lots of "awkward whitespace™" which isn't a problem, but it might make the product feel less polished. 

One note on truncation. It's most valuable when it replaces repeated, non-meaningful values. Anything that doesn't aid in uniquely identifying or distinguishing an option from other options could be replaced by truncation `...`. That said, that's hard to do and probably doesn't add enough value to justify consideration for this release.

**Comment by liyiy** [comment]
Screen Shot 2021-07-22 at 6 24 59 PM

**Pull request merged**
