### PR TITLE
fix(shared insights): shared pie chart layout

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

Spotted that the piechart was showing incorrectly but only when an insight was shared or exported

Screenshot 2022-12-05 at 10 06 50

(I assume this was broken in #13018 )

## Changes

* corrects that layout 
* fly-by only add right padding to the pie when showing the legend

Screenshot 2022-12-05 at 09 58 04

## How did you test this code?

* sharing a pie locally and seeing it display correctly
* switching it to each of the other insight types and seeing it display correctly

### CODE REVIEW

**Comment by pauldambra** [comment]
Slightly ridiculous number of combos 🤣 

Ugh, ok, this has changed behaviour around height of container. 

cc @thmsobrmlr a great example of where we could be using visual regression testing to protect us

| before | after |
|--|--|
| Screenshot 2022-12-05 at 10 29 40 | Screenshot 2022-12-05 at 10 19 38 |
| Screenshot 2022-12-05 at 10 28 25  | Screenshot 2022-12-05 at 10 19 53 |
| Screenshot 2022-12-05 at 10 28 42 | Screenshot 2022-12-05 at 10 20 12 |
| Screenshot 2022-12-05 at 10 29 13 | Screenshot 2022-12-05 at 10 20 27 |
| Screenshot 2022-12-05 at 10 33 01 | Screenshot 2022-12-05 at 10 20 42 |
| Screenshot 2022-12-05 at 10 29 25 | Screenshot 2022-12-05 at 10 21 21 |
| Screenshot 2022-12-05 at 10 29 53 | Screenshot 2022-12-05 at 10 22 20 |
| Screenshot 2022-12-05 at 10 30 11 | Screenshot 2022-12-05 at 10 22 34 |
| Screenshot 2022-12-05 at 10 30 28 | Screenshot 2022-12-05 at 10 22 51 |
| Screenshot 2022-12-05 at 10 27 51 | Screenshot 2022-12-05 at 10 23 09 |
| Screenshot 2022-12-05 at 10 27 32 | Screenshot 2022-12-05 at 10 23 22 |
| Screenshot 2022-12-05 at 10 27 12 | Screenshot 2022-12-05 at 10 23 35 |
| Screenshot 2022-12-05 at 10 26 52 | Screenshot 2022-12-05 at 10 23 52 |
| Screenshot 2022-12-05 at 10 26 40 | Screenshot 2022-12-05 at 10 24 05|

**Comment by pauldambra** [comment]
exporting pie chart now

export-pageview-count-by-events-country-code (1)

**Comment by pauldambra** [comment]
exporting a piechart with legend showing in normal display

export-pageview-count-by-events-country-code (2)

**Comment by pauldambra** [comment]
fixed this only in the pie chart component now @benjackwhite

**Review by benjackwhite — APPROVED** [review]
If you're happy with testing, I'm happy with the code 👍

**Comment by mariusandra** [comment]
I'm happy to merge this

**Pull request merged**
