### PR TITLE
Show "Unnamed insight" instead of "Insight #{id}"

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

A **proposal** to address https://github.com/PostHog/posthog/pull/6924#pullrequestreview-800080711 by using an idea from https://github.com/PostHog/posthog/pull/6924#issuecomment-963139612.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]

**Review by clarkus — APPROVED** [review]
The goal of the generated ID was to give the insight a uniquely identifying name by default and to make it so the user didn't have to provide a value for this before saving. As long as we can ensure insights are unique and findable, I'm ok with this change.

**Review by mariusandra — CHANGES_REQUESTED** [review]
I do see @clarkus 's concerns with this fix. Having clicked "save" twice, I now have these two insights:

image

There was no popup to ask me to fill in a name, and it's also not a real name, but just a placeholder for an empty string, making them not searchable:

image

At the very least, let's also save the string in the DB? Ideally though, a custom unique string could make things a lot nicer. [Something like this](https://github.com/poush/random-animal) perhaps?

**Comment by Twixes** [comment]
Well, the searchability problem is nothing new, because these ID-based titles were fake just like "Unnamed insights". You couldn't search for them.
I agree with both of you, so here's the new iteration:
Now every new insight gets a random friendly animal name, one that's actually saved so it's as real as a user-provided name. While truly unnamed insight are now italic _Unnamed insight_ to indicate that they aren't searchable.
Zrzut ekranu 2021-11-9 o 13 10 30

**Review by mariusandra — APPROVED** [review]
Looks good, just the title here also needs a placeholder when there's nothing persisted:

image

**Review by clarkus — APPROVED** [review]

**Review by paolodamico — COMMENTED** [review]
Posthumous review.
1. When first seeing this, I think it's confusing to know what you're looking at, particularly as this is the title of the insight. How about calling this "Funnel - Cheeky porcupine"?
2. It's quite unintuitive/annoying that you can't change the default name easily. After I've clicked on create insight, I would expect to be able to easily click on the title to change it, or get asked for a meaningful name when saving. If I want to save it with a meaningful name, I have to go out of my way to do this. CC @clarkus  

Sorry for not putting up a PR, I'm super swamped with reviews, lmk if you'd rather I put up a PR and will ship it tomorrow.

**Comment by clarkus** [comment]
>  If I want to save it with a meaningful name, I have to go out of my way to do this.

You should be able to edit it inline in both the edit mode and the read only view if you have edit access. The whole intent here is to provide a meaningful default so that if the user doesn't want to plug in a name, they don't have to. It also focuses the creation flow on the required fields. There isn't really anything to save until you have a meaningful query plugged in. This is mostly because we're moving from a model where saving was basically optional to one where saving is necessary to use insights. 

I'm happy to make adjustments, but that was the primary intent. Maybe we should go back to prompting for this info on save instead? Happy to continue working on this in another PR, too. I have a few other ideas that might be a better compromise. 👍

**Comment by mariusandra** [comment]
I think adding "Funnel" to the name could clarify things... but the problem is the name will remain static even if you change the tab, so "Dorky Funnel Rabbit" will remain that even if it's now a retention table. That's probably more confusing.

What about a popup asking for a name when you click "save"? Similar to adding to a dashboard?

**Comment by paolodamico** [comment]
1. Indeed, there's that annoying case. I think ideally we would change the name dynamically when you change a tab if it's a "default" name. I do think that helps clarify a lot and further makes it easy to find insights later.

2. Please disregard my comment, for some reason the edit button was not appearing for me yesterday, that's why I thought you couldn't change it easily. I do think a name confirmation when you save could be helpful, we could even provide a little bit more value (guiding users to setting up a relevant name), but probably something we can improve later.

**Pull request merged**
