### PR TITLE
Improve types vol. 10

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Submitting yet another batch of Kea and TypeGen upgrades over the weekend.
- TS errors are down to 25 after this. 90% are actually legit, and most of those come from bad toolbar types.
- Getting close to 0 🤩 

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

**Comment by mariusandra** [comment]
Something's still broken. Reverting to draft and will look when I get the time.

**Comment by paolodamico** [comment]
Sounds good! Tag us again for a review when it's ready

**Comment by mariusandra** [comment]
@paolodamico ready for a look. Should be rather quick and ultimately inconsequential changes: mostly just type improvements.

**Review by paolodamico — APPROVED** [review]
lgtm! pretty straightforward

**Pull request merged**
