### PR TITLE
feat(funnels): Connect new funnel bars to persons modal

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Now in the new `lemon-funnel-viz` variant of Funnels, you can actually click on the funnel bars and view the persons associated with the step. Works both for completion (filled part) and dropoff (striped backdrop).
Also fixes sizing of top-to-bottom funnel view. This gets us much closer to releasing the new funnels.

### CODE REVIEW

**Review by mariusandra — CHANGES_REQUESTED** [review]
Had a look, saw things.
- The title in the modal is wrong:

- Seems like the modals for the total counts just open the modal for "breakdown item 0"

**Comment by neilkakkar** [comment]
Side flyby: human friendly numbers here?

image

**Comment by mariusandra** [comment]
"two seven two two"

**Comment by Twixes** [comment]
Thanks both! I corrected the persons modal for bars, and added number formatting.

It seems behavior of baseline (i.e. total counts) persons modal is wrong on `master` too though – it shows persons not for the actual baseline, but for the first breakdown series returned by the API. I'm quite confused how this works, because the 1.5k-line `funnelLogic` does a ton of massaging on the results returned from the API, which makes it hard to grasp what's going on. IMO it ought to be hugely simplified at some point. But anyway, I will fix this separately.

Tagging @alexkim205 as you might have a bit more context on `funnelLogic` having worked on it in the past.

**Comment by pauldambra** [comment]
>  I'm quite confused how this works,

+1 - I was too!

https://github.com/PostHog/posthog/issues/7385

**Comment by alexkim205** [comment]
That's really strange how when you click baseline, it will automatically query the first breakdown item. That's definitely not intentional and I suspect it might've been introduced here - https://github.com/PostHog/posthog/pull/7654/files#diff-92e32501a6b77e6bdff549cb4f721a309c1b5fd3df14615dc6969315b66041dcR762-R764

Also taking a look now

**Comment by alexkim205** [comment]
Ooh this bug might be deeper than I initially thought it was. It looks like we somewhat recently changed how we make person modal requests. The backend is returning `converted_people_url` and `dropped_people_url` as parameters in each step, which the frontend directly calls via `personModalLogic.actions.loadPeopleFromUrl`. Since the backend has no concept of the "Baseline" step, this same url persists for the pseudo baseline step that's prepended to all steps on the frontend.

---

Update: this should fix it -> https://github.com/PostHog/posthog/pull/9557

**Review by mariusandra — APPROVED** [review]

**Comment by mariusandra** [comment]
👍 . Not sure what order anything should be merged in though, so will avoid clicking the green squishy button myself.

**Pull request merged**
