### PR TITLE
feat: allow verified property definitions

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

Today it annoyed me I could verify an event but not a property

## Changes

Adds property definition verification, which was mostly copy-pasta from existing code

## How did you test this code?

👀 locally and some developer tests

### CODE REVIEW

**Comment by pauldambra** [comment]
Screenshot 2023-06-07 at 12 15 38

cool the activity log works for free

**Comment by neilkakkar** [comment]
should we sort & have verified properties on top in filters? Otherwise it's _still_ a bit hard to find the right one based on the icon change 😅

**Review by benjackwhite — APPROVED** [review]
I'm not sure about this tbh... It feels like the wrong solution to the problem.

Why do we have verified events - to say "When searching for events I want ones that are definitely correct / intentional to be shown".

Why do we want verified properties - to say "When filtering an event, I want to see the properties that actually exist for the event in question".

Verifying properties to me doesn't sound like a useful thing. What if I have a property for one event that should be verified but not for other events? 

This reminds me of a pitch I had when I joined for data schemas, where you could define your event schema upfront, and then you could see if events matched the desired schema or not.

I see nothing _wrong_ with this PR but I do wonder if this is not really adding much real usefullness so I'll leave it to you to decide :D

**Comment by pauldambra** [comment]
> I do wonder if this is not really adding much real usefullness

We had `email` and `$email` I had to tag the correct property in order to verify it by proxy. Things could, for sure, be better. But at least for now the same mechanism can be used across both types of definition

**Comment by pauldambra** [comment]
> should we sort & have verified properties on top in filters?

@neilkakkar we say we do that for event definitions, but I can't see the code that does it... do you know where?

**Comment by pauldambra** [comment]
I don't think we do prefer _verified_ event definitions... I think we just say we do 🙈

**Comment by pauldambra** [comment]
Now definitions are sorted so that verified are promoted

Screenshot 2023-06-08 at 10 25 39

**Pull request merged**
