### PR TITLE
Add commas to large numbers so that they are readable

### LINKED ISSUE #4044: Add commas to big numbers on dashboards
## Is your feature request related to a problem?

Numbers like this are hard to read:

Screenshot 2021-04-20 at 16 26 57

## Describe the solution you'd like

Commas added ie 1000000 -> 1,000,000 to the axis of the graph.

## Describe alternatives you've considered

Glasses

### PR DESCRIPTION
**Pull request by buwilliams**
## Changes

- Added `maybeAddCommasToInteger` to utils
- Updated charts to use `maybeAddCommasToInteger`
- Updated tables to use `maybeAddCommasToInteger`
- Updated TrendsLegend with `maybeAddCommasToInteger`

Closes #4044 

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by buwilliams** [comment]
There's a table under Trends graph but haven't been able to find that code yet. Know where it is?

**Comment by samwinslow** [comment]
Hi Buddy. Added some TS overloads to this function to assert that when the input type is a number, the returned value is a string. Were you able to locate the table you needed? Pretty sure you're referring to `TrendLegend`, and it looks like you did call this function there.

P.S. do you have [React DevTools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) installed? The Components inspector is excellent for figuring out confusing virtual DOM hierarchies.

**Review by samwinslow — COMMENTED** [review]
Reverted the typing stuff because `Intl.NumberFormat.prototype.format(input: number | bigint)` actually _does_ accept number-like strings, contrary to  the official spec... didn't expect that.

**Comment by buwilliams** [comment]
I'm going to merge this branch and work on tests in a separate PR.

**Pull request merged**
