### PR TITLE
feat(insights): Add option for Last 3 days in insights

### PR DESCRIPTION
**Pull request by timgl**
## Problem

Some people would like more data than 24 hours, but less than 7 days

## Changes

- Add 'Last 3 days' option

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Code looks good obviously. Product-wise, fine for me, yet I remember we recently cleaned up this list and removed some options. I don't know if there's anything to consider here @paolodamico @clarkus @marcushyett-ph

**Comment by marcushyett-ph** [comment]
Product-wise the customer who highlighted it had a reasonable use-case (looking at a specific day in the past and data around it for context + large data volumes) so it makes sense, and they didn't just want every different variation of days.

I think we should be a little careful about making this list unmanageable, but it seems okay right now. We should think about past N-days as a potential longer term solution to cover these types of scenario.

**Comment by clarkus** [comment]
We support custom date ranges. Couldn't the user plug in an exact range in days via that control?

**Comment by timgl** [comment]
@clarkus This is rolling, so if you refresh the insight it will always be the last three days rather than a fixed set of dates

**Comment by clarkus** [comment]
https://github.com/PostHog/posthog/issues/9027 and https://github.com/PostHog/posthog/issues/8640 - I think this is the better solution. The trade off is that now every user has an additional option to navigate past. It's not a huge deal, but it does bias all usage towards a specific edge case.

**Pull request merged**
