### PR TITLE
Add ability to add person props on the UI

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

This is something I've been needing so just decided to go ahead and build it.

Fixed a few responsiveness overflow issues and added the ability to add new person props via the UI:

Screenshot 2021-02-18 at 20 29 27

Leverages the existing `editProperty` for updates. 

Also converts string to boolean on edits if appropriate.

#### Before

Screenshot 2021-02-18 at 20 33 17

#### After 

Screenshot 2021-02-18 at 20 29 08

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
The trash button hasn't been pushed yet (should we have it?) but here's what this looks like with it:


https://user-images.githubusercontent.com/38760734/108493516-5320f480-729e-11eb-9519-395c276e7e5a.mov

**Comment by yakkomajuri** [comment]
@paolodamico did you get a chance to give this a quick look?

**Comment by paolodamico** [comment]
Thanks for the ping, will definitely take a look today. Also FYI it looks like we're indeed keeping the personsV2 feature, will post more details on that later today.

**Comment by yakkomajuri** [comment]
Yeah I've been essentially assuming that purely from a code quality perspective. Even if the design was worse (it isn't), PersonsV2 is much more maintainable code.

**Review by paolodamico — COMMENTED** [review]
Great feature @yakkomajuri! Proposed a few changes hopefully to make the experience better. Mainly I moved from inline to modal-based form to be able to make things a bit more clear (more [context](https://posthog.slack.com/archives/C015UVBEHCN/p1614190665012800))

Context on other minor changes:
- Renamed `AddNewPropertyField` to `NewPropertyComponent` for clarity.
- Moved button to the top of the properties table to increase discoverability because some users may have way too many properties. Also adjusted the visual of the button to be more inline with our design language (unsure if doing this or the block button with the dotted border would be best here).
- Moved new property state from Kea to vanilla React state because when you navigate away as the Kea logic is still mounted, the state is maintained.
- Related to the above, adjusted some typescript definitions.

Some suggestions for additional improvements:
- When disabling custom sorting on person properties after adding a property, the existing properties get scrambled for the new property to be added to the top. The right behavior would be for properties to stay in the same ordering and only the new property to be added at the top.
- For the properties keys, suggest keys that are present in other users but not in this one (@corywatilo).
- Warn if the user is trying to add a property with the same name.

Please review and feel free to change however you think best!

**Comment by yakkomajuri** [comment]
Thanks for taking a look!

2 and 3 make sense to me.

Need to look into 1 after the changes. At least when I had it at the bottom adding a new property did keep everything in order and just add the prop to the end. Until of course the user refreshed

**Comment by paolodamico** [comment]
Sounds good! Keep me posted @yakkomajuri so I can update the subsequent PR.

Also, forgot to include the screenshots of the new flow I proposed here.

**Comment by paolodamico** [comment]
Merging with verbal approval from @yakkomajuri, as a follow-up PR we'll add auto-filling for existing props & values.

**Pull request merged**
