### PR TITLE
Add support for SOCIAL_AUTH_REDIRECT_IS_HTTPS

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This simple setting should allow us to force HTTPS on social auth redirects when needed (as in some routing cases the redirects may be mistakenly HTTPS). [Social auth docs.](https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#processing-redirects-and-urlopen)

### CODE REVIEW

**Review by paolodamico — APPROVED** [review]

**Comment by paolodamico** [comment]
lgtm! though, setting `IS_BEHIND_PROXY` properly seemed to work too, as we do set the header in there https://github.com/PostHog/posthog/blob/316e2a6f4dba8030a2c71098528a28a362f96582/posthog/settings.py#L121, but if you want to add it to be even more deliberate, perfect. Remember to update the environment variables doc too pls!

**Comment by Twixes** [comment]
Ah yeah, this basically is for proxy situations too, so if `IS_BEHIND_PROXY` does the job, we don't need this setting specifically for social auth.

**Comment by Twixes** [comment]
So `SOCIAL_AUTH_REDIRECT_IS_HTTPS` will be true by default, except in `DEBUG` mode.

**Comment by fuziontech** [comment]
Perfect

:shipit:

**Review by fuziontech — APPROVED** [review]
This is perfect

**Pull request merged**
