### PR TITLE
Revert "Insight history"

### PR DESCRIPTION
**Pull request by EDsCODE**
Reverts PostHog/posthog#1303

### CODE REVIEW

**Comment by timgl** [comment]
huh-oh. What happened? Reverting migrations is a little tricky on app

**Comment by EDsCODE** [comment]
it hasn't been deployed yet has it? it's just that if we release this, converting funnels will be more cumbersome because the additional need to change all the dashboard item(insight) filter objects along with the funnel models

**Comment by timgl** [comment]
Yep fair point

**Review by timgl — APPROVED** [review]

**Comment by mariusandra** [comment]
Oohh, close call then. I just thought of deploying the app a few hours ago to get the merged person-joining script in (#1351), but called it off as I found a bug with it (#1362)

**Pull request merged**
