### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by timgl**
## Changes

-
-
-

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey, doing a drive-by review.

I see that you added a file "frontend/src/layout/_assets/white-logo.svg", but that's not used by anything. I guess that should be removed?

Also, ideally I would like to completely remove the "public" folder and load all the assets via webpack loaders (so just `import logo from "logo.svg"`). It's simplest if all files go through one system instead of having two parallel ways to distribute files.

However, when piped through webpack, each asset/logo will contain a hash in its filename and we'll lose the opportunity to just specify `/static/favicon-192x192.png` in `index.html`. Perhaps there's a quick way around that? I'm not sure...

**Comment by timgl** [comment]
removed the white-logo!

I think you're more of a webpack expert than I am ha! Agree it'd be better but it's nice to have a direct url for these images. Maybe let's just get this in now? Up to you

**Comment by mariusandra** [comment]
I think we should 1) remove the `frontend/public` folder, 2) keep all svgs and other assets inside `frontend/src` folder and 3) use something like [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin) to generate all the different favicons for us.

I can pick this up if you wish.

**Comment by mariusandra** [comment]
Merged this now. This favicon part can be picked up later. It's more nice to have right now.

**Pull request merged**
