### PR TITLE
Monorepo with updated history

### LINKED ISSUE #6095: Monorepo with plugin-server?
A few times we've seen changes in `posthog` break `plugin-server`, as well as some occasions of the opposite happening. Yesterday was the worst of those.

The problem here is we have a circular dependency - `plugin-server` depends on `posthog` and vice-versa. So when we make e.g. a breaking change to a model, we will be out of sync for some time no matter what, even if we're on top of things.

That's because we can't update a query in the plugin server before merging the migration in `posthog`, yet merging the migration breaks the query.

A potential solution here is a monorepo. I'm opening this issue as this move would probably fall to me, but the suggestion came from both @fuziontech and @mariusandra. I believe this would also be helpful in us moving towards a better testing approach that @hazzadous is pushing for.

Certainly there are downsides to the monorepo. The test suite will get massive, getting work merged will take longer, and we won't have as granular control over versioning, among other things.

Nevertheless, I wanted to open this issue to see if anyone is a _strong no_ and why, because otherwise we should give this a try.

### PR DESCRIPTION
**Pull request by fuziontech**
This is a doozy

- [x] History is maintained
- [x] Updated links to point to plugin-server repo PRs
- [x] Prefix all plugin server commits with `[plugin-server]`

This _will_ require a force push to master ☢️ 
This PR is mainly a pointer to the `monorepo` branch which is the state that master will become. This PR _will ~not~ be merged and not squashed_. We will have to change the settings for the repo to enable that, but that's not a big deal.

~~Check out what the future (and by future I mean history) could look like:
https://github.com/PostHog/posthog/tree/monorepo~~
Edit: github doesn't know how to properly show the history here.

To see what this will look like do this locally:
```bash
git checkout monorepo
git pull
git reset --hard origin/monorepo
```

To undo this you'll need to:
```
git checkout master
git reset --hard origin/master
```

### In plugin-server repo
```bash
# Make sure to have a clean head on master
git checkout master
git add .
git reset --hard HEAD
git pull
# Let's begin
git checkout -b monorepo
FIRST_COMMIT_HASH=$(git rev-list HEAD | tail -n 1)
# Prefix all commits with `[plugin-server]`
git filter-branch -f --msg-filter " sed '1 s/^/[plugin-server] /'" ${FIRST_COMMIT_HASH}..HEAD
# Rewrite PRs to link to plugin-server PRs
git filter-branch -f --msg-filter " sed '1 s/\#\([0-9]*\)/https:\/\/github.com\/PostHog\/plugin-server\/pull\/\1/g'" ${FIRST_COMMIT_HASH}..HEAD
# rebase and rename first commit - check history
git rebase -i -r --root
```

### In Posthog repo
```bash
# Make sure to have a clean head on master
git checkout master
git add .
git reset --hard HEAD
git pull
# Setup our workspace (this will be done directly to master as final step)
git checkout -b monorepo
git subtree add -P plugin-server ../plugin-server HEAD
# Force push to remote branch for review
git push origin monorepo:monorepo -f
```

After this push is done all PRs will need to be rebased against new master

## What's next?
Once we make this master we will cut all of the wiring over from the old repo to this repo for deploys, npm, docker, et all.

### CODE REVIEW

**Comment by tiina303** [comment]
When I looked at https://github.com/PostHog/posthog/tree/monorepo I only saw this one commit there, specifically https://github.com/PostHog/posthog/commit/f4193014c660d9ea0c75533a7af1e811a16a5931 I'm not sure how the history is maintained exactly (https://github.com/PostHog/posthog/commits/monorepo/plugin-server)?

**Comment by fuziontech** [comment]
@tiina303 
image

**Comment by fuziontech** [comment]
I do see what you mean though. Inside of the plugin-server folder the history is squashed to the latest comment which is not supposed to happen. 👀

**Comment by tiina303** [comment]
how did you get to that view I also looked at https://github.com/PostHog/posthog/commits/monorepo & just see the 1 commit

**Comment by fuziontech** [comment]
OK there's something going on with github's interface. I've been beating myself against a wall thinking that this was a bug on my end. Turns out github is just not rendering this right on the branch.

Try this locally
```bash
git checkout monorepo
git pull
git reset --hard origin/monorepo
```

and then browse through the files with git blame on. You'll see the correct commits and pointers to the correct PRs

**Comment by yakkomajuri** [comment]
Do we need to force merge? Seems that disabling "Squash and merge" would allow us to do this via this PR

**Review by yakkomajuri — COMMENTED** [review]
Looks great, thanks for the work on the commits.

Not sure we do need to force merge though.

However, I'm now wondering about what the final steps are that we need to take after this to finalize this. This adds the subdirectory in but we still don't use it. I have a few PRs coming to the plugin server and it would be nice to avoid having to do them in both places.

**Comment by yakkomajuri** [comment]
Would like to merge [this](https://github.com/PostHog/plugin-server/pull/596) for instance, which would leave us out of sync. But that change would still go live, given we'll still be referencing that repo elsewhere

**Comment by fuziontech** [comment]
We can certainly do this after your large changes get merged in. This is more of just a representation of what the world will look like after we do this.

I tried to merge this in but got a lot of strange merge conflicts on files that were not modified by this which sketched me out. If someone is able to do this without that problem I would 100% support merging over force pushing.

**Comment by fuziontech** [comment]
Followed up on this on my ubuntu box and no such issues merging. Updated plan is to merge! Not sure what is up with my macbook.

**Comment by tiina303** [comment]
btw I suspect you need to change the settings for this repo before that (& revert later). I think we want "Allow rebase merging"
Screen Shot 2021-10-14 at 21 03 17

**Comment by mariusandra** [comment]
Will this get merged eventually?

**Comment by tiina303** [comment]
@fuziontech want to merge now (any time before Monday) assuming @macobo is ok with that (he has 1 open PR, but I think that can easily be moved to be on top of PostHog repo). I'll be continuing to work on data integrity, but likely will break the existing open PRs up to smaller ones and might as well do that in the posthog repo.

**Comment by macobo** [comment]
Just do it - it's _more_ confusing for me having this PR open.

**Comment by fuziontech** [comment]
I'll start the process of this tomorrow 🚢

**Pull request merged**
