### PR TITLE
feat: advanced settings in flags

### PR DESCRIPTION
**Pull request by liyiy**
## Problem

Permissions and auto rollouts should live under advanced settings in feature flags

## Changes

Screen Shot 2023-03-02 at 8 32 46 PM

https://user-images.githubusercontent.com/25164963/222608932-465236bd-ee8f-4109-9819-ada7aa86100c.mov

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by liyiy** [comment]
We only put the details for permissions because auto rollout is not even in beta right now 😬 but I'll add that summary detail to advanced settings when it is

**Review by neilkakkar — APPROVED** [review]
Had a quick look at other places in the app, and the drawer everywhere seems to be only icon-clickable.

Makes sense here to have a larger click area, the whole drawer turning dark blue though looks a bit odd.

**Comment by neilkakkar** [comment]
Maybe @Twixes has a way to resolve that^

**Comment by liyiy** [comment]
> Had a quick look at other places in the app, and the drawer everywhere seems to be only icon-clickable.

🤔 Isn't that because there's other things the user can accidentally click on for those drawers? There's like at least 3 different things to click on besides the expansion here 😅 Also those expansions are a bit different than a collapsible IMO

Screen Shot 2023-03-03 at 11 35 26 AM

> Makes sense here to have a larger click area, the whole drawer turning dark blue though looks a bit odd.

I'm just using a lemonbutton for that here, personally I think it's fine because it helps highlight to the user that it's clickable but if anyone else feels strongly about it with some UX reason too I'm happy to fix 😃

**Comment by liyiy** [comment]
Merging before CI breaks but any follow up I'll address in another PR 😳

**Pull request merged**
