### PR TITLE
Make PLUGIN_SERVER_INGESTION True by default

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

We held off on doing this due to some reliability issues on Cloud, but these have been resolved now, and we've just merged PostHog/plugin-server#213. Therefore we will be moving to making plugin server ingestion _the_ ingestion approach.

### CODE REVIEW

**Comment by mariusandra** [comment]
As discussed in this (internal) [slack thread](https://posthog.slack.com/archives/C01F6QWTVB5/p1614270427013700?thread_ts=1614262614.011800&cid=C01F6QWTVB5), we'll leave this as `False` for one more release.

**Comment by Twixes** [comment]
That was basically my idea too. Can we leave this to be merged on Monday/Tuesday/whatever day 1.22 is publishes?

**Comment by mariusandra** [comment]
Definitely, though I'd say even a few days later just for safety (patch release anyone?)

**Comment by Twixes** [comment]
1.22 frozen. Let's do this.

**Pull request merged**
