### PR TITLE
fix: Flakey snapshot

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

This has killed my productivity today so I'm killing it 😅 

## Changes

Happy to have it be fixed instead but this is my level of time I can give to the issue...

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
Should be fixed with https://github.com/PostHog/posthog/pull/23904. Let me know if you're still getting flakes for this test @benjackwhite

**Comment by benjackwhite** [comment]
@thmsobrmlr you're a legend thank you!

**Comment by benjackwhite** [comment]
Still seeing this ... https://github.com/PostHog/posthog/pull/23938/commits/fd3e17a20d8a159a2e0fce964e6ac87efed66498

**Review by thmsobrmlr — APPROVED** [review]
> Still seeing this ... [fd3e17a](https://github.com/PostHog/posthog/commit/fd3e17a20d8a159a2e0fce964e6ac87efed66498)

😢 I'll dig deeper, but let's get this in to unblock for now

**Pull request merged**
