### PR TITLE
fix(flags): our geoip service wasn't actually returning `$geoip_city_name` correctly, so properties weren't being overridden as expected

### PR DESCRIPTION
**Pull request by dmarticus**
## Problem

[A user had an issue](https://posthoghelp.zendesk.com/agent/tickets/18725) where a flag based on the `geoip_city_name` field was flapping on `identify` events from React Native (which trigger flag reloads).  [Our docs say](https://posthog.com/docs/libraries/react-native#overriding-server-properties) that these properties are overridden by the request, but it turns out that was only partially true....

Long story short, our GeoIP service returns some data that looks like this (note the `city` key name)
```
{'city': 'Sydney', 'continent_code': 'OC', 'continent_name': 'Oceania', 'country_code': 'AU', 'country_name': 'Australia', 'dma_code': None, 'is_in_european_union': False, 'latitude': -33.8715, 'longitude': 151.2006, 'postal_code': '2000', 'region': 'NSW', 'time_zone': 'Australia/Sydney'}
```
But our GeoIP parsing code was trying to extract data like this
```
VALID_GEOIP_PROPERTIES = [
    "city_name",
    "country_name",
    "country_code",
    "continent_name",
    "continent_code",
    "postal_code",
    "time_zone",
]

...

def get_geoip_properties(ip_address: Optional[str]) -> dict[str, str]:
    """
    Returns a dictionary of geoip properties for the given ip address.

    Contains the following:
        $geoip_city_name
        $geoip_country_name
        $geoip_country_code
        $geoip_continent_name
        $geoip_continent_code
        $geoip_postal_code
        $geoip_time_zone
    """
    if not ip_address or not geoip or ip_address == "127.0.0.1":
        # "127.0.0.1" would throw "The address 127.0.0.1 is not in the database." below
        return {}

    try:
        geoip_properties = geoip.city(ip_address)
    except Exception as e:
        logger.exception(f"geoIP computation error: {e}")
        return {}

    properties = {}
    for key, value in geoip_properties.items():
        if value:
            mapped_key = GEOIP_KEY_MAPPING.get(key, key)
            if mapped_key in VALID_GEOIP_PROPERTIES:
                properties[f"$geoip_{mapped_key}"] = value
    return properties
```

The astute reader may notice that we were just ditching the `city` field because it wasn't in the valid field list 🤦 

This meant that we weren't overriding the properties for the react native app when doing GeoIP targeting, which led to the inconsistent feature flag behavior that our user was experiencing.

## Changes

I modified the `geoip.py` service to correctly parse the city names from Geoip2-City.mmdb, I updated the tests to include test cases for parsing cities (since we didn't have that), and I added this test case to our Rust code as well (which did handle this case correctly, go me).

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

New unit tests

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
daaaaaamn, nice catch! I guess we have our first customer using city targeting 🙈

**Comment by dmarticus** [comment]
ugh the tests are passing in CI but failing locally; do we have some sort of different GeoIP database in CI vs locally?  @neilkakkar do you know?  Locally, my GeoIP says that `Coyoacán` is `Cuauhtémoc` and `Baldock` is `Royston` 🤔 

just asking in case you know, I'll look after sprint planning too

**Review by Phanatic — APPROVED** [review]
Looks good, good catch and fix!

**Comment by neilkakkar** [comment]
you probably have an old downloaded geoip database while CI downloads the newest one. Try deleting the local one and running bin/start again (which automatically downloads it if not present)

**Comment by dmarticus** [comment]
> you probably have an old downloaded geoip database while CI downloads the newest one. Try deleting the local one and running bin/start again (which automatically downloads it if not present)

that was it! Thank you :)

**Pull request merged**
