### PR TITLE
feat(ci): use Depot for Docker builds in CI, take 2

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Reverts PostHog/posthog#10179 and incorporates the fixes from #10182.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Hey @timgl / @EDsCODE, let me know if there's anything more we need to do here, but this should be ready to merge and re-test. It includes the original workflow changes + the fix for the failing build from #10182.

**Comment by jacobwgillespie** [comment]
I have fixed the merge conflict 👍

**Comment by jacobwgillespie** [comment]
This is ready for review and is not stale.

**Comment by timgl** [comment]
Sorry Jacob I've been on holiday, will have a look today.

**Comment by timgl** [comment]
Closing in favour of #10624 as I couldn't push changes to master to this PR

**Comment by jacobwgillespie** [comment]
Thank you, and totally no worries 🎉

**Pull request closed without merging**
