### PR TITLE
fix(annotations): Ensure timezone alignment

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Some annotations near period edges fell into the neighbor period because of timezone mismatches (unless both the project and client were set to UTC).

## Changes

All annotations should now be bucketed accurately.

## How did you test this code?

Updated logic tests to verify timezone correctness too.

### CODE REVIEW

**Review by benjackwhite — CHANGES_REQUESTED** [review]
Code-wise it looks good, but it doesn't seem to work for my browser/timezone combination

**Comment by benjackwhite** [comment]
@Twixes additional context - Added to a chart with "day" interval. They don't show up after adding or refresh but do show up when grouped by week/month

**Comment by Twixes** [comment]
Hmm, I _suspect_ it was because of the insight timezone being out sync with the project timezone. Or at least I can't reproduce this anymore. Can you try now?

**Comment by pauldambra** [comment]
something is off somewhere :)

**Comment by Twixes** [comment]
Should be good now, can you take a second look? @benjackwhite @pauldambra

**Review by mariusandra — APPROVED** [review]
LGTM 👀

**Review by benjackwhite — APPROVED** [review]
It works! Tried two different timezones and different groupings and at each stage it was correct. Great job 💪

**Comment by pauldambra** [comment]
grouped by day it seems to be off by a day?

I started from scratch on fresh install, viewed weekly active users and added some annotations, and then shifted to group by day. set to UTC

**Comment by pauldambra** [comment]
Although it's actually worse in Master 🤣  So no reason to block this PR 

Screenshot 2022-09-23 at 12 41 07

**Comment by Twixes** [comment]
Thanks for letting me know, all the cases seem to work as expected now!

**Pull request merged**
