### PR TITLE
feat: Always use person_distinct_id_override

### PR DESCRIPTION
**Pull request by timgl**
## Problem

For one version of PoE we were still using person_override instead of the correct person_distinct_id_override

Two types of people that would run into this
1. Anyone who opted in to poev2 in the old settings page
2. Anyone opting in to this on the new settings page
image

This _will_ somewhat change data for these groups. I think this is acceptable as they opted in to this, and it's better to be correct. It will also reduce confusion for anyone now opting in to this, as the new settings don't explain the trade off the old settings did.

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by Twixes** [comment]
I think the base commit of this PR is wrong, so the diff is much larger than it should be @timgl

**Comment by timgl** [comment]
@Twixes done!

**Review by fuziontech — APPROVED** [review]
lgtm!

**Review by Twixes — COMMENTED** [review]
Looks good to me, but results are different in a couple of tests, not sure why

**Comment by tkaemming** [comment]
> Looks good to me, but results are different in a couple of tests, not sure why

This also looks good to me in general. I spent a bit of time trying to figure out what was going on with these tests, too.

The issue with `posthog/hogql/test/test_modifiers.py::TestModifiers::test_modifiers_persons_on_events_mode_mapping` has a pretty straightforward fix: 89773344ed31d3c50d33a6e0fe78b225115135f7

The other test failures are more confusing: I assumed they were because the overrides created in the tests were still being written to the old `person_overrides` table and fixed that with 55a3179427cde107ada56806221aa86a6b97cb0b, but that doesn't seem to fix anything and actually causes _more_ test failures (7 failures with persons-on-events test flag off - up from 3 if you exclude the modifiers test, and tests then also start failing with the test flag on where they weren't before.)

It seems like these tests are still using the legacy event query. When patched with:

```diff
diff --git a/posthog/queries/event_query/event_query.py b/posthog/queries/event_query/event_query.py
index 49d4565a94..56ed872b81 100644
--- a/posthog/queries/event_query/event_query.py
+++ b/posthog/queries/event_query/event_query.py
@@ -134,6 +134,8 @@ class EventQuery(metaclass=ABCMeta):
         return f"{self.DISTINCT_ID_TABLE_ALIAS}.person_id"
 
     def _get_person_ids_query(self, *, relevant_events_conditions: str = "") -> str:
+        raise NotImplementedError("using legacy event query")
+
         if not self._should_join_distinct_ids:
             return ""
 
```

… running `PERSON_ON_EVENTS_V2_ENABLED=true py.test -k person_on_events_v2` results in:

```
FAILED ee/clickhouse/queries/test/test_paths.py::TestClickhousePaths::test_person_on_events_v2 - NotImplementedError: using legacy event query
FAILED ee/clickhouse/queries/test/test_retention.py::TestClickhouseRetention::test_groups_filtering_person_on_events_v2 - NotImplementedError: using legacy event query
FAILED ee/clickhouse/views/test/test_clickhouse_stickiness.py::TestClickhouseStickiness::test_stickiness_with_person_on_events_v2 - AssertionError: b'{"type":"server_error","code":"error","detail":"A server error occurred.","attr":null}'
FAILED posthog/queries/funnels/test/test_funnel.py::TestFOSSFunnel::test_funnel_events_with_person_on_events_v2 - NotImplementedError: using legacy event query
FAILED posthog/queries/test/test_retention.py::TestFOSSRetention::test_month_interval_with_person_on_events_v2 - NotImplementedError: using legacy event query
FAILED posthog/queries/test/test_trends.py::TestTrends::test_same_day_with_person_on_events_v2 - NotImplementedError: using legacy event query
FAILED posthog/queries/test/test_trends.py::TestTrends::test_same_day_with_person_on_events_v2_latest_override - NotImplementedError: using legacy event query
```

Not sure what the plan is with updating or replacing these tests to use the new queries, but hopefully this saves some debugging time for you.

Also, once we're not using this table in production queries any longer, I can take care of removing the override worker deployment and other plugin-server bits.

**Comment by tkaemming** [comment]
You're right, and I misspoke here:

> I assumed they were because the overrides created in the tests were still being written to the old `person_overrides` table and fixed that with [55a3179](https://github.com/PostHog/posthog/commit/55a3179427cde107ada56806221aa86a6b97cb0b), but that doesn't seem to fix anything

That change _does_ fix something — the errors in `posthog/hogql_queries/`! But it also also breaks the old tests in `posthog/queries/` because the change to use `person_distinct_id_overrides` instead of `person_overrides` was never backported to the legacy queries (intentionally.)

To me that seems to suggest a discrepancy in test coverage between the old queries and the new queries. Seems like they should either be ported to the new system, or deleted?

**Comment by timgl** [comment]
@tkaemming I fixed the old queries so they use the new overrides too.

**Review by tkaemming — APPROVED** [review]

**Review by Twixes — APPROVED** [review]
LGTM

**Pull request merged**
