### PR TITLE
Closes #282 better trend date filtering

### LINKED ISSUE #282: Improve trend data filtering
Currently, we can't filter action trends by a flexible date range.

We can only filter "last 7 / 14 / 30" etc days.

It would be better to be able ALSO to pick a start date and an end date.

## Context

The specific use case today was "hey, we're getting a bunch of traffic", but it's really skewed by the popular blog post on HN. We wanted to know where traffic today and yesterday is coming from.

### PR DESCRIPTION
**Pull request by timgl**
image

### CODE REVIEW

**Comment by timgl** [comment]
@Tannergoods QA?

**Comment by Tannergoods** [comment]
Posthog

I think dashboards are broken already, although I have not set any actions in this instance

**Comment by Tannergoods** [comment]
This continues after I set actions.

Posthog

**Comment by Tannergoods** [comment]
This is fixed, well done @timgl

**Pull request merged**
