### PR TITLE
feat: Multiple webhooks per action

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Realised in the current code we have 99% of what we need to offer multiple destination for actions. Part 1 of this is to make the code work basically the same regardless of resthooks or webhooks. Once we have that we just need to modify the UI to create rest hooks rathe than using the action property and walah - multiple configurable webhooks rather than one global one!

We know we want to go in a more ambitious direction for the proper CDP but this feels like an easy win for users today.

## Changes

|Before|After|
|----|----|
| Screenshot 2024-02-20 at 10 33 54 | Screenshot 2024-02-20 at 10 33 47 |
| Screenshot 2024-02-20 at 10 32 30 | Screenshot 2024-02-20 at 10 32 43 |
| Screenshot 2024-02-20 at 10 32 30 | Screenshot 2024-02-20 at 10 32 59 |
| Screenshot 2024-02-20 at 10 35 38 | Screenshot 2024-02-20 at 10 35 55 |

- [x] Refactors the hooks code as it was almost entirely copy-paste anyways
- [x] Add additional property to hooks to allow the same formatting as before
- [x] Update the UI to only show existing webhook config if it is there, otherwise show the new webhook config
- [x] Change the hooks api to filter on resource_id
- [x] Feature flag the whole thing
- [x] Also changes styles of the match groups to be a bit clearer with a real LemonButton for adding a match group
- [x] Opted for inline creation which allows the side-by-side docs to open which is awesome for referencing the formatting stuff

## Follow up
- [ ] Add documentation for the default webhook format
- [ ] Add limit on number of hooks per action?
- [ ] Handle removing webhooks when an action gets deleted

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

- [ ] Checked that the existing stuff worked
- [ ] Fired real webhooks to multiple services locally 🎉 
- [ ] When flag is on, still allows you to configure old config _if_ you already had it enabled.

### CODE REVIEW

**Comment by mariusandra** [comment]
There is a solution/proposal to make the current webhook action matching work without the elements_chain conversion: https://github.com/PostHog/posthog/pull/17042

... the implementation of which stalled because it couldn't read "elements_chain" directly and caused a slowdown when first rolled out. If it could access the chain directly without the elements object now, I could resume work on it in the next weeks.

**Comment by benjackwhite** [comment]
> I was hoping we'd take a different direction here, moving away from these webhooks/resthooks into a destination that's configured similarly to any other destination (which we can then evolve together towards a unified CDP approach), potentially adding a button to the action page to pre-fill info for it. For several reasons, one of them being that current webhooks/resthooks require us to backwards process elements chain, which is broken, expensive and hard to fix.

I don't feel strongly either way - just realised that we have 99% of what we need to at least solve this now. If you feel it adds too much risk or whatever then happy to abandon it - just not sure what that risk is given we would anyways need to migrate away from the old solution 🤔

**Comment by benjackwhite** [comment]
> There is a solution/proposal to make the current webhook action matching work without the elements_chain conversion: #17042
> 
> ... the implementation of which stalled because it couldn't read "elements_chain" directly and caused a slowdown when first rolled out. If it could access the chain directly without the elements object now, I could resume work on it in the next weeks.

@mariusandra this is essentially unrelated right? The elements matching stuff is determining "does this event match this action" which is before any of the changes here if I understand correctly?

**Comment by mariusandra** [comment]
@benjackwhite yes, it's unrelated in the scope of this PR (sending webhooks post match), but a solution to what Tiina was hoping for (matching without elements_chain)

**Comment by benjackwhite** [comment]
> @benjackwhite yes, it's unrelated in the scope of this PR (sending webhooks post match), but a solution to what Tiina was hoping for (matching without elements_chain)
> 
> My 2 cents for this PR: 🚢 !

gotcha - thanks for the clarification (was trying to figure out if it was blocking or not)

**Comment by tiina303** [comment]
> I don't feel strongly either way - just realised that we have 99% of what we need to at least solve this now. If you feel it adds too much risk or whatever then happy to abandon it - just not sure what that risk is given we would anyways need to migrate away from the old solution 🤔

Yes, I'd prefer we didn't do this, as it can increase usage, which might add to our support load, e.g. https://posthog.slack.com/archives/C02E3BKC78F/p1708521484593569
1. there's no visibility for users
2. the elements usage being broken (potentially)

My 2 🪙  I'd love for Marius to instead of the above work on (1) PoE (2) deprecating the stateful processEvent apps that

I'm more envisioning the future is similar to hogQL integration that Tomas built recently for batch exports, that we can use to replace the action matching part (so there will be a generic webhook app that users can configure like any other destination & whatever CDP plans we have on top of that).

**Comment by mariusandra** [comment]
> My 2 🪙 I'd love for Marius to instead of the above work on (1) PoE (2) deprecating the stateful processEvent apps

I'm not sure what you need me to do regarding PoE. I've given all the context I could, and asked to ask me if something is needed. So let me know 🤷.

Regarding the rest, I have my own tasks (e.g. HogQL insights) that are taking precedence over all other work right now, and I'm not planning on investing more in the HogVM work.

> I'm more envisioning the future is similar to hogQL integration that Tomas built recently for batch exports, that we can use to replace the action matching part (so there will be a generic webhook app that users can configure like any other destination & whatever CDP plans we have on top of that).

Does this mean moving away from the current stream processing approach towards a query-per-user-per-minute-till-the-end-of-time approach, and/or breaking the assumption users have that webhooks are "live"?

**Pull request closed without merging**
