### PR TITLE
feat(retention): display chart and table at the same time

### PR DESCRIPTION
**Pull request by hazzadous**
## Changes

This change places the Chart, that was previously navigable via the
display type selector, above the retention table. This is intended to
increase the discoverability of the chart, as well as the "Smile" charts
that can be viewed by specifying the reference_retention param.

"Smile" charts are useful to understanding long term retention
convergence.

This PR is built on top of https://github.com/PostHog/posthog/pull/7340  . We could merge one then the other, or just this one.

Screenshot 2021-12-07 at 14 28 50

## How did you test this code?

Tested manually using the storybook, screenshotted above.

### CODE REVIEW

**Comment by EDsCODE** [comment]
Screen Shot 2021-12-07 at 6 57 13 PM

Graph should be less squished and maybe add some spacing between the graphs?

**Comment by hazzadous** [comment]
> Graph should be less squished and maybe add some spacing between the graphs?

yup yup looks like storybook is giving different results, will check what's going on there

**Comment by hazzadous** [comment]
@EDsCODE have added some specificity so storybook styling is the same as in app.

**Comment by EDsCODE** [comment]
What's the reason for switching up the image here for e2e tests?

**Comment by hazzadous** [comment]
> What's the reason for switching up the image here for e2e tests?

Having some issues with local dev and debugging e2e, was just seeing if it was an issue with the codespaces image, I'll revert

**Comment by EDsCODE** [comment]
The layout looks right now. Something is weird with the tooltips on this graph though

Screen Shot 2021-12-09 at 2 52 11 PM

**Comment by hazzadous** [comment]
> The layout looks right now. Something is weird with the tooltips on this graph though

@EDsCODE  This looks the same on app.posthog.com for the first data point fyi. I guess you're expecting to see the cohort size rather than the percentage? As with the latter tooltips?

Anyway, I'll make it consistent at least. I think the percentage is actually more useful as otherwise these values aren't comparable due to the differing sizes or cohort.

**Comment by hazzadous** [comment]
> @EDsCODE This looks the same on app.posthog.com for the first data point fyi. I guess you're expecting to see the cohort size rather than the percentage? As with the latter tooltips?

Oops, I mistook the dot for a comma, they are all percentages. So I guess the issue could be that it's saying "Day 1" instead of the actual cohort date? I'll have a look at that.

**Comment by EDsCODE** [comment]
Oh, I wasn't looking at this tooltip correctly. I think we need to change the tooltip messaging to make this clearer. When I hover over the tooltip I'm not expecting to see the entire list of periods that make up the conversion rate or atleast not in the list format as shown. I think we _could_ merge and edit rather than hold this PR up though. @clarkus for some advice

**Review by EDsCODE — APPROVED** [review]

**Comment by clarkus** [comment]
Related improvements that @alexkim205 was owning for tooltips at https://github.com/PostHog/posthog/issues/7370. There are some definite scale issues with tooltips, so not sure these are specific to this issue or not. Generally, the tooltips should describe the thing the cursor is pointing at - if I am hovering a date on the axis, I'll see all data points for that date. If I am hovering a specific point, I only see data for that data point. 

In this example, it looks like we're running into an upperbound with the tooltip height and the length of items shown (the list is taller than the tooltip container) which results in cropping. That should also be resolved in the new design updates as we're reducing each row size and generally shoving a ton more stuff in there.

**Comment by hazzadous** [comment]
will resolve conflicts and get merged

**Pull request merged**
