### PR TITLE
Dashboard permissions upsell

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This adds an upgrade button to dashboard restrictions settings (which are a premium feature). Merges into https://github.com/PostHog/posthog/pull/8424.

I first tried out the design [from Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7167%3A36965). That didn't feel very enticing though… As a user, that message is very in-your-face, but it doesn't provide a strong moment where you'd say "we could REALLY use this". My current proposal is this: 

This may not be visible to users most of the time… But if you're that person/org which actually needs the feature, you will be excited to see it exist in UI (and what it has to offer), with it being extremely clear at the same time what path you need to take in order to start using it. The link takes you to the billing page on Cloud and pricing on self-hosted.

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
This diverges from the workflow we use in other places for upsells. We generally push users to the place to upgrade (account settings) primarily, and the secondarily to learn more about pricing / features / etc. The design in figma is targeted at being explicit about this - 1) you have to upgrade to get this, 2) this is here you go to upgrade 3) if you aren't sure, learn more here. 

In this solution, a user would have to navigate back from pricing to their account to upgrade. Just feels like a lot of context switching. What is the problem you're trying to solve for? What communicates the strong moment of "we could REALLY use this" in your solution? Is it that you can see the full range of sharing options and get a better idea of the feature? Is it something else?

**Comment by Twixes** [comment]
I'm basically trying to solve for point 1) "you have to upgrade to get this" by way of giving a better idea of the feature. My question as a user is "what is the 'this' that I should upgrade for?". The mock essentially just says "Upgrade to get Collaboration", which just seems very fluffy (this may be me being engineering-y). I suppose to find out what this actually includes, I have to click "Learn more"! The question is – where does that point? If we have a website page outlining collaboration features with an upgrade call to action, that should do actually. Not being aware of it though, I propose instead giving a clear glimpse at the feature inside the product.

**Comment by clarkus** [comment]
Got it. The text could probably use a few more updates. We're really upselling more than just dashboard collaboration tools, here. "Collaboration" is a set of features, so the text is somewhat aimed at representing that.

Screen Shot 2022-02-04 at 1 15 07 PM
 
Anytime we show a disabled form control, it should be a red flag. Those just read as immediate dead ends to users. Personally I wouldn't have known to click on the banner in the drop down to learn more. I think the clear and prominent buttons are much more obvious. 

I'm generally not a fan showing screenshots of UI inside of product UI because it takes a lot of chrome to distinguish the image from the real thing. I don't want users clicking on a picture thinking it's real product. We also iterate a ton, so that image could quickly become dated and turn into a maintenance burden. I'm all for being more up front with what the product does, but I want to keep all those things in balance - clear text, prominent actions, and aligned to our other upsell workflows.

**Comment by Twixes** [comment]
👍 Closing this in favor of #8614.

**Pull request closed without merging**
