### PR TITLE
chore: env for webhooks timeouts

### PR DESCRIPTION
**Pull request by tiina303**
## Problem

Made the timeout an env.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by xvello — CHANGES_REQUESTED** [review]
Let's add a field to [PluginsServerConfig](https://github.com/PostHog/posthog/blob/bf1a80deb4b345640c5bb44d213d1bf831ed4bd9/plugin-server/src/types.ts#L91) and pass the value to the constructor instead, to make configuration options easier to discover.

**Review by xvello — APPROVED** [review]
Thanks!
Just as a nit, `EXTERNAL_REQUEST_TIMEOUT_MS` hints to me that it also applies to onEvent, which it does not :/ Either:
  - we plan to also apply it to onEvent, by patching `fetch`, let's keep it
  - if not, let's rename `WEBHOOK_REQUEST_TIMEOUT_MS`

**Comment by tiina303** [comment]
> we plan to also apply it to onEvent, by patching fetch, let's keep it

that is exactly my plan. We need it there too.

**Comment by tiina303** [comment]
Update on the plan: the code around onEvent fetch is a bit complex, so I'll migrate to using the ENV as we migrate `onEvent` apps to using `composeWebhook` function.

**Pull request merged**
