### PR TITLE
feat: Update kafkajs to 2.0.0

### PR DESCRIPTION
**Pull request by macobo**
This was released on 6th of may.

Full changelog: https://github.com/tulios/kafkajs/blob/master/CHANGELOG.md

A notable feature is the ability to subscribe to multiple topics which
will help with buffer-based ingestion.

Creating a separate PR for deployment reasons

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Happy to upgrade but:

> A notable feature is the ability to subscribe to multiple topics which will help with buffer-based ingestion.

This was already possible and was the very thing that caused a slowdown in ingestion (when I set up the consumer to consume from buffer and ingestion topics).

Looking at the changelog they just made it so that you can pass in a list of topics to `subscribe` rather than having to call `subscribe` n times. It's syntatic sugar, nothing else

**Comment by yakkomajuri** [comment]
However, I like the sound of https://github.com/tulios/kafkajs/pull/1258

**Comment by macobo** [comment]
There's two considerations:
1. We should be staying on top of our core dependencies
2. When faced with performance issues, we should try the issue on the _latest_ version to make sure it hasn't been fixed.

We don't know whether this version will perform better - I'm hoping to measure after merging this.

**Comment by yakkomajuri** [comment]
Agree 100% - just meant that the `subscribe` thing doesn't really help us

**Review by yakkomajuri — APPROVED** [review]

**Comment by macobo** [comment]
Will deploy this monday to avoid weird regressions.

**Pull request merged**
