### PR TITLE
Add black

### PR DESCRIPTION
**Pull request by timgl**
## Changes

- Add black to post-commit hooks
- This means each time you touch a file it'll be formatted, but it won't cause all of our python files to be re-formatted at once.
- added re-formatting of actions.py as an example

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by fuziontech** [comment]
I love this, but we probably want this to be a `pre-receive` hook right?
We just want to make sure that things are cleaned up before you push it up to a remote branch.
https://githooks.com/

I don't see the hook in this PR but not sure, does that even show up in github PRs?

**Review by EDsCODE — APPROVED** [review]

**Comment by EDsCODE** [comment]
@fuziontech i think @timgl meant pre-commit. He attached it to lint-staged which is the precommit hook we have running for js files which will now lint .py files using black. If black detects something is off it won't let you go through with commit locally (which is what you're aiming for I think)

**Comment by fuziontech** [comment]
👍 sgtm!

**Review by fuziontech — APPROVED** [review]
:shipit:

**Pull request merged**
