### PR TITLE
Fix #7189

### LINKED ISSUE #7189: Missing page headers
## Bug description

The persons and events features are missing their page headers.

Screen Shot 2021-11-17 at 11 13 38 AM

## Expected behavior

These pages should have headers like our other feature pages.

## How to reproduce

1. Navigate to persons or events
2. Note the missing header

## Environment

- [x] PostHog Cloud

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Adds missing page headers and fixes layout to show tabs at the appropriate place. Closes #7189.

**Events & actions**

**Persons**

## How did you test this code?
- Enabled the groups functionality and feature flag to see the page with groups added.
- Disabled the groups feature flag and saw the Persons page still looked as expected.

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
Are the header values conditional based on the selected tab? The headers here should describe the overall page, the tabs should describe just that aspect of the page. Being that headers are higher in page hierarchy, tabs shouldn't have any affect on them.

**Comment by paolodamico** [comment]
As it is right now, the header does change conditionally based on the current tab. What you say about page hierarchy makes total sense, but I also think a changing header provides more value to users. I'm leaning towards a static header as you suggest, but I'll wait for your input on this.

**Comment by mariusandra** [comment]
We already have the same situation on the "Events & Actions" and "Person" pages:



There we have the tabs above the header. It's not ideal for other reasons, but at least the information hierarchy is clear.

**Comment by clarkus** [comment]
The tab should take over describing the feature, not the parent page. While the hierarchy is more accurate, it's still odd and still clashes with the other page structures. If we need to describe these tabs prominently, then maybe they should be distinct pages? I renamed events to Events and Actions just for this reason.

**Pull request merged**
