### PR TITLE
fix(insight-details): display correct property groups filters

### PR DESCRIPTION
**Pull request by liyiy**
## Problem
https://github.com/PostHog/posthog/issues/10048

## Changes

happy to take suggestions on how to make this more nice looking 😃 

Screen Shot 2022-06-07 at 2 45 58 PM
Screen Shot 2022-06-07 at 2 57 21 PM

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
Think it would be good to add @alexkim205 for a review on this. He recently made changes to cohort summary cards that overlaps with this quite a bit. Can we reuse the patterns from the summary cards here? https://github.com/PostHog/posthog/pull/9921

**Comment by liyiy** [comment]
> Think it would be good to add @alexkim205 for a review on this. He recently made changes to cohort summary cards that overlaps with this quite a bit. Can we reuse the patterns from the summary cards here? #9921

yep, taking a look! thanks for heads up

**Comment by liyiy** [comment]
@clarkus regular filters and cohort filters are quite different so I just tried to get the styling to match as close as possible

Screen Shot 2022-06-22 at 7 20 29 PM

**Comment by clarkus** [comment]
I don't think this is ready to be merged. I'll put in some time to draw read only filters for this. I figured we could reuse the treatment from the cohort cards, but what we have here just feels confusing to me. It'd be clearer with the operators between criteria and between the criteria groups. I won't be able to get to it until Monday, though.

**Comment by clarkus** [comment]
Posted a revised idea at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=11696:49716#218374148

**Pull request closed without merging**
