### PR TITLE
fix(recordings): use prewhere to speed up query

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

Recording queries are super slow sometimes

## Changes

Uses `PREWHERE` instead of `WHERE` to allow CH to read less data in the recording queries

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Loaded a list of recordings, filtered it, and then played a recording locally

### CODE REVIEW

**Review by fuziontech — APPROVED** [review]
image

**Comment by neilkakkar** [comment]
hmmm, now that I think about it, the slowdown could've been caused by me setting optimize_move_to_prewhere to false, because CH bugs: https://github.com/PostHog/posthog/blob/master/posthog/client.py#L61

**Comment by rcmarron** [comment]
> hmmm, now that I think about it, the slowdown could've been caused by me setting optimize_move_to_prewhere to false, because CH bugs: https://github.com/PostHog/posthog/blob/master/posthog/client.py#L61

Oooooooo yeah, I bet that's it. The timing lines up with when we started seeing the slowdown.

**Comment by fuziontech** [comment]
100% - If we can we should remove that or selectively apply that setting where we know things are broken.

Alternatively we can just manually select what to prewhere everywhere. Either way we need to have CH using prewhere's because of how much IO not using prewhere's costs us.

**Comment by neilkakkar** [comment]
We can get rid of it fully, if we can bump a CH version or two ;)

**Pull request merged**
