### PR TITLE
Adds to #216 change layout, move actions to top of graph

### PR DESCRIPTION
**Pull request by timgl**
image
Changed layout to move actions to top

### CODE REVIEW

**Comment by timgl** [comment]
@Tannergoods When you get a chance :)

**Comment by Tannergoods** [comment]
Invalid attempt to spread non-iterable instance I'm afraid

**Comment by timgl** [comment]
LOL

**Comment by timgl** [comment]
@Tannergoods fixed

**Comment by Tannergoods** [comment]
It works - all good!

**Pull request merged**
