### PR TITLE
Bring back top sessions link in persons modal

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Bring back sessions links on the top of the persons modal

Screen Shot 2021-08-09 at 10 17 47 AM
Screen Shot 2021-08-09 at 10 18 04 AM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by paolodamico — CHANGES_REQUESTED** [review]
I'm actually not sure we should bring these links back. These links seem useful if you don't have the individual buttons for each person, otherwise I'm not sure they're really achieving a useful goal here.

With individual buttons in, when you actually want to deep dive to understand "why", you jump into a specific recording, rather than getting the same list again and still needing to open that recording.

As for the general sessions page link, I wouldn't bring this back until we figure out #4884.  

Please feel free to challenge.

**Comment by liyiy** [comment]
What do you think? @macobo

**Comment by clarkus** [comment]
Related - I was addressing other feedback and restored the "view sessions" link in the footer of the modal. See the related work at https://github.com/PostHog/posthog/issues/5326#issuecomment-896472538

**Comment by macobo** [comment]
Up to you, just pointed out a weirdness in slack/asked for context :) Just noting a key client starting with V also mentioned this link being missing in their users chat (Marcus has context)

**Comment by paolodamico** [comment]
@marcushyett-ph do you have any extra context on this before we make a decision?

**Comment by marcushyett-ph** [comment]
The ideal solution is to direct straight from each user to the relevant session, in lieu of this, proving the link at the top sounds reasonable.

**Comment by liyiy** [comment]
> The ideal solution is to direct straight from each user to the relevant session, in lieu of this, proving the link at the top sounds reasonable.

That's what we do currently, let's close this then? We'll most likely revisit this anyway after the sessions rework

**Pull request closed without merging**
