### PR TITLE
feat: Add warning for person deletion modal

### PR DESCRIPTION
**Pull request by tiina303**
## Problem

For https://github.com/PostHog/posthog/issues/11590

## Changes

Screenshot 2022-11-02 at 16 50 25

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by tiina303** [comment]
Modal also says "Their ID(s) will be usable again in an hour or so." after deletion

**Comment by Twixes** [comment]
Is this still needed @tiina303 @macobo?

**Comment by tiina303** [comment]
The plan is to fix deletes completely (likely by using soft-deletes), so pushing this out could confuse users, so lets maybe not

**Review by xvello — APPROVED** [review]

**Comment by tiina303** [comment]
Context for why I re-opened it, while the plan is still to fix it I was obviously too optimistic in the past about when we'll get to it ... let's be pessimistic instead. See also https://posthog.slack.com/archives/C0374DA782U/p1684245049955989

**Pull request merged**
