### PR TITLE
feat(property-filters): Feature flags in a separate tab

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

[This list was getting long](https://posthog.slack.com/archives/C01RJ7T212S/p1657202672696189)

## How did you test this code?

Added tests for python, tested the rest locally.

Still something broken, will fix.

### CODE REVIEW

**Comment by camerondeleone** [comment]
I wanted to take a peek at how common event filters relative to other types are, and while it looks like we send the filter properties in the `filters set` event, I don't think the information there can differentiate between event, person, or group property filters, so we have no way to rank these in terms of which order we should put these in in the UI. Event would be the winner by a long shot if I had to guess, though. (Is this a bug or the intended behavior?)

(Tried a couple ways -- maybe I'm missing something - [PostHog](https://app.posthog.com/events?eventFilter=filters%20set&properties=%5B%7B%22key%22%3A%22filters__0__type%22%2C%22value%22%3A%22event%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22filters__0__type%22%2C%22value%22%3A%22action%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22filters__0__type%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22filters__0__type%22%2C%22value%22%3A%22new_entity%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D), [metabase](https://metabase.posthog.net/question/366-distinct-filter-types-on-filters-set-event))

**Comment by mariusandra** [comment]
Hey @pauldambra and @kappa90 can you help get this over the line in the next weeks?

**Review by pauldambra — APPROVED** [review]
:shipit:

**Review by benjackwhite — APPROVED** [review]
Didn't try it myself but everything looks code-wise great 👍

**Pull request merged**
