### PR TITLE
refactor(enteprise): Removes conditional SAML dependencies

### PR DESCRIPTION
**Pull request by paolodamico**
## Problem
Bunch of context in https://github.com/PostHog/posthog/pull/5870, https://github.com/PostHog/posthog/pull/6575#discussion_r733457836 & https://github.com/PostHog/posthog/pull/6607. More recently, as we work to bring SAML to Cloud, here's some context, https://github.com/PostHog/meta/pull/40

## Changes
- SAML dependencies (`libxml2-dev~=2.9`, `xmlsec~=1.2` & `xmlsec-dev~=1.2`) will now be required for all PostHog installations (including FOSS).
- No more conditionals on SAML stuff, will now run as a regular part of the `ee` codebase.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Looks clean 🧹 
Plugin server test failing though, re-running 😅

**Review by guidoiaquinti — APPROVED** [review]

**Comment by neilkakkar** [comment]
Heads up: I see SAML mentioned in local dev docs, can we update those as well? https://posthog.com/handbook/engineering/developing-locally

**Comment by guidoiaquinti** [comment]
> Heads up: I see SAML mentioned in local dev docs, can we update those as well? https://posthog.com/handbook/engineering/developing-locally

https://github.com/PostHog/posthog.com/pull/3132#pullrequestreview-910350796

**Comment by neilkakkar** [comment]
Amazong!

**Pull request merged**
