### PR TITLE
fix: have only way to create new dashboards

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

see #10788 

Creating a dashboard from the Insight 'Add to Dashboard' modal does not use the same form as when creating from the dashboards page

## Changes

* Uses the same form
* lets a user choose whether to visit the dashboard after creation
* defaults to not visiting the dashboard when creating from Insight view
* fixes adding a description in the new dashboard form which wasn't wired up

## Form with new checkbox

Screenshot 2022-07-18 at 11 39 53

NB there are other places we create dashboards that don't use the same form. They're not fixed in this PR

## How did you test this code?

running it locally and seeing it work

### CODE REVIEW

**Review by kappa90 — APPROVED** [review]
Good for me :)

**Comment by pauldambra** [comment]
The other two ways of creating a dashboard are...

## When there are no dashboards

We create an empty dashboard without using the modal



## from the command palette

we create an empty dashboard with a specified name without using the modal

**Review by benjackwhite — APPROVED** [review]

**Review by clarkus — CHANGES_REQUESTED** [review]
I don't think the checkbox for viewing the dashboard after creation is the best approach. Ideally we will display a toast notification on creation that links to the newly created dashboard. A user could click through that to view the new dashboard. Another approach would be primary and secondary creation actions: "Create" or "Create and go to dashboard". The reason I'm pushing back on the check box is because it's not really part of the dashboard definition... it's more a utility or nice-to-have option. It wouldn't fall under the same validation considerations for the rest of the form.

When creating from the command prompt, instead of using the prompt to populate all the dashboard parameters, could we instead trigger thew dashboard creation modal? It'd be just as convenient for the user and it would reduce the overlapping paths for creating dashboards. 

I'm a +1 on the other changes.

**Comment by pauldambra** [comment]
I like the idea of buttons instead of the checkbox...

The two routes behave differently at the moment anyway. So good to give people the choice IMHO

**Comment by pauldambra** [comment]
I'll leave command palette out of this PR https://app.posthog.com/insights/asUtZGb8

**Review by clarkus — APPROVED** [review]
Any chance we can link to the newly created dashboard in the toast notification too? I'm a +1 on the other stuff.

**Comment by pauldambra** [comment]
> Any chance we can link to the newly created dashboard in the toast notification too?

I'll merge and immediately follow-up (I'd expect so but....)

**Pull request merged**
