### PR TITLE
fix: activity score

### PR DESCRIPTION
**Pull request by pauldambra**
* make sure the lower half of the percentage is alway bigger than the top
* add a little color to the score

Screenshot 2024-10-23 at 17 59 41

or as a "snack"

Screenshot 2024-10-23 at 19 33 44

### CODE REVIEW

**Comment by pauldambra** [comment]
@andyvan-ph @annikaschmid added a little color -... too little?

**Comment by pauldambra** [comment]
also... i like the idea of making it "activity" instead of "activity score" and calling it low, high etc

**Comment by andyvan-ph** [comment]
> also... i like the idea of making it "activity" instead of "activity score" and calling it low, high etc

Yeah, I like that version too, though maybe "Engagement" is better? I don't feel strongly.

The colors are a little muted, though. I think a cold to hot would make sense, kind of like the heatmap, i.e:

- Very High: Red
- High: Orange
- Medium: Yellow
- Low: Purple
- Very low: Blue

**Review by richard-better — APPROVED** [review]

**Comment by pauldambra** [comment]
> The colors are a little muted, though. I think a cold to hot would make sense,

I think I'll get this in as is... we don't already have bright colours where you aren't supposed to interact with them

But absent other feedback we can definitely talk about it in the UX review in Valencia!

**Comment by pauldambra** [comment]
> The snack version looks a bit too busy for me

Ah, sorry! I missed this before merging...

**Pull request merged**
