### PR TITLE
feat(insights): Allow "Detailed results" table in shared insights

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

@posthogseb reported a customer being surprised that the "Detailed results" table can't be shown in the shared version of the insight. There's no technical obstacle to that, we just hadn't implemented the option.

## Changes

Here's the option:

Screenshot 2024-07-19 at 20 38 53

And here's a shared insight with it on (`?detailed` in the URL):

Screenshot 2024-07-19 at 20 37 20

I also fixed some weirdness around overflow, which is what the CSS changes are trying to address.

## How did you test this code?

~~TODO: Stories to gain visual snapshot coverage~~ Added.

### CODE REVIEW

**Review by thmsobrmlr — COMMENTED** [review]
IMO it would be better if we'd handle the option on the schema level and not as exporter option. We have frequent requests that people want to add other visualizations of their data on a dashboard as well and this is one of the reasons we came up with the nested node structure.

**Review by benjackwhite — COMMENTED** [review]
So little context now on these things that I'd rather leave y'all product peeps to review 🙌

**Comment by posthogseb** [comment]
@PostHog/team-product-analytics if you have a moment can you please have a look at this PR to approve it? Customer has been asking for it :) Thank you!

**Review by thmsobrmlr — APPROVED** [review]
Works well!

I assume we'll merge this PR in soon and will redo https://github.com/PostHog/posthog/pull/23886 on top of this (wanted to redo that for cleaning up anyways).

**Pull request merged**
