### PR TITLE
fix: re-enable team deletion with lightweight deletes

### PR DESCRIPTION
**Pull request by yakkomajuri**
implements [lightweight deletes](https://clickhouse.com/docs/en/guides/developer/lightweght-delete) for team deletion and re-enables the task that does it on weekends.

in reality we actually don't need to do this on weekends anymore, we can just do it synchronously. that's because lightweight deletes doesn't trigger any deletion immediately, it just marks rows for deletion in the background later.

but for now, let's just bring the old system back.

a follow up is to get rid of the whole AsyncDeletion model once we're confident in this

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Great :D

```
DB::Exception: DELETE query is not supported for table posthog_test.sharded_events.
```

Why?

**Comment by yakkomajuri** [comment]
Found out the issue: https://github.com/ClickHouse/ClickHouse/discussions/49299

**Comment by mariusandra** [comment]
What does this mean? Lightweight deletes don't work if a table uses `PROJECTION`s? What are those, and what do we use them for?

My rough search revealed that we only use one projection that came from here: https://github.com/PostHog/posthog/pull/13371

- "Make clickhouse_lag celery metric cheap."

Do we need it? Could this be made cheap some other way? Might VictoriaMetrics come with some magic that helps here?

**Comment by yakkomajuri** [comment]
Worry not! This is under control. 

I did a good bit of digging yesterday and I'm just going to delete the projections. We have a minmax index for the same column now so should be ok. Plus worst case is we have a metric be slow.

Apparently upgrading ClickHouse (again) might also do the trick but I won't advocate for that now :D

**Review by hazzadous — APPROVED** [review]
Do we need to worry that there will be a backlog to get through and that the initial delete will be really large? My understanding is that this will still be using the mutations queue and will block.

**Comment by yakkomajuri** [comment]
yeah was thinking about this. we should probably be careful, wondering how best to go about it, maybe limit the job somehow?

**Comment by hazzadous** [comment]
> yeah was thinking about this. we should probably be careful, wondering how best to go about it, maybe limit the job somehow?

Maybe we can trigger manually after merging? Then just make sure it's fine, otherwise cancel the op. It feels like something we should bound though, but it might be ok for now 🤞

**Comment by yakkomajuri** [comment]
will merge and then we should try this manually before the weekend

**Pull request merged**
