### PR TITLE
Take posthog-js from the props to the toolbar

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Takes `posthog-js` directly from the props passed to the toolbar, not from the `window` object.
- Depends on https://github.com/PostHog/posthog-js/pull/327

## How did you test this code?

- Ran locally, everything still worked. The toolbar does not have tests to begin with, so :yolo:

### CODE REVIEW

**Review by rcmarron — APPROVED** [review]
LGTM - tested with the old version of ph-js, and it works as expected.

**Comment by mariusandra** [comment]
Darnit, I was too slow to disable auto-merge.
I'm not that convinced about the extra spaces in the URL: https://github.com/PostHog/posthog/pull/6699/commits/12642073c442c2ae822f73123ac6bc09e197fd9c

**Comment by rcmarron** [comment]
> I'm not that convinced about the extra spaces in the URL: 1264207

Ah must've also been a prettier thing.... not sure what's going on. I'll push a revert  of that now.

**Comment by rcmarron** [comment]
>Ah must've also been a prettier thing.... not sure what's going on. I'll push a revert of that now.

@mariusandra https://github.com/PostHog/posthog/pull/6703

**Pull request merged**
