### PR TITLE
feat(flags): Disallow creating feature flags with Behavioral cohorts

### LINKED ISSUE #8628: Disable behavioral cohorts for new feature flags
## Context

Posthog cloud has been struggling recently due to load introduced by postgres `CohortPeople` calculations. We've stemmed the bleeding but the fundamental scalability issue remains:

/decide endpoint uses `CohortPeople` to decide what feature flags are enabled for a given user in an efficient manner as all client libraries depend on it. The endpoint thus cannot query clickhouse. Problem comes from cohorts with behavioral filters (user has done X in time range) which require doing event query to calculate.

We currently cache these cohorts periodically into postgres, which introduces a lot of load on postgres and clickhouse.

## Proposal 

Disable behavioral cohorts for feature flags. The semantics are unclear it poses a hard scalability challenge.

I discussed this briefly with @marcushyett-ph and rather than make feature flags immediately more powerful/scalable, the better answer is to disable the complicating behavior.

### Implementation plan

We can make this happen with no cost to current users by deprecating the functionality. This can be done by:
1. Storing a flag on cohorts if they have behavioral filters
2. Disallowing behavioral cohorts when creating/updating behavioral cohorts
3. Only calculating cohortpeople for cohorts with the flag and which are associated with a feature flag (small minority)
4. In the /decide endpoint, if feature flag checks a cohort, for normal cohorts check person properties instead of cohort, for behavioral cohorts, check the table.

Note if there are other usages of the CohortPeople table, we should query clickhouse for it instead.

## Additional context

Related issue: #7115

cc @guidoiaquinti @hazzadous @marcushyett-ph @EDsCODE @paolodamico for product and technical context.

cc @mariusandra and @clarkus for deprecation/design considerations

I propose this becomes a focus next sprint to lessen the load on team platform.

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

What it says on the tin^

Fixes https://github.com/PostHog/posthog/issues/8628

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Unit tests!

### CODE REVIEW

**Review by rcmarron — COMMENTED** [review]
This does a good job of erroring when a user tries to save a feature flag that users a behavioral cohort, but I think ideally, we would make it clearer to the user earlier on, so they can't even select behavioral cohorts and it's obvious that the list of cohorts that they're selecting from are only the non-behavioral ones.

This seems kind of tricky because the concept of behavioral vs not-behavioral cohort isn't  exposed elsewhere. @clarkus curious if you have thoughts on this?

I could be convinced that this doesn't happen frequently, so we shouldn't worry about it, but if that's the case, we should probably have some metrics + intrumentation for when this happens.

**Comment by neilkakkar** [comment]
Great idea!
 
> This seems kind of tricky because the concept of behavioral vs not-behavioral cohort isn't exposed elsewhere.

Actually, since `cohortsModel` are loaded on app mount, I can create a selector specifically for this, so the error state is almost impossible.

I could use some guidance though on how to explain that this list of cohorts you're seeing is incomplete...

**Comment by neilkakkar** [comment]
On second thoughts, given we have <30 total behavioural cohort FFs on cloud, I'll go the metrics route, even if the other route (only non-behavioral cohorts with design that makes it obvious) is possible. It doesn't seem worth the effort.

**Review by rcmarron — APPROVED** [review]
LGTM

**Pull request merged**
