### PR TITLE
fix(trend experiments): filter insight results correctly

### PR DESCRIPTION
**Pull request by jurajmajerik**
## Changes
A possible mistake/bug in `trend_experiment_result.py`

## How did you test this code?
existing tests pass

### CODE REVIEW

**Comment by jurajmajerik** [comment]
Edit - the existing test do break:

`ee/clickhouse/views/test/test_clickhouse_experiments.py::ClickhouseTestTrendExperimentResults::test_experiment_flow_with_avg_count_per_user_event_results - AssertionError: 0.8858 != 0.805 within 2 places (0.08079999999999998 difference)`

I wonder if they break because of the incorrect hardcoded value?

**Comment by neilkakkar** [comment]
ugh, I need to remember what the logic was here, disappointed I did not add comments 🤦

**Comment by neilkakkar** [comment]
ok no this is correct I think, see here: https://github.com/PostHog/posthog/pull/15623/files#diff-709ec28722b679d006e06a7f4ded9ca56468eaa42c7fde8217f70a6ab7ffbea7R105-R108

and see: https://github.com/PostHog/posthog/pull/15623/files#diff-709ec28722b679d006e06a7f4ded9ca56468eaa42c7fde8217f70a6ab7ffbea7R122

Worth adding a comment here too?

**Comment by neilkakkar** [comment]
yolo :)

**Pull request merged**
