### PR TITLE
feat(funnels): Add tooltip to new funnel viz

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

The tooltip was the last missing piece needed for releasing the new, much more readable funnels.

## Changes

The tooltip is here:
Screen Shot 2022-04-28 at 22 30 31

### CODE REVIEW

**Review by clarkus — APPROVED** [review]
Looks good. Do you want to include the affordance for "clicking to view persons"? I updated [figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8238%3A41103) to represent the latest.

**Review by mariusandra — APPROVED** [review]
Looks good. The only thing I found is that with multiple breakdown, the title was concat together:
image

This could also get the `::` that's in the table or a similar separator.

**Comment by mariusandra** [comment]
Found some of these though with breakdowns:
image

**Comment by Twixes** [comment]
Everything should be addressed now!

**Pull request merged**
