### PR TITLE
Insight card expandable details

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This implements an expandable "details" portion of `InsightCard`'s `InsightMeta`. It will allow users to quickly get an understanding on what the insight represents right there on the dashboard, or in saved insights' card view. [Design in Figma.](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6212%3A32693)

### CODE REVIEW

**Review by clarkus — CHANGES_REQUESTED** [review]
Can we align the "global" insight filters to the design a bit more? They're a separate design in figma, but they could even match the query filters for each series/step. My main goal is to summarize as much as possible in a small area, so reducing the pill height to align with the query above would be a nice to have. Thoughts?

**Comment by clarkus** [comment]
BTW this looks great! Nice job!

**Comment by clarkus** [comment]
Updated to include quick change that aligns with the step / graph filters. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=6212:32693#144888456

Screen Shot 2022-01-26 at 12 53 42 PM

**Comment by Twixes** [comment]
Sure @clarkus, updated:
Screen Shot 2022-01-27 at 14 51 22

**Review by clarkus — APPROVED** [review]

**Review by pauldambra — APPROVED** [review]
Screenshot 2022-01-28 at 09 46 25

Non-blocking... I expected clicking show details on a different insight would close details on one with details already shown. Not the worst thing since I can click hide if I want it hidden :)

**Comment by Twixes** [comment]
:+1: A possible use case for keeping multiple details open is comparing insights on the dashboard, so I'll run with it for now and see if users find it unintuitive.

**Pull request merged**
