### PR TITLE
fix: reduce toolbar bundle size by 60%

### PR DESCRIPTION
**Pull request by pauldambra**
Toolbar is 2.2MB of JS, that's an awful lot...

a production build shows half a meg of syntax highlighting

Screenshot 2024-02-04 at 20 00 12

* outputs a file that can be used to generate a view of the bundle at https://esbuild.github.io/analyze/ (that has awesome explanation of why a file is included when you click on things)
* also allows outputting a HTML file of the bundle locally NODE_ENV=production pnpm build && pnpm visualize-toolbar-bundle
* moves LemonMarkdown out of the LemonTextArea file so that a circular dependency out to TextCard and back doesn't affect LemonTextArea
* declares which files have sideeffects so that we can tree-shake LemonUI in the toolbar bundle
* and removing CodeSnippet for showing the current selector in the HTML element window
* and replaces any import of posthog-js with posthog-js-lite saving about 90kb
* and makes sure we don't use the datepicker which removes a few dependencies
* down by 60% at this point
* almost all remaining is react and antd

Screenshot 2024-02-17 at 22 07 16

### CODE REVIEW

**Comment by pauldambra** [comment]
@Twixes the toolbar is bundling more of lemon ui than I think it should... which means it's getting half a meg of formatting code it will never use. 

There don't seem to be any tools to investigate this other than thinking 😱 

Tagging you since it's lemon ui... and in case you've any suggestions on how to investigate 😊

**Comment by Twixes** [comment]
Oh wow, we definitely don't need a lot of this. @pauldambra By "investigate" do you mean finding out why this is not being tree-shaked? It definitely should be, but I have never looked into how we do tree-shaking at all, so would have to start with reading into that part of our ESBuild process 😅

**Comment by pauldambra** [comment]
if i edit the toolbar so that all it does is import lemontextarea then we still import the half meg of formatting code 👀 

Screenshot 2024-02-17 at 13 08 39

**Comment by marandaneto** [comment]
LGTM but I don't feel confident enough to YOLO, maybe someone else with more experience on the codebase + bundlers can take a look as well.

**Review by daibhin — APPROVED** [review]
Looks good.

Any idea where the remaining `antd.less` styling is coming from? Based on [this comment](https://github.com/PostHog/posthog/blob/master/frontend/src/toolbar/styles.scss#L3) it suggests we removed it from the toolbar at some point

**Comment by pauldambra** [comment]
> Any idea where the remaining antd.less styling is coming from? Based on [this comment](https://github.com/PostHog/posthog/blob/master/frontend/src/toolbar/styles.scss#L3) it suggests we removed it from the toolbar at some point

ah, no, is a dangling comment from me getting over excited in the past 🙈

**Comment by pauldambra** [comment]
I think in the tooltip component still?

We use lemon-ui, so while we're still using antd there then I think we're stuck...

**Comment by daibhin** [comment]
Another reason to get this PR in https://github.com/PostHog/posthog/pull/20160 💪

**Comment by pauldambra** [comment]
@joethreepwood in case you do changelog before wednesday all hands this one should definitely go in

**Pull request merged**
