### PR TITLE
Give the user better feedback when they click export events

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

It can take over seven seconds for the event download to begin when exporting events from the events UI

The only UI affordance is that the button changes to a colour to show it has been clicked. This was subtle enough I didn't sport it

Without altering how this button works so that a spinner can be swapped in this change disables the button for seven seconds so that we might have time to start the download before someone spams us with a second expensive request

## How did you test this code?

by running it locally

### CODE REVIEW

**Comment by mariusandra** [comment]
On the screencast, it feels like it's broken.

1. You click the button.
2. It changes its color (disables itself)
3. It changes the color back (undisables itself)
4. I still see "waiting for response..." in the browser's status bar
5. I guess some time later the download comes through.

So I guess this is better, but is there no way to actually spin until the file comes? StackOverflow [seems to think not really](https://stackoverflow.com/questions/1106377/detect-when-browser-receives-file-download)...  🤔

**Comment by pauldambra** [comment]
> On the screencast, it feels like it's broken.

Yeah, you can't get from the browser to the file system because security.

You'd need some kind of three-legged interaction with the server which feels like a lot of effort for little gain.

I don't know this is any better 🤷‍♀️

**Comment by mariusandra** [comment]
Tagging in @clarkus -> is this an improvement over what we have? 

I'm afraid users will click the button a second time once it stops spinning before the download starts, leading to some endless loop.

There are ways around the access issue as well. For example, the button could do a simple `api.get` request to a page that returns a URL that can be called when the download has been prepared. We show a spinner while this loads, and only then redirect to a page that should open instantly, e.g. a S3 export URL. Much more work obviously, but there's always a way

**Comment by clarkus** [comment]
Yeah this is an improvement for sure - it stops you from triggering multiple downloads. The one thing that's missing is feedback - there isn't any thing that obviously says "export in progress" or that notifies you that "export is done", or if there is an error that the "export failed". Toast notifications would be good for this. Some small-form inline-spinner to show progress could also add value. Thoughts? Happy to draw some ideas for this as it relates to the ongoing table work.

**Comment by clarkus** [comment]
Posted an idea to https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=4956:28296#125255192. This shows both action states - when an export is started, the icon would swap to the inline loading indicator and would continue to display until the export is completed. Likewise the label would change to reiterate that the process is running and the element would be disabled / have it's href / target removed. 

Screen Shot 2021-11-16 at 10 11 01 AM

**Comment by mariusandra** [comment]
That design is an obvious improvement over what we have, however the technical limitation right now is that we can't track the "exporting" time. It's set at a [fair guess](https://xkcd.com/221/) of 7 seconds right now, which is too short even on the screencast itself. It would be quite a bit of work to give us the ability to track the export durations and show an accurate spinner. That's not *really* the priority this sprint, so... 🤷.

One alternative could be to start the spinner `onclick`, and stop it `onblur`, hopefully when the user sees the file and clicks on it.

**Comment by clarkus** [comment]
If we can't ensure it's going to show at the appropriate times, then I think it might do more harm than good. Maybe on click we prompt with a toast saying the export has started and should finish soon. That would take the onus off the button to communicate status. If the prompt needs to be higher priority we might consider a dialog or something else more prominent.

**Comment by pauldambra** [comment]
@clarkus I love the toast suggestion. Great way to give the user a better journey without taking on the complexity of "full fat downloads". 🙌 

Will update this PR to use that mechanism instead of disabling the button

**Review by clarkus — CHANGES_REQUESTED** [review]
Saw that I had a lingering review due here - let me know when the toast version is available and we should be good to go for another review. 🍞

**Comment by pauldambra** [comment]
download-toast

@clarkus  Export is slow to start on my machine so the toast closes before the download has started. 

Maybe it should be "Your download is being prepared." with "It can be slow to start. Thanks for being patient" (I've no idea what our tone of voice is :))

**Review by clarkus — APPROVED** [review]
This looks good to me. We don't have any tone / voice guidelines documented that I know of. We have some more tactical writing style guidelines at https://posthog.com/handbook/company/communication#writing-style. For this specific case, I think what you have works. It'd almost be better without the secondary text, but I don't think it's doing any harm. I do think the toast does a great job taking over comms for the button. :shipit:

**Pull request merged**
