### PR TITLE
Chunk session recording events

### LINKED ISSUE #3510: Some teams are not getting any type 2 session recording events
## Bug description

Team 1810 on app has the following session recording events. Note there are no type 2 events. 
image

Same reports for team 1377.

See [this internal slack link](https://posthogusers.slack.com/archives/G01JXEDAL22/p1614364403009200?thread_ts=1614305979.000600&cid=G01JXEDAL22) for the rest of the context.

## Expected behavior

Type 2 events (entire dom dumps) should get sent correctly

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### LINKED ISSUE #3632: Chunking session recording events
## Is your feature request related to a problem?

Currently session recordings reach us via the following pipeline:
1. posthog-js captures a bunch of events, compresses and sends to /s endpoint
2. we decompress these events, put each into celery/kafka as a task
3. In the other end plugin server reads these events and puts them into the appropriate database

To retrieve a list of recordings, we:
4. Fetch all session recording $session_ids in time range
5. Filter out those without a full page snapshot
6. Display the list

We are currently missing some full snapshot events regularly from step 2 because of kafka message size limits.

## Describe the solution you'd like

Use compression and chunking to make sure we don't drop any events.

Some requirements:
1. If we're dealing with session recording events, compress, chunk and send all the events instead of individually. 
1. The chunked data needs to contain information whether the event is a full_snapshot event or not
1. Handle one row containing many session recording events in backend.
1. Skip decompression when it's not needed. Instead, include information via the URL that this is a session recording request and if it contains a full snapshot.

Not sure if the last point is achievable due to api tokens, etc being within the compressed payload.

## Additional context

https://github.com/PostHog/posthog/pull/3566/files got started with this process.

### PR DESCRIPTION
**Pull request by macobo**
Closes https://github.com/PostHog/posthog/issues/3632, Closes https://github.com/PostHog/posthog/issues/3510 and replaces https://github.com/PostHog/posthog/pull/3566/files

This should make it possible to ingest large full snapshot events which currently get silently dropped due to kafka size limits.

Base64 is used to compress the data for serialization purposes.

pytest.mock is used for clean patching methods

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Review by mariusandra — COMMENTED** [review]
Hey, I didn't run it (yet), but got two related questions from just reading the code:

1. "assumption: all events within a request have same session_id". I'm not sure if I'd be brave enough to make this assumption. Right now, if a session recording event comes in through posthog-js, this assumption will be true. However it's not given that this is how we'll always get events into capture.py. What if there's someone who's using the bigquery plugin to export all their events... and later imports all of them via some bulk import or API? We can't guarantee any future developments will respect this assumption. 

2. What if you re-capture a compressed snapshot? Similar case to the plugin scenario, what if these compressed snapshots are somehow re-ingested, either via a bulk export or some other plugin-based scenario. Will they all get compressed again and will the frontend know how to handle them?

3. Finally, should we add some postgres indices for the `JSONExtractBool(snapshot_data, 'has_full_snapshot'))`, etc columns?

**Comment by macobo** [comment]
Re 1, Good note. I generally don't think it's worth being super defensive in the code here for hypothetical usecases, but this is easy enough to add. 

Tangent:  in general our event data is not symmetrical enough to allow for easy re-ingestion. Some fields are added in or removed from a valid request - the ip url parameter, token, project_id and others. IMO this is a small fail in our API design.

This applies even more so to session recordings - the data format here is more volatile and likely to change over time, and will look completely different for e.g. an android session recording library.

Re 2 - Not quite sure what you mean re `What if you re-capture a compressed snapshot`? Do you mean that someone manages to pollute the database with junk data by duplicating rows somehow? Note that it's not possible to send the payloads generated here to capture again - it would re-chunk them in a different way in all likelihood. Also, deduping the underlying snapshots is mostly handled in rrweb.

Re 3 - This requires some actual measurements to determine whether the index would do anything here. There's already a index `"posthog_ses_team_id_0409c4_idx" btree (team_id, "timestamp")` which I think will carry most of the weight here. Will add a follow-up task for this.

**Comment by macobo** [comment]
Re 3: I now think the index would do nothing since the query does require looking through all session recording events in timerange as it returns things like start/end/duration. :)

**Comment by mariusandra** [comment]
Re tangent: totally agreed. For added side effects (documenting on the fly here), the plugin server also adds `$set_once: {'initial_utm_source': 'mailchimp'}` if it detects a `utm_source` parameter for example. This is added during ingestion (`captureEE`), so the last plugin won't see it, but it'll show up in the database. 

Re Re 2: I mean making a plugin that effectively does `if event == $snapshot then posthog.capture(the event itself)` (ignore the obvious recursive race condition)... and probably not directly, but through some import/export script. I think a block to prevent rechunking is easy enough to add and should be worth it. Being defensive again, but these usecases seem not that unlikely with a growing userbase and customisable open source code...

**Review by mariusandra — APPROVED** [review]
LGTM!

**Pull request merged**
