### PR TITLE
feat: console log for session recordings

### PR DESCRIPTION
**Pull request by timgl**
## Changes

- Adds session console recording
- Upgrades rrweb (had to because console recorder was only added in a newer version) < worth having a look at what this implies for us
- Super simple interface. You can click and the player will scroll to the right spot. Will need some work on the interface, specifically I couldn't get dynamic height rows to work.
- Safe to merge as is, but for the console recording to work we'll need to update posthog-js with this PR

image

*Stay up-to-date with our [coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

QA: 
- Check out the posthog-js library, run both `yarn` and `python -m SimpleHTTPServer 8080`
- Check out `add-console-log-recording`
- Navigate to http://127.0.0.1:8080/playground/flags/demo.html and click around
- Go to local posthog, add `session-recording-console` feature flag
- Go to recordings and select 'console', see console log coming in

### CODE REVIEW

**Comment by timgl** [comment]
@clarkus I think this would be a cool feature to push for the launch week. I feel strongly that the console log itself should look as close to the browser console log as possible to give people the sense that they are right there with the user. Any thoughts on the positioning and tabs etc?

**Comment by clarkus** [comment]
> @clarkus I think this would be a cool feature to push for the launch week. I feel strongly that the console log itself should look as close to the browser console log as possible to give people the sense that they are right there with the user. Any thoughts on the positioning and tabs etc?

Browser consoles can be pretty dynamic - they're resizable, can be repositioned, etc. The items logged tend to be verbose and require a good bit of space to fully describe the event in a readable way. For now, if we're just doing a simple console log, this layout is probably fine. If / when we add more capabilities, I'd want us to step back a bit and identify the problems we're solving and create a solution specifically for that. The current event log is pretty basic and really just optimized to show our simple event syntax. 

Are you wanting me to spend some time cleaning this up to align it with the rest of the app, or were your questions purely about placement?

**Comment by timgl** [comment]
> The current event log is pretty basic and really just optimized to show our simple event syntax.

Not sure if you noticed the logs in the screenshot up top? It does look quite different from the event log, but much more similar to how the browser shows it

> Are you wanting me to spend some time cleaning this up to align it with the rest of the app, or were your questions purely about placement?

Up to you! This will be a feature that people need to enable in their own code (for now) so I expect initial usage to not be massive.

**Comment by clarkus** [comment]
Based on that information I think we could just go with what you have for now.

**Comment by rcmarron** [comment]
Quick todo list here:

- [ ] Get it working with multiple `window_ids`. Long term, this is going to be tricky. Today, a recording combines the video from multiple windows into a single view, and it hides this complexity from the user. But if users are going to use this to debug, we can't do that. For the MVP, we're gonna just mix the logs from multiple windows.
- [ ] Fix issue with first log not appearing
- [ ] Message for users that don't have any logs to set the `ph-js` config
- [ ] Figure out options for multiple line logs (likely means either no virtualization, no autoscroll, or no variable height)

**Comment by rcmarron** [comment]
Just took a pass at this PR. I think it's in a good state for a beta/mvp feature.

Did the following:
* Moved logic into the kea logic
* Got it working with multiple `window_id` cases
* Handle a few more cases for trace formats
* Added a state for "logs loading"

image

* Added a state for "No logs on recording"

image

* Variable height log lines that wrap around the trace statement
* Added a "feedback" prompt
* Instrumentation
* Added some tests

Here's a video showing some of it off:

https://user-images.githubusercontent.com/4813045/158484652-fa51a35a-d0a1-4285-aa65-8b399227ea82.mov



A couple obvious missing features:
* It should indicate the current event in the same way events do
* If you switch to the console tab, the logs should be put on the seekbar instead of events
* It only supports 150 log events (because it doesn't do virtualization to support variable line height)
* The logs from multiple windows being merge into a single view without indication stinks
* Format json in a better way
* Show logs before the entire thing recording is loaded (this is hard because of different windows buffering in a non-linear way...)

**Review by rcmarron — APPROVED** [review]
Looks good to me hah, but probably best to some other eyes on it now

@timgl it won't let me add you as a reviewer

**Review by clarkus — COMMENTED** [review]
Nice changes, @rcmarron. I like that you applied the same empty state from project homepage here because I would've done the same thing. I love it when we reuse components. 

- I like how you indicated the 150 item limit, but I think we could potentially reduce frustration if we communicate it more prominently. I think we can retain what you have, but also add a tooltip to the console tab that communicates the limit. We typically do this with an info icon adjacent to the tab label. On hover we'd show a tooltip with the same limit warning you have below. 
- I saw that you have some feedback components in your video. Love the idea and placement, but wondering if we can change the button labels and determine a cadence for how often that's shown. We change this feature pretty often (so far) and this kind of feedback mechanism might work well on some recurring basis. However that works would inform the button labels to make them a bit more clear. I really like the concept because it feels like a really reusable way to poll for feedback in the context of a feature. I think this could be taken a lot farther, but realize it's outside the scope of this issue. Short term I think the key change would be allowing a user a quick action to provide us detailed feedback. Once acted on, whether feedback is given or it is dismissed, we could hide the area so that the user regains the full height of the container to view logs / events.

**Comment by rcmarron** [comment]
Thanks @clarkus 

> We typically do this with an info icon adjacent to the tab label. On hover we'd show a tooltip with the same limit warning you have below.

Love it, just added it

image

> I saw that you have some feedback components in your video. Love the idea and placement, but wondering if we can change the button labels and determine a cadence for how often that's shown.

That definitely makes sense. I made it as a one-off here (mainly with the idea that it could give a signal for how much we should invest in debugging features), but it totally makes sense as a component with logic around when it re-appears. I have to run for the evening, but I'll take a stab moving it into a component with re-appearing logic tomorrow morning. I think it should be pretty easy.

**Comment by rcmarron** [comment]
>  I'll take a stab moving it into a component with re-appearing logic tomorrow morning. I think it should be pretty easy.

On second thought, I think this new component should be in a different PR (it's a bit bigger than i thought). Just pushed some copy changes to the current feedback prompt, and this is still behind a FF, so no harm in merging this PR and following up with that one.

image

**Comment by timgl** [comment]
@rcmarron Changing the default state to this: 
image

Otherwise looks good. Feel free to merge if you're happy with above

**Comment by rcmarron** [comment]
Great, thanks! merging.

One non-blocking thought on the updated "no logs" state: People are going to see this state if the feature is enabled, but there just aren't logs (which probably isn't that uncommon for some companies that try not to use logs). So I was thinking "setting the config" is more of a secondary action on the screen. Otherwise, I'm a bit nervous that people are going to think they have it mis-configured, when in reality, they're fine.

Curious if you have thoughts on this @timgl @clarkus

**Comment by timgl** [comment]
> One non-blocking thought on the updated "no logs" state: People are going to see this state if the feature is enabled, but there just aren't logs (which probably isn't that uncommon for some companies that try not to use logs). So I was thinking "setting the config" is more of a secondary action on the screen. Otherwise, I'm a bit nervous that people are going to think they have it mis-configured, when in reality, they're fine.

Ah yes of course, confused myself. In that case I think let's just keep it as it was, I'll revert that commit now.

**Pull request merged**
