### PR TITLE
feat(web-analytics): Support opening web analytics queries as either a trend or modal

### PR DESCRIPTION
**Pull request by robbie-c**
## Problem

Supercedes https://github.com/PostHog/posthog/pull/20032

## Changes

https://github.com/PostHog/posthog/assets/2056078/943ad2ba-2a79-4e4a-b058-e80e1bf9292d

Ideally we would open all queries as a new insight, but there's some kinks to iron out before we can do that, so just open in a modal for now.

This is what would happen if we tried to open these as an insight:
Screenshot 2024-02-06 at 07 06 49
It'd be pretty useful to fix this but I'd rather do it in a new PR

## How did you test this code?
Manually

### CODE REVIEW

**Comment by mariusandra** [comment]
Had a quick look and made the insights openable (didn't change links), but now there's this 🤪

**Comment by robbie-c** [comment]
Ah I probably need to remove where I set embedded: true

**Comment by robbie-c** [comment]
Fixed (if tests pass)

**Comment by mariusandra** [comment]
Definitely works better now 👍. But now the next question: should some charts open in a modal, and others as a new insight?

**Comment by robbie-c** [comment]
Correct - the Trends open in a new insight, and the web analytics specific queries open in a modal, and there'll be a PR in the future to make opening them as an insight work better (I imagine I'll do this when I also properly implement table features like sorting by columns and offsets)

**Comment by mariusandra** [comment]
I'd find that confusing as a user, as there's nothing inherently obvious to explain the difference in behaviour between one chart to the next. From the users's perspective, they're all web analytics, but some can only be viewed, while the others can be e.g. exported as png.

Why not add both buttons?

image

 Or then, my preferred option, just the "new insight" one. 😅

**Comment by robbie-c** [comment]
Some of them don't work yet, this was Top Channels opened as an insight.

Screenshot 2024-02-06 at 13 39 57

I'd rather merge this so that the ones that support it can be opened in an insight and played around with, and the ones that don't work as a new insight (yet) can still be opened as a modal to view more rows at once.

**Review by mariusandra — APPROVED** [review]
Ah, I didn't test deep enough it seems. Good for me then 👍

**Pull request merged**
