### PR TITLE
Fix use 'and' for properties filters

### PR DESCRIPTION
**Pull request by timgl**
I was very confused when I tried filtering the trends page by 2 properties...

### CODE REVIEW

**Comment by timgl** [comment]
@Tannergoods Would you mind QA'ing?

**Comment by Tannergoods** [comment]
It broke when I followed the steps from #602, but only with specific combinations. I can't break it when only selecting events in /trends.

It does break if I have a combination of actions and events but will not break if you select something other than the first option in the dropdown (or if there is only 1 option in dropdown)

Posthog

I'm not sure that is the scope for the above but I can't get to 'and' in some circumstances.

Using only events it is fine to use a combination of 'and' property filters. 

If you use actions using a combination of 'and' property filters will break it.

I think I have gone through most varieties of selections but it is a weird bug

**Comment by timgl** [comment]
I wasn't originally planning on fixing #602 in this PR but I have done that now. To recap, this PR now
- Fixes #602 
- Makes sure you if you have multiple properties they "AND" rather than "OR"

**Comment by Tannergoods** [comment]
Have re QA's sorry for pr creep but both bits work!

**Comment by timgl** [comment]
Sorry more PR creep. I fixed the way we display actions/events in the graph, even if that action/event has no data in the given timeframe
image

It'll only give the "We couldn't find any matching events" if _all_ actions/events selected have no data. If one of them does, it'll look like above. This should cut down on confusion.

**Comment by Tannergoods** [comment]
This works in the way it is expected now. Although one thing I am confused with that I don't consider a bug more in the way we display information:

When there is no data at all it shows in the way I would expect it to but once I select all time (with a daily interval) it shows only the data for today (because that is the only time the data fitted the properties I'm filtering by) 

Posthog

Posthog

I don't think it prevents this from being merged though

**Comment by timgl** [comment]
Hm yeah because in that case "all time" is just today.. It is not pretty even though it is correct. We could come up with something better but not sure what it should look like.

I'll merge now

**Pull request merged**
