### PR TITLE
Limit to one organization in private instances

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Until we institute better restrictions to prevent unauthorized users from using up private instances' resources, we should disallow creating more than one organization on such deployments.

### CODE REVIEW

**Review by paolodamico — CHANGES_REQUESTED** [review]
Some comments. Seems like this PR is only updating tests, but there's already a test that partially covers the case described (`test_at_most_one_organization_on_noncloud`).

The problem I see with the test is that:
1. It doesn't cover all cases. Where we actually want to focus is making sure you can't create orgs accidentally by completing social signup or using the normal `/signup` endpoint. _(Note: I believe the second one is partially covered on the front-end because there's a redirect)_.
2. I actually think we would want to achieve the opposite of this. If an authorized administrator (with valid credentials) wants to create a new organization, they should be allowed (perhaps only validating licenses / billing stuff). We actually only want to prevent case 1 (from unauthenticated persons).

**Comment by Twixes** [comment]
Fair points! So how about instead of disallowing multiple orgs on self-hosted, still allowing existing users to create them, but only preventing users other than the initial one from signing up not-from-an-invite?

**Comment by timgl** [comment]
We should not allow multiple orgs on self hosted unless they have a license.

**Comment by Twixes** [comment]
Yes, that's always been the case and will continue to be @timgl

**Comment by paolodamico** [comment]
> Fair points! So how about instead of disallowing multiple orgs on self-hosted, still allowing existing users to create them, but only preventing users other than the initial one from signing up not-from-an-invite?

This plus the billing thing you mentioned makes total sense, agreed!

**Comment by Twixes** [comment]
This seems to have been achieved by switching to `OrganizationSocialSignupViewset` (`permission_classes = (UninitiatedOrCloudOnly,)`) in #2734. #3353 should completely remove old improper behavior.

**Pull request closed without merging**
