### PR TITLE
feat(correlation): add multiselect for property names

### PR DESCRIPTION
**Pull request by hazzadous**
Previously we had a simple text input box that was splitting the input
to get a list of property names. This doesn't give the greatest user
experience.

Now we have a simple select box that includes:

 1. search filtering for options
 2. multiselecting options
 3. a select $all, although this is pretty poorly implemented at the
    moment, for instance you can select $all, at the same time as
    selecting a subset of properties.

This follows the design at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4200%3A30715

Storybook for this found at https://61260360a8e859003a7c138b-faphaelhpj.chromatic.com/?path=/story/posthog-components-propertynamesselect--empty-with-options

### CODE REVIEW

**Comment by mariusandra** [comment]
Didn't review, just flyby commenting:
- Would be love to also see a gif or mp4 of the changes inside the PR description, even if there's a storybook that can be checked. A lot of us use [gifox](https://gifox.io/) for this
- The storybook url is great, but would be better to have a link to the new page. Had to look up what to look up via the changed files.

**Comment by hazzadous** [comment]
> * Would be love to also see a gif or mp4 of the changes inside the PR description, even if there's a storybook that can be checked. A lot of us use [gifox](https://gifox.io/) for this

For sure yup will add a gif

> * The storybook url is great, but would be better to have a link to the new page. Had to look up what to look up via the changed file

Yeah that was laziness on my part, will update

**Comment by hazzadous** [comment]
I'll also update this according to @clarkus [updated designs](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4160%3A26978)

**Comment by clarkus** [comment]
The latest component design is at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4200%3A30715.

**Comment by hazzadous** [comment]
@clarkus I've updated according to new designs, you can have a play with it at https://61260360a8e859003a7c138b-gerrxfqhjv.chromatic.com/?path=/story/posthog-components-propertynamesselect--empty-with-options

Let me know if there's anything missing.

**Review by clarkus — CHANGES_REQUESTED** [review]
Looking good! I noticed a couple of things we could update to better match the designs:

- Keyword highlighting with emphasis - when there is a keyword entered into the search, highlight that keyword pattern in the results with bold emphasis. This should also apply to the "no matches" state... generally whenever the keyword entered appears in the list of results, bold it. 
- The indeterminate state for the checkbox is kind of wonky in storybook. I never got it to render correctly for some reason. It seems to be triggering at the right events though. It's purely a visual thing I think. 
- Add a clear action to the search input - just lets you empty that input quickly
- The blue border on the input is an active state. When it isn't active it should be our default border color #d9d9d9

**Comment by hazzadous** [comment]
@clarkus have made updates:

1. include clear search button
2. added highlighting of search results

I wasn't sure about the indeterminate state, it seems to function as I would expect but perhaps you are using a diff browser?

For the blue border also. I'll include a gif of the functionality

**Comment by clarkus** [comment]
> @clarkus have made updates:
> 
> 1. include clear search button
> 2. added highlighting of search results
> 
> I wasn't sure about the indeterminate state, it seems to function as I would expect but perhaps you are using a diff browser?
> 
> For the blue border also. I'll include a gif of the functionality

@hazzadous I personally have never seen that particular indeterminate state. I think we should use something more 

I tried this out in storybook and locally in multiple browsers. The indeterminate state isn't quite right. It should be a minus inside the bounded area of the checkbox. Here's a quick component guide that demonstrates how these should render and apply. 
 
Screen Shot 2021-10-19 at 9 11 07 AM

**Comment by hazzadous** [comment]
@clarkus is that component guide in figma by and chance? if so would be great to create a corresponding component lib in react. I'm just using the default antd intermediate which is probably why it looks a bit stupid?

Anyway, I can add in the SVG from figma, unless there's a font somewhere that we should use?

**Comment by clarkus** [comment]
@hazzadous just added it https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=1764%3A522 - the checkboxes should be exportable as SVGs. Also sending them to you via slack directly.

**Comment by hazzadous** [comment]
> @hazzadous just added it https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=1764%3A522 - the checkboxes should be exportable as SVGs. Also sending them to you via slack directly.

amazing

**Comment by neilkakkar** [comment]
There seems to be a mismatch between selection, and what request is sent - seems to be delayed by one, so the previous selection is sent in the current request:

**Comment by hazzadous** [comment]
@guidoiaquinti re. the SonarCloud checks, I feel like "duplicate lines on new code" isn't a great rule, as often I like to avoid abstracting until it is clearer what they should be. Is there a way we can disable it?

At least for tests?

Do you know if there's a way to have the feedback as github check annotations as well so it's more visible?

**Comment by hazzadous** [comment]
@guidoiaquinti is there also some overlap with the other tooling we have e.g. eslint etc. I would prefer to have eslint etc config updated instead of SonarCube tbh, as makes devs in these areas work more autonomous

**Comment by hazzadous** [comment]
@clarkus I'm going to handle the remaining UI changes in a separate PR. This one is growing quite large!

**Comment by neilkakkar** [comment]
huh, that gif seems to have become corrupt. LEt me try a new one: .. nope, also black.

Anyway, **one final thing**: when I click on the selector box without opening, to select or deselect all, nothing happens. I think when all values are selected, we should be sending a request as well?

**Comment by guidoiaquinti** [comment]
> @guidoiaquinti re. the SonarCloud checks, I feel like “duplicate lines on new code” isn’t a great rule, as often I like to avoid abstracting until it is clearer what they should be. Is there a way we can disable it?

Apologise for the noise (especially if you think the rule shouldn’t apply to us)! I’ve disabled the rule globally (see the new code quality config [here](https://sonarcloud.io/organizations/posthog/quality_gates/show/51278)).

> Do you know if there’s a way to have the feedback as github check annotations as well so it’s more visible?

Probably there is, let me take a look 👀  

> @guidoiaquinti is there also some overlap with the other tooling we have e.g. eslint etc. I would prefer to have eslint etc config updated instead of SonarCube tbh, as makes devs in these areas work more autonomous

Let’s disable all the checks you think are unnecessary/duplicated. I’ve enabled SonarCloud with the default config, but it might require some config tweaking for our use case.

Let me know what do you think about it 🙇

**Comment by hazzadous** [comment]
@guidoiaquinti looking through the [metric list](https://docs.sonarqube.org/latest/user-guide/metric-definitions/):

 * Coverage - there's one part display and one part actually calculation here that generates the coverage xml. For the display side I'd say just use something like codecov or coveralls, which provide integration with github checks. We already have codecov setup. For generation, pytest is providing the xml that we send to codecov.  Jest has support for this also although we've not configured I don't think.
 * Complexity is cyclomatic complexity, which flake8 can do for us in python. There is also the `cognitive_complexity` in sonarcube which I'm not sure what that is, it's a 404. There is also https://eslint.org/docs/rules/complexity for eslint.
 * Maintainability look like something we'd want as part of flake8 or eslint
 * Reliability looks like things that should be part of flake8 or eslint from the list of bugs here: https://sonarcloud.io/project/issues?id=PostHog_posthog&resolved=false&types=BUG
 * Security maybe is useful

I think these sonar metrics are something we could look at to see trends over longer periods of time. For the PR checks, I'd suggest that keeping the tooling/checks local to the dev team and code is a better experience. Sonar is good for box ticking, but there are probably more impactful things we can do like looking at issues we want to remove/avoid and putting in bespoke solutions for them.

**Comment by guidoiaquinti** [comment]
> @guidoiaquinti looking through the [metric list](https://docs.sonarqube.org/latest/user-guide/metric-definitions/):
> 
> * Coverage - there's one part display and one part actually calculation here that generates the coverage xml. For the display side I'd say just use something like codecov or coveralls, which provide integration with github checks. We already have codecov setup. For generation, pytest is providing the xml that we send to codecov.  Jest has support for this also although we've not configured I don't think.
> * Complexity is cyclomatic complexity, which flake8 can do for us in python. There is also the `cognitive_complexity` in sonarcube which I'm not sure what that is, it's a 404. There is also https://eslint.org/docs/rules/complexity for eslint.
> * Maintainability look like something we'd want as part of flake8 or eslint
> * Reliability looks like things that should be part of flake8 or eslint from the list of bugs here: https://sonarcloud.io/project/issues?id=PostHog_posthog&resolved=false&types=BUG
> * Security maybe is useful
> 
> I think these sonar metrics are something we could look at to see trends over longer periods of time. For the PR checks, I'd suggest that keeping the tooling/checks local to the dev team and code is a better experience. Sonar is good for box ticking, but there are probably more impactful things we can do like looking at issues we want to remove/avoid and putting in bespoke solutions for them.

I think configuring, maintaining and keeping up-to-date CI checks for code coverage, complexity, maintainability, reliability and security for all the languages we use (currently in this repo I see: Python, Typescript, Javascript and SCSS) is significantly higher than configuring a tool like SonarCloud.

Anyway, despite I kindly disagree with your proposal I’m going to disable all the SonarCloud checks != security related till we agree on how to move forward.

Thank a lot for your feedback and patience 🙇

**Comment by hazzadous** [comment]
> I think configuring, maintaining and keeping up-to-date CI checks for code coverage, complexity, maintainability, reliability and security for all the languages we use (currently in this repo I see: Python, Typescript, Javascript and SCSS) is significantly higher than configuring a tool like SonarCloud.
> 
> Anyway, despite I kindly disagree with your proposal I’m going to disable all the SonarCloud checks != security related till we agree on how to move forward.
> 
> Thank a lot for your feedback and patience 🙇

Appreciate your kind disagreement 🙏 

If we enable again, I would love to make sure that there is something to integrate into local development as well. I see there is a vs code plugin. Re. the keeping CI checks up to date, I think the key here is that these same CI tools are also run by every developer locally as well, and the developer can update a tweak these things and take ownership of this.

Perhaps one straight forward guidance we could give is state what we think defines good code, i.e. low cyclomatic complexity, automated testing of code etc.

**Review by neilkakkar — APPROVED** [review]

**Review by mariusandra — COMMENTED** [review]
Hmm.... well, since you asked for it 😆, this PR flies in the face of many coding practices we've been trying to adhere to, so 🤔. I'd change things.

I also found one bug. Type for example `(` in the searchbox. It shouldn't execute untrusted input as regex?.

I've been hard at work pushing people to adopt a data-first mindset in describing the frontend. In short: 1) First make sure all your data passes through a logic and works well, and 2) only then develop a component that takes the data from the logic and renders accordingly. 3) Finally avoid (almost) all useState and useEffect calls, as those usually mean you're manipulating data inside a React component, and have inefficient rendering loops. E.g. an useEffect that calls a kea action whenever a useState value changes. This causes multiple renders, and the data could usually have flown in a simpler way with less complexity.

This is the first thing I thought about when I saw this component. 

For me the biggest offender is `usePersonProperies` (typo, btw). Please replace it with:

```ts
const { personProperties } = useValues(personPropertiesModel)
```

This gets the same data from an existing source, and updates it everywhere on the page if this source changes. 

I'd also avoid all those other custom hooks, and just have a logic controlling the component, similar to how the taxonomic property filter works. This clean separation between data and template will make this code so much cleaner to look at.

I'm also totally willing to discuss this over a call, just grab a slot.

**Comment by hazzadous** [comment]
> I'm also totally willing to discuss this over a call, just grab a slot.

Cool, I've put in a little session

**Pull request merged**
