### PR TITLE
fix: Alignment of verify installation in onboarding

### PR DESCRIPTION
**Pull request by xrdt**
## Before
Screenshot 2024-06-05 at 10 53 53 AM

## After
Screenshot 2024-06-05 at 10 53 35 AM

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by xrdt** [comment]
Sorry, not really sure what you mean. Are you saying that the `installation complete` block should be center aligned with the text in the continue button. That's doable with some more CSS. I just felt that the existing view looked weird because the continue button wasn't at the bottom of the whole onboarding block.

**Comment by raquelmsmith** [comment]
I agree it looks kind of strange but I did consider this when building it and tried a few different locations and ended up with the existing one. Did you see what it looks like when there is the "Verify installation" button - ie we haven't received events yet? I think when I tried that I didn't like the look of the two buttons next to each other. 

But, to answer your question, yes - the text in the button should align with the "Installation complete" text. That's what will make it look visually aligned.

**Comment by xrdt** [comment]
Yeah, I saw the button and thought it looked fine. Not having the continue button be aligned with the bottom of the block bothers me much more. 

One other solution is to replace the button with a function that polls every n seconds or so to see if events have been received. That way, we'd just have text that switches between "waiting for events..." and "installation complete!" / "events received!". Sentry does this and has a nice radar animation on the red dot (you can see this by going to the profiling tab, choosing an environment that's not billing or posthog, and clicking "set up now" to open the side panel. 


Screenshot 2024-06-07 at 9 40 49 AM

**Comment by zlwaterfield** [comment]
Closing this PR because I don't this it improves the UI.

**Pull request closed without merging**
