### PR TITLE
WIP | Add pre-commit

### PR DESCRIPTION
**Pull request by Pacu2**
Adding simple pre-commit as discussed in https://github.com/PostHog/posthog/pull/660
Unfortunately, darker does not support pre-commit yet but opened a related pull request to change it in https://github.com/akaihola/darker/pull/2

To enable pre-commit one needs simply:
1. `python -m pip install -r requirements/dev.txt`
2. `pre-commit install` 

this PR consists of 3 commits:
1. requirements update
2. pre-commit configuration
3. fix for all trailing whitespace/incorrect end of file lines generated by the pre-commit

### CODE REVIEW

**Comment by SanketDG** [comment]
This looks like a great start!

Would you consider using darker given it's obscure enough?

I am still on the `black` bandwagon and I can still believe we can do it right with what I said in https://github.com/PostHog/posthog/pull/660#issuecomment-619423015 albeit with a few blockers here and there.

Also it looks like `pip-tools` is being used and not used (there is an external requirements.txt file)

**Comment by timgl** [comment]
Thanks for doing this.

This does add _another_ way of doing precommits, we already use husky for JS and I don't think they play nicely together. I personally also prefer how Husky just adds the formatted code to your commit, rather than failing and having to manually add the code back. The other nice thing is it 'just works', without manually having to install something.

**Comment by SanketDG** [comment]
@timgl Yeah, `pre-commit` does the same. it matters more what tool you are using (prettier/black that autoformats vs something else that just reports and exits)

**Comment by Pacu2** [comment]
@timgl Husky requires a package manager, and NodeJS to run hooks. This way, backend engineers would need to set up (and maintain) the frontend ecosystem. 

Pre-commit, on the other side, just works. It supports a whole variety of scripts, no matter the programming language they use.

Not sure how to use backend-oriented hooks with Husky, however, pre-commit supports several frontend-oriented ones, not to mention eslint, tslint, prettier...

**Comment by timgl** [comment]
Happy either way! I do think we should make sure this PR doesn't break frontend formatting.

**Comment by timgl** [comment]
@Pacu2 Hello again, sorry this has stalled for a while. Do you still have interest in picking this up?

**Comment by Pacu2** [comment]
@timgl sure will do in 24h

**Comment by timgl** [comment]
This was done in #1043, but really appreciate the work!

**Pull request closed without merging**
