### PR TITLE
Webpack upgrade

### PR DESCRIPTION
**Pull request by mariusandra**
I have upgraded from parcel to webpack. Please test if this works on Heroku.

Also, I'm not sure what to do with the "array.js" file that is included everywhere with `<script src='https://t.posthog.com/static/array.js'>`. It was committed in to the repository in the "dist" folder and I couldn't figure out how it gets made.

### CODE REVIEW

**Comment by timgl** [comment]
image
This is the error I'm seeing on Heroku. Not sure why?

Array.js I have historically just manually copied `http://github.com/posthog/posthog-js` -- it's the JS library. There's probably a better way but I don't think it's worth spending more than 15 minutes on.

**Comment by mariusandra** [comment]
Hi, that's strange. I added a potential fix to this, but heroku stills fails. Could you check if there's a new error this time?
Alternatively I can try later to deploy this to a new heroku instance to see how it performs...

**Comment by timgl** [comment]
Ah, [the reason for this is Heroku prunes everything in devDependencies.](https://stackoverflow.com/questions/39457619/webpack-not-found-deploying-to-heroku) 

should be fairly straightforward :)

**Comment by timgl** [comment]
Also could be worth checking whether the preview.Dockerfile and production.Dockerfile still work.

**Comment by mariusandra** [comment]
Hi, regarding the `devDependencies` issue, something weird is going on. The Heroku docs say

> By default, Heroku will install all dependencies listed in package.json under `dependencies` and `devDependencies`.
> 
> **After** running the __installation and build steps__ Heroku will strip out the packages declared under `devDependencies` before deploying the application.

Thus the dev dependencies *should* be there? But they're not.

I certainly don't want to merge the two objects in `frontend/package.json` to appease Heroku, as there's a simple reason why these lists are be kept separate.

You can override this default with `NPM_CONFIG_PRODUCTION` and/or `YARN_PRODUCTION`, but 
I don't see any set... thus I'd guess the defaults still apply. But they somehow don't.

The recommended "fix" accoding to the Heroku docs is to just run this:

```
heroku config:set NPM_CONFIG_PRODUCTION=false YARN_PRODUCTION=false
```

But!

There's something more happening here. It looks like the "install dependencies" and "build" steps are mangled up somewhat.

If you look at the Heroku log closely, you'll see that `yarn` is run twice. Once for the empty `posthog/package.json` file (under the "install dependencies" step) and once for `posthog/frontend/package.json` (under the "build" step).

I see that you're using `cacheDirectories` inside the root package.json to also cache the `frontend/node_modules` folder... so probably there's no performance penalty for running`yarn` twice, but it might still be causing issues with Heroku's default devDependencies custom code (for example the default ENV might be set in the "install deps" step, but not in the "build" step).

I'd actually recommend just moving the "package.json" file into the root folder of the project (`/posthog`), together with the other .dot/config/rc files from `frontend`. You'll have less problems in the future compared to keeping it in a subfolder. Perhaps this suggestion goes against django's recommendations (I've seen other apps that keep their package.json in "frontend"), but it sounds like a pragmatic choice for me. I hope you agree :).

That's what the latest commit in this branch does. And it seems that the deployment worked now!

**Comment by mariusandra** [comment]
The Dockerfiles however will need some tweaking to get this to work, as I see "cd frontend" written here and there. I'll update the PR shortly.

**Comment by mariusandra** [comment]
Hi again! I updated the two Dockerfiles. 

The `preview.Dockerfile` works well.

I'm almost confident `production.Dockerfile` works as well... except that it doesn't for me. I started it up and gave it a `DATABASE_URL` it should be able to talk to, but couldn't get anything to load. I just got timeouts when opening https://127.0.0.1:8000/ . I'm not sure what's the issue. Probably I'm still doing something wrong with the database access.

...

In addition to this I had to make one security-related change. Previously the dockerfiles were running `npm install`, which is fine.. but when developing we are using yarn and more specifically, we're saving the exact versions of the packages that are in use (and known to work) into `yarn.lock`.

Running `npm install` completely disregards this lockfile... and as a result we can't have deterministic builds. This will eventually lead to random issues... such as `randomLib` version `0.13.12` breaks everything while the "locked" version `0.13.5` worked fine. And we'll only know once people start testing the production builds on their fresh machines.

So I added steps to install (and later uninstall) yarn... and to use it to install the `node_modules` folder.

**Pull request merged**
