### PR TITLE
[proposal] suggestion for reducing runtimes

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- here's a step toward speeding up tests. By inserting the events per test together rather than as separate statements, we can possibly get a 30% reduction in runtime for tests
- we could get even more aggressive with it if we compile all the events into a single insert

Before:
Screen Shot 2021-10-28 at 3 25 38 PM
After:
Screen Shot 2021-10-28 at 3 25 19 PM

Before:
Screen Shot 2021-10-28 at 3 24 51 PM

After:
Screen Shot 2021-10-28 at 3 24 31 PM

## How did you test this code?

*Please describe.*
wrote tests

### CODE REVIEW

**Comment by hazzadous** [comment]
In case it's useful, this is the debug log output with timestamps: https://gist.github.com/hazzadous/56c0890a390cb16942f36a2d6a9086b8

**Comment by EDsCODE** [comment]
Almost 50% reduction in runtime locally for me

before:
Screen Shot 2021-11-03 at 10 59 44 PM

after:
Screen Shot 2021-11-03 at 10 59 53 PM

**Comment by hazzadous** [comment]
It feels like 5 minutes in CI is pretty good, do you think that's still too long?

In which jobs to be done do you expect this to help with? e.g. is this so we can run all the tests locally before we push? Or just so you can run a single suite whilst developing a bit faster.

I think probably one of the main cases I've had that a speedup would help is when I'm continuously running a single test. Perhaps I'm not running the whole related test suite because it's too slow, but with a 50% speedup I'd switch to doing that instead which might be useful.

It's really the CI that was killing me tbh, and the intricacies of having to have the local dev environment in a specific state to be able to run the tests. I'm not sure how others feel, but I think this isn't the most impactful change.

**Review by hazzadous — COMMENTED** [review]
I'm on the fence on this one tbh, but I guess we can at least provide `create_event`/`create_events` that should/can be used for new tests.

**Review by timgl — APPROVED** [review]
I think we should do this, even if just for paths which was a super slow set of tests. We don't have to rewrite all the other existing tests but for a select couple of tests that are slow it makes sense.

**Comment by EDsCODE** [comment]
> It feels like 5 minutes in CI is pretty good, do you think that's still too long?

I'm willing to shave any amount of time we can. We're only going to keep adding integration tests that will make the runtime longer. There's a handful of tests that we use which generate dozens of rows separately. Targeting those tests could be a smaller goal.

> Perhaps I'm not running the whole related test suite because it's too slow, but with a 50% speedup I'd switch to doing that instead which might be useful.

I don't usually run the whole test suite either but getting the CI to run faster is always useful imo

**Pull request merged**
