### PR TITLE
chore(plugin-server): bump node-rdkafka to 2.18.0 (librdkafka 2.3.0)

### PR DESCRIPTION
**Pull request by bretthoerner**
## Problem

librdkafka [had a release](https://github.com/confluentinc/librdkafka/releases/tag/v2.3.0) with a bunch of bugfixes. Now released as part of [Blizzard node-rdkafka](https://github.com/Blizzard/node-rdkafka/releases/tag/v2.18.0).

## Changes

Bump node-rdkafka, keeping the same patch.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by xvello — APPROVED** [review]
Cool! Did we open a new PR to sync cooperative balance upstream?

**Comment by xvello** [comment]
@bretthoerner `make e2e` on the rebased https://github.com/PostHog/node-rdkafka do not pass, did it pass before the rebase?

```
ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/xavier/git/node-rdkafka/e2e/admin.spec.js:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
make: *** [e2e] Error 1
```

I'd feel more confident if these were to properly pass.

**Comment by bretthoerner** [comment]
> @bretthoerner `make e2e` on the rebased https://github.com/PostHog/node-rdkafka do not pass, did it pass before the rebase?
> 
> ```
> ReferenceError: describe is not defined
>     at Object.<anonymous> (/Users/xavier/git/node-rdkafka/e2e/admin.spec.js:72:1)
>     at Module._compile (node:internal/modules/cjs/loader:1254:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
>     at Module.load (node:internal/modules/cjs/loader:1117:32)
>     at Module._load (node:internal/modules/cjs/loader:958:12)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
>     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
> make: *** [e2e] Error 1
> ```
> 
> I'd feel more confident if these were to properly pass.

Huh, I definitely misunderstood the existing Github action because I thought it ran this. It most likely failed before, too. I'll look into it.

**Comment by bretthoerner** [comment]
Ah OK, so a bunch of these already fail on upstream. The rest fail because this fork only pulls in the incremental rebalance patch, not other features such as `getMetadata` which the e2e tests use.

Since our tests pass, and this is just a librdkafka release change I feel like we should deploy it (but not Friday before I get on a plane).

**Pull request merged**
