### PR TITLE
feat(data-warehouse): extending posthog models UI

### PR DESCRIPTION
**Pull request by EDsCODE**
## Problem

- provide option to extend database fields

## Changes

https://github.com/PostHog/posthog/assets/13127476/6fb3ce9a-584e-48c7-9530-b563046ab7bd

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by EDsCODE** [comment]
TODO: address https://github.com/PostHog/posthog/pull/16877#pullrequestreview-1593166986

**Review by mariusandra — COMMENTED** [review]
This is looking very powerful 👍 

My only comment is really around terminology. When I click "Add field" I expect to be able to add custom SQL fields... not "foreign keys". Until we add support for any custom SQL fields, let's call this button something like "add link to a view"... or something more descriptive?

image

**Comment by EDsCODE** [comment]
@mariusandra Makes sense. I adjusted the button name and a bunch of the copy on the form!
Screenshot 2023-08-29 at 1 01 07 PM

Are there any blocking issues from getting this merged? Going to do more testing before 🚢 but lmk if there's concerns to address

**Review by mariusandra — APPROVED** [review]
Nothing blocking

**Pull request merged**
