### PR TITLE
Persisted flags for 1.29.0

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

In preparation for release 1.29.0 this PR sets the feature flags we're persisting for this release.
- In addition we clear a no longer necessary FF related to the legacy sessions page.

## How did you test this code?

Pending.

### CODE REVIEW

**Comment by mariusandra** [comment]
One higher level question.

We currently **merge** the persisted flags on top of flags normally returned by PostHog JS:

https://github.com/PostHog/posthog/blob/3832ec788bda276b12054da74c639f322d5fa8e2/frontend/src/lib/logic/featureFlagLogic.ts#L31

That means the persisted flags will always be there, but all other flags can be toggled on and off as we see fit.

If we now exclude a flag from the persisted list, say `3408-saved-insights`, and later roll it to 100% of users, everyone who's on 1.29.0 will automatically get a broken saved insights experience, as suddenly the flag will have been turned on for them.

I'd propose for removing this, and **only** having persisted flags in self-hosted instance, no variance from posthog-js possible.

**Comment by paolodamico** [comment]
One higher level answer @mariusandra, https://github.com/PostHog/posthog/pull/6442

**Review by mariusandra — APPROVED** [review]
LGTM. Won't merge yet in case you want any last minute changes.

**Comment by mariusandra** [comment]
Though, perhaps we should do more testing for `6050-remove-sessions` before releasing it? Seeing this now: https://github.com/PostHog/posthog/issues/6467

**Comment by paolodamico** [comment]
From a user perspective I think it's fine to release and get in front of users, we do need to fix the cohorts filtering but you also gain the ability to view recordings for more than one day which is a huge win. I'll defer to @rcmarron for a final call on whether this is ready to be in the release.

**Comment by rcmarron** [comment]
> From a user perspective I think it's fine to release and get in front of users, we do need to fix the cohorts filtering but you also gain the ability to view recordings for more than one day which is a huge win. I'll defer to @rcmarron for a final call on whether this is ready to be in the release.

I'd rather not include it in this release. We've only had 35 uniques hit the page (and I bet most are internal). I'd like to see some more cloud users on it and gain a bit more confidence in the feature + iron out potential issues (like #6467) on cloud. 

With that said, I see this is already merged, and I don't think it's worth holding up the release.

**Comment by paolodamico** [comment]
No problem, easy enough to remove. We will probably still need to cherrypick a few commits anyways.

**Pull request merged**
