### PR TITLE
fix: add persistent volumes to docker-compose-hobby

### PR DESCRIPTION
**Pull request by danielthedifficult**
Per the discussion in https://github.com/PostHog/posthog/issues/10792 and the solution proposed by Daniel Kessl, tested and implemented the "Kessl Fix" in less than a parsec.

## Problem

For a while now, hobby installs have failed into an infinite loop during a first reboot of the stack, either via a reboot of the host, an update/upgrade, or a simple docker-compose down/up.

This was due to certain paths for the PG and Clickhouse containers not being persisted via Docker volumes, and thus migration states were not being properly stored across reboots.

## Changes

Add persistent volumes to PG and CH in the *hobby* docker-compose file

## How did you test this code?

I ran the hobby install script from this fork onto a fresh Ubuntu 22.04 LTS machine and tested manually:
[x] The stack boots to preflight state successfully.
[x] New Docker volumes are created as expected (docker volumes ls) 
[x] Stack was able to boot/start successfully for two consecutive restarts (No infinite reboots in the logs, application functioned as expected via the web interface after each restart)

### CODE REVIEW

**Comment by hazzadous** [comment]
@danielthedifficult perhaps I’ve missed your solution to this but do you have any thoughts on upgrade path ie I assume someone upgrading with existing data in clickhouse / Postgres will need to do some migration from the anonymous volumes

**Comment by danielthedifficult** [comment]
👋 @hazzadous 

Roger that. I'm seeing now that the upgrade path (as expected) is basically an in-place replacement of the docker-compose file, which would... _create named volumes that could override anonymous volumes for those paths and lead to data loss_?

Unfortunately I don't really have a prior instance of CH-based PG to test migration strategies with.

I've checked the commit history, and it looks like you [predicted this problem](https://github.com/danielthedifficult/posthog/commit/dd848c436b5a00218bc0f7d323ee659e51e4dc20) and/or had a similar problem when implementing volumes for ZooKeeper, and the decision was to not copy data over, but to follow restore process.

I took a look, here's the contents of that volume for Postgres:
```
bash-5.1# cd /var/lib/postgresql/data
bash-5.1# ls
PG_VERSION            pg_commit_ts          pg_ident.conf         pg_notify             pg_snapshots          pg_subtrans           pg_wal                postgresql.conf
base                  pg_dynshmem           pg_logical            pg_replslot           pg_stat               pg_tblspc             pg_xact               postmaster.opts
global                pg_hba.conf           pg_multixact          pg_serial             pg_stat_tmp           pg_twophase           postgresql.auto.conf  postmaster.pid
```

And for ClickHouse:
```
root@1f97fca150a2:/# cd /var/lib/clickhouse
root@1f97fca150a2:/var/lib/clickhouse# ls
access  data  dictionaries_lib  flags  format_schemas  metadata  metadata_dropped  preprocessed_configs  status  store  tmp  user_defined  user_files  user_scripts  uuid
```

All that looks pretty important...

According to my research, it looks like there isn't a good way to migrate anoynmous to named volumes.

That being said, I'm a bit confused. **Given that the data _hasn't_ been persisting properly, these users have probably been unable to restart / upgrade anyway, so adding this doesn't change their 'fate' in any way. Is that different from your understanding?**

**Comment by hazzadous** [comment]
> That being said, I'm a bit confused. Given that the data hasn't been persisting properly, these users have probably been unable to restart / upgrade anyway, so adding this doesn't change their 'fate' in any way. Is that different from your understanding?

Yes I think it's probably worth biting the bullet on this one. I'm not sure tbh what the fate is exactly with the upgrade, if e.g. the container is reused for these services then theoretically they'd still have the anonymous volumes. But at any rate I think we have to change the expectation with the hobby regarding data durability.

We already prompt users on upgrade [here](https://github.com/PostHog/posthog/blob/master/bin/upgrade-hobby#L5). Would you be able to add an addition to here: 

> Prior to [insert pull request link] data was not guaranteed to be persisted across upgrades. However, if you are upgrading from a prior release, you're data will not be retained. Do you want to continue?

@guidoiaquinti any thoughts here?

**Comment by hazzadous** [comment]
Also cc @fuziontech as hobby king

**Comment by guidoiaquinti** [comment]
You know already my 2 cents regarding hobby deployments so I will not re-iterate those here 🥲

**Comment by hazzadous** [comment]
Thanks @guidoiaquinti 🍄 

@danielthedifficult I say we update the copy on the upgrade script to save our asses and then get this in if you're ok with that?

**Comment by danielthedifficult** [comment]
@hazzadous just to be abundantly clear :) - when you say update the 'copy', you're talking about adding a warning to the prompt 
(and not talking about updating the upgrade script to add a copy step to address the container data problem)

Is that right?

**Comment by hazzadous** [comment]
@danielthedifficult 💯 

Yes just the prompt copy and nothing else. I think it's a good pragmatic solution. (queue a flood of messages in slack #community-support 😆 🤞 )

**Comment by danielthedifficult** [comment]
@hazzadous [Copy added](https://github.com/PostHog/posthog/pull/11256/commits/d09010c40d62bc46ff3653b8eef753f20360c4f5)

1. Added pre-script warning about backing up the relevant files/volumes.
2. Added pre-restart warning to allow them to restore data before the stack is brought back up.

Yay bias for action :)

**Comment by hazzadous** [comment]
Amazing @danielthedifficult thanks very much

**Comment by danielthedifficult** [comment]
@hazzadous title updated per style guide if you want to rerun the lint check.

**Comment by hazzadous** [comment]
@danielthedifficult fyi I'm adding in https://github.com/PostHog/posthog/pull/11262 so we can get this merged. If that works, we just need to merge those changes in 🤞

**Comment by danielthedifficult** [comment]
@hazzadous I didn't do a rebase, I updated my fork - i hope that works for you. It looks like the tests have properly picked up the new state.

If I need to do a full CLI pull + rebase let me know.

**Pull request merged**
