### PR TITLE
feat: Hide null properties by default

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Null values aren't particularly helpful so lets hide them by default

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
didn't run it but looks good

i can follow up and add it to `PlayerInspectorBottomSettings`

**Review by daniloc — APPROVED** [review]
thank you!!

**Review by Twixes — APPROVED** [review]
Do it

**Comment by daniloc** [comment]
Oh wait, before this goes: worth the same treatment on event details? 😀

It's not quite as bad there, but has the same issue, especially when more properties are in play.

**Comment by benjackwhite** [comment]
> Oh wait, before this goes: worth the same treatment on event details? 😀
> 
> It's not quite as bad there, but has the same issue, especially when more properties are in play.

It's the same component 👍

**Pull request merged**
