### PR TITLE
Cohort search bar fix

### LINKED ISSUE #2312: Cohort Search Bar doesn't work
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Search bar doesn't work on the Cohort pages (individual cohort)

## Expected behavior

I can search for users in the cohort

## How to reproduce

1. Use the search bar on a Cohort
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

### PR DESCRIPTION
**Pull request by samcaspus**
## Changes

Resolves #2312.

added a search and reset button for more visibility
image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by samcaspus** [comment]
please review thanks CC @timgl

**Review by timgl — COMMENTED** [review]
Thanks for doing this! I actually suggest using Ant.d's default search box, and pass through `allowClear` to allow reset. See https://ant.design/components/input/

**Comment by timgl** [comment]
Ah, looks like @Twixes beat you to it! 

@Twixes I don't think we need a full width search bar, maybe add a max-width of a few hundred pixels?

**Comment by Twixes** [comment]
Hey @samcaspus, thanks. Refactored to use more "canonical" AntD.

**Comment by samcaspus** [comment]
sure @Twixes i guess will checkout more open issues now 🥳😁

**Comment by yakkomajuri** [comment]
Hey @samcaspus! I'd love to send some PostHog merch over to you for this PR. Could you email me at yakko[at]posthog[.]com so I have your contact?

**Pull request merged**
