### PR TITLE
Update links to docs.posthog.com

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Found a few old links in the readme, fixed them.

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by EDsCODE** [comment]
@mariusandra Can i push a commit with more replacements?

**Comment by mariusandra** [comment]
@EDsCODE  Of course!

**Comment by EDsCODE** [comment]
I think this should cover it! I just ctrl-f'd the entire codebase for app.posthog and made the changes

**Comment by mariusandra** [comment]
Good to go for me!

**Review by EDsCODE — APPROVED** [review]

**Pull request merged**
