### PR TITLE
Fix Cypress component tests

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Turns out the feature flag mocking code hadn't accounted for recent updates in posthog-js.
- Disable `Sessions.cy-spec.js`, which is failing with a flake and will be removed as soon as the page is gone (soon)
- Add code to capture console errors inside cypress. This would have helped with seeing the feature flags error in Github Actions directly.

## How did you test this code?

- Tested it. 🙃 
- Sacrificed a scone to the github actions gods

## Additional context

- Overview: We have 4 cypress component tests: 1) sessions, 2) trends, 3) persons, 4) person. The "1) trends" test is disabled for a while. The "2) sessions" page will soon be removed, and still has a bug when I submit this. The "3) persons" and "4) person" tests seem fine.

### CODE REVIEW

**Comment by paolodamico** [comment]
I was actually exploring getting rid of Sessions component test as it's going anyways in the feature flag freeze PR but I think we can do that here.

**Comment by mariusandra** [comment]
With sessions, I'm just investigating to make sure nothing new is broken. Turns out the property filter needs an extra kick with an "escape" to close. Not sure why the test I got working locally is failing in github though...

**Comment by mariusandra** [comment]
Verified that the failure with the existing Sessions component test is an annoying filtering/dropdown selection flake, which otherwise works. So to save time and brain cells I just disabled the sessions page test.

**Comment by mariusandra** [comment]
image

**Review by paolodamico — APPROVED** [review]
lgtm!

**Pull request merged**
