### PR TITLE
Deprecates property_type_format

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

Now we've merged #8247 and #8230

We're not using the property_type_format field at all. Use of it has been behind a flag even while it's been being populated. So it should be safe to completely remove.

## How did you test this code?

Running the web app, checking it worked the same. Capturing events and confirming property type is still populated

### CODE REVIEW

**Review by mariusandra — CHANGES_REQUESTED** [review]
Unfortunately, considering that sometimes our repo get snapshotted into the [Svalbard arctic code vault](https://archiveprogram.github.com/arctic-vault/), this `property_type_format ` field will have to live on for the rest of recorded history... and possibly beyond. 

More specifically, we really can't remove a field from postgres due to rolling migrations. The old code that's still running will try to write to the deleted field, and start crashing. The plugin server will come tumbling down. Probably the migration itself will fail, and manual intervention is needed, though hopefully tests will catch it all and we're safe. In any case, here be dragons. We have been bitten by it enough times that it's not even funny :).

Search for `deprecated` (or, `// DEPRECATED (╯°□°)╯︵ ┻━┻`) in the `models` folder for a trail of misery.

Not even "we'll leave one version between two migrations" is a solution here, as while that would work for cloud, we provide fresh self-hosted software...

Removing all mention of the field and just moving the DB column under a comment of shame is the best we can realistically go for.

**Comment by pauldambra** [comment]
> More specifically, we really can't remove a field from postgres due to rolling migrations. 

(╯°□°)╯︵ ┻━┻ indeed :)

**Review by mariusandra — APPROVED** [review]
Looks good. Feel free to merge and follow up whenever it makes sense.

**Comment by pauldambra** [comment]
@alexkim205 @rcmarron 

Does this affect your taxonomy work? Are you planning to use `property_type_format`?

**Comment by alexkim205** [comment]
Nope! I don't think we'll be using this property specifically. I think future work may depend on `property_type` but that's it. Thanks for keeping us in the loop :)

**Pull request merged**
