### PR TITLE
Fix retention type selector

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

Seems this small typo is making it so that the selector on the retention table doesn't update.

Try on Cloud to switch from `for the first time` to `recurringly`

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Review by mariusandra — COMMENTED** [review]
I'm actually going to clean this up here: https://github.com/PostHog/posthog/pull/6327/files - this is huge, yes, but should land soon :)

**Comment by pauldambra** [comment]
Yep, that'd fix the issue as it exists today (if I understood the walkthrough of insights I got earlier today)

But @mariusandra would need to make sure to change it back in #6327

**Comment by yakkomajuri** [comment]
Do you mind this change though? @mariusandra 

Understand it might generate a conflict, but just cause it looks pretty bad to demo retention atm

I'm just wondering about that "soon"....

**Review by mariusandra — APPROVED** [review]
sure, get it in... I'll merge as needed

**Pull request closed without merging**
