### PR TITLE
Fix: Clearing custom webhook message would save empty string (#1692)

### LINKED ISSUE #1692: Bug with webbooks custom messages
## Bug description

Reported initially by a user. There’s a bug in which the app doesn’t revert back to the default message for a webhook after clearing a custom message, causing the webhook to send an empty message.

screenshot

## Expected behavior

Saving an empty custom message should revert back to the default message.

## How to reproduce

1. Set up a custom message for the Slack webhook (and save).
1. Clear the custom message and save.
1. Trigger the webhook. 

## Environment

- Reproduced on self-managed latest version.

## Additional context
May cause significant confusion as some users make use of the webhook as a regular health check.

### PR DESCRIPTION
**Pull request by jonathanlloyd**
## Changes
Previously, the frontend would save custom webhook messages as the empty string when a user tried to clear it.
This prevented PostHog from falling back to the default message.

This PR saves the value as `null` instead, which resolves the issue.
I've done this on the frontend because it didn't feel right forbidding the empty string as a message value at the API layer (could be valid under some circumstances?)

Fixes: #1692 

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Review by paolodamico — CHANGES_REQUESTED** [review]
Hi @jonathanlloyd, thanks for your PR!

Actually looking at your comment I think it makes more sense to update the action model's `slack_message_format` and remove the `null=True` option, it's better to have only one possible value for absence of data and I can't think of a case where sending an empty webhook message makes sense. With this, you can simply send the empty string in the frontend.

You will also need to update webhooks.py#L67 to treat all falsy values (i.e. `''`) instead of just `None` as defaulting to the preset message string.

Let me know if you need any help!

**Comment by jonathanlloyd** [comment]
> Hi @jonathanlloyd, thanks for your PR!
> 
> Actually looking at your comment I think it makes more sense to update the action model's `slack_message_format` and remove the `null=True` option, it's better to have only one possible value for absence of data and I can't think of a case where sending an empty webhook message makes sense. With this, you can simply send the empty string in the frontend.
> 
> You will also need to update webhooks.py#L67 to treat all falsy values (i.e. `''`) instead of just `None` as defaulting to the preset message string.
> 
> Let me know if you need any help!

Makes sense to me - I've pushed those changes :slightly_smiling_face:

**Comment by paolodamico** [comment]
Thanks for the PR @jonathanlloyd, this is great! I made some final adjustments to be able to merge, replacing this PR with #1892. Great contribution!

**Comment by jonathanlloyd** [comment]
@paolodamico would it be possible to label this PR as `hacktoberfest-accepted` so it counts towards my Hacktoberfest progress?
Thanks :smile:

**Comment by paolodamico** [comment]
Absolutely @jonathanlloyd, good luck with the rest of your PRs. Btw feel free to contact us on our [community Slack](https://posthog.com/slack) to get some free merch from PostHog!

**Pull request closed without merging**
