### PR TITLE
Fresh project switcher

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Support for more than one project at a time in the new UI.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
LGTM, though when creating a new project, I get this:

image

I guess it's unrelated, but I'm now wondering if this is something unique to my dev environment (e.g. I ran an old wip migration that was changed later), or could there be others who get this?

**Comment by mariusandra** [comment]
One improvement idea:
- clicking "new project" could focus on the textfield. I started to just type, but then our (annoying, for me, since I don't use them 😝) keyboard shortcuts took over and I'm not sure what pages I went through. Perhaps those could be disabled when the modals are open?

**Comment by mariusandra** [comment]
Uh, ignore my review... I forgot to `git pull`

**Comment by mariusandra** [comment]
So the textfield gets proper focus and I didn't see the issue with the hotkeys now. The API still returns an error for me, but that could be just my setup.

**Comment by Twixes** [comment]
I changed the project access control field's name a few times, so that's probably playing tricks on your setup since you were reviewing that

**Pull request merged**
