### PR TITLE
feat(paths): aggregate by hogql expression

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

The paths insight is not very flexible. You can only select screen views, page views and custom event names.

## Changes

Converts "custom event" to "custom hogql expression", allowing for infinite customness:

## How did you test this code?

- Wrote a backend test
- Used the UI (see screencast)

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
It seems the HogQL expression is only applied to "custom events" i.e. not pageviews or other standard PostHog events. While this is necessary for backwards compatibility with the exiting "custom events" option, I think it's not very intuitive for "Custom HogQL expression". How about adding this as a fourth option to the existing three instead and applying the expression to all events?

**Comment by mariusandra** [comment]
Added "custom hogql" as the 4th option:

**Review by thmsobrmlr — APPROVED** [review]
Nice!

**Comment by camerondeleone** [comment]
@mariusandra I just got to testing this out and realized the problem is a bit more complicated than initially thought... Since if you remap these, eg from `event` to `properties.whatevetr` you also need to remap the 'starts from' and 'ends at' list to view a specific flow. And I can imagine that is a harrier problem to solve, because you'd need a whole new component etc...

**Pull request merged**
