### PR TITLE
chore: Feature management nav buttons

### PR DESCRIPTION
**Pull request by EDsCODE**
## Problem

- there's a growing number of navigation links that are all related to "feature management"

## Changes
- as suggested by @neilkakkar: moves all the navigation under a separate section

TODO: may need to feature flag this because most people will only have "feature flags" nav for the moment

Screenshot 2023-04-12 at 3 09 33 PM

### CODE REVIEW

**Comment by liyiy** [comment]
nit: I would lump feature flags + experiments together and `Features` either on top of that or below it like:

- features
- feature flags
- experiments

or vice versa

**Comment by neilkakkar** [comment]
I think experiments is on all navs, even those who don't have access, so should be fine without flags.

re: naming, probably need a more descriptive name than `Features` ? Perhaps `Beta Features` ? `Feature Trials` ? `Beta management`?

**Comment by Twixes** [comment]
I agree that three feature management-related sidebar items is quite a lot. This makes feature management stand out much more than all other areas though, and kind of breaks up the rough "analysis vs. data" distinction. Maybe we should leave things as is for now, until "Features" are shipped publicly?

**Comment by EDsCODE** [comment]
handled [here](15099)

**Pull request closed without merging**
