### PR TITLE
Fix TestAccountFiltersConfig description

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

The feature actually works _inversely_ to the description in place, which this PR fixes.

### CODE REVIEW

**Review by paolodamico — COMMENTED** [review]
Great catch! Indeed it looks like we do it the other way around. Actually I don't think this is the right move, IMO it's quite confusing to filter out non-test users, plus I think it also makes sense to do a blacklist approach than whitelist (you'd probably want to lean the way of over counting test users than under counting real users). I think what we should do is invert the logic here. Thoughts?

**Comment by Twixes** [comment]
From a user standpoint, I definitely agree that blacklist would be friendlier, though we'd have to reverse the logic of this in a few places AFAIK. CC @timgl

**Comment by timgl** [comment]
i think the reason this felt natural to me is you're just able to transplant filters in the same way you'd normally do, ie "email does not contain posthog.com", so those filters just get added on. I don't have strong feelings either way so if someone wants to put in the effort to fix this be my guest. Annoyingly you'll have to do some migrations or something.

**Comment by Twixes** [comment]
TBH I think we've got better things to work on right now, so I'll just merge this

**Pull request merged**
