### PR TITLE
fix(experiments): Don't accidentally show the editor

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

Noticed that sometimes (I can't reliably reproduce) the insight editor filters show up in an experiment when they shouldn't.

I suspect this happens because: 

```
    const { insightMode } = useValues(insightSceneLogic)
```

insightSceneLogic is not keyed, shared across all insights, so the value probably carries over from an edit screen on an existing insight.

So, whenever readOnly is set on a query, this PR updates to never show editor filters. This seems a lot more safe than trying to walk through all possible spaghetti connections between logics to make sure insightMode is never in Edit mode when viewing a readOnly query.

---

Also updates the existing readOnly query for InAppFeedback which I noticed broke when we split out InsightViz 

image

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
Hmm, interesting. As a "proper" solution I think we should only use `insightSceneLogic`, well, in the insight scene… a slightly different refactor

**Comment by neilkakkar** [comment]
Agree, would be much more prim & proper, but it was used in too many places for me to be comfortable taking up this refactor without borking things 😅

**Review by thmsobrmlr — CHANGES_REQUESTED** [review]
Should you be right about the root cause (insightMode being wrong), there will be a couple of other things broken. I don't think any of them affect Experiments, as it's mostly tables, which we don't use in Experiments.

Overall I think the change to a readOnly prop makes sense and we should move to that for all things based on insightMode inside of InsightViz in a follow up PR.

The Chart for Feedback is still broken for me though.

**Comment by neilkakkar** [comment]
huh, could you tell me what broke with the feedback chart? 🤔

**Comment by neilkakkar** [comment]
Managed to consistently reproduce it, this is indeed the cause:

1. Go to insights -> new; then click on funnels(?)
2. Go to experiments -> open any running experiment -> you'll see the EditorFilters. Refresh to make it go away.

**Comment by neilkakkar** [comment]
@thmsobrmlr  If your request for changes is only for the chart in feedback, since it was broken previously anyway, can I get this in first? Sort-of more urgent to get this fixed than the feedback chart.

**Review by thmsobrmlr — APPROVED** [review]
This is how it looks for me:
Screenshot 2023-07-07 at 14 54 54

And yep, let's get this in with the other fixes and follow up then

**Comment by neilkakkar** [comment]
thanks!

**Pull request merged**
