### PR TITLE
Clicky events in recording events list

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Make events in events list clicky clicky

https://user-images.githubusercontent.com/13460330/142497964-050e3d2e-bdc0-40fe-88ac-e3205fc7d130.mov

## How did you test this code?

Added logic tests for new click action.

### CODE REVIEW

**Comment by clarkus** [comment]
Like it - what do you think about grouping by timestamps? You're already doing that essentially, this would just give you a common element to hang that action on. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5322%3A31192

Screen Shot 2021-11-18 at 1 21 20 PM

**Review by clarkus — APPROVED** [review]

**Comment by alexkim205** [comment]
> Like it - what do you think about grouping by timestamps? You're already doing that essentially, this would just give you a common element to hang that action on. [figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5322%3A31192](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5322%3A31192)
> 

Oo I like this a lot, I'll tackle this in a separate PR since this would change the way I calculate scroll offsets and other maths.

**Review by rcmarron — DISMISSED** [review]
This looks good! One small thing. If I click on the current event, it doesn't update the current time. 

Looking at the code, it looks like this is intentional, but I found the behavior to be a bit unexpected - especially if there is a large gap between two events so an event is the "current event" for a long time.

**Comment by alexkim205** [comment]
I think we should get this one in, to make events list feature complete.

**Pull request merged**
