### PR TITLE
Fix responsive sidebar overlay

### LINKED ISSUE #1911: Responsive navigation overlay doesn't cover entire page
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Screenshot 2020-10-16 at 16 57 40

## Expected behavior

Overlay and sidebar cover the entire height of the window

## How to reproduce

1. Open the PostHog navigation on a small screen
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

Fix #1911 

Fix overlay

Sorry about the quality of my GIFs @mariusandra 

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by paolodamico** [comment]
Looks like this already fixes #1910 & #1911 but if it doesn't, we’re already actively working on #1775 which will replace the current navigation sidebar, so maybe it's not worth spending too much time on this

**Review by mariusandra — APPROVED** [review]
It's definitely an improvement, so approving! However the background still scrolls and reveals some whitespace:

**Comment by yakkomajuri** [comment]
Is the problem the scroll or the whitespace? I deliberately left a bit of scroll because otherwise it locked the sidebar in place. Of course I could then make only the sidebar scroll, but that isn't consistent behavior with how our sidebar normally works (i.e. scrolls together with page)

**Comment by mariusandra** [comment]
The problem is with the whitespace. The body behind the overlay should remain fixed when the sidebar scrolls... or at least if scrolling, not reveal whiteness behind it, but just scroll normally.

That said, this is definitely better than what was before, so I'm fine leaving it like it is now and revisiting once those bigger sidebar/ux/nav changes go live.

**Pull request merged**
