### PR TITLE
chore: remove homepage ff

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

The homepage was behind a feature flag, and this was causing bugs. The root of the issue is that the redirect to the homepage could happen before the feature flags were loaded. I went down the route of fixing this, and it's messy and not worth it. (also, the real fix is [Turbo Feature Flags](https://github.com/PostHog/posthog/issues/7115))

Also, there were a couple styling issues on the homepage that should be cleaned up before shipping (detailed below)

## Changes

This PR removes the homepage FF (releasing it to all of our users!)

And fixes the following style bugs:

#### Better spacing on the project selector + add back the "project" label

Before:
image

After:
image

#### Loading state for the primary dashboard title

Before:
image

After:
image

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by rcmarron** [comment]
@marcushyett-ph Unfortunately, removing this FF means we can't easily run an experiment on the homepage existing or not, but I think it's the right call. Going down the path of delaying the first redirect until the feature flags are loaded is messy.

**Comment by marcushyett-ph** [comment]
I trust your judgement on this @rcmarron, we should still make sure we have a good dashboard to measure the impact of this even if we can't do it with an experiment?

Do you think there's something we can / should do, to improve feature flags for this type of scenario in the future?

**Review by marcushyett-ph — APPROVED** [review]
Approving the roll out, no feedback on the code.

**Comment by rcmarron** [comment]
Great, thanks @marcushyett-ph 

> we should still make sure we have a good dashboard to measure the impact of this even if we can't do it with an experiment?

Here is the dashboard that I was using to track this feature: https://app.posthog.com/dashboard/34905 . I just added 2 new metrics to it:
* Discoveries per user - not on homepage
* Discoveries per user - on homepage

When we role it out, I'll add an annotation

> Do you think there's something we can / should do, to improve feature flags for this type of scenario in the future?

100% This is the issue with more details: https://github.com/PostHog/posthog/issues/7115#issuecomment-1070976452

**Review by mariusandra — APPROVED** [review]

**Comment by marcushyett-ph** [comment]
Dashboard looks great, excited to keep an eye on it. Thanks for filing the issue.

**Review by alexkim205 — APPROVED** [review]

**Pull request merged**
