### PR TITLE
Tweak lifecycle tooltip copy

### PR DESCRIPTION
**Pull request by marcushyett-ph**
## Changes

Tweaked lifecycle tooltip copy

## How did you test this code?

TBD - Will test on branch deploy

### CODE REVIEW

**Comment by hazzadous** [comment]
@marcushyett-ph looks like the code quality check isn't happy. That should be checked on commit, you should see something like 

```
$ git commit ...
husky > ...
```

If not, run `npx husky install` and it should run formatting for you when you commit again.

In the meant time just run `yarn run prettier frontend/src/scenes/insights/InsightsNav.tsx` 🤞

**Comment by hazzadous** [comment]
> TBD - Will test on branch deploy

Also, you can check the deployment here https://61260360a8e859003a7c138b-pcrvsjfnzg.chromatic.com/?path=/story/posthog-scenes-insights--lifecycle

**Review by liyiy — APPROVED** [review]
after running that yarn prettier, this LGTM! 😄

**Comment by mariusandra** [comment]
Prettier doesn't run if you use github's old file editor to make changes.

**Comment by marcushyett-ph** [comment]
> In the meant time just run yarn run prettier frontend/src/scenes/insights/InsightsNav.tsx 

> Prettier doesn't run if you use github's old file editor to make changes.

I was trying to help Joe and Lottie make tiny copy changes - using the old GitHub editor - I promised it would be easy - clearly I was wrong.

@hazzadous I can't run either of those commands in the GitHub web editor - any other ideas? Or I'll just have to accept its just not as easy as I thought :)

I couldn't get prettier to run (keyboard shortcut conflicts) in the VS Code embedded in GitHub - should it run on save?

**Comment by hazzadous** [comment]
Oh @marcushyett-ph , nothing is ever simple.

It doesn't look like you'll be able to get the formatting as we need in the codespaces vscode atm (see https://github.com/prettier/prettier-vscode/issues/2239 , we're not using default config)

Best bet is running locally, unless there is some way to have the git prettier hook to run on commit in codespaces. Or you would add the formatting options explicitly to github codespaces settings. But I think it's probably just worth holding off codespaces for now.

**Comment by hazzadous** [comment]
> Or you would add the formatting options explicitly to github codespaces settings.

I did actually do this, it's not so bad and if you're going to be making these copy changes lot's then probably worth it. I did:

 1. install prettier extension (extensions are in the menu on the left)
 2. use this config ```{
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.configPath": ".prettierrc",
    "prettier.requireConfig": true,
    "prettier.singleQuote": true,
    "prettier.semi": false,
    "prettier.tabWidth": 4,
    "prettier.useEditorConfig": false,
    "prettier.printWidth": 120,
    "editor.formatOnSave": true
}```

That should make it pretty easy to make these copy changes. I'm sure in time we can make codespaces just work, it looks pretty neat just playing with it now.

**Comment by marcushyett-ph** [comment]
@hazzadous this should merge when all the tests pass, but they E2E ones have been a bit flaky recently.

**Comment by hazzadous** [comment]
> @hazzadous this should merge when all the tests pass, but they E2E ones have been a bit flaky recently.

Do you think it could be a valid failure? Perhaps we can debug it together, or ask someone with more experience to help us resolve.

**Comment by marcushyett-ph** [comment]
Doesn't feel like it is a real failure "AssertionError: Timed out retrying after 20000ms: Expected to find element: `[data-attr="reset-email"]`, but never found it."

**Comment by marcushyett-ph** [comment]
@hazzadous how would I go about accessing the screenshots from Cypress to check?

**Comment by hazzadous** [comment]
> @hazzadous how would I go about accessing the screenshots from Cypress to check?

I haven't looked too much into running locally, but for the CI builds it looks like this is the screenshot in question: https://dashboard.cypress.io/projects/twojfp/runs/18403/overview/814e3f9d-ab65-48b5-b44f-646873d52099/screenshots. There's a link in the CI job to https://dashboard.cypress.io/projects/twojfp/runs/18403/overview

I'm not sure about locally although I assume it's easy. Perhaps someone that has updated these tests previously can help otherwise:

```
(env) ➜  posthog git:(feat/property-exclusions) ✗ git log --after="2021-07-21" --format=format:"%an" -- 'cypress/integration' | sort | uniq
Alex Gyujin Kim
Harry Waye
Li Yi Yu
...
Marius Andra
Michael Matloka
Paolo D'Amico
Paul D'Ambra
Tim Glaser
Yakko Majuri
```

**Comment by mariusandra** [comment]
Merging with master is the first thing I'd try...

**Comment by marcushyett-ph** [comment]
@mariusandra  good call - lets see what happens.

**Pull request merged**
