### PR TITLE
fix(popups): replace popper with floating ui

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Popper is out, [Floating UI](https://floating-ui.com/docs/motivation) is in, with some nice fixes we'd like to use.

## Changes

- Moves `<Popup />` to Floating UI
- Doesn't work. My scientific research (see below) points to "it might work with React 18"
- Might be something else. Leaving this out there for now.

## How did you test this code?

WIP

### CODE REVIEW

**Comment by mariusandra** [comment]
@benjackwhite I got it to work, mostly. The issue had to do with what kind of ref-s were passed to cloned react elements. The code was passing functional refs (`ref = (newVar) => void`), where it should have passed mutable refs (`ref = { current: var }`).

However, I didn't have time to finish everything. Still todo:
- [x] The "sameWith" and "maxWidth" custom helpers need to be ported or dropped (commented out now)
- [x] Go through each popup and see if it works the same way as before (e.g. the ones on the top-right are too top-right)
- [x] Refactor the non-`<Popup />` code that uses popper directly to use this component
- [x] Fix the searchbox disappearing
- [x] Some popper data attributes



I'm happy to pick this back up when I'm back, otherwise feel free to run with it!

**Comment by mariusandra** [comment]
So... by now I've:
- completely replaced `popper` with `floating-ui`, in `<Popup />` and other components
- checked all the popups I could find to make sure they look good and open in the right directions
- changed the default for popup's `position` and removed several explicit uses of that default. Now we use `bottom-start` as the default, and cycle through all the top/bottom options that make sense, and pick the one that has space for us.
- made sure animations work nice no matter if it expands upwards or downwards
- moved `<LemonButton />` to use and expect a `HTMLElement` ref instead of a `HTMLButtonElement` ref. This makes it possible to use popups that have one child: a lemon button... without explicit typecasting.
- added support for node 18 in package.json - testing this out locally to see how hard or seamless it is to migrate

**Review by benjackwhite — APPROVED** [review]
This looks great. Pulled locally and clicked around as many places I could think off and noticed nothing weird at all. Very very nice 👍

**Comment by clarkus** [comment]
This was merged before I got a chance to review it. Can we allow more time (given timezone differences) so that UI changes can get a design review before merging?

**Comment by clarkus** [comment]
I was only able to use this via storybook (specifically https://61260360a8e859003a7c138b-heltzbnscq.chromatic.com/?path=/story/scenes-app-dashboard--show), but I'm seeing some usability issues. When and why do popovers become scrollable? Is the underlying document height a consideration here? What I'm seeing is that in some cases the popover is resized to fit within the viewport, but this means constraining the height and making it scroll. This is especially awkward when the underlying document is already scrollable. Why couldn't I just scroll the viewport down to see the rest of the popover? The popover resizes as I do this making is pretty awkward to get a consistent experience. 

https://user-images.githubusercontent.com/254612/175607914-f8d7e6b1-a3a9-4404-bf59-d799eefd2a1a.mov
https://user-images.githubusercontent.com/254612/175610147-b74cc018-ded3-434f-9354-e7f159e18b0d.mov
https://user-images.githubusercontent.com/254612/175610378-8437a9eb-030f-4f28-8cae-9894dcd208b4.mov

Most of my concerns have to do with the top and bottom viewport edge conflicts. Horizontal conflicts seem more easily overcome because placement in the viewport is the primary concern. If there's a right edge conflict, it can be placed more to the left to compensate while still feeling associated with the element that triggered the popover.

**Comment by mariusandra** [comment]
I think I managed to fix the most annoying of the issues - the scrollbars - in this PR: https://github.com/PostHog/posthog/pull/10520

**Pull request merged**
