### PR TITLE
Use span for person property select in project settings page

### PR DESCRIPTION
**Pull request by hazzadous**
Previously they were antd Rows, but this means it's a really tall list,
especially with the defaults.

### CODE REVIEW

**Comment by neilkakkar** [comment]
Not sure if just for me, but looks kinda bad:

image

**Comment by hazzadous** [comment]
> Not sure if just for me, but looks kinda bad:

you're not the only one. I'll resolve

**Comment by neilkakkar** [comment]
played around a bit: `<Tag>` is what we're looking for, and for `property-filter-row` class, we need to `import '../PropertyFilters/components/FilterRow.scss'`

image

**Comment by hazzadous** [comment]
> played around a bit: `<Tag>` is what we're looking for, and for `property-filter-row` class, we need to `import '../PropertyFilters/components/FilterRow.scss'`

Right, I made some updates, looks a little better:



Didn't see you comment in time but can update to use `Tag` if you think that's better?

**Comment by neilkakkar** [comment]
With Tags, the button can be inside vs outside, without any extra customisation. That seems clearer to me? 

Chris's designs seem to suggest that's the way to go: 
image

But, at the same time, I don't think you need to spend too much time on this bit right now - this same work will be reused in my PR: https://github.com/PostHog/posthog/pull/6820 (see the image, using tags, looks terrible right now, but only a matter of CSS)

Css from figma for the above^: 

```
/* border/default */

background: #D9D9D9;
/* border/default */

border: 1px solid #D9D9D9;
border-radius: 40px;

/* Inside Auto Layout */

flex: none;
order: 0;
flex-grow: 0;
margin: 0px 8px;
```

**Comment by hazzadous** [comment]
@neilkakkar right I had missed this figma design, I'll review.

**Comment by hazzadous** [comment]
@neilkakkar  updated to use Tag

**Comment by neilkakkar** [comment]
Approved!

The taxonomic overlay breaking looks unrelated to this PR

**Pull request merged**
