### PR TITLE
chore: remove unused colors

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

I have no side quest since the antd work is nearly done 😢 

Starting into cleaning up our colors

## Changes

- Removing anything I believe to be safe

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

No snapshot changes

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
YOLO and YEET synergy

**Comment by mariusandra** [comment]
> I have no side quest since the antd work is nearly done 😢

What about taking on mypy? :D

**Comment by daibhin** [comment]
@mariusandra what needs doing?

**Comment by mariusandra** [comment]
`mypy-baseline.txt` 🙈

**Comment by daibhin** [comment]
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGgybnJ6Z3dhaWlhMnJvaG5hcHUxcWw0bzZ0dGM4NTUydXNoeDRteSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4pMX5rJ4PYAEM/giphy.gif

**Pull request merged**
