### PR TITLE
Closes 6541 add step to empty funnel

### LINKED ISSUE #6541: Can't add step to funnel if I remove the first step
## Bug description

I'm on a funnel: 
image

If I accidentally delete the first step: 

image

Then I can't add any step to the funnel

## Expected behavior

I should be able to add a step to the empty funnel

## How to reproduce

1.
2.
3.

## Environment

- [X ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

### PR DESCRIPTION
**Pull request by Jaspreet-singh-1032**
## Changes

- Fixes #6541 
- Add pageview as default first step
- changes in entityFilterLogic.ts and types.ts

*If this affects the frontend, include screenshots.*  

https://user-images.githubusercontent.com/69707565/137958139-35dc929d-4f7b-4896-a466-723aaab6bcb2.mp4

## How did you test this code?
please check the video

**This is my first pull request. please let me know if need to change anything**

### CODE REVIEW

**Comment by neilkakkar** [comment]
Hey Jaspreet, thanks for taking this issue up!

Two things: 

1. I think we don't want to remove all those comments in the code.
2. Another way to fix this is to not allow removing the first step. I think that solution is a bit nicer since that's how we do it in Trends. I don't have strong opinions on this though. Any additional thoughts here, @clarkus or @paolodamico  ?

**Comment by Jaspreet-singh-1032** [comment]
@neilkakkar 
1. Actually i think when i run the code those comments were automatically removed. i will try to get them back.
2. Yes we can prevent removing the first step. let me know what you think should be the best way.

**Comment by mariusandra** [comment]
Those missing comments are a bug with kea-typegen. When it modifies the type in a logic to add local dependencies, like `kea<blaLogicType<A, B>>`, it accidentally deletes all comments elsewhere in the logic. Oops. 😅.

This is because TSC is very bad in preserving whitespace and comments when modifying files, by just deleting them entirely. There's no place for comments in the AST. 

The fix is to switch the file-overwriting part in kea-typegen to babel, but... you know how those todo lists go. Might be time to tackle this though, as it has come up more and more.

**Comment by Jaspreet-singh-1032** [comment]
@mariusandra okay , so is there any way to prevent this permanently. and can i get those comments back or we have to add them manually ? that i don't think will be the right way.

**Comment by neilkakkar** [comment]
I see!

You should be able to recover them by:

`git checkout master -- <filename>`

**Comment by Jaspreet-singh-1032** [comment]
@neilkakkar thanks this worked. i just had to copy path of all files to run this command :sweat_smile:

**Comment by clarkus** [comment]
When a single step exists in the query builder, we'd hide the remove action (trashcan icon). This would be sufficient for limiting a user's ability to remove that first step.

**Comment by neilkakkar** [comment]
Guess that overrides my review, @Jaspreet-singh-1032 ! I'd prefer doing as Chris says :)

**Comment by Jaspreet-singh-1032** [comment]
@neilkakkar @clarkus sure, as per you think.

**Comment by Jaspreet-singh-1032** [comment]
https://user-images.githubusercontent.com/69707565/138299180-2ae2b2b0-9175-4673-ad7b-401e27c22ed6.mp4

**Comment by Jaspreet-singh-1032** [comment]
@neilkakkar should we need to remove that logic of adding first step ? there might a case if step gets deleted or there is not any step due to any reason. so user atleast should be able to add first one. what do you think ?

**Comment by neilkakkar** [comment]
Makes sense! Just the remaining review changes then^

**Comment by neilkakkar** [comment]
Thanks for the PR, Jaspreet!

It should show up in Cloud in ~1 hour, and on self-hosted instances in the next release.

**Comment by Jaspreet-singh-1032** [comment]
@neilkakkar thanks. it was great experience.

**Pull request merged**
