### PR TITLE
feat: adding capture events for created and deleting org domains under authentication domains and sso

### PR DESCRIPTION
**Pull request by surbhi-posthog**
## Problem

We need capture events for add and deleting domains under Authentication Domain and SSO

## Changes

No UX changes, just added logs in the backend

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud: Yes

## How did you test this code?
Tested locally on: http://localhost:8000/project/1/settings/project

Added unit test and verified that they pass:

```

posthog/api/test/test_organization_domain.py ......................                                                    [100%]
====================================================== inline snapshot =======================================================

============================== 22 passed in 2.44s ==============================
```

Verified capture events showed up under the activity tab
image

### CODE REVIEW

**Review by zlwaterfield — COMMENTED** [review]
Awesome, this looks good. And for this one your should be able to test it here: https://github.com/PostHog/posthog/blob/master/posthog/api/test/test_organization_domain.py#L87. Basically adding the mock (like the example I sent you). You can [test locally](https://posthog.com/handbook/engineering/developing-locally) with `pytest`

**Comment by surbhi-posthog** [comment]
yes ofc, just added the tests.

**Comment by surbhi-posthog** [comment]
> Awesome, this looks good. And for this one your should be able to test it here: https://github.com/PostHog/posthog/blob/master/posthog/api/test/test_organization_domain.py#L87. Basically adding the mock (like the example I sent you). You can [test locally](https://posthog.com/handbook/engineering/developing-locally) with `pytest`

Yes of course, I just updated the tests

**Review by zlwaterfield — APPROVED** [review]
Awesome, looks great!

**Comment by zlwaterfield** [comment]
Good to merge once tests pass.

**Pull request merged**
