### PR TITLE
Do not request time to convert funnel if there are less than 2 steps

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Time to convert requires at least 2 funnel steps, otherwise the API will error from it. 

Screen Shot 2021-07-14 at 10 45 36 AM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by paolodamico** [comment]
UI-wise I think we could use something similar to the empty graph state that @clarkus built for when you only have one step in the funnel. Wdyt?

**Review by alexkim205 — APPROVED** [review]

**Comment by clarkus** [comment]
> UI-wise I think we could use something similar to the empty graph state that @clarkus built for when you only have one step in the funnel. Wdyt?

I think we can probably use the exact same empty state. It's all about directing the user to compose at least two steps before visualizations are enabled. Viz type is secondary and as long as there are at least two steps defined. https://github.com/PostHog/posthog/issues/3982

**Comment by alexkim205** [comment]
> UI-wise I think we could use something similar to the empty graph state that @clarkus built for when you only have one step in the funnel. Wdyt?

Hey @paolodamico could you link to this mockup? I mustve missed it in the funnel soup

@liyiy If you don't mind, I could also take a look at this since I'm already refactoring the FunnelsViz a bit already?

**Comment by liyiy** [comment]
> > UI-wise I think we could use something similar to the empty graph state that @clarkus built for when you only have one step in the funnel. Wdyt?
> 
> Hey @paolodamico could you link to this mockup? I mustve missed it in the funnel soup
> 
> @liyiy If you don't mind, I could also take a look at this since I'm already refactoring the FunnelsViz a bit already?

yep, I saw that you already had this going on in your refactor so I didn't try to componentize it, just wanted to supply a quick fix until then 😄

**Comment by paolodamico** [comment]
The latest mockup for this can be found on https://github.com/PostHog/posthog/issues/3982, but 100% makes sense to do this as a separate PR

**Pull request merged**
