### PR TITLE
Remove expensive person header logic allocation

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

maintains behaviour introduced in #6403 without the performance impact and complexity of allocating a logic for each person to be displayed

## How did you test this code?

unit tests and running it locally

### CODE REVIEW

**Comment by pauldambra** [comment]
@mariusandra @Twixes small change to review for whoever has time first. Applying the "fool me once, shame on you. fool me twice, shame on me" principle... #6403 has already caused/been involved in two bugs, let's not wait for three :). This keeps the behaviour without the logic

**Review by mariusandra — APPROVED** [review]
LGTM as a refactor, just one rename suggestion inline that I'd stall this for (because editors sort files by case sometimes, and it'll be annoying to match them). Feel free to merge after.

However, we can complicate life and clean a lot of things with `PersonHeader` still:

- I'd rename this component from `<PersonHeader />` into something more descriptive. "Header" in a react component name tells me it's some kind of layout element, not a inline element decorator that can be used anywhere. Something like `Person` or `PersonDisplay` or `PersonDecorator` or ...?
- This is now a very decoupled component, so `lib/**/Person*` is a better place for it. Maybe. `lib/decorators/`? 🤔 🤷‍♂️ 
- Storybook would love to one day include this component and its variations in it.
- I think the tests on these `as*` functions are fine, though there is a very strong opportunity here to do storybook-based testing instead. This is not wired up, but we could just take snapshots of each story, and flag for review if anything changes anywhere. There would then be a page listing all the permutations of this component, which would be snapshot, instead of this long test.

**Comment by mariusandra** [comment]
oh, and thanks for taking this on proactively! 😍

**Comment by pauldambra** [comment]
"However, we can complicate life and clean a lot of things with PersonHeader still:"

All good suggestions! 🙌 -> #6537 in order to avoid scope creep on this

**Pull request merged**
