### PR TITLE
fix: fixes command palette scrolling issue

### LINKED ISSUE #2640: Command palette scrolling issue
## Bug description

Using the keyboard arrow keys scrolls the underlying page.
image

## Expected behavior

Using the arrow keys on the command palette should not scroll the page beneath.

## How to reproduce

1. Open the command palette
2. Open the share feedback command
3. Press the top and bottom arrow keys

## Environment
Cloud

### PR DESCRIPTION
**Pull request by suresh1999**
closes #2640

## Changes
Added event.preventDefault() to cancel the default action for the event. This prevent the default page scrolling action.

*If this affects the frontend, include screenshots.*  
img

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by EDsCODE** [comment]
Hi Suresh! Thanks for picking this up. Could you run prettier on the file (or just delete the semicolons) and commit again? Thanks

**Comment by suresh1999** [comment]
> Hi Suresh! Thanks for picking this up. Could you run prettier on the file (or just delete the semicolons) and commit again? Thanks

Thanks for pointing it. Just missed to run prettier.

Updated the PR @EDsCODE

**Comment by paolodamico** [comment]
Thanks for your contribution @suresh1999, could you email yakko[at]posthog[.]com so we can send some merch over to you?

**Comment by suresh1999** [comment]
> Thanks for your contribution @suresh1999, could you email yakko[at]posthog[.]com so we can send some merch over to you?

Sure. Thanks for accepting my PR.

**Pull request merged**
