### PR TITLE
Revert "Insights short share URL"

### PR DESCRIPTION
**Pull request by paolodamico**
Reverts PostHog/posthog#4513

### CODE REVIEW

**Comment by Twixes** [comment]
Why revert?

**Comment by paolodamico** [comment]
Still not sure about this, but wanted to get a head start with the checks. I'm considering just relying on the PK instead of introducing this short ID concept. Main reason being that we heavily rely on this ID in the frontend and the refactor might not be worth it. What are your thoughts @Twixes ?

**Comment by Twixes** [comment]
We shouldn't really be using autoincremented IDs anywhere outside of server internals, as they reveal sensitive usage information, so I really appreciate the short ID concept – it seems friendly for users and better for us. I'd keep it. Especially since it was merged already.

**Comment by paolodamico** [comment]
Yeah I guess that makes a lot of sense. Will wait for @macobo's input before making a final ruling on this or #4558, but leaning towards keeping it too.

**Pull request closed without merging**
