### PR TITLE
Fix tables on shared dashboards

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Tables on shared dashboards would spin endlessly. This fixes it but not 100% sure why

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by EDsCODE** [comment]
Typing error

**Comment by EDsCODE** [comment]
The above is just a typing issue still where the aggregated_value field isn't included in IndexedTrendResults.

I did test this problem briefly and I'm not quite sure how to repro. Could I get the repro steps? I tried a shared dashboard with a table on both clickhouse and postgres locally

**Comment by timgl** [comment]
@EDsCODE fixed the typing issue although ugly. See https://app.posthog.com/shared_dashboard/uUMEBaCRjyj4VtOOWL2j1Cx8jvxs6Q / https://app.posthog.com/dashboard/3182 for an example of dashboard that fails.

Note: you do need to look at the shared dashboard in incognito mode I think to reproduce this.

**Comment by timgl** [comment]
@EDsCODE would you mind having another look? The failing e2e test is failing on other PRs as well

**Review by EDsCODE — APPROVED** [review]
The table still seems to be working for me but this change is also more accurate for the actual type so lgtm

**Pull request merged**
