### PR TITLE
Add plugins to instance status report

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

Adds some plugin reporting to our `instance status report` event.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
On board with this. :+1: I did modify the type of plugins usage data to include the number of teams per plugin.

**Comment by yakkomajuri** [comment]
I guess we do track usage somewhat with other mechanisms, but would it not be good to also get names with this?

**Comment by Twixes** [comment]
I don't quite understand, this does get names?

**Comment by yakkomajuri** [comment]
hahahaha I got confused by my own naming, quickly looked at this:

```
self.assertEqual(report["plugins_installed"], {"Installed but not enabled": 1, "Installed and enabled": 1})
```

And thought we're now just getting stats on plugins that are installed and enabled

**Pull request merged**
