### PR TITLE
fix: insight filters and UI not in sync

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

Right now the filters shown in the header of an insight are not editable in a notebook. This means that there is no way to update the time range of a query.

Screenshot 2023-10-11 at 16 49 06
 
## Changes

- Add the view prop to show the filters, but in the settings component not the insight.
- Add custom CSS to remove extra padding & add a margin to other settings

**Note:** Sacrificing the title above the display filters because that would mean adding an entirely separate `Query` component which I'm not sure is worth the extra complexity until we're certain this is how insight editing will look going forward

There is a bug with this implementation that means the query is never updated. There is an internal hook in `setQuery` that is not being called _somewhere_

https://github.com/PostHog/posthog/assets/6685876/c84ec50d-94cb-4d97-9f20-f4af495375db

## How did you test this code?

Visually

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
The code looks good, but this grouping of options is quite dubious:
Screenshot 2023-10-12 at 16 19 35
The time range etc. settings look as if they belonged to "Sampling". Their layout and that of the existing query definition settings are from different worlds.
In [these PostHog 3000 mocks](https://www.figma.com/file/uNuL5XDnOqasYuK0yfpnmV/PostHog-3000?type=design&node-id=991-17006&mode=design) from Cory, he proposed putting the options _inside_ the "widget", just at the bottom to take away the clutter from the top.
Screenshot 2023-10-12 at 16 25 01
That's one way to do it. The other is that we can put them in the side panel, ideally at the top or sticky at the bottom – but with the same layout (headings and all) as all the other settings.

**Comment by benjackwhite** [comment]
@Twixes I think this should be the "lets get it working" solution for now and we tackle the proper solution in a way that works everywhere. Otherwise we will get stuck

**Comment by Twixes** [comment]
Yeah yeah @benjackwhite that's a comment but not a blocker.

**Comment by daibhin** [comment]
Still working on this but just blocked by the Product Analytics work to fix queries (coming next week)

**Pull request closed without merging**
