### PR TITLE
2248 remove pandas numpy

### LINKED ISSUE #2248: Get rid of pandas and numpy
## Is your feature request related to a problem?

There's only 2 files where we use pandas, but pandas is 49MB and numpy is another 86MB, slowing down builds massively.

## Describe the solution you'd like

Replace pandas with a pure SQL/Python solution in
- posthog/queries/trends.py
- posthog/queries/sessions.py

Both of those have equivalent examples in Clickhouse (ee/clickhouse) that don't use Pandas.

## Describe alternatives you've considered

Continue using Pandas and clogging builds

### PR DESCRIPTION
**Pull request by cpankajr**
## Changes
Closes #2248 
The initial version of code;
I have removed pandas dependency from session.py and trends.py;

Look forward to your feedback.

I will add few comments by tomorrow for a better understanding

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by timgl** [comment]
Thanks for getting started on this! 

Looks like there is a legit typecheck error [here](https://github.com/PostHog/posthog/pull/2997/checks?check_run_id=1732957918) and legit test failures [here](https://github.com/PostHog/posthog/pull/2997/checks?check_run_id=1732958084)

**Comment by cpankajr** [comment]
@timgl I have updated the PR with changes.

**Comment by timgl** [comment]
@cpankajr Awesome, thanks for doing this. Feel free to email yakko [at] posthog [dot] com for some free contributor merch!

**Comment by cpankajr** [comment]
Yay!! @timgl Thanks for merging!! Surely will connect with @yakkomajuri over email !!

**Pull request merged**
