### PR TITLE
chore(deps): Remove unused Python requirements

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Saw #21503 was opened to update `idna`, but that dependency actually seems to be unused.

## Changes

I think all of the below production Python dependencies are unused:
`defusedxml`, `idna`, `amqp`, `gevent`, `geoip2`, `importlib-metadata`, `kafka-helper`, `openapi-spec-validator`, `parso`, `pexpect`, `pickleshare`, `python3-saml`, `requests-oauthlib`, `urllib3`

### CODE REVIEW

**Comment by webjunkie** [comment]
Reminds be of recent post:

https://news.ycombinator.com/item?id=39724132

**Comment by Twixes** [comment]
Oh, that's exactly the kind of thing I was thinking would be useful @webjunkie! Thanks, used it and found a few more seemingly-unused deps (though `deptry` seems to ignore deps that are used as Django middleware and such)

**Comment by Twixes** [comment]
(`test_reload_external_data_source` is currently failing on `master`, otherwise this is green)

**Comment by bretthoerner** [comment]
I've barely touched Python here, so I'm not sure how confident you should be in my review. 😅 But the two deps I have touched (`pyarrow` and `temporalio`) are still there.

> (`test_reload_external_data_source` is currently failing on `master`, otherwise this is green)

So the 26 failed checks are just unrelated? I didn't dig in yet, tbh.

**Comment by Twixes** [comment]
Yeah, that was some bout of Cypress flakiness.

**Review by bretthoerner — APPROVED** [review]
[Conflicts now](https://github.com/PostHog/posthog/pull/21648) 😢 but LGTM

**Pull request merged**
