### PR TITLE
514 trends people bug

### PR DESCRIPTION
**Pull request by Tmunayyer**
## Changes
Resolves issue: #514 

- Updates `day` format to include time if minute or hour interval is selected. This was to easily send the time upon a /people request with minimal changes to frontend.
- Updates to the util.py function `relative_date_parse` to account for this new time attached to a `date_from` and `date_to`.
- Some conditional logic to handle the relativity in `_filter_events` in action.py. Previously it would always add 1 day to the date. This is the reason at the hour/minute interval we would see a days worth of people. It now account for hour/minute interval.
- Additional test to ensure the correct people and amount of people are retrieved.

## Checklist
- [ ] Code reviewed
- [ ] QA'd

### CODE REVIEW

**Comment by timgl** [comment]
@Tmunayyer Hm this does fix the issue for minutes/hours but not weeks/months. In fairness that also wasn't specified in the original ticket so let me know whether you fancy fixing this here or whether you want to open a new ticket for that?

**Comment by Tmunayyer** [comment]
@timgl My bad, I must been out of it when testing this. For some reason I thought it was working haha. Im close to a solution and I'll push changes to this branch here.

**Comment by Tmunayyer** [comment]
@timgl Support now added for weeks and months.

**Comment by Tmunayyer** [comment]
After I got everything working, I noticed this warning popping up in the API logs:

`
/Users/thomas/Desktop/posthog/posthog/env/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1310: RuntimeWarning: DateTimeField Event.timestamp received a naive datetime (2020-04-03 00:00:00) while time zone support is active.
`

This was causing a lot of unnecessary noise and was really just annoying. I decided to try and resolve it in this PR since it would put the repo in an annoying state with noisy API logs. What was causing it was this pandas function to create the `time_index` within the `group_events_to_date`:

`
line 169: pd.date_range(date_from, date_to, freq=freq_map[interval])
`

I altered the `_get_dates_from_request` function to output `pd.Timestamps`. According to documentation [they are identical to the python `datetime` types](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html) so side affects should be none. There were minor changes to handle "all ranges" passing `None` as `date_from` and reconciling the `_group_events_to_date` to handle the new input formats.

This warning is still showing up in the test logs but it doesn't seem to be related to what I was working on here. Because of that, I'll leave those so this PR doesn't touch too many things.

**Comment by timgl** [comment]
@Tmunayyer Awesome!

**Pull request merged**
