### PR TITLE
Part 3: Add tags to FF and Cohorts Backend

### PR DESCRIPTION
**Pull request by alexkim205**
Part 1: https://github.com/PostHog/posthog/pull/8528
Part 2: https://github.com/PostHog/posthog/pull/8529

### PR dependency:

Part 1 <- Part 2 <- Part 3

## Changes

Adds new tagging functionality to:
- [x] Feature Flags
- [x] Cohorts

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
This looks so clean after all the work in parts 1 and 2

**Comment by alexkim205** [comment]
Needs to be cleaned up, commenting to prevent PR from being garbage collected

**Comment by alexkim205** [comment]
Blocked on https://github.com/PostHog/posthog/pull/8824 and https://github.com/PostHog/posthog/pull/8825

**Comment by alexkim205** [comment]
lets put a pin on this for now. commenting so its not autoclosed

**Pull request closed without merging**
