### PR TITLE
Turn off cypress recording for now

### PR DESCRIPTION
**Pull request by fuziontech**
We are racking up the cypress recordings, let's turn them off for now

### CODE REVIEW

**Review by EDsCODE — APPROVED** [review]

**Comment by timgl** [comment]
I think it is worth paying $90/month to make these tests run in 4 minutes rather than 12 minutes, or am I misunderstanding what's going on here?

**Comment by EDsCODE** [comment]
Not sure why this is the case but it looks like only recorded tests can be parallelized (unless I'm reading the docs incorrectly) which is why @fuziontech disabled both features altogether

**Comment by fuziontech** [comment]
Yup, you got it. For parallel running we need recording set to true. I think the $90 is totally worth it. I was going to reach out and see if we can’t make a deal since we are OSS as well

**Comment by timgl** [comment]
Sounds like we can close this then?

**Pull request closed without merging**
