### PR TITLE
Fix prop filter not formatting properly

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- when cohort filters were placed after prop filters in any of the insights,  clickhouse query wasn't firing. This was due to a spacing issue it seems as sql parsing fixed it

*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by timgl** [comment]
Hm weird we didn't have a test for trends + cohort. might be worth adding?

**Comment by EDsCODE** [comment]
> Hm weird we didn't have a test for trends + cohort. might be worth adding?

I think we do if you're referring to this test `test_filter_events_by_cohort` test_trends.py line 183. What's weird is that this was a specific formatting issue. Let me take a look again and see if i can resolve it without randomly formatting this query

**Comment by EDsCODE** [comment]
@timgl found the issue. It was a spacing issue in the prop filter function. I patched it with a better joining pattern. Lmk if there's a configuration of the trend test that's missing. It seems like the cohort test does exist

**Comment by timgl** [comment]
Hm just surprised there were no failing tests before but it did break on production?

**Comment by paolodamico** [comment]
Won't be able to test this locally, will make sure it works on prod after deploy.

**Comment by EDsCODE** [comment]
Oh yeah the tests didn't fail because we don't test every combination/ordering of filters. So this broke when you added a property filter and then a cohort filter in that specific order

**Comment by EDsCODE** [comment]
bump @timgl

**Pull request merged**
