### PR TITLE
fix(insights): Fix dashboard HogQL tables and others

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

- some HoqQL based insights don't display
- `dataNodeLogic` does not get initialized with the same key consistently
- cached results do not get passed consistently to the logics
- cached results do not get used by logics in some cases even if passed
- data table does not display from cached results, because they miss `columns`

## Changes

- fix most of the above problems

Todos:

- [x] when flipping back and forth, insight is vanashing in dashboard depending on what dashboard was loaded first FIXED
- [x] also a loop of reloading hogql insight at one point FIXED
- [x] going to detail page and back will show the insight empty on the dashboard, presumably dataNodeLogic does not contain the cached data anymore in its state or something is still wired up wrong
- [x] snapshots are wrong because fixtures contain nested results which is not the way the endpoint delivers it
- [ ] ~lots of `Error: [KEA] Can not find path "scenes.dashboard.dashboardLogic.10" in the store.`... not sure if caused by this branch~ PRESENT IN MASTER ☹️ 

## Does this work well for both Cloud and self-hosted?

n/a

## How did you test this code?

How to test this:

- use the SQL tab to make a HogQL query that display in a table
- add to two dashboards
- move between the dashboards, it should load nicely and the network tab should show just queries to /insights endpoint not to /query

### CODE REVIEW

**Comment by webjunkie** [comment]
@Twixes this is ready now as fix for the HogQL table... fixing other insights to display nicely would be a follow up

Please check regarding `columns`.. they need to be present in the insight endpoint, otherwise the table wouldn't display. I believe your updated caching also takes them into account. But maybe there's another way I didn't see.

**Review by Twixes — COMMENTED** [review]
The code looks good, but I'm not sure about the snapshot change

**Comment by webjunkie** [comment]
Found another logic problem here:
Going from the dashboard HogQL insight to its detail page and back and forth, it will show empty on the dashboard. Seems like some state is overwritten, but I couldn't figure it out so far.

**Comment by mariusandra** [comment]
Looks like we're getting legit snapshot errors: 
image

**Comment by webjunkie** [comment]
Yes that are the problems I meant.. Fixed a thing in one area, broke things in another.

**Comment by webjunkie** [comment]
Finally green. I needed to make sure `result` vs. `results` is handled better in some places, which brought other problems with it because at least one logic now was happily assuming the now-available results to always be funnels(?).

**Review by mariusandra — APPROVED** [review]
Code looks good and nothing immediately broke when I clicked around 👍 ... though obviously with the state of insight logics it's hard to say how deep the hole goes. Let's try?

**Pull request merged**
