### PR TITLE
fix: pause error patch

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

https://github.com/PostHog/posthog/issues/21874

## Changes

Applies patch suggested in https://github.com/rrweb-io/rrweb/pull/1462

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
🚢

**Comment by marandaneto** [comment]
@daibhin should we remove this patch now https://github.com/PostHog/posthog/pull/21898 ?

**Comment by marandaneto** [comment]
Shouldn't the patches live in the SDK instead? https://github.com/PostHog/posthog-js/tree/main/patches

**Comment by daibhin** [comment]
@marandaneto I typically remove the patches when we upgrade the version. That one we probably could remove but it's not doing any harm either.

We actually have patches in two places 😓 Because we don't have a fork we apply patches depending on whether it is a recording or playback issue (in this case it's playback so the `posthog` repo)

**Comment by marandaneto** [comment]
> @marandaneto I typically remove the patches when we upgrade the version. That one we probably could remove but it's not doing any harm either.
> 
> 
> 
> We actually have patches in two places 😓 Because we don't have a fork we apply patches depending on whether it is a recording or playback issue (in this case it's playback so the `posthog` repo)

Ahhh that makes sense, thanks.

**Pull request merged**
