### PR TITLE
Automatically enable debug mode for posthog-js on SELF_CAPTURE

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

If `SELF_CAPTURE = True` (i.e. on local development instances), we automatically enable `debug` mode on posthog-js so that all events are logged to the console.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by macobo** [comment]
Q: What's the goal of setting this though? What sort of insights are you looking for.

As for the typescript error - your change made another (ignored) error change locations. You'll need to either update `.ts-strict-blacklist` or fix it :)

**Comment by paolodamico** [comment]
The TS error has been addressed in the posthog-js library, so tests should now pass. The goal of this PR is that if you're running on development, you see all the posthog capture requests in your console. This can help test and debug event instrumentation.

**Comment by macobo** [comment]
Seems a bit noisy but sure.

**Review by macobo — APPROVED** [review]

**Comment by paolodamico** [comment]
Will merge and we can remove if we realize it's not helpful.

**Pull request merged**
