### PR TITLE
Closes #358 don't autosave funnels

### LINKED ISSUE #358: Display day of week in hover over labels in graphs
**Is your feature request related to a problem? Please describe.**
When daily data is visualized as a graph, the day of the week is likely to explain why the data might be changing - any B2B software being tracked with PostHog is likely to dip in usage at weekends.

Currently we do not show this.

**Describe the solution you'd like**

In this view, it'd be nice to indicate the day of the week in the label:

Screenshot 2020-03-15 at 10 24 05

**Describe alternatives you've considered**
Pull open a calendar or engage brain.

### PR DESCRIPTION
**Pull request by timgl**
image

Funnels should "feel" a lot faster, plus be less glitchy

### CODE REVIEW

**Comment by Tannergoods** [comment]
Very small bug that when you have no funnels set up it flashes "you don't have any actions set up"  before disappearing.

+ it breaks when I click add step

**Comment by Tannergoods** [comment]
Bug when moving stages, ordering # doesn't work.

Posthog

When refreshed the funnel does not load cannot refresh to stop this

Posthog

**Comment by Tannergoods** [comment]
This is working as expected apart from one bug. I am unsure if this is the expected behavior but it is showing the first unique event by user e.g.

Posthog

Vs the actual total:

Posthog

I would expect it to perhaps show the total?

**Comment by timgl** [comment]
@Tannergoods Yeah the counts are unique, as you're interested in how many people made it through the funnel, not necessarily how often they have

**Pull request merged**
