### PR TITLE
Show session player icons as greyed out if visited

### PR DESCRIPTION
**Pull request by macobo**
## Changes

What it looks like:

Screenshot from 2020-11-25 23-09-00
Screenshot from 2020-11-25 23-08-52

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by GalDayan** [comment]
I think it will be great if the visiting state will be saved in backend.
I mean, I think your code saves the "visiting state" only in front end, and on every page refresh, it will init.

PMs are working with multiple tabs, and it very common they forget where was the tab they worked on, and they just open a new one :)

**Comment by macobo** [comment]
The goal is to get something out and testable ASAP - adding new tables + schema for tracking this _might_ be needed in the long-term, but using in-built browser features will help us get this done without adding complexity elsewhere.

**Comment by mariusandra** [comment]
I think you can probably use the `Link` tag here? It should abstract away the `onClick` part and even make CMD/CTRL+click work.

**Comment by macobo** [comment]
Thanks @mariusandra, great note. Done!

**Review by mariusandra — APPROVED** [review]

**Pull request merged**
