### PR TITLE
Closes #665 Allow editing of frontend elements on actions in app

### LINKED ISSUE #665: Show selectors, link href etc in actions in PostHog
**Is your feature request related to a problem? Please describe.**
At the moment, the only way to know what autocapture events an action matches is by opening the popup

**Describe the solution you'd like**
Show the selector, href etc in posthog itself.

### PR DESCRIPTION
**Pull request by timgl**
## Changes

- Show href/text/selector/url under frontend element
- If nothing is inputted, force use of toolbar to select something.

## Checklist
- [x] All querysets/queries filter by Team
- [ ] Code reviewed
- [ ] QA'd

### CODE REVIEW

**Review by EDsCODE — COMMENTED** [review]
Works on initial load and display. However, if you are viewing the frontend element, click to a pageview tab and then click back to frontend element, the fields will be cleared. I'm assuming it should remain filled

**Comment by timgl** [comment]
Fixed, thanks!

**Comment by EDsCODE** [comment]
Still getting the behavior described above

**Comment by timgl** [comment]
@EDsCODE The only field that got cleared for me was the URL field, which I've now fixed. Are the other ones being cleared for you too?

**Review by EDsCODE — APPROVED** [review]
works after latest commit!

**Pull request merged**
