### PR TITLE
Handle ChunkLoadError better

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

This should stop ChunkLoadError (which seems to happen when a user doesn't do a full page reload including assets after we redeploy the app) from spamming our Sentry issues list.

### CODE REVIEW

**Comment by timgl** [comment]
I'm not sure this actually fixes the issue from a users point of view, I think people still tend to get stuck until they hard-refresh. Have you been able to reproduce that?

**Comment by Twixes** [comment]
This does the hard refresh for them though. Not sure I understand how they get stuck?

**Review by mariusandra — APPROVED** [review]

**Comment by mariusandra** [comment]
@timgl if I understand correctly, the fix I did a long time ago still refreshes the page for the users, yet we threw the error into sentry regardless. Now the error is swallowed if we handle it.

I tried locally - started webpack and closed it, then opened another page from the sidebar. The page refreshed.

**Comment by timgl** [comment]
@mariusandra Perfect!

**Pull request merged**
