### PR TITLE
feat(insights): first time for user math type for Trends

### PR DESCRIPTION
**Pull request by skoob13**
## Problem

The PR implements an aggregation type for Trends insights, which only counts events if users do them for the first time. It aims to replace the last stateful deprecated [pipeline plugin](https://github.com/PostHog/first-time-event-tracker).

**Demo**

Related to #15945.

## Changes

The PR extends aggregation operations with a new type. It generates queries like:

```sql
SELECT
    groupArray(1)(date)[1] AS date,
    arrayFold((acc, x) -> arrayMap(i -> plus(acc[i], x[i]), range(1, plus(length(date), 1))), groupArray(total), arrayWithConstant(length(date), reinterpretAsFloat64(0))) AS total,
    if(ifNull(greaterOrEquals(row_number, 25), 0), '$$_posthog_breakdown_other_$$', breakdown_value) AS breakdown_value
FROM
    (SELECT
        arrayMap(number -> plus(toStartOfDay(assumeNotNull(toDateTime('2024-07-17 00:00:00'))), toIntervalDay(number)), range(0, plus(coalesce(dateDiff('day', toStartOfDay(assumeNotNull(toDateTime('2024-07-17 00:00:00'))), toStartOfDay(assumeNotNull(toDateTime('2024-07-24 23:59:59'))))), 1))) AS date,
        arrayMap(_match_date -> arraySum(arraySlice(groupArray(count), indexOf(groupArray(day_start) AS _days_for_count, _match_date) AS _index, plus(minus(arrayLastIndex(x -> equals(x, _match_date), _days_for_count), _index), 1))), date) AS total,
        breakdown_value AS breakdown_value,
        rowNumberInAllBlocks() AS row_number
    FROM
        (SELECT
            sum(total) AS count,
            day_start,
            breakdown_value
        FROM
            (SELECT
                count() AS total,
                toStartOfDay(min_timestamp) AS day_start,
                breakdown_value AS breakdown_value
            FROM
                (SELECT
                    min(timestamp) AS min_timestamp,
                    minIf(timestamp, and(greaterOrEquals(timestamp, toStartOfDay(assumeNotNull(toDateTime('2024-07-17 00:00:00')))), in(person_id, (SELECT
                                            person_id
                                        FROM
                                            raw_cohort_people
                                        WHERE
                                            and(equals(cohort_id, 2), equals(version, 71)))))) AS min_timestamp_with_condition,
                    argMin(ifNull(nullIf(toString(properties.$browser_language), ''), '$$_posthog_breakdown_null_$$'), timestamp) AS breakdown_value
                FROM
                    events AS e SAMPLE 1
                WHERE
                    and(lessOrEquals(timestamp, assumeNotNull(toDateTime('2024-07-24 23:59:59'))), equals(event, '$pageview'))
                GROUP BY
                    person_id
                HAVING
                    equals(min_timestamp, min_timestamp_with_condition))
            GROUP BY
                day_start,
                breakdown_value)
        GROUP BY
            day_start,
            breakdown_value
        ORDER BY
            day_start ASC,
            breakdown_value ASC)
    GROUP BY
        breakdown_value
    ORDER BY
        if(equals(breakdown_value, '$$_posthog_breakdown_other_$$'), 2, if(equals(breakdown_value, '$$_posthog_breakdown_null_$$'), 1, 0)) ASC,
        arraySum(total) DESC,
        breakdown_value ASC)
WHERE
    notEquals(breakdown_value, NULL)
GROUP BY
    breakdown_value
ORDER BY
    if(equals(breakdown_value, '$$_posthog_breakdown_other_$$'), 2, if(equals(breakdown_value, '$$_posthog_breakdown_null_$$'), 1, 0)) ASC,
    arraySum(total) DESC,
    breakdown_value ASC
LIMIT 50000
```

There is one edge case though: if there is more than one event with the same timestamp but different event properties, the query outputs data by all different values.

For example, there are two events:
- 2024-07-24 20:00:00 and $browser is Chrome
- 2024-07-24 20:00:00 and $browser is Safari

The query will output exactly one event for a filter that uses the `$browser` property with either of the above values. This is the correct behavior IMO, but let me know if you have another opinion. We can use `uuid` in the HAVING clause above to compare, which guarantees that only the first recorded event will match.

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Unit tests, manual testing and added additional tests.

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
Not sure if my expectations here are correct, but shouldn't a query like this always return something?
Screenshot 2024-07-25 at 11 38 34

**Comment by skoob13** [comment]
> Not sure if my expectations here are correct, but shouldn't a query like this always return something?

@thmsobrmlr thank you for spotting the bug. It must output events for your query. I've fixed the problem and added more tests.

**Comment by thmsobrmlr** [comment]
I'm just trying to review this and get the following error when trying to test the feature in the UI:
```
2024-07-26T10:57:14.175159Z [error    ] Error processing query for team 1 query 4f681064-3b05-4ded-889f-f547019d4714 [posthog.clickhouse.client.execute_async] ip=127.0.0.1 pid=8033 request_id=4f776518-351e-4aa7-add4-1e9d907e4323 task_id=700ebb62-ab25-46bb-b335-a5c493e592e6 task_name=posthog.tasks.tasks.process_query_task tid=13932736512
Traceback (most recent call last):
  File "/Users/thomas/Posthog/posthog/posthog/clickhouse/client/execute_async.py", line 176, in execute_process_query
    results = process_query_dict(
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Posthog/posthog/posthog/api/services/query.py", line 45, in process_query_dict
    model = QuerySchemaRoot.model_validate(query_json)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Posthog/posthog/env/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 29 validation errors for QuerySchemaRoot
TrendsQuery.series.0.EventsNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[BaseMathType]]]
  Input should be 'total', 'dau', 'weekly_active', 'monthly_active' or 'unique_session' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.EventsNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[PropertyMathType]]]
  Input should be 'avg', 'sum', 'min', 'max', 'median', 'p90', 'p95' or 'p99' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.EventsNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[CountPerActorMathType]]]
  Input should be 'avg_count_per_actor', 'min_count_per_actor', 'max_count_per_actor', 'median_count_per_actor', 'p90_count_per_actor', 'p95_count_per_actor' or 'p99_count_per_actor' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.EventsNode.math.literal['unique_group']
  Input should be 'unique_group' [type=literal_error, input_value='first_time_for_user', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.EventsNode.math.literal['hogql']
  Input should be 'hogql' [type=literal_error, input_value='first_time_for_user', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.ActionsNode.id
  Field required [type=missing, input_value={'custom_name': None, 'ev... None, 'response': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
TrendsQuery.series.0.ActionsNode.kind
  Input should be 'ActionsNode' [type=literal_error, input_value='EventsNode', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.ActionsNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[BaseMathType]]]
  Input should be 'total', 'dau', 'weekly_active', 'monthly_active' or 'unique_session' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.ActionsNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[PropertyMathType]]]
  Input should be 'avg', 'sum', 'min', 'max', 'median', 'p90', 'p95' or 'p99' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.ActionsNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[CountPerActorMathType]]]
  Input should be 'avg_count_per_actor', 'min_count_per_actor', 'max_count_per_actor', 'median_count_per_actor', 'p90_count_per_actor', 'p95_count_per_actor' or 'p99_count_per_actor' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.ActionsNode.math.literal['unique_group']
  Input should be 'unique_group' [type=literal_error, input_value='first_time_for_user', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.ActionsNode.math.literal['hogql']
  Input should be 'hogql' [type=literal_error, input_value='first_time_for_user', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.ActionsNode.event
  Extra inputs are not permitted [type=extra_forbidden, input_value='$pageview', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
TrendsQuery.series.0.ActionsNode.limit
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
TrendsQuery.series.0.ActionsNode.orderBy
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
TrendsQuery.series.0.DataWarehouseNode.distinct_id_field
  Field required [type=missing, input_value={'custom_name': None, 'ev... None, 'response': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
TrendsQuery.series.0.DataWarehouseNode.id
  Field required [type=missing, input_value={'custom_name': None, 'ev... None, 'response': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
TrendsQuery.series.0.DataWarehouseNode.id_field
  Field required [type=missing, input_value={'custom_name': None, 'ev... None, 'response': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
TrendsQuery.series.0.DataWarehouseNode.kind
  Input should be 'DataWarehouseNode' [type=literal_error, input_value='EventsNode', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.DataWarehouseNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[BaseMathType]]]
  Input should be 'total', 'dau', 'weekly_active', 'monthly_active' or 'unique_session' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.DataWarehouseNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[PropertyMathType]]]
  Input should be 'avg', 'sum', 'min', 'max', 'median', 'p90', 'p95' or 'p99' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.DataWarehouseNode.math.lax-or-strict[lax=chain[str,function-plain[to_enum()]],strict=json-or-python[json=function-after[to_enum(), str],python=is-instance[CountPerActorMathType]]]
  Input should be 'avg_count_per_actor', 'min_count_per_actor', 'max_count_per_actor', 'median_count_per_actor', 'p90_count_per_actor', 'p95_count_per_actor' or 'p99_count_per_actor' [type=enum, input_value='first_time_for_user', input_type=str]
TrendsQuery.series.0.DataWarehouseNode.math.literal['unique_group']
  Input should be 'unique_group' [type=literal_error, input_value='first_time_for_user', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.DataWarehouseNode.math.literal['hogql']
  Input should be 'hogql' [type=literal_error, input_value='first_time_for_user', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
TrendsQuery.series.0.DataWarehouseNode.table_name
  Field required [type=missing, input_value={'custom_name': None, 'ev... None, 'response': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
TrendsQuery.series.0.DataWarehouseNode.timestamp_field
  Field required [type=missing, input_value={'custom_name': None, 'ev... None, 'response': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
TrendsQuery.series.0.DataWarehouseNode.event
  Extra inputs are not permitted [type=extra_forbidden, input_value='$pageview', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
TrendsQuery.series.0.DataWarehouseNode.limit
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
TrendsQuery.series.0.DataWarehouseNode.orderBy
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
```

For this query:

```json
{
  "kind": "InsightVizNode",
  "source": {
    "kind": "TrendsQuery",
    "filterTestAccounts": false,
    "series": [
      {
        "kind": "EventsNode",
        "event": "$pageview",
        "name": "Pageview",
        "math": "first_time_for_user"
      }
    ],
    "interval": "hour",
    "trendsFilter": {
      "display": "ActionsLineGraph"
    },
    "dateRange": {
      "date_from": "-24h",
      "date_to": null
    }
  },
  "full": true
}
```

Any idea why this is happening @skoob13 ?

**Comment by skoob13** [comment]
@thmsobrmlr you might need to restart a Celery worker because it looks like the schema changes didn't apply.

**Comment by thmsobrmlr** [comment]
> @thmsobrmlr you might need to restart a Celery worker because it looks like the schema changes didn't apply.

Of course 🙈  Works with a reload, thanks.

**Review by thmsobrmlr — APPROVED** [review]
Works great now!

**Pull request merged**
