### PR TITLE
refactor(experiments): use ad-hoc insights for previews

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

We were creating a new insight for every preview of experiments.

This PR is prep-work for the upcoming replacement of `<LegacyInsightContainer />` with `<Query />`.

## Changes

This PR replaces creating an insight for every preview with ad-hoc insights.

## How did you test this code?

Clicked around to see experiment previews still work. Please check as well - I don't know this part of the app as well as you do.

### CODE REVIEW

**Comment by neilkakkar** [comment]
Thanks for doing this!

On first load, I'm greeted with an empty state that seems broken: 




You might need to keep something in the `afterMount()`

---

I don't think we can keep a single constant PREVIEW_ID , because this clobbers all primary & secondary metrics together:




We want every instance to be independent, so changing one doesn't change the other: both, the preview & the metric definition.

It becomes further quite a bit messy if I choose a funnel metric in the secondary metric box 😬 .

**Comment by thmsobrmlr** [comment]
Thanks for the quick feedback! I'll look into the issue right away.

**Comment by thmsobrmlr** [comment]
So, this is a stacked PR: 
1. master
2. [refactor(insights): remove sampling feature flag](https://github.com/PostHog/posthog/pull/16172)
3. [refactor(experiments): use ad-hoc insights for previews](https://github.com/PostHog/posthog/pull/16183)
4. [refactor(experiments): rename to metric idx](https://github.com/PostHog/posthog/pull/16187)
5. [refactor(experiments): replace legacy insight container with query](https://github.com/PostHog/posthog/pull/16195)

All your feedback seems to get resolved with (5) and my suggestion would be to resolve this by merging in the whole stack instead of trying to fix the intermediate step here.

**Comment by neilkakkar** [comment]
Cool, let me just QA #5 then

**Pull request merged**
