### PR TITLE
Refactor web ingestion onboarding & add bookmarklet

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- Refactors the web ingestion step of the onboarding process to be a bit more clear, and to allow more intuitively connecting PostHog through `posthog-js`. Before & after screenshots below to simplify review.
    ### 🔙 Before
    

    ### 🔜 After
    

- Adds the option to use the bookmarklet to get started quickly and try out PostHog.
    

- Adds basic instrumentation to the bookmarklet.

This PR is only intended to improve the UX, and mostly introduce the bookmarklet to the onboarding process. **The UI still needs a ton of work** (see #2822).

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey! Few thoughts. 

1. The first step is still this:
image

Clicking "Mobile" opens up a choice between iOS, Android, RN and Flutter. Clicking "Web" basically only lets you capture JS events. Gone are the options for direct API ingestion or any kind of backend ingestion with the python, ruby, etc libraries.

I would in this case redo it and make the first steps "Web", "Mobile", "Backend Only"

2. The first time I clicked the bookmarklet there was no confirmation that anything worked. Only when I clicked it again and saw "posthog is already installed on this site" I though it was working. However, I later saw no events coming in and had to look at the console to see "Refused to load the script 'http://localhost:8000/static/array.js' because it violates the following Content Security Policy directive:...". The snippet should probably give a visible error if it fails. I tried with another site and there it worked. This is possibly another issue though.

3. The terminology is off here. The first option is "Snippet". The "Option 2, JS lib" also does autocapture.
image

**Comment by paolodamico** [comment]
Thanks @mariusandra! Totally right, I've addressed your feedback, but as it's quite a bit of changes, would you mind reviewing fully again?

Just worth noting: let's continue the bookmarklet actual functionality conversation on #2823, and I'm not putting a ton of effort on the details of this refactoring non-related to the bookmarklet as we have #2822 coming for the next release.

**Comment by mariusandra** [comment]
What I found now:

1. The style change to the `<code>` blocks look nice in the right places, but it might be worth checking all the places where it's used. Here for example it breaks the design:
image

2. Probably out of scope, but each code block starts with a small half-space before the actual code.
image

3. A space or linebreak would improve things here:
image

4. I think it should be "on your website" in "Just exploring? Immediately run PostHog in your website for some initial exploring."

5. This might require a few additional 👀 to feedback, but I'd replace "server" with "backend". It might not be the best, but seeing "server" here makes me think a bit (ha! :D)... and I'm not sure what to find behind this button. Nginx server metrics perhaps?
image

**Comment by paolodamico** [comment]
All feedback addressed, thanks @mariusandra! Definitely think the "Backend" vs. "Server" vs. _a different term_ conversation is worth having, maybe it could be part of #2822. Will merge after tests pass.

**Pull request merged**
