### PR TITLE
feat: Improve Slack dropdown

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

The new Slack subs have a few less pleasant design issues

## Changes
* Fixed padding of SelectMulti dropdown due to virtual list (see [Storybook](https://61260360a8e859003a7c138b-fjbmfzehmg.chromatic.com/?path=/docs/lemon-ui-lemon-selectmultiple--loading#loading))
* Added loading state to dropdown (see [Storybook](https://61260360a8e859003a7c138b-fjbmfzehmg.chromatic.com/?path=/docs/lemon-ui-lemon-selectmultiple--loading#loading))
* Added warning that Private channels only show if the bot is invited
* Added indicator if the channel is shared externally
* Sorted channels alphabetically
* Fix to ensure channels are loaded if looking at a slack subscription
* Fixed janky flashing when saving a Subscription

Screenshot 2022-06-24 at 21 49 43
Screenshot 2022-06-24 at 21 50 02

Screenshot 2022-06-24 at 21 52 30

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

UI Testing

### CODE REVIEW

**Review by clarkus — DISMISSED** [review]
Looks like good changes overall, but I think we could improve the loading state. The loader is better than no state, but in this case it can actually make the feature feel like it's taking longer to load. I think a better solution would be skeleton loading states... these would mimic the structure of the list with images or svgs or something and then be replaced by the real results once they load. 

I drew a quick example at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=11637%3A49649

The exception would be for really long load times. If we can't be sure that this will load in a shorter amount of time, then we'd need to change to a spinner and a clear message about why things are taking longer to load and and how the user can recover.

Screen Shot 2022-06-24 at 3 09 56 PM

**Comment by benjackwhite** [comment]
@clarkus changed over to Skeleton loaders. I agree with the long loading idea. Perhaps we can consider that when we make the move away from the Ant Select that powers this component. As it stands the loaders we have don't take long.

**Review by mariusandra — APPROVED** [review]
The improvements are good for me. Agreed that this list will not "spin" for too long, and skeletons are the best element to use now.

**Comment by mariusandra** [comment]
A test is failing though :)

**Pull request merged**
