### PR TITLE
fix(dashboard): share modal not closing

### PR DESCRIPTION
**Pull request by abhi12299**
## Problem
Dashboard share modal not being closed on close/done button click and not even on outside click

https://github.com/user-attachments/assets/b87577be-202e-4e65-a8a4-d34190f1481d

## Changes

https://github.com/user-attachments/assets/0e2dcd59-e690-4df2-916f-4110ff861ddc

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Video attached.

### CODE REVIEW

**Review by anirudhpillai — APPROVED** [review]
Thanks a lot for the fix, was an annoying bug!

**Comment by abhi12299** [comment]
@anirudhpillai are there any other issues I can pick up? Most issues are either stale, or have been fixed but the issue is not closed, or behind a subscription :/

**Comment by anirudhpillai** [comment]
Sure, we're working to improve our issue tracking.
But here are some 
https://github.com/orgs/PostHog/projects/104/views/1?pane=issue&itemId=79312283
https://github.com/orgs/PostHog/projects/104/views/1?pane=issue&itemId=79154658
https://github.com/orgs/PostHog/projects/104/views/1?pane=issue&itemId=79313470

**Comment by abhi12299** [comment]
@anirudhpillai can't access those links :( getting 404

**Comment by anirudhpillai** [comment]
Try these
https://github.com/PostHog/posthog/issues/24869
https://github.com/PostHog/posthog/issues/24895
https://github.com/PostHog/posthog/issues/24894

**Comment by abhi12299** [comment]
thanks! will look into them.

**Pull request merged**
