### PR TITLE
fix: Fix container build CI step for fork repositories

### PR DESCRIPTION
**Pull request by frankh**
## Problem

Don't try to push if on a fork (will not have permissions)

See https://github.com/PostHog/posthog/actions/runs/3925346182/jobs/6710866925 for example failure for fork PR

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

- [ ] CI passed on fork PR (this one)

### CODE REVIEW

**Comment by frankh** [comment]
wait I need approval again? :| @hazzadous

**Review by Twixes — APPROVED** [review]

**Comment by hazzadous** [comment]
Looks like we also need to not try to build the Cloud image also, if we are on a fork.

@guidoiaquinti or @ellie what do you think?

**Comment by frankh** [comment]
hmm looks like pushing the cache still breaks it :/

**Comment by frankh** [comment]
ah i see there's 2 image workflows, made the same change to the other one we'll see if that works

**Review by hazzadous — CHANGES_REQUESTED** [review]
Can we make [this workflow](https://github.com/PostHog/posthog/pull/13725/files#diff-78b403df46a7dc1a8a62a3d0cc6fb6acc4df6be3685f82d0b02fd17a28446c4dR63) not run on forks in it's entirety. It requires a secret to run which isn't available. It would be nice to remove that but I think out of scope for this change.

**Comment by guidoiaquinti** [comment]
> Can we make [this workflow](https://github.com/PostHog/posthog/pull/13725/files#diff-78b403df46a7dc1a8a62a3d0cc6fb6acc4df6be3685f82d0b02fd17a28446c4dR63) not run on forks in it's entirety. It requires a secret to run which isn't available. It would be nice to remove that but I think out of scope for this change.

I think we need this for E2E tests if we don't want to rebuild everything all the time

**Comment by hazzadous** [comment]
It also looks like [these](https://github.com/PostHog/posthog/actions/runs/3931290815/jobs/6723135377) need the image to have been pushed to ghcr.io, it is going to be a larger change than expected!

For historical context:

 1. change was made to use docker image in E2E tests as a byproduct of https://github.com/PostHog/posthog/pull/10488/files#diff-3e103440521ada06efd263ae09b259e5507e4b8f7408308dc227621ad9efa31e. It used GitHub artefacts instead of ghcr for allowing forks to work.
 2. since then, that artefact workflow has been removed, but we now have issues with the E2E ones.

I think the more pragmatic change is to change the E2E tests to run as [per the before time](https://github.com/PostHog/posthog/pull/10488/files#diff-3e103440521ada06efd263ae09b259e5507e4b8f7408308dc227621ad9efa31e) i.e. not with the docker image and as they were running before my changes.

cc @ellie @guidoiaquinti

**Comment by hazzadous** [comment]
Made there is the more pragmatic change to not run E2E on forks, but I'd want them to run at some point before we deploy 🤔

**Comment by frankh** [comment]
damn a lot more complicated that i hoped

one option is to try to pull and build the image if it fails (and ofc have to skip the cloud image build)

**Pull request closed without merging**
