### PR TITLE
fix: _parse_total_volume_result

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Problem
While investigating some HTTP 5xx I've found few occurrences of:

```
serialized_data = cast(List[Callable], parse_functions)[entity.index](result[entity.index])
File \\\"/code/posthog/queries/trends/total_volume.py\\\", line 122, in _parse
for _, stats in enumerate(result):\\nTypeError: 'NoneType' object is not iterable\"}
```
happening despite the type hint `List` for `result`. This is an issue not caught by `mypy` due to all the level of indirections and abstraction we are using in the code. 

## Changes
We are trying to fix the main issue with https://github.com/PostHog/posthog/pull/11607 while this PR is only to fix this specific occurrence.

## How did you test this code?
CI is ✅

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]
Although I'm thinking this may produce false results for users where before it will have at least displayed an error.

**Comment by guidoiaquinti** [comment]
> Although I'm thinking this may produce false results for users where before it will have at least displayed an error.

cc @neilkakkar @EDsCODE . Let me know if you are 👍 to merge

**Comment by hazzadous** [comment]
> cc @neilkakkar @EDsCODE . Let me know if you are 👍 to merge

It would also be good to get context on why we need a higher order function, but that is just from curiosity. We would love to remove these if possible.

**Comment by guidoiaquinti** [comment]
> > cc @neilkakkar @EDsCODE . Let me know if you are 👍 to merge
> 
> It would also be good to get context on why we need a higher order function, but that is just from curiosity. We would love to remove these if possible.

+1, this (_possibly unnecessary?_) level of indirection/abstraction likely hid [quite few bugs](https://github.com/PostHog/posthog/runs/8138856385?check_suite_focus=true)

**Review by neilkakkar — APPROVED** [review]
I'm not quite sure why we have this level of indirection. I suppose when it was introduced, we wanted a single function to handle trend breakdowns, lifecycle, and total volume.

The shape of results for all 3 is different, so then we also need a different parse function for each to tell us how to parse them.

@EDsCODE probs has more context.

I'd quite like to refactors these into their own Trend classes, and a base class with the common functionality, like we do in funnels.

**Comment by guidoiaquinti** [comment]
> I'm not quite sure why we have this level of indirection. I suppose when it was introduced, we wanted a single function to handle trend breakdowns, lifecycle, and total volume.
> 
> The shape of results for all 3 is different, so then we also need a different parse function for each to tell us how to parse them.
> 
> @EDsCODE probs has more context.
> 
> I'd quite like to refactors these into their own Trend classes, and a base class with the common functionality, like we do in funnels.

👍 I'll leave this to whoever owns the Trend functionality, in the meantime I'm going to merge this to fix this annoying bug.

**Pull request merged**
