### PR TITLE
Drop sessions backend support

### PR DESCRIPTION
**Pull request by macobo**
## Changes

Follow-up to https://github.com/PostHog/posthog/pull/7912 and https://github.com/PostHog/posthog/pull/7933

This removes all remaining sessions code I could find.

### CODE REVIEW

**Review by EDsCODE — APPROVED** [review]

**Review by paolodamico — APPROVED** [review]
lgtm!
- Looks like we still have some test benchmarks on .test_durations, unsure if we want to update those.
- Found some files that maybe we want to remove? `ee/clickhouse/sql/sessions/*.py`

**Comment by paolodamico** [comment]
Will merge as I need to do additional cleanup on the frontend, will include the removal of the files referenced above in my PR.

**Comment by EDsCODE** [comment]
Hmm RE: a few sentry errors. was there a plan here with the existing dashboards that use sessions or we're just hard removing it since #7912 already removed the insight frontend for it

**Comment by paolodamico** [comment]
Yup, https://github.com/PostHog/posthog/pull/7933

**Pull request merged**
