### PR TITLE
fix(async-migrations): multiple completion emails

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe. If this affects the frontend, include screenshots.*

*Stay up-to-date with our [coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

Prevents us from sending multiple emails (and multiple updates) if we complete an already completed migration

## How did you test this code?

*Briefly describe the steps you took.*

### CODE REVIEW

**Review by tiina303 — APPROVED** [review]
🚢  But note that I'm not sure if the next migration if there's a new one will run properly now.

**Comment by yakkomajuri** [comment]
Well, this is the only way to complete a migration - so by checking for it being completed before it is implied that this code path has run at least once before

**Comment by tiina303** [comment]
> Well, this is the only way to complete a migration - so by checking for it being completed before it is implied that this code path has run at least once before

I meant the case of you have auto run next one enabled & there's some completed in the past & we add a migration, specifically this was the place it would have kicked it off as it looks like https://github.com/PostHog/posthog/blob/1d1d6d335c08da536b51253fe50dff0d98d4eeab/posthog/async_migrations/setup.py#L77 we only try the first one.

**Review by tiina303 — CHANGES_REQUESTED** [review]
Change of plans - we need to check completion earlier for the upgrade path. Will put up a PR

**Comment by yakkomajuri** [comment]
> Change of plans - we need to check completion earlier for the upgrade path. Will put up a PR

but that's unrelated to this change?

**Comment by tiina303** [comment]
sure we could ship this too, but my earlier comment still applies about auto run

**Comment by yakkomajuri** [comment]
overall this is a useful change - can you approve? reducing wip

**Comment by tiina303** [comment]
This breaks `AUTO_START_ASYNC_MIGRATIONS` see https://github.com/PostHog/posthog/pull/8782#issuecomment-1055381165 there are two options:
1. needs_update in this PR doesn't remove the last part
```
     if needs_update:
      update_async_migration(
        migration_instance=migration_instance,
        status=MigrationStatus.CompletedSuccessfully,
        finished_at=finished_at,
        progress=100,
      )
      if email and async_migrations_emails_enabled():
        from posthog.tasks.email import send_async_migration_complete_email
        send_async_migration_complete_email.delay(migration_key=migration_instance.name, time=finished_at.isoformat())
    if getattr(config, "AUTO_START_ASYNC_MIGRATIONS"):
        next_migration = DEPENDENCY_TO_ASYNC_MIGRATION.get(migration_instance.name)
        if next_migration:
            from posthog.async_migrations.runner import run_next_migration
            run_next_migration(next_migration)
```
2. Change https://github.com/PostHog/posthog/blob/1d1d6d335c08da536b51253fe50dff0d98d4eeab/posthog/async_migrations/setup.py#L78 to kick off the first not completed migration

btw we end up going all the way to  https://github.com/PostHog/posthog/blob/9ae7c194e327bd61d3e6033db6072c899cc8c941/posthog/async_migrations/runner.py#L65
for all completed migrations, so maybe we can somewhere exit early if it's completed? But that's less important.

**Review by tiina303 — APPROVED** [review]
Made the change, merge if this looks good to you

**Pull request merged**
