### PR TITLE
fix: Trim person search input

### PR DESCRIPTION
**Pull request by isAdrisal**
## Problem

The `Person` search input takes a distinct id or email — neither of which have leading or trailing whitespace.

Often, especially when copying these identifiers from other sources (including Posthog insights), there can be a stray piece of whitespace that is copied along with it. It's tedious to always need to edit the input manually in these instances for the search to work.

## Changes

Adds a `?.trim()` to the PersonsSearch onChange value.

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Haven't tested — assumed this would be tested by CI.

### CODE REVIEW

**Comment by isAdrisal** [comment]
Hey @Twixes, could you please review this, or include the right person?

**Review by Twixes — CHANGES_REQUESTED** [review]
That's a good idea! However, can we only trim when _pasting_ in? The problem with `.trim()`ming at every `onChange` is that it makes entering a space a frustrating experience, when that's something you do need.

**Comment by isAdrisal** [comment]
@Twixes Hmm, I'm not sure how we'd know it's a _paste_, while preserving the "on change" behaviour where the search happens without needing to submit or un-focus the input.

I thought about checking if the new value is ≥2 characters different in length than the previous one (suggesting pasting rather than typing), but that'd error on emojis (lol), but also if the new value just happens to be the same length as the old value which is likely the case in distinct IDs.

How do you feel about this instead?

```ts
input.trimStart().replace(/[\t\n\r]+$/, '')
```

It removes any leading whitespace (which I assume isn't an issue?), and then only removes any trailing tab, newline, or carriage return characters but will leave any spaces.

**Comment by Twixes** [comment]
Actually I think we should be able to use the browser input event's [`inputType` property](https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType)!

**Comment by isAdrisal** [comment]
@Twixes Ahh I didn't know about `inputType` — TIL!

LemonInput looks like it'd need [modifying](https://github.com/PostHog/posthog/blob/master/frontend/src/lib/lemon-ui/LemonInput/LemonInput.tsx#L12) to take an `onInput` prop to implement that. I can't seem to get the codespace to run for me to add that to this PR, so I might need to bail out on this PR unfortunately!

**Comment by Twixes** [comment]
Ah, I see. :( In case you'd like to run things locally, here's our guide on this: https://posthog.com/handbook/engineering/developing-locally. But no worries about bailing out, thanks for giving this a shot either way!

**Pull request closed without merging**
