### PR TITLE
fix: Improve label in row for other breakdown

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

The row "Other" can be a bit confusing.

## Changes

image

## How did you test this code?

- 👀

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Works for me!

**Review by MarconLP — APPROVED** [review]
🚢it

**Comment by raquelmsmith** [comment]
This looks meh. Can we do an info icon with a tooltip instead?

**Comment by MarconLP** [comment]
> This looks meh. Can we do an info icon with a tooltip instead?

Having the text under this icon would look great: 
2024-02-12 at 22 06 36@2x

**Comment by webjunkie** [comment]
True. It doesn't look pretty. The problem is that the function needs to return `string` and not an element with tooltip.
To adjust that, I need to adjust 10 places where the function is used, which takes time.

**Comment by webjunkie** [comment]
I've merged this in the spirit of "moving fast". We should still make this not looking meh, I agree.

**Pull request merged**
