### PR TITLE
Signup improvements

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- This PR introduces the new signup design from #1504. The signup page is now a React view instead of HTML served from Django.
- There's now a REST API endpoint (using DRF) to sign up (i.e. create a user and team account).
- Removes the `/setup_admin` view and derived sign up logic (using a form-data POST request).
- Removes complex password requirements (enforcing only an 8-character length minimum), as per discussion with @mariusandra on Figma.
- Restricts creating multiple teams unless on multi-tenancy. Following #1540 we might enable this too to enterprise customers.

alt

## Checklist

- [X] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [X] Backend tests (if this PR affects the backend)
- [X] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by paolodamico** [comment]
Partial implementation of #1504

**Review by Twixes — CHANGES_REQUESTED** [review]
At a quick glance code's good, just a few UI points.

---

Screen Shot 2020-09-04 at 14 59 21

This guy looks just a bit blurry, need to export a higher resolution version from the original vector graphic, or outright use an SVG.

---

Screen Shot 2020-09-04 at 14 52 51

The placing of this is a bit… I'm not sure, but it looks slightly out of place. I think it looked more fitting in the Figma design.

---

Screen Shot 2020-09-04 at 14 52 22

This is really wide, would be better with just one column (as in the Figma design).

---

Screen Shot 2020-09-04 at 14 58 47

"Tapping" is very mobile-specific, I think "clicking" is more universal.

---

Screen Shot 2020-09-04 at 14 58 30

Hm, this could be _maybe_ a bit nicer. Something like "Send me occasional emails about security and product updates. Subscription can be canceled at any time."

**Comment by paolodamico** [comment]
Thanks @Twixes, on second thought I agree with you, it looks better in a single column, updated UI/UX.

Screenshot

**Review by Twixes — COMMENTED** [review]
Looks pretty nice. Just that the heading is placed a bit oddly still.

Screen Shot 2020-09-07 at 13 32 54

And the sizing/spacing doesn't fit mobile very well.

Screen Shot 2020-09-07 at 13 32 54

**Comment by paolodamico** [comment]
> And the sizing/spacing doesn't fit mobile very well.

I've optimized this for mobile too (see image below), but in general we need to decide if we should support mobile too. It might not make sense at this point to allow mobile signup if the rest of the app does not perform well on mobile.

screenshot

Thanks for the thorough review @Twixes!

**Pull request merged**
