### PR TITLE
chore: add react-hooks plugin to eslint

### PR DESCRIPTION
**Pull request by kappa90**
## Problem

I realized we are not using [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) which means we are not enforcing linting for react [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html), which means we have sub-optimal or potential buggy hooks all over the codebase.

By adding it, vscode (not sure about pycharm) will show warns for wrong hook dependencies, and errors if hooks are used wrongly (e.g. placed outside of a function)

image

## Changes

- Add `esling-plugin-react-hooks` to eslint

## How did you test this code?

Works in VSCode

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
I say let's give it a go but see how intrusive the "exhaustive deps" warning is. I'm past projects I found it to be a nuisance as you don't always want all your deps accounted for.

**Comment by kappa90** [comment]
I'd rather have the warning and decide if I want to add the dependencies or just write a comment to dismiss them, rather than being forgetful and not noticing that I need to add a dependency.

**Comment by kappa90** [comment]
It needs to be a warning on hooks errors though, because on error the Frontend CI won't pass

**Comment by mariusandra** [comment]
This is disabled on purpose.

Last time we tried this: https://github.com/PostHog/posthog/pull/6571 - [here](https://github.com/PostHog/posthog/pull/6576#pullrequestreview-785352926) were some of my arguments.

**Comment by kappa90** [comment]
I see. I will then keep it as a local dependency because I think it does help during development.

Not everything will end up being a Kea logic, and having a little help from the linter makes a big difference.

**Pull request closed without merging**
