### PR TITLE
do not start worker, plugins, or events if migrations not complete

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

as per a conversation with Guido about code relying on a certain db state on upgrades

https://docs.djangoproject.com/en/3.2/ref/django-admin/#cmdoption-migrate-check

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by guidoiaquinti** [comment]
The tl;dr; is that we should fail fast if required migrations are not deployed as this could lead to unexpected app behaviours.

**Review by macobo — APPROVED** [review]

**Review by guidoiaquinti — APPROVED** [review]

**Review by hazzadous — APPROVED** [review]
Also checked that ghost migrations don't cause failures, i.e. old code will still run for example if we have to roll back.

**Comment by yakkomajuri** [comment]
Seems we never merged this.

**Comment by guidoiaquinti** [comment]
I was re-reviewing this and then I saw `bin/migrate` that does:

- `python manage.py migrate`
- `python manage.py migrate_clickhouse`
- `python manage.py run_async_migrations`

are we ok to check only DB migrations?

**Pull request merged**
