### PR TITLE
feat: show only login options if account exists when accepting an invite

### PR DESCRIPTION
**Pull request by Justicea83**
## Problem

https://github.com/PostHog/posthog/issues/4077

## Changes
1. Add a redirect to the login page if an existing user is invited to an organization
2. When they login, they are automatically redirected to accept the invite

## How did you test this code?
In the browser and automated tests

https://github.com/PostHog/posthog/assets/26106822/1b85136d-5f5e-48c7-919e-bd4daa65c75d

1. Invite a user who already exists into an organization
3. Copy the invite URL and open it in a new browser / incognito window
4. You will be redirected to the login page

### CODE REVIEW

**Comment by raquelmsmith** [comment]
@Justicea83 this is great, thank you! can you write some tests to cover this functionality?

**Comment by Justicea83** [comment]
> @Justicea83 this is great, thank you! can you write some tests to cover this functionality?

Having a very busy week, will get on top of this, this weekend

**Comment by Justicea83** [comment]
@raquelmsmith I just added tests, kindly let me know if I need to update something

**Comment by Justicea83** [comment]
The cypress tests are failing, I'm new to it, so I may take longer to fix it, but yes I'm fixing it 😄

**Comment by Justicea83** [comment]
I don't see any failing tests again, did I miss something? It seems to me the house is in order

**Comment by raquelmsmith** [comment]
Every time you push I have to re-approve workflow runs 🙃

**Comment by raquelmsmith** [comment]
You can run cypress tests locally to make sure they pass. https://posthog.com/handbook/engineering/developing-locally#end-to-end

**Comment by Justicea83** [comment]
Oh I understand now, let's see what happens in this build

**Comment by Justicea83** [comment]
> You can run cypress tests locally to make sure they pass. https://posthog.com/handbook/engineering/developing-locally#end-to-end

Yes I did this time around

**Comment by raquelmsmith** [comment]
Visual regression test is flakey, you can ignore. But the failing cypress is for an invite flow so I think the failure is legit. And the backend failures look legit too. Lmk if you need help or direction getting them fixed up 🙂

**Comment by Justicea83** [comment]
There's a test failing in `test_session_recordings.py` which I find strange, I didn't touch anything in that file. Fixed the other backend test. Merging master to see

**Comment by Justicea83** [comment]
Saw some merges on flaky tests, so I merged and fixed the backend bug

**Comment by Justicea83** [comment]
I merged main again, waiting for workflow approval. @raquelmsmith is there a slack for contributors that I can join in and ask questions? I want to contribute more

**Comment by raquelmsmith** [comment]
Approved the checks! Have you run the tests locally to verify they succeed locally?

Re: contributing, using GitHub here is probably your best bet. We used to have a slack community but we've mostly shut it to new members. What type of support are you looking for? Knowing that I can help point you in the right direction.

**Comment by Justicea83** [comment]
The tests for the session recordings are failing, finding it difficult to debug because I'm new to the codebase.
Can you help me with how session recordings are related to user sign up logic?

I will also be glad if you can point me to resources about session recordings. I'd love to take a read on the docs.

The funny thing is most of the test in session recording is failing for me locally, and only a few(11) are actually failing in the PR.

So I don't know which one to look at.

I'll also be glad if you can help with something I'm missing locally for the session recordings

**Comment by Justicea83** [comment]
`'TestSessionRecordings' object has no attribute 'snapshot'`, seeing this error in most of the failings

**Comment by Justicea83** [comment]
After digging further, i realized the failure starts from here https://github.com/Justicea83/posthog/blob/705d87719a76e1693a09589f28ff95cf783de951/posthog/test/base.py#L376-L393, the code itself looks suspicious, will be interesting to get your view on this

**Comment by raquelmsmith** [comment]
These failures are happening on master locally for me, too. I've pinged the team internally. After they get it resolved we can merge master in again and get this live!

**Comment by raquelmsmith** [comment]
Hm, similar type of failures, hold tight while we get this sorted internally. thanks for your patience here @Justicea83 😄

**Comment by Justicea83** [comment]
Looks like everything is passing now, great news!
I can look at another issue now ):

**Comment by Justicea83** [comment]
Was updating my fork, ended up updating this branch instead 🥹

**Review by raquelmsmith — APPROVED** [review]

**Comment by Justicea83** [comment]
@raquelmsmith all the tests were passing, now one is failing, do I need to do anything else at my end?

**Comment by raquelmsmith** [comment]
That was much more of a pain than it should have been, but it's in now. Thanks for the contribution @Justicea83!

**Comment by Justicea83** [comment]
You welcome, I want a Posthog merch 😉

**Pull request merged**
