### PR TITLE
Improve bin/start

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Automatically set KAFKA_HOSTS and DATABASE_URL to the correct (docker backed) settings. Also wait for kafka and clickhouse to be up and running.

## How did you test this code?

ran bin/start

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
Should we also set `PRIMARY_DB=clickhouse`?

**Review by mariusandra — CHANGES_REQUESTED** [review]
Hmm... unlike `curl`, the `wget` util that I also often use myself, needs to be manually downloaded from brew/apt/etc and won't be installed for everyone --> we'll need extra steps in the [developing locally](https://posthog.com/docs/contribute/developing-locally) docs to install it.

Can we avoid this somehow?

**Comment by mariusandra** [comment]
Looks good otherwise, and I don't have a direct answer to the question posed by @Twixes

**Review by Twixes — APPROVED** [review]
Updated the way `KAFKA_HOSTS` are set, added `PRIMARY_DB` (it will go away soon, but still safer to have now), replaced `wget` with `curl`, fixed `DEBUG` (FYI this `BAR=$FOO || 1` doesn't work as a way of setting a default in bash @timgl, this does: `BAR=${FOO:-1}`).

**Comment by timgl** [comment]
@Twixes Thank you for doing all the work here 😄

**Pull request merged**
