### PR TITLE
revert: login redirect changes

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

Urls like app.posthog.com/login?next=/ would hang if the user was already logged in (for some users, their browser autocompletes to this when they type "posthog", so it's pretty common to hit this case). I think it was happening because kea router wants a relative URL, and this function was now returning a full URL.
 
## Changes

Reverts #8998 (doing an old fashioned revert because I couldn't get a normal revert to pass conventional commits 🤔)

I don't have context on the initial reason for this change in #8998, but if is important, we could also resolve this issue by changing [the line here](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/sceneLogic.ts#L244) to be:

```
window.location.href = afterLoginRedirect()
```
That change is less ideal because it would cause the page to refresh on redirect.

## How did you test this code?

Manually verified it works by logging int and navigating to: app.posthog.com/login?next=/ and verifying it doesn't hang

### CODE REVIEW

**Review by yakkomajuri — CHANGES_REQUESTED** [review]
sent you a message on Slack

**Review by yakkomajuri — APPROVED** [review]

**Comment by yakkomajuri** [comment]
can we just make sure we have a test for the origin remaining the same? even if that kind of belongs in the kea-router util, but would love to sanity check this in our codebase

**Comment by rcmarron** [comment]
> can we just make sure we have a test for the origin remaining the same? even if that kind of belongs in the kea-router util, but would love to sanity check this in our codebase

This is a bit tricky to test. This gets blocked by browser's `pushState` function (it throws when you try to change the origin), and I'm having trouble reproducing it in `jest`. I'll have to put some thought into how to best do this.

**Comment by EDsCODE** [comment]
@rcmarron What's the scenario you're trying to recreate in jest?

**Comment by rcmarron** [comment]
> @rcmarron What's the scenario you're trying to recreate in jest?

I'm trying to test the case where the URL looks like: `/login?next=//example.com`. Given the solution here, if you try that URL in the browser, it throws an exception because it tries to change the page's origin to example.com via Kea router, and that just uses the browser's `history.replaceState` under the hood which throws an exception if you try to change the origin. The issue is that I can't get jest to throw that exception...

An alternative here that's more easily tested would be to always set the origin (like the function did before), and then always update the URL here using `window.location.href = ...` instead of kea. The downside is that we get more page loads.

**Pull request merged**
