### PR TITLE
Test if key for kafka is none and set to empty string

### PR DESCRIPTION
**Pull request by fuziontech**
## Changes

This is to mitigate 500's on events pipeline currently caused by new kafka partitioning

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by yakkomajuri — APPROVED** [review]
great

**Comment by hazzadous** [comment]
I guess this just means the 3 percent of anonymised ip teams will get put into the same partition? I assume that wouldn't be an issue?

**Comment by yakkomajuri** [comment]
Actually we just broke a few things and these are just fixes. The final version of all the changes is actually shipping soon.

First we broke it by passing a string and not bytes, then the encoding mechanism was failing for `None`

**Comment by hazzadous** [comment]
Ooops I missed the bytes issue sorry 👎

**Pull request merged**
