### PR TITLE
feat(data-exploration): improved editing UX

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Currently you can only edit data exploration columns via the "column configurator" view

## Changes

Adds a submenu at the end of each column header, letting you sort, edit, add and delete columns:

I don't know what should be in the scope of this PR and what should go in a followup. There are still many obvious changes we can make to this interface. I'd be very happy to hear thoughts on how can we improve this further, and what is blocking in this round :).

## How did you test this code?

Played around with the columns.

### CODE REVIEW

**Comment by mariusandra** [comment]
I improved the popups somewhat, yet there's probably still some room for improvement. The tooltip that shows up for e.g. "library" could likely also be rolled into the popup.

**Review by thmsobrmlr — APPROVED** [review]
LGTM - I have absolutely no remarks code or functionality wise. Sorting the columns seems to be eagerly awaited, so this will help lots

Since you're asking for feedback - here are some ideas that came to mind:
- I think the "more" button would be better right aligned, as otherwise there is no spacing between the column title text and the button on hover
- Sorting could be done with with by up / down / neutral icons, like we do here, including clickable columns https://storybook.posthog.net/?path=/docs/lemon-ui-lemon-table--basic
- I'm not a big fan of the "Add column before/after" items - I think the current solution works, and could imagine a "+" button at the end of the table, with draggable columns
- We could show the edit / sort icons just on hover, to keep the UI more clean
- Something that doesn't work well right now, but could with PostHog 3000 is how Notion does it (hover and click on the columns): 
  
  https://user-images.githubusercontent.com/1851359/212857248-c44f6753-ab43-4978-bf33-008d13ef201a.mov

**Comment by mariusandra** [comment]
Thanks for the review! I added a link to your UX suggestions as a checkmark in the "[next steps](https://github.com/PostHog/meta/issues/81)" list to be sure not to forget this. As it would be a bit of work which I'd take on after the ["hogql property filters" PR](https://github.com/PostHog/posthog/pull/13264) is done (so likely not today), I'll merge this in now and continue in a followup.

**Comment by lharries** [comment]
Great work! Few thoughts:
- I like the suggestion of moving to the SQL format of “total() as ‘crash_events’ for when we have a more custom parser [https://github.com/PostHog/meta/issues/86#issuecomment-1382133589](https://github.com/PostHog/meta/issues/86#issuecomment-1382133589)
- Agreed with making columns draggable
- Agreed with the plus on the right similar to Notion which adds a column on the right
- When clicking this plus we could add a dropdown for “Total count” which then prefills the formula total(). This will make it easy for people who don’t know SQL to add counts
    - [https://github.com/PostHog/meta/issues/86#issuecomment-1381834851](https://github.com/PostHog/meta/issues/86#issuecomment-1381834851)
- Small bug - When you add a column with invalid HogQL it creates an empty column I think [https://share.cleanshot.com/fJT3ljf8](https://share.cleanshot.com/fJT3ljf8)

**Pull request merged**
