### PR TITLE
Add support for Groups in Experiments

### LINKED ISSUE #8295: Groups Support for Experimentation
## Is your feature request related to a problem?

I want to run experiments on groups

## Describe the solution you'd like

Experiments support group target metrics, and the FF respects group selection.

## Describe alternatives you've considered

No groups :(

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

Fixes #8295 

Here's a video in action:

image

and more consistent styling for add funnel step button:

image

## How did you test this code?

See exp can be created, edited, and launched with group types.

### CODE REVIEW

**Comment by liyiy** [comment]
Don't we need to add the groups taxonomic types to the participant selection filter too?

**Comment by neilkakkar** [comment]
Goood point! That does make things a bit annoying, since we can't mix person properties & group properties for user selection.

For now, I can switch around the participants selector based on whether we're aggregating by users / orgs/ etc. -- just like we do for feature flags, but I wonder if there's a more coherent way to go about this? (cc: @clarkus ). Same for trends.

**Comment by clarkus** [comment]
[There's already a solution for this in figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6342%3A67735). There is a participant selection portion of the form. Adjacent to that header is a participant type selector that shows persons, or the group objects applicable. Changing this would change the filter types for the whole experiment - we'd only be working with group properties.

Screen Shot 2022-02-07 at 10 33 39 AM

**Comment by neilkakkar** [comment]
Totally missed that, and makes sense, will do this thanks! 🤦

**Comment by neilkakkar** [comment]
Opening up to review again with @clarkus  (see video in description please)

**Review by clarkus — CHANGES_REQUESTED** [review]
Why do we still have the "aggregating by" control if we're setting participant type at a higher level? We only need one, right?

**Comment by neilkakkar** [comment]
Is it clear that the funnel is also aggregating by the participants type? ... oh, yes, because the funnel changes name from users -> organisations! Makes sense 🤦 . Removing that.

**Comment by neilkakkar** [comment]
image

**Review by clarkus — APPROVED** [review]

**Review by liyiy — APPROVED** [review]

**Pull request merged**
