### PR TITLE
Flake8 setup and improvements

### PR DESCRIPTION
**Pull request by eLRuLL**
This PR adds a more strict flake8 setup on the project with an example (on the `posthog/api/test/test_action.py ` file). Before it found 597 errors and now it has 1099 (If this gets accepted, I can help to fix all of those errors 😄)

Please let me know if this is something that you guys think could be beneficial for the project.

Pros:
- Sets a standard on the development
- It makes the project more readable and easy for others to contribute

Cons:
- Could be annoying for quick development environments

## Changes

- flake8 setup
- flake8 first improvement on test_action test
- improvement on github action

## Checklist
- [ ] All querysets/queries filter by Team
- [ ] Code reviewed
- [ ] QA'd

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey!
We currently use prettier for ja formatting. It's great because it automatically fixes all the issues it detects. Thus it greatly speeds up our workflow by making styling issues a thing of the past. See the [why prettier] (https://prettier.io/docs/en/why-prettier.html) page for some explanation about the philosophy behind such decisions. 

While I definitely appreciate the spirit of this PR, I feel it will take us backward and slow us down. Is there any approach like prettier for python that would let the computer fix all these style issues automatically? 

Quick googling brought me to black. [Could this be a solution?](http://www.locallyoptimal.com/blog/2019/08/23/why-you-should-use-black-for-your-python-style-linting/)

**Comment by SanketDG** [comment]
`black` is pretty awesome, given how it's been mass adopted so fast despite [labelling itself as beta](https://github.com/psf/black#the-black-code-style)

Also relevant: [`pre-commit`](https://pre-commit.com/) for language agnostic git hooks! We can use both prettier and black with this.

**Comment by eLRuLL** [comment]
yeah I also thought about using black first, but a few reasons I think starting with that wouldn't be a good solution:

- The PR that black would first generate would be huge.
- I didn't want to obstruct development somehow by adding too many changes to the codebase at once.
- I also found some code improvements that black wouldn't be able to do, like request formatting:

https://github.com/eLRuLL/posthog/blob/ac224270097b19a5cb016f836e8091509ff6b85e/posthog/api/test/test_action.py#L282-L291
```
        with freeze_time('2020-01-02'):
            action_response = self.client.get(
                '/api/action/trends/',
                data={
                    'date_from': '2020-01-02 23:00:00',
                    'date_to': '2020-01-02 23:00:00',
                    'interval': 'hour',
                },
            ).json()
        self.assertEqual(action_response[0]['labels'][23], 'Thu. 2 January, 23:00')
```
instead of

https://github.com/PostHog/posthog/blob/42be1ceff860ce174ec4046f53c83cd413b7d11d/posthog/api/test/test_action.py#L234-L236

- You are setting 127 as the `max-line-length` and most of the flake8 errors on the project come from long strings, for which black will have to break up those strings, I think there is a better way understanding the context of it and improving the code.
- I was also going to use this opportunity to read and understand the codebase so I can contribute better to the project.

**Comment by SanketDG** [comment]
@eLRuLL 

> * The PR that black would first generate would be huge.

That is indeed true, running a basic black run  over `posthog/` (excluding migrations) generates a [diff](http://ix.io/2jwO) of over 4k+ lines.

> * I didn't want to obstruct development somehow by adding too many changes to the codebase at once.

Let's not to it at once and instead go by one component/PR. A component would stand for a functional core unit of Posthog (Actions, Trends etc). So for one PR, you would change the source files, the tests and anything else that is related. We also have to make sure that no PR is open on those said files, because then it would cause large merge conflicts on those PRs.

I am also waiting for others to pitch in on whether this is the righ approach,

> * I also found some code improvements that black wouldn't be able to do, like request formatting:

Pretty nice, but as I understand. whether through `flake8` or any other tool, we have to do this manually, right?



> * You are setting 127 as the `max-line-length` and most of the flake8 errors on the project come from long strings, for which black will have to break up those strings, I think there is a better way understanding the context of it and improving the code.

I think this is the whole spirit of what was said in https://github.com/PostHog/posthog/pull/660#issuecomment-619336744, the idea of using a tool that is **opinionated**, has less false positives, so that the developers can work on other important things. [The Black code style explains it](https://github.com/psf/black#the-black-code-style)

> * I was also going to use this opportunity to read and understand the codebase so I can contribute better to the project.

Hopefully, if you go down the one `component/commit` road, this seems to be doable :)

---
Let me know what you think.

**Comment by Pacu2** [comment]
We could stick with tools like Flake8 or Pylint, but that would require a CI style check to ensure the code styling is unified across the whole project. We all have our personal preferences in the end.

I've successfully used black in many of my professional projects, with codebases bigger than PostHog, and that's why I understand concerns of @eLRuLL and @SanketDG, as this change will affect every open PR and will probably cause a lot of merge conflicts for those how regularly update the app. However, this step is necessary to improve the readability and consistency of PostHog codebase. One step back two steps forward, I'd say.

The partial update is unfortunately not an option, as black would reformat the whole file instead of lines modified, creating even greater chaos in merge conflicts.

As already mentioned by @SanketDG, pre-commit would be a great option to have. Let's not limit ourselves to black. We have a whole variety of options: sorting imports (isort), trimming trailing whitespace, removing extra space at the end of the file, pydocstyle, mypy, and of course, custom ones like checking if all migrations were generated for the code changes. We can add Prettier to the pack as well. 

If you'd need help with such a PR or would like me to contribute - let me know.

**Comment by SanketDG** [comment]
> The partial update is unfortunately not an option, as black would reformat the whole file instead of lines modified, creating even greater chaos in merge conflicts.

It is possible, but involves quite an amount of unsaid work, black can just work on python code instead of a file.

When I said one component per commit, I did just mean one file per commit or PR, a lot of PostHog's code is built that way :D

**Comment by Pacu2** [comment]
I've just found that [darker](https://github.com/akaihola/darker) is built on top of black & isort and it reformats only regions changed since the last commit

**Comment by eLRuLL** [comment]
To recap, this PR's intention was to introduce some flake8 checks into the codebase while presenting an example (on `posthog/api/test/test_action.py`) to show the code improvements.

As you all know, the project is not (yet) enforcing code linting on the CI configuration (github actions). My intention was not to change that, but according to the comments, it looks like that is something that some of you would like to start doing (this is where `black` enters).

I wanted to (silently) start improving the code with flake8, so when the team is ready to "activate" code linting, it wouldn't be too much trouble.

I would recommend opening an issue for discussing when and how you want to start forcing code linting (btw `darker` seems like the best first approach IMO).

Please let me know what you guys decide, I am here just to contribute.

**Review by mariusandra — APPROVED** [review]

**Comment by mariusandra** [comment]
Hi @eLRuLL and others! I had a chat with @timgl about this and we decided to merge this PR.

Thank you for getting the ball rolling regarding code linting and for the work in this PR improving `test_actions.py`. We would be very happy if you'd be interested in continuing this, either by opening a new PR regarding `darker` or just improving code based on flake8's suggestions.

**Pull request merged**
