### PR TITLE
Convert existing pie charts to D3

### PR DESCRIPTION
**Pull request by samwinslow**
## Changes

WIP. Converts existing pie charts to bare D3 implementation. Use `d3-piecharts-default` flag to test.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by samwinslow** [comment]
Getting there — basic text tooltips, but some weirdness regarding focus management.

https://user-images.githubusercontent.com/4645779/122130107-240e3000-ce05-11eb-9c9b-465e3165505b.mp4

TODO:
- [ ] Fix these tooltips (preferably keep everything within SVG, but another approach may be needed
- [ ] onClick actions to show users

Should be ready to merge v1 tomorrow.

**Comment by mariusandra** [comment]
Hey, this wasn't exactly how I had it in mind. You are using some utils from d3 (great), but at the end of the day, this is still a react component, which builds a SVG from various other react `path` components. d3 is just used for angle calculations... and in this case I'd replace it with a 10-line d3-less helper to do the same thing. All in all, while the code is definitely better than the current pie chart, architecturally this is not moving us in the right direction.

So let's table this please for the rest of the sprint... and regroup and try again later.

**Comment by paolodamico** [comment]
Think we can close this for now?

**Comment by mariusandra** [comment]
Indeed, closing for now. If we revisit this and need the this code, we can easily grab it from the PR.

**Pull request closed without merging**
