### PR TITLE
Kea-TypeGen Upgrade 36

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Bumps kea to `2.2.0-beta.6` and kea-typegen to `0.0.36`, including all updates from last night
- Adds support for `props`, `key`, `defaults` and other smaller changes
- Adds support for listeners that listen to actions from another logic

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by Twixes** [comment]
Why is `logic.key` sometimes `string`, sometimes `unknown`, and sometimes `undefined`?

**Comment by mariusandra** [comment]
Hey!
- `string` when props are typed and we're sure `key: (props) => props.id` returns a string
- `undefined` when there's no key in the logic
- `unknown` when there is a key, but we don't know it... because there is no type information for the props given

To type the props, do this:

image

(yes, I should write all of this down in a documentation)

The `props: {}` property does nothing right now, other than provide a type for the props via `props: {} as {...}`. In future versions of Kea, I hope to make it possible to use this key to assign default props to the logic...

**Comment by mariusandra** [comment]
Tagging @EDsCODE in here as well, since this is the only documentation right now about setting the type for props :).

**Comment by mariusandra** [comment]
Closing this PR to avoid potential merge conflicts and will make a new one later for the latest typegen, which hopefully won't change much anymore.

**Pull request closed without merging**
