### PR TITLE
feat(hogql): replace filters with query backend side

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

We eventually want to migrate the `filters` column of insights to the `query` column. In preparation for this, we do a live replace behind a feature flag in this PR - allowing us to fix any issues.

## Changes

This PR replaces the `filters` property of insights with a `query` (by converting existing filters using the `filter_to_query` method) based on a feature flag. This allows us to find places that break when replacing filters with queries.

There are three places where I could potentially handle the replacement: (1) in the insight model (2) in the insight serializer with a custom getter (3) in the `to_representation` method. I opted for (3) as this method contains code cleaning up filters and merges in dashboard overrides. Let me know if I'm missing something about how we handle dashboard filter overrides in the new query system.

Any fixes are out of scope for this PR and we just want to have a safe way to try out converted insights.

## Does this work well for both Cloud and self-hosted?

The flag should defaults to "off" in a self-hosted environment.

## How did you test this code?

Be sure to start the dev server with `POSTHOG_PERSONAL_API_KEY` set.

Screenshot 2024-04-08 at 12 22 04

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
> Isn't this doing what is already live since #21781 or am I missing something? 🙈

It's actually something different :) This PR replaces the `filters` returned as part of an insight (note: the actual *insight model*, not the computed insight results), whereas @Twixes PR changes the backend side calculation of *results* to be based on a `query` from `filters`.

**Comment by webjunkie** [comment]
Ah thanks, it's adjusting it there. Got it.

**Review by mariusandra — APPROVED** [review]
Makes sense to add this with a flag. It could also be worth running this conversion function in a python shell with real data to see what's up.

Also somewhat related, I've seen many support cases, where the culprit was pydantic errors because there was a `{}` property filter left at the end of an array.

**Comment by thmsobrmlr** [comment]
> Makes sense to add this with a flag. It could also be worth running this conversion function in a python shell with real data to see what's up.

Yup, at some point the `filter_to_query` function should be used to migrate insights, so I'm planning to make it robust against all malformed filters.

**Pull request merged**
