### PR TITLE
Add `flake-assertive` + fix 2 rules

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Changes
1. add [flake-assertive](https://github.com/jparise/flake8-assertive) as dev dependency
1. add two new linting rules in the `flake8` configuration: A500,A501
1. fixed all the occurrences found
 
## Why
`TestCase` assertions like `self.assertEquals` [are deprecated](https://docs.python.org/3/library/unittest.html#deprecated-aliases) in Python 3.

## How did you test this code?
CI should be ✅

### CODE REVIEW

**Comment by hazzadous** [comment]
It's a shame to add a dependency for something that I don't think has caused much issue. I'm not sure it's worth it. Rather we should just use `assert`, given that we are using pytest, and the assert introspection seems pretty mature there.

**Comment by guidoiaquinti** [comment]
> It's a shame to add a dependency for something that I don't think has caused much issue. I'm not sure it's worth it. Rather we should just use `assert`, given that we are using pytest, and the assert introspection seems pretty mature there.

This hasn't cause much issues for now but I'm not sure about the future. I'm not familiar with pytest assert introspection but I'm also ok to close this without merging. You tell me

**Comment by hazzadous** [comment]
This is the [pytest assert](https://docs.pytest.org/en/6.2.x/assert.html) detail. e.g. we can always just use `assert`, and pytest will display a sensible message/diff. We should be leaning in more to pytest rather than trying to make unittest usage better.

**Comment by guidoiaquinti** [comment]
Thank you for the additional context! I'm closing this.

**Pull request closed without merging**
