### PR TITLE
fix(dev): Fix CH replicated table error when starting E2E tests

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Running `bin/e2e-test-runner` with a clean ClickHouse instance works just fine… but if you close Cypress and then start `bin/e2e-test-runner` again at some point, this error stops the show:

`infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: Table posthog_test.infi_clickhouse_orm_migrations does not exist.`

## Changes

I introduced a setting in our `infi.clickhouse_orm` fork, which fixes the issue. More context in https://github.com/PostHog/infi.clickhouse_orm/pull/11. This PR just enables that solution.

`docker compose -f docker-compose.dev.yml down` is no longer needed.

### CODE REVIEW

**Review by fuziontech — APPROVED** [review]

**Comment by pauldambra** [comment]
This is really cool! 🙌 😍

**Review by mariusandra — APPROVED** [review]
Next step, fixing `posthog/session_recordings/queries/test/test_session_recording_list_from_session_replay.py::TestClickhouseSessionRecordingsListFromSessionReplay::test_basic_query_with_ordering`

**Comment by daibhin** [comment]
@mariusandra ask and @pauldambra delivers: https://github.com/PostHog/posthog/pull/20683

**Comment by daibhin** [comment]
Haven't dug into why yet but started getting an error this morning when running the migrate command. Looks like it might be related to this change
```
(env) ➜  posthog git:(master) DEBUG=1 ./bin/migrate
2024-03-05 10:02:00 [warning  ] ['️Environment variable DEBUG is set - PostHog is running in DEVELOPMENT MODE!', 'Be sure to unset DEBUG if this is supposed to be a PRODUCTION ENVIRONMENT!']
2024-03-05T10:02:01.566108Z [warning  ] Skipping async migrations setup. This is unsafe in production! [posthog.apps] pid=25234 tid=8014945344
2024-03-05T10:02:01.569511Z [info     ] AXES: BEGIN LOG                [axes.apps] pid=25234 tid=8014945344
2024-03-05T10:02:01.569732Z [info     ] AXES: Using django-axes version 5.9.0 [axes.apps] pid=25234 tid=8014945344
2024-03-05T10:02:01.569777Z [info     ] AXES: blocking by IP only.     [axes.apps] pid=25234 tid=8014945344
Operations to perform:
  Apply all migrations: admin, auth, axes, contenttypes, ee, otp_static, otp_totp, posthog, sessions, social_django, two_factor
Running migrations:
  No migrations to apply.
2024-03-05 10:02:04 [warning  ] ['️Environment variable DEBUG is set - PostHog is running in DEVELOPMENT MODE!', 'Be sure to unset DEBUG if this is supposed to be a PRODUCTION ENVIRONMENT!']
2024-03-05T10:02:04.980006Z [warning  ] Skipping async migrations setup. This is unsafe in production! [posthog.apps] pid=25238 tid=8014945344
2024-03-05T10:02:04.981569Z [info     ] AXES: BEGIN LOG                [axes.apps] pid=25238 tid=8014945344
2024-03-05T10:02:04.981783Z [info     ] AXES: Using django-axes version 5.9.0 [axes.apps] pid=25238 tid=8014945344
2024-03-05T10:02:04.981830Z [info     ] AXES: blocking by IP only.     [axes.apps] pid=25238 tid=8014945344
Traceback (most recent call last):
  File "/Users/david/src/posthog/manage.py", line 21, in <module>
    main()
  File "/Users/david/src/posthog/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/david/src/posthog/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/david/src/posthog/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/david/src/posthog/env/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/david/src/posthog/env/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/david/src/posthog/posthog/management/commands/migrate_clickhouse.py", line 53, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/Users/david/src/posthog/posthog/management/commands/migrate_clickhouse.py", line 56, in migrate
    database = Database(
TypeError: Database.__init__() got an unexpected keyword argument 'randomize_replica_paths'
```

**Comment by neilkakkar** [comment]
I faced the same problem^ possibly because the versions are the same, but pip install-ing didn't actually update to the right version - I had to run:

```
pip uninstall infi-clickhouse-orm
```
and then install all requirements again for it to work

**Comment by Twixes** [comment]
Yeah, pip is unfortunately pretty dumb about git-based dependencies pinned to commit (https://github.com/pypa/pip/issues/2837). Looks like either the `-U` argument or uninstallation is needed.

**Pull request merged**
