### PR TITLE
chore: The alias function uses the wrong ordering

### PR DESCRIPTION
**Pull request by lharries**
## Problem

The alias ordering looks like it is the wrong way.

You should have the distinct ID of the user first, and the alias second: https://posthog.com/docs/integrate/server/python#alias

### CODE REVIEW

**Comment by lharries** [comment]
Taking Em and Raquel as it looks like is mainly a user invitation thing and therefore sits in growth?

**Comment by raquelmsmith** [comment]
I'd run this by pipeline team because I know there are specific ways they choose to alias people together based on which ID you want to keep. @xvello ? 

@lharries what problem are you trying to fix?

**Comment by lharries** [comment]
> @lharries what problem are you trying to fix?

I'm updating the libraries comments for how to use aliasing and spotted that this invocation is currently wrong.

Let me confirm properly with the pipeline team then we can decide to merge it or not

**Comment by lharries** [comment]
@tiina303 can I confirm that this update makes sense?

**Review by xvello — APPROVED** [review]
Looks fine to me indeed. The identity we want to keep is the django ID, not the invite_* one (although that identity is older).

The events for `invite_*` are already out of the buffer, but that case will be handled by our person_overrides mechanism.

**Review by tiina303 — APPROVED** [review]
lgtm, can you fix the tests, merge and verify that the calls worked (i.e. maybe check ingestion warnings).

**Review by raquelmsmith — APPROVED** [review]

**Comment by raquelmsmith** [comment]
Tests are good, @lharries you can merge this when you're around otherwise I'll do it in the morning my time.

**Pull request merged**
