### PR TITLE
perf: Don't compile the regex twice when evaluating it

### PR DESCRIPTION
**Pull request by zackelan**
## Problem

When evaluating a `regex` or `not_regex` query, we first call `is_valid_regex`, which attempts to compile the regex and returns False if it fails to compile.

If it passes validation, we then compile it again, and that second compiled pattern is what we actually use for the search.

## Changes

This removes the `is_valid_regex` call and instead returns False directly if `re.compile` throws an exception. This allows us to only do the compile step once, instead of twice.

## How did you test this code?

Ran `pytest posthog/queries/test/test_base.py`

### CODE REVIEW

**Review by yakkomajuri — COMMENTED** [review]
Nice! Two things: can we add a quick test for this? 

Also seems that some bot has messed up and updated snapshots on this PR - could you revert the commit and merge/rebase `master` before pushing the change up? Should do the trick

**Comment by zackelan** [comment]
test added (and checked that it failed before making my change), and snapshot commit removed.

**Review by yakkomajuri — APPROVED** [review]
I was more interested in a test that makes sure that we handle invalid regexes correctly without `is_valid_regex` but there might already be a test for it (I didn't check). Also I guess `re.error` would cover all of those use cases but that's not immediately clear.

This was all more of a nit to get you involved in writing tests so just approving this :) 

And let's just merge with these snapshots anyway - I thought `master` would have up to date ones but seems not

**Comment by zackelan** [comment]
> I was more interested in a test that makes sure that we handle invalid regexes correctly without `is_valid_regex` but there might already be a test for it (I didn't check). Also I guess `re.error` would cover all of those use cases but that's not immediately clear.

Yes, there's an existing test for invalid regexes (see farther up in `test_match_properties_regex`). This change shouldn't affect the validation behavior at all - previously we were calling `re.compile` and throwing away the result, only relying on it to throw `re.error` if the regex was invalid. This should have the exact same behavior but with one compile instead of two.

**Pull request merged**
