### PR TITLE
Tweaks to local clickhouse docker setup

### PR DESCRIPTION
**Pull request by marcushyett-ph**
## Changes

I could not get the following to work when developing locally:

- **Docker image build**: Could not find version 13.* of libpqdev - so I pinned it to an older version which exists (this might not be the best version - so would appreciate any feedback on this)
- `start-ch-dev` - Web container would not run because it was using the same port as the Webpack process also kicked off by yarn
- `clear-ch-dev`- The command failed since `docker compose` is not valid

## How did you test this code?

Built it locally and PostHog works
image

### CODE REVIEW

**Comment by hazzadous** [comment]
Am testing this now using vscode Remote Containers extension, I assume this what you were doing @marcushyett-ph  given you're on an M1 (and the default ch docker-compose wouldn't run there)?

**Comment by marcushyett-ph** [comment]
>  vscode Remote Containers extension

Not totally sure what this is - I was using docker-compose on the command line on my DO droplet

**Comment by hazzadous** [comment]
> > vscode Remote Containers extension
> 
> Not totally sure what this is - I was using docker-compose on the command line on my DO droplet

Ah ok cool I'll give that a go

**Comment by hazzadous** [comment]
I get 

```
$ docker build -f dev.Dockerfile .
...
#11 15.48 Collecting psycopg2-binary==2.8.6
#11 15.50   Downloading psycopg2-binary-2.8.6.tar.gz (384 kB)
#11 15.70     ERROR: Command errored out with exit status 1:
#11 15.70      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9v6o4hcu/psycopg2-binary_8968d2a745014a7f965e038e79d2c5a1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9v6o4hcu/psycopg2-binary_8968d2a745014a7f965e038e79d2c5a1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_mmm9z7u
#11 15.70          cwd: /tmp/pip-install-9v6o4hcu/psycopg2-binary_8968d2a745014a7f965e038e79d2c5a1/
#11 15.70     Complete output (23 lines):
#11 15.70     running egg_info
#11 15.70     creating /tmp/pip-pip-egg-info-_mmm9z7u/psycopg2_binary.egg-info
#11 15.70     writing /tmp/pip-pip-egg-info-_mmm9z7u/psycopg2_binary.egg-info/PKG-INFO
#11 15.70     writing dependency_links to /tmp/pip-pip-egg-info-_mmm9z7u/psycopg2_binary.egg-info/dependency_links.txt
#11 15.70     writing top-level names to /tmp/pip-pip-egg-info-_mmm9z7u/psycopg2_binary.egg-info/top_level.txt
#11 15.70     writing manifest file '/tmp/pip-pip-egg-info-_mmm9z7u/psycopg2_binary.egg-info/SOURCES.txt'
#11 15.70     
#11 15.70     Error: pg_config executable not found.
#11 15.70     
#11 15.70     pg_config is required to build psycopg2 from source.  Please add the directory
#11 15.70     containing pg_config to the $PATH or specify the full executable path with the
#11 15.70     option:
#11 15.70     
#11 15.70         python setup.py build_ext --pg-config /path/to/pg_config build ...
#11 15.70     
#11 15.70     or with the pg_config option in 'setup.cfg'.
#11 15.70     
#11 15.70     If you prefer to avoid building psycopg2 from source, please install the PyPI
#11 15.70     'psycopg2-binary' package instead.
#11 15.70     
#11 15.70     For further information please check the 'doc/src/install.rst' file (also at
#11 15.70     <https://www.psycopg.org/docs/install.html>).
#11 15.70     
#11 15.70     ----------------------------------------
#11 15.71 WARNING: Discarding https://files.pythonhosted.org/packages/fc/51/0f2c6aec5c59e5640f507b59567f63b9d73a9317898810b4db311da32dfc/psycopg2-binary-2.8.6.tar.gz#sha256=11b9c0ebce097180129e422379b824ae21c8f2a6596b159c7659e2e5a00e1aa0 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#11 15.71 ERROR: Could not find a version that satisfies the requirement psycopg2-binary==2.8.6 (from versions: 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1)
#11 15.71 ERROR: No matching distribution found for psycopg2-binary==2.8.6
#11 15.80 WARNING: You are using pip version 21.1.2; however, version 21.3 is available.
#11 15.80 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

i.e. it does need libpq-dev 😢  I wonder why it works in prod build 🤷  .  Anyway, there seems to be some [work to refactor this Dockerfile](https://github.com/PostHog/posthog/pull/6524/files#diff-3ed65642ec1610de6b0f162c77dc8499662ebeb7057d3f6c89108952d1cb33deL14) atm so I'm going to suggest we leave this PR for now and revisit when they are in

**Comment by marcushyett-ph** [comment]
@hazzadous sounds sensible to me.

**Pull request closed without merging**
