### PR TITLE
Fix: #346 Paths could be prettier with one user

### PR DESCRIPTION
**Pull request by anandvenkat4**
PR.

### CODE REVIEW

**Comment by timgl** [comment]
Thanks for this!

It's pretty good on a small screen, but on a bigger screen you would normally be able to see the full url, which you now can't anymore (see image).

This also cuts down urls that are already small anyway (like `posthog.com`).

I think the function should be something like, cut down URL if:
- screen width > 1024
- length of url > 40-50

Those numbers might be wrong so see whatever looks good!

image

**Comment by anandvenkat4** [comment]
> Thanks for this!
> 
> It's pretty good on a small screen, but on a bigger screen you would normally be able to see the full url, which you now can't anymore (see image).
> 
> This also cuts down urls that are already small anyway (like `posthog.com`).
> 
> I think the function should be something like, cut down URL if:
> 
> * screen width > 1024
> * length of url > 40-50
> 
> Those numbers might be wrong so see whatever looks good!
> 
> image

Sure, I will look for alternatives.

Thanks
Venkat

**Comment by anandvenkat4** [comment]
@timgl I made some improvements in the rendering of url depending on the length of the url and checked it with the different resolutions that are available as part of the chrome developer tools. Can you please check if this suffice or should I have to work on altering the url depending on the resolution size as well?

**Comment by timgl** [comment]
This is great, thanks!

**Pull request merged**
