### PR TITLE
chore: remove old error embeddings

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

Error tracking supercedes this. Was never released. Let's remove it

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
👍 assuming things go green

**Comment by pauldambra** [comment]
should we drop the `session_replay_embeddings` table?

**Comment by daibhin** [comment]
@pauldambra I've been burned by too many table migrations in recent memory 😂 Is that something the `safe_migrations_check` allows us to do?

**Comment by pauldambra** [comment]
I think because it's in ClickHouse the safe migrations check doesn't run - that's just for postgres migrations - but we can leave this for the future traveller to complain about 🤣

**Pull request merged**
