### PR TITLE
Create a bookmarklet for demoing posthog

### PR DESCRIPTION
**Pull request by macobo**
## Changes

This introduces a bookmarklet generated via https://mrcoles.com/bookmarklet/ into settings js setup code. Users can drag this to their bookmark bar and use it on a live site to generate events on real data.

I did not introduce this to setup flows - there wasn't a good place to put it without making things confusing.

### Images

Installing bookmarklet

ezgif-6-af5146e62627

Using it in bing

Screenshot from 2020-12-15 19-04-10

Result

Screenshot from 2020-12-15 18-00-48

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
How about making sure these events are tagged accordingly as "demo" or something? Could use super props? Although that might keep the cookie for later

**Comment by macobo** [comment]
For that to work this would need to modify the cookie logic as well, which makes the whole thing a bit more complex and harder to change. I think it's worth using it as-is in a few demos and iterating based on that. WDYT?

**Comment by yakkomajuri** [comment]
Yeah that works!

**Comment by yakkomajuri** [comment]
Made a small change because having it all in one line was leading to an annoying line break. Otherwise, I love this! Will merge when the checks are done, write some docs for it, and start recommending it to people.

**Review by yakkomajuri — APPROVED** [review]

**Pull request merged**
