### PR TITLE
Add new `api` composition approach

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Proposed way of composing API requests in the frontend in a less error-prone way than template strings (prompted by https://github.com/PostHog/posthog/pull/6574#pullrequestreview-786644927).

### CODE REVIEW

**Comment by Twixes** [comment]
Forgot to attach a code sample – here's a look at the difference (the old way still works, as the new one is only built on top of it):

#### Before

```TypeScript
people = await api.get(
    `api/projects/${teamLogic.values.currentTeamId}/actions/people/?${params}`
)
```

#### After

```TypeScript
people = await api()
    .actionsList(unwrapCurrentTeamId())
    .withAction('people')
    .withQueryString(params)
    .get()
```

**Review by mariusandra — CHANGES_REQUESTED** [review]
Hmmm... very interesting and very cool. Love it!

However, the high level question I have, is why does `Api` have to be a class? All this prototyping code looks very messy and complicated, could this be cleaned up. Was class inheritance not possible? You can always `export default () => new Api()` if you want to preserve callability.

However, to clean this up, I'd personally go for a nifty functional approach:

```ts
export const api = {
    _path: [],
    _queryString: '',

    // modifiers that do not mutate!
    addPath: (path: string) => ({ ...api, _path: [...api._path, path] }),
    setQueryString: (queryString: string) => ({ ...api, _queryString: queryString }),

    // all the endpoints in a compact and nested way
    withAction: (apiAction: string) => api.addPath(apiAction),
    projectsList: () => api.addPath('projects'),
    projectsDetail: (id = getTeamId()) => api.projectsList().addPath(String(id)),
    actionsList: (teamId = getTeamId()) => api.projectsDetails(teamId).addPath('actions'),
    actionsDetail: (actionId: ActionType['id'], teamId = getTeamId()) => api.actionsList(teamId).addPath(String(actionId)),

    // get, create, etc as they are, but with path merging
    get: () => {},
}
```

**Comment by Twixes** [comment]
Cleaned things up a bit, but I do like the current approach based on `ApiRequest`, as this way there's _evident_ separation between requests (each one being instantiated with `api()`), which is not the case as much with an approach like `({ ...api, _path: [...api._path, path] })`.

**Comment by Twixes** [comment]
Added some solid structure and got rid of the callable class instance hack as it's not useful anymore. @mariusandra Still not all the way there with query strings being typed as I didn't want to mess with them too much, but this is already smarter than direct `api.{create,get,update,delete}(url)`.

**Review by mariusandra — APPROVED** [review]
Few comments inline that I think would still make this nicer. Feel free to address and/or merge.

**Pull request merged**
