### PR TITLE
refactor(early-access): use query node

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Removes the persons list table.
- Updates the early access management page to get the persons list via a HogQL query instead.

## How did you test this code?

Clicked around

### CODE REVIEW

**Comment by neilkakkar** [comment]
_maybe_ we can move it to the header? always keep it there for details on how to implement?

Also, indeed, those new buttons are good buttons to keep

**Comment by mariusandra** [comment]
So more like this?

image

**Comment by neilkakkar** [comment]
I'd put them to the right --> Delete Archive | Implement public opt in | Edit; so Delete, the most destructive action is not easy to hit accidentally.

but also I can quickly make a PR for this afterwards so not a blocker, LGTM.

**Review by neilkakkar — APPROVED** [review]
This sparks joy, thanks!

**Pull request merged**
