### PR TITLE
Toolbar Typings

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Adds TypeScript typings for all "logic.js" files under "frontend/src/toolbar".
- Convert all components to TS under "frontend/src/toolbar"
- Upgrades kea & kea-typegen to the latest versions

- Runs typegen on all the files, causing 31 extra files to be changed in this PR. Sorry for the noise.
- In the latest typegen, `actions` return `void`, so there's a lot of extra noise in the diff because of that.

End result: thousands of lines of changed code, 9 logics out of 40 (edit: 45) are now fully typed, the entire toolbar folder is now fully typed.

## Checklist

- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
I also enabled stricter type checking (it being off was causing issues with returned action types - it was skipping ` | undefined` at times), merged with master and created types for all the new insights code.

This is ready for a review.

**Comment by mariusandra** [comment]
As another note, this is the first really big thing I do with TypeScript. Thus @Twixes or @EDsCODE , as you have worked with TS before, perhaps you'll easily spot some typing mistakes I'm making. 

I tried to use as little `any`s and as little `bla as unknown as TypeThatIWant` as possible, but sometimes it was unavoidable, especially with some DOM elements (and the code that converts querySelectorAll results to an array), shadow roots, etc. I'm open to any suggestions in how to improve this.

Regarding the `never` types in some of the generated definitions. Yeah... those shouldn't be there, but since the types are just not used at all, I don't think it's a big issue for now. As we gradually add types to all the other logics, these nevers in those Type.ts files will gradually disappear.

**Review by Twixes — COMMENTED** [review]
The "*array* of `never`" thing is *really* weird, but if it doesn't really affect anything, then I suppose it can be sorted out somewhere down the line.

**Review by Twixes — APPROVED** [review]

**Comment by mariusandra** [comment]
I fixed a few regressions this PR introduced. It should be ready to be merged now.

**Comment by mariusandra** [comment]
> The "_array_ of `never`" thing is _really_ weird, but if it doesn't really affect anything, then I suppose it can be sorted out somewhere down the line.

@Twixes Can you explain what's off with it? I don't know any details behind it... and right now `never` feels like just another falsy type a'la `null`, `undefined`, `unknown`, `false`, `NaN`, etc. What makes it different?

(...or say RTFM and I'll say "ok, that's fair" :P)

**Comment by Twixes** [comment]
### [RTFM, because it's pretty handy](https://www.typescriptlang.org/docs/handbook/basic-types.html#never)

But also, the types you mentioned are actually JS values, just falsy.

Then there is the TS type `void` which is not a JS value and only intended to convey the lack of a relevant value, e.g. the return type of a function without a `return` statement - such a function still returns *something* in JS, it's just that it's always `undefined` and completely irrelevant. Well, you could make a variable of type `void[]` and that'd be an array consisting of `undefined`s and/or `null`s. Just what would anyone do with that?

And then there is `never` which means that there does not exist a case in which the function returns. It just *never* returns. Two possibilities for that: either it always throws an error, or it contains an always infinite loop. In this case there is just *no* value to make an array out of. True null.

**Comment by mariusandra** [comment]
I read that `never` is also used to cull trees when using generics:

```typescript
type Arguments<T> = T extends (...args: infer A) => any ? A : never
type Return<T> = T extends (...args: any[]) => infer R ? R : never
```

In any case, thanks for the description and I added a fix for this to kea-typegen: https://github.com/keajs/kea-typegen/commit/4679826c9da998cbc44c32fa422c3f91f8244de1 . I'll release a version with it later.

**Comment by Twixes** [comment]
By the way, typegen has to be ran manually, right?

**Comment by mariusandra** [comment]
Yep.

I hope to get some acceptable documentation up by the end of the day, but the `tl;dr` is that you should run `kea-typegen watch` with some params while coding... and then commit the changed type files as well. In PostHog, you should run `yarn run typegen:watch`. 

It's a work in progress, so feel free to suggest any improvements.

I'm a bit annoyed that it's another command that needs to be run (and documented, etc). I think it could be possible to have this running as a webpack plugin. I ran into [some issues](https://github.com/keajs/kea-typegen/issues/4) when changing between branches with different typegen versions. Sometimes my IDE doesn't reload the generated types fast enough. These are just some of the issues I've found so far.

**Comment by Twixes** [comment]
Maybe it could just be a pre-commit hook?

**Comment by mariusandra** [comment]
Do you mean a pre-commit hook [that aborts the commit](https://github.com/keajs/kea-typegen/issues/5) if kea-typegen would write something out? Or to just write the new types on commit?

I'd definitely be in favor of the check. For writing them on commit, if something in the typing changes, we need to run a type linter (eslint-typescript) to assure that no `number` changed to `string` somewhere else in the code... and then break the commit anyway. I think the check option would achieve the same, but with fewer surprises.

Also, sometimes "kea-typegen write" will need to be run many times to get the correct type. For example with selectors that depend on selectors that depend on selectors. ([issue for fix](https://github.com/keajs/kea-typegen/issues/6)).

**Comment by Twixes** [comment]
Yeah, it may be just a check.

**Pull request merged**
