### PR TITLE
[patch] add longer timeout for scene test

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- the`changing URL runs openScene, loadScene and setScene` jest test has been timing out at 5seconds. 
- test whether a longer timeout will have success
*If this affects the frontend, include screenshots.*  

## How did you test this code?

*Please describe.*
- adjusting a test directly

### CODE REVIEW

**Comment by mariusandra** [comment]
Updating with master should help. The text was fixed here: https://github.com/PostHog/posthog/pull/7254/files#diff-589d52e098298c616c1f03c6fcb7454e53b112cabf29d859721946aa84ac9228

**Comment by mariusandra** [comment]
I just ran `yarn test` locally on `master` and it passed.

The original bug here was that the dashboard scene started to crash with turbo mode. With turbo mode, the logic was now loaded earlier, and it crashed because some API calls were not mocked.

**Comment by EDsCODE** [comment]
It always passes locally for me too but some of my latest PRs and others still are failing. Will try again

**Comment by EDsCODE** [comment]
Seems like it sometimes still wants to fail like [here](https://github.com/PostHog/posthog/pull/7303)

**Comment by mariusandra** [comment]
I think https://github.com/PostHog/posthog/pull/7313 could have done the trick

**Pull request closed without merging**
