### PR TITLE
1139-Fix regex for event filter

### LINKED ISSUE #1139: Filter by Event Type seems not working
**Describe the bug**
Filter by "Event Type" seems not working in Evnets view as well as in Action definition.

**To Reproduce**
1. Go to events page on app.posthog.com
2. Filter based on `Event Type` and try  `equal` or `contains`. As value set `submit`.
3. You will see no events match the filter.

If you set filter to `$type is not set` then you will see all events (even the "submitted form" events).
The same behavior is within creating/editing Action when add filter with `$type`.

**Expected behavior**
I am able to filter events based on event type e.g. 'click', 'submit', 'change'.

**Screenshots**
posthog1
posthog2
posthog3

**Hosted or self hosted?:**
On app.posthog.com

**Additional context**

Together with #274 I am not able to distinguish submitting form from input (checkbox) field change which blocks me to create Action.

**Usability hint**
It is a little bit confusing for me, that in select box is "Event Type" and then it's showing as "$type" (and in code it's `$event_type`). Aslo "Evnet Type" [help suggest 'click', 'submit', 'change'](https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/PropertyKeyInfo.js#L135) but on Event page (in the events list) I see "submitted form", "clicked input", etc.

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes
- fixes #1139 (regex was being called globally when we really just wanted to remove the prefix/first instance)

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
Haha! cc @timgl 

https://github.com/PostHog/posthog/pull/1040/files/93748d75a106e753e82756228cff0ac2be9b5fbe#diff-52d7ebc2151159c4363c0cc5539b6e10

I'd still prefer the fix I originally suggested, which really hooks this to the beginning of the line to avoid any future issues.

**Review by mariusandra — CHANGES_REQUESTED** [review]
requesting changes

**Comment by EDsCODE** [comment]
the javascript function `replace` [defaults](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) to the first occurrence but happy to make the regex explicit anyway!

**Comment by timgl** [comment]
@mariusandra Wow how rude of me ha. Not sure why I didn't act on that but my apologies

**Comment by mariusandra** [comment]
@timgl - hah, I noticed that when reviewing, yet I didn't think this would cause issues... turns out I was wrong :)

@EDsCODE - probably best to be very explicit as this bit us in the ass already once

**Review by mariusandra — APPROVED** [review]

**Pull request merged**
