### PR TITLE
feat: use readonly replica if available

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

stacked on top of #15749 

We use `django-redis` to access our Redis cache.

We use elasticache which provides a "reader" endpoint for access to read replicas.

But we don't use those replicas because we never tried to

## Changes

`django-redis` supports receiving an array of Redis urls and treats the first as the primary and any others as secondary.

So, let's do that.

## How did you test this code?

Edited my docker compose file to have a redis replica

added

```
    redis:
        extends:
            file: docker-compose.base.yml
            service: redis
        container_name: primary
        ports:
            - '6379:6379'
        networks:
            - redis-replication

    redis-replica:
        extends:
            file: docker-compose.base.yml
            service: redis
        container_name: replica
        ports:
            - "6380:6379"
        command: redis-server --replicaof primary 6379
        depends_on:
            - redis
        networks:
            - redis-replication

networks:
  redis-replication:
    driver: bridge
```

Started the application with the `REDIS_READER_URL` hard-coded to localhost:6380

Navigating the application I saw it use :6379 when setting values and :6380 when reading then

Screenshot 2023-05-26 at 14 02 45
Screenshot 2023-05-26 at 14 05 27

### CODE REVIEW

**Comment by xvello** [comment]
Heya @pauldambra, thanks again for jumping on this!

When I saw that read replicas were not used, I assumed this was because some of the redis uses could get into nasty edge cases with replication lag between the master and replicas. This is why I suggested having teams opt-into using the replica after they evaluated the impact. That's most probably me being too conservative because I don't have a good view of what's happening in django-land.

As django_redis supports instantiating several pools, what about keeping the `default` as is for now, and adding another with the dual-url scheme, that we can opt into for insights, then decice?

**Comment by pauldambra** [comment]
I'd put money on us not turning it on because we'd never turned it on 🤣 

We have about 6 weeks of metrics for replication lag from AWS. For the entire six weeks lag was measured in tenths of milliseconds

There was a ten minute period on the 23rd where lag was measured in seconds - which is what led to this discussion

But overall that's super reliable... and if we can do more (like compression or separating clusters) then we can reduce likelihood/impact of a  repeat.

----

The interesting thing about making it opt-in via code and a separate cache is that if we find it's problematic we have to fix the code where as it is now we can strip the ENV variable and force a rolling restart 

For the compression I can see being a little less YOLO but I feel bullish on this change

**Comment by pauldambra** [comment]
I'll separate the two PRs so we can deal with them separately too.

**Comment by neilkakkar** [comment]
Makes sense to me! We can get this in!

For the env vars - do we have a reader on dev, and can I send  a couple thousand decide requests on dev before we set this on prod?

**Comment by neilkakkar** [comment]
Ah, you're adding the env var only for the web pod, that's fine, even more de-risked 👍

**Comment by pauldambra** [comment]
> do we have a reader on dev, 

We do!

**Review by xvello — APPROVED** [review]
Looks great, thanks! Let's merge, enable it on dev, then prod 👍

**Pull request merged**
