### PR TITLE
refactor: remove redundant references

### PR DESCRIPTION
**Pull request by hirehamir**
## Problem

There are some unnecessary `&`s in the codebase. We take references in places we don't need to.

## Changes

There are no frontend changes.

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

It doesn't have an impact.

## How did you test this code?

`cargo test` passes locally.

### CODE REVIEW

**Review by hirehamir — COMMENTED** [review]
@Twixes are you open to this pull request?

**Review by Twixes — DISMISSED** [review]
@aspicer is the one with context on our Rust implementation of funnels, but currently this PR is somewhat unreviewable, as most of the changed lines are just formatting by `cargo fmt`, rather than actual code changes. Please revert the formatting changes, so that the PR is targeted to just references

**Comment by hamirmahal** [comment]
Okay, I'll redo the changes without `cargo fmt` right now.

**Comment by hamirmahal** [comment]
@aspicer are you open to this change?

**Review by aspicer — APPROVED** [review]
lgtm!

**Pull request merged**
