### PR TITLE
Match docker compose file clickhouse version to cloud prod version

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- our docker-compose ch follows latest rather than production which might have unintended and hard to track side effects. This [run](https://github.com/PostHog/posthog/runs/3314680462) is failing due to extra checks in a query clause that clickhouse added in the latest version
- explicitly set the version to cloud version 21.6.5.37
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by neilkakkar** [comment]
Unsure about this change: This now implies whenever D&I update CH for Cloud/self-hosted, we got to update this here, as otherwise when the update does happen, and a lot of things start failing (like in the tests here^^), we'd only find out in production.

Ok with it though if @tiina303  / @fuziontech  are happy to add this to the "upgrading CH runbook / checklist" / any process that ensures we don't miss this.

**Comment by tiina303** [comment]
We're using similar hardcoded version for self-hosted too
https://github.com/PostHog/charts-clickhouse/blob/30f4a13d97dfe6d977384b8821ebafd3d77e06b9/charts/posthog/templates/clickhouse_instance.yaml#L88
so this seems fine to me.

**Comment by neilkakkar** [comment]
Yeah, makes sense! My point was to remember to change it here as well from now on, whenever you change it there^

**Comment by tiina303** [comment]
Maybe we can have a Github action change these together (or comment on a pr that's changing any one of them) @Twixes

**Comment by Twixes** [comment]
It seems to me that automating this would end up being pretty brittle, so maybe the easiest solution is just comments in the right places. That's what I added in https://github.com/PostHog/charts-clickhouse/pull/101 + https://github.com/PostHog/posthog/pull/5623

**Pull request merged**
