### PR TITLE
chore: Use depot again for production builds

### PR DESCRIPTION
**Pull request by timgl**
Reverts PostHog/posthog#10881

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]

**Comment by yakkomajuri** [comment]
@timgl why did we do this? we don't need the prod build to be fast, and I'd rather it be reliable

See how it is failing intermittently today:

Screenshot 2022-09-20 at 15 36 29

Note that this might not be related to depot, but just wondering why use it in areas that we don't have great speed requirements for

**Comment by timgl** [comment]
> @timgl why did we do this? we don't need the prod build to be fast, and I'd rather it be reliable

Pushing out a fix to a customer in ~20mins rather than 40 mins is definitely valuable, but agree them failing is very annoying. Let's revert.

**Comment by yakkomajuri** [comment]
@timgl that's fair if the disparity is indeed that large. I do think it's worth monitoring how this goes for a longer period of time and then maybe switching over

**Comment by timgl** [comment]
I've spent a bit too much time creating pull requests reverting and re-reverting depot. I think @hazzadous had some good ideas on how to get some of the speed gains just by doing better caching?

**Comment by hazzadous** [comment]
Yes see https://posthog.slack.com/archives/C0113360FFV/p1663689483569449 , it's already in motion, please add anything I should test before we move to the new build.

**Pull request merged**
