### PR TITLE
add version to person

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

After enough thinking, I came to the conclusion that this is probably the best approach to handling keeping persons in sync across Postgres and ClickHouse. Every time we update a person, we should increment this value. 

Subsequent PR swill then make sure we send this value in the Kafka message and pull this column into the CH table. 

This will replace `_timestamp` as the `ver` value for our persons `ReplacingMergeTree`.

In Postgres, this will look something like:

```sql
UPDATE posthog_person
SET version = COALESCE(version, 0)::numeric + 1
WHERE person_id = 1
```

We should also probably only increment this if something _actually_ changes, which is something that would fall on you @tiina303 regarding returning updated props. Happy to chat more about this.
## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Marked this as draft given I need to fix the default setting

**Review by tiina303 — COMMENTED** [review]
I like this idea.

> We should also probably only increment this if something actually changes, which is something that would fall on you @tiina303 regarding returning updated props. Happy to chat more about this.

Ideally yes, but nothing bad happens if we always increment, unless we're worried about running out of 2147483647 values, in which case we should use the bigint type.

**Comment by yakkomajuri** [comment]
> Adding a default value will lock the whole table & could be a slow migration, can that be a problem? Didn't we add a test against it in #6640?

Yes, hence I added this comment last night:

Marked this as draft given I need to fix the default setting

**Comment by yakkomajuri** [comment]
Nothing bad happens except some additional logic. Although could be that it's just cleaner to always increment

**Review by tiina303 — APPROVED** [review]
lgtm 

I will add `SET version = COALESCE(version, 0)::numeric + 1` to the update properties function (even if we run it in a transaction with other things worst case we increment multiple times, best case we avoid a problem, when someone forgot to increment).

**Comment by hazzadous** [comment]
> even if we run it in a transaction with other things worst case we increment multiple times

I guess we've got to be careful to ensure we've committed before we send any kafka messages? Otherwise we might think we're in sync when we're not, if the transaction is rolled back and a different change comes in that is successful? I have no idea if that's relevant to our situation.

Would a uuid, or a hash instead be relevant here?

**Comment by hazzadous** [comment]
> Would a uuid, or a hash instead be relevant here?

Or a sequence and `nextval`, that way we don't have to worry about rollback?

**Comment by yakkomajuri** [comment]
@hazzadous 

If you check the latest plugin server PRs by @tiina303 you'll see that this is handled.

Our Postgres transactions will throw and rollback automatically if they encounter an error. Kafka producing will only happen when `COMMIT` succeeds.

Either way, that's something we can make sure of in the plugin server.

**Comment by yakkomajuri** [comment]
PR showing how this will be used #6667

**Comment by yakkomajuri** [comment]
Would love a final look and ✅ or nah given you originally had comments @macobo

**Comment by hazzadous** [comment]
@yakkomajuri great!

What do we do btw if we fail between the commit and the message to kafka? Do we have something running periodically to check the diff between clickhouse and postgres? (sorry for my ignorance btw, just curious)

**Comment by tiina303** [comment]
> What do we do btw if we fail between the commit and the message to kafka? Do we have something running periodically to check the diff between clickhouse and postgres? (sorry for my ignorance btw, just curious)

afaik noting, but the good news is now it will be easy to debug why things are out of sync. Additionally since we send the full properties spec to kafka the next update for setting user properties will cover effectively sync them (in case we merged  or deleted the person that's trickier, haven't looked at the details there for what we could do)

**Comment by yakkomajuri** [comment]
@hazzadous unfortunately at the moment the plugin server is does not do much to handle such failures. In fact, we don't handle these things very well anywhere, really. See e.g. https://github.com/PostHog/posthog/issues/6314 https://github.com/PostHog/posthog/pull/6631

This is something I'd like to work on but still going down the data integrity priorities list for now.

There are a few bits of good news here though:

We won't commit offsets to Kafka if we fail to process the event (e.g. because the whole server crashed). That means the event will be reprocessed, which would help us potentially fix any intermediate states. In this particular case, we might end up out of sync though with regards to persons. However, we still keep Postgres as the source of truth and have good monitoring available. i.e. the approach right now would be to sync from Postgres if we notice this issue.

**Comment by hazzadous** [comment]
> We won't commit offsets to Kafka if we fail to process the event (e.g. because the whole server crashed). That means the event will be reprocessed, which would help us potentially fix any intermediate states. In this particular case, we might end up out of sync though with regards to persons. However, we still keep Postgres as the source of truth and have good monitoring available. i.e. the approach right now would be to sync from Postgres if we notice this issue.

Right, so I guess the key point here is we have guaranteed delivery of messages with kafka, sounds great.

**Review by macobo — APPROVED** [review]
Sorry for the late review - noticed an unrelated long thread but missed your comment.

**Comment by yakkomajuri** [comment]
Worth noting that your point about atomic event ingestion is still very valid and something I'd like to look into and see how those large transactions may or may not bite us. 

We're wrapping up some work on the ingestion pipeline and I think this could be valid to look into after

**Comment by yakkomajuri** [comment]
Marked as draft to prevent a merge. I just want to check what might break in the plugin server. Given `null=True`, probably not ingestion. Possibly tests. I'll check.

Either way, +1 for monorepo :D

**Comment by yakkomajuri** [comment]
https://github.com/PostHog/plugin-server/pull/618

**Comment by yakkomajuri** [comment]
I'm getting this in.

Important to note that we've seen old Postgres instances struggling with migrations on tables in the hot path because they can't get a lock. This happens when analytical queries are hanging around for long.

Before releasing 1.30.0 this migration is something to consider. However, we already have a migration story to ClickHouse-backed instances and k8s instances would not have this problem.

Finally, I'll add the script below somewhere in the engineering handbook. It should help people clear queries that are hanging in order to get the lock:

```python
# How to run:
# Add this code to a delete_queries.py file
# Run python manage.py shell < delete_queries.py

import os
from time import sleep

from django.db import connection

QUERY_TIME_LIMIT = os.environ.get("QUERY_TIME_LIMIT", "5 minutes")
TARGET_TABLE = os.environ.get("TARGET_TABLE", "posthog_person")
DRY_RUN = os.environ.get("DRY_RUN", "1") == "1"

MAX_TRIES = 10


def fetch_open_queries():
    res = []
    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT
                pid,
                now() - pg_stat_activity.query_start AS duration,
                query
            FROM pg_stat_activity
            WHERE (now() - pg_stat_activity.query_start) > interval '{QUERY_TIME_LIMIT}'
            AND state = 'active'
            """
        )
        res = cursor.fetchall()
    return res


open_queries = fetch_open_queries()
tries = 0

while open_queries and len(open_queries) > 0 and tries < MAX_TRIES:
    for query_details in open_queries:
        if TARGET_TABLE in query_details[2]:
            print(f"Preparing to kill query {query_details[0]}:")
            print(query_details[2])
            print(f"It has been active for {query_details[1].seconds}s")
            if not DRY_RUN:
                with connection.cursor() as cursor:
                    cursor.execute(f"SELECT pg_terminate_backend({query_details[0]})")
                print(f"Killed query {query_details[0]}")
            print("")
    open_queries = fetch_open_queries()
    tries += 1
    sleep(1)
```

**Pull request merged**
