### PR TITLE
feat: add website traffic template

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We have an excellent website traffic dashboard from @andyvan-ph. Seems a good opportunity to help folk use PostHog well

## Changes

Adds (a slightly stripped down version of) that dashboard as a template

templates

Set the names of the templates to:

* Product analytics 
* Website traffic

Screenshot 2022-10-31 at 19 26 12

## How did you test this code?

Running it locally and seeing it work :)

### CODE REVIEW

**Comment by mariusandra** [comment]
Something's broken:
image

Looks good in general, though what about the users who don't have a blog?... and "website app" vs "website traffic" is not really *that* descriptive of the difference 😅

**Comment by pauldambra** [comment]
> "website app" vs "website traffic"

Yep, I was hoping @andyvan-ph would see it and say "those aren't the names. they _should be_ blah" 😓

**Comment by lharries** [comment]
@pauldambra this is major! ~~How is it that customers will configure which events the insights are linked to e.g. organic SEO users? Or should it all work out of the box~~ Just read through the code - looks like it should work out the box if I'm reading it correctly. Very cool

**Comment by pauldambra** [comment]
> Or should it all work out of the box

It should work out of the box... I've stuck to only the tiles that use autocapture.

But 🤔 the dangerous "should" word crops up. I'll throw in a feature flag and then we can test that "should" :)

**Comment by joethreepwood** [comment]
Can't comment in much depth on the code, but the content looks great to me. 

If there are unanswered questions about what things are called, is it worth adding in a text dashboard card that explains some of that? Just throwing the idea out there to be awkward.

**Review by joethreepwood — APPROVED** [review]

**Pull request merged**
