### PR TITLE
Make PluginConfig.order mandatory

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

That field was nullable, but since we're now enforcing plugin processing order, we shouldn't allow that anymore.

## Checklist

- [ ] Django backend tests

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Some black issue, otherwise 👍

**Comment by Twixes** [comment]
Added a migration to enforce `order`

**Review by mariusandra — CHANGES_REQUESTED** [review]
Ah, no, please remove that. This will make the current version crash. When deactivating a plugin we don't reset its order. Also, while this `order` should technically be unique per team, in practice I'm sure it won't and we will get various API errors. We should be resilient, not strict.

**Comment by Twixes** [comment]
I see how this is problematic, but then if we are willy-nilly with order, it may mess up someone's data by running processing in an unintended order?

**Comment by Twixes** [comment]
I mean, we can easily do this another time, so reverted, but in the end I'd feel safer about the pipeline if we enforced this.

**Review by mariusandra — APPROVED** [review]
Yeah, let's think of this another time. The main question: what to do if you disable a pluginConfig? Set the `order` to null? Set it to `0 - pluginConfig.id`? Too many random issues to worry about with both cases, so I'd punt on it. This looks good for now.

**Pull request merged**
