### PR TITLE
feat: Calculate count of static cohort

### PR DESCRIPTION
**Pull request by psykomal**
## Problem

Adds count of users in static cohort on CREATE or UPDATE. Solves #15110 

## Changes

Calling `calculate_cohort_ch.delay` in calculate_cohort_from_list and insert_cohort_from_insight_filter tasks. Note: This will launch another celery task after the completion of above mentioned tasks. Another alternative is to use chain() but didn't go there to keep things simple.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

1. Created static cohort by uploading a csv and checking count. Updating csv with new users and checking count.
2. Creating static cohort from Insights and checking count
3. Ran relevant tests

### CODE REVIEW

**Comment by psykomal** [comment]
Another note - Currently calculate_cohorts() task is only run for dynamic cohorts. Do we want to run it for static as well ?

**Comment by neilkakkar** [comment]
Hey @psykomal - thanks for the contribution!

Static cohorts by definition don't change over time, so don't need to be recalculated. For this reason, this solution doesn't quite work.

Here's what you should do instead:

Like this query for dynamic cohorts: https://github.com/PostHog/posthog/blob/master/posthog/models/cohort/util.py#L289 - write one for static cohorts (table name / details here:  https://github.com/PostHog/posthog/blob/master/posthog/models/person/sql.py#L256 ).

And then run this in the cohort calculation task `insert_users_by_list` - and save the count on the cohort right there before returning.

**Comment by psykomal** [comment]
Thanks @neilkakkar for the quick response! I'll look into that

**Comment by neilkakkar** [comment]
Looking good! All this is missing is a few tests. Here's a good place to add them / to get inspiration from existing tests: https://github.com/PostHog/posthog/blob/master/posthog/api/test/test_cohort.py#L125

You can add count to just this test; and then add a second one which is not a csv upload, so we handle both code paths.

**Comment by psykomal** [comment]
@neilkakkar sure will do. Should I also update snapshots for the failing tests to pass ?

**Comment by neilkakkar** [comment]
Ah, looks like the automatic update isn't running on forked PRs.

Yes, if you run the test in question like so: `./bin/tests posthog/api/test/test_feature_flag.py::TestBlastRadius::test_user_blast_radius_with_multiple_static_cohorts` it should update snapshots

**Comment by psykomal** [comment]
Hey @neilkakkar, the tests have passed in your draft. Let me know if I need to do anything more.

**Comment by neilkakkar** [comment]
Perfect - thanks @psykomal :) . Looks like our CI is a bit borked for contributor PRs - I'll merge the copy. Should be equivalent, as the commits are still under your name.

I'd love to send you a PostHog merch code for writing this PR - send me an email at [first name] @ posthog.com

**Comment by psykomal** [comment]
Sure, thanks @neilkakkar for your support and really appreciate the quick responses!

**Pull request closed without merging**
