### PR TITLE
feat(experiments): validate events for Trend experiments

### PR DESCRIPTION
**Pull request by jurajmajerik**
## Changes
Same as #19988 but for trends.

I'm not sure of the purpose of `exposure_results` - in my tests, this was always an empty array; not used as an input for validation.

## How did you test this code?
Unit tests

### CODE REVIEW

**Comment by neilkakkar** [comment]
`exposure_results` check exposure for experiment, (think of it as step 1 in the funnel - i.e. how many people enter the experiment). By default, this is calculated using `$feature_flag_called` events, which is probably why it's empty in your tests - those events aren't happening.

Would be nice to add a validation here for exposure counts as well! I.e. if there are trend experiment results, with a flag variant, but no exposure, means something is wrong, and we can prompt them to either change exposure metric, or send feature flag called events. I think when it doesn't exist we default to equal exposure, which can sometimes be wonky

**Review by neilkakkar — APPROVED** [review]

**Comment by neilkakkar** [comment]
I think failing test is valid - we're probably over-eager with some validation?

**Comment by jurajmajerik** [comment]
The test was failing correctly because the `test` variant was missing (had been uncommented). I added it back and fixed the assertions for counts and breakdown values.

However, the hardcoded probabilities now no longer match:
`AssertionError: 0.26459 != 0.299 within 2 places (0.034409999999999996 difference)`

Do we want just to change them to the new ones?

**Comment by neilkakkar** [comment]
oh actually, this is a good test, when there are more than 1 test variants, we only need one existing variant to show results, and we shouldn't block results because other variants aren't there. (specially because when dealing with multiple variants, it can be possible some variants never have results, because, let's say it rolls out to a very small fraction and is an edge case).

So, we should update validation such that it requires:

(1) The control variant
(2) Atleast 1 test variant. But ok to not have other test variants.

For both funnels and trends 👍

**Comment by jurajmajerik** [comment]
Oh, I see!

Looking at the [old validation](https://github.com/PostHog/posthog/blob/cb12ce03c2c0b1d774c505dd3cfa8292a08966a0/ee/clickhouse/queries/experiments/trend_experiment_result.py#L289) earlier, I was wondering why we raise "No control variant data found" when both `control` and `test` were missing. Now I get it - `control` can never be missing, but it's okay if _some_ test variants are missing if at least one of them is present.

I was now actually wondering if we need the new validation at all. But it seems we do - the old validation will tell you when the variants are missing on the events, but it makes no distinction whether _some_ events have been ingested or _none_ at all. We indeed need to look at the unfiltered `insight_results` to get that information 👍

**Review by neilkakkar — APPROVED** [review]
Not sure why the snapshots have updated like so 🤔 

but lgtm! Reminder to update the same for funnels :)

**Pull request merged**
