### PR TITLE
Help popup refresh

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

A revamp of the help popup to adjust it to our new UI style.

| Before | After | 
| --- | --- |
| Screen Shot 2021-11-01 at 18 25 12 | Screen Shot 2021-11-01 at 18 15 57 |

### CODE REVIEW

**Review by clarkus — APPROVED** [review]

**Review by paolodamico — APPROVED** [review]
lgtm! merging to avoid merge conflicts

**Comment by paolodamico** [comment]
This was merged 5 mins ago, but it's not showing on the commit list 🤔 , any ideas?

**Comment by paolodamico** [comment]
Oh shoot, this wasn't merging to `master`, apologies. Let's just deal with any merge conflicts later.

**Comment by Twixes** [comment]
Yeah, I wanted to merge this only after the base PR is approved 😅 But it's not a big problem

**Pull request merged**
