### PR TITLE
Persons modal session recordings?

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

Here we are matching a return list of sessions (for just TRENDS persons rn, but the same logic would be applied to the other person modal calls too), and not session recordings because adding the session recording filter on it makes the query extremely slow (on production that filter takes like 40 seconds)

And thennn we are trying to match it to the persons to see if any of those people have a valid session recording 😭 

Obviously this is less than ideal but we're looking for a super hacky temporary solution that could provide any quick value 

ALSO. My CH setup is messed up and I have no data on it right now. I left some mock data up

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by mariusandra** [comment]
Hmm... yeah, something that slow is obviously not a real solution :).

Instead of that one query that ties together events, session recordings and a lot of magic, could we fake it by making a simple query to the "session_recording_events" table (in clickhouse) and filtering by distinct_id (or multiple distinct ids) and timestamp.. even if it's just "has any session recording event in the funnel conversion window timeframe" or whatever else gives accurate enough results fast enough. Then if anything is found, we can show a "play" link... and the person/sessions pages will take it from there.

**Comment by neilkakkar** [comment]
Maybe I'm missing something, but since we use the Django Serializer to return Person results, if we were to: join the ORM definition of Persons table to `session_recording_events`, and ensure the serializer picks that up, there would be no extra work for a second query?

**Comment by liyiy** [comment]
> Hmm... yeah, something that slow is obviously not a real solution :).
> 
> Instead of that one query that ties together events, session recordings and a lot of magic, could we fake it by making a simple query to the "session_recording_events" table (in clickhouse) and filtering by distinct_id (or multiple distinct ids) and timestamp.. even if it's just "has any session recording event in the funnel conversion window timeframe" or whatever else gives accurate enough results fast enough. Then if anything is found, we can show a "play" link... and the person/sessions pages will take it from there.

hmm today the session recordings with > 0 duration query seems faster, I think maybe because of the person distinct ID PR revert?

**Comment by liyiy** [comment]
> Maybe I'm missing something, but since we use the Django Serializer to return Person results, if we were to: join the ORM definition of Persons table to `session_recording_events`, and ensure the serializer picks that up, there would be no extra work for a second query?

What do you mean by second query? Do you mean to replace the step where we would filter for multiple persons/distinct_ids and timestamp with a join instead?

**Comment by neilkakkar** [comment]
So, I'm assuming: (1) You only need a distinct ID on the Persons Modal, and the button links to the pre-existing sessions page for the user.

Now, the problem with Trends/Funnels Persons endpoint is that we don't know if every person_id we have has distinct_ids that link to a session. So to figure this out, if our serializer outputs, say, session_distinct_ids, we are done.

To make this happen, we could either do what you're already doing^, or, the option I was suggesting is to connect [the Persons Model](https://github.com/PostHog/posthog/blob/master/posthog/models/person.py#L71) to `session_recording_events` via the distinct ids. (I didn't realise there's a separate CH model for Persons, so unsure how this would work anymore). In funnels atleast, we're using the PersonSerializer to return this data (not `ClickhousePerson`), and if I understand the ORM correctly, if it's on the model and used in the serializer, it would load that property before sending the data.

Another question I'm unsure about is whether this will be slower or not? But given that behind the scenes this will do what Marius was suggesting anyway (i.e. filter sessions based on distinct id), I think it should be fast enough.

**Comment by macobo** [comment]
Just linking the relevant issue: https://github.com/PostHog/posthog/issues/5173

> Instead of that one query that ties together events, session recordings and a lot of magic, could we fake it by making a simple query to the "session_recording_events" table (in clickhouse) and filtering by distinct_id (or multiple distinct ids) and timestamp.. even if it's just "has any session recording event in the funnel conversion window timeframe" or whatever else gives accurate enough results fast enough. Then if anything is found, we can show a "play" link... and the person/sessions pages will take it from there.

+1 for this. This is exactly how sessions and session recordings are tied together and this performs really well given you know session timestamps  and distinct_ids. Grep for `join_with_session_recordings`. A proper solution here will use the same approach.

**Pull request closed without merging**
