### PR TITLE
Toolbar "button mode"

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Still WIP, but there's now a tiny button that opens the toolbar:

image

Long-pressing it opens a rag-tag modal that lets you choose which style of toolbar do you want:

image

Not sure if that's an inherently obvious way to do it. I might change it later and e.g. show alternative options/buttons when you mouseover (+ and press on mobile). We'll see

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
I think we should just default to docked mode, and allow people to switch if they really want to.

Also I might be biased (and we will be changing logos) but I think white background looks better:

**Comment by mariusandra** [comment]
Updates!

The button is now white and comes with two side-buttons that 1) hide the button and 2) open the toolbar in "float" mode. 

screencast 2020-06-05 13-00-03

Not visible above, but everything is really smooth:

screencast 2020-06-05 13-03-19

Clicking on the big "hedgehog" opens the toolbar in "dock" mode.

screencast 2020-06-05 13-05-34

I'm not super satisfied with how the float mode opens (I think the animation is too slow), but it should all be good enough now.

Everything should work on mobile as well, yet I had some trouble hooking it up and testing thanks to HMR. I'll check later. There will be a separate task with a proper push for good mobile support later anyway.

**Comment by mariusandra** [comment]
@timgl This can be looked at now. 

The UX might need to be tweaked once we test this with real people. I guess it's good enough for a soft launch though.

image

Right now there are 3 clickable targets:
- the main button (opens "docked more")
- the "float mode" button
- the "close" button

On desktop if you hover over the main button you get the extra actions. On mobile if you long press the main button you get the extra actions.

Some ideas for future changes:
- replace the "float mode" button with a toggle that switches between float/dock, making the main button the one that opens the selected mode
- add a third "aim/target/inspect" button, so you could directly inspect some element in the button mode. clicking it would select the element and then expand the toolbar


Also, if needed, the "circle" system supports multiple levels. We could build a nested menu and do all sorts of crazy stuff (create a spinning solar system for example):

image

**Review by timgl — COMMENTED** [review]
This looks good! One thing I implemented in my version was it remembered where you dragged the button to. That way if our default position is in the way of the logout button for example and you drag it somewhere else, it'll stay there on refresh:

https://github.com/PostHog/posthog/pull/432/files#diff-90855717687535126679c5f306606720R11

**Comment by mariusandra** [comment]
That's now implemented as well! @timgl , ready for another look.

**Review by timgl — APPROVED** [review]
Looks good, not sure why e2e tests are failing but otherwise all good

**Comment by mariusandra** [comment]
There's a caching issue. In the e2e tests `yarn install` is skipped because `if: steps.yarn-dep-cache.outputs.cache-hit != 'true'`. Thus it won't install the missing package.
I'm not sure why... and I'd rather have @fuziontech check this out.

**Comment by fuziontech** [comment]
Updated the config to hash `**/yarn.lock` recursively. Seems to have busted the cache here as it should have since `yarn.lock` was modified. :crossed_fingers: that should take care of it. It does look like one of the e2e tests is failing though.

**Comment by mariusandra** [comment]
All tests now pass. I'm just not sure if [the fix](https://github.com/PostHog/posthog/pull/925/commits/e8674492f7ede4e3f6e0d60a3820d3dd95f0e6b2) for the tests by @fuziontech should go in to master or not.

**Comment by fuziontech** [comment]
should be good to have that in master

**Pull request merged**
