### PR TITLE
feat: Add filters and searching to event properties

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Someone mentioned it would be helpful to be able to simply hide all PostHog properties when looking at the PropertiesTable. Seemed like an easy enough change

## Changes

* Adds a filter button to the event properties in Persons, Events and Recordings
* Also adds search because why not
* Open question: Should this be a "persisted property" via localstorage?

**Events**
Screenshot 2023-03-23 at 15 36 29

**Person**
Screenshot 2023-03-23 at 15 36 49

**Recording**
Screenshot 2023-03-23 at 15 36 38

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by pauldambra — COMMENTED** [review]
few sharp edges...

* `distinct_id` isn't hidden but does have a little posthog
* empty state text "needs" changing when there are no matches
* `show hide X hidden properties` doesn't seem to work any more

**Comment by benjackwhite** [comment]
> few sharp edges...
> 
> * `distinct_id` isn't hidden but does have a little posthog
> * empty state text "needs" changing when there are no matches
> * `show hide X hidden properties` doesn't seem to work any more

Well noticed! Should be easy enough so worth fixing

**Review by Twixes — APPROVED** [review]
Looks great! Made a few tweaks, merge if they look good to you or point anything out.

**Pull request merged**
