### PR TITLE
feat(insights): aggregate funnel on custom hogql

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Funnels can be aggregated by custom HogQL, but you'll need to edit an insights's source to do so.

## Changes

WIP

## How did you test this code?

WIP

### CODE REVIEW

**Comment by Twixes** [comment]
Looks like this is a draft for now, let me know when it's reviewable.

**Comment by mariusandra** [comment]
I got it to a quality bar called "good enough, I hope":



However I had to use some deprecated components to get there... 🙃 

Ready for feedback @Twixes

**Review by Twixes — APPROVED** [review]
Okay, so I upgraded `Menu` so that we can stick to this being a menu (which it is) instead of unwrapping everything to basic components. Let me know if you think this makes sense as is @mariusandra

**Comment by mariusandra** [comment]
Thanks a lot! Makes a ton of sense and would have taken me forever to clean up. Much appreciated! 👍

**Pull request merged**
