### PR TITLE
chore(django): squash django migrations

### PR DESCRIPTION
**Pull request by hazzadous**
## Problem

We have lots of migrations, and they are not super fast to apply. This impacts 
CI in that we have to run these migrations before every run in this repo, as well 
as e.g. in the tests on the Helm chart, which makes these especially annoying 
to work with.

## Changes

Uses the squashmigrations command to make it such that initial installs will need to 
run far fewer migrations. Existing installs will still be able to reference the old individual 
migrations, thus there is no need to ensure that all deployments are on a particular version 
before rolling this out.

By running a single migration we can perform certain optimizations to speed up application
e.g. if we added then removed a model, we could instead in the squashed migration simple 
never create that model. If we have a model that started with a single field with individual 
migrations to add 100 more, we can simply create the model with all of the fields in one go.

See the [Django squashmigrations documentation](https://docs.djangoproject.com/en/4.1/topics/migrations/#migration-squashing) for context.

 1. add elided to any migration steps that don't need to run as part of
    the squashed migration
 2. run `./manage.py squashmigrations posthog 0284`
 3. checked out just before posthog 0285
 4. move `ee/migrations` and `posthog/migrations` to backup dirs
 5. run `./manage.py migrate posthog`
 6. checkout to latest again, move backup migrations back
 7. copy migration steps from step 5 to the squashed migration. Due to the dependency tree
     evaluation of the squash optimize not being able to collapse operations if they have other
     model migrations in between (?) I wanted to just start with an initial migration operation, 
     but with the addition of any ops that aren't registered as part of the django model state 
     management.
 9. remove any index _concurrently_ that already have a django tracked state. 
     We don't need to handle these cases by hand for initial installs, as we don't need 
     to use concurrently.

This takes migration time from 25s to 15s, but adds some annoyingness around migration tests. 
The larger time savings can be found with the ClickHouse migrations which take around 
a minute on my machine.

NOTE: we've added a few more migrations since this was last opened, but I'd rather get this in as is and leave further squashes as a separate task.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by hazzadous** [comment]
The savings don't seem worth it. Perhaps after bigger savings are exhausted elsewhere and we need some further savings we can revisit.

**Comment by neilkakkar** [comment]
Deploy makes this a lot more easier to review.

What's the issue with constraints in squashing?

**Comment by hazzadous** [comment]
> Deploy makes this a lot more easier to review.
> 
> What's the issue with constraints in squashing?

I believe the constraints naming is fixed. It's a pain to check properly. It _should_ be ok to merge, it _shouldn't_ do anything to existing deploys so pretty safe.

Should we.... sentit?

**Comment by hazzadous** [comment]
Oh and the issue is that the constraint names were different when I checked the `pg_dump --schema-only` when setting unique=true on initial model create and on AlterField. It 99% of the time probably wouldn't be an issue but I wanted to remove edge cases as much as possible.

I ended up splitting the operations as per https://github.com/PostHog/posthog/pull/13530/commits/8da2917baffb93c6eb5298418bbf501ef94ecbdd

**Comment by hazzadous** [comment]
Oh, but the plugin server tests! hmmmmmmmmmmm something non-deterministic in the tests :/

**Review by neilkakkar — COMMENTED** [review]
Pending the plugin server test, rest looks good to me!

**Review by neilkakkar — APPROVED** [review]

**Comment by hazzadous** [comment]
@neilkakkar it's deployed, all is fine.

There are likely a lot of optimisations that you could make with the squashed migration. The Django optimiser is on the cautious side mostly, but we can probably assume things that it doesn't know about to make it super fast.

**Comment by neilkakkar** [comment]
Shaves off 5 seconds for local dev, so that's a great start!

**Pull request merged**
