### PR TITLE
chore: remove merge persons option from persons page

### PR DESCRIPTION
**Pull request by tiina303**
## Problem

For https://github.com/PostHog/posthog/issues/11873

## Changes

Release: Merging persons in the UI is no longer available.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

Screenshot 2022-09-29 at 16 32 48
Screenshot 2022-09-29 at 16 32 52
Screenshot 2022-09-29 at 16 33 05
Screenshot 2022-09-29 at 16 33 21

### CODE REVIEW

**Comment by macobo** [comment]
Please also remove the associated backend code.

I'd also love for @yakkomajuri to be involved in reviewing this once he's back and better.

**Review by yakkomajuri — COMMENTED** [review]
Nothing else from my side beyond the fact that we should yeet the backend code too

**Review by macobo — APPROVED** [review]
Not sure why tests are failing, but lgtm. Thanks for handling!

**Comment by macobo** [comment]
Should this have a highlight tag + section in release notes? I recommend doing a mini writeup ahead of time.

**Pull request merged**
