### PR TITLE
Fix dashboard insight loader

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

It was broken because the action for it didn't exist

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by liyiy** [comment]
@samwinslow @paolodamico 😅 now that link should work... https://posthog-pr-4321.herokuapp.com/dashboard_insight/9

**Comment by samwinslow** [comment]
Cool! It works locally and is a good feature. However I think something may have gone wrong with the Heroku deploy, because I'm seeing a white screen and every network request on the page is hanging or resulting in a `5xx`.

**Comment by liyiy** [comment]
> Cool! It works locally and is a good feature. However I think something may have gone wrong with the Heroku deploy, because I'm seeing a white screen and every network request on the page is hanging or resulting in a `5xx`.

It just takes a couple of tries sometimes I think there's probably network delays, I clicked around and went to dashboards and then the specific dashboard insight page and it worked after a while (basically whenever the server could respond with the `dashboard_item` api request)

Screen Shot 2021-05-12 at 6 44 46 PM

**Review by samwinslow — APPROVED** [review]
LGTM. The issues on Heroku are so intermittent that I wonder if this particular query just runs slow in that environment. 🚢

**Pull request merged**
