### PR TITLE
feat(dashboards): declutter insight card

### PR DESCRIPTION
**Pull request by yakkomajuri**
Decluttering our insight card on dashboards so that more stuff can fit (like incoming sampling info). Based on @lharries suggestion [here](https://github.com/PostHog/posthog/pull/14488#discussion_r1123148162).

Main changes:

- Don't list the insight type - that should be clear from the graph already
- Don't show the user profile picture: too much information here
- Show the title above everything
- Show details & Hide details --> Details & Hide
- Last modified --> modified

Reasonably sure @Twixes will have strong opinions so tagging you as reviewer so I can close this quickly. Provided you don't immediately hate this, one thing I'd like your help with is the details button. If I keep `flex-start` it feels really out of place, but if I add it, it cuts off the button's shading on hover. Fixing this nicely is not something that comes naturally to me so I can spend a bunch of time on CSS or ask for help :D

| Before | After |
| :-----: | :----: |
|Screenshot 2023-03-08 at 11 32 01|Screenshot 2023-03-08 at 11 31 19|
|Screenshot 2023-03-08 at 11 32 06|Screenshot 2023-03-08 at 11 31 25|
|Screenshot 2023-03-08 at 11 32 21|Screenshot 2023-03-08 at 11 31 38|

### CODE REVIEW

**Comment by lharries** [comment]
Definitely looks nicer. However, when I use a long dashboard name it seems to bump the details and options button off to the side.

One potential fix is adding `overflow: hidden` to the <a ...>Insight title</a>. However we might want it to be multiline with line-clamp: 2

image

**Comment by Twixes** [comment]
I agree there are some superfluous elements on the insight card (like the insight type, "No description", or the profile picture), so happy to contribute to improving this. I have a few notes though:
- This change doesn't actually solve the problem of showing sampling, so it's hard to say how it helps _exactly_, and I'd prefer to avoid changing this core UI preemptively, without a concrete final state in mind.
- It feels weird to put heading-styled text (the date range) in the same row as caption-styled text ("Last modified"). Though I agree scannability is better with the insight name at the top, so perhaps we can think of some other layout where we still keep the top clear of distractions. As for "Last modified", I strongly think we should just put that next to "Created by" in details and reuse that pattern. Previously discussed it with Paul when this cropped up around text cards, but we didn't get around to implementing that.
- The gaps between the title, description, and extra metadata now differ (seems to be because of increased title-description distance).
- It also feels a bit weird that the details button in one state is a noun "Details" and in another a verb "Hide". At this point, it'd be better if it were always just "Details", and we can indicate its state with the icon. Or we can drop the label and keep just the icon. I suggest the latter.

**Comment by yakkomajuri** [comment]
Got the ball rolling on us thinking about this, but indeed while I decided to take a quick stab at it, I was reasonably sure I wasn't quite there, thus, closing this. I'm atm not the best person to lead efforts like this :D

**Comment by lharries** [comment]
@yakkomajuri / @Twixes I'd argue this is still better than what we have currently, any reason why we wouldn't merge it and then further iterate when we get to it later?

**Pull request closed without merging**
