### PR TITLE
chore: Updated favicons

### PR DESCRIPTION
**Pull request by corywatilo**
Our favicons were from another era. This bring them inline with our current styles.

image

It also replaces the dev icon:

image

There is also a crazy new dev icon (`favicon-dev-2.ico`) in case we want to get really weird:

image

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
I'm totally in favor of using our actual logo instead of this gradienty thing we have now. 😄 I'm not sure about the solid background however. It feels a bit unsettling how the PostHog icon's background is slightly but clearly off-white on a white backdrop.
Screenshot 2023-03-07 at 18 51 38
It also seems that the logo itself gets a bit lost when surrounded by the background – just from looking at my own tab bar, the transparency-based logos of Storybook, GitHub or Cloudflare are significantly more legible in terms of their details.
Screenshot 2023-03-07 at 18 55 09
Can we go for the same logo, but with a transparent background and less padding?

**Comment by corywatilo** [comment]
Do we have the ability to swap the logo when in dark mode? That's the main reason I added a background, otherwise the head becomes invisible.

But if we can swap them, that opens up the possibilities!

**Comment by Twixes** [comment]
Yup, we can have a different icon depending on `@media (prefers-color-scheme: dark)`.

**Review by Twixes — APPROVED** [review]
Let's get this in

**Pull request merged**
