### PR TITLE
Increase Element model varchar limits

### LINKED ISSUE #3913: Events with large HTML elements don't work in Postgres
Sentry Issue: [POSTHOG-2MC](https://sentry.io/organizations/posthog/issues/2325605024/?referrer=github_integration)

Looks like we can't process autocapture elements containing elements that have too large definitions, because the relevant field has a limit of 400 chars in Postgres (while having NO limit in ClickHouse, as CH varchars are unlimited). This affects all such events in Postgres PostHog and webhooks in ClickHouse PostHog.

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Model field change to support larger elements in Postgres PostHog and in ClickHouse webhooks (which do matching in Postgres). Resolves #3913.

### CODE REVIEW

**Review by paolodamico — APPROVED** [review]
lgtm!

I believe CharField & TextField have no significant differences with a Postgres backend, so just a nit, but maybe TextField would better reflect these attributes?

**Comment by macobo** [comment]
This operation WILL cause issues both in prod and for self-hosted.

ALTER TABLE on huge tables is insanely expensive since it needs to rewrite the whole table.

**Comment by Twixes** [comment]
@paolodamico
We could, but I think there _is_ a size we should not cooperate with, so I'd leave it some limit in. Ridiculously big elements could cause performance problems.

@macobo
This is not the case for this type of operation since Postgres 9.2 @macobo.
From https://www.postgresql.org/docs/9.2/release-9-2.html#AEN114949:
> Increasing the length limit for a varchar or varbit column, or removing the limit altogether, no longer requires a table rewrite.

**Comment by macobo** [comment]
You're correct - these should be instantaneous assuming no long-running queries holding locks block them.

```
posthog> select count(*) from posthog_element;
+----------+
| count    |
|----------|
| 26525865 |
+----------+
posthog> ALTER TABLE posthog_element ALTER COLUMN text TYPE VARCHAR(1000);
ALTER TABLE
Time: 0.166s
```

**Pull request merged**
