### PR TITLE
Funnels API GET -> POST|GET - Frontend + Clickhouse

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Reverting the revert in order to spin up a heroku review app... and test the difference locally vs deployed.

https://github.com/PostHog/posthog/pull/4769

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

**Comment by mariusandra** [comment]
Deployed a heroku review app and everything works ([link to funnels page in review app](https://posthog-pr-4789.herokuapp.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=false&display=FunnelViz&interval=day&actions=%5B%7B%22id%22%3A6%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Watched%20Movie%22%7D%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%7D%5D&new_entity=%5B%5D) - note, `plugin-server` is not running to save Redis).

image

Same locally. 

What is different on cloud that makes it fail? 🤔 

Whatever it is, it's not reaching Sentry either. Assuming funnels were down for half a day (underestimating), we should have many more errors:

image

Something in the infra layer?

**Comment by mariusandra** [comment]
A similar POST request to app.posthog.com returns:

```json
{"type":"invalid_request","code":"method_not_allowed","detail":"Method \"POST\" not allowed.","attr":null}                                                                                                                                                                                                                                             
```

**Comment by mariusandra** [comment]
The answer is quite obvious in hindsight: clickhouse insights uses a different viewset... that didn't have "POST" added to the funnels. 🤦 

I patched this and tested locally in EE mode. Everything works well.

And it turns out we were bitten by an old `TODO` from [this PR](https://github.com/PostHog/posthog/pull/1754).

image

Still some last testing to do and... 🤞

**Review by alexkim205 — APPROVED** [review]

**Comment by alexkim205** [comment]
Arghhh that's a good catch. I can't believe I didn't see that `is_clickhouse_enabled` check. Thanks for figuring this one out Marius. I feel like I can sleep easy knowing that it's not a larger deployment issue.

**Pull request merged**
