### PR TITLE
ci(GH actions): consolidate service usage

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Problem
In CI we have some tests relying on the service stack provided by docker compose while others are manual overriding those. As we can see from the fixes in this PR, this approach can create config drift between what's been tested and what's running (on our local workstation and/or in other environments).

## Changes
- unify docker compose steps
- remove the use of custom shell when not necessary
- remove use of custom service overrides when not needed
- make backend tests run on Python version `3.8.12` instead of `3.8.5` (bug) 

## How did you test this code?
* CI is 99% ✅. Not sure why the async migration check is failing but looks unrelated to my change (?). It's green on `master` tho.
* to make the benchmark action running I've added the label `performance` to this PR but it seems it does get skipped anyway

### CODE REVIEW

**Review by hazzadous — CHANGES_REQUESTED** [review]
I have no idea about the async migration test failure, could we get the other changes in and revert the ci-async changes?

The service changes seem the most useful anyhow

**Review by hazzadous — APPROVED** [review]
Looks like we need xmlsec for the benchmark as well. I guess that’s already broken though? So fine to get in if you like

**Comment by guidoiaquinti** [comment]
@macobo benchmark seems to be broken and looks unrelated to this PR. I've tried a couple of things but it is still broken and I have very little context about it. Are you 👍 if I merge this?

**Comment by guidoiaquinti** [comment]
Bias to action. I'm merging this

**Pull request merged**
