### PR TITLE
feat: only allow opening auth related tickets while logged out

### PR DESCRIPTION
**Pull request by MarconLP**
## Problem

users should open community questions or tickets on their paid accounts instead.
2024-04-09 at 01 17 58

### CODE REVIEW

**Comment by minekansu** [comment]
Can we add a login hyperlink in the warning text to make it easier?

**Comment by MarconLP** [comment]
> Can we add a login hyperlink in the warning text to make it easier?

This modal will only be shown while on the login page anyway. Like this (only works while not logged in): https://us.posthog.com/login?next=%2Fproject%2F2#panel=support%3Asupport%3A%3Alow

**Comment by corywatilo** [comment]
What's the context for this change and what does it solve? Is it to _only_ allow auth tickets when not logged in?

If so, a better way to handle this UX-wise would be to just hide the topic selector entirely, or make it read only so Auth is selected and you can't change it (with a tooltip explaining why you can't change it).

(Also 👀 at the [yolo merge](https://posthog.com/handbook/help#dont-yolo-merge)!)

**Comment by MarconLP** [comment]
> What's the context for this change and what does it solve?

We occasionally get non-auth tickets from logged-out users and have to respond with "Please open a ticket while logged in to your account".

> Is it to only allow auth tickets when not logged in?
> If so, a better way to handle this UX-wise would be to just hide the topic selector entirely, or make it read only so Auth is selected and you can't change it (with a tooltip explaining why you can't change it). 

Yes, will put up another PR tmr

**Pull request merged**
