### PR TITLE
feat(persons): Person feed

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

The person page has some practical value but it doesn't spark much joy or curiosity…

Before

## Changes

@corywatilo proposed we make the person page interesting as a hackathon project. I got on board. The new look's here!

After

The new default "Feed" tab shows the person's sessions (and out-of-session events), with metadata presented in a sidebar.

Wireframes: https://balsamiq.cloud/sd0i9zq/pl0wjty/rCCBB

## How did you test this code?

TBD

### CODE REVIEW

**Comment by corywatilo** [comment]
For context, here's the original wire:

**Comment by corywatilo** [comment]
How dare you @posthog-bot

**Comment by Semisol** [comment]
@posthog-bot why

**Comment by corywatilo** [comment]
Bad @posthog-bot

**Comment by Twixes** [comment]
Let's keep this closed, since it will be tough to prioritize this work in the near future with PostHog 3000 already scoped, but let's keep the branch, since the code (like the map) might come in useful when we get back to this. @corywatilo ;)

**Pull request closed without merging**
