### PR TITLE
Improve API routing

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Our API endpoints in this form: `/api/events` have confusingly been not working… the difference is just the lack of a trailing slash. That has been a longstanding issue, hard to diagnose for users and annoying when developing. This PR fixes that, ~~along with lacking support for personal API keys in `/decide`~~ (superseded by #1553), and also adds API-specific 404 handling (as to not confusingly 302 to the app login page when hitting a wrong endpoint).
Updated URLs in a few tests to make this covered by tests.

## Checklist

- [x] Backend tests (if this PR affects the backend)

### CODE REVIEW

**Comment by yakkomajuri** [comment]
@Twixes maybe take a look at #1553 to see the approach you'd wanna have to the /decide endpoint since I set up the same authentication mechanism on /decide as /capture

**Comment by yakkomajuri** [comment]
@Twixes when you get a chance take a look at the conflicts and then I could pick up the review on this, unless there's any objection to that

**Review by yakkomajuri — APPROVED** [review]
This looks good to me. I made some changes to also make the internal use endpoints flexible, as well as made sure the tests were testing endpoints both with and without a trailing slash. Added comments so that people can make sense of the "inconsistency". 

I made changes regarding endpoints that weren't in the scope of this PR but that I thought made sense. @Twixes see if the changes make sense and otherwise this should be good to go.

**Comment by Twixes** [comment]
Makes sense. 👍

**Comment by Twixes** [comment]
Will have to take a look at these Cypress tests finally… But this should be OK for the moment.

**Comment by yakkomajuri** [comment]
Yeah I was thinking of doing that and then we got the debug bar PR merged, all new PRs pass, but old PRs that get merged with master don't?

**Pull request merged**
