### PR TITLE
Swap out old paths querying class with new

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- wait on #5820 
- swaps out old path query class with new
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
LGTM! Also deleted old paths file so if something burns now, we know the swapping is incomplete 😅

**Review by neilkakkar — DISMISSED** [review]
Oh actually, `update_cache` is borked right now, since the signature is different:

https://github.com/PostHog/posthog/blob/swap-clickhousepaths/posthog/tasks/update_cache.py#L164

Annoying. I'm tempted to actually move Paths back to the old format (and maybe Funnels at a later stage too) - so that everything has the same signature. Thoughts?

Edit: Nope, not tempted to move back anymore. Realised we have other public functions now (like `get_query`, `get_step_count_query`) which depend on filter and team, so just adjusting update cache

**Comment by neilkakkar** [comment]
I tried writing a proper test for this, but it turned out to be very messy.

1. Can't write it in `test_update_cache` since it's an EE test, and imports have already occurred at this point, so test becomes a false positive
2. Creating a new test in EE, the Paths class returns `[]` (with no data), in which case it's not cached. So here I could add more data in, or mock the class return value, but mocking defeats the purpose of checking the class initialisation works. Ugh.

**Comment by neilkakkar** [comment]
Apart from this:

1. ~~I think we also need to send the source_element, target_element stuff? As that's used for the `elements` end point, and would break current UI if we switch to this?~~
2.  ~~Current UI depends on `target_event` to decide whether to show SCREENS, PAGEVIEW, etc. This will break with our new querying class right now?~~

**Comment by EDsCODE** [comment]
> Apart from this:
> 
> 1. I think we also need to send the source_element, target_element stuff? As that's used for the `elements` end point, and would break current UI if we switch to this?
> 2. Current UI depends on `target_event` to decide whether to show SCREENS, PAGEVIEW, etc. This will break with our new querying class right now?

Yeah, I was thinking maybe we make some UI adjustments in this PR so that the merge works as expected

**Pull request merged**
