### PR TITLE
Reset insight if opening new insight

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Final TODO before saved insights could be released to the world.
- Previously when you had an insight open, and then clicked "new insight", nothing would happen. 
- This was made worse with Turbo Mode, where you can have a saved insight open, click back to a random page, click "new insight", and still see that previously open insight, but with some bugs.

## How did you test this code?

- Tried in the browser and made some tests

### CODE REVIEW

**Comment by mariusandra** [comment]
This is getting too complicated. Going to fix the `/insight/123` routes first.

**Comment by mariusandra** [comment]
@Twixes this is the last TODO before saved insights could go out on cloud. This fixes the same thing in the non-saved-insights interface as well.

**Comment by mariusandra** [comment]
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` for `jest test`, also locally. That can't be good 🤔

**Comment by Twixes** [comment]
Has been solved in a different PR.

**Pull request closed without merging**
