### PR TITLE
feat(insights): actor breakdown

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

The current actors modal lets you choose between the different breakdown options. The HogQL version doesn't.

## Changes

Introduces `InsightActorsQueryOptions` (I know, it's a mouthful), which wraps `InsightActorsQuery` and returns the values you can use when making the query. 

Behind the scenes, this is just delegated to `LifecycleQuery`, which knows what options to present.

## How did you test this code?

See screencast.

### CODE REVIEW

**Comment by mariusandra** [comment]
Putting this out for feedback. I'm not sure if this should be a "runner", or just a few functions that get called like the `HogQLMetadata` node. Thoughts? Also, will something like this work/help with trends, retention, etc?

**Comment by Gilbert09** [comment]
Excellent timing, I was _just_ about to look at the trends breakdowns next. A few comments below (inc 1 blocking bug). Overall, I like this approach, but I do feel like we have a bunch of runners that do something slightly different from each other - plus, we're making multiple queries to get very related data back into the client (people + the status/dates) - sure this isn't hitting the DB in the world of lifecycle, but it very much will be hitting the same data in Trends. That being said, this does simplify the trends breakdown implementation (which is v nice)

#### UX
I'm unsure of how I feel about having the date selector in the modal. I want to see the charts before making a choice of which day to look at next. But I'm also not super clear of the typical use case of viewing the persons modal.

#### Bugs / improvements 
- Looks like the date in the modal gets reverted when both the date and status get changed (see vid below)
- Also, would be nice for the title of the modal to update as you change the date

https://github.com/PostHog/posthog/assets/1459269/11746402-870f-4374-b903-ba18386c67a3

**Comment by mariusandra** [comment]
Yeah... I was wondering if I should return the data in a new query, or if perhaps `InsightActorsQuery` itself could return `options: Record<field, {label,value}[]>`, and hence save an extra breakdown values query. In the end, I just did the simplest thing possible, as I wanted the breakdowns to show up as quickly as possible. 

Regarding the dates in the modal... dunno 🤷. Some people might find them nice, some might not use them. I added them as it was now easy to add. We could also show the same select fields when you click "explore" to dig deeper. Perhaps a date will be good then, not sure.

**Comment by mariusandra** [comment]
I hope I fixed the bug with the select fields flapping. 

Regarding the title, I'd ideally do it in another PR. It's currently passed in a very weird way from the component that opens the modal:

image

Instead of this, the model should calculate it's title from the query. This however feels like another chunky PR, so let's get this merged first? 🤞

**Review by Gilbert09 — APPROVED** [review]

**Pull request merged**
