### PR TITLE
feat: Notebook queries node

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Follow up from https://github.com/PostHog/posthog/issues/15680

@mariusandra and @Twixes tagged as this touches some of your stuff so just wanted you to be aware

## Changes

* Notebooks are sorted by created_at desc
* Hedgehog key commands don't trigger if focused on the Notebook
* Styles DataTable to fit nicely to the bounds of the view
* Adds a floating button to add Persons, HogQL, DataTable or Playlist
* Allows resizing widgets
* Fixed new notebook method so it always opens in the sidebar if open already.

## TODO
- [x] Might have broken styles on safari according to the snapshots...
- [x] Fix new notebook - should open in sidebar if open, otherwise as its own notebook

**Playlist / events**

**HogQL**

## Side effects

LemonTable has a footer now and the buttons for DataTables are in there (fits much better in a Notebook).
Also the header has position sticky so that if it is fitting the bounds of its parent, it sticks to the top.

Screenshot 2023-06-15 at 09 52 54

## In follow up PR
- [ ] Fix issue with the Query not changing controls when selecting

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
Screenshot 2023-06-15 at 12 28 23

LGTM

Clicked around things seem to work. I can add things to notebooks without using the mouse 🥇

**Review by Twixes — COMMENTED** [review]
The "Load more" change is great, makes a lot of sense. Just one thing I noticed is that when the table has horizontal scroll, the footer doesn't take up the full width.
From an API point of view, maybe we can make this a `loadMore` handler instead of a free-form `footer`? In that case we'd handle the `fullWidth` or `center` type of styling for you

Screenshot 2023-06-16 at 12 45 11

**Comment by benjackwhite** [comment]
> The "Load more" change is great, makes a lot of sense. Just one thing I noticed is that when the table has horizontal scroll, the footer doesn't take up the full width.
> 
> From an API point of view, maybe we can make this a `loadMore` handler instead of a free-form `footer`? In that case we'd handle the `fullWidth` or `center` type of styling for you
> 
> 
> 
> Screenshot 2023-06-16 at 12 45 11
> 
> 

That's a great idea yeah. In my head I thought there might be other use cases I'm not thinking about but then we can handle them when they happen. 

I won't do it yet, but it could be an option for infinite loading as well...

**Comment by benjackwhite** [comment]
@Twixes I'm going to follow up with another PR to make the table changes as its a little more involved...

**Comment by Twixes** [comment]
Just a ping to follow-up on these @benjackwhite ;) Particularly the "Load more" button width fix, since it affects production UI

**Pull request merged**
