### PR TITLE
Add regex matching to actions and filters (closes #1150)

### LINKED ISSUE #1150: Add basic REGEX support for Page view / contains actions
For Page view actions, it would be greate if we could use contains and check the string is at the end of the string? 

Something like: `website.com/admin/%/page$`? 

And that would match:
- `website.com/admin/%/page/` 
- `website.com/admin/%/page` 

But not match 
- `website.com/admin/%/page/sub-page` 
- `website.com/admin/%/page/sub-page/123`

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Per feature request (#1150), this adds regex matching.

Trends
Action

## Checklist

- [x] All querysets/queries filter by Team (if applicable)
- [x] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Review by timgl — COMMENTED** [review]
This looks awesome! It's missing some tests (backend and maybe cypress)? Will QA too

**Comment by Twixes** [comment]
Yep, definitely deserves tests, I'm adding them right after the standup.

**Review by EDsCODE — APPROVED** [review]
lgtm!

Nit for better ux: test the regex before sending request. If you submit a bad regex it just has a general response error that isn't explained well by our default error toast

**Comment by Twixes** [comment]
There's a problem with client-side validation here: Postgres has its own regex syntax, which differs from that of JavaScript or even Python. I think it'd be safest to just have the server return a sensible error message in case of a bad regex.

**Comment by EDsCODE** [comment]
@Twixes feel free to merge if ready!

**Pull request merged**
