### PR TITLE
WIP: Have the element info-window follow the mouse

### LINKED ISSUE #1372: Not obvious you can "pin" toolbar infowindows
## Bug description

When hovering over a page with lots of elements, unless someone tells you, it's not inherently obvious you can click on any of the elements to "pin" the infowindow to the screen. 

## Expected behavior

Somehow this should be more obvious.

One idea is that the infowindow is normally not pegged to the bottom/top of the heatmap element, but is always floating right under the mouse cursor (while you hover the element).

This would make the page feel smoother and less flashy... and it would probably make the click more obvious. Maybe.

## Additional context

This came out in a toolbar feedback session with a customer

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Here's a proposal to fix #1372 

- Before:

- After:

Please send feedback if this approach makes sense or not. It's still WIP.

Todo:
- Refactor `InfoWindow.tsx` by moving a lot of the calculation there into a logic (many selectors...)
- Make it work better on narrow screens (move the window to the right/left of the mouse if it doesn't fit and make it full height)
- Test how it all works on mobile

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by Twixes** [comment]
I think this is a good idea!

**Comment by Twixes** [comment]
Maybe add a "Click element to lock window in place" note inside the window.

**Comment by mariusandra** [comment]
Hi, this was a WIP still. The windows didn't work right with a small screen and I had not tested anything on devices without a mouse.

**Comment by timgl** [comment]
Oops, I'll revert

**Pull request merged**
