### PR TITLE
Clean up person profile picture

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Based on https://github.com/PostHog/posthog/pull/7514#issuecomment-986940573 (let me know if this is what you had in mind – PRs over issues), this restores the person icon
Screen Shot 2021-12-06 at 19 15 37
in place of the "profile picture" introduced in #7514
Screen Shot 2021-12-06 at 19 19 28
until we figure out a distinct avatar style for persons, that would separate them from users of PostHog itself. My reasoning is that an avatar more unique than the person icon is a great idea, but it should be different from the way _team members_ are represented.

### CODE REVIEW

**Review by clarkus — CHANGES_REQUESTED** [review]
I was using lettermarks in the designs, but I can see how that isn't super valuable. I'm fine using person icons here - can we reuse the same icon from the left navigation?

**Review by paolodamico — CHANGES_REQUESTED** [review]
I maintain the original position that @clarkus and I talked about, on using the profile picture component. One option to distinguish from users is using a different color. Alternatively we could use the squared versions that we only use for orgs (as we'd likely want to support custom logos in the future anyways).

As this is very subjective, I'll defer to @clarkus or you, but personally I'm strongly in favor of not using the icon.

**Comment by Twixes** [comment]
Alright :+1: @paolodamico Let's use something more unique than the Material Design person icon, but will move sorting out the way to distinguish the person icon to Figma ([artboard](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5248%3A28954))

**Comment by Twixes** [comment]
So I ended up reverting the revert. Only improved the margins basically, so I'll merge this.
Screenshot 2021-12-13 at 15 29 20

**Pull request merged**
