### PR TITLE
feat: New loading spinner

### LINKED ISSUE #11290: Update loading spinner for app
## Our current spinner doesn't align with the company aesthetic that much 

Currently we have a [two tone blue circular spinner](https://storybook.posthog.net/?path=/docs/lemon-ui-spinner--default) for the majority of small loading states within the app. While we could leave this, I believe that it is clunky and takes away from the overall branding of the app. We want to convey a strong and trustworthy front with our app and that includes spinners! 

Screenshot 2022-08-04 at 11 23 1

## Describe the solution you'd like

Introducing [the new spinner ](https://lottiefiles.com/share/hlkairn3)(hold for applause) yay!

animation_500_l6eutak1 1

Inspired by the product this new spinner includes the company logo colors, alongside hinting to the insight points held on our trend graphs. It spins while also including a soft bounce motion to portray a friendly and calm loading state. This loader is exported via lottiefiles so it is super small and efficient. 

### Examples of use cases:

Frame 9210

Frame 9864

## Describe alternatives you've considered

Loaders I experimented with:
- a circle of blue multi tonal dots that changed in opacity- while this was a fresher approach to the blue spinner we had, it still felt far removed from the brand.
-  a thinner stroke spinner- this was going to be an issue for visibility purposes so lost the race pretty early on.
- feature flag inspired buttons, these would swap and change and flip. I really liked this iteration to be honest but it was too complicated for small periods of loading (which is the aim) and therefore would just be a jumble of movement with not that much relation to loading. 
- a worm-like loader - the name explains why we didn't go for this one. 

Group 9101

## Additional context

Complicated loader - https://lottiefiles.com/share/4xba6avz
Worm loader - https://lottiefiles.com/share/ctqkkm1o
Figma file - https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=4934%3A29109

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Closes https://github.com/PostHog/posthog/issues/11290

## Changes

* Adds the new spinner

Screenshot 2022-08-22 at 11 20 00
Screenshot 2022-08-22 at 11 20 30

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## TODO
* What do with switch spinner...

FYI @lottiecoxon

### CODE REVIEW

**Comment by lottiecoxon** [comment]
Would it be worth adding an additional alt-loader for blue or coloured backgrounds? (I was thinking white dots instead of colored ones?)

Also would it be worth having a call/chat about how CSS animations work so we could design more efficiently with the preferred software? lmk

**Comment by lottiecoxon** [comment]
Would it be worth adding an additional alt-loader for blue or coloured backgrounds? (I was thinking white dots instead of colored ones?)

Also would it be worth having a call/chat about how CSS animations work so we could design more efficiently with the preferred software? lmk

**Comment by lottiecoxon** [comment]
Commenting as unsure - is this sorted or do we need to work out switch spinner? - also what is switch spinner ?

**Comment by benjackwhite** [comment]
> Commenting as unsure - is this sorted or do we need to work out switch spinner? - also what is switch spinner ?

[This](https://61260360a8e859003a7c138b-jtesrxsulb.chromatic.com/?path=/docs/lemon-ui-lemon-switch--loading) is the Spinner in the Switch. I noticed it as I was clicking about. Seems we used the old spinner within the handle for a loading state. Looks a bit off with the new spinner...

**Comment by clarkus** [comment]
Switches are meant to be immediate and don't typically have loading states. I think it's probably fair to drop that from consideration. Thoughts?

**Comment by clarkus** [comment]
For the non-primary states, should we use the full color loader? The main issue with the primary states is that the primary and destructive palette options are also used in the spinner which results in poor contrast.

**Comment by benjackwhite** [comment]
> For the non-primary states, should we use the full color loader? The main issue with the primary states is that the primary and destructive palette options are also used in the spinner which results in poor contrast.

I did have it as the full color one at first and to my eye it still looked a little jarring, especially for the non-primary colors like "danger". 
That said I can't think of a place where we aren't using the "primary" button with the loading state as it is almost always tied to doing something. Might never even show in the actual usage 😅 

Agree that we can get rid of the loading state for switches 👍. It isn't used that often and probably should have a different pattern anyways

**Comment by lottiecoxon** [comment]
if the switch is loading why not incorporate the skeleton loader style instead of the spinner?
Agreed the spinner looks uber weird inside the switch , but if it is a part of the skeleton loader style we can still convey that it is loading. I have done some work on [custom skeleton loaders here.](https://github.com/PostHog/posthog/issues/11294)

**Comment by benjackwhite** [comment]
@lottiecoxon the loading style for the switch is more like "I am performing the action you asked for" than "I am waiting to be ready" so a Skeleton state wouldn't be applicable here.

In reality all the use cases we have are in project / org settings for turning off or on certain functions so its edge-casey enough that I think we can live without it

**Review by mariusandra — APPROVED** [review]
Good for me!

As a follow up to removing the spinner in the switch, do we need to add buttons here:

Screenshot 2022-08-23 at 12 21 33

I'd personally hit CMD+R just to be sure it's really saved, if I toggle something and miss the notification.

**Comment by benjackwhite** [comment]
Personally I don't think it needs anything more. Those values update so quick that you almost didn't see the spinner anyways

**Comment by mariusandra** [comment]
Not if you're using 4G in an elevator 🙃

**Comment by clarkus** [comment]
> Good for me!
> 
> As a follow up to removing the spinner in the switch, do we need to add buttons here:
> 
> Screenshot 2022-08-23 at 12 21 33
> 
> I'd personally hit CMD+R just to be sure it's really saved, if I toggle something and miss the notification.

Don't think we need buttons here. If there is a submit action, then we should be using checkboxes, not switches. Switches are meant to apply immediately without any secondary action to submit. If we want to reinforce that the changes were applied, showing a toast notification to confirm the change would be a better experience.

**Pull request merged**
