### PR TITLE
feat(hogql): add poe v2 support 

### PR DESCRIPTION
**Pull request by yakkomajuri**
Just putting this up as I've been spending a good amount of time on it (and have other things to do) while I feel it might be a quick thing for @mariusandra.

Essentially, seems most of the PoE v2 stuff is in place here, but I need the person_id field in PoE v2 to be an alias to `if(notEmpty(...), ...)` seems I'd need to edit the printer to do this? Could probably figure out a way but wondering what the suggested approach here would be

### CODE REVIEW

**Comment by yakkomajuri** [comment]
@mariusandra any thoughts?

**Comment by mariusandra** [comment]
It took a few stacked PRs of [refactors](https://github.com/PostHog/posthog/pull/15165), but I got a more or less clean version of [custom sql fields](https://github.com/PostHog/posthog/pull/15180) ready. It's still a draft and I'm actively watering its [prerequisite](https://github.com/PostHog/posthog/pull/15175). So soon, soon.

However you can rebase and play with it. It should fit into the PoEv2 system nicely, though I didn't try it yet myself.

**Comment by mariusandra** [comment]
Not stale. Will get back on it next week.

**Comment by mariusandra** [comment]
@yakkomajuri let's split the PoE work at HogQL into two parts:

1. Joining the new person_id onto events as `override_person_id`, similar to `person_id` and other things are joined now
2. Actually having a seamless experience with a hidden `if()` when selecting `person.properties` https://github.com/PostHog/posthog/pull/15180

I merged with master and started to cleaning up the person_overrides table you added here, only to realise we have 4 identical tables we select from with argmax joins. Thus it was time for a common solution (and one more step towards becoming an ORM 😅).

This PR now adds:
- `events.override.*` as a link to the last person_overrides table row for that distinct_id
- `events.override_person_id` as a shorthand to access the new person_id
- A new specific error "Can't select a table when a column is expected" to spark just a tiny bit more joy

If you find this all a-OK and the tests pass, I'll happily ✅ and 🚢 🇮🇹

**Comment by mariusandra** [comment]
I'd like to test PoEv2 locally. Are there any specific flags I can enable and things I can do to get any data to come in to the person_overrides table? I was flying blind until now :)

**Review by mariusandra — APPROVED** [review]

**Comment by mariusandra** [comment]
I merged this PR in (despite my own many changes), as it is just step 1 in poev2 support that adds a table we can query in step 2. Plus it improves some errors I just saw in #sentry.

**Pull request merged**
