### PR TITLE
Fix funnel navigation step-merge

### LINKED ISSUE #4519: When navigate away and back to certain funnels - the funnel breaks
## Bug description

Saved funnels don't seem to be working as expected.

https://www.loom.com/share/cbf26a3f5288408f8032fdec2e719a73

Password is available in papercups conversation:
https://app.papercups.io/conversations/all?cid=084051e1-fd3f-4997-8951-ea7baf298cb2

Or reach out to me for it.

## Expected behavior

The funnel to be in the same state as you left it.

## How to reproduce

From the Loom recording:
1) Create two stage funnel and save it.
2) Navigate away from funnel tab
3) Navigate back
4) Observe a broken 3 stage funnel

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

From Papercups user

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Fixes https://github.com/PostHog/posthog/issues/4519
- Explicitly overrides filters for funnels when the filter change comes from the URL.
- Previously we merged them all the time. This resulted in a case where the URL contained just actions, yet an event was in the existing filter. They got merged leading to weirdness.
- We have been talking about improving navigation within insights (e.g. directly see a funnel from the lines on trends, etc), but that's outside the scope of this task.

The bug was this:

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

**Comment by mariusandra** [comment]
Broken cypress test is related to funnels. 🤔

**Review by paolodamico — APPROVED** [review]
💪 this seems to solve the problem!

**Comment by paolodamico** [comment]
There was indeed a bug that the test caught. Previously we would automatically start the funnel with a single Pageview step to provide a better experience. Because we were no longer passing the params from trends, the funnel started empty by default. Pushed a fix for this, take a look before merging @mariusandra

**Review by alexkim205 — APPROVED** [review]

**Comment by mariusandra** [comment]
These are frontend changes, so counting the backend cloud test as a flake.

**Pull request merged**
