### PR TITLE
Update antd and dayjs to latest

### PR DESCRIPTION
**Pull request by macobo**
## Changes

Some new functionality was required for FF work

See https://ant.design/changelog for full details. This update should not have any breaking changes.

## How did you test this code?

Clicking through the app for 3 minutes, verified no ts errors.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]

**Review by mariusandra — CHANGES_REQUESTED** [review]
Checkmarked too soon. Seems like there are some TS errors...

**Comment by macobo** [comment]
Hmm, managed to cause this error clicking around a bit w/ date pickers. 

image

:calendar: :disappointed:

**Comment by macobo** [comment]
Seems like the issue was we ended up having two versions of dayjs in use. This is now fixed \o/

**Review by mariusandra — APPROVED** [review]
LGTM

**Pull request merged**
