### PR TITLE
WIP Remove hotlinked images

### PR DESCRIPTION
**Pull request by jamesefhawkins**
## Changes

- Removed any references to images that were in the wp-content folder

When the DNS for posthog.com is switched, this means whilst I can 301 in the previous images with their full URLs so this works for non-upgraded users, we can at least hotlink directly to the right places for future installs. 

The next step is to then switch all of these out for the new logo.

WIP since we should not merge this until the DNS is changed.

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
Except for the readme and app.json it'd probably be better if these were included in the app itself I think?

**Comment by jamesefhawkins** [comment]
Yes - that approach means it would work offline properly

**Comment by timgl** [comment]
@jamesefhawkins bumperoony - i need this for something else

**Comment by timgl** [comment]
These pictures all still work so I assume this is fine. Feel free to reopen if not

**Pull request closed without merging**
