### PR TITLE
Remove Toolbar Dock Mode

### LINKED ISSUE #1551: Get rid of "dock" mode in toolbar
## Is your feature request related to a problem?

Dock mode is mostly redundant and is going to be a huge head-ache to maintain.

## Describe the solution you'd like

Remove dock mode

## Additional context

@mariusandra (once you're back!) i think we already discussed this though I couldn't find a ticket. It came up again with a user who's app didn't work at all when opening dock mode.

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Removes the toolbar dock more, with it a lot of broken code
- Replace the "dock" button with a "help" button that opens the toolbar tutorial
- Fixes #1551

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by mariusandra** [comment]
Ready for a look.

**Review by Twixes — COMMENTED** [review]
A few tiny things:
- `toolbar_model` should be removed all over the place I think (unless there's another Toolbar mode planned
?).
- It's not actually a bar at all anymore. 🤔 Idea: rebrand this to PostHog Floaty Website Thing. Or something like that.
- The help button feels out of place for some reason.
    Screen Shot 2020-09-29 at 01 17 14
    IMO, the question mark icon seems thin and the button's corners seem not rounded enough.

**Comment by mariusandra** [comment]
1. I guess you mean `toolbar_mode` (without the `l`)? If so, this is a field that switches between the old `editor` toolbar and the new (beta opt-in) `toolbar`... and not between the "button" and "dock" modes. We should probably remove the entire old editor code, then I can remove this field and the related code as well. But that's outside the scope of this PR.

2. Yeah, I've been having a hard time calling it a "toolbar" as well at times. Though I don't know what's a better name.

3. I made it round and blue. It's a "bit" better I think, though I'm totally open to suggestions. 

image

**Comment by Twixes** [comment]
I brought back gray and made rounding more similar across all the floaty elements. I think it looks OK, but the call is yours, merge in with whatever styling you think is best!

Screen Shot 2020-09-29 at 10 23 10

**Comment by mariusandra** [comment]
Good enough!

**Pull request merged**
