### PR TITLE
Proposal: Disable eslint warnings

### PR DESCRIPTION
**Pull request by macobo**
We don't really follow no-shadow warnings, but they pollute every PR review with
unchanged lines showing warnings.

I propose we disable these warnings (or make them an error).

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by mariusandra** [comment]
Or convert them to errors instead and fix them in one go?

This rule was added because there were legit bugs with shadowed vars that caused some things to not work.

**Comment by macobo** [comment]
> Or convert them to errors instead and fix them in one go?

It's a non-trivial fix in 45 files which will cause merge conflicts and/or bugs if I get the scoping wrong during renaming. But ok, will try.

**Comment by macobo** [comment]
Did the update. ~95% sure no new error was introduced here.

I do think this was not worth the effort:
- There are false-positives: https://github.com/PostHog/posthog/pull/3475/commits/c77e865c3718e50987749827e72526922440e0f6#diff-29158f70214e1b52070a0066a00e089b573ece481fb628dae4bca81848c433bfL48-L50
- It makes code actively worse in a lot of places (e.g. onChange functions in react components) where the overridden name is correct: https://github.com/PostHog/posthog/pull/3475/commits/c77e865c3718e50987749827e72526922440e0f6#diff-3f502e1b06f5c051c529031ab8cf8122820699d683c0c6c226fd90352746e478L23 https://github.com/PostHog/posthog/pull/3475/commits/c77e865c3718e50987749827e72526922440e0f6#diff-362e941677926eb428f4963335f4bf0e60a485ed7d80cda9d0ef6bfbcc95370aL61-L144 or where destructing could be used: https://github.com/PostHog/posthog/pull/3475/commits/c77e865c3718e50987749827e72526922440e0f6#diff-6bde4fe1c8dcd0772b146caeb5fa1b5988dedd4973fb84430626f192dd16f2c4L36-L37
- This will cause further merge conflicts
- Saw no actual errors caught by this check

**Comment by mariusandra** [comment]
I'm absolutely in favor of disabling all eslint rules that do not help catch errors. This one however would have caught the `color` variable [being wrong here](https://github.com/PostHog/posthog/commit/10313299860edfb1dcca6aab961db37a277d47c0#diff-7ecdd311cea9fedb6b0c0ddd704ed418601040118cc2fd1fa0a74b6192323aafR120), which messed up dashboard colors for at least a release or two. Not a critical error by any means, but still something that caused extra work down the line. I think there was one more case, but can't find it now.

> Saw no actual errors caught by this check

... because they were fixed already before :). Just the "no obvious errors, only warnings here" lines weren't touched.

I'm also not in favour of the `type_` naming convention. I've used the `type` <-> `innerType` convention before to make the separation of inner loop variables obvious... or then something more explicit like `newValue` or `changedValue` or ...

Anyway, if you do feel strongly about it, like it seems that you do, feel free to revert and remove the rule.

**Comment by macobo** [comment]
Thanks for the context!

I'd say this is a "perfect being the enemy of the good" situation: we're feeling a pain day-to-day (noisy pull requests). The goal of this PR was to get rid of this issue in a straight-forward way. When opening the PR up I was not aware of the context laid out above - I just saw the noise in PRs being ignored 100% of the times.

The perfect solution (obviously) is fixing everything. However it comes with the downsides mentioned above, as well as:
- I did manage to introduce at least one bug here, which the CI caught
- We're spending a ton of effort in fixing this - both for doing the refactor, discussions on what variable names to use, future merge conflicts this will cause (I have at least 1 branch in conflict).

This feels like a bad approach - I've already spent more effort here than I feel this issue deserves.

Is there a middle ground? If we want to keep the rule, then the lazy thing is to instead // eslint-disable-line all of the current errors/files for this error.

**Review by mariusandra — APPROVED** [review]
There are two more errors that eslint says are not fixed. Other than that it LGTM.

**Comment by Twixes** [comment]
This got quite out of sync with master it seems. Do we want to work on merging this or close? @macobo

**Comment by mariusandra** [comment]
Probably best to do in a new PR. Looking at the errors in an unrelated PR there are just 10 no shadow warnings left to fix.

**Comment by Twixes** [comment]
Closing this one then

**Pull request closed without merging**
