### PR TITLE
fix(taxonomy): don't convert numeric strings to numbers

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

If you send us a property that's a string, but contains a numeric value, e.g. `"0"` or `"0.1"`, we convert this property's data type to `numeric` for you. 

## Changes

Stops that nonsense. It's causing plenty of support requests and internal turmoil. 

## How did you test this code?

CI

### CODE REVIEW

**Review by marandaneto — APPROVED** [review]
LGTM

**Review by Twixes — APPROVED** [review]

**Comment by pauldambra** [comment]
I look forward to the support requests in the other direction 🤣

**Comment by marandaneto** [comment]
@mariusandra 

> Test Suites: 1 failed, 23 passed, 24 total
> Tests:       5 failed, 1 skipped, 322 passed, 328 total

You need more 5 minutes of your life 🗡️

**Comment by marandaneto** [comment]
still failing some tests:

> Test Suites: 1 failed, 23 passed, 24 total
> Tests:       5 failed, 1 skipped, 322 passed, 328 total

**Comment by mariusandra** [comment]
I'm aware... 😅 
Just finished my support week, will water all the plants now.

**Comment by marandaneto** [comment]
Screenshot 2024-01-25 at 11 28 03

@mariusandra there are still some warnings, but it did fix some as well.

**Pull request merged**
