### PR TITLE
Spinner UI

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Initial pass at the new loading spinner. Starts using it in some places (not everywhere just yet).

**Spinner component**
image

**In the wild**

## How did you test this code?
- Manually set states as loading in all places where the Ant component was being replaced.

### CODE REVIEW

**Comment by paolodamico** [comment]
Now used across the entire app.
image

**Review by clarkus — APPROVED** [review]
These changes look good to me. I do think we need a broader review of loading states in the product, just to ensure that we're using skeleton states where appropriate. Nitpick, but the ends of the animated portion are rounded in the designs, but not critical for this.

**Comment by paolodamico** [comment]
Yup I noticed, but I wasn't able to replicate it, perhaps @Twixes has some magic here he can help us with? Will merge and you know how to improve that we can do it in a follow-up PR.

**Comment by Twixes** [comment]
Here's an updated version with some SVG magic:
@paolodamico @clarkus

**Comment by paolodamico** [comment]
Amazing @Twixes, thanks!

**Pull request merged**
