### PR TITLE
fix: removing session replay button from feature flag create page

### PR DESCRIPTION
**Pull request by surbhi-posthog**
## Problem

Removing the "View Session Replays" button from the Create Feature Flag page.

I found this PR referencing when the feature was originally added: https://github.com/PostHog/posthog/pull/26072/files. There’s some logic around payload added in that PR, but it doesn’t seem related to the recording button. Let me know if I’m overlooking anything.

## Changes

| Before | After |
|--------|-------|
| Before Image | After Image |

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud

## How did you test this code?

tested locally on: http://localhost:8000/project/2/feature_flags/new

### CODE REVIEW

**Review by zlwaterfield — CHANGES_REQUESTED** [review]
We still do want the button to exist, we should don't want it to show when / creating or editing the flag. More context in screen share here: https://posthog.slack.com/archives/C043VJ93L3B/p1732316635183779?thread_ts=1732308736.312529&cid=C043VJ93L3B

**Comment by raquelmsmith** [comment]
Oh, this is not what we want 😅 

Right now the button shows up when someone goes to edit the flag if it's a boolean type flag. We don't want it to show up on edit. It's just a conditional somewhere.

**Comment by surbhi-posthog** [comment]
oooh, ok. Will revert. Thanks for the feedback

**Comment by surbhi-posthog** [comment]
starting a new branch here and closing this PR https://github.com/PostHog/posthog/pull/26407

**Comment by surbhi-posthog** [comment]
I noticed that the View recordings button shows up in two different places in this code base: https://github.com/PostHog/posthog/blob/afb491bd1b88aed6ed34ce6630229496d2ca3a4d/frontend/src/scenes/feature-flags/FeatureFlag.tsx#L887. 

Does it make sense to consolidate the logic? @zackelan @raquelmsmith

**Pull request closed without merging**
