### PR TITLE
Add individual user filter #1289

### PR DESCRIPTION
**Pull request by chrysillala**
## Changes

Add individual user filter #1289
add-user-filter

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Hey @chrysillala! Thanks for this!

However, I don't think this is what Tim was referring to in the issue. I'm quite sure the idea is to search for specific users, not their properties. User properties are already part of properties, so that's covered. The idea is that I can pass a user's distinct ID, or a list of IDs, and get the actions from those users only.

From the original issue:

"In the PropertyFilter I want to have a third option (next to Property and Cohort) that allows you to search a list of users."
...
"I could look up the distinct ID or email address for example"

Email addresses can already be done with properties, so maybe that was slightly confusing. But maybe a good way to look at this is distinct IDs first - can we build a filter by Distinct ID? Then, it would be a matter of expanding that filter to allow multiple distinct IDs in a list. Emails can also be used as user IDs, so that should be doable in the same context.

**Comment by yakkomajuri** [comment]
Do let me know if you need any help though!

**Review by yakkomajuri — CHANGES_REQUESTED** [review]
The approach should be changed to filtering by user IDs rather than user properties.

**Comment by chrysillala** [comment]
Hi @yakkomajuri , thank you for your feedback and instructions. Let me check and will get back to you soon.

**Comment by yakkomajuri** [comment]
Hey @chrysillala! I'm making this a draft just because it isn't ready for review. Do feel free to mark it ready whenever you want though!

**Comment by timgl** [comment]
@chrysillala Hey, any updates on this? Let us know if you need any help!

**Comment by chrysillala** [comment]
Hi @timgl, first let me apologize because I haven't got time to continue working on this issue and I'm not sure if I can continue since my full-time job load is kinda full. Maybe you can help me to reassign the issue to someone else. 
Once again, I'm really sorry for the inconvenience. Hopefully I can still contribute to your project in the future.
Thank you and regards :)

**Comment by yakkomajuri** [comment]
@chrysillala No worries! Thank you and best of luck!

**Comment by DukeCityDigital** [comment]
@timgl thanks again for your help on this and the related issues - I'm wondering if there's any progress on this or a workaround available?  

If we have i.e. 10 team members and their emails and distinct IDs are known to PostHog (obviously), is there a way to filter out users based on those properties in a cohort?  I've seen it suggested to paste a command in the developer console to ignore a session - this is a good idea but won't necessarily work long term for our use case.  Thanks again!

https://github.com/PostHog/posthog/issues/2776

https://github.com/PostHog/posthog/issues/1289

**Pull request closed without merging**
