### PR TITLE
Add index to events.created_at

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

PRs over issues, but not sure if we should add this. Probably.

- As discovered by a user in https://github.com/PostHog/posthog/issues/3753, when we do the check to calculate actions to all new events since the last calculation, we do a full table scan here: `WHERE "created_at" >= $from AND "created_at" < $to` because there's no index on the `created_at` field.
- This adds an index to the `created_at` field in the events postgres table.
- Running this migration might take a **long long long** time for some users with a large events table, so I'm hesitant to include this. Any thoughts?

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by macobo** [comment]
I'd like to do some measurement in different scenarios before merging this - indexes are great and all but we've been wrong about what needs indexing as frequently as we've been right.

Dropped this into https://github.com/PostHog/posthog/issues/3688

Marking it as draft until we have some numbers/testing done.

For creating indexes like this, CONCURRENTLY is the right keyword.

**Comment by timgl** [comment]
This does seem like an obvious solution to me here (with a CONCURRENTLY built index), as this is what we filter on when we do the partial recalculations. But yes would be good to do some tests as well.

**Comment by mariusandra** [comment]
Converted to a concurrent index, will run some tests locally.

**Comment by macobo** [comment]
Sorry for the delay. Let's ship this.

A future improvement might be adding a separate `created_at` posthog_action_events column using that over the nested subquery.

**Review by macobo — APPROVED** [review]

**Pull request merged**
