### PR TITLE
fix(surveys): reuse feature flag filters for targeting options

### PR DESCRIPTION
**Pull request by liyiy**
## Problem

Re-using feature flag release condition filters allows us to change rollout percentages and show approximate % of users targeted. By default now all surveys will release to 0%, like feature flags, unless updated otherwise

## Changes
the above ^ and moved `linked feature flag` to targeting since it makes more sense there

survey new/edit mode

Screen Shot 2023-07-03 at 6 37 12 PM

survey view mode

Screen Shot 2023-07-03 at 7 14 30 PM

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
I think we'd want to customise the Release Conditions sub-text, to make it clearer / adhere more to what's happening in the survey / explain how this is different from linking a feature flag.

But otherwise, lgtm!

**Review by neilkakkar — CHANGES_REQUESTED** [review]
Actually, just ran it locally, few issues:

1. We're now always creating a targeting flag by default, which isn't great.
2. This unintentionally created flag is also targeted to 0%, so no one will get the survey.
3. The styling on the release conditions component is borked, perhaps because it was intended for high-width areas:
image

4. [not necessary for this PR]: The empty / loading state is a bit wonky:

**Comment by annikaschmid** [comment]
I think we should adjust the wording / structure here a bit.

Both targeting by feature and targeting by user is a targeting/release condition.

We should find the right name (hard problem) that works for both and then adjust the design to make sense.

Ideas:
- release condition
- display on / for
- target by product / target by user

The structure/information hierarchy should then be something like this:

Targeting
      Target by feature
      Target by user

And then the design should be the same for target by feature and target by user. The user targeting currently has a box and a "set 1 - match against all criteria" whereas the page / selector targeting doesn't. It's not consistent design and the only reason I think is because we just took what we had from feature flags without aligning the two designs?

@liyiy Let me know if you want me to spend a bit more time thinking about the design of this and create a mockup, unless we get designs from Cory for this soon, which take this into account already

**Comment by liyiy** [comment]
> Actually, just ran it locally, few issues:
> 
> 1. We're now always creating a targeting flag by default, which isn't great.
> 2. This unintentionally created flag is also targeted to 0%, so no one will get the survey.

I actually think 1 and 2 are an improvement and should be intentional because 2) will ensure surveys don't get rolled out to everyone by accident much like our pattern with feature flags and is better behavior. For 1) I think that is fine because I suspect people will almost always use some form of user properties when they create surveys and ensures 2. I don't see many downsides to this, what do you think?

> 3. The styling on the release conditions component is borked, perhaps because it was intended for high-width areas:

I had noticed this too but I think this only occurs if you have the console open at the same time, otherwise all the words fit fine. But let me know if this is untrue!

> 4. [not necessary for this PR]: The empty / loading state is a bit wonky:

Will fix!

**Comment by liyiy** [comment]
> Both targeting by feature and targeting by user is a targeting/release condition.

> We should find the right name (hard problem) that works for both and then adjust the design to make sense.

Yep there's some consistency text issues here with how we call this targeting/release conditions/etc. I'm not sure when Cory would get back on designs but it would make a lot of sense to collaborate with him on how to best express targeting options considering we also want to have a "how often to show this survey" option later too. 

Let me know if you think the wording is a blocker for the PR though~!

**Comment by annikaschmid** [comment]
I think we should do some improvements to the wording/design before we launch this, yes. This is also in line with Neil's first comment. Especially since you will be off / we don't have a better proposal yet from Cory etc.

Could you follow up with @corywatilo when we can expect some of this designs?

**Comment by neilkakkar** [comment]
[3] borks if you add a property to the release condition, irrespective of screen width.

[1] seems weird to me. We already have a draft mode, remembering to do the 100% rollout right after seems like a hassle. It also introduces this unnecessary dependency of flags for all surveys, which I think isn't great because flags then take down surveys too. It also means people need to make sure decide is enabled (ex: for those using flags only on the backend and having disabled on the frontend due to billing concerns, etc.) for simple url targeted surveys.

I'd rather have an extra step of (a): Explicitly select targeting by users. (b): Then edit conditions / change roll out %s, etc.
If (a) doesn't happen, then no flag is created, keeping dependencies low and having surveys _just work_.

**Comment by liyiy** [comment]
> [3] borks if you add a property to the release condition, irrespective of screen width.

👍 

> [1] seems weird to me. We already have a draft mode, remembering to do the 100% rollout right after seems like a hassle. It also introduces this unnecessary dependency of flags for all surveys, which I think isn't great because flags then take down surveys too. It also means people need to make sure decide is enabled (ex: for those using flags only on the backend and having disabled on the frontend due to billing concerns, etc.) for simple url targeted surveys.
> 
> I'd rather have an extra step of (a): Explicitly select targeting by users. (b): Then edit conditions / change roll out %s, etc. If (a) doesn't happen, then no flag is created, keeping dependencies low and having surveys _just work_.

Fair points! I'll revert it back to empty flag on default

**Comment by liyiy** [comment]
@neilkakkar 

1. Squished text width fixed.

Screen Shot 2023-07-04 at 2 24 05 PM

2. Flags will not be automatically created with surveys unless the user chooses to include "user properties targeting". For new surveys, if a user is just clicking around and checking things out they can remove the user properties before they save. However, once a targeting flag is created, it will always exist with the survey (for now).

Screen Shot 2023-07-04 at 2 23 43 PM

**Comment by liyiy** [comment]
Along with the above ^ fix, added some tweaks to wording and removed the confusing double "release conditions" title from the feature flags filters component.

Let's get this in so users can have the option to change their rollout percentages etc and then continue updating whatever is confusing for users after the user interviews since we've already announced the surveys beta in our changelog.

I think the wording for "targeting" when you're actually editing the survey and then "release conditions" when you're summarizing it makes sense for now

**edit mode**

Screen Shot 2023-07-10 at 6 40 41 PM

**view mode**

Screen Shot 2023-07-10 at 6 41 05 PM

**Review by neilkakkar — APPROVED** [review]
Based on snapshots, these seems to have added a margin bottom to release conditions on feature flags page that makes it look weird.

Let's get rid of that, otherwise LGTM!

**Pull request merged**
