### PR TITLE
Add plugin config required_if and visibile_if

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

Thought this was important for the experience of using plugins as they get more complicated. Thought of this when building the Snowflake plugin.

This introduces two new optional config fields: `required_if` and `visible_if` (**names can be changed** and I still need to do a PR to `plugin-scaffold`).

The way this works is you can specify a list of fields (and optionally also values) that need to be set (or set to the value) for the config option to become visible or required. See below:

https://user-images.githubusercontent.com/38760734/124508629-b5d6e080-dda6-11eb-9113-75f99ef6c6c6.mov

In the first example, we show only the config options that are relevant for the stage the user will use (GCS or S3), and in the second, we make all the Postgres connection options required until the user adds in a DATABASE_URL.

This helps keep configs simple and much easier to use. There's quite a few other plugins that need X to be set if Y is also set, so this will help a lot there.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Frontend CI failing because this needs a supporting PR to `plugin-scaffold`

**Comment by yakkomajuri** [comment]
The way this works now is:

```json
"visible_if": [["someConfigName", "targetValue"],["anotherConfigName"]]
```

An `AND` operation is performed (i.e. it will be visible if all conditions match). 

If the value isn't specified, the condition is fulfilled if the config is simply set.

You can also specify the value `""` if you want something to be visible/required if no value is set for some field.

**Review by mariusandra — APPROVED** [review]
Some type errors to fix, but LGTM otherwise.

**Comment by mariusandra** [comment]
Also, I think this antd way of doing forms makes things really complicated, but until [kea-forms](https://github.com/keajs/kea-forms) is ready (later this week? [the demo](https://github.com/keajs/kea-forms/tree/main/demo/src/forms) already works), this is the best option we have. Thus I'm fine with the extra `useState`, etc hooks for now... :)

**Comment by yakkomajuri** [comment]
Yeah it's cause this needs to go in first:

https://github.com/PostHog/plugin-scaffold/pull/22

**Comment by yakkomajuri** [comment]
Also thought this was quite a bit messy with Antd forms. Kea forms seem interesting

**Pull request merged**
