### PR TITLE
Show toast on API errors

### LINKED ISSUE #3525: Many error notices are suppressed after limiting error toasts
## Bug description

Merging #3220 a while ago suppressed a great deal of **helpful** error messages shown on errors received from API. For instance, creating an invite for an email that already is a member of the org returns err 400 from the API with message "A user with this email address already belongs to the organization.". That message used to be shown in the error toast, which was clear UX, but since we removed that error handling, no error is shown and the user is left very confused as to what happened.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.22

### PR DESCRIPTION
**Pull request by mariusandra**
(PR hijacked by @paolodamico , ignore @mariusandra 's face next to the text)

## Changes

Closes #3525. This PR brings back toast errors when something goes wrong, with a few key differences.
- We will now show only one error at a time. Part of the problem we had before is that you would open a page and 4 toasts would pop up, which felt quite overwhelming.
- We don't show errors for some specific endpoints that we know don't affect the user experience (e.g. preflight) or have special error handling (e.g. insights).
- Show a more detailed error.
- We will show a more detailed error message when a request fails due to a network error or blocked request.
- Opens Papercups if available.
image

**Examples:**

All feedback welcome!

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by paolodamico** [comment]
@mariusandra if you don't mind I'll hijack your PR, make some tweaks and get this out, want to get this in before the code freeze.

**Comment by mariusandra** [comment]
Please!

**Comment by paolodamico** [comment]
Ready for a review @mariusandra!

**Review by mariusandra — COMMENTED** [review]
Code looks good and considering I was already happy with how these toasts were before they were removed, I can only approve!

Because of this bias I'd say @timgl should also say if the approach works for him. 

It's good that we can easily add actions to be ignored. This will help keep the interface noise free.

There's just one UX issue that I think should be solved, best illustrated by a screencast:



If we show only one error, then I'd always like to see the last error shown to me, as that's probably the most urgent one.

**Comment by paolodamico** [comment]
Agreed @mariusandra, I've updated it so that the last error is the one that's actually shown. Will wait for @timgl's input on the UX before merging.

**Pull request merged**
