### PR TITLE
feat(capture): short-circuit most middlewares before event capture

### PR DESCRIPTION
**Pull request by xvello**
## Problem

Part of https://github.com/PostHog/posthog/issues/13260, acting on the low-hanging fruits first. Requests to the capture enpoints go through the full django middleware list, one of them involving a redis query.

As with the decide endpoint, these middlewares do not bring value to the capture endpoints.

## Changes

Expand `ShortCircuitMiddleware` to cover all the routes leading to the `get_event` handler. 

## How did you test this code?

e2e tests should ensure we have no regression. Will profile locally to ensure the middlewares are skipped.

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]
Looks good

Is there an easy way to test that we are short circuiting? Ok if not

**Comment by neilkakkar** [comment]
This does mean we'll lose metrics for the capture endpoints in grafana though. Would be nice to sort these out as well.

**Comment by xvello** [comment]
Agreed @neilkakkar , it's been discussed in [this slack thread](https://posthog.slack.com/archives/C02E3BKC78F/p1670951181902679?thread_ts=1670944608.999199&cid=C02E3BKC78F):

- my django knowledge is pretty limited, and I'd love help on making sure I'm not breaking the prometheus middleware
- do we have dashboards or monitors depending on these metrics?

**Comment by neilkakkar** [comment]
Cool 👍 .

For decide, I put a not-as-exhaustive, quick-fix metric check here:

https://github.com/PostHog/posthog/blob/master/posthog/api/decide.py#L57

which helps track latency, but not the volume: https://metrics.posthog.net/d/iffHpmSMz/posthog-cloud?orgId=1&refresh=30s&viewPanel=14

**Pull request closed without merging**
