### PR TITLE
Saved insights  🐛  fixes

### LINKED ISSUE #6036: Saved Insights 🐛 List
We recently shipped a new saved insights feature hidden behind a FF - #5702

Let's collect all saved insights bugs that our team might find while dogfooding it. Feel free to edit this issue to add to this list.

All fixes will be merged into branch `fix/saved-insights-bugs-6036`

- [X] Funnel insights don't take up the full width - #6039
- [X] Add CTA button to empty insights table for new users w/o insights. - #6042
- [x] The create / edit insight page needs a header that reflects the page state. "Create insight" or "Edit insight" should suffice - #6045
- [ ] ~~When a saved insight is loading, the placeholder for the graph says 'We couldn't find any matching events. Try changing dates or pick another action or event.'~~ See https://github.com/PostHog/posthog/issues/6036#issuecomment-923313159
- [X] Refactor `Insights.tsx` - #6037
- [X] List and Grid buttons should look nicer. - #6048
- [X] Back button doesn't work when viewing a saved insight - #6047
- Add yours here...

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Closes #6036.

Merges a bunch of bug fixes for saved insights into `master`. Each fix was separated out into its own PR and merged into branch `fix/saved-insights-bugs-6036` so that it's easier to scan the diffs.

- [X] Funnel insights don't take up the full width - #6039
- [X] Add CTA button to empty insights table for new users w/o insights. - #6042
- [x] The create / edit insight page needs a header that reflects the page state. "Create insight" or "Edit insight" should suffice - #6045
- [X] Refactor `Insights.tsx` - #6037
- [X] List and Grid buttons should look nicer. - #6048
- [X] Back button doesn't work when viewing a saved insight - #6047
- [X] Add loading check for switching between tabs
- [X] Person modal not showing in view mode - https://github.com/PostHog/posthog.com/pull/2076#discussion_r715013362

@paolodamico This should be blocked on merge until Wednesday to separate it from the release.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by mariusandra — DISMISSED** [review]
Hey, already some merge change to resolve...

Other than that, looks good, just there should also be some "loading" state to prevent this flash:

**Comment by paolodamico** [comment]
Looks like @mariusandra already did an initial pass, please retag us @alexkim205 once it's ready for another look. Also mind, the merge conflicts

**Comment by alexkim205** [comment]
Retagging ya'll for feedback. @paolodamico @mariusandra

**Review by mariusandra — APPROVED** [review]
LGTM

**Pull request merged**
