### PR TITLE
feat(sso): SSO enforcement error codes

### PR DESCRIPTION
**Pull request by paolodamico**
## Problem

See below.

## Changes

- Exposes the new SSO enforcement error codes nicely in the UI (using the already existing UI).
- Changes the parameter name `error` to `error_code` to standardize with the error codes we send on signup.

## How did you test this code?
- Open the login page with an error code, e.g. `/login?error_code=no_new_organizations`
- Attempt to login with an invalid SSO provider, e.g. `/login/invalid/`

### CODE REVIEW

**Review by clarkus — COMMENTED** [review]
Should we make that URL a link so a user can click through? They'd have to copy and paste or type manually otherwise. Are there any other ways to recover here? Also https://posthog.com/sso points to a 404.

**Review by mariusandra — APPROVED** [review]
Looks good. I suggest merging with master to get jest tests working, and then also adding this to the relevant storybook. Should be quite simple.

**Comment by paolodamico** [comment]
Alright added to Storybook and converted to link. @clarkus there's a bunch of things to try to fix for improperly configured SSO but nothing we can explain concisely, that's why I think the link to the docs is the best bet.

**Comment by clarkus** [comment]
> Alright added to Storybook and converted to link. @clarkus there's a bunch of things to try to fix for improperly configured SSO but nothing we can explain concisely, that's why I think the link to the docs is the best bet.

That's cool, the main thing is to offer some means of recovery and you're doing that, so it should work.

**Pull request merged**
