### PR TITLE
Unify Insights table with refreshed style

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Part of #6710.

### Before
Zrzut ekranu 2021-11-23 o 17 29 29

### After
Zrzut ekranu 2021-11-23 o 17 36 58

## How did you test this code?

Manually. Potentially tricky: controlled pagination and sorting.

### CODE REVIEW

**Review by clarkus — APPROVED** [review]
@Twixes is pagination considered part of this effort or is this purely table styling and such? Looks good to me otherwise.

**Comment by Twixes** [comment]
Primarily about unifying the style and making it feel polished. Do you have some pagination improvements in mind?

**Comment by clarkus** [comment]
@Twixes I think it looks good here, but I was thinking about other scenarios with pagination. We're using pagination on some tables but not others (dashboards for example). I can file a follow up issue to make this consistent if that is helpful.

**Comment by Twixes** [comment]
Hmm I think it makes sense to only use it in some places. So far my rationale has been that it makes sense when there's many items (like insights), but it's useless to show it when there's relatively few (like dashboards, at least for the vast majority of projects).

**Review by mariusandra — CHANGES_REQUESTED** [review]
- There's still something with scrolling when going back/forward if the pages are of different length, but it's such an existing niche issue that whatever


- There's a bit too much space between columns and sort icons, making the icons visually connected to the wrong things. I'd try removing the whitespace, and putting the icon after the text, but 🤷‍♂️... @clarkus ? Also there's too much whitespace after the row's first icon.
Screenshot 2021-11-24 at 09 53 12
 
- The "loading" state could already have the list/card view toggle to avoid moving too many things post-load:

**Comment by Twixes** [comment]
Alright, made a few small changes:
- put the sorting icon right after the text instead of at the end of the column
- made the list/card row also be shown during loading
- set the insight type icon column's width to take the minimum possible amount of space

**Review by mariusandra — APPROVED** [review]
Looks good! 

Only nit I found is that these icons all move together. Not sure if that's intentional or not:

**Comment by Twixes** [comment]
That's a 🐞

**Pull request merged**
