### PR TITLE
chore(early-access-management): remove delete and enable archiving early access features

### PR DESCRIPTION
**Pull request by EDsCODE**
## Problem

- deletes aren't useful for seeing feature management history

## Changes

- replace delete with archiving feature

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by liyiy** [comment]
I would want to still be able to delete an early access feature as a user 👀 why can't we have both?

**Comment by EDsCODE** [comment]
@liyiy would you want to be able to delete at every stage? Or delete when the feature is in draft and archive when the feature is in beta

**Comment by liyiy** [comment]
> @liyiy would you want to be able to delete at every stage? Or delete when the feature is in draft and archive when the feature is in beta

at every stage~ esp if people create early access features to test with and then want to delete it permanently

but if there's reasons we shouldn't then I'll happily take at least an option to delete during draft mode heh

**Comment by EDsCODE** [comment]
cool, i added back

**Review by liyiy — APPROVED** [review]

**Pull request merged**
