### PR TITLE
Enable SSL PostgreSQL configuration through env variables

### PR DESCRIPTION
**Pull request by tmilicic**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by Twixes** [comment]
Hey! Thanks a lot for the contribution, we'll work on merging this. Are you a Postgres-over-SSL user yourself?

**Comment by tmilicic** [comment]
> Hey! Thanks a lot for the contribution, we'll work on merging this. Are you a Postgres-over-SSL user yourself?

Hey @Twixes, thank you so much!
Yes, I am currently working on setting up Postgres-over-SSL as part of the project for the company I work in. This would really help us and save us some additional code.

**Comment by Twixes** [comment]
As a side note for our team, **after we accept this**, but **before we merge it**, we're going to have to implement the same in https://github.com/PostHog/plugin-server for event processing to work with the same configuration.

**Review by EDsCODE — COMMENTED** [review]
Hi @tmilicic, thanks for the contribution! Before accepting this, would you mind adding relevant docs that accompany this change on our docs [repo](https://github.com/PostHog/posthog.com/tree/master/contents/docs/configuring-posthog)?

**Comment by tmilicic** [comment]
> Hi @tmilicic, thanks for the contribution! Before accepting this, would you mind adding relevant docs that accompany this change on our docs [repo](https://github.com/PostHog/posthog.com/tree/master/contents/docs/configuring-posthog)?

Hi @EDsCODE, oppened the PR with relevant docs [here](https://github.com/PostHog/posthog.com/pull/866)

**Comment by EDsCODE** [comment]
Awesome, thanks.

@Twixes do you mind making the addition to the plugin-server? Otherwise, I can pick it up in a short bit

**Comment by tmilicic** [comment]
Hi, is there something I can do to push this foreward? I saw that docs for this have already been merged

**Comment by Twixes** [comment]
Hey, so at the moment the plugin server supports connections **exclusively** using the `DATABASE_URL` env var, which does support these settings (see brianc/node-postgres#2345), so for me this PR is a go. Just awaiting confirmation from @EDsCODE.
Should you experience any issues @tmilicic with any piece of PostHog not cooperating with Postgres over SSL, let us know.
Disregard the single failing Cypress test causing redness, it's an unrelated problem. #2988

**Review by EDsCODE — APPROVED** [review]
lgtm!

**Comment by yakkomajuri** [comment]
Hey @tmilicic! Thanks for the PR - email me at yakko[at]posthog[.]com from your GH email to get some merch from us!

**Pull request merged**
