### PR TITLE
feat(correlation): add warning when funnel skewed

### PR DESCRIPTION
**Pull request by hazzadous**
This actual just uses the funnel numbers rather than the correlation
endpoint as this gives us a little more freedom to, for instance, add
details of why we think there might be inaccurate results, without
having to update the definition in the backend as well.

And alternative option might be to introduce an error code along with a
human readable message that includes the details of skew reasoning,
returned from the API, but I think this gives us what we want.

Screenshot 2021-10-12 at 10 39 35

### CODE REVIEW

**Review by macobo — COMMENTED** [review]
Some quick fly-by comments.

Nit: For visual changes a screenshot would be nice!

**Comment by hazzadous** [comment]
> Nit: For visual changes a screenshot would be nice!

Have updated with screenshot

**Comment by hazzadous** [comment]
fyi @neilkakkar I ended up removing the logic as I ran into typing issues, and I'm not sure it's worth it for just `isSkewed`

Perhaps in another separate refactor? Pulling in, e.g. the other correlation related bits?

**Comment by neilkakkar** [comment]
I think the new logic makes sense for when we do correlation over other insights as well? Right now it's a property of the funnel, so I think makes sense for it to be a part of funnelLogic

**Review by neilkakkar — APPROVED** [review]

**Pull request merged**
