### PR TITLE
Persist event and property definitions

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Simpler version of https://github.com/PostHog/posthog/pull/4571
- Makes event and property definitions load no matter where you are in the app, and then keep them in memory for the entire duration of the app.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by macobo** [comment]
:+1: seems sane, though might have bugs which got fixed in the linked PR (see trendsLogic/propertyFilterLogic).

Since this does not solve same problem set as https://github.com/PostHog/posthog/pull/4571 - what are the plans for the rest of the requests? As-is this is only a half-solution.

**Comment by mariusandra** [comment]
You wanted a fast solution that would fix the issues this one client is having, and this PR helps with that. As for the other requests, they haven't been a problem yet for anyone?

Thus I'll tackle them when I work on this tomorrow. However I'd rather merge and revert this PR, than #4571

**Comment by liyiy** [comment]
I think another part of this problem is that the SQL query I wrote (because there's a join 😢) for enterprise version is making it take a while to load? https://github.com/PostHog/posthog/blob/master/posthog/api/event_definition.py#L49 

Anything simple I can do to speed things up backend wise to help that initial request load time?

**Comment by macobo** [comment]
> As for the other requests, they haven't been a problem yet for anyone?

They are a problem, hence my original PR. Weird gatekeepering going on here - I shouldn't need to be pointing out that yes, the problem that is being solved is real in 2 different slack threads, 2 different issues, in a demo session and in 2 different PRs. 

I appreciate this PR and it's worth simplifying the original with this. However: please give me the tools needed to get my tasks done here or give me the go-ahead to fix it myself - you're being a blocker here @mariusandra for getting things done and solving the pain points of our focus clients both self-hosting and on cloud.

**Comment by macobo** [comment]
@liyiy - if that's the case then please open a separate issue/PR, not worth discussing under this one.

**Comment by liyiy** [comment]
> @liyiy - if that's the case then please open a separate issue/PR, not worth discussing under this one.

Actually #4571 was already up before I merged in my taxonomy PR #4486 so I don't think my PR was the issue here, nvm! We can ignore my above comment 🙂

**Comment by mariusandra** [comment]
Closing this in favor of #4627

@macobo, my apologies for not understanding the urgency of this. I had assumed we both mutually understood it was OK for me to look at it at the beginning of this week as soon as I can, which is now.

**Pull request closed without merging**
