### PR TITLE
style(flake8): enable B001

### PR DESCRIPTION
**Pull request by ellie**
## Problem

More linting = better (usually...)

## Changes
Enable a lint rule that has, so far, been disabled

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

CI + running `flake8 .` locally

### CODE REVIEW

**Comment by ellie** [comment]
Looks like our codebase doesn't actually violate this 🥳

**Comment by ellie** [comment]
Huh my local flake8 lied 🤔 will come back to this.

**Comment by Twixes** [comment]
Even if it doesn't, it's probably a good idea to remove this from the ignored list, isn't it? (I mean, there's already the – tiny – sunk cost of a PR created 😄) @ellie

**Comment by Twixes** [comment]
Oh, there's a bunch of them – well, probably not high priority right now!

**Pull request closed without merging**
