### PR TITLE
fix: removing session replay button from feature flag create page

### PR DESCRIPTION
**Pull request by surbhi-posthog**
Removing the "View recordings" button from the Create Feature Flag page and making sure it still exists in the edit/view page

I created a branch that I deprecated and started a new one since I needed to revert too many files. Here is the original PR for reference: https://github.com/PostHog/posthog/pull/26364

## Changes

| Before | After | After (multi-variant create view) |
|--------|-------|----------------------------------|
| Before Image | After Image |image|

Verified that the View recordings button is still visible in the view/edit pages:

## Unimpacted views

| View Page | Edit Page |
|-----------|-----------|
| View Page | Edit Page |

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud

## How did you test this code?
Verified that button is not seen in the view page, but can still be access in the edit/view pages.
tested locally on: http://localhost:8000/project/2/feature_flags/new

### CODE REVIEW

**Comment by surbhi-posthog** [comment]
@zlwaterfield @raquelmsmith I noticed that the View recording button is implemented in [another place ](https://github.com/PostHog/posthog/blob/2e4052afa26eba93e7d14173871fe7acd9eafd5e/frontend/src/scenes/feature-flags/FeatureFlag.tsx#L887)in the same file: 

I'm assuming this was built for the multi variant view. I verified that the button does not show up while creating a flag with multi variants. 

Should we also try to consolidate button logic into one component? Or does it make sense to keep in separate here?

**Review by zlwaterfield — APPROVED** [review]
Looks good, thanks for adding this.

For the multi-variant one, that passed in different parameters so we can keep them separate.

**Comment by neilkakkar** [comment]
100% optional flyby, I think it makes more sense to re-use the `readonly` parameter here - recordings button should show only when read only, vs checking the `id` is not new. It doesn't make too much sense for this button to exist on the edit page either - at the stage its not something editable and clutters the edit screen 😅

**Comment by surbhi-posthog** [comment]
Sure thing! I initially left the button on the edit page, thinking it might be useful for users to check session relays while editing the feature flag. That said, I trust your judgment on use behaviors, so I’ll go ahead and make the change.

**Comment by surbhi-posthog** [comment]
updated logic to use the readOnly flag instead here: https://github.com/PostHog/posthog/pull/26451

**Pull request merged**
