### PR TITLE
Add .github/workflows/docker-vuln-scan.yml

### LINKED ISSUE #5374: Fix/mitigate security vulnerabilities before a release or in general
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Let's try to fix/mitigate package vulnerabilities before a release. It's good general maintenance and users have reported having issues with us not doing so.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Changes
This PR adds a new GitHub action workflow to:

* build and upload to Docker Hub a new artifact image
* scan that artifact image via [Trivy](https://github.com/aquasecurity/trivy) 

## How did you test this code?
* see image created [here](https://hub.docker.com/layers/posthog/posthog/vuln-scan-77bd076af0761635f7e2e9c658376fa8b87a17c3/images/sha256-7668b0f6a8de46ac45913ce1734014312927a0719663b545658006b23dc0cb85?context=repo) 
* see scan results [here](https://github.com/PostHog/posthog/security/code-scanning?query=is%3Aopen+pr%3A6479)

### CODE REVIEW

**Review by yakkomajuri — APPROVED** [review]
LGTM

**Comment by paolodamico** [comment]
FYI we already run automatic vulnerability scans on Docker Hub (I believe they do it through Snyk) and ECR. We may want to just pull the results from there.

**Comment by guidoiaquinti** [comment]
> FYI we already run automatic vulnerability scans on Docker Hub (I believe they do it through Snyk) and ECR. We may want to just pull the results from there.

Yes I'm aware of that but while Docker Hub, Snyk and ECR require a subscription, Trivy doesn't have any requirement. I was also thinking to use Trivy as it seems (at least to me) better supported by the GitHub ecosystem.

**Comment by paolodamico** [comment]
FYI we do have a subscription on Docker Hub

**Comment by guidoiaquinti** [comment]
> FYI we do have a subscription on Docker Hub

Good to know! Anyway, I didn't find an easy way to pull Snyk reports from Docker Hub to the GitHub `Security` tab. If it's 👍 to you @paolodamico I'm inclined to merge this to start collecting some metrics and start the work to reduce the security issues.

**Comment by paolodamico** [comment]
Absolutely! No hold back on my part at all, just wanted to make sure you had all the context there.

**Pull request merged**
