### PR TITLE
fix: Segmenter calculation of inactive segments

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Not sure how or when this broke but we were calculating inactive period all wrong.

## Changes

* Fixed to set the lastactivetime _after_ we use it rather than before.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by benjackwhite** [comment]
I don't think this ever worked 🙈

**Comment by benjackwhite** [comment]
@rcmarron FYI this is the fix for your inactivity issue

**Review by pauldambra — APPROVED** [review]
I'm guessing we need to update the ingestion segmenter too?

**Comment by benjackwhite** [comment]
> I'm guessing we need to update the ingestion segmenter too?

Ah yeah probably

**Pull request merged**
