### PR TITLE
Remove sessions insight frontend

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- Removes the frontend code for the `sessions` insight. This was original discussed in this blog post (https://posthog.com/blog/sessions-removal) and we ran a test where we added the following warning and deprioritized the insight.

    

### Additional context / metrics
- Usage of the insight dropped 56% from Nov to Dec. Further, only ~1% of discoveries on December were on Sessions. [[Source](https://app.posthog.com/insights/BWiGv8Nq/edit?insight=TRENDS&display=ActionsLineGraph&interval=month&actions=%5B%7B%22id%22%3A%2210784%22%2C%22name%22%3A%22Discoveries%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math%22%3A%22total%22%7D%2C%7B%22id%22%3A%2210784%22%2C%22name%22%3A%22Discoveries%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22insight%22%2C%22value%22%3A%5B%22SESSIONS%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22total%22%7D%5D&events=%5B%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&date_from=-90d&formula=B%2FA*100)]
- From the warning above, no one clicked on "Still interested?" [[Source](https://app.posthog.com/insights/BWiGv8Nq/edit?insight=TRENDS&display=ActionsLineGraph&interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22session%20removal%20still%20interested%22%2C%22name%22%3A%22session%20removal%20still%20interested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&date_from=-90d)]
- From the warning above, only ~20 users went to the blog post for context [[Source](https://app.posthog.com/insights/BWiGv8Nq/edit?insight=TRENDS&display=ActionsLineGraph&interval=month&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22utm_campaign%22%2C%22value%22%3A%5B%22sessions-insight-deprecation%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&date_from=-90d)]

## How did you test this code?
- Launched the app and made sure insights loaded correctly without showing Sessions.
- Relied on typescript to clean unneeded code.
- Relying on E2E tests & frontend tests.

### CODE REVIEW

**Comment by paolodamico** [comment]
One thing I'm unsure about is what we want to do with previously saved insights and dashboards. I think perhaps we want to show a deprecation warning view (simple concept below) in any dashboard and just disappear the ones in the saved insight list. Thoughts @clarkus ?

**Comment by clarkus** [comment]
> One thing I'm unsure about is what we want to do with previously saved insights and dashboards. I think perhaps we want to show a deprecation warning view (simple concept below) in any dashboard and just disappear the ones in the saved insight list. Thoughts @clarkus ?

A similar case could exist if a dashboard can reference a non-existent insight via other scenarios. I think it'd be best to represent that the insight no longer exists more-so than that "sessions have been deprecated". That would result in a pattern that could still add value in other scenarios. I like the prominent delete action, but it might be clearer if it were labeled "remove from dashboard". If that insight no longer exists, we're really just having the user remove the reference, not the insight itself. Thoughts?

**Review by alexkim205 — APPROVED** [review]
Awesome, I love red PR's. I think it's a good call to tear down the frontend first before the backend. Feel free to tag me or @rcmarron for that PR.

I briefly looked over the diff and tried it out on local, and nothing major seems to be broken.

A few more things that can also be deleted found through JetBrains magic:
- `frontend/src/lib/components/SessionsFilter.tsx`
- [report.txt](https://github.com/PostHog/posthog/files/7818722/report.txt)

**Comment by marcushyett-ph** [comment]
I know we've been working on this for a while, removing a feature is always a bold move. From the data shared, It looks to me like we've done a good level of diligence and made the call to improve the overall quality of the experience for users by removing this insight.

I expect we might get more people to reach out when the feature is actually gone - we should proactively use a ticket to capture feedback and justification for building a new sessions type insight in the future.

Given this PR is just changing the front-end - what happens to the data that was used to calculate session lengths? Can people still query it using trends? If so, should we provide a guide to get similar results using trends or should we prevent them from being able to do so?

**Pull request merged**
