### PR TITLE
feat(Dashboards): Filtering on entire dashboard

### LINKED ISSUE #2587: Custom filters on dashboards
## Is your feature request related to a problem?

When setting up dashboards I'd like to filter the stats to a certain page/subdomain. 

## Describe the solution you'd like

Allow adding a extra filters for all graphs on a dashboard (e.g. filter by $current_url)

## Describe alternatives you've considered

Updating every graph in dashboard one-by-one and then reverting them back.

## Additional context

Related to https://github.com/PostHog/posthog/issues/780

Datadog has a decent solution for this: https://docs.datadoghq.com/dashboards/template_variables/, which I think we can simplify and use ourselves.

Came up during #2560

### PR DESCRIPTION
**Pull request by timgl**
## Problem

Want to be able to filter a dashboard down on a specific property

Closes #2587

## Changes

- Add property filter to dashboard
- Any properties here get "AND" with the property group of the insight. @clarkus this feels like the most obvious way of doing this (and same way the test/internal users filter works).
- TODO: I should probably add a feature flag
- TODO: current place looks really ugly, but it needs to be tied in to the date filter on the right somehow. @clarkus thoughts?

image

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

unit tests
QA: go to dashboard, filter down

### CODE REVIEW

**Comment by clarkus** [comment]
I think we could repurpose the designs from the [recent live events / data management UI changes](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10208%3A43295). Filters can be very verbose and scale to take up a lot of horizontal space, so the placement you have would breakdown after enough filters are specified.

Screen Shot 2022-05-12 at 10 00 58 AM
 
I was just talking about dashboards with some other folks - I'm wondering about validation and what happens when filters / time ranges are specified that conflict with the insight definition. It's a bigger topic than just this issue but there are cases where the dashboard conditions can make an insight undisplayable - funnels with their conversion windows are especially prone to getting into hard to render scenarios.

**Comment by pauldambra** [comment]
double-checked and this works perfectly with many-to-many insights 🙌 

If you edit a name, the filter disappears (if you refresh - it comes back)

**Comment by timgl** [comment]
@pauldambra Is this still happening? I can't reproduce

**Comment by pauldambra** [comment]
Still there for me...

But the feature is cool and behind a flag, also might be fixed by sorting out insight/dashboard turbo mode for many-to-many

I don't think it's blocking

new-name

**Comment by timgl** [comment]
@pauldambra Found the issue, fixed and merged. Thanks!

**Pull request merged**
