### PR TITLE
feat(async-migrations): add auto complete trivial migrations option

### PR DESCRIPTION
**Pull request by hazzadous**
## Problem

When there is a heavy query as part of the check for is_required for a migration, this 
can end up putting a lot of load on ClickHouse. We run `run_async_migrations --check` as
an init container on k8s, when there are a lot of pods this can become an intensive operation
and can bring the cluster to a stand still.

## Changes

This change is to ensure that the `run_async_migrations --check` command
option is a light operation such that we can safely use this e.g. in an
init container to gate the starting of a K8s Pod.

Previous to this change, the command was also handling the
auto-completion of migrations that it deamed to not be required, via the
`is_required` migration function. Aside from this heaviness issue, it's
good to avoid having side effects from a check command.

Note that `./bin/migrate` is the command we call from both ECS migration
task and the Helm chart migration job.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by guidoiaquinti — COMMENTED** [review]
LGTM but better to have another pair of 👀 . I'm not very familiar with async-migrations

**Review by guidoiaquinti — APPROVED** [review]
LGTM but better to have another pair of 👀 . I'm not very familiar with async-migrations

**Review by yakkomajuri — APPROVED** [review]
Thanks - makes sense to me.

I just disagree a bit with the naming "trivial". "Completing a trivial migration" implies to me that something actually ran. In reality we just no-op migrations that are not required on an instance. Sure, technically we do an extra check on the dependency, but in reality we "skip non-required migrations" in my mind rather than "auto complete trivial" ones.

Slight issue though, feel free to push back/override

**Comment by hazzadous** [comment]
> I just disagree a bit with the naming "trivial". "Completing a trivial migration" implies to me that something actually ran. In reality we just no-op migrations that are not required on an instance. Sure, technically we do an extra check on the dependency, but in reality we "skip non-required migrations" in my mind rather than "auto complete trivial" ones.

how about `--skip-noop-migrations`?

**Comment by hazzadous** [comment]
@yakkomajuri have made the rename change to `--skip-noop-migrations`, I think it sounds better

**Comment by yakkomajuri** [comment]
To be fair, let's actually use "complete noop". Noop already implies it does nothing, so complete is better than skip here as we do actually update the db. 

Whatcha think? @hazzadous

**Comment by hazzadous** [comment]
> Whatcha think? 

Yep done 👍

**Pull request merged**
