### PR TITLE
Modify hashing mechanism for Feature Flag rollout percentage

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

This is a "discussion" PR, following our principle of submitting a PR instead of an issue. 

Currently, for feature flags using rollout percentage, we decide if they are on for a given user based on a hash of the distinct id of the user and the key of the flag.

This is good because it ensures that the same flag will persist for users, but that there is some variation across flags. If we were to just use distinct ids for instance, then a given user might have all flags off with no variation.

However, the key of the flag is very easily changed in our current frontend setup. Indeed, if someone has a flag powering a lot of things in their app, they would probably be reluctant to change the key since they would need to update their codebase, but I can see various cases where even simply for style purposes someone would change the key of a flag. Once that happens, that given flag stops persisting and users may experience changes to their UI/UX. 

As a result, this PR is proposing to use the flag id rather than its key as a parameter to the hash function. This should be consistent and persist, irrespective of the key changing.

For the long-term, I haven't come up with ways about how this would be worse. However, the whole point of this PR is to be told if this makes sense or not. In the short-term, the change in this mechanism will cause users with rollout percentage flags on to have problems as their flags will not persist following the change. 

Hence, I'd like to hear your thoughts. If we decide not to follow this approach or change the use of the key in the hash function, I'll then put out another PR to warn users of what can happen when they change the key of a flag. 

## Checklist

- [ ] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [ ] Backend tests (if this PR affects the backend)
- [ ] Cypress E2E tests (if this PR affects the front and/or backend)

### CODE REVIEW

**Comment by timgl** [comment]
I can also see no downside. There's not a huge amount of usage of feature flags (45 total created so far).

**Comment by yakkomajuri** [comment]
@timgl Should we move forward with this then?

The next Release Notes could then include a mention about this for those who do have feature flags on.

**Comment by timgl** [comment]
Actually I have come up with a case that would be annoying here. Say you've accidentally removed a feature flag and you want to re-create it. With this change, you won't be able to get the same outcome, even if you use the same key. Same if you move environments (for example from PostHog cloud to self hosted)

Also what makes me a little nervous is that all other feature flag providers use key based rather than ID based. I think lets stick with key based for now and add a warning when you try editing a key on an existing feature flag. WDYT?

**Comment by yakkomajuri** [comment]
@timgl Yeah that makes sense to me. Again, the idea of the PR was exactly for people to poke holes in it. But definitely good to have a little warning on the key change. I'll work on that.

**Pull request closed without merging**
