### PR TITLE
Experiment workflow steps

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

First iteration of experiment workflow. This only shows up on the read only page for experiments, right after the user creates an experiment but before the user clicks "launch"

Screen Shot 2022-02-03 at 3 21 32 PM

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Comment by neilkakkar** [comment]
Looks good! The first step background though falls shorter than the other 2:

image

**Comment by neilkakkar** [comment]
(and margin bottom for next section)

But otherwise LGTM - are we going to get this in as is, or wait for Chris's refresh to solve #8436 ?

**Comment by liyiy** [comment]
> (and margin bottom for next section)
> 
> But otherwise LGTM - are we going to get this in as is, or wait for Chris's refresh to solve #8436 ?

get this in so I can avoid merge conflicts xD since #8436 is an addition and not a modification

**Comment by liyiy** [comment]
Screen Shot 2022-02-04 at 12 01 54 PM

**Review by neilkakkar — APPROVED** [review]

**Comment by neilkakkar** [comment]
Wait you didn't push anything 😂 . No clue how to sort this - what do you usually do in this case?

**Pull request merged**
