### PR TITLE
Use pytest-xdist for parallel tests.

### PR DESCRIPTION
**Pull request by tirkarthi**
## Changes

Use pytest-xdist for parallel tests. Use `--nomigrations` for some more speed boost.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Comment by tirkarthi** [comment]
Not sure about the ee test pipeline failure but the --nomigrations and pytest-xdist seems to keep the tests under 1 minute.

**Comment by tirkarthi** [comment]
Just noticed that the db fixture is present in conftest that applies migrations. In parallel process it could be a case where this goes on to execute the migration twice in CI and causes error that database already exists.

**Comment by macobo** [comment]
This is a solid change, but needs more work to work under ee/ (which is a prerequisite for merging).

For ee, currently there's a single clickhouse connection pool used that reads the db name from `env` (via settings.py) - I assume that needs to get somehow refactored for this to work. :)

**Comment by tirkarthi** [comment]
pytest exposes the worker_id as a fixture : https://github.com/pytest-dev/pytest-xdist/issues/280 . So I tried using the worker_id to connect to db_1 for 1st process, db_2 for 2nd process etc. Since it's a pytest fixture it's not present during settings.py load. Hence I just used a different database for django_db_setup clickhouse connection and patched settings.CLICKHOUSE_DATABASE . I am getting a different error now that default.kafka_person was not created. Maybe I am missing some place where the database name or something has to be updated.

**Comment by tirkarthi** [comment]
This is turning out to be more complex with my approach. I tried to patch the database name but pytest imports all files before db_setup and hence the modules import the unpatched database value to form incorrect sql strings during migration. There is `pytest_configure` hook but that won't really have the worker_id since the tests were not yet collected with which the database name can be patched.

**Comment by tirkarthi** [comment]
This is not a very ideal way to do it. But the way it works is that the clickhouse database is named according to the worker. worker_id fixture gives us the worker id for the current process. So 2 process means we create test_1 and test_2 database. For single process worker_id is just master. The complexity comes in the fact that SQL strings constructed inside ee.clickhouse.sql are done at import time. The worker_id is available only after collection. This results in SQL strings to be created at import time with normal test database name. So after the database creation for the respective worker the CLICKHOUSE_DATABASE value is patched and the modules were SQL strings are constructed on top-level are reloaded so that the strings pick up the patched value to construct database. Similarly ee.clickhouse.client also makes client with unpatched value for sync_execute which also needs to be reloaded. I can see the CI timing cut into half from 15 minutes to 6-7 minutes. Timings as below in various stages : 

|  Change | normal  |
|---|---|
| master  | 15 minutes |
|  -n auto (2 Process)  |  10 minutes |
|  -n 4 (4 Process, 2 * (2 cores)) | 7 minutes  |

This PR is backwards compatible as in if user wants with single process also it works fine. 

Drawbacks mostly in CI : 
* breakpoints don't work in xdist though it's only in CI
* -s to capture output don't work in xdist that means print won't work. Using stderr to print will work.
* xdist might cause failures exposing fragile tests. I have used rerun failures plugin to run the failed tests. But this is something to be fixed.
* Future new modules that construct sql during compile time if any might cause failures and have to be included here for reload.

**Pull request closed without merging**
