### PR TITLE
Update UI for person header

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- Updates the UI of the person header using lemonade components.
- Adjust the styling to better match our design language (e.g. hover style)
- Removes the link from the Person page as you’re already there.

**Main table**
image

**In other contexts**

## How did you test this code?
- Ensured everything looked correctly in the person/persons page & other places where we use the same component (e.g. the person modal)

### CODE REVIEW

**Review by clarkus — APPROVED** [review]

**Comment by paolodamico** [comment]
Unrelated failing tests.
- Cypress failure: https://github.com/PostHog/posthog/pull/7499
- Storybook failure: https://posthog.slack.com/archives/C0113360FFV/p1638543918015400?thread_ts=1638541708.015000&cid=C0113360FFV

**Review by Twixes — COMMENTED** [review]
This was merged quickly but I'd kind of like to do "request changes" here:

- This "profile picture" is a bit too close to the "user name", it looks very tight
    Screen Shot 2021-12-06 at 15 14 55
- The hover state for the "profile picture" should have a 200ms transition
- I'm not really a fan of using the `ProfilePicture` component for PostHog persons, for a few reasons:
	- It doesn't use gravatars here and IMO it'd be a bit weird if it did. If we do implement avatar support for persons, it should IMO be somehow integrated with the tracked product's avatars
	- Because it doesn't use gravatars, it only shows the initial letter. That's practically useless for distinguishing persons, as many are named "User WXYZ" in which case it's all "U"s, or it's a variation of special person properties such as `email`.
	- Most importantly, I think that `ProfilePicture` should be reserved for users of PostHog itself – I really liked that "mass-produced" PostHog persons got a somewhat anonymous person icon, while tangible (you know them personally) team members got an actual avatar. When `ProfilePicture` is used for both, it's less clear that a product user (_person_) is a completely different entity from a PostHog user.

What do you think about this? @paolodamico @clarkus

**Comment by clarkus** [comment]
I like the idea of distinguishing posthog users from persons in data. Having a richer representation of the person makes a ton of sense. Gravatars are a good way of doing this, but gravatars aren't super well known to everyone. We might eventually allow for a simple picture upload to make it easier to personalize your account. The same approach could be applied to organizations - it'd make sense to use personalization to distinguish orgs from other instrumented group data.

**Comment by Twixes** [comment]
Hmm, I don't quite understand @clarkus, what do you mean by "distinguishing posthog users from persons _in data_"?
As for personalizing your account, I don't think it's super relevant for this PR. My main objection is about using the same UI component for both _PostHog persons_ (users of your product) and _PostHog users_ (your team members).
I would prefer to keep using the person icon for persons instead of `ProfilePicture` introduced here – what's your take on this proposal?

**Comment by clarkus** [comment]
> Hmm, I don't quite understand @clarkus, what do you mean by "distinguishing posthog users from persons in data"?

Apologies - I was agreeing with your point / proposal. The use of an images for users, lettermarks for persons in data. As a placeholder, we can use lettermarks for both. Persons in data don't really have "profiles" so it'd make sense to not use that here.

**Pull request merged**
