### PR TITLE
chore(eslint): explicitly disable exhaustive deps on historical code

### PR DESCRIPTION
**Pull request by hazzadous**
I haven't made any attempt here to resolve anything here, just to
explicitly acknowledge that these are issues that eslint has highlighted
and we should ignore, for the sake of easily picking up new issues. If
these are truely problematic, then I am assuming they should have been
picked up as bugs with the system.

This doesn't stop someone from coming in and reviewing the code in this
pr retrospectively.

There's a bit on the web about this rule, about having it disabled. I suspect that it's difficult to get a good view on if this signals that it's useless. i.e. large community will always have large subset expressing any view. Anyway, that how I'm explaining it to myself.

Anyway, point is, it does catch bugs, and is easy to override in a deliberate way, will show up on PR's to initial discussion and is a good learning point about how react works.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
I'm too late, but I disagree with removing the eslint rule.

- It normally has not helped us catch bugs we otherwise wouldn't catch. Few rare exceptions nonwithstanding.
- Any kea action will be treated as a new and unique dependency that needs to be added to the deps list, greatly adding noise. Those should never change anyway.
- We should move away from using useEffect with kea in the first place. Normally code inside a useEffect goes into kea's `events` -> `afterMount`, but we're not there yet.

The PR looks good though. Definitely better to add 46 `eslint-disable-next-line`s than editing all these the deps arrays. Better still to disable the rule though 😅

**Comment by mariusandra** [comment]
This captures my thoughts around eslint rules: https://overreacted.io/writing-resilient-components/#marie-kondo-your-lint-config

**Comment by hazzadous** [comment]
> This captures my thoughts around eslint rules: https://overreacted.io/writing-resilient-components/#marie-kondo-your-lint-config

I definitely agree on aesthetic rules for sure. For pointers to where there may be likely logical issues I'd say it's useful, even just as a communication/teaching tool.

Anyway, I'd low some help then on migrating [my recent react changes](https://github.com/PostHog/posthog/pull/6407) to kea when you have a chance @mariusandra

**Comment by mariusandra** [comment]
I mean, while I'll try to please eslint, I'll probably keep adding this `eslint-disable` tag to some new deps arrays in the future and suggest others to do the same, as kea actions, `window`, and other false matches this rule blesses us with, just don't belong in the array. So a teaching tool it is...

Looking at these changes is coming up in my "get through" list...

**Pull request merged**
