### PR TITLE
feat(actions): Increase `slack_message_format` max length from 200 to 500

### LINKED ISSUE #9438: Increase character limit of Action message format
## Is your feature request related to a problem?

Can't define desired message format in an Action.

## Describe the solution you'd like

Increase character limit significantly.

## Describe alternatives you've considered

none

## Additional context

200 characters are way too little, especially if you have lots of variables with long names.
A single placeholder can easily take 50 characters, esp. with the overly long `[event.properties.…]` syntax.

image

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Resolves #9438.

## Changes

Increases max length of message format to ~~500~~ 600. Seems like a safe change that should be practically free, so why not accommodate users.
Also improved readability of file structure by moving actual code out of `__init__`.

### CODE REVIEW

**Review by guidoiaquinti — APPROVED** [review]
LGTM, also 👍 if we want to bump it even more

**Comment by Twixes** [comment]
600 then because why not

**Review by guidoiaquinti — APPROVED** [review]
:generous mood:

**Comment by thmsobrmlr** [comment]
Are we good to bump this once more @Twixes ? Customer is limited by 600 https://posthog.com/questions/error-when-i-write-to-slack-message-format

**Pull request merged**
