### PR TITLE
chore(docker-compose): fix regression

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Problem
Fix regression introduced via #10917 as `network_mode: host` only works on Linux because docker runs in a VM in windows/macos.

## Changes
Move back to use ports but still removes the need to add an entry to `/etc/hosts` 

## How did you test this code?
Locally the stack seems to work fine

Screenshot 2022-07-22 at 11 13 17

Let's see CI

### CODE REVIEW

**Comment by hazzadous** [comment]
you'll also need to make sure django thinks kafka is at `kafka` not `localhost` as it sets this in the KafkaTable on ClickHouse, for which localhost will not work.

OT: At some point it would be great to move to a push model for loading rather than a pull, there's something nasty about the ClickHouse dependencies as it is now.

**Comment by hazzadous** [comment]
> you'll also need to make sure django thinks kafka is at kafka not localhost as it sets this in the KafkaTable on ClickHouse, for which localhost will not work.

At which point we're back to adding kafka to /etc/hosts 👎

**Comment by guidoiaquinti** [comment]
> you'll also need to make sure django thinks kafka is at kafka not localhost as it sets this in the KafkaTable on ClickHouse, for which localhost will not work.

Ah right. The right fix here would be decoupling the `Django -> Kafka` and `ClickHouse -> Kafka` name resolution. The logic could use the default for both if another env variable is not set.

**Comment by guidoiaquinti** [comment]
Closing as this will not work (see why above)

**Pull request closed without merging**
