### PR TITLE
feat: highlight in legend for pie charts

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

relates to #12226 and #11433

## Changes

Highlights insight legend row when hovering over piechart

## How did you test this code?

running it locally

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
This is really nice. From a UX perspective, I see two possible enhancements:

- Would be intuitive for highlighting to work both ways (i.e. hovering in the legend would highlight that series + activate hover in the chart) – might be achievable with `chart.setActiveElements()`, but not sure
- We should scroll a highlighted series into view within the legend:
    

Do with those as you will.

**Comment by pauldambra** [comment]
added scrolling into view on highlight... will punt highlighting from the legend forwards into another PR. Turns out it's tricky and I don't want this PR to get stuck :)

**Comment by pauldambra** [comment]
scroll-to-hover

**Review by Twixes — APPROVED** [review]
Love it

**Pull request merged**
