### PR TITLE
feat: re-order activity log sentences

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

Our APIs allow multiple changes in one request. And so the activity log sometimes has to describe multiple changes in one sentence.

It uses the sentence structure "person did a thing, did a thing, and did a thing on the item being tracked"

This doesn't always work. For example:

Screenshot 2022-06-23 at 22 10 01

## Changes

Changes the structure of the sentences

So now it is "On the item being tracked, person, did a thing, did a thing, and did a thing"

|   Before | After  | 
|---|---|
|  Screenshot 2022-06-23 at 22 54 12 |   Screenshot 2022-06-23 at 23 33 15 |
|  Screenshot 2022-06-23 at 23 41 27|  Screenshot 2022-06-23 at 22 31 33 |   
|  Screenshot 2022-06-23 at 22 17 01 |  Screenshot 2022-06-23 at 22 43 29 |

Alongside this, it fixes two layout bugs

* spaces between sentence items weren't always showing
* person split and merge changes were vertical sentences

These are all available in story book for review

## How did you test this code?

updated developer tests, and ran locally in storybook

### CODE REVIEW

**Comment by mariusandra** [comment]
I might not be used to this style, but somehow the "before" looks more readable. I expect to see the user's avatar next to the user's name, not disconnected by several words like here -> the symmetry makes it easier to scan. So I'm not sure the "after" versions are better 🤔.

If the insight details are the main changes that break the presentation, could we have some exception for only them? E.g. breaking them apart from the rest of the sentence?

Other bug: the user's name is not visible in the "created the flag" cases.

**Review by benjackwhite — APPROVED** [review]
Code-wise looks good. I also agree with @mariusandra that it is slightly less natural to read but personally I would lean towards something that is more maintainable than something that is grammatically the best.

**Comment by clarkus** [comment]
I agree with the feedback that the updated syntax is generally harder to read. Do we have a list of all the supported log entry types? If we know the full list of scenarios to cover, we can work from that to come up with a general approach that can apply everywhere. @joethreepwood might be especially impactful here. I can make time to support on this, too.

**Comment by pauldambra** [comment]
I'll work up a list of what is supported...

**Comment by joethreepwood** [comment]
This is actually a really fascinating idea, linguistically.

I can't foresee a list of all the possibilities, but what it looks likes we're doing is basically shifting from a subject-verb-object structure ("Joe listened to The Weakerthans") to a object-verb-subject structure ("To The Weakerthans, Joe listened."). 

The tricky thing is that this inherently shifts us to the passive voice, which is always harder to parse and less impactful (see: [point four](https://expresswriters.com/guide-on-flesch-kincaid-readability)). It's nearly always best to stay in the active voice and the SVO structure (in English), so that the subject (basically: the thing which is the focus of the sentence and which controls the verb) is framed first. 

However I can absolutely see the line of thinking that the subject here isn't the person, but the changed item. That's the focus of the reader, not who it was that made the change. But you can't use that easily in a sentence structure without slipping into passive voice or hard-to-parse sentences. It's actually a really exciting thing to consider, if you're a word-nerd. 

There are a few possible solutions to strike a balance here. The best may be to use a structure which frames the users' focus (the changed item) ahead of the main sentence to give context while sticking to an SVO structure or expanding into detail. 

This would essentially mean changing from  "person did a thing, did a thing, and did a thing on the item being tracked" to "Item being tracked: Person did a thing, did a thing and did a thing" instead of "On item being tracked, person did a thing, did a thing and did a thing."

**Comment by pauldambra** [comment]
We currently show activity log for 

* feature flags
* insights
* persons

We can show the activity log in the context of a single `thing` or all `thing`s and it currently tries to treat them both the same so always says "did this change **on identifier or link to thing**" (currently we show single Person changes, all feature flag changes, and all Insight changes)

Sometimes in the UI and generally in the API we allow mutliple things to change at once. So we need to be able to say "Someone changed one-thing to blah, added the other thing, removed a third thing, and fangled a fourth in tracked-thing-15"

| tracked thing 	|                                                     change                                                    	|                                                       display                                                       	|
|---------------	|:-------------------------------------------------------------------------------------------------------------:	|:-------------------------------------------------------------------------------------------------------------------:	|
| Person        	| someone changed a property in the UI  (processed async so can't say what  was changed without fancy fangling) 	| "Paul edited this person's properties"                                                                              	|
| Person        	| merged people                                                                                                 	| Paul merged people into this person: id-one, id-two, and id-three                                                   	|
| Person        	| split people                                                                                                  	| Pau split this person into: id-one, id-two, and id-three                                                            	|
| Person        	| deleted                                                                                                       	| Paul deleted the person: the-persons-id                                                                             	|
| Feature Flag  	| description                                                                                                   	| Paul changed the description to its-new-value on the-flag-key                                                       	|
| Feature Flag  	| enabled or disabled                                                                                           	| Paul enabled the-flag Paul disabled the-flag                                                                        	|
| Feature Flag  	| changed rollout conditions (this has a few different variants  - pun intended)                                	| Ben changed the filter conditions to apply to 100% of cohort-name,  and removed 1 release condition on the-flag-key 	|
| Feature Flag  	| soft deleted                                                                                                  	| Paul deleted the-flag-key (nb no colon)                                                                             	|
| Feature Flag  	| changed flag key                                                                                              	| Paul changed flag key from $original on $new                                                                        	|
| Feature Flag  	| enabled experience continuity                                                                                 	| (currently not clear) -> Paul enabled  should be -> Paul enabled experience continuity on the-flag-key              	|
| Feature Flag  	| created                                                                                                       	| Paul created the flag: the-flag-key                                                                                 	|
| Feature Flag  	| hard deleted in the API                                                                                       	| Paul deleted the flag: the-flag-key (nb colon)                                                                      	|
| Insight       	| created                                                                                                       	| Paul created the insight: insight-name                                                                              	|
| Insight       	| hard deleted in the API                                                                                       	| Paul deleted the insight: insight-name (nb colon)                                                                   	|
| Insight       	| changed name                                                                                                  	| Paul changed the name to "new-name" on new-name                                                                     	|
| Insight       	| soft deleted                                                                                                  	| Paul deleted the-insight                                                                                            	|
| Insight       	| changed short id  (probably only possible via API)                                                            	| Paul changed the short if to "new-value" on insight-name                                                            	|
| Insight       	| changed of derived name (by changing filters without  setting a name)                                         	| Paul changed the name to "new-name" on new-name                                                                     	|
| Insight       	| changed description                                                                                           	| Paul changed the description to "description" on insight-name                                                       	|
| Insight       	| favorite or un-favorite                                                                                       	| Paul (un-)favorited insight-name                                                                                    	|
| Insight       	| changed tags (the UI restricts this  to one at a time but the API allows multiple)                            	| Paul added the tags <new-1> <new-2>, and removed the tags <old-3> <old-4>                                           	|
| Insight       	| adding to a dashboard                                                                                         	| Paul (added to removed from) dashboard dashboard-name insight-name                                                  	|
| Insight       	| exporting insight to PNG                                                                                      	| Paul exported the insight insight-name as a PNG                                                                     	|

The only thing not in that list is when someone changes the settings for an insight... Which I don't think we should describe as a sentence because we already have the insight card description that we can add

Screenshot 2022-06-28 at 14 21 19

Maybe the simplest is (as @mariusandra suggested)

We say "Someone changed the details on insight-name" and below that show the card describing those details

**Comment by joethreepwood** [comment]
So, it would seem to me like the simplest way to strike a balance between the desire for an SVO order and the user need of having a way to focus would be this approach:

```
[Tracked Thing]: [Subject] [Verb] [Object]
[Tracked Thing]: [Subject] [Verb] [Object], and [Object 2]
[Tracked Thing]: [Subject] [Verb] [Object], and [Object 2]
[Tracked Thing]: [Subject] [Verb] [Object], [Object 2], and [Object 3]
```

This would mean, for example:

```
Feature Flag: Paul enabled [FlagKey]
Insights: Paul deleted [InsightName]
```

There are a few places where the verb would have to be longer, or some extra construction is needed, but these should be obvious. E.g. `Person: Paul split [UserID] into [ID1], [ID2], and [ID3]`

And there are a few places where I think we can make things simpler by omitting a tiny bit of information (which is clickable anyway):

- `Paul changed flag key from [OldKey] on [NewKey]` to `Feature Flag: Paul changed [OldKey] to [NewKey]` 
- `Paul changed the description to [NewValue] on [FlagKey]` to `Feature Flag: Paul changed the description on [FlagKey]`
- `Paul created the insight [InsightName]` to `Insight: Paul created [InsightName]`

A full list would be: 

| tracked thing | change                                                                                                      | Before                                                                                                             | After                                                                                                                    |
|---------------|-------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------|
| Person        | someone changed a property in the UI (processed async so can't say what was changed without fancy fangling) | Paul edited this person's properties                                                                               | Person: Paul edited [UserID]'s properties.                                                                               |
| Person        | merged people                                                                                               | Paul merged people into this person: id-one, id-two, and id-three                                                  | Person: Paul merged [ID1], [ID2], and [ID3] into [UserID].                                                               |
| Person        | split people                                                                                                | Pau split this person into: id-one, id-two, and id-three                                                           | Person: Paul split [UserID] into [ID1], [ID2], and [ID3].                                                                |
| Person        | deleted                                                                                                     | Paul deleted the person: the-persons-id                                                                            | Person: Paul deleted [UserID].                                                                                           |
| Feature Flag  | description                                                                                                 | Paul changed the description to its-new-value on the-flag-key                                                      | Feature Flag: Paul changed the description on [FlagKey].                                                                 |
| Feature Flag  | enabled or disabled                                                                                         | Paul enabled the-flag Paul disabled the-flag                                                                       | Feature Flag: Paul enabled [FlagKey].                                                                                    |
| Feature Flag  | changed rollout conditions (this has a few different variants - pun intended)                               | Ben changed the filter conditions to apply to 100% of cohort-name, and removed 1 release condition on the-flag-key | Feature Flag: Paul changed filter conditions to apply to 100% of [Cohort], and removed 1 release condition on [FlagKey]. |
| Feature Flag  | soft deleted                                                                                                | Paul deleted the-flag-key (nb no colon)                                                                            | Feature Flag: Paul deleted [FlagKey].                                                                                    |
| Feature Flag  | changed flag key                                                                                            | Paul changed flag key from $original on $new                                                                       | Feature Flag: Paul changed the flag key on [OldKey] to [NewKey].                                                         |
| Feature Flag  | enabled experience continuity                                                                               | (currently not clear) -> Paul enabled should be -> Paul enabled experience continuity on the-flag-key              | Feature Flag: Paul enabled experience continuity on [FlagKey].                                                           |
| Feature Flag  | created                                                                                                     | Paul created the flag: the-flag-key                                                                                | Feature Flag: Paul created [FlagKey].                                                                                    |
| Feature Flag  | hard deleted in the API                                                                                     | Paul deleted the flag: the-flag-key (nb colon)                                                                     | Feature Flag: Paul deleted [FlagKey].                                                                                    |
| Insight       | created                                                                                                     | Paul created the insight: insight-name                                                                             | Insights: Paul created [InsightName].                                                                                    |
| Insight       | hard deleted in the API                                                                                     | Paul deleted the insight: insight-name (nb colon)                                                                  | Insights: Paul deleted [InsightName].                                                                                    |
| Insight       | changed name                                                                                                | Paul changed the name to "new-name" on new-name                                                                    | Insights: Paul renamed [OldName] to [InsightName].                                                                       |
| Insight       | soft deleted                                                                                                | Paul deleted the-insight                                                                                           | Insights: Paul deleted [InsightName].                                                                                    |
| Insight       | changed short id (probably only possible via API)                                                           | Paul changed the short if to "new-value" on insight-name                                                           | Insights: Paul changed the short ID to [NewID] on [InsightName].                                                         |
| Insight       | changed of derived name (by changing filters without setting a name)                                        | Paul changed the name to "new-name" on new-name                                                                    | Insights: Paul renamed [OldName] to [InsightName].                                                                       |
| Insight       | changed description                                                                                         | Paul changed the description to "description" on insight-name                                                      | Insights: Paul changed the description on [InsightName].                                                                 |
| Insight       | favorite or un-favorite                                                                                     | Paul (un-)favorited insight-name                                                                                   | Insights: Paul unfavorited [InsightName].                                                                                |
| Insight       | changed tags (the UI restricts this to one at a time but the API allows multiple)                           | Paul added the tags , and removed the tags                                                                         | Insights: Paul tagged [InsightName] as [Tag], [Tag2], and [Tag3].                                                        |
| Insight       | adding to a dashboard                                                                                       | Paul (added to removed from) dashboard dashboard-name insight-name                                                 | Insights: Paul added [InsightName] to [DashboardName].                                                                   |
| Insight       | exporting insight to PNG                                                                                    | Paul exported the insight insight-name as a PNG                                                                    | Insights: Paul exported [InsightName] as a PNG.                                                                          |

Definitely interested in feedback on this, as I may have made some painful assumptions!

**Comment by pauldambra** [comment]
@joethreepwood that is amazing 🙌 

I'll absorb and implement that next week

**Comment by pauldambra** [comment]
## Insight changes first part

Screenshot 2022-07-31 at 13 40 49

## Insight changes last part

 Screenshot 2022-07-31 at 13 41 01
 
## Feature flag changes

Screenshot 2022-07-31 at 10 44 13

## Person changes

Screenshot 2022-07-31 at 10 21 34

**Comment by pauldambra** [comment]
@joethreepwood see comment above for changes... work for you?

**Review by benjackwhite — APPROVED** [review]
Looked through with a _relatively_ close eye and didn't see anything to comment on 👍

**Review by joethreepwood — APPROVED** [review]
Can't comment on the code, but the words make sense so it's a thumbs up from me. Merge when ready!

**Pull request merged**
