### PR TITLE
perf(events): add index on distinct_id for postgres Event model

### PR DESCRIPTION
**Pull request by hazzadous**
UPDATE: just add docs on the existing index added as a manual migration.

~~We're using this to join onto person distinct ids in lots of places so this really should be indexed. There is almost certainly a better composite index here however.~~

~~Of interest here also is that we create the index concurrently, so as not to block the `./manage.py migrate` command~~

~~Relates to https://github.com/PostHog/posthog/issues/5519 although I have yet to
look into if this is a resolution to the issue specifically.~~

~~There are likely other perf improvements here that I'll do as a followup pr, but this seems like a cross cutting improvement which doesn't require too much introspection into the querying logic.~~

~~The specific query for #5519 looks like this, from looking `pytest posthog/api/test/test_insight.py -k test_insight_funnels_basic_post`:~~

```
SELECT "posthog_person"."uuid",
    "posthog_person"."created_at",
    "posthog_person"."team_id",
    "posthog_person"."properties",
    "posthog_person"."is_user_id",
    MIN("step_0"."step_ts") as "step_0",
    MIN("step_1"."step_ts") as "step_1"
FROM (
        SELECT "pdi"."person_id",
            MIN("posthog_event"."timestamp") AS "step_ts"
        FROM posthog_event
            JOIN posthog_persondistinctid pdi ON pdi.distinct_id = posthog_event.distinct_id
        WHERE (
                "posthog_event"."timestamp" >= '2020-10-08T00:00:00+00:00'::timestamptz
                AND "posthog_event"."timestamp" <= '2020-11-15T13:10:40.739763+00:00'::timestamptz
                AND "posthog_event"."event" = 'user signed up'
                AND "posthog_event"."team_id" = 2
            )
        GROUP BY "pdi"."person_id"
    ) step_0
    LEFT JOIN LATERAL (
        SELECT "pdi"."person_id",
            MIN("posthog_event"."timestamp") AS "step_ts"
        FROM posthog_event
            JOIN posthog_persondistinctid pdi ON pdi.distinct_id = posthog_event.distinct_id
        WHERE (
                "posthog_event"."timestamp" >= '2020-10-08T00:00:00+00:00'::timestamptz
                AND "posthog_event"."timestamp" <= '2020-11-15T13:10:40.739763+00:00'::timestamptz
                AND "pdi"."person_id" = "step_0"."person_id"
                AND "posthog_event"."event" = 'user did things'
                AND "posthog_event"."team_id" = 2
                AND "posthog_event"."timestamp" >= "step_0"."step_ts"
            )
        GROUP BY "pdi"."person_id"
    ) step_1 ON TRUE
    JOIN posthog_person ON posthog_person.id = "step_0".person_id
WHERE "step_0".person_id IS NOT NULL
GROUP BY "posthog_person"."uuid",
    "posthog_person"."created_at",
    "posthog_person"."team_id",
    "posthog_person"."properties",
    "posthog_person"."is_user_id"
```

### CODE REVIEW

**Review by EDsCODE — COMMENTED** [review]
Would be useful to have some sort of benchmarking to demonstrate improvement here. Also, goign to tag @fuziontech to review for any side effects with adding an index concurrently

**Comment by hazzadous** [comment]
Cool thanks @EDsCODE , I haven't managed to do any benchmarking for this locally. I guess as long as it doesn't slow down the ingest too much, or take up too much space there can't be that much that can go wrong :famouslastwords:

Note there is also a follow PR that also adds an extra filter that I've verified does improve performance: https://github.com/PostHog/posthog/pull/5997

For what it's worth, here are the docs on create index concurrently: https://www.postgresql.org/docs/9.1/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY

**Comment by fuziontech** [comment]
Creating an index concurrently to our DB should be fine right now. We are really not too pressured on IO or CPU at the moment so fire away! 🚀 

Though, do keep an eye on it and it may take some time to complete. Curious to see how long it takes since we haven't done this in a bit.

Edit:
Just noticed this is for `posthog_events`! This should be fine since if anything it is improving performance for those who haven't migrated to ClickHouse version of PostHog yet. To be frank though I wouldn't spend much time on improving this since we are really trying to get people to migrate off of Postgres backed PostHog and onto ClickHouse backed PostHog.

**Comment by hazzadous** [comment]
> Edit:
> Just noticed this is for `posthog_events`! This should be fine since if anything it is improving performance for those who haven't migrated to ClickHouse version of PostHog yet. To be frank though I wouldn't spend much time on improving this since we are really trying to get people to migrate off of Postgres backed PostHog and onto ClickHouse backed PostHog.

Yes not high priority. I'm just picking up from a list of perf related tickets. This is a super easy change and potentially quite good perf improvements. I'm surprised there wasn't an index on this already!

**Comment by hazzadous** [comment]
@EDsCODE turns out there was already a manual migration in here. Worth adding in for the comments anyway?

**Pull request merged**
