### PR TITLE
chore(ci): skip fe when no changes

### PR DESCRIPTION
**Pull request by pauldambra**
[This comment](https://github.com/PostHog/posthog/pull/18661#discussion_r1395324870) on #18661 made me wonder: "Can we skip FE tests entirely?"

If only the backend changes we still run the FE CI which can't fail since it has had no changes and has no integration tests, so we can skip it...

# requrired jobs being reported as successful when skipped

Screenshot 2023-11-16 at 09 30 40

### CODE REVIEW

**Comment by pauldambra** [comment]
@marandaneto your comment on the other PR made me wonder about why we run the FE checks at all for every PR.

We could run the toolbar check on a subset of these but it's pretty fast...

Whereas this change saves c3m30s for every PR with no FE changes.

We can leave this as draft until Monday - this kind of change always has unintended consequences and there's no rush 😅

**Comment by marandaneto** [comment]
> @marandaneto your comment on the other PR made me wonder about why we run the FE checks at all for every PR.
> 
> We could run the toolbar check on a subset of these but it's pretty fast...
> 
> Whereas this change saves c3m30s for every PR with no FE changes.
> 
> We can leave this as draft until Monday - this kind of change always has unintended consequences and there's no rush 😅

It's OOO time @pauldambra go bake a pizza and share pizzaporn pics :D

**Review by Twixes — COMMENTED** [review]
Makes a ton of sense, I think we only haven't done this before because we weren't using `dorny/paths-filter` and ran into the skipped runs clashing with required checks. Commented with a couple improvement suggestions before we merge this

**Review by marandaneto — APPROVED** [review]
👍 for using `dorny/paths-filter`, the `filters` I'll let someone else review since I never worked on this codebase.

**Review by Twixes — APPROVED** [review]

**Pull request merged**
