### PR TITLE
Update event/property key info with groups and recording IDs

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Fixes the `$foo`s:
| Before | After |
| --- | --- |
| Zrzut ekranu 2021-12-7 o 12 00 51 | Zrzut ekranu 2021-12-7 o 12 16 17 |

Not sure what to do about `$group_${i}` though… Ideas?

### CODE REVIEW

**Comment by macobo** [comment]
IIRC we had a "hidden properties" feature here. I'd hide all of these as they're not useful for clients. Related: https://github.com/PostHog/posthog/pull/7328/files

**Comment by Twixes** [comment]
That's an interesting point, thanks. I agree that window or session IDs should be hidden, but as for groups, while I don't think these don't belong on the property definitions page, I believe they should still be shown. If someone is inspecting an event, I think it's quite valid for them to be interested what groups this event is associated with. Maybe the ugly `$group_${i}` and `$groups__${type}` properties should be hidden though.

**Comment by macobo** [comment]
Given that none of them are assigned by the users, aren't really "queryable" in a semantic sense for users, it makes sense to hide them.

I would have also hidden them as part of groups project on this page, but didn't realize to add it to the task list. Happy to do this in a follow-up if you wish.

**Comment by Twixes** [comment]
Alright, hid the pretty-much-only-internal `$session_id`, `$window_id` and `$group_{0,1,2,3,4}`. I'll leave `$groups` and the `$groupidentify`-only `$group_set`, `$group_key` and `$group_type` shown since they're human readable and someone could definitely be interested in those in event details (I would).

**Review by macobo — APPROVED** [review]

**Pull request merged**
