### PR TITLE
Build frontend separately from backend in `production.Dockerfile`

### PR DESCRIPTION
**Pull request by hazzadous**
## Changes

Instead of having the frontend build depend on previous backend build steps, we can build the frontend dist folder in parallel. This should make it easier to avoid having unnecessary node deps in the final image, as well as speed up builds through both parallelism and reduced cache invalidations.

The concrete reason that led me here is that we are holding off installing node dev dependencies e.g. [cypress](https://github.com/PostHog/posthog/pull/6580) . i.e. production concerns are affecting local development, which would be a great link to break. This may not actually be the simplest solution

TODO: check that we can't just ensure that node build deps are added and remove in the same layer

## How did you test this code?

CI should build and test 🤞

### CODE REVIEW

**Comment by hazzadous** [comment]
@guidoiaquinti have added this if it's useful?

**Comment by guidoiaquinti** [comment]
LGTM, I tried to keep the dev and prod dockerfile as close as possible but I think this is worth the complexity introduced.

**Comment by hazzadous** [comment]
> LGTM, I tried to keep the dev and prod dockerfile as close as possible but I think this is worth the complexity introduced.

hmmm. Yeah it may be that the speed / size improvements aren't worth the divergence 🤷 .

**Comment by hazzadous** [comment]
Probably not worth it unless the build is really long. Closing

**Comment by hazzadous** [comment]
@guidoiaquinti I just remembered why I initially added this. We're holding off adding cypress to the frontend dev deps because we're worried it will add to the image size. I'm not sure if that actually issue if we are to remove the `node_modules` folder in the same command/layer as we yarn install and build so I might just check that after you've merged your production.Dockerfile changes.

**Pull request closed without merging**
