### PR TITLE
chore: Update broken test snapshot

### PR DESCRIPTION
**Pull request by frankh**
## Problem

The tests are breaking in master - see https://github.com/PostHog/posthog/actions/runs/3915150172/jobs/6693019433

The snapshot has been broken since https://github.com/PostHog/posthog/commit/dc3e1ed9e3e52b05368706080cf38aa0215ba0ad

the diff is that there used to be a duplicate ```AND JSONExtractInt(x, 'data', 'source') = 2 AND JSONExtractInt(x, 'data', 'source') = 2``` which has now been fixed

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

```pytest posthog/clickhouse/test/test_schema.py```

### CODE REVIEW

**Comment by frankh** [comment]
@hazzadous  can approve me for CI? 🙏

**Comment by hazzadous** [comment]
> @hazzadous can approve me for CI? 🙏

For the remaining failures:

Container Images CI - not relevant to your changes. Looks like it doesn't work with contributor PRs maybe? cc @guidoiaquinti 
Visual regression I have seen failing on others, not relevant to your changes, I believe @thmsobrmlr is working on this
Backend CI / Django tests - suspect this is another one that is not working for contributor PRs. Not related to your changes.

**Review by hazzadous — APPROVED** [review]
Looks good. The failures afaict are unrelated to your changes.

**Comment by pauldambra** [comment]
Yep, I agree that the failures shouldn't be related to this change

@timgl do you have permission/happiness to merge this despite the failing tests?

**Pull request merged**
