### PR TITLE
Remove legacy code for previous insights’ UI

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

As the new insights UI experiment was successful and has been released to most people (https://github.com/PostHog/product-internal/issues/49), this PR removes all the legacy code from the previous insights components. In addition, this PR also removes the crosshair component from the lifecycle chart which is confusing.

Please don't be scared by the number of changed lines, the big change came from changing `{Insight}TabHorizontal.tsx` to `{Insight}Tab.tsx` and removing the old vertical layout.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Awesome! Looks good to me!

However, as you know, there was a case with the horizontal ui [having amnesia](https://github.com/PostHog/posthog/pull/4845) when saving user paths to a dashboard.

There are still some similar cases happening:
- https://github.com/PostHog/posthog/issues/4787 (cohorts - even the filter won't show "2 filters" if you add a cohort)
- From a support chat, no issue yet: "on the lifecycle tab I uncheck dormant for example, save to my dashboard, yet my dashboard still displays the dormant data"

Is this because of the new UI? Are we inviting trouble by removing the old one? 🤔 

Everything else that I tested worked for me after this PR though, so 🚢 🇮🇹 (ship it, get it, haha, I'm funny).

**Comment by paolodamico** [comment]
Well we're already using the new UI everywhere so I don't think it'll make a difference (though we should definitely address those cases). Will merge when tests pass. And 🤣

**Comment by mariusandra** [comment]
I think some of the test errors are legit. Cypress has been mostly running with the old UI, and some buttons moved around.

**Comment by paolodamico** [comment]
Test failures are definitely legit, will fix them later today

**Pull request merged**
