### PR TITLE
Revert "Change funnels API from GET to POST"

### PR DESCRIPTION
**Pull request by alexkim205**
Reverts PostHog/posthog#4602

### CODE REVIEW

**Comment by alexkim205** [comment]
The change from GET to POST happened on the frontend but backend didn't deploy which is why it was still serving up the old GET endpoint. Reverting to mitigate impact for now.

**Comment by timgl** [comment]
@alexkim205 I think we should just accept both POST and GET for this endpoint in general

**Comment by alexkim205** [comment]
Yup I agree, I discussed this with the team on Slack and decided that a major api change should be backwards compatible. Fix is still in the works!

**Comment by timgl** [comment]
Cool!

**Pull request merged**
