### PR TITLE
chore: Update base postgres to version 15

### PR DESCRIPTION
**Pull request by danielxnj**
## Problem

POstgres 12 is an old version and will lose support on AWS, so we are upgrading to pg 15.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Comment by xvello** [comment]
We do need to land this before upgrading cloud, but this will require a manual call to `pg_upgrade` for both the devenv and the hobby deploy, that we do need to document. Right now, the `posthog-db-1` container is failing with:

> 2023-08-23 14:30:25.062 UTC [1] FATAL:  database files are incompatible with server
> 2023-08-23 14:30:25.062 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.4.

There are third-party postgres images that do automatically run pg_upgrade, but I'm not sure we want to go there.

**Comment by danielxnj** [comment]
> 2023-08-23 14:30:25.062 UTC [1] FATAL: database files are incompatible with server
> 2023-08-23 14:30:25.062 UTC [1] DETAIL: The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.4.

This is getting really hard i have tried different approaches and the issue is that for the pg_upgrade we need both pg12 and pg15 binaries, and the alpine image does not let me have both versions.

Is this something we need to support and can people recreate the hobby deployment again?

cc @ellie @frankh

**Comment by danielxnj** [comment]
> > 2023-08-23 14:30:25.062 UTC [1] FATAL: database files are incompatible with server
> > 2023-08-23 14:30:25.062 UTC [1] DETAIL: The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.4.
> 
> This is getting really hard i have tried different approaches and the issue is that for the pg_upgrade we need both pg12 and pg15 binaries, and the alpine image does not let me have both versions.
> 
> Is this something we need to support and can people recreate the hobby deployment again?
> 
> cc @ellie @frankh

Another option is to have two containers running one for pg12 and another for pg15 and do the upgrade and switch the volumes, if is worth having this process i can try it tomorrow.

**Comment by xvello** [comment]
We could move forward for now by overriding the image in docker-compose.hobby.yml to pin hobby to 12 while we figure it out, but still run our tests on 15.

One low-effort way forward would be to switch to using [the pgautoupgrade image](https://github.com/pgautoupgrade/docker-pgautoupgrade) that's a drop-in replacement image that runs `pg_upgrade` if needed. Running with `pgautoupgrade/pgautoupgrade:15-alpine3.8` for the  db container got me a smooth upgrade path on a local devenv. 

Ideally we could run it once in [the upgrade-hobby script](https://github.com/PostHog/posthog/blob/08eab1f9c0be4931b73c56c6c5035a3278fe336d/bin/upgrade-hobby), or add a warning to run it manually with a one-liner example. cc @fuziontech as the person with the most context on the hobby deploy and the upgrade script.

**Comment by danielxnj** [comment]
> We could move forward for now by overriding the image in docker-compose.hobby.yml to pin hobby to 12 while we figure it out, but still run our tests on 15.
> 
> One low-effort way forward would be to switch to using [the pgautoupgrade image](https://github.com/pgautoupgrade/docker-pgautoupgrade) that's a drop-in replacement image that runs `pg_upgrade` if needed. Running with `pgautoupgrade/pgautoupgrade:15-alpine3.8` for the db container got me a smooth upgrade path on a local devenv.
> 
> Ideally we could run it once in [the upgrade-hobby script](https://github.com/PostHog/posthog/blob/08eab1f9c0be4931b73c56c6c5035a3278fe336d/bin/upgrade-hobby), or add a warning to run it manually with a one-liner example. cc @fuziontech as the person with the most context on the hobby deploy and the upgrade script.

I have pinned pg12 for the hobby deployment, please let me know how it looks for you.

**Review by xvello — APPROVED** [review]

**Pull request merged**
