### PR TITLE
Docker setup s3 minio and clickhouse backup server

### PR DESCRIPTION
**Pull request by tiina303**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Comment by tiina303** [comment]
Todo: test backup + restore path ... i.e. create some demo data, nuke Clickhouse (verify it's gone first) & then try to restore it

**Comment by tiina303** [comment]
Tried to test things and I'm running into some problems (both with Posthog and some simple test tables). Specifically only metadata gets stored, when I create the backup (the shadow folder doesn't exist, which is where it seems the data should be).

PS: clickhouse-backup only works with MergeTree engines ("Only MergeTree family tables engines" from the README in https://github.com/AlexAkulov/clickhouse-backup )
PPS: we can ignore the uploading to S3 and just work with the local backups (if we uploaded to S3 we could just later download it to local and backup from that). That upload and download seemed to work fine (with the metadata only need to test again later).

Run clickhouse, s3, chbk and create a test table
```
$ docker-compose -f ee/docker-compose.ch.yml up -d clickhouse s3 chbk
$ clickhouse-client -q 'CREATE DATABASE testing'
$ clickhouse-client -q 'CREATE TABLE testing.hits_v1 (EventDate Date, UserID UInt64, x String) ENGINE = MergeTree() PARTITION BY toYYYYMM(EventDate) ORDER BY (EventDate, intHash32(UserID)) SAMPLE BY intHash32(UserID)'
$ clickhouse-client -q "INSERT INTO testing.hits_v1 (*) VALUES ('2021-04-04', 5, 'just testing')"
$ clickhouse-client -q "SELECT * FROM testing.hits_v1"
2021-04-04      5       just testing
```

Running the `clickhouse-backup` commands with the cli in the docker container as it's a bit more verbose about errors compared to `curl` (also `curl` kicks of async so need to follow-up with status)
```
$ docker-compose -f ee/docker-compose.ch.yml exec chbk /bin/bash
bash-5.0# clickhouse-backup create --table testing.hits_v1 hits4
2021/05/12 18:41:34 debug create data               backup=hits4 operation=create table=testing.hits_v1
2021/05/12 18:41:34 debug   partition '202104'
2021/05/12 18:41:34 debug freezed                   backup=hits4 operation=create table=testing.hits_v1
2021/05/12 18:41:34 debug done                      backup=hits4 operation=create table=testing.hits_v1
2021/05/12 18:41:34 debug create metadata           backup=hits4 operation=create table=testing.hits_v1
2021/05/12 18:41:34  info done                      backup=hits4 operation=create table=testing.hits_v1
2021/05/12 18:41:34  info done                      backup=hits4 operation=create
bash-5.0# clickhouse-backup list
hits                  990B        12/05/2021 17:59:20   local
hits4                 990B        12/05/2021 18:41:34   local
2021-05-11T22-08-22   148.92KiB   11/05/2021 22:08:22   remote   tar
...
```
Note: we need to nuke the table otherwise we'll run into an error
```
bash-5.0#  clickhouse-backup restore hits4
2021/05/12 19:06:01 error can't create table 'testing.hits_v1': code: 57, message: Table testing.hits_v1 already exists.

$ clickhouse-client -q "DROP TABLE testing.hits_v1"
```
ok, so lets see if we can restore now, the table gets restored, but it's empty as we don't have a shadow directory
```
bash-5.0#  clickhouse-backup restore hits4
2021/05/12 19:08:25 debug found 1 tables with data in backup backup=hits4 operation=restore
2021/05/12 19:08:25 error can't restore 'testing.hits_v1': error during filepath.Walk for partition '202104_1_1_0': lstat /var/lib/clickhouse/backup/hits4/shadow/testing/hits_v1/202104_1_1_0: no such file or directory
bash-5.0# ls /var/lib/clickhouse/backup/hits4/
metadata       metadata.json
```

**Comment by Twixes** [comment]
What does this do? Will we end up using this in the future or can be closed?

**Comment by tiina303** [comment]
https://github.com/PostHog/vpc/issues/64 but it's not fully ready, we can close it for now, reprioritization happened

**Pull request closed without merging**
