### PR TITLE
feat: currency units choice

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

A user mentioned (in [this community slack thread](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1665077682468179)) that they expected to be able to choose currency as a unit

They reference Grafana which has a multi-level select with _many_options of units

## Changes

Screenshot 2022-10-11 at 18 50 32

* Adds inputs to add prefix or postfix for formatting
* Doesn't allow prefix and postfix at the same time

## How did you test this code?

running it locally and seeing it work

### CODE REVIEW

**Review by mariusandra — COMMENTED** [review]
Ahh... currencies. Having worked on a global p2p knowledge sharing marketplace, I have run into this.

This rabbit hole goes deep:

1. Not every currency is prefixed. If I'd have seen "kr200" during the glory days of the Estonian Kroon, I'd found it weird. It was "200kr" everywhere. Same with "200€", but there's "$200". 

2. Not every currency is displayed equally. Most have 2 digits after the comma (e.g. EUR), some have 3 digits ("TND") and then seeing two is just weird. Some have 0 (JPY).

image

3. Some have a local short format and a foreign short format. E.g. "C$200" for Canada when viewed from abroad... vs "$200" for Canada when you're in Canada.

These are all solvable problems, and worth building into an in house json db, instead of relying on some external package.

I would consider the prefix/postfix issue to be the only truly blocking one. As for the interface, well, it's kind of clunky... but we've done worse. We can always add more units and more select boxes inside select boxes later 😅

**Comment by pauldambra** [comment]
OK, broke some of the state by adding this to test. But we can base the conversion on the browser locale... (undefined _should_ have been doing this but 🤷 )

currency-based-on-browser-locale

**Comment by mariusandra** [comment]
I honestly don't understand this feature as it is. 🙃 

Why not just add two textfields "prefix" and "postfix", letting users enter whatever they want which then get appended to the numbers? Boom and done? Same effect, 10x less complexity?

As it's now, two things are still not clear:
- Prefix vs Postfix. I mentioned it in my last comment, but there is often a difference that will get locals riled up if you do it wrong. So let's not do it wrong.
- Why do we show the local formats if we don't use them, e.g. Estonian or Danish Kroons:

image

The real numbers should say "500 kr". Why's the "kr" there if we show "EEK 500" (it should also be "500 EEK").

The EEK is no longer a real currency btw and should be removed, though all the above works with DKK as well. There are likely other dead entries in the list.

I also don't understand why mention the Intl API At all in the comments? You're just looping a list of JSON values, what does the StackOverflow link add?

Finally, the UX is also clunky. Dropdown in a dropdown. Why not a dropdown for the other options and just currencies? Why not 50 different types of lengths?

Etc, etc...

So, like I said, I don't understand this feature as it is 🙃 😆

**Comment by pauldambra** [comment]
> Prefix vs Postfix. I mentioned it in my last comment, but there is often a difference that will get locals riled up if you do it wrong. So let's not do it wrong.
> Why do we show the local formats if we don't use them, e.g. Estonian or Danish Kroons:

@mariusandra what's the output for `window.navigator.language` for you?

We're delegating to 

```
value.toLocaleString(window.navigator.language, {
            style: 'currency',
            currency: axisFormat,
        })
```

Maybe `window.navigator.language` isn't the right thing to read

----------

```
I also don't understand why mention the Intl API At all in the comments? You're just looping a list of JSON values, what does the StackOverflow link add?
```

At some point we can remove the JSON mapping. 🤷 don't need to include the pointer for the future traveller

--------

What UI would you expect? "Not this" isn't actionable 😊 

E.g. google sheets presents a couple of currencies and lets you launch a modal to select others.

**Comment by mariusandra** [comment]
> > Prefix vs Postfix. I mentioned it in my last comment, but there is often a difference that will get locals riled up if you do it wrong. So let's not do it wrong.
> > Why do we show the local formats if we don't use them, e.g. Estonian or Danish Kroons:
> 
> @mariusandra what's the output for `window.navigator.language` for you?
> 
> We're delegating to
> 
> ```
> value.toLocaleString(window.navigator.language, {
>             style: 'currency',
>             currency: axisFormat,
>         })
> ```
> 
> Maybe `window.navigator.language` isn't the right thing to read

Definitely not. It's a random noisy mystery string that is loosely connected to the user's environment.

For me it's `'en-GB'`. I'm not in the UK. The language around me is not English, and I don't use the regal pound here.

Often people just set their computer's locale to `en` or `en-US`. Some people around me in this cafe have it set to `fr-BE` or `nl-BE`. However this is all just noise, since the PostHog App is in English... and why should the chart displaying your sales in EUR look different, if you're viewing it from Brussels (100€) or from Montreal (€100)?

Like I'm now saying for the third time: whether to use the prefix or the postfix depends on the currency, not whether you're looking at an English language website in a French or Japanese language browser.

> ```
> I also don't understand why mention the Intl API At all in the comments? You're just looping a list of JSON values, what does the StackOverflow link add?
> ```
> 
> At some point we can remove the JSON mapping. 🤷 don't need to include the pointer for the future traveller

I guess I just don't get what does the browser's local have to do with anything here 🤷 

> What UI would you expect? "Not this" isn't actionable 😊

The 4 options we had before, and a two textfields for "prefix" and "postfix"

**Comment by Twixes** [comment]
Big +1 to what Marius is saying with formatting.

**Comment by pauldambra** [comment]
(gifs updated in main description)

**Review by mariusandra — COMMENTED** [review]
Probably the last feedback here: it's hard to type more than one character 🤔

**Comment by pauldambra** [comment]
Ugh, yeah, valid... Now only closes on item click, press enter, or press escape

picker

**Review by mariusandra — APPROVED** [review]
Well, nothing really "blocking" anymore, but I think we should still debounce applying the local filter somehow. E.g. typing "EEK" shouldn't make 3 queries, but should either wait until I press enter or close the popup... 🤔 or just wait a good second or so.

**Pull request merged**
