### PR TITLE
Have migration task bypass pgbouncer and connect direct to pg for session stickiness

### PR DESCRIPTION
**Pull request by fuziontech**
This is in preparation for issue #4941 where we want to create an index concurrently that will exceed our statement_timeout time.

### CODE REVIEW

**Review by macobo — APPROVED** [review]

**Comment by tiina303** [comment]
is this applied immediately or do we need to update the sha too?

**Comment by macobo** [comment]
@tiina303 yup, the ecs task definitions are updated each cloud deploy

**Comment by tiina303** [comment]
I meant for self hosted, tied to the change to charts repo https://github.com/PostHog/charts-clickhouse/pull/93

**Comment by macobo** [comment]
This PR does not affect self-hosted in any way. This file is for ecs task definitions used by cloud only.

**Pull request merged**
