### PR TITLE
feat: Swapped to use KAFKA_HOSTS everywhere

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

We are adding another KAFKA_HOSTS (for session recordings) and this became messy when we had to handle KAFKA_URL _and_ KAFKA_HOSTS separately.

## Changes

* This pulls it all into one variable and tidies up the parsing logic.
* Also fixes some of the types in the config of plugin-server to make converting to Kafka config easier.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

https://github.com/PostHog/posthog/pull/16109
which allows
https://github.com/PostHog/charts-clickhouse/pull/747
which lets us update
https://github.com/PostHog/posthog-cloud-infra/pull/1757

### CODE REVIEW

**Comment by pauldambra** [comment]
@benjackwhite `frontend/src/scenes/notebooks/Notebook/SlashCommands.tsx` had snuck into this PR, I've removed it but we should check we don't accidentally merge in such an order that we remove that file and break things when we actually merge

**Review by pauldambra — APPROVED** [review]
LGTM

**Comment by pauldambra** [comment]
@hazzadous this is the first step in us adding a new kafka producer to capture. Could we get your 👀 ?

**Review by hazzadous — APPROVED** [review]
Looks ok. I feel like the tests should pick up if something was really wrong.

Maybe ensuring that env vars all specify two brokers, even if they are in fact the same might give a little more confidence.

**Pull request merged**
