### PR TITLE
chore: Allow using clickhouse 22.8

### PR DESCRIPTION
**Pull request by ellie**
## Problem
Migrations will not run because dev is running a too-new version of clickhouse. Didn't know we had this until it broke 😂 

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by guidoiaquinti — APPROVED** [review]
LGTM

Separately, should we bump the min supported version in the next release @macobo ?

**Comment by macobo** [comment]
The original issue (https://github.com/PostHog/posthog/issues/12967#issuecomment-1329097061) has this PR: https://github.com/PostHog/posthog/pull/12966 which does the appropriate changes, most of which are not included in this pr.

However chart-side work is not yet done right?

**Comment by ellie** [comment]
> The original issue (https://github.com/PostHog/posthog/issues/12967#issuecomment-1329097061) has this PR: https://github.com/PostHog/posthog/pull/12966 which does the appropriate changes, most of which are not included in this pr.

I see - would you be able to rebase your PR and get it merged?

> However chart-side work is not yet done right?

I'd like us to run the latest change on our own dev and then production environment before we push it out to everyone on the self-hosted side of things.

**Comment by ellie** [comment]
For context (after seeing all the edits on your post 😅), this PR was the result of the dev env breaking after testing the upgrade

And for additional context after seeing some of your other comments - we do not use the clickhouse image referenced in the chart, at all. Check [this file](https://github.com/PostHog/posthog-cloud-infra/blob/main/terraform/environments/aws-accnt-prod/eu-central-1/clickhouse.tf) for the definition of our EU clickhouse deployment

**Pull request merged**
