### PR TITLE
Pause polling when there are new events, restart it when they are shown

### LINKED ISSUE #8191: Event table does unneeded work in the background
## Bug description

When there are new events, events table displays this:

image

In the background, we continually continue polling our APIs

## Expected behavior

Pause once that banner is shown

## How to reproduce

1. Go to events

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @pauldambra and @mariusandra who have been doing work on this table recently.

### PR DESCRIPTION
**Pull request by pauldambra**
## Changes

For #8191 

This pauses background polling on the events table when we know there are new events, and restarts it when they are shown.

pause and unpause

## How did you test this code?

Adding unit tests and manually testing by viewing the network tab in the events table in different states

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
I don't think this takes into account "Automatically load new events"?

**Comment by pauldambra** [comment]
> I don't think this takes into account "Automatically load new events"?

Great catch 🙌

**Review by Twixes — APPROVED** [review]
I'm a bit wary of the "There are new events" button being a bit stale with this (as `newEvents` is filled up by `pollEventsSuccess`, in the usual case of events trickling in constantly it takes two clicks to get fully up to speed: first one to get the previous portion of the data plus to enable polling to get to the latest portion, second one to actually show the latest portion).
However, this shouldn't really be an issue, as I suppose someone really interested in watching the latest data stream in can just enable "Automatically load new events", and there are clear benefits to reducing the number of requests.

**Comment by Twixes** [comment]
Although maybe we could instead fix the situation with informing how many events will shown on click? After all, the code for that still is in https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/events/EventsTable.tsx#L116 as you noted @pauldambra. (If we stick to pausing polling though, the `EventsTable.tsx` part should be updated too, to avoid the potential UI inconsistency).

**Comment by Twixes** [comment]
After chatting with @macobo, it turned out that the impact of events polling on ClickHouse is indeed [pretty significant](https://posthog.slack.com/archives/C0113360FFV/p1643029704109900), so +1 for pausing polling.

**Pull request merged**
