### PR TITLE
fix(insights): fix funnel time to convert funnel steps

### LINKED ISSUE #16077: Custom name for all events isn't displayed
## Bug description

Renaming an "All events" series with a custom name doesn't currently work. Example insight where the second series was renamed to "Series B": https://app.posthog.com/insights/qn79d8Bu/edit.

## How to reproduce

1. Create a new funnel insight
2. Click "Add step" to add an "All events" series
3. Rename this series
4. Observe that the custom name is not displayed in the series row and in for the step

Screenshot_2023-06-15_at_13_01_03

The "All events" step probably shouldn't be displayed in grey as well.

## Additional context

Ping when fix is in:
- https://posthoghelp.zendesk.com/agent/tickets/3590
- https://posthoghelp.zendesk.com/agent/tickets/4490

### LINKED ISSUE #16282: Step picker for time-to-convert funnel does not display the "All events" option correctly
## Bug description

Step picker for time-to-convert funnel does not display the "All events" option correctly

## How to reproduce

1. Create a new funnel with "Time to convert" graph type and an "All events" step
2. Open the step picker select above the insight
3. Observe that the "All events" option isn't displayed correctly

Screenshot 2023-06-28 at 12 06 50

## Additional context

Potential fix:
```ts
export const entityNodeToFilter = (node: EventsNode | ActionsNode): EntityFilter => {
    if (node.kind === NodeKind.EventsNode) {
        return {
            type: EntityTypes.EVENTS,
            id: node.event === undefined ? null : node.event,
            name: node.name,
            custom_name: node.custom_name,
        }
    }

    return {
        type: EntityTypes.ACTIONS,
        id: node.id,
        name: node.name,
        custom_name: node.custom_name,
    }
}
```

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

The funnel steps filter and the funnel steps picker was broken for "all events". Resolves https://github.com/PostHog/posthog/issues/16077, resolves https://github.com/PostHog/posthog/issues/16282.

## Changes

This PR:
- fixes the funnel steps picker all events option (also removing a leftover $ from all steps)
- fixes the funnel steps all events option
- makes the all event option black in general

## How did you test this code?

Tested locally

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
Weirdly I still can't rename a newly-added funnel step until I switch it from the default "All events" to something else. (This includes switching to something else and then back to "All events" – then I suddenly can rename "All events")

**Comment by thmsobrmlr** [comment]
I linked the wrong issue 🙈 This one - https://github.com/PostHog/posthog/issues/16282 -  is fixed by this PR and the other issue with renaming funnel steps is indeed still present.

**Comment by thmsobrmlr** [comment]
Fixed #16077 in apology.

**Review by Twixes — APPROVED** [review]
Oh, well, everything works now!

**Pull request merged**
