### PR TITLE
Add save as button

### PR DESCRIPTION
**Pull request by timgl**
## Changes

- Add a "Save as" button that allows you to save any 'unsaved' (technically it reverts them) changes as a new insight instead
 
@clarkus This top bar is getting a little fussy, happy to grab any suggestions on how to improve this
image

## How did you test this code?

- e2e tests
- Save an insight, add a filter, click 'save as', see that you're now working on a copy

### CODE REVIEW

**Comment by clarkus** [comment]
This came up a few times before when working through saved insights. There is this idea of a save action that also considers the subsequent page shown after saving. For example, `Save` implies you'd save changes and then be taken back to the read view of that insight. `Save and keep editing` implies that you save changes and stay in the edit view. `Save as new insight` would act just the same as `Save` only it takes you to an entirely new context (the newly saved insight). In this case we're prioritizing the `Save` action over the others. Thoughts?

https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?node-id=577%3A1594

full template - no announcements or toggle

**Comment by timgl** [comment]
@clarkus Done!

@Twixes @mariusandra I just had a chat with Chris. We should really avoid rolling our own components as much as we can. Ant.d has a super well tested library of components, and I was able to build the 'New insights' button using ant.d in about 10 minutes. Before that I wasted an hour and a half trying to get the LemonButton to create the same functionality, running into all sorts of weird bugs and stuff I had to build myself.

image

**Review by mariusandra — CHANGES_REQUESTED** [review]
Found some issues, let me know if you'd like me/the team to have a look at them, or if you'll take them on. 

Point taken in any case: it's time to have a chat how far we go with the `lemon`ade. It's awesome for the menus and design, but I'm pretty sure we don't want to start redoing common antd elements.

The issues I found, and more comments below in the code:

- It's a bit broken when clicking "save" and when clicking the back button since we don't put the new insight's ID in the URL:


- According to [this comment](https://github.com/PostHog/posthog/pull/7174#issuecomment-970613396) after clicking the "Save as" button we should be taken back to "view" mode.

**Review by Twixes — COMMENTED** [review]
Well, the issue is that with AntD components this looks much different in the details than the style used in our mockups. We have less control over AntD components' style and behavior, so currently implementation looks like a bootleg version of Chris's designs with them. Though I'm fine with continuing to use AntD – let's just in this case design with AntD components from the get go.

**Comment by Twixes** [comment]
Also, curious what were the bugs @timgl? As far as I understand the feature, this should work without problems already (looks similar to e.g. pinned dashboards).

**Comment by timgl** [comment]
> Well, the issue is that with AntD components this looks much different in the details than the style used in our mockups. We have less control over AntD components' style and behavior, so currently implementation looks like a bootleg version of Chris's designs with them. Though I'm fine with continuing to use AntD – let's just in this case design with AntD components from the get go.

@Twixes Yes so this is what I was chatting to @clarkus  about. He was assuming that engineers would just pick whatever is easiest to implement, whereas engineers will see a mockup and think they need to implement a pixel perfect design. As an action Chris will start using standard ant.d components in his mockups. I also wanted to encourage you to push back against custom stuff if there's an ant.d thing we can use instead.

> Also, curious what were the bugs @timgl? As far as I understand the feature, this should work without problems already (looks similar to e.g. pinned dashboards).

I wasn't able to have the left side of the button do an action and the right side open the menu. I also wasn't able to position the button correctly because it had a mix of position:absolute and relative so at some point found myself setting the width of the button in pixels(!) to get it to work.

In general, we shouldn't try to innovate on buttons. Ant.d has solved this for us.


@mariusandra Thanks for the review! I'll try tackling this today/tomorrow.

**Comment by clarkus** [comment]
> @Twixes Yes so this is what I was chatting to @clarkus about. He was assuming that engineers would just pick whatever is easiest to implement, whereas engineers will see a mockup and think they need to implement a pixel perfect design. As an action Chris will start using standard ant.d components in his mockups. I also wanted to encourage you to push back against custom stuff if there's an ant.d thing we can use instead

To clarify my point of view - I don't have strong opinions about implementation, but I am going to diverge from antd patterns. My concern is that the UI looks and functions according to the designs, not how it is implemented. AntD is well documented so I will base my work on it as much as possible to encourage reuse, but there are going to be cases where things don't align. 

Antd is designed to be a framework and is solving for  broader framework problems. Our problem cases are sometimes different so I want to solve for those first without being constrained to only using antd components. 

I am working to document guidelines and component patterns to bridge the gap between antd and our needs. Hopefully that will help with consistency and code reuse.

**Comment by timgl** [comment]
>  I don't have strong opinions about implementation, but I am going to diverge from antd patterns. My concern is that the UI looks and functions according to the designs, not how it is implemented. AntD is well documented so I will base my work on it as much as possible to encourage reuse, but there are going to be cases where things don't align.

I think that makes sense! My worry is that engineers will treat your designs like they need to implement them pixel perfect, leading Michael spending half a day building a half-working new component, whereas we could have spent 15 minutes and gotten to 90% pixel perfect with a button that will continue to work perfectly and we don't need to maintain or modify ongoingly.

The way to get around that is working from standard ant.d components as much as possible and minimally modifying them where necessary.

**Comment by timgl** [comment]
@mariusandra 

> According to this comment after clicking the "Save as" button we should be taken back to "view" mode.

Ah I did misread that. However I much prefer staying in edit mode as I just actively made a copy of something so I probably want to make some more changes. I suggest leaving as is.

Ready for another look.

**Comment by clarkus** [comment]
If we do that we might consider dropping the idea of "save and keep editing" as an explicit choice in the menu. The redirect to the read mode was mostly meant to confirm that changes were saved and the insight exists. Generally 'save' and 'save as' should work the same, one just results in a new insight.

**Comment by timgl** [comment]
> If we do that we might consider dropping the idea of "save and keep editing" as an explicit choice in the menu. The redirect to the read mode was mostly meant to confirm that changes were saved and the insight exists. Generally 'save' and 'save as' should work the same, one just results in a new insight.

Done!

@mariusandra happy to merge?

**Review by mariusandra — COMMENTED** [review]
- The only thing I'd change before getting this in is to use `push` instead of `replace` when duplicating the insight, as then you could click "back" to the previous one, instead of losing it:


- It feels weird without a clear way to close edit mode now. Would going for a "Save and close edit mode" option make things too verbose? A cross somewhere else? We leave this for later? @clarkus 

- Also, the "discard changes" text doesn't seem to disappear after saving, but that feels out of scope for this PR.

**Comment by clarkus** [comment]
> It feels weird without a clear way to close edit mode now. Would going for a "Save and close edit mode" option make things too verbose? A cross somewhere else? We leave this for later? @clarkus

I don't think "save and keep editing" should be our default action. Saving and exiting the edit mode is how all our other CRUD workflows function right now (except dashboards). Having this one differ unexpected. If we want to support a "save and keep editing" option, let's not make it the default and make sure the button label is meaningful. The job to be done here is communicating what happens after save:

- **Save** - Save changes and exit edit view
- **Save and keep editing** - save changes and remain in edit view
- **Save as a new insight** - save changes as a new insight and edit the exit view

https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?node-id=577%3A1594

**Pull request merged**
