### PR TITLE
feat: add a fake status bar

### PR DESCRIPTION
**Pull request by pauldambra**
Mobiles have a status bar... so we should have one too!

Screenshot 2024-01-22 at 21 50 33

### CODE REVIEW

**Comment by marandaneto** [comment]
status bar and navigation bar were purposely ignored since they are OS features and it's not part of the app, we don't have access to its children, colors, etc.
We could add a new `type` and/or `inputType` for both of them, but that's all the info we have, if they are visible (which can be hidden), and sizes, but that's all.
A placeholder will be better than assuming the color and shape, would that help?

https://github.com/PostHog/posthog-android/blob/6665c47c368b256d92cf858f0a3156d8b2ebb583/posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt#L344-L346

**Comment by pauldambra** [comment]
> A placeholder will be better than assuming the color and shape, would that help?

I think we need something here. It all looks too flat and unbounded to me

**Comment by pauldambra** [comment]
Screenshot 2024-01-23 at 12 25 58

obeys provided status and navbar now

I kept the clock in showing the time of the full snapshot that renders it for a little exciting flair 🤣

**Review by marandaneto — APPROVED** [review]
Looking forward to test this out.

**Pull request merged**
