### PR TITLE
fix: PersonsModal feedback

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Fixes some feedback from @clarkus and brings the design closer to that in Figma

Needs https://github.com/PostHog/posthog/pull/11693

## Changes
* Removes the icons and positions buttons to match [Figma design](https://www.figma.com/file/XklcUpnAb8UYXJxVSZFNeI/Cohorts%2C-Persons-%26-Groups?node-id=28%3A3088) better 
* Updates style of expanded recordings to match the design better (content is not possible as we only have the Recording ID from the API currently)

Screenshot 2022-09-07 at 10 15 53
Screenshot 2022-09-07 at 10 19 58

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

**Review by pauldambra — APPROVED** [review]
LGTM

**Review by clarkus — DISMISSED** [review]
I made some changes in [figma](https://www.figma.com/file/XklcUpnAb8UYXJxVSZFNeI?node-id=28:3088#253350817) based on the feedback there. The component for viewing the list of recordings for a person in the set is a bit unclear in purpose. In the latest iteration in production, clicking this button acts as a proxy for expanding the result and navigating to the recordings tab (I think this is a great workflow). Because of the way it's working, I don't think the triangle icon really makes sense. Instead I think we should indicate the count of recordings for person. If there are more than one, we show `N recordings`. This would indicate the count and take you to the list where you can view each recording. If there is only one recording, the label would update to show `View recording` with a play icon to reinforce the play action. 

This way the button label is extra clear and easy to distinguish in each scenario, and it simplifies the component we're using. 

Screen Shot 2022-09-07 at 3 10 18 PM

Thoughts on this change?

**Comment by benjackwhite** [comment]
@clarkus I like this a lot 👍 Very clear that a single recording will actually play it. 

Screenshot 2022-09-08 at 09 56 54

**Comment by benjackwhite** [comment]
@clarkus merging this to unblock me. We can still follow up with more feedback if you have it 👍

**Pull request merged**
