### PR TITLE
Insight session entities

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- adds ability to specify what entities should be part of a session in calculating session insights (avg and distribution)
- This reuses the action/event selector to send parameters to backend for querying
- This feature will improve transparency in how sessions are determined and also reduce load on queries as the query won't attempt to iterate all events anymore

*If this affects the frontend, include screenshots.*  

## Checklist

- [x] add tests
- [ ] consider currently cached session objects

### CODE REVIEW

**Comment by EDsCODE** [comment]
Follows #3580

**Review by timgl — COMMENTED** [review]
Works fine. I find the interface a little confusion, because when you add more events the graph might not change, unlike all of our other Insights.

I did this locally, not sure it's quite right but I think we should make it clear this is a filter not a line graph.

image

**Comment by EDsCODE** [comment]
Yeah, you're right. Also, on first glance, this looks more like a filter for sessions with a specific event. @paolodamico Any thoughts on how to better message this? The idea here is that the user specifies a list of events/actions that will be used to determine a session

**Comment by Twixes** [comment]
I'd offer a suggestion but TBH it's not totally clear to me how this works.

**Comment by EDsCODE** [comment]
@Twixes for context: This isn't ideal but given we infer sessions from the data by querying for specific conditions rather than having preset sessions ids, we are trying to reduce the load on the query. Previously we did the query over all possible events because this would be the most comprehensive but that's been overloading high volume users. 

This PR is suggesting a change to allow users to define the events/actions that should be accounted for in calculating a session. So if you have '$pageview' set it will only use pageview events rather than every event to determine a session meaning the query will only be looking for pageviews in a 30 minute user window to calculate the session length

**Comment by Twixes** [comment]
Ah right, makes absolute sense to me, I confused myself actually because I thought this changes something else.
But I think it's OK the way it is, I'd just add "SESSION-DEFINING" before to "ACTIONS & EVENTS", with a tooltip to lay out the mechanics in case someone wonders if it's e.g. ORed or ANDed.

**Comment by EDsCODE** [comment]
How about this?

Screen Shot 2021-03-05 at 2 18 45 PM

**Comment by paolodamico** [comment]
Couple of ideas:
- We could add a small explanation text for this section as this departs from the usual behavior. Something like "Select the events that could comprise a session (e.g. a `$pageview`). You could use the same tooltip text but putting it directly as a caption.
- Definitely follow @Twixes point on adding the `OR` tags as we do for cohorts, FFs, ...

**Comment by paolodamico** [comment]
Re @EDsCODE update (sorry my previous comment came in after your changes),

- Think it's really worth adding the `OR` indicator



- Def not a big deal (not even 100% sure) but maybe moving the text from the tooltip to a caption directly below the title will nudge users to think about the events a bit more.

**Comment by Twixes** [comment]
Ping if/when up for review :)

**Comment by EDsCODE** [comment]
@paolodamico it looks too crowded to put the prompt directly here wdyt?

Screen Shot 2021-03-16 at 3 45 31 PM

**Comment by jamesefhawkins** [comment]
Could we just change the default filter to "all"? To make it clear it's every session. Then a little icon just in case that isn't intuitive.

**Comment by EDsCODE** [comment]
> Could we just change the default filter to "all"? To make it clear it's every session. Then a little icon just in case that isn't intuitive.

What's the default filter?

**Comment by paolodamico** [comment]
Agreed @EDsCODE, the tooltip thing would work best in this case. I think @jamesefhawkins means that by default we don't select any event, and then sessions are considered based on all events.

**Comment by EDsCODE** [comment]
I'd prefer to avoid the "all" notation as it would add some inconsistency to the actionfilter component. What do you think about shipping as is right now with the tooltip?

**Pull request merged**
