### PR TITLE
Routing for new data management tab

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Title says it all

## With FF

Screen Shot 2022-02-10 at 8 22 46 PM

Screen Shot 2022-02-10 at 8 22 52 PM

## Without FF

Screen Shot 2022-02-10 at 8 24 44 PM

## How did you test this code?

Toggle FF on and off. Make sure none of the routes break.

### CODE REVIEW

**Comment by mariusandra** [comment]
Not a full review, but all these pages seem empty. Can we make the old pages work instead of the empty pages for the time being? If the scope is to 100% redo also the action pages before getting this live, we're in for trouble. So I think we should reuse as much of the existing components inside this shell as possible...

Also, a "beta" or "alpha" or "dev" tag in the sidebar would be useful. :)

**Comment by alexkim205** [comment]
Thanks for taking a look! This revision brings in the old tables so that it doesn't look so empty. 

Note: going into action edit/view/create modes will use the old routes. Figured its not worth the time to change these to use the new urls if they're going to be replaced soon.

https://user-images.githubusercontent.com/13460330/154133278-f2e9ced3-2daa-4b6b-8f6f-627e0ef6c00a.mov

**Comment by mariusandra** [comment]
This does bring in some of the old pages, but you actually just reuse the old pages, and slap a different header on them depending on the flag or not? Keep the URLs exactly as they are. We can change them later if there's enough to fork the page content.

As an example of some issues with this PR with the flag on that comes from duplicating things:

**Comment by alexkim205** [comment]
> This does bring in some of the old pages, but you actually just reuse the old pages, and slap a different header on them depending on the flag or not? Keep the URLs exactly as they are. We can change them later if there's enough to fork the page content.

I think this is a good point in the project to think about how to organize these set of PRs to save headache in the future. My gut tells me that reusing the old pages now could overcomplicate things and create more work for us in the future. 

If we reuse the old routes these are likely the steps to get us to new urls + new scenes. Each bullet would be a separate PR.

```
1. Create new data management tab and point to old routes
2-4. Build new features on top of existing components with FF's (x3 for events, actions, properties)
5. When new components have changed enough split out old from new components into separate scene folders
6. Create new routes and redirect new components to new scenes
-- After full release --
7. Delete old events, actions, and properties folders + old routes.
```

All the while not breaking functionality of current actions, event stats, and property stats pages or messing up dev workflow in existing components. 

If we create new routes today:

```
1. Create new routes today and reuse EventVolume and PropertyVolume table components (maybe hide Actions tab for now)
2. Add new Actions tab + creation/editing flow
3. Redo EventVolume table
4. Redo PropertyVolume table
-- After full release --
5. Delete old events, actions, and properties folders + old routes.
```

Keeps old and new logics and components separate from the beginning and leaves less room for error.

Actions functionality is definitely a blocker for release, but for laying groundwork for new components, I think this PR as is (minus the Actions Tab) is a more straightforward path to where we want to get to. Do you think this is fine?

**Comment by mariusandra** [comment]
I'm just worried that what happened with #7938 could happen here again. Realistically you won't have time to finish any of these pages before the offsite, so there will be a lot of duplicated or "// TODO [draw the rest of the owl](https://knowyourmeme.com/memes/how-to-draw-an-owl)" code lingering around the codebase, confusing other people.

What about just building the new features scene by scene, and worrying about the routing, sidebars, tabs, etc later?

It's a bit of a fallacy to plan for the future like this. You're as capable of doing this work in the future as you're now, but doing it now just adds debt to the codebase that doesn't need to be there, right now. 🙃

**Comment by mariusandra** [comment]
Said differently,

image

**Pull request closed without merging**
