### PR TITLE
Fix shared dashboard loading

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Fixes [this bug](https://sentry.io/organizations/posthog2/issues/1921146315/?project=1899813&query=is%3Aunresolved+&statsPeriod=14d), we now don't attempt to load a bunch of stuff if the user is viewing a shared dashboard anonymously.

## How did you test this code?
Opened a shared dashboard in an incognito window, made sure only valid requests were sent and no request errors were logged to the console.

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
This solution works but is pretty dirty, relying on things like checking whether the request URL contains some string and silently returning empty results. Could we instead handle this more explicitly at a higher level, by avoiding the offending `api.get/update/etc.` calls in logics? E.g. to avoid calls to PATCH requests to the dashboard `/layouts` action, don't call `saveLayouts` in the `updateLayouts` listener if app context says `anonymous` (and annotate with a relevant comment to make this behavior clear).

**Comment by paolodamico** [comment]
Makes sense @Twixes, that was the original approach I went with, wanted to prevent future regressions but I agree it ends up in a dirty state. Ready for another look.

**Review by mariusandra — CHANGES_REQUESTED** [review]
This looks better than how it was before, though I'd still change some things. 

If we keep the logic as it is now, I'd suggest cleaning this up to something like:

```ts
// in some utils file
const isUserLoggedIn = () => !getAppContext()?.anonymous

// below in code
if (!isUserLoggedIn()) {
    return
}
```

However, can't we just simplify this even more to:

```ts
const isUserLoggedIn = () => !!getAppContext()?.current_user
```

It's not clear what extra information this `anonymous` field gives us.

All this said, I think there's even another angle to approach this from.

With both the `anonymous` code and the `current_user` simplification, if the user is logged in, then we still make a lot of extra API requests that the user doesn't care about. 

I'd advocate 🥑 that just like we keep dev & production consistent, we should keep the logged in and logged out experience the same for shared dashboards. 

Thus, perhaps the best place solve this is the entrypoint for the shared dashboard JS bundle, `frontend/src/scenes/dashboard/SharedDashboard.tsx`? Could we toggle some flag there, which will disable all these fetches, and would not be toggled in the regular `frontend/src/scenes/index.tsx` entrypoint?

**Comment by paolodamico** [comment]
Makes sense, did the refactor to use a global util, opted not to rely on `current_user` because we might set `no-preloaded-app-context` and then `current_user` would not be present even if the user is logged in. Agreed that the shared_dashboard refactor sounds better but I don't think it's worth spending more time on this for now.

**Pull request merged**
