### PR TITLE
Feature flags in the toolbar

### LINKED ISSUE #1996: Make feature flags toggleable in development/testing environments via toolbar
## Is your feature request related to a problem?

This idea comes from [this feeback] by customer: https://github.com/PostHog/posthog-js/issues/100#issuecomment-714896659

Specifically:

> PostHog is one of the few (possibly only) things that is unique to our production environment since it does not provide a way to test it without polluting production data. In hindsight, with this knowledge, more care on our end should have been taken before rolling out any updates to the PostHog client. I recommend others do the same.

This is 100% true and rather scary - we're making it hard to test what you write.

Our users need a solution for:
- Testing out feature flags locally w/o needing to use production posthog (due to data pollution, needing to hit production environments)
- Being able to toggle feature flags on-off in development/testing easily without it affecting other tests/developers

## Describe the solution you'd like

1. Add a `development: true` flag to posthog-js configuration
1. We don't ingest data while `development: true`
1. If in development mode, toolbar would have an additional tab: feature flags. 
    - It would list all previously used feature flags and a way to toggle them on-off
    - Toggling features there would only apply changes to your own local environment (via localstorage), not production/other devs
    - Toggling features should give immediate feedback in e.g. a react app
1. Levarage and document the solution used to store local flags and how to use it in feature/integration tests.

In addition, it would be cool if we (similar to stripe) always:
- created a development environment for every project
- switched to that when `development: true`. 
- allowed (optionally) to send data to the development environment via a toggle in the toolbar to allow testing our tracking

I would prefer not to store flags there though since it would mean one dev changing flags affected all others.

## Describe alternatives you've considered

- Promoting `posthog.featureFlags.override(...)` - this seems like a too low-level tool, might lead to surprises
- Documenting how to turn off all tracking in posthog-js in development

## Additional context

Notes:
- this does not address all problems from https://github.com/PostHog/posthog-js/issues/100, other actions required there
- not sure how to make this work for BE flags
- from experience, list of feature flags grows over time and they don't get pruned immediately. We might need a way to "persist" these defaults as well (development env?)
- I think this is immediately applicable to our own workflows -> dogfooding :dog: 

@timgl @paolodamico

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Edit: Depends on https://github.com/PostHog/posthog-js/pull/271

Some late night hacking to scratch my own itch.

100% WIP and very hacky (comes with reverted #3040), but can already do this:

Is this worth polishing into something real? :)

Resolves #1996.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by Twixes** [comment]
Depends on the effort, but seems pretty cool and useful to me. Not sure what the data on Toolbar usage is though.

**Comment by mariusandra** [comment]
I would really love to use this locally, but it's a bit more than just a quick hackathon project to get right. (Except, if, well, on a real hackathon... somewhere in Portugal?)

IIRC, the biggest blocker to get this running is that we can override feature flags, but then you only have overridden flags, and new flags don't show up in their default setting. Setting this and cleaning it up via posthog-js wasn't trivial, so I paused for now.

**Comment by paolodamico** [comment]
Keeping this open until Marius gets back.

**Comment by mariusandra** [comment]
Whoever wants can pick this up. I'd love to see it finalised, though haven't had the time/priority for this yet

**Comment by mariusandra** [comment]
Now that we have feature flags with variants #5725, ...

image

... I think this project should get a bit of a priority bump. I believe the toolbar is the best place to add a select-box to switch variants per flag, especially if you can see the changes live while testing/developing.

#hackathonideas

**Pull request closed without merging**
