### PR TITLE
Step 2: migration and use groups for filtering

### PR DESCRIPTION
**Pull request by timgl**

### CODE REVIEW

**Comment by Tannergoods** [comment]
When creating a funnel extra steps reduce the width of the drop down to select actions (this becomes very difficult to select.
Posthog

Funnels do not load after creation
Posthog

**Comment by timgl** [comment]
@Tannergoods Can you give this another go?

**Comment by Tannergoods** [comment]
Still an issue with creating funnels, if I want to move the order of the steps this will work the first time I move a step but then the second time I move a stage it will not let me put the steps in the right place.

Posthog

The step numbering should also change perhaps? this isn't as necessary as being able to move them.

When deleting a funnel it only removes off the list after refreshing the page

**Comment by timgl** [comment]
@Tannergoods Can you give this another go? Should be fixed now.

**Pull request merged**
