### PR TITLE
Sanitize `entity.math_property`

### PR DESCRIPTION
**Pull request by macobo**
Was refactoring related code and stumbled upon this issue. Yikes!

As I mentioned yesterday, it's a numbers game.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by neilkakkar — APPROVED** [review]
Indeed, yikes!

**Review by Twixes — APPROVED** [review]

**Review by Twixes — CHANGES_REQUESTED** [review]
Looking at test failures I think `entity.order` is not enough of a key (e.g. queries using a formula confuse entities because of this). Not sure TBH, but in any case a few query tests failing.
BTW could we validate `entity.order` in `Entity.__init__` just to be sure too? I.e. cast to `int` if not `None` – without that there's still a way to inject something into `value` (though a bit more tricky because would need to work with `params`).

**Comment by macobo** [comment]
I ended up going for a different (although also bad) approach - keeping track of how many times the function has been called.

Working with order is tricky - it's only used in backend for sorting, but nothing guarantees it's populated. Worse, we have two parallel arrays (actions vs events) which means we can't even default well to based on list position.

**Comment by Twixes** [comment]
Can't we populate `order` it in `EntitiesMixin.entities`?

**Comment by macobo** [comment]
We could, but we need to be careful there since frontend uses the "order" to determine what order to display things in, and `entities` is used to re-serialize the data.

All-in-all it feels like a refactoring _not_ worth doing - we're creating a close coupling between pieces of logic that should be isolated. 

Worse it doesn't solve the problem since some callsites create an entity directly - now we need to add defaulting there as well.

One way out is to have a separate property (e.g. uuid) in the entity, but IMO while ugly this is self-contained. If we see this logic repeated (get unique parameter name) elsewhere we can extract a function of it as well.

**Comment by macobo** [comment]
Merging for now, based on slack convo:

```
Karl
WDYT about getting the PR in for now? Just to get rid of vul, happy to have you follow up though :)

Michael Matloka
Should be alright
```

**Pull request merged**
