### PR TITLE
Fix zero trends metric

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Bug found in break the release where metric in trends is always 0. Not a super accurate way to calculate total rate, but better than what we have now.

Screen Shot 2021-10-18 at 7 42 20 AM

## How did you test this code?

*Please describe.*

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
👍

**Comment by neilkakkar** [comment]
How do you feel about hiding this value instead? Since the trends graph displays conversion values over time, a single value, without an explanation of what exactly it means, seems more confusing than it's worth? cc: @clarkus, Paolo  thoughts?

**Comment by clarkus** [comment]
> How do you feel about hiding this value instead? Since the trends graph displays conversion values over time, a single value, without an explanation of what exactly it means, seems more confusing than it's worth? cc: @clarkus, Paolo thoughts?

I'm not sure. We already answer this question in the other visualization option, so this might be redundant. I don't have a strong opinion.

**Comment by paolodamico** [comment]
I agree with @neilkakkar, even with this fixed I don't know what this number is telling me, is it the average? I would remove it in this view. Wdyt @alexkim205 ?

**Comment by alexkim205** [comment]
I think it makes sense to remove it for now. It's more confusing and the trends graph as a whole is used more as a deeper dive from the metric shown in step trends.

**Pull request merged**
