### PR TITLE
1842 link to edit cohort

### PR DESCRIPTION
**Pull request by girlProg**
## Changes

you can now view/edit a cohort filter by clicking on the **View** button beside the selected cohort.
Opens in new tab
Screenshot 2020-12-07 at 22 30 05

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Comment by EDsCODE** [comment]
Hi @girlProg! Thanks for this. Looks like our e2e pipeline is being flaky as your addition should be clear from these tests. I'll rerun the pipeline and get it merged afterwards!

**Comment by girlProg** [comment]
hey @EDsCODE, you're welcome :) 
I was starting to wonder how the tests were failing. Great then. Thanks!

**Comment by girlProg** [comment]
@EDsCODE not sure but they all seem to be failing over (the same?) assertion ?
Screenshot 2020-12-07 at 23 29 15

**Comment by paolodamico** [comment]
If you merge master and push again, tests will pass correctly.

**Comment by girlProg** [comment]
> If you merge master and push again, tests will pass correctly.

@paolodamico sorry does this require a new pull request? as this PR is referencing the branch not master

**Comment by paolodamico** [comment]
Hey @girlProg, no new PR needed, just do git fetch && git merge master, push and you should be good to go.

**Comment by paolodamico** [comment]
Will merge now because failing test is unrelated and already fixed in #2674. Thanks for the contribution @girlProg, please be sure to email yakko[at]posthog{.}com to get some official PostHog merch 😄

**Comment by girlProg** [comment]
oh great! did the merge the other way around and couldn't seem to undo the merge. yay! will definitely send the email. thank you for the help!

**Pull request merged**
