### PR TITLE
Proposed cleanup of events table column configurator

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

I love the new ability to configure columns in the events table. This is my proposal to polish it even further.

#### Before

It works :tada: _but_ button capitalization is inconsistent, checkboxes in this case act more like add/remove buttons instead of on/off switches (by disappearing), there's a bit of excessive whitespace, and the modal appears smoothly but disappears instantly.

#### After

Simpler UI code and a bit more intuitive UX. Also, I used "Customize" instead of "Configure", as that feels more applicable to me in this case – "Customize" is more about just the display aspect of the table, while "Configure" feels a bit more as if I were to adjust some system configuration.

## How did you test this code?

Used the UI like a person new to it (which I was).

### CODE REVIEW

**Review by pauldambra — CHANGES_REQUESTED** [review]
I don't think we should merge this without understanding how much we want to match current in figma

**Comment by clarkus** [comment]
That looks like a good change. Is column reordering in scope? Can I drag an item to a different position in the list? If so, then I think we might only bind the remove event to the icon and not the entire container. Otherwise that looks good to me.

**Comment by Twixes** [comment]
Merging with an okay from Chris (though no reordering as this is only some layout changes).

**Comment by pauldambra** [comment]
see #6523

**Comment by paolodamico** [comment]
Love these UI changes @Twixes! Cherrypicked

**Pull request merged**
