### PR TITLE
feat(hogql): Add funnels to paths insight

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

This PR builds upon https://github.com/PostHog/posthog/pull/21044 to add funnels to paths insights.

## Changes

Changes:
- Uses a `funnelPathsFilter` as schema key to hold all relevant params. Removes other params from the query schema and adapts `filterToQuery` functions to accomodate this.
- Uses a `toTimeZone(timestamp, 'UTC')` to fix issues with adding an interval and DST transitions.

## How did you test this code?

Verified the funnel path can be added and removed locally.

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Didn't review very deeply, but looks good overall

**Review by webjunkie — CHANGES_REQUESTED** [review]
For me it doesn't work anymore to go to the paths from funnels, e.g. by clicking "Show user paths after step". I suspect the URL with the filter is not converted correctly anymore. We can also discuss in standup what the status is here.

**Review by webjunkie — APPROVED** [review]
I was able to fix the issues and would merge this. Then we can check #20057 for tests and possibly fix leftover issues.

**Comment by thmsobrmlr** [comment]
> I was able to fix the issues and would merge this. Then we can check #20057 for tests and possibly fix leftover issues.

Awesome, go for it!

**Pull request merged**
