### PR TITLE
chore(storybook): update to 6.4 and add esbuild

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Upgrade storybook to 6.4
- Add a plugin to use as much esbuild as possible when building storybook
- It still goes through webpack, but is 10sec faster. Full build goes from 50sec to 40sec, launching the dev environment now takes 30sec.
- Fixed a few TS type-related exports that storybook complained about
- Replaced a few CSS rules it also complained about

## How did you test this code?

Ran storybook and made sure it still works as much as it did before.

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
The code style changes are nice, but I'm not feeling the effects of "turbo build". Build seems to take the same amount of time for me. 🤔

**Comment by mariusandra** [comment]
Two things that go in here:
- When running `yarn build-storybook`, I saw a 10sec improvement.
- Prior to 6.4 storybook would build everything inside one giant ".js" file. Now the app itself is code-splitted and thus loads much faster. This is regardless of esbuild.

**Comment by Twixes** [comment]
Hmm, I've always been running `yarn storybook`, what does `build-storybook` do differently?

**Comment by mariusandra** [comment]
It builds the bundle for production usage, including minification and other optimisations that esbuild now helps with.

**Review by Twixes — APPROVED** [review]
There indeed is a bit of an improvement for `build-storybook`.

**Pull request merged**
