### PR TITLE
fix(frontend): popover scrollbar css

### LINKED ISSUE #14517: UI of dropdown in Cohort is messed up
## Bug description
image

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. https://app.posthog.com/cohorts/new
2. click on "completed event" dropdown in the first matching criteria
3.

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

### LINKED ISSUE #14598: Dashboard can't scroll to date range option
## Bug description

*Please describe.*  
- when a dashboard only has 1 row of items, you can't scroll to the bottom of the date range picker
*If this affects the front-end, screenshots would be of great help.*  
Screen Shot 2023-03-07 at 8 27 13 AM

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. Make a dashboard with 1 or 2 items in a row
2. Click on date range
3. Try to get to the last option

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

### PR DESCRIPTION
**Pull request by mariusandra**
## Problem

Resolves #14517, resolves #14598.

## How did you test this code?

Visually in the browser. I did not add any automated tests. I'm also not sure what this change will break.

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
Thanks for fixing!

**Comment by mariusandra** [comment]
Is this a.... visual regression? 👀  https://github.com/PostHog/posthog/pull/14519/files#diff-239062d2954f9d888ad635bfaa5c46a95f9a682c77f6acc7f4cb6be9105d8385

**Comment by Twixes** [comment]
It was… fixed now!

**Comment by Twixes** [comment]
Looks like there's now some non-flaky issue in `events.cy.ts`... No idea what's the problem looking at the screenshots, I'll just run that locally to see what's what.

**Pull request merged**
