### PR TITLE
426-email-opt-in

### PR DESCRIPTION
**Pull request by Tmunayyer**
## Changes
Issue: #426 

- `Setup` tab now features a checkbox to opt in or out of feature/security updates
-  Team member signup features the same check box to opt in
-  Both locations "phone home" using `posthoganalyze.identify()`

Note: The only thing I deliberated on with the front end is the fact the new setting is using two different states (kea and local). Because of this its re rendering twice. It felt a bit out of scope to refactor this seeing as this probably wont be a feature used all that often and its not causing serious issue. At some point it would probably be best to standardize this and strictly use one or the other.

## Checklist
- [ ] Code reviewed
- [ ] QA'd

### CODE REVIEW

**Comment by timgl** [comment]
@Tannergoods If you fancy QA'ing this?

**Comment by Tannergoods** [comment]
This works fine and is clear to see if a user has opted in or out

We should change the language as the header could make a user tick to believe they are opting out

Posthog

It could read "Opt into email updates" or "Security and Feature Updates"

**Comment by timgl** [comment]
Yeah good catch, let's do "Security and feature updates" as the title @Tmunayyer

**Comment by Tmunayyer** [comment]
@timgl @Tannergoods Updated:

image

**Pull request merged**
