### PR TITLE
feat: Explore tab

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Proposing as a follow up / alternative to the "SQL Studio" area - Explore.

SQL Studio is sort of a "stateless" area for running arbitrary queries which you can then save as an insight when happy.
Similarly we have "Activity" (events) which is the same idea - explore your event stream and save as an insight if you want.
Finally we have the yet unreleased "Canvas" which is a scratchpad notebook that can be saved or simply shared via the url params.

In my view these are all common and should be grouped together as:
1. They are stateless and are a good entrypoint to finding something out
2. They each persist their state to the URL for simple sharing
3. They each allow you to jump out and save their "state" as a proper product area (Insight/Notebook)

## Changes

* Mostly does what I proposed here

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

**Comment by daibhin** [comment]
I really like this! Having `SQL Studio` as the new default on a tab that customers are familiar with feels like a great way to highlight its existence & promote it

**Comment by Gilbert09** [comment]
I'm pretty against having SQL Studio hidden away within Explore. SQL is one of the main platform surfaces of data warehouse and we want to make that easy to find. "Explore" doesn't really hint at what could be inside this page. I'd be much happier if SQL studio was a standalone nav item

**Comment by benjackwhite** [comment]
> I'm pretty against having SQL Studio hidden away within Explore. SQL is one of the main platform surfaces of data warehouse and we want to make that easy to find. "Explore" doesn't really hint at what could be inside this page. I'd be much happier if SQL studio was a standalone nav item

Is it "hidden"? - Explore makes it the first thing you see there _and_ you get to it from making a new insight. The only thing that is different is that it isn't explicitly called "sql" in the sidebar 🤔 I'm trying to balance this feature in combination with the rest of the platform.

**Comment by benjackwhite** [comment]
@Gilbert09 We could compromise and have "SQL studio" as a tab further down _as well_ as in the Explore tab. That way it has a prominent place in a nicely grouped area (Explore) as well as a less prominent space in the product area?

**Comment by Twixes** [comment]
I'm inclined to agree with Tom, in that SQL seems like a different user story from looking at the collection/stream of events. 

The trouble with "Explore" is that that can really mean _anything_. For example, it poses the question why are events supposed to be "explorable", whereas people are just "People". Then, product analytics is also about exploring the data, in a different way.
I really like the current label of "Activity" for events, because it's extremely obvious what's inside, and what's not. Similarly with "People", or "SQL studio".

**Comment by Twixes** [comment]
I also don't see Canvas being useful right now. It's basically the scratchpad Notebook but… not, and also less handy?

**Comment by Gilbert09** [comment]
> @Gilbert09 We could compromise and have "SQL studio" as a tab further down _as well_ as in the Explore tab. That way it has a prominent place in a nicely grouped area (Explore) as well as a less prominent space in the product area?

@benjackwhite I'd also be against having SQL editors in two places - we currently have that right now (product analytics and data warehouse) and it's a bit of a mess. We want one single place to write SQL.

> Is it "hidden"? - Explore makes it the first thing you see there and you get to it from making a new insight. The only thing that is different is that it isn't explicitly called "sql" in the sidebar 🤔 I'm trying to balance this feature in combination with the rest of the platform.

In this new world of no `Data Warehouse` tab, it's a product hidden away amongst other areas of the platform, which is why I'm a big advocate for having it's own prominent SQL Studio nav item

**Comment by benjackwhite** [comment]
> I also don't see Canvas being useful right now. It's basically the scratchpad Notebook but… not, and also less handy?

Not really - the shareability of it is the big thing. I've used it a fair bit (but with no one knowing it exists it is of course not particularly useful 😅

**Comment by benjackwhite** [comment]
Enough pushback that I'm happy to give up here and focus elsewhere (I would encourage you to consider the issues that this was trying to solve though...)

**Pull request closed without merging**
