### PR TITLE
fix(homepage): update logic for tracking when an insight is viewed

### PR DESCRIPTION
**Pull request by rcmarron**
## Problem

Insights from experiments could end up in the recent recordings list. These insights don't have titles and shouldn't really be in this list.

## Changes

This PR updates how we track when an insight is viewed for the recent insights list. It moves the logic from the `InsightContainer` (Used by experiments) to the insight scene (only used by normal insights).

## How did you test this code?

Verified locally that insights viewed on experiments are not tracked.

### CODE REVIEW

**Comment by Twixes** [comment]
Hmm, nowadays it shouldn't be possible to create new "unsaved" insights, since an insight is only created in the DB upon clicking "Save" and not upon clicking "New insight". Overall I don't think the `saved` value can really be relied upon.

**Comment by rcmarron** [comment]
> Hmm, nowadays it shouldn't be possible to create new "unsaved" insights, since an insight is only created in the DB upon clicking "Save" and not upon clicking "New insight". Overall I don't think the saved value can really be relied upon.

Yeah, I definitely agree with you. I couldn't figure out how it happened, but the insight `AJxZzEPW` was recently created, but it's not saved, so it is appearing in my recent insights list without a name. 

Any clues how that could've happened? @Twixes  

Probably better to fix it at the root if it's a case that shouldn't be happening at all.

**Comment by rcmarron** [comment]
Oooooo I see, insights created in an experiment aren't saved, but they still count as being viewed.

**Comment by Twixes** [comment]
Ohh, right. We should probably indicate insights created for experiments with something more like `experiment BOOLEAN` instead of relying on wonky `saved`.

**Comment by rcmarron** [comment]
> Ohh, right. We should probably indicate insights created for experiments with something more like experiment BOOLEAN instead of relying on wonky saved.

Yeah, that sounds like the right thing to do there. 

For the 'insight viewed' feature specifically, I think it was being a bit too lenient on what was considered an insight (I was tracking it at the `InsightContainer` level, when it should probably be tracked at the `scene` level). Just updated this PR to fix that.

**Comment by alexkim205** [comment]
Code looks good to me, but I'm confused by the objective of the PR. It looks like only event tracking usage is being changed here and not the way we're actually filtering for recently saved insights.

**Comment by rcmarron** [comment]
> Code looks good to me, but I'm confused by the objective of the PR. It looks like only event tracking usage is being changed here and not the way we're actually filtering for recently saved insights.

Oh oops, sorry, I never updated the description after the changes Michael suggested. Just updated that @alexkim205

**Review by alexkim205 — APPROVED** [review]
Thanks for the clarification, lgtm!

**Comment by mariusandra** [comment]
Every time an experiment is viewed, we create a new insight:


We probably don't need to save these ad-hoc insights into the database.

**Pull request merged**
