### PR TITLE
Toolbar Updates - Episode 3

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Here's another set of random small fixes for the toolbar. This PR can be merged at any time... however until it is, I'll keep adding stuff here (and make a `toolbar-fixes-quatre` branch if it's closed)

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
I also added the new logo here. This version is in the PR:

image

I also tried without the label, but I'm not sure if this looks better:

image

somehow it looks badly aligned due to its shape...

**Comment by lottiecoxon** [comment]
The logo looks slightly strange alignment wise, it would be fine to leave, but would you like me to draw up an icon/s for this?  More than happy to / would give a more personal feel to the toolbar. Let me know

**Comment by lottiecoxon** [comment]
If we are leaving them as is, the float icon is much smaller than the other two visuals - maybe we should make the other two slightly smaller within the circle.

**Comment by timgl** [comment]
@lottiecoxon Custom icons would be awesome and worth you having a go at this :) I also think the current circle is a bit big on the page. I was about to raise a PR that reduce its size by 30-50% so might be worth taking into account as well

**Comment by mariusandra** [comment]
@lottiecoxon definitely! If there's anything you find that you can improve, just go for it :).

Regarding the toolbar itself, in "button mode" we now have 4 circles: "toolbar", "float", "inspect" and "heatmap". Most likely "inspect" and "heatmap" will remain buttons like they are, but something might change with the "toolbar" and "float" buttons and how they work. (There will be an issue to discuss this soon)

In any case, we will anyway need one big button with the logo, no matter the label under it... so if you have ideas on how to improve it, please go ahead!

**Comment by mariusandra** [comment]
One point regarding the size of the icon. It can definitely be reduced a bit, yet we should keep in mind accessibility concerns. 

The 3 smaller buttons/icons (inspect/heatmap/float) are that size and with that alignment on purpose - they are big/comfortable enough to tap with your finger... and far enough that it's hard to tap the wrong one by accident. If I would add a fourth and fifth icon to the bunch, it would make all the rest too small to comfortably interact with on a small screen with thick fingers. 

Then, the icon with the logo is bigger than the 3 others just to add some visual hierarchy to the bunch. If it would be the same size or smaller, I fear it'll diminish this hierarchy. It'll still be obvious what is the "main button" from just the animation/logo, so I might be over thinking it.

**Comment by lottiecoxon** [comment]
does the main circle have to be the classic logo, could we experiment with other possibilities such as a hedgehog face or something a little more abstract with colours of the logo?

**Comment by timgl** [comment]
image

Maybe it's partly due to it's slighty odd random positioning on the page but our widget feels much more in the way (I've been tempted to X it on a couple of occasions(!)), definitely compared to my notion widget on the bottom right which has never really bothered me.

Maybe we should also attach it to the side of a window like that?

@lottiecoxon definitely in favour of having our own logo here so people recognise it. It might be nicer if we do something similar to motion (bottom right in screenshot) where it's a bit more square.

**Comment by lottiecoxon** [comment]
yes agreed - square would be better - plus maybe the square blocks would lend itself to the geometric illustrations we have so far. We could try making all the buttons rounded squares- I don't mind mocking both options up to see what works best

**Comment by mariusandra** [comment]
It can be square-ish as well. Here's an example that didn't take too long to make:

screencast 2020-06-26 17-12-13

It now looks a bit weird with all the other icons being full circles.

**Comment by lottiecoxon** [comment]
Untitled_Artwork 2 copy

**Comment by jamesefhawkins** [comment]
That was 18 minutes of work?!! Wow :)

**Comment by mariusandra** [comment]
So here's 5 min of (sloppy) work to make the icons extend to the left:

screencast 2020-06-26 18-11-37

Not pushing it live as there are several things to clean up here, but it can serve as inspiration.

In this mode we do have more space for more icons, so I'd just remove the "Toolbar" from the logo button and add "Dock" as the 4th icon... in case we decide to keep both float & dock.

**Comment by mariusandra** [comment]
@lottiecoxon can you share these icons with me somehow? Did you make them in figma?

**Comment by mariusandra** [comment]
All right, I couldn't help myself. Inspired by discussions today, I "experimented with code" and transformed the button to this:

screencast 2020-06-26 22-24-40

This code is not yet committed as it's a bit raw still.

This solves many issues we had previously:
- Clicking the logo button does nothing. You tap it to expand the buttons on a mobile device. With a mouse, the menu opens way before you even have a chance to click this button anyway. (We could have it show the posthog version when you click it 10 times a'la Android)
- I'll put the "actions" and "stats" tabs into simple draggable boxes (kind of like the float now, but prettier) that open when you click the buttons. Simple enough for now. (This is not yet done)
- We need to show the heatmap's ranked list in a similar window (what you see when you dock the toolbar). I'm still not sure where to put the button to open it. Perhaps it'll just open automatically when you click "heatmap"? Perhaps some button will appear? Perhaps you must drag the heatmap button out in order to reveal the window? More "experimenting with code" needed probably :P

Any feedback on the upgrades? Or are they downgrades? The totally circular style did have some fun aesthetic benefits.

Also, I'd totally love to put Lottie's icons on the boxes once I get the access/files! :)

**Comment by mariusandra** [comment]
The scope that's still planned before this PR is ready:
- [x] Actions & Stats info windows
- [x] Actions button mode toggle (now it just opens the dock... which when open on the actions tab shows DOM elements with actions on them --> the toggle in button mode should also show/hide all elements with actions)
- [x] Actions new/edit in button mode (all in same floating thing I guess)
- [x] Add close button to "heatmap" and the other windows
- [x] Sync the look & feel of the dock and button modes (icons, colors, etc)

**Comment by timgl** [comment]
I suggest we don't needs Actions & Stats to get this out before the next release right?

**Comment by mariusandra** [comment]
This is now ready to be reviewed!
There's still a lot to improve with the interactivity and design, but basically everything that should be there is there... and everything should work, works.

**Review by timgl — APPROVED** [review]
Looks awesome!

**Pull request merged**
