### PR TITLE
fix: update monaco editor

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We had several reports of shared/embedded things being a blank white screen.

Bisecting showed it started with this PR https://github.com/PostHog/posthog/pull/15957

Viewing shared or embedded previews or directly via their URL did show a white page and the console had the error 

`Cannot read properties of undefined (reading 'ENABLE_VSCODE_BROWSER_CODE_LOADING'` from monaco

## Changes

Updating the version of monaco and monaco react seems to fix it so 🤷 

## How did you test this code?

updating and installing monaco and seeing embeds and shared work again

### CODE REVIEW

**Comment by pauldambra** [comment]
reported

 * slack: https://posthog.slack.com/archives/C04J1TJ11UZ/p1686512285999949
 * zendesk:   https://posthoghelp.zendesk.com/agent/tickets/3512 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/6562)
 * zendesk: https://posthoghelp.zendesk.com/agent/tickets/3516 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/6308)

**Review by benjackwhite — APPROVED** [review]
Looks good. Ran it locally and clicked around with everything looking correct 👍

**Comment by thmsobrmlr** [comment]
Going to merge this in since we have a couple of requests related to this issue.

**Comment by thmsobrmlr** [comment]
Thanks for the fix @pauldambra! Works like a charm now.

**Pull request merged**
