### PR TITLE
Rename dashboarditem to insight

### PR DESCRIPTION
**Pull request by timgl**
## Changes

 It'd be good to reduce confusion/cognitive overhead around the difference between insights and dashboard items.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

**Review by EDsCODE — COMMENTED** [review]
Generally looks good. There are a few more references of `dashboard_item` in variable names and constants that could be changed in `update_cache.py`, `celery.py`, and `settings.py`

Also, worth adding a ticket or follow up PR adjusting the variables on the frontend that use dashboarditemId

**Comment by EDsCODE** [comment]
On second thought it wouldn't be good to change env var names at the moment so this looks good to go

**Comment by Twixes** [comment]
Oof, lots of merge conflicts now. Why didn't we merge this?

**Comment by timgl** [comment]
@Twixes Li was doing some new stuff so was waiting for that to go in... and then forgot. I might just start from scratch here as all I did was search + replace

**Pull request closed without merging**
