### PR TITLE
Add link to plugin troubleshooting if server offline

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

Adds a link to the plugin troubleshooting page if the server is offline

Screenshot 2021-01-13 at 22 53 00

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Review by Twixes — COMMENTED** [review]
Good idea, though I'm a bit unsure about the phrasing "Why could this be?"

**Comment by mariusandra** [comment]
Not sure either. Probably good enough?

**Comment by mariusandra** [comment]
@paolodamico - should we add some `utm_source` style instrumentation to this link?

**Review by Twixes — APPROVED** [review]
Should be alright this way. Set up a PostHog action https://app.posthog.com/action/3492 to track this.

**Pull request merged**
